window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"almond-oil",cat:"fats",name:{en:"Almond oil",fr:"Huile d’amande"},latin:"Prunus dulcis",
origin:{en:"Mediterranean almond groves",fr:"Amandaies méditerranéennes"},season:[],
flavor:["nutty","sweet","delicate"],
story:{en:"For most of its history sweet almond oil was sold by pharmacists rather than grocers, pressed for skin and for infants long before it came back into the kitchen. It is not to be confused with bitter almond oil, which is a distillate, is used by the drop, and carries the almond smell that is really benzaldehyde.",
fr:"Pendant l’essentiel de son histoire, l’huile d’amande douce s’est vendue en pharmacie plutôt qu’en épicerie, pressée pour la peau et pour les nourrissons bien avant de revenir en cuisine. À ne pas confondre avec l’huile d’amande amère, qui est un distillat, s’emploie à la goutte et porte cette odeur d’amande qui est en réalité du benzaldéhyde."},
tip:{en:"It burns low and turns rancid fast, so buy small, keep it cold and use it raw. Replace a fifth of the butter with it in a pastry cream, but cut it half and half with a neutral oil in a vinaigrette or it cloys.",
fr:"Elle brûle bas et rancit vite : achetez petit, gardez-la au froid, employez-la crue. Remplacez un cinquième du beurre par elle dans une crème pâtissière, mais coupez-la de moitié avec une huile neutre en vinaigrette, sinon elle écœure."},
pairs:["apricot","peach","trout","white-asparagus","cherry","honey"],
svg:'<path class="f1 sf" d="M44 22h8v12l6 10v26q0 4-4 4H42q-4 0-4-4V44l6-10z"/><path class="s" d="M43 22h10M38 50h20"/><path class="f2 sf" d="M66 54q6 2 6 10t-6 10q-6-2-6-10t6-10z"/><path class="s" d="M66 57v20"/>'},

{id:"argan-oil",cat:"fats",name:{en:"Argan oil",fr:"Huile d’argan"},latin:"Argania spinosa",
origin:{en:"Souss valley, Morocco",fr:"Vallée du Souss, Maroc"},season:[],
flavor:["nutty","toasty","rich","earthy"],
story:{en:"The tree grows nowhere but southwestern Morocco, and the kernels are still cracked by hand between two stones because no machine has managed it. Berber women's cooperatives control most of the production, which is unusual and deliberate.",
fr:"L’arganier ne pousse qu’au sud-ouest du Maroc, et les amandons se concassent encore à la main entre deux pierres, aucune machine n’y étant parvenue. Des coopératives de femmes berbères contrôlent l’essentiel de la production, ce qui est rare et voulu."},
tip:{en:"The culinary version is pressed from roasted kernels and is darker. The cosmetic one is raw, paler, and tastes of very little.",
fr:"La version culinaire est pressée d’amandons torréfiés et plus foncée. La cosmétique est crue, plus claire, et n’a presque aucun goût."},
pairs:["almond","honey","flour-t65","cumin","lemon","olive","orange","chickpeas"],
svg:'<path class="f1 sf" d="M42 76V46h12v30z"/><path class="s" d="M42 54h12"/><path class="f2 sf" d="M44 42q-6-8 4-12t4 12z"/>'},

{id:"avocado-oil",cat:"fats",name:{en:"Avocado oil",fr:"Huile d’avocat"},latin:"Persea americana",
origin:{en:"Mexico & New Zealand",fr:"Mexique & Nouvelle-Zélande"},season:[],
flavor:["mild","grassy","buttery","fresh"],
story:{en:"Pressed from the flesh rather than a seed, which makes it one of the very few fruit oils alongside olive and palm. It also has one of the highest smoke points of any unrefined oil, which is unusual for something pressed cold.",
fr:"Pressée de la chair plutôt que d’une graine, ce qui en fait l’une des très rares huiles de fruit avec l’olive et le palme. Elle possède aussi l’un des points de fumée les plus élevés parmi les huiles non raffinées, chose rare pour un pressage à froid."},
tip:{en:"It takes a hard sear without smoking, so use it where you want high heat but a clean, buttery background.",
fr:"Elle supporte une saisie vive sans fumer : employez-la quand vous voulez une forte chaleur avec un fond net et beurré."},
pairs:["lime","cilantro","tomato","chili","black-pepper","avocado","red-onion","lemon"],
svg:'<path class="f3 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f2 sf" d="M48 26q6 4 6 10t-6 8-6-8 6-10z"/>'},

{id:"beeswax",cat:"fats",name:{en:"Beeswax",fr:"Cire d’abeille"},latin:"Cera alba",
origin:{en:"Honeycomb cappings",fr:"Opercules de rayon"},season:[],
flavor:["honeyed","warm","delicate"],
story:{en:"A colony eats something like six to eight kilos of honey to secrete a single kilo of wax, which makes comb the most expensive material in the hive. Kitchens came to it late, for a prosaic reason: beeswax melts at 62-65C, which happens to be poaching temperature.",
fr:"Une colonie consomme six à huit kilos de miel pour sécréter un seul kilo de cire : le rayon est la matière la plus chère de la ruche. La cuisine s’en est emparée tard, pour une raison prosaïque — la cire fond entre 62 et 65 °C, soit exactement une température de pochage."},
tip:{en:"Hold the bath at 65-70C and slide in fish or root vegetables for eight to ten minutes; above 85C the wax darkens and is spent. Strain it back into a jar and reuse it - a single drop of water ruins the batch.",
fr:"Maintenez le bain entre 65 et 70 °C et plongez-y poisson ou légumes racines huit à dix minutes ; au-delà de 85 °C la cire brunit et devient inutilisable. Filtrez-la, elle se réemploie — une seule goutte d’eau suffit à la perdre."},
pairs:["honey","butter","carrot","scallop","cream","apricot"],
svg:'<path class="f2 sf" d="M32 24h32l14 26-14 26H32L18 50z"/><path class="s" d="M40 38h12l6 12-6 12H40l-6-12z"/><path class="s" d="M52 26l6 12M40 62l-6 12"/>'},

{id:"camelina-oil",cat:"fats",name:{en:"Camelina oil",fr:"Huile de cameline"},latin:"Camelina sativa",
origin:{en:"Northern European flax fields",fr:"Champs de lin du nord de l’Europe"},season:[],
flavor:["grassy","fresh","nutty"],
story:{en:"Camelina, gold-of-pleasure, was a staple oilseed across Bronze Age Europe — its seeds turn up in the stomachs of the Danish bog bodies — then vanished when rapeseed and sunflower took the fields. It came back in France in the 1990s because it wants almost no water and no treatment, and cooks found it tasted of raw peas.",
fr:"La cameline, ou sésame d’Allemagne, était un oléagineux courant dans l’Europe de l’âge du bronze — on en a retrouvé les graines jusque dans l’estomac des corps des tourbières danoises — avant de disparaître devant le colza et le tournesol. Elle est revenue en France dans les années 1990 parce qu’elle ne demande presque ni eau ni traitement, et les cuisiniers ont découvert qu’elle avait le goût du petit pois cru."},
tip:{en:"Never heat it: the perfume is gone above 60 °C and its fats turn quickly. Raw on white asparagus, smoked herring or a warm potato salad, count one spoon of camelina to two of a neutral oil so it does not take the whole dish.",
fr:"Ne la chauffez jamais : son parfum s’en va au-delà de 60 °C et ses acides gras tournent vite. Crue sur l’asperge blanche, le hareng fumé ou une salade de pommes de terre tièdes, comptez une cuillère de cameline pour deux d’huile neutre afin qu’elle ne prenne pas toute la place."},
pairs:["white-asparagus","potato","saumon-fume","herring","pea","fromage-blanc"],
svg:'<path class="f2 sf" d="M42 24h12v14l12 22q3 6-3 10H33q-6-4-3-10l12-22z"/><path class="s" d="M40 24h16"/><path class="f1" d="M36 54h24l6 10H30z"/><path class="s" d="M74 30q-8 14-6 32"/><circle class="f1 sf" cx="74" cy="38" r="3"/><circle class="f1 sf" cx="70" cy="50" r="3"/>'},

{id:"caul-fat",cat:"fats",name:{en:"Caul fat",fr:"Crépine"},latin:"Sus scrofa domesticus",
origin:{en:"Pig, the membrane over the stomach",fr:"Porc, la membrane de l’estomac"},season:[],
flavor:["rich","meaty","mild"],
story:{en:"Crépine is the omentum, the fat-laced membrane that hangs over a pig's stomach; one animal yields a single sheet, which is why butchers ration it. English and French both borrow the word from birth — the caul, la coiffe, that some babies arrive wearing, once sold to sailors as insurance against drowning.",
fr:"La crépine est l’épiploon, la membrane veinée de gras qui tombe sur l’estomac du porc ; une bête n’en donne qu’une seule pièce, ce qui explique que les bouchers la rationnent. Le français comme l’anglais empruntent le mot à la naissance — la coiffe que certains enfants portent en venant au monde, jadis vendue aux marins comme assurance contre la noyade."},
tip:{en:"Soak it in tepid water, sharpened with a splash of vinegar if it is heavily salted, until it unfolds by itself — pull at it cold and it tears. Wrap in one layer only: two and the fat cannot all render, and you get a greasy skin instead of a crisp one.",
fr:"Faites-la tremper à l’eau tiède, vinaigrée si elle est très salée, jusqu’à ce qu’elle se déplie seule : tirée à froid, elle se déchire. Une seule épaisseur suffit, deux et le gras ne peut pas fondre entièrement, vous obtenez une peau grasse au lieu d’une croûte."},
pairs:["pork","lamb","foie-de-volaille","sage","parsley","prune"],
svg:'<path class="f1 sf" d="M22 40q10-12 26-10t26 10q4 16-6 26-12 12-26 8T20 58q-2-10 2-18z"/><path class="s" d="M26 42q10 6 22 2t22 4M24 56q12 8 24 2t22 4M32 70q8 6 16 2t14 2"/><path class="s" d="M34 32q2 16 6 34M50 30q0 18 2 36M64 34q-2 16-4 32"/><circle class="dot" cx="40" cy="50" r="1.6"/><circle class="dot" cx="58" cy="58" r="1.6"/>'},

{id:"clarified-butter",cat:"fats",name:{en:"Clarified butter",fr:"Beurre clarifié"},latin:"Butyrum clarificatum",
origin:{en:"France",fr:"France"},season:[],
flavor:["buttery","rich","delicate","mild"],
story:{en:"Butter burns at around 150°C because of its milk solids, not its fat. Remove them and the same fat will take 250°C — which is why every classical French kitchen keeps a pot of it beside the stove for searing.",
fr:"Le beurre brûle vers 150 °C à cause de ses solides du lait, non de sa matière grasse. Ôtez-les et la même graisse tient 250 °C — d’où le pot que toute cuisine classique française garde près du fourneau pour saisir."},
tip:{en:"Melt gently and do not let it colour — that is the difference from ghee. Skim the foam, pour off the gold, leave the milky base.",
fr:"Fondez doucement sans laisser colorer — c’est ce qui le distingue du ghee. Écumez la mousse, versez l’or, laissez le fond laiteux."},
pairs:["shallot","lemon","thyme","garlic","scallop","black-pepper","parsley","turbot"],
svg:'<path class="f3 sf" d="M36 72V48q12-5 24 0v24z"/><path class="s" d="M36 48q12 5 24 0M36 58h24"/>'},

{id:"cocoa-butter",cat:"fats",name:{en:"Cocoa butter",fr:"Beurre de cacao"},latin:"Theobroma cacao",
origin:{en:"Cacao pod, the pressed fat",fr:"Cabosse de cacao, la matière grasse pressée"},season:[],
flavor:["buttery","mild","creamy"],
story:{en:"Van Houten built his press in 1828 to obtain cocoa powder; the fat that came out was the by-product, and it took another fifteen years before anyone thought to put it back and make chocolate you could bite. It sets in six different crystal forms and only one of them, the fifth, gives gloss and a snap.",
fr:"Van Houten a construit sa presse en 1828 pour obtenir de la poudre de cacao ; le beurre qui en sortait n’était qu’un sous-produit, et il a fallu une quinzaine d’années avant que quelqu’un pense à le remettre dedans pour faire du chocolat que l’on croque. Il cristallise sous six formes et une seule, la cinquième, donne le brillant et la casse."},
tip:{en:"Melt it no higher than 45 °C, take it down to about 27 °C, then bring it back to 31–32 °C before use; skip that and it sets dull and greys over within a day. A spoonful thinned into melted chocolate makes it flow for coating without sweetening it.",
fr:"Fondez-le à 45 °C au plus, descendez vers 27 °C, puis remontez à 31-32 °C avant emploi : sans cela, il se fige terne et se marbre de gris en un jour. Une cuillerée dans du chocolat fondu le rend assez fluide pour enrober sans le sucrer."},
pairs:["dark-chocolate","cocoa-nibs","vanilla","hazelnut","pistachio","coffee"],
svg:'<path class="f2 sf" d="M26 38h44v26H26z"/><path class="f1 sf" d="M26 38l8-8h44l-8 8z"/><path class="f3 sf" d="M70 38l8-8v26l-8 8z"/><path class="s" d="M40 44v14M56 44v14"/><path class="s" d="M30 76q8-6 16-2t16-4"/>'},

{id:"coconut-oil",cat:"fats",name:{en:"Coconut oil",fr:"Huile de coco"},latin:"Cocos nucifera",
origin:{en:"Indo-Pacific",fr:"Indo-Pacifique"},season:[],
flavor:["sweet","nutty","creamy","mild"],
story:{en:"Almost uniquely among plant fats it is solid at room temperature, because it is overwhelmingly saturated — which is also why it keeps for years without turning. Kerala and Sri Lanka have cooked in nothing else for centuries.",
fr:"Presque unique parmi les graisses végétales, elle est solide à température ambiante parce qu’elle est massivement saturée — ce qui explique aussi qu’elle se garde des années sans rancir. Le Kerala et le Sri Lanka n’ont cuisiné qu’avec elle pendant des siècles."},
tip:{en:"Virgin coconut oil tastes strongly of coconut; the refined version tastes of nothing. Choose deliberately, they are not interchangeable.",
fr:"L’huile vierge a un goût marqué de coco ; la raffinée n’a aucun goût. Choisissez sciemment, elles ne sont pas interchangeables."},
pairs:["chili","lime","ginger","turmeric","cilantro","coconut-milk","curry-leaf","garlic"],
svg:'<path class="f3 sf" d="M36 74V46h24v28z"/><path class="s" d="M36 54h24"/><circle class="f1 sf" cx="48" cy="34" r="8"/><circle class="dot" cx="45" cy="32" r="1.6"/><circle class="dot" cx="51" cy="32" r="1.6"/>'},

{id:"flaxseed-oil",cat:"fats",name:{en:"Cold-pressed flaxseed oil",fr:"Huile de lin"},latin:"Linum usitatissimum",
origin:{en:"Northern and Eastern Europe",fr:"Europe du Nord et de l’Est"},season:[],
flavor:["bitter","grassy","nutty"],
story:{en:"The same oil that dries hard into paint and linoleum is eaten raw in Germany and Russia: Spreewald quark with linseed oil and potatoes is a regional dish, not a health fad. It dries because its fat is triply unsaturated, which is also why it turns bitter within weeks of pressing and is never sold in a clear bottle.",
fr:"L’huile qui sèche en peinture et en linoléum se mange crue en Allemagne et en Russie : le fromage blanc du Spreewald à l’huile de lin et pommes de terre est un plat régional, pas une lubie diététique. Elle sèche parce que ses acides gras sont trois fois insaturés, ce qui explique aussi qu’elle devienne amère quelques semaines après le pressage et ne se vende jamais en bouteille claire."},
tip:{en:"Buy the smallest bottle that carries a pressing date, keep it in the fridge, finish it in six weeks and never bring it near a pan. Serve it cold over quark, boiled potatoes or a beetroot salad — if it smells of fish or paint it has oxidised, and it goes out.",
fr:"Achetez le plus petit flacon portant une date de pressage, gardez-le au réfrigérateur, finissez-le en six semaines et ne l’approchez jamais d’une poêle. Servez-la froide sur du fromage blanc, des pommes de terre à l’eau ou une salade de betterave ; si elle sent le poisson ou la peinture, elle est oxydée, jetez-la."},
pairs:["potato","fromage-blanc","beetroot","chives","yogurt","rye"],
svg:'<path class="f3 sf" d="M42 30h12v10l4 8v26q0 4-4 4H42q-4 0-4-4V48l4-8z"/><path class="s" d="M40 30h16v-6H40z"/><path class="s" d="M38 56h20"/><path class="f1 sf" d="M70 34q5 4 0 8-5-4 0-8zM78 42q-4 5-8 0 4-5 8 0zM70 50q-5-4 0-8 5 4 0 8zM62 42q4-5 8 0-4 5-8 0z"/><circle class="dot" cx="70" cy="42" r="2"/>'},

{id:"duck-fat",cat:"fats",name:{en:"Duck fat",fr:"Graisse de canard"},latin:"Adeps anatis",
origin:{en:"Southwest France",fr:"Sud-Ouest de la France"},season:[],
flavor:["rich","meaty","earthy","umami"],
story:{en:"Confit exists because of it: submerge a leg in rendered fat, cook it slowly and store it under the set fat, and it keeps for months without refrigeration. The fat is the preservative, the cooking medium and the seal all at once.",
fr:"Le confit existe grâce à elle : immerger une cuisse dans la graisse fondue, la cuire lentement et la conserver sous la graisse figée, et elle se garde des mois sans froid. La graisse est à la fois conservateur, milieu de cuisson et opercule."},
tip:{en:"Nothing makes a better roast potato. Get it smoking hot before the potatoes go in, or they absorb it instead of frying.",
fr:"Rien ne réussit mieux les pommes de terre rôties. Faites-la fumer avant d’y jeter les pommes de terre, sinon elles l’absorbent au lieu de frire."},
pairs:["potato","garlic","thyme","duck","black-pepper","onion","white-beans","bay-leaf"],
svg:'<path class="f2 sf" d="M34 72V48q14-6 28 0v24z"/><path class="s" d="M34 48q14 6 28 0"/><path class="s" d="M40 60q8 4 16 0"/>'},

{id:"fatback",cat:"fats",name:{en:"Fatback (green back fat)",fr:"Bardière (lard gras)"},latin:"Sus scrofa domesticus",
origin:{en:"The pig's back, uncured",fr:"Le dos du porc, non salé"},season:[],
flavor:["rich","mild","meaty"],
story:{en:"Bardière is the hard fat from along the spine, firmer than belly fat because it holds less water and more stearic acid — the only pork fat that keeps a clean dice at room temperature. Old breeds were selected for it, a Mangalitza or a Bigorre pig carrying it a hand deep, and that is exactly what industrial breeding took back out.",
fr:"La bardière est le gras dur du long de l’échine, plus ferme que celui de poitrine parce qu’il tient moins d’eau et plus d’acide stéarique : c’est le seul gras de porc qui garde un dé net à température ambiante. Les races anciennes étaient sélectionnées pour lui — un mangalitza ou un noir de Bigorre en porte l’épaisseur d’une main — et c’est exactement ce que l’élevage industriel a fait disparaître."},
tip:{en:"Give it half an hour in the freezer before cutting: warm, it smears and turns a farce greasy instead of binding it. In a pâté count a third fat to two thirds lean by weight, and keep everything, bowl included, below 12 °C while you work.",
fr:"Passez-la une demi-heure au congélateur avant de la tailler : tiède, elle s’écrase et rend une farce grasse au lieu de la lier. Dans un pâté, comptez un tiers de gras pour deux tiers de maigre au poids, et gardez tout, cul-de-poule compris, sous 12 °C."},
pairs:["pork","foie-de-volaille","thyme","juniper","cognac","pigeon"],
svg:'<path class="f1 sf" d="M22 46q26-10 52 0v16q-26 10-52 0z"/><path class="f3 sf" d="M22 46q26-10 52 0-1 5-3 5-23-8-46 0-2 0-3-5z"/><path class="f2 sf" d="M26 70q22-8 44 0-22 8-44 0z"/><path class="s" d="M36 56q12-4 24 0"/>'},

{id:"ghee",cat:"fats",name:{en:"Ghee",fr:"Ghee"},latin:"Butyrum depuratum",
origin:{en:"India",fr:"Inde"},season:[],
flavor:["nutty","rich","toasty","buttery"],
story:{en:"Butter simmered until the water boils off and the milk solids brown at the bottom, then strained — which removes everything that would spoil. In a climate without refrigeration it keeps for a year, and Vedic texts treat it as sacred.",
fr:"Du beurre mijoté jusqu’à évaporation de l’eau et coloration des solides du lait au fond, puis filtré — ce qui ôte tout ce qui pourrait tourner. Sous un climat sans réfrigération il se garde un an, et les textes védiques le tiennent pour sacré."},
tip:{en:"Let the solids brown, do not just melt the butter. That browning is the difference between ghee and clarified butter.",
fr:"Laissez colorer les solides, ne vous contentez pas de fondre le beurre. Cette coloration fait toute la différence avec un beurre clarifié."},
pairs:["cumin","turmeric","cardamom","garlic","ginger","rice","curry-leaf","chili"],
svg:'<path class="f2 sf" d="M36 72V46q12-6 24 0v26z"/><path class="s" d="M36 46q12 6 24 0"/><circle class="dot" cx="44" cy="60" r="2"/><circle class="dot" cx="53" cy="64" r="2"/>'},

{id:"graisse-doie",cat:"fats",name:{en:"Goose fat",fr:"graisse d’oie"},latin:"Anser anser (rendered fat)",
origin:{en:"South-West France",fr:"Sud-Ouest de la France"},season:[],
flavor:["rich","mild","buttery"],
story:{en:"Goose fat sets harder and melts higher than duck fat, a few degrees of difference that decide everything: it seals a confit crock more reliably and holds around 190 °C in a pan without breaking down. Central Europe and the South-West both built their winter cooking on it because a goose yields far more of it than a duck.",
fr:"La graisse d’oie fige plus dur et fond plus haut que celle de canard, quelques degrés d’écart qui décident de tout : elle scelle mieux un pot de confit et tient autour de 190 °C sans se dégrader. L’Europe centrale et le Sud-Ouest ont bâti leur cuisine d’hiver dessus parce qu’une oie en donne bien davantage qu’un canard."},
tip:{en:"Par-boil the potatoes, dry them completely, then drop them into fat already at 180 °C — wet potatoes and cold fat each give you a soft crust. A tablespoon per person is plenty; more and they poach.",
fr:"Précuisez les pommes de terre à l’eau, séchez-les complètement, puis jetez-les dans la graisse déjà à 180 °C : pommes humides et graisse froide donnent l’une comme l’autre une croûte molle. Une cuillère à soupe par personne suffit — au-delà, elles pochent."},
pairs:["potato","garlic","thyme","white-beans","cabbage","onion"],
svg:'<path class="f2 sf" d="M28 30h40v8H28z"/><path class="f1 sf" d="M30 38h36v30a6 6 0 0 1-6 6H36a6 6 0 0 1-6-6z"/><path class="s" d="M36 50q12 5 24 0M36 60q12 5 24 0"/><path class="s" d="M60 30l8-8"/><ellipse class="f2 sf" cx="71" cy="19" rx="5" ry="4"/>'},

{id:"grapeseed-oil",cat:"fats",name:{en:"Grapeseed oil",fr:"Huile de pépins de raisin"},latin:"Vitis vinifera",
origin:{en:"Wine regions of Europe",fr:"Régions viticoles d’Europe"},season:[],
flavor:["mild","delicate","fresh","grassy"],
story:{en:"A by-product of winemaking — the pomace left after pressing holds seeds that would otherwise be waste, and it takes roughly forty kilos of grapes to yield a single litre. Nothing in a vineyard is thrown away twice.",
fr:"Un sous-produit de la vinification — le marc laissé après pressage contient des pépins qui seraient sinon perdus, et il faut environ quarante kilos de raisin pour un seul litre. Rien dans une vigne ne se jette deux fois."},
tip:{en:"Its very high smoke point and clean taste make it the right oil for mayonnaise and for searing, where olive oil would dominate.",
fr:"Son point de fumée très élevé et son goût net en font l’huile juste pour la mayonnaise et les saisies, là où l’olive dominerait."},
pairs:["lemon","egg","mustard","garlic","black-pepper","thyme","shallot","white-wine-vinegar"],
svg:'<path class="f3 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="dot" cx="44" cy="62" r="2"/><circle class="dot" cx="52" cy="66" r="2"/>'},

{id:"hazelnut-oil",cat:"fats",name:{en:"Hazelnut oil",fr:"Huile de noisette"},latin:"Corylus avellana",
origin:{en:"Piedmont & southwest France",fr:"Piémont & Sud-Ouest de la France"},season:[],
flavor:["nutty","toasty","rich","sweet"],
story:{en:"Sweeter and rounder than walnut oil, and rarer, because hazelnuts give less oil for the same weight. Piedmont uses it where Provence would reach for olive, and it turns a plain green salad into something that tastes cooked.",
fr:"Plus douce et plus ronde que l’huile de noix, et plus rare, la noisette rendant moins d’huile à poids égal. Le Piémont l’emploie là où la Provence prendrait l’olive, et elle transforme une simple salade verte en quelque chose qui a l’air cuisiné."},
tip:{en:"A teaspoon at the end of a soup or a purée does more than a whole spoonful of butter. Add it off the heat.",
fr:"Une cuillère à café en fin de soupe ou de purée fait plus qu’une cuillerée de beurre. Ajoutez-la hors du feu."},
pairs:["hazelnut","mache","goat-cheese","pear","sherry-vinegar","apple","beetroot","comte"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="f1 sf" cx="48" cy="34" r="7"/><path class="s" d="M44 30q4-4 8 0"/>'},

{id:"hemp-oil",cat:"fats",name:{en:"Hemp oil",fr:"Huile de chanvre"},latin:"Cannabis sativa",
origin:{en:"Northern France & Canada",fr:"Nord de la France & Canada"},season:[],
flavor:["grassy","nutty","bitter"],
story:{en:"France grows more industrial hemp than any other country in Europe, most of it for paper and insulation; the seed oil is the by-product that found its way into kitchens. Its green is chlorophyll, which is also why a bottle left in the light fades and turns fishy.",
fr:"La France cultive plus de chanvre industriel que tout autre pays d’Europe, l’essentiel pour le papier et l’isolation ; l’huile de graine en est le sous-produit passé en cuisine. Son vert vient de la chlorophylle, ce qui explique aussi qu’une bouteille laissée à la lumière pâlisse et tourne au poisson."},
tip:{en:"Never heat it — it breaks down below 165 °C. Keep it in the fridge and finish the bottle within three months of opening; past that it tastes of fish.",
fr:"Ne la chauffez jamais : elle se dégrade en dessous de 165 °C. Gardez-la au réfrigérateur et finissez la bouteille dans les trois mois suivant l’ouverture, au-delà elle a un goût de poisson."},
pairs:["goat-cheese","tomato","beetroot","walnut","yogurt","potato","lemon"],
svg:'<path class="f3 sf" d="M44 20h8v14l6 10v30q0 4-4 4H42q-4 0-4-4V44l6-10z"/><path class="s" d="M38 56h20"/><path class="f2 sf" d="M62 24q-3 9 0 15 3-6 0-15zM62 30q-8 3-8 11 8-2 8-11zM62 30q8 3 8 11-8-2-8-11z"/>'},

{id:"iberico-lard",cat:"fats",name:{en:"Ibérico lard (manteca ibérica)",fr:"Saindoux ibérique (manteca ibérica)"},latin:"Sus scrofa domesticus",
origin:{en:"Extremadura & Andalusia, Spain",fr:"Estrémadure & Andalousie, Espagne"},season:[],
flavor:["rich","nutty","meaty"],
story:{en:"Acorns are so heavy in oleic acid that Extremadura calls the pigs that eat them olive trees on four legs, and the fat takes on the same chemistry. Rendered, it sets to a spreadable cream instead of the hard white block ordinary lard makes.",
fr:"Le gland est si riche en acide oléique qu’en Estrémadure on appelle les porcs qui s’en nourrissent des oliviers sur pattes, et la graisse en reprend la chimie. Fondue, elle prend en crème tartinable au lieu du bloc blanc et dur du saindoux ordinaire."},
tip:{en:"Use it where the pork flavour has to survive: roast potatoes, or spread thin on toast with salt. Above 180 °C the aroma burns off and you have paid for nothing.",
fr:"Employez-la là où le goût du porc doit rester : pommes de terre rôties, ou étalée fine sur du pain grillé avec du sel. Au-delà de 180 °C son arôme part et vous avez payé pour rien."},
pairs:["potato","garlic","pimenton-de-la-vera","rosemary","white-beans","chickpeas","onion"],
svg:'<path class="f1 sf" d="M30 46h36v22q0 6-8 6H38q-8 0-8-6z"/><path class="f3 sf" d="M28 40h40v6H28z"/><path class="s" d="M40 58q8 4 16 0"/><path class="f2 sf" d="M56 22l6 4-14 14-4-2z"/>'},

{id:"laminating-butter",cat:"fats",name:{en:"Laminating butter (dry butter, 84%)",fr:"Beurre de tourage (beurre sec)"},latin:"Butyrum siccum",
origin:{en:"Charentes-Poitou, France",fr:"Charentes-Poitou, France"},season:[],
flavor:["buttery","rich","milky"],
story:{en:"Ordinary butter cracks when cold and leaks when warm; laminating butter is churned and worked so its fat crystals stay plastic across roughly 14 to 18 °C, the window a croissant is folded in. Three letter folds turn one sheet of it into twenty-seven, each thinner than a page.",
fr:"Le beurre ordinaire casse au froid et rend de l’eau au chaud ; le beurre de tourage est baratté et malaxé pour que ses cristaux gras restent plastiques entre 14 et 18 °C environ, la fenêtre du tourage. Trois tours simples transforment une plaque en vingt-sept, chacune plus mince qu’une page."},
tip:{en:"Butter and dough must be equally firm when you roll — if the butter is harder it shatters into shards and the layers weld shut. Bring both to about 14 °C and rest the dough 30 minutes between turns.",
fr:"Le beurre et la détrempe doivent avoir la même fermeté au moment d’abaisser : si le beurre est plus dur, il se brise en éclats et les feuillets se soudent. Amenez les deux vers 14 °C et laissez 30 minutes de repos entre les tours."},
pairs:["flour-t45","flour-t55","yeast","sugar","egg","dark-chocolate","cream"],
svg:'<path class="f1 sf" d="M24 44h48v26H24z"/><path class="f2 sf" d="M24 44l8-8h48l-8 8z"/><path class="f2 sf" d="M72 44l8-8v26l-8 8z"/><path class="s" d="M24 52h48M24 60h48"/>'},

{id:"lard",cat:"fats",name:{en:"Lard",fr:"Saindoux"},latin:"Adeps suillus",
origin:{en:"Europe & China",fr:"Europe & Chine"},season:[],
flavor:["rich","meaty","mild","creamy"],
story:{en:"Its large fat crystals coat flour particles better than butter does, which is why lard pastry is flakier than any other and why it dominated baking until vegetable shortening arrived and marketing pushed it out.",
fr:"Ses gros cristaux de gras enrobent les particules de farine mieux que le beurre, d’où une pâte au saindoux plus feuilletée que toute autre, et sa domination de la boulangerie jusqu’à l’arrivée des graisses végétales et de leur publicité."},
tip:{en:"Ask for leaf lard, from around the kidneys, if you are baking. The back fat is fine for frying but tastes of pork.",
fr:"Demandez la panne, prise autour des rognons, si vous pâtissez. Le lard dorsal convient à la friture mais garde le goût de porc."},
pairs:["potato","onion","garlic","black-pepper","thyme","cabbage","flour-t65","paprika"],
svg:'<path class="f3 sf" d="M32 70V50h32v20z"/><path class="s" d="M32 58h32"/><path class="s" d="M42 50v20M54 50v20"/>'},

{id:"panne-de-porc",cat:"fats",name:{en:"Leaf lard",fr:"Panne de porc"},latin:"Sus scrofa domesticus (adeps perirenalis)",
origin:{en:"Around the pig’s kidneys",fr:"Autour des rognons du porc"},season:[],
flavor:["mild","creamy","rich"],
story:{en:"Panne is the sheet of fat hanging around the kidneys, and it is not interchangeable with back fat: it renders whiter, firmer and almost without pork flavour, which is why pastry cooks order it by name. Rendered slowly it gives the saindoux that made pie crusts flake long before anyone bought shortening in a tin.",
fr:"La panne est la nappe de gras qui entoure les rognons, et elle ne remplace pas le lard gras : elle fond plus blanche, plus ferme et presque sans goût de porc, ce qui explique que les pâtissiers la commandent par son nom. Fondue doucement, elle donne le saindoux qui faisait feuilleter les pâtes bien avant qu’on achète de la graisse végétale en boîte."},
tip:{en:"Render it low: dice it cold, add a splash of water to the pan and hold it under 110 °C until the water has gone and the pieces float pale gold. Push the heat and it browns — and browned lard tastes of pork forever after, which ruins it for pastry.",
fr:"Fondez-la bas : coupez-la froide en dés, ajoutez un fond d’eau dans la casserole et tenez sous 110 °C jusqu’à ce que l’eau soit partie et que les morceaux flottent, blonds. Poussez le feu et elle colore — et un saindoux coloré garde à jamais le goût de porc, ce qui le condamne en pâtisserie."},
pairs:["flour-t55","salt","apple","sugar","potato","onion","sage","rye-flour"],
svg:'<path class="f1 sf" d="M48 24q18 6 20 26t-20 26q-20-6-20-26t20-26z"/><path class="s" d="M48 26v50"/><path class="s" d="M48 40q-8 4-12 12M48 40q8 4 12 12M48 56q-7 3-10 10M48 56q7 3 10 10"/>'},

{id:"macadamia-oil",cat:"fats",name:{en:"Macadamia oil",fr:"Huile de macadamia"},latin:"Macadamia integrifolia",
origin:{en:"Queensland, Australia",fr:"Queensland, Australie"},season:[],
flavor:["buttery","nutty","creamy"],
story:{en:"The macadamia is the only Australian native to have become a global commercial crop, and most of the world's orchards descend from seed carried to Hawaii in the 1880s. Close to 80% of its fat is monounsaturated, which is why it holds a pan where walnut oil would turn bitter.",
fr:"La macadamia est la seule plante indigène d’Australie devenue une culture commerciale mondiale, et la plupart des vergers descendent de semences emportées à Hawaï dans les années 1880. Près de 80 % de ses acides gras sont mono-insaturés, ce qui lui permet de tenir la poêle là où l’huile de noix tournerait à l’amer."},
tip:{en:"It holds to about 200 °C and will take a gentle sear, but treat it as a seasoning: a spoonful over the fish at the end does more than a panful under it.",
fr:"Elle tient jusqu’à 200 °C environ et supporte une saisie douce, mais traitez-la en assaisonnement : une cuillère sur le poisson en fin de cuisson fait plus qu’une poêlée entière."},
pairs:["macadamia","scallop","lime","sea-bass","avocado","mango","honey"],
svg:'<path class="f1 sf" d="M46 22h4v20q10 6 10 18t-12 14-12-14 10-18z"/><path class="s" d="M38 58h20"/><circle class="f2 sf" cx="68" cy="68" r="8"/><path class="s" d="M60 68q8 5 16 0"/>'},

{id:"mustard-oil",cat:"fats",name:{en:"Mustard oil",fr:"Huile de moutarde"},latin:"Brassica juncea",
origin:{en:"Bengal & Punjab",fr:"Bengale & Pendjab"},season:[],
flavor:["pungent","hot","peppery","nutty"],
story:{en:"In India it is taken to smoking point before anything else goes in the pan — the moment its allyl isothiocyanate breaks down and the raw horseradish burn turns nutty. In the United States and much of Europe it may only be sold labelled for external use, because of its erucic acid content.",
fr:"En Inde, on la mène au point de fumée avant tout le reste — le moment où son isothiocyanate d’allyle se décompose et où la brûlure de raifort tourne au noisette. Aux États-Unis et dans une grande partie de l’Europe, elle ne se vend qu’étiquetée pour usage externe, à cause de sa teneur en acide érucique."},
tip:{en:"Smoke it first, always: take it to the first wisp, cut the heat for thirty seconds, then start the spices. Used raw it overwhelms everything it touches.",
fr:"Fumez-la d’abord, toujours : montez-la jusqu’au premier filet de fumée, coupez le feu trente secondes, puis lancez les épices. Crue, elle écrase tout ce qu’elle touche."},
pairs:["turmeric","nigella","fenugreek","potato","mustard-greens","eggplant","ginger","mackerel"],
svg:'<path class="f2 sf" d="M44 18h8v18l4 6v28q0 4-4 4H40q-4 0-4-4V42l4-6z"/><path class="s" d="M36 54h20"/><path class="f1 sf" d="M68 26q3 0 3 6v18q0 6-3 6t-3-6V32q0-6 3-6z"/><circle class="dot" cx="68" cy="36" r="1.6"/><circle class="dot" cx="68" cy="44" r="1.6"/>'},

{id:"niter-kibbeh",cat:"fats",name:{en:"Niter kibbeh",fr:"Niter kibbeh (beurre clarifié épicé éthiopien)"},latin:"Butyrum aromaticum",
origin:{en:"Ethiopia",fr:"Éthiopie"},season:[],
flavor:["buttery","warm","herbal","rich"],
story:{en:"The butter is simmered rather than merely melted, with korarima, koseret and besobela — three Ethiopian aromatics with no real substitute — until the water has gone and the spices have given their oil up to the fat. What is strained off keeps for months at room temperature, which is the whole point in a kitchen without refrigeration.",
fr:"Le beurre mijote au lieu de simplement fondre, avec du korarima, du koseret et du besobela — trois aromates éthiopiens sans véritable équivalent — jusqu’à ce que l’eau soit partie et que les épices aient cédé leur huile à la graisse. Ce qu’on filtre se garde des mois à température ambiante, ce qui est tout l’intérêt dans une cuisine sans réfrigérateur."},
tip:{en:"Start the wot with it rather than finishing with it — the flavour is fat-soluble and needs those first minutes with the onions. One tablespoon per two onions is the working ratio.",
fr:"Commencez le wot avec, plutôt que de le finir avec : l’arôme est liposoluble et il lui faut les premières minutes avec les oignons. Une cuillère à soupe pour deux oignons est le bon rapport."},
pairs:["berbere","fenugreek","turmeric","ginger","garlic","onion","lentils","cardamom"],
svg:'<path class="f1 sf" d="M28 40h32v18q0 6-6 6H34q-6 0-6-6z"/><path class="s" d="M28 40h32"/><path class="f3 sf" d="M60 44h16v5H60z"/><circle class="dot" cx="38" cy="52" r="2"/><circle class="dot" cx="46" cy="56" r="2"/><circle class="dot" cx="53" cy="50" r="2"/>'},

{id:"olive-oil",cat:"fats",name:{en:"Olive oil",fr:"Huile d’olive"},latin:"Olea europaea",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["fruity","grassy","peppery","bitter"],
story:{en:"Athens is named for a bet: Athena offered the olive tree, Poseidon a salt spring, and the citizens chose the tree. Homer called its oil “liquid gold”; athletes wore it, lamps burned it, and the Mediterranean still cooks in it before anything else.",
fr:"Athènes doit son nom à un pari : Athéna offrit l’olivier, Poséidon une source salée, et les citoyens choisirent l’arbre. Homère appelait son huile « l’or liquide » ; les athlètes s’en oignaient, les lampes la brûlaient, et la Méditerranée cuisine toujours avec elle avant toute chose."},
tip:{en:"The peppery catch in the throat of a young oil is a virtue, not a flaw. Keep a modest oil for the pan and a great one for the final thread over the plate.",
fr:"Le piquant en gorge d’une huile jeune est une vertu, pas un défaut. Gardez une huile modeste pour la poêle et une grande pour le filet final sur l’assiette."},
pairs:["tomato","garlic","lemon","basil","white-beans","cod","eggplant"],
svg:'<path class="f1 sf" d="M44 26h8v10l4 6v30q0 6-8 6t-8-6V42l4-6z"/><path class="s" d="M44 26h8"/><path class="f3 sf" d="M40 66a4 4 0 108 0 4 4 0 10-8 0z" transform="translate(4 0)"/><path class="s" d="M52 62q4-4 8-4"/>'},

{id:"olive-pomace-oil",cat:"fats",name:{en:"Olive pomace oil",fr:"Huile de grignons d’olive"},latin:"Olea europaea",
origin:{en:"Andalusia, Spain",fr:"Andalousie, Espagne"},season:[],
flavor:["mild","delicate"],
story:{en:"Spent olive paste still holds a few percent of its oil after pressing, enough that hexane is sent in after it; refining then strips the colour, the smell and the polyphenols with it. A little virgin oil is blended back at the end so the tin can say olive at all.",
fr:"Le grignon retient encore quelques pour cent d’huile après le pressurage, assez pour qu’on aille la chercher à l’hexane ; le raffinage en retire ensuite la couleur, l’odeur et les polyphénols avec. On y remet un peu d’huile vierge à la fin pour que le bidon puisse porter le mot olive."},
tip:{en:"It holds 220 °C without breaking down, which is why Spanish kitchens fry and confit in it. It brings no flavour of its own, so never buy it to dress anything.",
fr:"Elle tient 220 °C sans se dégrader, d’où son emploi en friture et en confit dans les cuisines espagnoles. Elle n’apporte aucun goût : n’en assaisonnez jamais rien."},
pairs:["potato","garlic","duck","artichoke","cod","chickpeas","salt","thyme"],
svg:'<path class="f2 sf" d="M28 40h40v34H28z"/><path class="s" d="M28 52h40"/><path class="f3 sf" d="M58 32h8v8h-8z"/><path class="s" d="M36 40q4-10 14-10"/>'},

{id:"peanut-oil",cat:"fats",name:{en:"Peanut oil",fr:"Huile d’arachide"},latin:"Arachis hypogaea",
origin:{en:"South America, via West Africa",fr:"Amérique du Sud, via l’Afrique de l’Ouest"},season:[],
flavor:["mild","nutty","toasty","delicate"],
story:{en:"Its smoke point is high enough that it fries chips twice without breaking down, which is why chip shops and Chinese kitchens both settled on it. Refined, it carries almost none of the protein that triggers nut allergy.",
fr:"Son point de fumée est assez haut pour frire deux fois des frites sans se dégrader, d’où son adoption par les friteries comme par les cuisines chinoises. Raffinée, elle ne porte presque rien de la protéine qui déclenche l’allergie."},
tip:{en:"It can be strained and reused several times for deep frying, which no delicate oil tolerates. Filter it while still warm.",
fr:"Elle se filtre et se réutilise plusieurs fois en friture, ce qu’aucune huile délicate ne tolère. Filtrez-la encore tiède."},
pairs:["chili","garlic","ginger","soy-sauce","spring-onion","potato","peanut","sesame"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f1 sf" d="M42 38q-4-6 0-8t6 2 6-2 0 8-6 2z"/>'},

{id:"perilla-oil",cat:"fats",name:{en:"Perilla oil",fr:"Huile de périlla"},latin:"Perilla frutescens",
origin:{en:"Korea",fr:"Corée"},season:[],
flavor:["nutty","herbal","grassy","rich"],
story:{en:"Pressed from the toasted seed of the plant whose leaves are kkaennip, perilla oil runs about sixty percent alpha-linolenic acid, more than any other common kitchen oil. That is also its weakness: it oxidises within months, which is why a Korean kitchen keeps deulgireum in the fridge and sesame oil in the cupboard.",
fr:"Pressée à partir de la graine grillée de la plante dont les feuilles sont les kkaennip, l’huile de périlla titre environ soixante pour cent d’acide alpha-linolénique, plus qu’aucune autre huile de cuisine courante. C’est aussi sa faiblesse : elle s’oxyde en quelques mois, raison pour laquelle une cuisine coréenne garde le deulgireum au réfrigérateur et l’huile de sésame dans le placard."},
tip:{en:"Use it raw. Brush it over laver sheets before toasting them, or fold it into blanched greens off the heat; if the bottle smells of fish or wet paint, it has turned and nothing rescues it.",
fr:"Employez-la crue. Badigeonnez-en les feuilles d’algue avant de les griller, ou liez-en des légumes blanchis hors du feu ; si la bouteille sent le poisson ou la peinture fraîche, elle est perdue."},
pairs:["kkaennip","nori","spinach","soy-sauce","garlic","rice","gochugaru"],
svg:'<path class="f1 sf" d="M44 22h8v12q10 6 10 18v20a4 4 0 0 1-4 4H38a4 4 0 0 1-4-4V52q0-12 10-18z"/><path class="f2 sf" d="M34 58h28v14a4 4 0 0 1-4 4H38a4 4 0 0 1-4-4z"/><path class="f2 sf" d="M66 24q10 4 8 13t-13 4q-7-8-3-13 3-5 8-4z"/><path class="s" d="M62 40q6-7 11-11"/>'},

{id:"pine-nut-oil",cat:"fats",name:{en:"Pine nut oil",fr:"Huile de pignon de pin"},latin:"Pinus pinea",
origin:{en:"Mediterranean pine forests",fr:"Pinèdes méditerranéennes"},season:[],
flavor:["resinous","nutty","woody","delicate"],
story:{en:"A stone pine cone takes three years on the tree to ripen and gives up its kernels one shell at a time, which is why the oil is sold in bottles the size of a perfume flask. It is one of the few oils with a genuine resin note — the tree's own terpenes come through the press.",
fr:"Une pomme de pin parasol met trois ans à mûrir sur l’arbre et livre ses pignons une coque à la fois, d’où une huile vendue en flacons de la taille d’un parfum. C’est l’une des rares huiles à véritable note résineuse : les terpènes de l’arbre passent au pressoir."},
tip:{en:"Count it in drops and never heat it — a few drops on raw scallop or cured trout is a dose. Refrigerate once open; it turns within weeks.",
fr:"Comptez-la en gouttes et ne la chauffez jamais : quelques gouttes sur une saint-jacques crue ou une truite fumée font une dose. Au frais après ouverture, elle tourne en quelques semaines."},
pairs:["scallop","trout","basil","parmesan","sea-bass","fennel","lemon","ricotta"],
svg:'<path class="f1 sf" d="M40 42h16v28q0 4-4 4h-8q-4 0-4-4z"/><path class="f3 sf" d="M43 30h10v12H43z"/><ellipse class="f2 sf" cx="48" cy="24" rx="6" ry="7"/><path class="s" d="M66 32L58 50M71 38l-11 14M62 30l-2 12"/>'},

{id:"pistachio-oil",cat:"fats",name:{en:"Pistachio oil",fr:"Huile de pistache"},latin:"Pistacia vera",
origin:{en:"Iran & the Mediterranean",fr:"Iran & Méditerranée"},season:[],
flavor:["nutty","toasty","resinous","rich"],
story:{en:"The kernels are roasted before pressing, which is where the depth comes from — pressed raw the oil is thin and grassy. Its green is chlorophyll and does not last: an open bottle fades to khaki in a couple of months, and the flavour goes with the colour.",
fr:"Les amandons sont torréfiés avant pressage, c’est de là que vient la profondeur : pressée crue, l’huile reste maigre et herbacée. Son vert est de la chlorophylle et ne tient pas — une bouteille ouverte vire au kaki en deux mois, et le goût s’en va avec la couleur."},
tip:{en:"Never cook it — past about 120 °C the roast note flattens and turns bitter. In a vinaigrette use one part pistachio oil to two of a neutral oil; alone it is too heavy to coat a leaf.",
fr:"Ne la cuisez pas : au-delà de 120 °C environ, la note torréfiée s’aplatit et devient amère. En vinaigrette, une part d’huile de pistache pour deux d’huile neutre ; seule, elle est trop lourde pour napper une feuille."},
pairs:["pistachio","apricot","raspberry","goat-cheese","white-chocolate","lamb","endive","honey"],
svg:'<path class="f2 sf" d="M44 22h8v14L62 74H34l10-38z"/><path class="s" d="M38 60h20"/><ellipse class="f1 sf" cx="68" cy="44" rx="7" ry="9" transform="rotate(20 68 44)"/><path class="s" d="M62 40q6 6 12 2"/>'},

{id:"couenne",cat:"fats",name:{en:"Pork rind",fr:"Couenne"},latin:"Sus scrofa domesticus (cutis)",
origin:{en:"Lauragais and the cassoulet pot",fr:"Le Lauragais et la cassole"},season:[],
flavor:["rich","meaty","mild"],
story:{en:"Castelnaudary lines the bottom of the cassole with sheets of rind, fat side down, before a single bean goes in: they stop the base catching and dissolve into the gelatine that gives the dish its lip-sticking body. Rind is close to pure collagen, which is why a scrap of it in a stockpot does more for texture than an extra hour of simmering.",
fr:"Castelnaudary tapisse le fond de la cassole de couennes, côté gras dessous, avant le moindre haricot : elles empêchent la base d’attacher et se dissolvent en gélatine, ce qui donne au cassoulet sa tenue collante aux lèvres. La couenne est presque du collagène pur, et c’est pourquoi un morceau dans un bouillon fait plus pour la texture qu’une heure de cuisson supplémentaire."},
tip:{en:"Scrape the underside clean of fat and blanch the sheets ten minutes from cold water before they go in the pot, or they perfume the dish with pig instead of melting quietly. Dried, then fried at 200 °C, they blister into crackling.",
fr:"Grattez le gras du dessous et blanchissez les plaques dix minutes à départ eau froide avant de les mettre au pot, sinon elles parfument le plat de cochon au lieu de fondre discrètement. Séchées puis frites à 200 °C, elles boursouflent en grattons."},
pairs:["haricot-tarbais","garlic","confit-de-canard","onion","bay-leaf","carrot","black-pepper","thyme"],
svg:'<path class="f1 sf" d="M22 38q12-6 26 0t26-4v26q-14 6-26 2t-26 4z"/><path class="s" d="M22 52q12-4 26 0t26-2"/><circle class="dot" cx="36" cy="46" r="1.5"/><circle class="dot" cx="50" cy="50" r="1.5"/><circle class="dot" cx="62" cy="44" r="1.5"/>'},

{id:"pumpkin-seed-oil",cat:"fats",name:{en:"Pumpkin seed oil",fr:"Huile de pépins de courge"},latin:"Cucurbita pepo var. styriaca",
origin:{en:"Styria, Austria",fr:"Styrie, Autriche"},season:[],
flavor:["nutty","toasty","rich","earthy"],
story:{en:"So dark it looks black in the bottle and bright green in a thin film — an optical effect called dichromatism, rare in food. Styria protects it with a European designation, and the seeds come from a squash that grows without a husk.",
fr:"Si sombre qu’elle paraît noire en bouteille et vert vif en film mince — un effet optique appelé dichromatisme, rare en alimentation. La Styrie la protège par une appellation européenne, et les graines viennent d’une courge qui pousse sans coque."},
tip:{en:"Austrians pour it over vanilla ice cream, and it is not a joke — the toasted, salty note against cold cream works.",
fr:"Les Autrichiens la versent sur la glace vanille, et ce n’est pas une plaisanterie — la note grillée et salée contre la crème froide fonctionne."},
pairs:["vanilla","pumpkin","cider-vinegar","potato","cream","honey","walnut","lettuce"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><ellipse class="f3 sf" cx="48" cy="34" rx="6" ry="8"/>'},

{id:"rapeseed-oil",cat:"fats",name:{en:"Rapeseed oil",fr:"Huile de colza"},latin:"Brassica napus",
origin:{en:"Europe",fr:"Europe"},season:[],
flavor:["grassy","nutty","mild","fresh"],
story:{en:"The original plant made an oil too high in erucic acid to eat safely, and it was sold as a machine lubricant. Canadian breeders bred that compound out in the 1970s and renamed the result canola — a new food invented by subtraction.",
fr:"La plante d’origine donnait une huile trop riche en acide érucique pour être consommée sans risque, et on la vendait comme lubrifiant. Des sélectionneurs canadiens éliminèrent ce composé dans les années 1970 et rebaptisèrent le résultat canola — un aliment nouveau créé par soustraction."},
tip:{en:"Buy the cold-pressed version for dressings — it is grassy and bright yellow. The refined one is for heat and nothing else.",
fr:"Prenez la version vierge pour les assaisonnements — herbacée et jaune vif. La raffinée est pour la chaleur, rien d’autre."},
pairs:["mustard","potato","white-wine-vinegar","chives","lemon","black-pepper","shallot","dill"],
svg:'<path class="f2 sf" d="M40 76V42h16v34z"/><path class="s" d="M40 50h16"/><path class="f3 sf" d="M44 38V28h8v10z"/>'},

{id:"raw-milk-butter",cat:"fats",name:{en:"Raw-milk butter",fr:"Beurre cru"},latin:"Butyrum crudum",
origin:{en:"Normandy & Brittany",fr:"Normandie & Bretagne"},season:[],
flavor:["creamy","rich","grassy","milky"],
story:{en:"Colour tells you the season: spring grass is loaded with carotene and the butter comes out deep yellow, while winter butter made on hay is nearly white. Because the cream is never heated the milk's own bacteria stay in the churn, so two farms a valley apart give two different butters.",
fr:"La couleur dit la saison : l’herbe de printemps est chargée de carotène et le beurre sort jaune foncé, tandis qu’un beurre d’hiver au foin est presque blanc. La crème n’étant jamais chauffée, les bactéries du lait restent dans la baratte, et deux fermes d’une même vallée donnent deux beurres différents."},
tip:{en:"Serve it at 16 °C, neither fridge-cold nor soft — it should take the print of a knife. Do not clarify it or fry in it: what you paid for is exactly the part that burns first.",
fr:"Servez-le à 16 °C, ni sortant du froid ni mou : il doit prendre l’empreinte de la lame. Ne le clarifiez pas et ne le faites pas fondre en poêle, ce qui coûte cher est justement ce qui brûle en premier."},
pairs:["radish","anchovy","salt","asparagus","potato","oyster","honey","walnut"],
svg:'<path class="f1 sf" d="M32 66q0-20 16-20t16 20z"/><path class="s" d="M36 58q12-6 24 0M40 50q8-4 16 0"/><path class="f3 sf" d="M26 66h44v6H26z"/>'},

{id:"red-palm-oil",cat:"fats",name:{en:"Red palm oil (dendê)",fr:"Huile de palme rouge (dendê)"},latin:"Elaeis guineensis",
origin:{en:"West Africa & Bahia",fr:"Afrique de l’Ouest & Bahia"},season:[],
flavor:["earthy","rich","warm"],
story:{en:"Unrefined palm oil is the richest natural source of carotene there is, several times a carrot's, which is what makes it orange enough to stain a pot. It crossed the Atlantic with the slave trade and Bahian cooking still runs on it as dendê, while the refined white version — same fruit, no colour, no smell — goes into soap and biscuits.",
fr:"L’huile de palme non raffinée est la source naturelle de carotène la plus riche qui soit, plusieurs fois celle d’une carotte, d’où cet orange qui tache la marmite. Elle a traversé l’Atlantique avec la traite, et la cuisine bahianaise tourne encore au dendê, tandis que la version raffinée — même fruit, sans couleur ni odeur — part au savon et au biscuit."},
tip:{en:"One tablespoon colours and flavours a whole pot; more turns the dish waxy and cloying. It is semi-solid at room temperature, so warm it gently — it does not need a high flame to go liquid.",
fr:"Une cuillère à soupe colore et parfume toute une marmite ; au-delà, le plat devient cireux et écœurant. Elle est semi-solide à température ambiante : réchauffez-la doucement, elle n’a pas besoin d’un feu vif pour redevenir liquide."},
pairs:["okra","shrimp","coconut-milk","chili","onion","cowpea","egusi-seed","cilantro"],
svg:'<path class="f3 sf" d="M48 20q6 0 6 8t-2 10q10 6 10 20t-14 14-14-14 10-20q-4-2-2-10t6-8z"/><path class="s" d="M38 58q18 8 22-4"/><ellipse class="f2 sf" cx="28" cy="66" rx="5" ry="7"/><ellipse class="f2 sf" cx="34" cy="74" rx="5" ry="7"/>'},

{id:"rice-bran-oil",cat:"fats",name:{en:"Rice bran oil",fr:"Huile de son de riz"},latin:"Oryza sativa (bran)",
origin:{en:"Japan & India",fr:"Japon & Inde"},season:[],
flavor:["mild","nutty","delicate"],
story:{en:"Bran is what is stripped from brown rice to make it white - about eight per cent of the grain, and nearly all of its fat, so the oil is a by-product of polishing. It carries gamma-oryzanol, an antioxidant that slows the oil breaking down in a fryer, which is why tempura counters top the pot up rather than empty it.",
fr:"Le son est ce que l’on retire du riz complet pour le rendre blanc : environ huit pour cent du grain, et presque toute sa matière grasse — l’huile est donc un sous-produit du polissage. Elle contient du gamma-oryzanol, un antioxydant qui ralentit sa dégradation en friture, d’où l’habitude des comptoirs à tempura de remettre de l’huile plutôt que de tout changer."},
tip:{en:"Fry tempura at 175-180 °C, with a spoonful of toasted sesame oil per litre for aroma - the sesame flavours without pulling the smoke point down far. It foams very little, so the pot can be filled closer to the rim than with a seed oil.",
fr:"Frire les tempura à 175-180 °C, avec une cuillerée d’huile de sésame grillé par litre pour le parfum : le sésame aromatise sans faire chuter le point de fumée. Elle mousse très peu, on peut donc remplir la casserole plus haut qu’avec une huile de graines."},
pairs:["shrimp","egg","ginger","soy-sauce","sesame-oil","sweet-potato","shiso","rice-flour"],
svg:'<path class="f2 sf" d="M42 30h12v8l6 10v28q0 4-4 4H40q-4 0-4-4V48l6-10z"/><path class="s" d="M36 58h24"/><path class="f2 sf" d="M42 24h12v6H42z"/><ellipse class="f1 sf" cx="70" cy="46" rx="3.5" ry="6" transform="rotate(20 70 46)"/><ellipse class="f1 sf" cx="72" cy="60" rx="3.5" ry="6" transform="rotate(-15 72 60)"/>'},

{id:"schmaltz",cat:"fats",name:{en:"Schmaltz (rendered chicken fat)",fr:"Graisse de poulet (schmaltz)"},latin:"Gallus gallus domesticus (rendered)",
origin:{en:"Ashkenazi Central & Eastern Europe",fr:"Europe centrale & orientale ashkénaze"},season:[],
flavor:["rich","meaty","umami","toasty"],
story:{en:"Where religious law kept lard off the table and butter away from meat, rendered poultry fat was the one cooking fat admitted on both sides of an Ashkenazi kitchen; goose did the work until chicken became the cheaper bird in the twentieth century. The browned skin and onion left in the pan afterwards - gribenes - were the part people actually fought over.",
fr:"Là où la loi religieuse écartait le saindoux de la table et le beurre des plats de viande, la graisse de volaille fondue était la seule matière grasse admise des deux côtés d’une cuisine ashkénaze ; l’oie tint ce rôle jusqu’à ce que le poulet devienne, au XXe siècle, la volaille la moins chère. La peau et l’oignon dorés restés au fond — les gribenes — étaient la vraie récompense."},
tip:{en:"Render skin and fat from cold in a heavy pan with a splash of water and a sliced onion, on the lowest heat, about forty-five minutes. Lift the onion out while it is still amber: let it blacken and the whole jar tastes burnt.",
fr:"Faites fondre peau et gras à froid dans une cocotte épaisse, avec un fond d’eau et un oignon émincé, au plus doux, environ quarante-cinq minutes. Retirez l’oignon tant qu’il est ambré : s’il noircit, tout le pot prend un goût de brûlé."},
pairs:["onion","potato","chicken","foie-de-volaille","egg","parsley","black-pepper","rye-flour"],
svg:'<path class="f1 sf" d="M32 40h32v34q0 4-4 4H36q-4 0-4-4z"/><path class="s" d="M32 56h32"/><path class="f2 sf" d="M30 32h36v8H30z"/><path class="s" d="M42 68a6 6 0 0112 0M45 62a3 3 0 016 0"/>'},

{id:"smen",cat:"fats",name:{en:"Smen (fermented Moroccan butter)",fr:"Smen (beurre fermenté marocain)"},latin:"Butyrum fermentatum",
origin:{en:"Middle Atlas, Morocco",fr:"Moyen Atlas, Maroc"},season:[],
flavor:["pungent","rich","salty","musky"],
story:{en:"Salted butter is packed into an unglazed earthenware jar, sealed and buried, where it ages for months or years; in the Middle Atlas a jar laid down at a daughter's birth is opened at her wedding. What comes out is closer to a washed-rind cheese than to butter, and it is used at that strength.",
fr:"Le beurre salé est tassé dans une jarre de terre non vernissée, scellée puis enfouie, où il vieillit des mois ou des années ; dans le Moyen Atlas, une jarre mise en terre à la naissance d’une fille s’ouvre à son mariage. Ce qui en sort tient davantage du fromage à croûte lavée que du beurre, et s’emploie à cette puissance."},
tip:{en:"Work in grams: a piece the size of an almond seasons a tagine for six, and twice that takes the dish over. Melt it into the couscous or stir it into the sauce at the end, where the aroma survives.",
fr:"Comptez en grammes : un morceau gros comme une amande parfume un tajine pour six, le double le rend immangeable. Faites-le fondre dans la semoule ou incorporez-le à la sauce en fin de cuisson, là où l’arôme tient."},
pairs:["couscous","lamb","saffron","cumin","chickpeas","preserved-lemon","honey","mint"],
svg:'<path class="f3 sf" d="M38 36h20q12 10 12 22t-14 20H40q-14-2-14-20t12-22z"/><path class="s" d="M38 44h20"/><path class="f2 sf" d="M36 28h24v8H36z"/><path class="s" d="M34 32h28"/>'},

{id:"suet",cat:"fats",name:{en:"Suet",fr:"Graisse de rognon"},latin:"Sebum bovis",
origin:{en:"Britain",fr:"Grande-Bretagne"},season:[],
flavor:["rich","meaty","mild","earthy"],
story:{en:"The hard fat from around beef kidneys, and it melts far higher than butter — so in a steamed pudding it stays solid while the flour sets around it, then melts and leaves the batter airy. British puddings depend entirely on that timing.",
fr:"La graisse dure prise autour des rognons de bœuf, dont le point de fusion dépasse largement celui du beurre — dans un pudding vapeur elle reste solide le temps que la farine prenne autour, puis fond et laisse la pâte aérée. Les puddings britanniques reposent entièrement sur ce décalage."},
tip:{en:"It must go in cold and grated, never melted. Warm suet blends into the flour and the whole point is lost.",
fr:"Elle doit entrer froide et râpée, jamais fondue. Tiède, elle se fond dans la farine et tout l’intérêt disparaît."},
pairs:["flour-t65","beef","onion","black-pepper","thyme","raisin","cinnamon","bay-leaf"],
svg:'<path class="f3 sf" d="M34 70V48h28v22z"/><path class="s" d="M40 48v22M48 48v22M56 48v22"/>'},

{id:"sunflower-oil",cat:"fats",name:{en:"Sunflower oil",fr:"Huile de tournesol"},latin:"Helianthus annuus",
origin:{en:"Russia & Ukraine",fr:"Russie & Ukraine"},season:[],
flavor:["mild","nutty","delicate","toasty"],
story:{en:"The Russian Orthodox Church banned most fats during Lent but had never heard of the sunflower, so it escaped the list — and by the nineteenth century Russia was pressing it by the shipload. A loophole created an industry.",
fr:"L’Église orthodoxe russe interdisait la plupart des corps gras pendant le Carême mais ignorait le tournesol, qui échappa donc à la liste — et au XIXe siècle la Russie le pressait par cargaisons entières. Une faille a créé une industrie."},
tip:{en:"Its neutrality and high smoke point make it the default frying oil. Do not use it where you want the fat to taste of something.",
fr:"Sa neutralité et son point de fumée élevé en font l’huile de friture par défaut. Ne l’employez pas là où le gras doit avoir du goût."},
pairs:["potato","egg","onion","garlic","paprika","black-pepper","white-wine-vinegar","mustard"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f3 sf" d="M44 40V30h8v10z"/><circle class="dot" cx="48" cy="62" r="3"/>'},

{id:"sesame-oil",cat:"fats",name:{en:"Toasted sesame oil",fr:"Huile de sésame grillé"},latin:"Sesamum indicum",
origin:{en:"East Asia",fr:"Asie de l’Est"},season:[],
flavor:["nutty","toasty","rich","umami"],
story:{en:"Two entirely different products share the name: the pale oil from raw seed, used for frying, and the dark oil from toasted seed, which is a seasoning and not a cooking fat at all. Buying the wrong one ruins the dish either way.",
fr:"Deux produits entièrement différents partagent le nom : l’huile claire de graines crues, pour la friture, et l’huile sombre de graines torréfiées, qui est un assaisonnement et pas du tout une matière grasse de cuisson. Se tromper gâche le plat dans les deux sens."},
tip:{en:"Add it at the very end, by the half-teaspoon. Heated, its whole aroma burns off within seconds.",
fr:"Ajoutez-la tout à la fin, à la demi-cuillère. Chauffée, tout son arôme s’évapore en quelques secondes."},
pairs:["soy-sauce","ginger","garlic","spring-onion","chili","sesame","fish-sauce","shiitake"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><ellipse class="f2 sf" cx="44" cy="34" rx="4" ry="3"/><ellipse class="f2 sf" cx="53" cy="36" rx="4" ry="3"/>'},

{id:"truffle-oil",cat:"fats",name:{en:"Truffle oil",fr:"Huile de truffe"},latin:"C3H8S2 (2,4-dithiapentane)",
origin:{en:"Flavour houses, Italy",fr:"Maisons d'arômes, Italie"},season:[],
flavor:["pungent","musky","earthy"],
story:{en:"The molecule that makes it, 2,4-dithiapentane, was synthesised in a Berlin laboratory in 1941 and only identified in white truffles a quarter of a century later, in Milan. Almost every bottle on sale is neutral oil dosed with the lab version: one note, held at full strength, where a real truffle carries dozens that fade.",
fr:"La molécule qui la fait, le 2,4-dithiapentane, a été synthétisée dans un laboratoire berlinois en 1941 et n'a été identifiée dans la truffe blanche qu'un quart de siècle plus tard, à Milan. Presque toutes les bouteilles du commerce sont une huile neutre dosée à la version de synthèse : une seule note, tenue à pleine puissance, quand la vraie truffe en porte des dizaines qui s'effacent."},
tip:{en:"It does not cook off and it does not dilute, so it goes on at the table by the drop, never into the pan and never into hot fat. If a dish tastes of nothing but truffle oil there is no rescue — start the sauce again.",
fr:"Elle ne s'évapore pas à la cuisson et ne se dilue pas : elle se met à table, goutte à goutte, jamais dans la poêle ni dans un corps gras chaud. Si un plat ne sent plus qu'elle, il n'y a pas de rattrapage — recommencez la sauce."},
pairs:["potato","egg","parmesan","carnaroli","mushroom","olive-oil"],
svg:'<path class="f1 sf" d="M40 40h16v34q0 4-4 4H44q-4 0-4-4z"/><path class="s" d="M44 40V26h8v14"/><path class="f3 sf" d="M42 20h12v6H42z"/><path class="f2 sf" d="M40 58h16v16q0 4-4 4H44q-4 0-4-4z"/><ellipse class="dot" cx="68" cy="46" rx="3" ry="4"/>'},

{id:"walnut-oil",cat:"fats",name:{en:"Walnut oil",fr:"Huile de noix"},latin:"Juglans regia",
origin:{en:"Périgord & Dauphiné",fr:"Périgord & Dauphiné"},season:[],
flavor:["nutty","rich","toasty","earthy"],
story:{en:"Pressed in stone mills in the Périgord, where the kernels are roasted before crushing — that roasting is the whole flavour. Before it was a condiment it lit lamps and thinned the paints of Renaissance workshops.",
fr:"Pressée dans des moulins de pierre en Périgord, où les cerneaux sont torréfiés avant broyage — cette torréfaction fait tout le goût. Avant d’être un condiment, elle éclairait les lampes et diluait les peintures des ateliers de la Renaissance."},
tip:{en:"Never heat it. It turns bitter almost immediately, and it goes rancid fast — keep the bottle in the fridge.",
fr:"Ne la chauffez jamais. Elle tourne à l’amer presque aussitôt, et rancit vite — gardez la bouteille au réfrigérateur."},
pairs:["walnut","endive","blue-cheese","mache","apple","sherry-vinegar","pear","comte"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="f2 sf" cx="48" cy="34" r="7"/><path class="s" d="M48 28v12"/>'}
]);
