// Chefs — chronological. Descriptive only: dates, documented work, recorded
// influence. No rankings, no superlatives, no judgement of anyone's cooking.
window.CHEFS = (window.CHEFS || []).concat([

{id:"taillevent", name:"Guillaume Tirel, dit Taillevent", born:1310, died:1395, approx:true,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"France — court of Charles V",fr:"France — cour de Charles V"},
 role:{en:"Cook to the French court",fr:"Queux de la cour de France"},
 work:{en:"Le Viandier",fr:"Le Viandier"},
 contribution:{en:"Cooked for Charles V and Charles VI and is associated with Le Viandier, one of the earliest recipe collections written in French. The manuscripts predate his career in part, so authorship is shared and disputed. The recipes show a cuisine built on spices, verjuice and bread-thickened sauces, with little of the butter and stock that came later.",
 fr:"Cuisinier de Charles V puis de Charles VI, son nom est attaché au Viandier, l’un des plus anciens recueils de recettes rédigés en français. Une partie des manuscrits est antérieure à sa carrière : la paternité en est donc partagée et discutée. Les recettes montrent une cuisine d’épices, de verjus et de sauces liées au pain, sans le beurre ni les fonds qui viendront plus tard."},
 legacy:{en:"His tomb at Saint-Germain-en-Laye shows him in armour between three cooking pots — among the earliest images of a cook commemorated as a figure of standing.",
 fr:"Sa pierre tombale à Saint-Germain-en-Laye le montre en armure entre trois marmites — l’une des plus anciennes images d’un cuisinier commémoré comme un personnage de rang."},
 ingredients:["verjus","black-pepper","cinnamon","ginger","saffron","clove","nutmeg","almond"]},

{id:"lavarenne", name:"François Pierre de La Varenne", born:1618, died:1678,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Dijon, France",fr:"Dijon, France"},
 role:{en:"Cook to the Marquis d’Uxelles",fr:"Cuisinier du marquis d’Uxelles"},
 work:{en:"Le Cuisinier françois (1651)",fr:"Le Cuisinier françois (1651)"},
 contribution:{en:"His book is generally treated as the boundary between medieval and modern French cooking. It moves away from heavy spicing towards butter, local herbs and reduced cooking liquids, and contains early written descriptions of roux, bouquet garni and stock-based sauces. Duxelles is named after his employer.",
 fr:"Son ouvrage est généralement tenu pour la frontière entre cuisine médiévale et cuisine française moderne. Il s’éloigne des épices lourdes au profit du beurre, des herbes locales et des jus réduits, et contient des descriptions écrites précoces du roux, du bouquet garni et des sauces montées sur fonds. La duxelles porte le nom de son employeur."},
 legacy:{en:"The book was reprinted for over a century and translated across Europe, which spread the new style well beyond France.",
 fr:"L’ouvrage fut réimprimé plus d’un siècle et traduit dans toute l’Europe, ce qui diffusa le nouveau style bien au-delà de la France."},
 ingredients:["beurre-de-baratte","mushroom","shallot","thyme","bay-leaf","parsley","flour-t55","white-wine-vinegar"]},

{id:"careme", name:"Marie-Antoine Carême", born:1784, died:1833,
 gender:"m", country:"FR", discipline:"cuisine",
 phrase:{text:"Les beaux-arts sont au nombre de cinq : la peinture, la sculpture, la poésie, la musique et l’architecture, laquelle a pour branche principale la pâtisserie.", by:"Carême"},
 place:{en:"Paris — Talleyrand, later foreign courts",fr:"Paris — Talleyrand, puis cours étrangères"},
 role:{en:"Cook and pastry chef",fr:"Cuisinier et pâtissier"},
 work:{en:"L’Art de la cuisine française au XIXe siècle",fr:"L’Art de la cuisine française au XIXe siècle"},
 contribution:{en:"Worked for Talleyrand, the Prince Regent in London and the Russian court. He grouped sauces into families under a set of base preparations — the system later reduced to the mother sauces — and wrote extensively on organisation and presentation. His pièces montées were built as architectural constructions, a discipline he had studied.",
 fr:"Au service de Talleyrand, du prince régent à Londres et de la cour de Russie. Il regroupa les sauces en familles sous quelques préparations de base — le système ramené plus tard aux sauces mères — et écrivit abondamment sur l’organisation et la présentation. Ses pièces montées étaient conçues comme des constructions architecturales, discipline qu’il avait étudiée."},
 legacy:{en:"He worked at a scale and for a clientele that made French cooking a European reference, and his written system gave later cooks something to revise rather than invent.",
 fr:"Il travailla à une échelle et pour une clientèle qui firent de la cuisine française une référence européenne, et son système écrit donna aux suivants quelque chose à réviser plutôt qu’à inventer."},
 ingredients:["beurre-de-baratte","flour-t45","sugar","egg","cream","truffle","almond","vanilla"]},

{id:"escoffier", name:"Auguste Escoffier", born:1846, died:1935,
 gender:"m", country:"FR", discipline:"cuisine",
 phrase:{text:"Faites simple.", by:"Escoffier"},
 place:{en:"Savoy and Carlton hotels, London",fr:"Hôtels Savoy et Carlton, Londres"},
 role:{en:"Chef de cuisine and author",fr:"Chef de cuisine et auteur"},
 work:{en:"Le Guide culinaire (1903)",fr:"Le Guide culinaire (1903)"},
 contribution:{en:"Working with the hotelier César Ritz, he reorganised professional kitchens into the brigade system — separate stations, each with a defined role, reporting to a chef de cuisine. Le Guide culinaire condensed and simplified Carême's repertoire into a working reference, and reduced the sauce families to a shorter list still taught today.",
 fr:"Avec l’hôtelier César Ritz, il réorganisa les cuisines professionnelles en brigade — des parties distinctes, chacune au rôle défini, sous l’autorité d’un chef de cuisine. Le Guide culinaire condensa et simplifia le répertoire de Carême en un ouvrage de travail, et ramena les familles de sauces à une liste plus courte, toujours enseignée."},
 legacy:{en:"The brigade structure and much of the vocabulary in Le Guide culinaire remain in use in professional kitchens internationally.",
 fr:"La structure en brigade et une grande part du vocabulaire du Guide culinaire restent en usage dans les cuisines professionnelles du monde entier."},
 ingredients:["tenderloin","beurre-de-baratte","shallot","truffle","tarragon","flour-t55","cream","tomato"]},

{id:"brazier", name:"Eugénie Brazier, la Mère Brazier", born:1895, died:1977,
 gender:"f", country:"FR", discipline:"cuisine",
 stars:{n:3, years:"1933",
  note:{en:"Three stars at two restaurants at once — six in total, and the first three awarded to a woman.",fr:"Trois étoiles dans deux maisons à la fois — six au total, et les trois premières décernées à une femme."}},
 place:{en:"Lyon and col de la Luère",fr:"Lyon et col de la Luère"},
 role:{en:"Cook and restaurateur",fr:"Cuisinière et restauratrice"},
 work:{en:"La Mère Brazier, rue Royale",fr:"La Mère Brazier, rue Royale"},
 contribution:{en:"Came from the mères lyonnaises, women who had cooked in bourgeois households and then opened their own restaurants. In 1933 she was awarded three Michelin stars at two establishments at once — the first person to hold six stars simultaneously, and the first woman awarded three. Her cooking stayed close to the Lyonnais repertoire.",
 fr:"Issue des mères lyonnaises, ces femmes passées des maisons bourgeoises à leurs propres restaurants. En 1933, elle obtint trois étoiles Michelin dans deux établissements à la fois — première personne à détenir six étoiles simultanément, et première femme à en obtenir trois. Sa cuisine resta proche du répertoire lyonnais."},
 legacy:{en:"Paul Bocuse trained in her kitchen. No woman was awarded three stars in France again until 2007.",
 fr:"Paul Bocuse fit son apprentissage dans sa cuisine. Aucune femme ne fut à nouveau distinguée de trois étoiles en France avant 2007."},
 ingredients:["chicken","truffle","artichoke","foie-gras","beurre-de-baratte","cream","morel","tarragon"]},

{id:"point", name:"Fernand Point", born:1897, died:1955,
 gender:"m", country:"FR", discipline:"cuisine",
 phrase:{text:"Du beurre ! Donnez-moi du beurre ! Toujours du beurre !", by:"Point"},
 stars:{n:3, years:"1933–1955",
  note:{en:"Three stars held continuously from 1933 until his death.",fr:"Trois étoiles conservées sans interruption de 1933 à sa mort."}},
 place:{en:"La Pyramide, Vienne",fr:"La Pyramide, Vienne"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Ma Gastronomie (published 1969)",fr:"Ma Gastronomie (paru en 1969)"},
 contribution:{en:"Ran La Pyramide from 1925, holding three stars from 1933. He worked with lighter treatments and shorter cooking than the hotel repertoire of the period, and insisted on buying produce daily. He took apprentices who later ran their own three-star kitchens.",
 fr:"Il tint La Pyramide à partir de 1925, trois étoiles depuis 1933. Il travailla des cuissons plus légères et plus courtes que le répertoire hôtelier de l’époque, et imposa un approvisionnement quotidien. Il forma des apprentis qui dirigèrent ensuite leurs propres maisons trois étoiles."},
 legacy:{en:"Bocuse, the Troisgros brothers, Alain Chapel and François Bise all passed through his kitchen, which is why he is often placed at the start of the line leading to nouvelle cuisine.",
 fr:"Bocuse, les frères Troisgros, Alain Chapel et François Bise passèrent tous par sa cuisine, ce qui le place souvent à l’origine de la lignée menant à la nouvelle cuisine."},
 ingredients:["beurre-de-baratte","cream","morel","truffle","crayfish","asparagus","chicken","tarragon"]},

{id:"bocuse", name:"Paul Bocuse", born:1926, died:2018,
 gender:"m", country:"FR", discipline:"cuisine",
 phrase:{text:"Il n’y a qu’une seule cuisine : la bonne.", by:"Bocuse"},
 stars:{n:3, years:"1965–2019",
  note:{en:"Fifty-four consecutive years at three stars, among the longest runs recorded.",fr:"Cinquante-quatre années consécutives à trois étoiles, l’une des plus longues séries enregistrées."}},
 place:{en:"Collonges-au-Mont-d’Or",fr:"Collonges-au-Mont-d’Or"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"L’Auberge du Pont de Collonges",fr:"L’Auberge du Pont de Collonges"},
 contribution:{en:"Trained with Eugénie Brazier and Fernand Point. His restaurant held three Michelin stars from 1965 to 2019, one of the longest unbroken runs recorded. He was among the chefs associated with nouvelle cuisine in the 1970s, though he continued to cook classical dishes alongside it.",
 fr:"Formé chez Eugénie Brazier puis Fernand Point. Son restaurant conserva trois étoiles Michelin de 1965 à 2019, l’une des plus longues séries ininterrompues enregistrées. Il fut de ceux qu’on associa à la nouvelle cuisine dans les années 1970, tout en continuant de cuisiner le répertoire classique."},
 legacy:{en:"He founded the Bocuse d’Or competition in 1987 and a cookery school in Écully, and was among the first chefs widely known to the public outside the profession.",
 fr:"Il fonda le concours du Bocuse d’Or en 1987 et une école de cuisine à Écully, et fut l’un des premiers cuisiniers largement connus du public hors de la profession."},
 ingredients:["truffle","chicken","foie-gras","beurre-de-baratte","bresse-chicken","morel","cream","potato"]},

{id:"scappi", name:"Bartolomeo Scappi", born:1500, died:1577, approx:true,
 gender:"m", country:"IT", discipline:"cuisine",
 place:{en:"Rome — papal kitchens",fr:"Rome — cuisines pontificales"},
 role:{en:"Private cook to Pius IV and Pius V",fr:"Cuisinier privé de Pie IV et Pie V"},
 work:{en:"Opera dell’arte del cucinare (1570)",fr:"Opera dell’arte del cucinare (1570)"},
 contribution:{en:"Cooked for cardinals and two popes across the mid-sixteenth century. His Opera runs to roughly a thousand recipes and is illustrated with engravings of kitchens, tools and equipment — among the earliest such images in print. It records a fork on the table and describes techniques for pastry, preserves and roasting in unusual detail.",
 fr:"Au service de cardinaux puis de deux papes au milieu du XVIe siècle. Son Opera compte environ mille recettes, illustrées de gravures de cuisines, d’ustensiles et de matériel — parmi les premières images de ce genre imprimées. Il y mentionne une fourchette à table et décrit pâtisserie, conserves et rôtissage avec un détail inhabituel."},
 legacy:{en:"The Opera is the most complete record of Renaissance Italian cooking to survive, and a principal source for what the French court inherited.",
 fr:"L’Opera est le témoignage le plus complet de la cuisine italienne de la Renaissance qui nous soit parvenu, et une source principale de ce que la cour de France en hérita."},
 ingredients:["saffron","cinnamon","sugar","almond","vanilla","black-pepper","egg","flour-t55"]},

{id:"vatel", name:"François Vatel", born:1631, died:1671,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Vaux-le-Vicomte, then Chantilly",fr:"Vaux-le-Vicomte, puis Chantilly"},
 role:{en:"Maître d’hôtel to Fouquet, then to the Prince de Condé",fr:"Maître d’hôtel de Fouquet, puis du prince de Condé"},
 work:{en:"The fête for Louis XIV at Chantilly, April 1671",fr:"La fête pour Louis XIV à Chantilly, avril 1671"},
 contribution:{en:"Organised the tables and service of two of the grandest households of the century. He was a steward rather than a cook in the modern sense — responsible for supply, staging and order of service for feasts of several thousand. During the 1671 fête he died by his own hand; the account we have is a letter by Madame de Sévigné, written within days.",
 fr:"Organisa les tables et le service de deux des plus grandes maisons du siècle. Intendant plus que cuisinier au sens moderne — chargé de l’approvisionnement, de la mise en scène et de l’ordre du service pour des fêtes de plusieurs milliers de couverts. Durant la fête de 1671 il se donna la mort ; le récit qui nous reste est une lettre de Madame de Sévigné, écrite quelques jours après."},
 legacy:{en:"The attribution of crème Chantilly to him is later legend with no contemporary source. His name survives as the emblem of service under pressure.",
 fr:"L’attribution de la crème Chantilly à son nom est une légende postérieure sans source contemporaine. Son nom reste l’emblème du service sous pression."},
 ingredients:["cream","sugar","turbot","dover-sole","beurre-de-baratte","asparagus","strawberry","truffle"]},

{id:"menon", name:"Menon", born:1700, died:1770, approx:true,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Paris",fr:"Paris"},
 role:{en:"Author — identity otherwise unknown",fr:"Auteur — identité par ailleurs inconnue"},
 work:{en:"La Cuisinière bourgeoise (1746)",fr:"La Cuisinière bourgeoise (1746)"},
 contribution:{en:"Nothing is known of the person beyond the surname. The book is addressed not to the aristocratic kitchen but to the household cook of a middling family, and it was reprinted for over a century — among the most widely circulated French cookbooks before the nineteenth century.",
 fr:"On ne sait rien de la personne au-delà du nom. Le livre s’adresse non à la cuisine aristocratique mais à la cuisinière d’une maison bourgeoise, et fut réimprimé plus d’un siècle — l’un des livres de cuisine français les plus diffusés avant le XIXe siècle."},
 legacy:{en:"It marks the moment written French cooking turned from the court towards the home.",
 fr:"Il marque le moment où la cuisine française écrite se tourne de la cour vers la maison."},
 ingredients:["onion","carrot","beurre-de-baratte","parsley","bay-leaf","egg","flour-t55","white-wine-vinegar"]},

{id:"gouffe", name:"Jules Gouffé", born:1807, died:1877,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Paris — the Jockey Club",fr:"Paris — le Jockey Club"},
 role:{en:"Chef and author; pupil of Carême",fr:"Chef et auteur ; élève de Carême"},
 work:{en:"Le Livre de cuisine (1867)",fr:"Le Livre de cuisine (1867)"},
 contribution:{en:"Trained under Carême and ran the kitchens of the Jockey Club. His book is unusual for its time in giving weights, measures and timings with precision, and in separating household cooking from grande cuisine within one volume. Illustrated with colour plates.",
 fr:"Formé chez Carême, il dirigea les cuisines du Jockey Club. Son livre est inhabituel pour l’époque par la précision de ses poids, mesures et temps de cuisson, et par la séparation, dans un même volume, de la cuisine de ménage et de la grande cuisine. Illustré de planches en couleur."},
 legacy:{en:"Translated into English within a year; one of the bridges between Carême’s system and Escoffier’s.",
 fr:"Traduit en anglais dans l’année ; l’un des ponts entre le système de Carême et celui d’Escoffier."},
 ingredients:["beurre-de-baratte","cream","truffle","flour-t55","egg","sugar","tendron-de-veau","mushroom"]},

{id:"dubois", name:"Urbain Dubois", born:1818, died:1901,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Paris, then the Prussian court",fr:"Paris, puis la cour de Prusse"},
 role:{en:"Chef to Prince Orloff, then to Wilhelm I",fr:"Chef du prince Orloff, puis de Guillaume Ier"},
 work:{en:"La Cuisine classique (1856), with Émile Bernard",fr:"La Cuisine classique (1856), avec Émile Bernard"},
 contribution:{en:"Worked for Russian and German courts and is associated with the adoption in France of service à la russe — dishes brought in sequence, hot, rather than laid out together. Veau Orloff is attributed to his kitchen. His books ran to many editions and were widely used in professional training.",
 fr:"Au service des cours de Russie et d’Allemagne, on lui associe l’adoption en France du service à la russe — les plats apportés en séquence, chauds, plutôt que disposés ensemble. Le veau Orloff est attribué à sa cuisine. Ses ouvrages connurent de nombreuses éditions et servirent largement à la formation professionnelle."},
 legacy:{en:"The sequence of courses that restaurants still follow owes a good deal to the change he helped carry.",
 fr:"L’enchaînement des plats que suivent encore les restaurants doit beaucoup au changement qu’il contribua à porter."},
 ingredients:["tendron-de-veau","mushroom","onion","cream","truffle","beurre-de-baratte","flour-t55","gruyere"]},

{id:"montagne", name:"Prosper Montagné", born:1865, died:1948,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Paris",fr:"Paris"},
 role:{en:"Chef and author",fr:"Chef et auteur"},
 work:{en:"Larousse gastronomique (1938)",fr:"Larousse gastronomique (1938)"},
 contribution:{en:"Ran hotel kitchens in Paris and Monte Carlo and wrote the first edition of the Larousse gastronomique, the reference encyclopedia of French cooking, with a preface by Escoffier. In earlier writing he argued against the elaborate garnishes and constructed presentations inherited from Carême.",
 fr:"Dirigea des cuisines d’hôtel à Paris et Monte-Carlo, et rédigea la première édition du Larousse gastronomique, l’encyclopédie de référence de la cuisine française, préfacée par Escoffier. Dans ses écrits antérieurs, il s’élevait contre les garnitures élaborées et les présentations construites héritées de Carême."},
 legacy:{en:"The Larousse gastronomique remains in print and in revision nearly a century later.",
 fr:"Le Larousse gastronomique reste édité et révisé près d’un siècle plus tard."},
 ingredients:["beurre-de-baratte","shallot","tarragon","cream","truffle","flour-t55","mushroom","white-wine-vinegar"]},

{id:"blanc", name:"Élisa Blanc, la Mère Blanc", born:1883, died:1949,
 gender:"f", country:"FR", discipline:"cuisine",
 place:{en:"Vonnas, Ain",fr:"Vonnas, Ain"},
 role:{en:"Cook and innkeeper",fr:"Cuisinière et aubergiste"},
 work:{en:"The family inn at Vonnas",fr:"L’auberge familiale de Vonnas"},
 phrase:{text:"La meilleure cuisinière du monde.", by:"Curnonsky, 1933, of Élisa Blanc"},
 contribution:{en:"Took over the family inn beside the market at Vonnas and cooked Bresse produce — poultry, cream, frogs’ legs — in a repertoire that stayed regional. The critic Curnonsky named her the best cook in the world in 1933, a phrase that followed the house for decades.",
 fr:"Reprit l’auberge familiale près du marché de Vonnas et cuisina les produits de la Bresse — volaille, crème, grenouilles — dans un répertoire resté régional. Le critique Curnonsky la nomma en 1933 la meilleure cuisinière du monde, formule qui suivit la maison pendant des décennies."},
 legacy:{en:"Her grandson Georges Blanc took the same house to three stars in 1981, which it has held since.",
 fr:"Son petit-fils Georges Blanc porta la même maison à trois étoiles en 1981, conservées depuis."},
 ingredients:["bresse-chicken","cream","beurre-de-baratte","morel","tarragon","egg","flour-t55","white-wine-vinegar"]},

{id:"pic-andre", name:"André Pic", born:1893, died:1984,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Valence, Drôme",fr:"Valence, Drôme"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Maison Pic",fr:"Maison Pic"},
 stars:{n:3, years:"1934", note:{en:"Three stars in 1934; later lost, regained by his son Jacques in 1973 and by his granddaughter Anne-Sophie in 2007.",fr:"Trois étoiles en 1934 ; perdues ensuite, retrouvées par son fils Jacques en 1973 et par sa petite-fille Anne-Sophie en 2007."}},
 contribution:{en:"Moved the family restaurant from the Ardèche countryside to the Nationale 7 at Valence in 1936, on the road south, and was among the first three-star chefs of the modern guide. The house passed to his son and then his granddaughter.",
 fr:"Déplaça en 1936 le restaurant familial de la campagne ardéchoise vers la Nationale 7 à Valence, sur la route du sud, et fut parmi les premiers chefs trois étoiles du guide moderne. La maison passa à son fils puis à sa petite-fille."},
 legacy:{en:"Three generations of the same family have held three stars in the same house — the only such case in France.",
 fr:"Trois générations d’une même famille ont détenu trois étoiles dans la même maison — cas unique en France."},
 ingredients:["crayfish","truffle","cream","beurre-de-baratte","chicken","morel","tarragon","white-wine-vinegar"]},

{id:"dumaine", name:"Alexandre Dumaine", born:1895, died:1974,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Saulieu, Burgundy",fr:"Saulieu, Bourgogne"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Hôtel de la Côte-d’Or",fr:"Hôtel de la Côte-d’Or"},
 stars:{n:3, years:"1935–1964", note:{en:"Three stars for nearly thirty years on the Route Nationale 6.",fr:"Trois étoiles pendant près de trente ans sur la Nationale 6."}},
 contribution:{en:"Ran the Côte-d’Or at Saulieu from 1932 on the main road from Paris to the south, and held three stars from 1935 until retiring. With Point and Pic he formed the group of roadside three-star houses of the inter-war years. Long, slow cooking of Burgundian dishes was the mark of the kitchen.",
 fr:"Tint la Côte-d’Or à Saulieu à partir de 1932, sur la grande route de Paris vers le sud, et garda trois étoiles de 1935 à sa retraite. Avec Point et Pic il forma le groupe des maisons trois étoiles de bord de route de l’entre-deux-guerres. Les cuissons longues et douces des plats bourguignons faisaient la marque de la cuisine."},
 legacy:{en:"The house was later taken to three stars again by Bernard Loiseau, in 1991.",
 fr:"La maison fut de nouveau portée à trois étoiles par Bernard Loiseau, en 1991."},
 ingredients:["beef","red-wine-vinegar","mushroom","lard","onion","chicken","cream","truffle"]},

{id:"bise", name:"Marguerite Bise", born:1898, died:1965,
 gender:"f", country:"FR", discipline:"cuisine",
 place:{en:"Talloires, lac d’Annecy",fr:"Talloires, lac d’Annecy"},
 role:{en:"Cook and innkeeper",fr:"Cuisinière et aubergiste"},
 work:{en:"Auberge du Père Bise",fr:"Auberge du Père Bise"},
 stars:{n:3, years:"1951", note:{en:"The third woman awarded three stars, after Eugénie Brazier and Marie Bourgeois in 1933.",fr:"Troisième femme distinguée de trois étoiles, après Eugénie Brazier et Marie Bourgeois en 1933."}},
 contribution:{en:"Cooked at the family inn on the lake, which her parents-in-law had opened in 1903. She was awarded three stars in 1951 and kept them until her death, working with the lake’s fish and the produce of the Savoie.",
 fr:"Cuisinait à l’auberge familiale au bord du lac, ouverte par ses beaux-parents en 1903. Trois étoiles en 1951, conservées jusqu’à sa mort, autour des poissons du lac et des produits de Savoie."},
 legacy:{en:"After her, no woman was awarded three stars in France until Anne-Sophie Pic in 2007 — a gap of fifty-six years.",
 fr:"Après elle, aucune femme ne fut distinguée de trois étoiles en France avant Anne-Sophie Pic en 2007 — cinquante-six ans plus tard."},
 ingredients:["char","crayfish","beurre-de-baratte","cream","morel","chives","tarragon","white-wine-vinegar"]},

{id:"oliver", name:"Raymond Oliver", born:1909, died:1990,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Le Grand Véfour, Paris",fr:"Le Grand Véfour, Paris"},
 role:{en:"Chef-patron and broadcaster",fr:"Chef-propriétaire et homme de télévision"},
 work:{en:"Art et magie de la cuisine (television, from 1954)",fr:"Art et magie de la cuisine (télévision, dès 1954)"},
 stars:{n:3, years:"1953–1983", note:{en:"Three stars at the Grand Véfour for three decades.",fr:"Trois étoiles au Grand Véfour pendant trois décennies."}},
 contribution:{en:"Bought the Grand Véfour in the Palais-Royal in 1948 and restored it to three stars. From 1954 he presented a weekly cooking programme on French television with Catherine Langeais — the first chef to cook regularly on air in France, over some fourteen years.",
 fr:"Racheta le Grand Véfour au Palais-Royal en 1948 et le ramena à trois étoiles. À partir de 1954 il présenta une émission hebdomadaire de cuisine à la télévision française avec Catherine Langeais — le premier chef à cuisiner régulièrement à l’antenne en France, pendant quelque quatorze ans."},
 legacy:{en:"He established the chef as a television figure in France, a role Bocuse and others would extend.",
 fr:"Il installa le chef comme figure de télévision en France, rôle que Bocuse et d’autres élargiraient."},
 ingredients:["beurre-de-baratte","truffle","foie-gras","cream","chicken","shallot","white-wine-vinegar","lobster"]},

{id:"child", name:"Julia Child", born:1912, died:2004,
 gender:"f", country:"US", discipline:"cuisine",
 place:{en:"Paris, then Cambridge, Massachusetts",fr:"Paris, puis Cambridge, Massachusetts"},
 role:{en:"Cook, author and broadcaster",fr:"Cuisinière, auteure et présentatrice"},
 work:{en:"Mastering the Art of French Cooking (1961)",fr:"Mastering the Art of French Cooking (1961)"},
 phrase:{text:"People who love to eat are always the best people.", by:"Julia Child"},
 contribution:{en:"Trained at the Cordon Bleu in Paris in her late thirties and, with Simone Beck and Louisette Bertholle, spent a decade writing a French cookbook for American home cooks, tested for American ingredients and equipment. Her television series The French Chef ran from 1963.",
 fr:"Formée au Cordon Bleu à Paris passé la trentaine, elle consacra avec Simone Beck et Louisette Bertholle dix ans à un livre de cuisine française pour les foyers américains, testé avec les ingrédients et le matériel américains. Sa série télévisée The French Chef débuta en 1963."},
 legacy:{en:"She is generally credited with making French technique accessible to a mass American audience, in print and on screen.",
 fr:"On lui attribue généralement d’avoir rendu la technique française accessible à un large public américain, à l’écrit et à l’écran."},
 ingredients:["beurre-de-baratte","beef","red-wine-vinegar","mushroom","onion","egg","cream","shallot"]},

{id:"lenotre", name:"Gaston Lenôtre", born:1920, died:2009,
 gender:"m", country:"FR", discipline:"patisserie",
 place:{en:"Paris, from Normandy",fr:"Paris, depuis la Normandie"},
 role:{en:"Pastry chef and founder of a school",fr:"Pâtissier et fondateur d’une école"},
 work:{en:"École Lenôtre (1971)",fr:"École Lenôtre (1971)"},
 contribution:{en:"Opened a pastry shop in Paris in 1957 and built it into a house with catering, retail and a professional school. His pastry used less sugar and less flour than the classical repertoire and relied more on fruit and mousse — a change many later pâtissiers adopted.",
 fr:"Ouvrit une pâtisserie à Paris en 1957 et en fit une maison avec traiteur, boutiques et école professionnelle. Sa pâtisserie employait moins de sucre et de farine que le répertoire classique, davantage de fruits et de mousses — une évolution que beaucoup de pâtissiers reprirent ensuite."},
 legacy:{en:"Pierre Hermé apprenticed with him at fourteen; the school has trained pastry cooks internationally for five decades.",
 fr:"Pierre Hermé fit son apprentissage chez lui à quatorze ans ; l’école forme des pâtissiers du monde entier depuis cinq décennies."},
 ingredients:["beurre-de-baratte","dark-chocolate","cream","raspberry","vanilla","almond","sugar","flour-t45"]},

{id:"ono", name:"Jiro Ono", born:1925,
 gender:"m", country:"JP", discipline:"cuisine",
 place:{en:"Sukiyabashi Jiro, Ginza, Tokyo",fr:"Sukiyabashi Jiro, Ginza, Tokyo"},
 role:{en:"Sushi chef",fr:"Maître sushi"},
 work:{en:"Sukiyabashi Jiro",fr:"Sukiyabashi Jiro"},
 stars:{n:3, years:"2007–2019", note:{en:"The first sushi restaurant awarded three stars. Removed from the guide in 2019 as it no longer took public reservations.",fr:"Premier restaurant de sushi distingué de trois étoiles. Retiré du guide en 2019, ne prenant plus de réservations du public."}},
 contribution:{en:"Has served omakase sushi at a ten-seat counter in a Ginza basement since 1965. The restaurant was awarded three stars in the first Tokyo guide in 2007 and was the subject of the 2011 documentary Jiro Dreams of Sushi.",
 fr:"Sert des sushis en omakase à un comptoir de dix places dans un sous-sol de Ginza depuis 1965. Le restaurant reçut trois étoiles dans le premier guide de Tokyo en 2007 et fit l’objet du documentaire Jiro Dreams of Sushi en 2011."},
 legacy:{en:"The restaurant made the shokunin ideal — a lifetime spent refining one craft — widely known outside Japan.",
 fr:"Le restaurant fit connaître largement hors du Japon l’idéal du shokunin — une vie consacrée à perfectionner un seul métier."},
 ingredients:["tuna","rice","rice-vinegar","wasabi","soy-sauce","nori","sea-bream","mackerel"]},

{id:"troisgros", name:"Jean et Pierre Troisgros", born:1926, died:2020,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Roanne, Loire",fr:"Roanne, Loire"},
 role:{en:"Brothers, chef-patrons",fr:"Frères, chefs-propriétaires"},
 work:{en:"Saumon à l’oseille (1962)",fr:"Saumon à l’oseille (1962)"},
 stars:{n:3, years:"1968", note:{en:"Three stars from 1968, held by the family across three generations since.",fr:"Trois étoiles depuis 1968, conservées par la famille sur trois générations."}},
 contribution:{en:"Both trained with Fernand Point before returning to the family hotel opposite Roanne station. Jean (1926–1983) and Pierre (1928–2020) worked the kitchen together; their escalope of salmon with sorrel — barely cooked, with a reduced cream sauce — is among the most cited dishes of nouvelle cuisine.",
 fr:"Tous deux formés chez Fernand Point avant de reprendre l’hôtel familial face à la gare de Roanne. Jean (1926–1983) et Pierre (1928–2020) tinrent la cuisine ensemble ; leur escalope de saumon à l’oseille — à peine cuite, sur une réduction de crème — compte parmi les plats les plus cités de la nouvelle cuisine."},
 legacy:{en:"The house passed to Pierre’s son Michel and then to Michel’s son César, keeping three stars throughout.",
 fr:"La maison passa au fils de Pierre, Michel, puis au fils de celui-ci, César, gardant trois étoiles tout du long."},
 ingredients:["salmon","sorrel","cream","shallot","white-wine-vinegar","beurre-de-baratte","chervil","black-pepper"]},

{id:"verge", name:"Roger Vergé", born:1930, died:2015,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Le Moulin de Mougins, Provence",fr:"Le Moulin de Mougins, Provence"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Ma cuisine du soleil (1978)",fr:"Ma cuisine du soleil (1978)"},
 stars:{n:3, years:"1974", note:{en:"Three stars at the Moulin de Mougins from 1974.",fr:"Trois étoiles au Moulin de Mougins à partir de 1974."}},
 contribution:{en:"Opened the Moulin de Mougins in a sixteenth-century oil mill in 1969 and built a kitchen on olive oil, vegetables, herbs and fish of the Mediterranean coast, which he called cuisine du soleil. He was one of the chefs grouped under nouvelle cuisine in the 1970s.",
 fr:"Ouvrit le Moulin de Mougins dans un moulin à huile du XVIe siècle en 1969 et bâtit une cuisine sur l’huile d’olive, les légumes, les herbes et les poissons de la côte méditerranéenne, qu’il nomma cuisine du soleil. Il fut de ceux qu’on rassembla sous la nouvelle cuisine dans les années 1970."},
 legacy:{en:"Alain Ducasse, Daniel Boulud and David Bouley are among those who trained in his kitchen.",
 fr:"Alain Ducasse, Daniel Boulud et David Bouley comptent parmi ceux qui se formèrent dans sa cuisine."},
 ingredients:["olive-oil","basil","tomato","zucchini","fennel","garlic","sea-bass","lemon"]},

{id:"guerard", name:"Michel Guérard", born:1933, died:2024,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Eugénie-les-Bains, Landes",fr:"Eugénie-les-Bains, Landes"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"La Grande Cuisine minceur (1976)",fr:"La Grande Cuisine minceur (1976)"},
 stars:{n:3, years:"1977", note:{en:"Three stars from 1977 at Les Prés d’Eugénie, held for over four decades.",fr:"Trois étoiles dès 1977 aux Prés d’Eugénie, conservées plus de quatre décennies."}},
 contribution:{en:"Trained as a pâtissier, then ran Le Pot-au-Feu at Asnières before moving to a spa hotel in the Landes in 1974. There he developed cuisine minceur — a set of techniques for reducing fat and sugar without abandoning French method — alongside a conventional grande cuisine menu.",
 fr:"Formé pâtissier, il tint Le Pot-au-Feu à Asnières avant de s’installer en 1974 dans un hôtel thermal des Landes. Il y développa la cuisine minceur — un ensemble de techniques pour réduire gras et sucre sans renoncer à la méthode française — à côté d’une carte de grande cuisine classique."},
 legacy:{en:"Cuisine minceur was translated widely and is the origin of much later interest in lighter professional cooking.",
 fr:"La cuisine minceur fut largement traduite et se trouve à l’origine de bien des recherches ultérieures sur une cuisine professionnelle plus légère."},
 ingredients:["fromage-blanc","chervil","tarragon","lemon","asparagus","salmon","mushroom","yogurt"]},

{id:"chapel", name:"Alain Chapel", born:1937, died:1990,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Mionnay, Ain",fr:"Mionnay, Ain"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"La cuisine, c’est beaucoup plus que des recettes (1980)",fr:"La cuisine, c’est beaucoup plus que des recettes (1980)"},
 stars:{n:3, years:"1973", note:{en:"Three stars from 1973 at the family house in Mionnay.",fr:"Trois étoiles dès 1973 à la maison familiale de Mionnay."}},
 contribution:{en:"Trained with Fernand Point and returned to his father’s restaurant north of Lyon, taking it to three stars in 1973. His cooking was noted for restraint and for the quality of sourcing rather than for signature effects, and his one book is as much about the philosophy of the kitchen as its recipes.",
 fr:"Formé chez Fernand Point, il revint au restaurant paternel au nord de Lyon et le porta à trois étoiles en 1973. Sa cuisine fut remarquée pour sa retenue et la qualité de ses approvisionnements plutôt que pour des effets signature, et son unique livre traite autant de la philosophie de la cuisine que de recettes."},
 legacy:{en:"Alain Ducasse has described him as his most important teacher; his death at fifty-two ended the house’s run.",
 fr:"Alain Ducasse le décrit comme son maître le plus important ; sa mort à cinquante-deux ans mit fin à la période de la maison."},
 ingredients:["bresse-chicken","truffle","morel","cream","crayfish","beurre-de-baratte","artichoke","tarragon"]},

{id:"waters", name:"Alice Waters", born:1944,
 gender:"f", country:"US", discipline:"cuisine",
 place:{en:"Chez Panisse, Berkeley, California",fr:"Chez Panisse, Berkeley, Californie"},
 role:{en:"Restaurateur and campaigner",fr:"Restauratrice et militante"},
 work:{en:"Chez Panisse (1971); the Edible Schoolyard (1995)",fr:"Chez Panisse (1971) ; l’Edible Schoolyard (1995)"},
 contribution:{en:"Opened Chez Panisse in 1971 with a single fixed menu changed daily, built around what local growers could supply that morning. The restaurant’s sourcing practices — direct relationships with farms, seasonal menus — became a model widely adopted in American restaurants.",
 fr:"Ouvrit Chez Panisse en 1971 avec un menu unique changé chaque jour, bâti sur ce que les producteurs locaux pouvaient livrer le matin même. Les pratiques d’approvisionnement du restaurant — relations directes avec les fermes, cartes de saison — devinrent un modèle largement repris par les restaurants américains."},
 legacy:{en:"The Edible Schoolyard programme, begun in a Berkeley school garden, has been replicated in several thousand schools.",
 fr:"Le programme Edible Schoolyard, né dans le jardin d’une école de Berkeley, a été reproduit dans plusieurs milliers d’écoles."},
 ingredients:["lettuce","olive-oil","garlic","tomato","goat-cheese","basil","lemon","fig"]},

{id:"robuchon", name:"Joël Robuchon", born:1945, died:2018,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Jamin, Paris; later L’Atelier, worldwide",fr:"Jamin, Paris ; puis L’Atelier, dans le monde"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"Purée de pommes de terre; L’Atelier (2003)",fr:"Purée de pommes de terre ; L’Atelier (2003)"},
 stars:{n:3, years:"1984", note:{en:"Three stars at Jamin within three years of opening. At his death his restaurants held more stars simultaneously than any chef before him.",fr:"Trois étoiles à Jamin trois ans après l’ouverture. À sa mort, ses restaurants détenaient plus d’étoiles simultanément qu’aucun chef avant lui."}},
 contribution:{en:"Meilleur Ouvrier de France in 1976, he opened Jamin in 1981 and reached three stars in 1984. He retired from the stove in 1996, then returned in 2003 with L’Atelier — counter seating, an open kitchen, small plates — which he opened in a dozen cities. His potato purée, with a very high proportion of butter, is the most reproduced version of the dish.",
 fr:"Meilleur Ouvrier de France en 1976, il ouvrit Jamin en 1981 et atteignit trois étoiles en 1984. Il quitta les fourneaux en 1996, puis revint en 2003 avec L’Atelier — service au comptoir, cuisine ouverte, petites assiettes — ouvert dans une douzaine de villes. Sa purée de pommes de terre, à très forte proportion de beurre, est la version la plus reproduite du plat."},
 legacy:{en:"The counter format of L’Atelier has been widely imitated; his purée is the reference technique taught in most schools.",
 fr:"Le format au comptoir de L’Atelier a été largement imité ; sa purée est la technique de référence enseignée dans la plupart des écoles."},
 ingredients:["potato","beurre-de-baratte","cream","truffle","caviar","langoustine","cauliflower","black-pepper"]},

{id:"bras", name:"Michel Bras", born:1946,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Laguiole, Aubrac",fr:"Laguiole, Aubrac"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Le gargouillou (1980); le coulant au chocolat (1981)",fr:"Le gargouillou (1980) ; le coulant au chocolat (1981)"},
 stars:{n:3, years:"1999", note:{en:"Three stars at Laguiole from 1999; the family returned them in 2017 by choice.",fr:"Trois étoiles à Laguiole dès 1999 ; la famille les rendit en 2017 par choix."}},
 contribution:{en:"Cooked in his mother’s hotel at Laguiole before building a restaurant on the plateau above it in 1992. The gargouillou — several dozen vegetables, herbs and shoots, each prepared separately and assembled on the plate — dates from 1980; the coulant au chocolat, with a liquid centre, from 1981.",
 fr:"Cuisina dans l’hôtel maternel de Laguiole avant de bâtir en 1992 un restaurant sur le plateau qui le domine. Le gargouillou — plusieurs dizaines de légumes, d’herbes et de pousses, chacun préparé à part puis assemblé sur l’assiette — date de 1980 ; le coulant au chocolat, à cœur liquide, de 1981."},
 legacy:{en:"Both dishes have been reproduced in kitchens worldwide, the coulant to the point of becoming a generic dessert.",
 fr:"Les deux plats ont été repris dans les cuisines du monde entier, le coulant au point de devenir un dessert générique."},
 ingredients:["dark-chocolate","fava-bean","pea","chervil","lovage","sorrel","beurre-de-baratte","cantal"]},

{id:"gagnaire", name:"Pierre Gagnaire", born:1950,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Saint-Étienne, then Paris",fr:"Saint-Étienne, puis Paris"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"Collaboration with the chemist Hervé This",fr:"Collaboration avec le chimiste Hervé This"},
 stars:{n:3, years:"1993 · 1998", note:{en:"Three stars at Saint-Étienne in 1993; the restaurant closed in 1996 and he regained three stars in Paris in 1998.",fr:"Trois étoiles à Saint-Étienne en 1993 ; le restaurant ferma en 1996 et il retrouva trois étoiles à Paris en 1998."}},
 contribution:{en:"Reached three stars in Saint-Étienne, an industrial city without a restaurant tradition, and after that restaurant closed reopened in Paris and reached three stars again within two years. From 2000 he worked with the physical chemist Hervé This on applying laboratory findings to cooking.",
 fr:"Atteignit trois étoiles à Saint-Étienne, ville industrielle sans tradition de restauration, et après la fermeture rouvrit à Paris pour retrouver trois étoiles en deux ans. À partir de 2000 il travailla avec le physico-chimiste Hervé This à l’application de résultats de laboratoire à la cuisine."},
 legacy:{en:"Their joint work is among the origins of what became called molecular gastronomy.",
 fr:"Leur travail commun compte parmi les origines de ce qu’on appela la gastronomie moléculaire."},
 ingredients:["langoustine","foie-gras","yuzu","tonka","dark-chocolate","cream","sea-urchin","black-pepper"]},

{id:"keller", name:"Thomas Keller", born:1955,
 gender:"m", country:"US", discipline:"cuisine",
 place:{en:"The French Laundry, Yountville; Per Se, New York",fr:"The French Laundry, Yountville ; Per Se, New York"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"The French Laundry Cookbook (1999)",fr:"The French Laundry Cookbook (1999)"},
 stars:{n:3, years:"2006", note:{en:"Three stars at both The French Laundry and Per Se in the same year — the first American chef with two three-star restaurants.",fr:"Trois étoiles à The French Laundry et à Per Se la même année — premier chef américain à deux restaurants trois étoiles."}},
 contribution:{en:"Trained in France under Guy Savoy and others before taking over The French Laundry in the Napa Valley in 1994. His tasting menus of many small courses, each finished before its interest fades, and his written insistence on precision made the restaurant a reference for American fine dining.",
 fr:"Formé en France chez Guy Savoy et d’autres avant de reprendre The French Laundry dans la Napa Valley en 1994. Ses menus dégustation en nombreux petits plats, chacun achevé avant que l’intérêt ne retombe, et son insistance écrite sur la précision firent du restaurant une référence de la haute cuisine américaine."},
 legacy:{en:"A large number of American chefs of the following generation passed through his kitchens.",
 fr:"Nombre de chefs américains de la génération suivante passèrent par ses cuisines."},
 ingredients:["beurre-de-baratte","salmon","caviar","truffle","oyster","cauliflower","cream","chives"]},

{id:"ducasse", name:"Alain Ducasse", born:1956,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Monaco, Paris, London and elsewhere",fr:"Monaco, Paris, Londres et ailleurs"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"Le Louis XV, Monaco (1987)",fr:"Le Louis XV, Monaco (1987)"},
 stars:{n:3, years:"1990", note:{en:"Three stars at the Louis XV at thirty-three. In 2005 he became the first chef to hold three three-star restaurants simultaneously — Monaco, Paris and New York.",fr:"Trois étoiles au Louis XV à trente-trois ans. En 2005 il fut le premier chef à détenir simultanément trois restaurants trois étoiles — Monaco, Paris et New York."}},
 contribution:{en:"Trained with Guérard, Vergé and Chapel. He took the Louis XV in Monaco to three stars within three years of opening, and from there built a group of restaurants, a cookery school and a publishing house. His cooking there drew on Mediterranean produce and Provençal repertoire.",
 fr:"Formé chez Guérard, Vergé et Chapel. Il porta le Louis XV de Monaco à trois étoiles en trois ans, et bâtit à partir de là un groupe de restaurants, une école et une maison d’édition. Sa cuisine y puisait dans les produits méditerranéens et le répertoire provençal."},
 legacy:{en:"In 2016 he cooked the state dinner at the Élysée for the visiting British monarch; his group operates on several continents.",
 fr:"En 2016 il servit le dîner d’État à l’Élysée pour la souveraine britannique en visite ; son groupe opère sur plusieurs continents."},
 ingredients:["olive-oil","tomato","zucchini","basil","sea-bass","artichoke","lemon","fennel"]},

{id:"herme", name:"Pierre Hermé", born:1961,
 gender:"m", country:"FR", discipline:"patisserie",
 place:{en:"Paris and Tokyo",fr:"Paris et Tokyo"},
 role:{en:"Pastry chef",fr:"Pâtissier"},
 work:{en:"Maison Pierre Hermé (1998)",fr:"Maison Pierre Hermé (1998)"},
 contribution:{en:"Fourth generation of an Alsatian baking family, apprenticed with Gaston Lenôtre at fourteen, then pastry chef at Fauchon and Ladurée before opening his own house in 1998 — in Tokyo first, then Paris. He is associated particularly with the macaron and with pairings such as rose, lychee and raspberry.",
 fr:"Quatrième génération d’une famille de boulangers alsaciens, apprenti chez Gaston Lenôtre à quatorze ans, puis chef pâtissier chez Fauchon et Ladurée avant d’ouvrir sa maison en 1998 — à Tokyo d’abord, puis à Paris. On l’associe particulièrement au macaron et à des accords comme rose, litchi et framboise."},
 legacy:{en:"His work is frequently cited as the point at which pastry began to be discussed in the same terms as savoury cooking.",
 fr:"Son travail est souvent cité comme le moment où la pâtisserie commença d’être discutée dans les mêmes termes que la cuisine salée."},
 ingredients:["raspberry","lychee","dark-chocolate","beurre-de-baratte","almond","vanilla","passion-fruit","sugar"]},

{id:"white", name:"Marco Pierre White", born:1961,
 gender:"m", country:"GB", discipline:"cuisine",
 place:{en:"Harveys, then The Restaurant, London",fr:"Harveys, puis The Restaurant, Londres"},
 role:{en:"Chef",fr:"Chef"},
 work:{en:"White Heat (1990)",fr:"White Heat (1990)"},
 stars:{n:3, years:"1995–1999", note:{en:"Three stars at thirty-three — the first British chef, and the youngest at that date. He returned them in 1999 and stopped cooking professionally.",fr:"Trois étoiles à trente-trois ans — premier chef britannique, et le plus jeune à cette date. Il les rendit en 1999 et cessa de cuisiner professionnellement."}},
 contribution:{en:"Trained under Albert Roux, Pierre Koffmann and Raymond Blanc. Harveys, opened in 1987, and its successor reached three stars in 1995. White Heat, a book of recipes and photographs of the kitchen at work, was widely read by young cooks.",
 fr:"Formé chez Albert Roux, Pierre Koffmann et Raymond Blanc. Harveys, ouvert en 1987, puis son successeur atteignirent trois étoiles en 1995. White Heat, livre de recettes et de photographies de la cuisine au travail, fut largement lu par les jeunes cuisiniers."},
 legacy:{en:"Gordon Ramsay and Heston Blumenthal are among those who worked in his kitchens.",
 fr:"Gordon Ramsay et Heston Blumenthal comptent parmi ceux qui travaillèrent dans ses cuisines."},
 ingredients:["beurre-de-baratte","tarragon","langoustine","truffle","pigeon","cream","shallot","white-wine-vinegar"]},

{id:"adria", name:"Ferran Adrià", born:1962,
 gender:"m", country:"ES", discipline:"cuisine",
 place:{en:"elBulli, Cala Montjoi, Catalonia",fr:"elBulli, Cala Montjoi, Catalogne"},
 role:{en:"Chef",fr:"Chef"},
 work:{en:"elBulli (chef from 1987; closed 2011)",fr:"elBulli (chef à partir de 1987 ; fermé en 2011)"},
 stars:{n:3, years:"1997–2011", note:{en:"Three stars from 1997 until the restaurant closed.",fr:"Trois étoiles de 1997 à la fermeture du restaurant."}},
 contribution:{en:"Ran the kitchen at elBulli, a restaurant on a Catalan cove open only part of the year, and spent the closed months in a Barcelona workshop developing techniques — foams, spherification, warm gels, deconstructed dishes — that were then served in tasting menus of several dozen courses.",
 fr:"Dirigea la cuisine d’elBulli, restaurant d’une crique catalane ouvert une partie de l’année seulement, et passait les mois de fermeture dans un atelier barcelonais à développer des techniques — écumes, sphérification, gels chauds, plats déconstruits — servies ensuite en menus dégustation de plusieurs dizaines de plats."},
 legacy:{en:"Techniques from elBulli spread through professional kitchens worldwide within a decade; the restaurant closed in 2011 and became a foundation.",
 fr:"Les techniques d’elBulli se répandirent dans les cuisines professionnelles du monde en une décennie ; le restaurant ferma en 2011 pour devenir une fondation."},
 ingredients:["olive-oil","almond","tomato","saffron","sea-urchin","oyster","pea","parmesan"]},

{id:"bottura", name:"Massimo Bottura", born:1962,
 gender:"m", country:"IT", discipline:"cuisine",
 place:{en:"Osteria Francescana, Modena",fr:"Osteria Francescana, Modène"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Food for Soul; the Refettorio (2015)",fr:"Food for Soul ; le Refettorio (2015)"},
 stars:{n:3, years:"2012", note:{en:"Three stars from 2012.",fr:"Trois étoiles dès 2012."}},
 contribution:{en:"Opened Osteria Francescana in 1995 with a kitchen that reworked Emilian dishes — tortellini, Parmigiano, balsamic — in forms that were initially resisted locally. During Expo Milan 2015 he opened the Refettorio Ambrosiano, a kitchen serving meals to people in need from surplus food, which grew into a network in several cities.",
 fr:"Ouvrit l’Osteria Francescana en 1995 avec une cuisine qui retravaillait les plats émiliens — tortellini, parmigiano, balsamique — sous des formes d’abord mal reçues localement. Pendant l’Expo de Milan 2015 il ouvrit le Refettorio Ambrosiano, cuisine servant des repas à des personnes dans le besoin à partir d’invendus, devenu un réseau dans plusieurs villes."},
 legacy:{en:"The Refettorio model has been reproduced in Rio, London, Paris and elsewhere under the Food for Soul foundation.",
 fr:"Le modèle du Refettorio a été reproduit à Rio, Londres, Paris et ailleurs sous la fondation Food for Soul."},
 ingredients:["parmesan","balsamic","flour-t55","egg","beurre-de-baratte","prosciutto","tomato","basil"]},

{id:"crenn", name:"Dominique Crenn", born:1965,
 gender:"f", country:"US", discipline:"cuisine",
 place:{en:"Atelier Crenn, San Francisco",fr:"Atelier Crenn, San Francisco"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Atelier Crenn (2011)",fr:"Atelier Crenn (2011)"},
 stars:{n:3, years:"2018", note:{en:"The first woman in the United States awarded three stars.",fr:"Première femme distinguée de trois étoiles aux États-Unis."}},
 contribution:{en:"Born in Brittany, she moved to San Francisco in 1988 and opened Atelier Crenn in 2011. Her tasting menus are presented as poems, each course a line, and the restaurant removed meat from its menu in 2018. Three stars followed the same year.",
 fr:"Née en Bretagne, elle s’installa à San Francisco en 1988 et ouvrit l’Atelier Crenn en 2011. Ses menus dégustation se présentent comme des poèmes, chaque plat une ligne, et le restaurant retira la viande de sa carte en 2018. Les trois étoiles suivirent la même année."},
 legacy:{en:"Her award ended a long absence of women at three stars in the United States.",
 fr:"Sa distinction mit fin à une longue absence de femmes à trois étoiles aux États-Unis."},
 ingredients:["oyster","sea-urchin","buckwheat","beurre-de-baratte","cream","apple","cider-vinegar","nori"]},

{id:"blumenthal", name:"Heston Blumenthal", born:1966,
 gender:"m", country:"GB", discipline:"cuisine",
 place:{en:"The Fat Duck, Bray, Berkshire",fr:"The Fat Duck, Bray, Berkshire"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"The Fat Duck (1995)",fr:"The Fat Duck (1995)"},
 stars:{n:3, years:"2004", note:{en:"Three stars from 2004, nine years after opening.",fr:"Trois étoiles dès 2004, neuf ans après l’ouverture."}},
 contribution:{en:"Largely self-taught, he opened The Fat Duck as a bistro in 1995 and turned it towards a scientific approach to cooking — measuring, testing and questioning received technique, with academic collaborators. Dishes drew on memory and perception as much as flavour.",
 fr:"Largement autodidacte, il ouvrit The Fat Duck en bistrot en 1995 et l’orienta vers une approche scientifique de la cuisine — mesurer, tester, questionner la technique reçue, avec des collaborateurs universitaires. Les plats jouaient sur la mémoire et la perception autant que sur le goût."},
 legacy:{en:"His television work brought the questioning of kitchen received wisdom to a wide public.",
 fr:"Son travail télévisuel porta auprès d’un large public la remise en question des idées reçues de cuisine."},
 ingredients:["beef","egg","cream","vanilla","dark-chocolate","lard","mustard","apple"]},

{id:"darroze", name:"Hélène Darroze", born:1967,
 gender:"f", country:"FR", discipline:"cuisine",
 place:{en:"Paris and London",fr:"Paris et Londres"},
 role:{en:"Chef and restaurateur",fr:"Cheffe et restauratrice"},
 work:{en:"Hélène Darroze at The Connaught (2008)",fr:"Hélène Darroze at The Connaught (2008)"},
 stars:{n:3, years:"2021", note:{en:"Three stars at The Connaught, London, in 2021.",fr:"Trois étoiles au Connaught, à Londres, en 2021."}},
 contribution:{en:"Fourth generation of a family of restaurateurs in the Landes, she trained with Alain Ducasse before opening in Paris in 1999 and taking the restaurant at the Connaught hotel in London in 2008. Her cooking draws on the south-west of France.",
 fr:"Quatrième génération d’une famille de restaurateurs des Landes, formée chez Alain Ducasse avant d’ouvrir à Paris en 1999 et de reprendre en 2008 le restaurant de l’hôtel Connaught à Londres. Sa cuisine puise dans le Sud-Ouest."},
 legacy:{en:"One of a small number of women to hold three stars, and among the few chefs to run starred kitchens in two capitals at once.",
 fr:"L’une des rares femmes à détenir trois étoiles, et parmi les rares chefs à diriger des cuisines étoilées dans deux capitales à la fois."},
 ingredients:["foie-gras","duck","piquillo","espelette","prune","beurre-de-baratte","chestnut","oyster"]},

{id:"pic", name:"Anne-Sophie Pic", born:1969,
 gender:"f", country:"FR", discipline:"cuisine",
 place:{en:"Maison Pic, Valence",fr:"Maison Pic, Valence"},
 role:{en:"Chef-patronne",fr:"Cheffe-propriétaire"},
 work:{en:"Maison Pic",fr:"Maison Pic"},
 stars:{n:3, years:"2007", note:{en:"Three stars in 2007 — the first woman in France since Marguerite Bise in 1951. By 2022 she held more stars across her restaurants than any woman before her.",fr:"Trois étoiles en 2007 — première femme en France depuis Marguerite Bise en 1951. En 2022 elle détenait plus d’étoiles, sur l’ensemble de ses restaurants, qu’aucune femme avant elle."}},
 contribution:{en:"Granddaughter of André Pic and daughter of Jacques Pic, she did not train as a cook, joining the family kitchen in 1992 shortly before her father’s death and taking it over in 1997. She regained the third star in 2007 and has since opened in Lausanne, Paris, London and Singapore.",
 fr:"Petite-fille d’André Pic et fille de Jacques Pic, elle ne se forma pas à la cuisine, rejoignant la cuisine familiale en 1992 peu avant la mort de son père et la reprenant en 1997. Elle retrouva la troisième étoile en 2007 et a depuis ouvert à Lausanne, Paris, Londres et Singapour."},
 legacy:{en:"Third generation at three stars in one house, and the most-starred woman in the guide’s history.",
 fr:"Troisième génération à trois étoiles dans une même maison, et la femme la plus étoilée de l’histoire du guide."},
 ingredients:["sea-bass","caviar","truffle","coffee","cream","beurre-de-baratte","chervil","white-chocolate"]},

{id:"redzepi", name:"René Redzepi", born:1977,
 gender:"m", country:"DK", discipline:"cuisine",
 place:{en:"Noma, Copenhagen",fr:"Noma, Copenhague"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Noma (2003); the New Nordic Cuisine manifesto (2004)",fr:"Noma (2003) ; le manifeste de la nouvelle cuisine nordique (2004)"},
 stars:{n:3, years:"2021", note:{en:"Three stars in 2021, in the guide’s first year of awarding three in Denmark.",fr:"Trois étoiles en 2021, première année où le guide en attribua trois au Danemark."}},
 contribution:{en:"Opened Noma in a Copenhagen warehouse in 2003 with a kitchen restricted to ingredients of the Nordic region — foraged plants, shore and forest produce, fermentation. The 2004 manifesto he co-signed set out that approach for the region’s cooks.",
 fr:"Ouvrit Noma dans un entrepôt de Copenhague en 2003 avec une cuisine limitée aux produits de la région nordique — plantes cueillies, produits de rivage et de forêt, fermentation. Le manifeste de 2004 qu’il cosigna formula cette approche pour les cuisiniers de la région."},
 legacy:{en:"Foraging and fermentation moved from margin to mainstream in professional kitchens over the following fifteen years, with Noma’s fermentation lab widely cited.",
 fr:"Cueillette et fermentation passèrent de la marge au courant dominant des cuisines professionnelles en quinze ans, le laboratoire de fermentation de Noma étant largement cité."},
 ingredients:["oyster","nori","sea-buckthorn","juniper","buckwheat","creme-fraiche","lovage","beetroot"]},

{id:"munk", name:"Rasmus Munk", born:1991,
 gender:"m", country:"DK", discipline:"cuisine",
 place:{en:"Alchemist, Refshaleøen, Copenhagen",fr:"Alchemist, Refshaleøen, Copenhague"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Alchemist (2015; reopened at scale 2019)",fr:"Alchemist (2015 ; rouvert à grande échelle en 2019)"},
 stars:{n:2, years:"2020", note:{en:"Two stars within a year of the 2019 reopening.",fr:"Deux étoiles dans l’année suivant la réouverture de 2019."}},
 contribution:{en:"Opened the first Alchemist in 2015 and a far larger one in a former shipyard in 2019, structured as an evening of around fifty courses across several rooms and a planetarium dome, with themes drawn from social and environmental questions. He describes the approach as holistic cuisine. He also founded the JunkFood project, serving meals to people experiencing homelessness.",
 fr:"Ouvrit le premier Alchemist en 2015 et un second, bien plus vaste, dans un ancien chantier naval en 2019, conçu comme une soirée d’une cinquantaine de plats à travers plusieurs salles et un dôme planétarium, sur des thèmes sociaux et environnementaux. Il nomme cette approche cuisine holistique. Il fonda aussi le projet JunkFood, servant des repas à des personnes sans domicile."},
 legacy:{en:"Alchemist has become a reference point for restaurants conceived as staged experiences rather than menus.",
 fr:"Alchemist est devenu une référence pour les restaurants conçus comme des expériences mises en scène plutôt que comme des cartes."},
 ingredients:["oyster","sea-urchin","caviar","beetroot","dark-chocolate","lamb","nori","cream"]},

{id:"vildgaard", name:"Eric Vildgaard", born:1984, approx:true,
 gender:"m", country:"DK", discipline:"cuisine",
 place:{en:"Jordnær, Gentofte, north of Copenhagen",fr:"Jordnær, Gentofte, au nord de Copenhague"},
 role:{en:"Chef-patron, with Tina Kragh Vildgaard",fr:"Chef-propriétaire, avec Tina Kragh Vildgaard"},
 work:{en:"Jordnær (2017)",fr:"Jordnær (2017)"},
 stars:{n:3, years:"2024", note:{en:"One star in 2018, two in 2020, three in 2024 — Denmark’s second three-star restaurant.",fr:"Une étoile en 2018, deux en 2020, trois en 2024 — deuxième trois étoiles du Danemark."}},
 contribution:{en:"Opened Jordnær in 2017 in a suburban hotel dining room with his wife, who runs the front of house. The kitchen is built largely around seafood and shellfish, and the restaurant moved through the three star levels in six years.",
 fr:"Ouvrit Jordnær en 2017 dans la salle d’un hôtel de banlieue avec son épouse, qui tient la salle. La cuisine s’articule largement autour des poissons et coquillages, et le restaurant franchit les trois niveaux d’étoiles en six ans."},
 legacy:{en:"Its rise made Jordnær the first Danish restaurant outside central Copenhagen to reach three stars.",
 fr:"Son ascension fit de Jordnær le premier restaurant danois hors du centre de Copenhague à atteindre trois étoiles."},
 ingredients:["langoustine","caviar","oyster","scallop","turbot","cream","beurre-de-baratte","chives"]},

{id:"marcon", name:"Régis Marcon", born:1956,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Saint-Bonnet-le-Froid, Haute-Loire",fr:"Saint-Bonnet-le-Froid, Haute-Loire"},
 role:{en:"Chef-patron, with his son Jacques",fr:"Chef-propriétaire, avec son fils Jacques"},
 work:{en:"Bocuse d’Or (1995)",fr:"Bocuse d’Or (1995)"},
 stars:{n:3, years:"2005", note:{en:"Three stars from 2005, in a village of about two hundred people at 1,100 metres.",fr:"Trois étoiles dès 2005, dans un village d’environ deux cents habitants à 1 100 mètres."}},
 contribution:{en:"Took over his mother’s inn in a village on the Haute-Loire plateau and won the Bocuse d’Or in 1995 with a dish built on wild mushrooms. The restaurant reached three stars in 2005 and has kept them; mushrooms and the lentils of Le Puy remain central to the kitchen.",
 fr:"Reprit l’auberge maternelle dans un village du plateau de Haute-Loire et remporta le Bocuse d’Or en 1995 avec un plat bâti sur les champignons sauvages. Le restaurant atteignit trois étoiles en 2005 et les a conservées ; champignons et lentilles du Puy restent au centre de la cuisine."},
 legacy:{en:"The village has become a destination on the strength of the restaurant, with a hotel, a bakery and a cookery school around it.",
 fr:"Le village est devenu une destination grâce au restaurant, avec hôtel, boulangerie et école de cuisine autour."},
 ingredients:["porcini","morel","lentille-du-puy","chanterelle","black-trumpet","cream","beurre-de-baratte","hazelnut"]},

{id:"renaut", name:"Emmanuel Renaut", born:1968,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Flocons de Sel, Megève",fr:"Flocons de Sel, Megève"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Meilleur Ouvrier de France (2004)",fr:"Meilleur Ouvrier de France (2004)"},
 stars:{n:3, years:"2012", note:{en:"Three stars from 2012.",fr:"Trois étoiles dès 2012."}},
 contribution:{en:"Trained at the Crillon in Paris and then with Marc Veyrat before opening Flocons de Sel in Megève in 1998, later moving it to a chalet above the town. His cooking draws on the lakes, forests and pastures of the Haute-Savoie — freshwater fish, alpine herbs, mountain dairy.",
 fr:"Formé au Crillon à Paris puis chez Marc Veyrat, il ouvrit Flocons de Sel à Megève en 1998, avant de l’installer dans un chalet au-dessus de la ville. Sa cuisine puise dans les lacs, forêts et alpages de Haute-Savoie — poissons d’eau douce, herbes alpines, laitages de montagne."},
 legacy:{en:"With Veyrat and Marcon he is among the chefs who established mountain and plateau cooking at three-star level.",
 fr:"Avec Veyrat et Marcon, il compte parmi les chefs qui ont porté la cuisine de montagne et de plateau au niveau trois étoiles."},
 ingredients:["char","reblochon","beaufort","morel","hazelnut","cream","lovage","butter"]},

{id:"roca", name:"Joan, Josep et Jordi Roca", born:1964,
 gender:"m", country:"ES", discipline:"cuisine",
 place:{en:"El Celler de Can Roca, Girona",fr:"El Celler de Can Roca, Gérone"},
 role:{en:"Brothers — chef, sommelier, pastry chef",fr:"Frères — chef, sommelier, pâtissier"},
 work:{en:"El Celler de Can Roca (1986)",fr:"El Celler de Can Roca (1986)"},
 stars:{n:3, years:"2009", note:{en:"Three stars from 2009. Ranked first in the World’s 50 Best in 2013 and 2015.",fr:"Trois étoiles dès 2009. Classé premier au World’s 50 Best en 2013 et 2015."}},
 contribution:{en:"Joan (b. 1964) and Josep (b. 1966) opened the restaurant beside their parents’ bar in 1986; Jordi (b. 1978) joined as pastry chef. Each brother runs one discipline, and the kitchen is known for techniques developed in-house — distillation, cooking in vacuum at low temperature, and desserts built on perfumes.",
 fr:"Joan (né en 1964) et Josep (né en 1966) ouvrirent le restaurant à côté du bar de leurs parents en 1986 ; Jordi (né en 1978) les rejoignit comme pâtissier. Chaque frère tient une discipline, et la cuisine est connue pour des techniques développées en interne — distillation, cuisson sous vide à basse température, desserts bâtis sur des parfums."},
 legacy:{en:"Their parents’ bar still serves lunch next door; the brothers have said the family kitchen is where the restaurant began.",
 fr:"Le bar des parents sert encore le déjeuner à côté ; les frères ont dit que la cuisine familiale est le lieu où le restaurant a commencé."},
 ingredients:["shrimp","olive-oil","sea-urchin","dark-chocolate","truffle","saffron","almond","cream"]},

{id:"colagreco", name:"Mauro Colagreco", born:1976,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Mirazur, Menton — born in La Plata, Argentina",fr:"Mirazur, Menton — né à La Plata, Argentine"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Mirazur (2006)",fr:"Mirazur (2006)"},
 stars:{n:3, years:"2019", note:{en:"The first chef not born in France to be awarded three stars in France. Ranked first in the World’s 50 Best the same year.",fr:"Premier chef né hors de France distingué de trois étoiles en France. Classé premier au World’s 50 Best la même année."}},
 contribution:{en:"Trained in Argentina and then in France with Bernard Loiseau, Alain Passard and Alain Ducasse. He opened Mirazur in 2006 in a building above the sea at the Italian border, with terraced gardens that supply much of the kitchen. Menus are organised around the lunar calendar and the garden’s cycles.",
 fr:"Formé en Argentine puis en France chez Bernard Loiseau, Alain Passard et Alain Ducasse. Il ouvrit Mirazur en 2006 dans un bâtiment au-dessus de la mer, à la frontière italienne, avec des jardins en terrasses qui fournissent une grande part de la cuisine. Les menus s’organisent selon le calendrier lunaire et les cycles du jardin."},
 legacy:{en:"Mirazur was the first restaurant certified plastic-free, in 2020.",
 fr:"Mirazur fut en 2020 le premier restaurant certifié sans plastique."},
 ingredients:["beetroot","lemon","olive-oil","sea-bass","fava-bean","lemon","artichoke","honey"]},

{id:"kofoed", name:"Rasmus Kofoed", born:1974,
 gender:"m", country:"DK", discipline:"cuisine",
 place:{en:"Geranium, Copenhagen",fr:"Geranium, Copenhague"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Bocuse d’Or gold (2011)",fr:"Bocuse d’Or, médaille d’or (2011)"},
 stars:{n:3, years:"2016", note:{en:"Denmark’s first three-star restaurant. Ranked first in the World’s 50 Best in 2022.",fr:"Premier trois étoiles du Danemark. Classé premier au World’s 50 Best en 2022."}},
 contribution:{en:"Won bronze, silver and then gold at the Bocuse d’Or across three attempts. Opened Geranium in 2007 and moved it in 2010 to the eighth floor of the national football stadium. In 2022 the restaurant removed meat from its menu, keeping fish and shellfish.",
 fr:"Remporta bronze, argent puis or au Bocuse d’Or en trois participations. Ouvrit Geranium en 2007 et l’installa en 2010 au huitième étage du stade national de football. En 2022 le restaurant retira la viande de sa carte, conservant poissons et coquillages."},
 legacy:{en:"Geranium and Noma between them made Copenhagen a destination for fine dining within a decade.",
 fr:"Geranium et Noma firent ensemble de Copenhague une destination de haute cuisine en une décennie."},
 ingredients:["langoustine","oyster","caviar","celeriac","juniper","creme-fraiche","dill","beetroot"]},

{id:"veyrat", name:"Marc Veyrat", born:1950,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Annecy, then Megève and Manigod",fr:"Annecy, puis Megève et Manigod"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Cooking with alpine plants",fr:"La cuisine des plantes alpines"},
 stars:{n:3, years:"1995 · 2001", note:{en:"Three stars at the Auberge de l’Éridan in 1995 and at La Ferme de mon Père in 2001 — six at once.",fr:"Trois étoiles à l’Auberge de l’Éridan en 1995 et à La Ferme de mon Père en 2001 — six à la fois."}},
 contribution:{en:"Built a cooking on plants gathered in the Savoie mountains — herbs, roots, flowers — used both for flavour and as the basis of techniques he developed himself. He held three stars at two restaurants simultaneously and was twice given the maximum 20/20 by the Gault & Millau guide.",
 fr:"Bâtit une cuisine sur les plantes cueillies dans les montagnes de Savoie — herbes, racines, fleurs — employées pour le goût comme pour des techniques de son cru. Il détint trois étoiles dans deux restaurants à la fois et reçut deux fois le 20/20 du Gault & Millau."},
 legacy:{en:"Emmanuel Renaut trained in his kitchen; foraged alpine plants in high cooking are largely his legacy in France.",
 fr:"Emmanuel Renaut se forma dans sa cuisine ; l’usage des plantes alpines cueillies en haute cuisine est en grande part son héritage en France."},
 ingredients:["lovage","sorrel","wild-garlic","char","cream","beaufort","hazelnut","angelica"]},

{id:"alleno", name:"Yannick Alléno", born:1968,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Pavillon Ledoyen, Paris; Courchevel",fr:"Pavillon Ledoyen, Paris ; Courchevel"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"Sauces: Reflections of a Chef (2014)",fr:"Sauces, réflexions d’un cuisinier (2014)"},
 stars:{n:3, years:"2015 · 2017", note:{en:"Three stars at Ledoyen in 2015 and at Le 1947 in Courchevel in 2017.",fr:"Trois étoiles à Ledoyen en 2015 et au 1947 à Courchevel en 2017."}},
 contribution:{en:"Held three stars at Le Meurice before taking over Ledoyen in 2014. He has concentrated on sauces, replacing long reduction with extraction and cryoconcentration — freezing a liquid and removing the ice to concentrate flavour without heat — and has published on the subject.",
 fr:"Détint trois étoiles au Meurice avant de reprendre Ledoyen en 2014. Il s’est concentré sur les sauces, remplaçant la réduction longue par l’extraction et la cryoconcentration — geler un liquide et retirer la glace pour concentrer le goût sans chaleur — et a publié sur le sujet."},
 legacy:{en:"His sauce methods have been taken up in professional kitchens as an alternative to classical reduction.",
 fr:"Ses méthodes de sauce ont été reprises dans les cuisines professionnelles comme alternative à la réduction classique."},
 ingredients:["shallot","beurre-de-baratte","cream","truffle","langoustine","white-wine-vinegar","mushroom","chicken"]},

{id:"donckele", name:"Arnaud Donckele", born:1977,
 gender:"m", country:"FR", discipline:"cuisine",
 place:{en:"Saint-Tropez and Paris",fr:"Saint-Tropez et Paris"},
 role:{en:"Chef",fr:"Chef"},
 work:{en:"La Vague d’Or; Plénitude (2021)",fr:"La Vague d’Or ; Plénitude (2021)"},
 stars:{n:3, years:"2013 · 2022", note:{en:"Three stars at La Vague d’Or in 2013 and at Plénitude in Paris in 2022, its first year.",fr:"Trois étoiles à La Vague d’Or en 2013 et à Plénitude à Paris en 2022, dès sa première année."}},
 contribution:{en:"Trained with Alain Ducasse and Michel Guérard before taking the kitchen of the Résidence de la Pinède in Saint-Tropez, where he reached three stars in 2013. In 2021 he opened Plénitude in the Cheval Blanc hotel in Paris and was awarded three stars on its first appearance in the guide. His cooking is centred on sauces, several to a plate.",
 fr:"Formé chez Alain Ducasse et Michel Guérard avant de prendre la cuisine de la Résidence de la Pinède à Saint-Tropez, où il atteignit trois étoiles en 2013. En 2021 il ouvrit Plénitude à l’hôtel Cheval Blanc à Paris et reçut trois étoiles dès sa première parution au guide. Sa cuisine est centrée sur les sauces, plusieurs par assiette."},
 legacy:{en:"Among a small number of chefs to hold three stars at two restaurants in France at once.",
 fr:"Parmi les rares chefs à détenir trois étoiles dans deux restaurants en France à la fois."},
 ingredients:["sea-bass","red-mullet","olive-oil","fennel","tomato","beurre-de-baratte","saffron","basil"]},

{id:"aduriz", name:"Andoni Luis Aduriz", born:1971,
 gender:"m", country:"ES", discipline:"cuisine",
 place:{en:"Mugaritz, Errenteria, Basque Country",fr:"Mugaritz, Errenteria, Pays basque"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Mugaritz (1998)",fr:"Mugaritz (1998)"},
 stars:{n:2, years:"2005", note:{en:"Two stars from 2005.",fr:"Deux étoiles dès 2005."}},
 contribution:{en:"Worked at elBulli in the early 1990s and opened Mugaritz in a farmhouse outside San Sebastián in 1998. The restaurant closes for several months each year for research and reopens with a new menu; dishes are frequently designed around texture, ambiguity or discomfort rather than pleasure alone.",
 fr:"Travailla à elBulli au début des années 1990 et ouvrit Mugaritz dans une ferme près de Saint-Sébastien en 1998. Le restaurant ferme plusieurs mois chaque année pour la recherche et rouvre avec une carte nouvelle ; les plats sont souvent conçus autour de la texture, de l’ambiguïté ou de l’inconfort plutôt que du seul plaisir."},
 legacy:{en:"Mugaritz is often cited as the most research-oriented restaurant in Spain after elBulli’s closure.",
 fr:"Mugaritz est souvent cité comme le restaurant le plus orienté vers la recherche en Espagne depuis la fermeture d’elBulli."},
 ingredients:["potato","hake","cod","olive-oil","egg","sea-urchin","white-beans","manchego"]},

{id:"berasategui", name:"Martín Berasategui", born:1960,
 gender:"m", country:"ES", discipline:"cuisine",
 place:{en:"Lasarte-Oria, Basque Country",fr:"Lasarte-Oria, Pays basque"},
 role:{en:"Chef and restaurateur",fr:"Chef et restaurateur"},
 work:{en:"Restaurante Martín Berasategui (1993)",fr:"Restaurante Martín Berasategui (1993)"},
 stars:{n:3, years:"2001", note:{en:"Three stars at Lasarte from 2001. Across his restaurants he has held more stars than any other Spanish chef.",fr:"Trois étoiles à Lasarte dès 2001. Sur l’ensemble de ses restaurants, il a détenu plus d’étoiles qu’aucun autre chef espagnol."}},
 contribution:{en:"Began in his parents’ restaurant in San Sebastián’s old town at fifteen and opened his own house at Lasarte in 1993, reaching three stars in 2001. He has since opened restaurants in Barcelona, Tenerife, Bilbao and elsewhere, several with stars of their own.",
 fr:"Commença à quinze ans dans le restaurant de ses parents dans la vieille ville de Saint-Sébastien et ouvrit sa propre maison à Lasarte en 1993, trois étoiles en 2001. Il a depuis ouvert à Barcelone, Tenerife, Bilbao et ailleurs, plusieurs de ces restaurants étant étoilés."},
 legacy:{en:"A large number of Basque and Spanish chefs of the following generation trained in his kitchens.",
 fr:"Nombre de chefs basques et espagnols de la génération suivante se formèrent dans ses cuisines."},
 ingredients:["hake","squid","olive-oil","foie-gras","piquillo","cod","cream","truffle"]},

{id:"arzak", name:"Elena Arzak", born:1969,
 gender:"f", country:"ES", discipline:"cuisine",
 place:{en:"Arzak, San Sebastián",fr:"Arzak, Saint-Sébastien"},
 role:{en:"Co-chef with her father, Juan Mari Arzak",fr:"Co-cheffe avec son père, Juan Mari Arzak"},
 work:{en:"Arzak — the family house since 1897",fr:"Arzak — la maison familiale depuis 1897"},
 stars:{n:3, years:"1989", note:{en:"The house has held three stars since 1989, under her father; she has shared the kitchen since the late 1990s.",fr:"La maison détient trois étoiles depuis 1989, sous son père ; elle en partage la cuisine depuis la fin des années 1990."}},
 contribution:{en:"Fourth generation of the family restaurant, trained in Switzerland and in kitchens including elBulli, Gagnaire and Troisgros before returning to run the house alongside her father. Arzak has a laboratory above the restaurant with a bank of several thousand ingredients used for development.",
 fr:"Quatrième génération du restaurant familial, formée en Suisse et dans des cuisines dont elBulli, Gagnaire et Troisgros avant de revenir tenir la maison avec son père. Arzak dispose d’un laboratoire au-dessus du restaurant, avec une banque de plusieurs milliers d’ingrédients pour la recherche."},
 legacy:{en:"Named the Veuve Clicquot World’s Best Female Chef in 2012.",
 fr:"Nommée Veuve Clicquot World’s Best Female Chef en 2012."},
 ingredients:["hake","squid-ink","piquillo","egg","olive-oil","dark-chocolate","cod","almond"]},

{id:"smyth", name:"Clare Smyth", born:1978,
 gender:"f", country:"GB", discipline:"cuisine",
 place:{en:"Core, Notting Hill, London",fr:"Core, Notting Hill, Londres"},
 role:{en:"Chef-patron",fr:"Cheffe-propriétaire"},
 work:{en:"Core by Clare Smyth (2017)",fr:"Core by Clare Smyth (2017)"},
 stars:{n:3, years:"2021", note:{en:"The first British woman awarded three stars.",fr:"Première femme britannique distinguée de trois étoiles."}},
 contribution:{en:"Born in Northern Ireland, she trained under Alain Ducasse and then ran Gordon Ramsay’s Royal Hospital Road as chef-patron, the first woman to hold three stars in charge of a British kitchen. She opened Core in 2017 with a menu built around British produce and reached three stars in four years.",
 fr:"Née en Irlande du Nord, formée chez Alain Ducasse, elle dirigea ensuite le Royal Hospital Road de Gordon Ramsay comme cheffe-propriétaire, première femme à tenir trois étoiles à la tête d’une cuisine britannique. Elle ouvrit Core en 2017 autour des produits britanniques et atteignit trois étoiles en quatre ans."},
 legacy:{en:"Named the World’s Best Female Chef in 2018.",
 fr:"Nommée World’s Best Female Chef en 2018."},
 ingredients:["potato","lamb","scallop","beurre-de-baratte","cream","apple","oyster","truffle"]},

{id:"romito", name:"Niko Romito", born:1974,
 gender:"m", country:"IT", discipline:"cuisine",
 place:{en:"Reale, Castel di Sangro, Abruzzo",fr:"Reale, Castel di Sangro, Abruzzes"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Reale (family restaurant from 2000)",fr:"Reale (restaurant familial dès 2000)"},
 stars:{n:3, years:"2014", note:{en:"Three stars from 2014, in a converted monastery in the Apennines.",fr:"Trois étoiles dès 2014, dans un monastère reconverti des Apennins."}},
 contribution:{en:"Self-taught, he took over his late father’s trattoria in 2000 with his sister Cristiana and moved it to a sixteenth-century monastery in 2011. His cooking reduces dishes to few elements and concentrated single flavours. He also runs a cookery school and the restaurants of the Bulgari hotels.",
 fr:"Autodidacte, il reprit en 2000 la trattoria de son père disparu avec sa sœur Cristiana et l’installa en 2011 dans un monastère du XVIe siècle. Sa cuisine réduit les plats à peu d’éléments et à des saveurs uniques concentrées. Il dirige aussi une école et les restaurants des hôtels Bulgari."},
 legacy:{en:"His work on institutional cooking — a project to improve hospital food — extended his method beyond the restaurant.",
 fr:"Son travail sur la restauration collective — un projet d’amélioration des repas hospitaliers — a étendu sa méthode au-delà du restaurant."},
 ingredients:["flour-t55","tomato","olive-oil","potato","onion","lamb","pecorino","sage"]},

{id:"crippa", name:"Enrico Crippa", born:1971,
 gender:"m", country:"IT", discipline:"cuisine",
 place:{en:"Piazza Duomo, Alba, Piedmont",fr:"Piazza Duomo, Alba, Piémont"},
 role:{en:"Chef",fr:"Chef"},
 work:{en:"Insalata 21… 31… 41… 51",fr:"Insalata 21… 31… 41… 51"},
 stars:{n:3, years:"2012", note:{en:"Three stars from 2012.",fr:"Trois étoiles dès 2012."}},
 contribution:{en:"Trained with Gualtiero Marchesi from sixteen, then with Adrià and Bras, and worked three years in Japan. He opened Piazza Duomo in Alba in 2005 with the Ceretto wine family. His signature salad assembles dozens of leaves, herbs and flowers from the restaurant’s own gardens, the number changing with the season.",
 fr:"Formé chez Gualtiero Marchesi dès seize ans, puis chez Adrià et Bras, avec trois années au Japon. Il ouvrit Piazza Duomo à Alba en 2005 avec la famille viticole Ceretto. Sa salade signature assemble des dizaines de feuilles, d’herbes et de fleurs des jardins du restaurant, en nombre variable selon la saison."},
 legacy:{en:"The restaurant put Alba on the fine-dining map beyond its white truffle season.",
 fr:"Le restaurant plaça Alba sur la carte de la haute cuisine au-delà de la saison de la truffe blanche."},
 ingredients:["white-truffle","lettuce","roquette","purslane","borage","hazelnut","egg","olive-oil"]},

{id:"ros", name:"Ana Roš", born:1972,
 gender:"f", country:"SI", discipline:"cuisine",
 place:{en:"Hiša Franko, Kobarid, Slovenia",fr:"Hiša Franko, Kobarid, Slovénie"},
 role:{en:"Chef-patron",fr:"Cheffe-propriétaire"},
 work:{en:"Hiša Franko",fr:"Hiša Franko"},
 stars:{n:3, years:"2023", note:{en:"Two stars in 2020, the guide’s first year in Slovenia; three in 2023.",fr:"Deux étoiles en 2020, première année du guide en Slovénie ; trois en 2023."}},
 contribution:{en:"Trained as a diplomat and never professionally as a cook; she took over the kitchen of her partner’s family inn in the Soča valley in 2000 and taught herself. The kitchen works with the valley’s produce — trout, cheese from alpine dairies, foraged plants — and closes in winter.",
 fr:"Formée à la diplomatie et jamais à la cuisine professionnellement ; elle reprit en 2000 la cuisine de l’auberge familiale de son compagnon dans la vallée de la Soča et apprit seule. La cuisine travaille les produits de la vallée — truite, fromages d’alpage, plantes cueillies — et ferme l’hiver."},
 legacy:{en:"Named the World’s Best Female Chef in 2017, before Slovenia had a Michelin guide.",
 fr:"Nommée World’s Best Female Chef en 2017, avant que la Slovénie n’ait un guide Michelin."},
 ingredients:["trout","cream","kale","hazelnut","elderberry","sorrel","beetroot","honey"]},

{id:"frantzen", name:"Björn Frantzén", born:1977,
 gender:"m", country:"SE", discipline:"cuisine",
 place:{en:"Frantzén, Stockholm; Zén, Singapore",fr:"Frantzén, Stockholm ; Zén, Singapour"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Frantzén (2008; reopened 2017)",fr:"Frantzén (2008 ; rouvert en 2017)"},
 stars:{n:3, years:"2018", note:{en:"Sweden’s first three-star restaurant. Zén in Singapore reached three stars in 2021.",fr:"Premier trois étoiles de Suède. Zén, à Singapour, atteignit trois étoiles en 2021."}},
 contribution:{en:"A former professional footballer, he trained in London and Paris before opening Frantzén/Lindeberg in Stockholm in 2008. The restaurant reopened in 2017 in a townhouse over several floors, with guests moving through the building, and reached three stars the following year. His cooking combines Nordic produce with Japanese technique.",
 fr:"Ancien footballeur professionnel, formé à Londres et Paris avant d’ouvrir Frantzén/Lindeberg à Stockholm en 2008. Le restaurant rouvrit en 2017 dans un hôtel particulier sur plusieurs étages, les convives se déplaçant dans le bâtiment, et atteignit trois étoiles l’année suivante. Sa cuisine allie produits nordiques et technique japonaise."},
 legacy:{en:"The multi-floor format has since been adopted by his other restaurants and imitated elsewhere.",
 fr:"Le format sur plusieurs étages a depuis été repris par ses autres restaurants et imité ailleurs."},
 ingredients:["langoustine","caviar","truffle","beurre-de-baratte","soy-sauce","wasabi","cream","chives"]},

{id:"bang", name:"Esben Holmboe Bang", born:1982,
 gender:"m", country:"NO", discipline:"cuisine",
 place:{en:"Maaemo, Oslo",fr:"Maaemo, Oslo"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Maaemo (2010)",fr:"Maaemo (2010)"},
 stars:{n:3, years:"2016", note:{en:"Norway’s first three-star restaurant, six years after opening.",fr:"Premier trois étoiles de Norvège, six ans après l’ouverture."}},
 contribution:{en:"Danish-born, he opened Maaemo in Oslo in 2010 with a kitchen restricted to Norwegian produce, much of it organic or wild, and a menu built on the country’s coastal and forest ingredients. It was the first Nordic restaurant outside Denmark to reach three stars.",
 fr:"Né au Danemark, il ouvrit Maaemo à Oslo en 2010 avec une cuisine limitée aux produits norvégiens, en grande part biologiques ou sauvages, et une carte bâtie sur les ingrédients de côte et de forêt du pays. Ce fut le premier restaurant nordique hors du Danemark à atteindre trois étoiles."},
 legacy:{en:"Maaemo established that the New Nordic approach could reach the top level outside Copenhagen.",
 fr:"Maaemo montra que l’approche nouvelle nordique pouvait atteindre le plus haut niveau hors de Copenhague."},
 ingredients:["oyster","langoustine","creme-fraiche","juniper","sea-buckthorn","beetroot","dill","mackerel"]},

{id:"martinez", name:"Virgilio Martínez", born:1977,
 gender:"m", country:"PE", discipline:"cuisine",
 place:{en:"Central, Lima; Mil, Cusco",fr:"Central, Lima ; Mil, Cuzco"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Central (2008); Mater Iniciativa",fr:"Central (2008) ; Mater Iniciativa"},
 contribution:{en:"Trained in London and New York before returning to Lima to open Central in 2008. Its tasting menu is organised by altitude, each course drawn from a different elevation of Peru’s ecosystems, from the Pacific to above four thousand metres. Mater Iniciativa, run with his sister Malena, is a research centre cataloguing Peruvian ingredients.",
 fr:"Formé à Londres et New York avant de revenir à Lima ouvrir Central en 2008. Son menu dégustation s’organise par altitude, chaque plat tiré d’un étage différent des écosystèmes péruviens, du Pacifique à plus de quatre mille mètres. Mater Iniciativa, dirigé avec sa sœur Malena, est un centre de recherche recensant les ingrédients péruviens."},
 legacy:{en:"Central was ranked first in the World’s 50 Best in 2023, the first South American restaurant to hold the position.",
 fr:"Central fut classé premier au World’s 50 Best en 2023, premier restaurant sud-américain à cette place."},
 ingredients:["potato","quinoa","lime","corn","chili","avocado","cilantro","dark-chocolate"]},

{id:"grolet", name:"Cédric Grolet", born:1985,
 gender:"m", country:"FR", discipline:"patisserie",
 place:{en:"Le Meurice, Paris",fr:"Le Meurice, Paris"},
 role:{en:"Pastry chef",fr:"Pâtissier"},
 work:{en:"Trompe-l’œil fruits",fr:"Les fruits en trompe-l’œil"},
 contribution:{en:"Pastry chef at the Meurice hotel from 2013, after training at Fauchon. He is known for sculpted desserts that reproduce the appearance of whole fruits — a lemon, a hazelnut, an apple — with a thin shell around a mousse and a centre of the fruit itself. He opened his own shops from 2018.",
 fr:"Chef pâtissier de l’hôtel Meurice à partir de 2013, après une formation chez Fauchon. Connu pour des desserts sculptés reproduisant l’apparence de fruits entiers — un citron, une noisette, une pomme — coque fine autour d’une mousse et cœur du fruit lui-même. Il ouvrit ses propres boutiques à partir de 2018."},
 legacy:{en:"Named the World’s Best Pastry Chef in 2018; his fruit desserts have been widely imitated.",
 fr:"Nommé World’s Best Pastry Chef en 2018 ; ses fruits en trompe-l’œil ont été largement imités."},
 ingredients:["lemon","hazelnut","apple","vanilla","dark-chocolate","cream","sugar","beurre-de-baratte"]}

]);
