window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"acorn",cat:"nuts",name:{en:"Acorn",fr:"Gland"},latin:"Quercus spp.",
origin:{en:"Temperate oak woodland",fr:"Chênaies tempérées"},season:[9,10,11],
flavor:["bitter","earthy","nutty"],
story:{en:"In central California the acorn was the staple grain: the meal was spread in a shallow sand basin and cold stream water run through it for hours until the tannin was gone, a technique with no European equivalent. Those same tannins are why wine and whisky are aged in oak — what makes the nut inedible is what makes the barrel worth having.",
fr:"Dans le centre de la Californie, le gland était la céréale de base : la farine, étalée dans une cuvette de sable, était lessivée des heures durant à l’eau froide du ruisseau jusqu’à disparition du tanin — une technique sans équivalent européen. Ce sont ces mêmes tanins qui font vieillir vin et whisky sous le chêne : ce qui rend le fruit immangeable fait la valeur du fût."},
tip:{en:"Leach cold, not hot. Cold water pulls the tannin and leaves the starch able to gel, which is exactly what dotori-muk needs; hot leaching gelatinises the starch on the spot and leaves you a flour that can only ever be baked.",
fr:"Lessivez à froid, jamais à chaud. L’eau froide emporte le tanin en laissant l’amidon capable de prendre, ce qu’exige le dotori-muk ; à chaud, l’amidon gélatinise sur place et il ne vous reste qu’une farine bonne à cuire au four."},
pairs:["soy-sauce","sesame-oil","gochugaru","garlic-chives","honey","chestnut"],
svg:'<path class="f2 sf" d="M38 42h20q0 22-10 30-10-8-10-30z"/><path class="f3 sf" d="M35 32q13-6 26 0 2 10-13 10t-13-10z"/><path class="s" d="M48 24v8"/>'},

{id:"almond",cat:"nuts",name:{en:"Almond",fr:"Amande"},latin:"Prunus amygdalus",
origin:{en:"Central & Western Asia",fr:"Asie centrale & occidentale"},season:[],
flavor:["nutty","sweet","milky"],
story:{en:"The almond tree flowers before it leafs — a white promise in bare February orchards that van Gogh painted for his newborn nephew. Sugared almonds have marked weddings since Roman times: bitterness coated in sweetness, like marriage, says the joke.",
fr:"L’amandier fleurit avant de feuiller — une promesse blanche dans les vergers nus de février, que van Gogh peignit pour son neveu nouveau-né. Les dragées marquent les noces depuis Rome : de l’amer enrobé de sucre, comme le mariage, dit la plaisanterie."},
tip:{en:"Toast them always — raw almonds are only a rumour of themselves. Ground with sugar, they become frangipane, the soul of French tarts.",
fr:"Torréfiez-les toujours — l’amande crue n’est qu’une rumeur d’elle-même. Moulue avec du sucre, elle devient la frangipane, âme des tartes françaises."},
pairs:["peach","raspberry","dark-chocolate","honey","cherry","saffron"],
svg:'<path class="f2 sf" d="M48 30q14 14 12 30-1 14-12 14t-12-14q-2-16 12-30z"/><path class="dot" d="M43 50a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M50 44a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M50 58a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M43 62a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/>'},

{id:"almond-flour",cat:"nuts",name:{en:"Almond flour",fr:"Poudre d'amande"},latin:"Prunus dulcis",
origin:{en:"Nut mills, Spain and California",fr:"Moulins à fruits secs, Espagne et Californie"},season:[],
flavor:["nutty","mild","sweet"],
story:{en:"The macaron base is called tant pour tant, as much for as much: equal weights of almond powder and icing sugar. The sugar is not only sweetening — it takes up the oil the kernel releases as it is ground, and it is the only way to get almond that fine without turning it into paste.",
fr:"La base du macaron s'appelle le tant pour tant : autant d'amande en poudre que de sucre glace, au poids. Le sucre n'est pas seulement là pour sucrer — il absorbe l'huile que l'amande libère au broyage, et c'est le seul moyen de descendre aussi fin sans obtenir une pâte."},
tip:{en:"Buy it by fineness, and sift it together with the icing sugar rather than alone: whatever stays in the sieve is oiled clumps, not coarse nut, and re-grinding them makes it worse. If a batter looks greasy, the powder was warm.",
fr:"Achetez-la selon sa finesse et tamisez-la avec le sucre glace plutôt que seule : ce qui reste dans le tamis, ce sont des grumeaux huileux et non de la poudre grossière, et les rebroyer aggrave tout. Si l'appareil paraît gras, c'est que la poudre était tiède."},
pairs:["egg","icing-sugar","butter","vanilla","apricot","raspberry"],
svg:'<ellipse class="f1 sf" cx="48" cy="32" rx="22" ry="8"/><path class="s" d="M26 32v6q0 8 22 8t22-8v-6"/><path class="s" d="M38 50v10M46 50v12M54 50v10"/><path class="f2 sf" d="M30 74q12-12 18-12t18 12z"/>'},

{id:"antep-pistachio",cat:"nuts",name:{en:"Antep pistachio",fr:"Pistache d'Antep"},latin:"Pistacia vera",
origin:{en:"Gaziantep, Türkiye",fr:"Gaziantep, Turquie"},season:[9],
flavor:["nutty","rich","earthy"],
story:{en:"Turkish has no separate word for the nut: it is Antep fıstığı, the Antep nut, named for the city that grows it. When Gaziantep baklava became the first Turkish product to win a European protected name, this pistachio was written into the pastry's legal definition — there it is not an ingredient choice but a specification.",
fr:"Le turc n'a pas d'autre mot pour la pistache : c'est l'Antep fıstığı, la « noix d'Antep », du nom de la ville qui la cultive. Lorsque le baklava de Gaziantep est devenu le premier produit turc protégé en Europe, cette pistache est entrée dans la définition légale de la pâtisserie : elle n'y est plus un choix, mais une spécification."},
tip:{en:"It is the pistachio that survives an oven: chop it coarse and scatter it dry between the sheets, because a paste or a wet mix steams the filo from inside. Keep it raw — the colour goes long before the pastry browns.",
fr:"C'est la pistache qui tient au four : concassez-la grossièrement et répartissez-la sèche entre les feuilles, car une pâte ou un mélange humide ferait buée sous le filo. Gardez-la crue : sa couleur part bien avant que la pâtisserie ne dore."},
pairs:["clarified-butter","honey","rose-water","semolina","lemon","cardamom"],
svg:'<ellipse class="f1 sf" cx="38" cy="48" rx="12" ry="15"/><ellipse class="f1 sf" cx="58" cy="52" rx="11" ry="14"/><path class="s" d="M38 32v-3q6-6 14-6"/><path class="f3 sf" d="M48 66q9 3 9 8t-9 6q-9-1-9-6t9-8z"/>'},

{id:"apricot-kernel",cat:"nuts",name:{en:"Apricot kernel",fr:"Amandon d'abricot"},latin:"Prunus armeniaca",
origin:{en:"Malatya, Anatolia",fr:"Malatya, Anatolie"},season:[],
flavor:["bitter","nutty","delicate"],
story:{en:"The almond flavour in amaretti and in most noyau liqueurs is not almond at all: it comes from this seed, cracked out of the apricot stone. Sweet or bitter is a cultivar trait rather than a stage of ripeness, so the same-looking kernel is eaten by the handful in Malatya and weighed out by the gram in a distillery.",
fr:"Le goût d'amande des amaretti et de la plupart des liqueurs de noyau ne vient pas de l'amande : il vient de cet amandon, tiré du noyau d'abricot. Doux ou amer est un caractère de variété et non un stade de maturité, si bien que le même amandon se mange par poignées à Malatya et se pèse au gramme dans une distillerie."},
tip:{en:"Crack the stones with the flat of a knife rather than a nutcracker — a nutcracker shatters shell into the kernel. Blanch and rub the brown skin off before grinding; that is where most of the bitterness sits.",
fr:"Ouvrez les noyaux avec le plat d'un couteau plutôt qu'avec un casse-noix, qui projette des éclats de coque dans l'amandon. Ébouillantez puis frottez la peau brune avant de broyer : c'est là que loge l'essentiel de l'amertume."},
pairs:["apricot","dried-apricot","cherry","persipan","honey","vanilla"],
svg:'<path class="f1 sf" d="M40 26q-16 10-16 26t16 24q6-26 0-50z"/><path class="f2 sf" d="M56 30q16 10 16 24t-16 22q-6-24 0-46z"/><path class="f3 sf" d="M48 40q8 4 8 14t-8 12q-8-4-8-12t8-14z"/><path class="s" d="M32 40q-2 12 2 22M64 44q2 10-2 20"/>'},

{id:"avola-almond",cat:"nuts",name:{en:"Avola almond",fr:"Amande d'Avola"},latin:"Prunus dulcis (Pizzuta d'Avola)",
origin:{en:"Val di Noto, Sicily",fr:"Val di Noto, Sicile"},season:[8,9],
flavor:["nutty","bitter","delicate"],
story:{en:"Pizzuta means pointed in Sicilian, and the kernel is flat and almost perfectly symmetrical — which is why it became the almond for sugared confetti, since an even shape takes an even coat. The trees are grown without irrigation in the Val di Noto, so crops are small and the kernels dense enough to grind dry.",
fr:"Pizzuta veut dire « pointue » en sicilien, et l'amande est plate, presque parfaitement symétrique : c'est ce qui en a fait l'amande des dragées, une forme régulière prenant un enrobage régulier. Les arbres poussent sans irrigation dans le Val di Noto, d'où de petites récoltes et une amande assez dense pour se broyer à sec."},
tip:{en:"For granita di mandorla grind it cold and in bursts — it is dry enough to stay a powder where a Marcona smears into paste. One part almond to six of water, sweetened, then frozen and scraped.",
fr:"Pour la granita di mandorla, broyez-la froide et par à-coups : elle est assez sèche pour rester en poudre là où une Marcona part en pâte. Une part d'amande pour six d'eau, sucrée, puis prise au froid et grattée à la fourchette."},
pairs:["lemon","orange-blossom-water","ricotta","honey","coffee","cinnamon"],
svg:'<path class="f1 sf" d="M48 22q-20 12-20 30t20 24z"/><path class="f2 sf" d="M48 22q20 12 20 30t-20 24z"/><path class="f3 sf" d="M48 34q8 8 8 18t-8 14q-8-4-8-14t8-18z"/><path class="s" d="M30 46q6 4 12 0M54 46q6 4 12 0"/>'},

{id:"baru-nut",cat:"nuts",name:{en:"Baru nut",fr:"Noix de baru"},latin:"Dipteryx alata",
origin:{en:"Cerrado, Brazil",fr:"Cerrado, Brésil"},season:[],
flavor:["nutty","toasty","bitter"],
story:{en:"Baru is a legume, not a nut, and belongs to the same genus as the tonka bean — Dipteryx — gathered under wild savanna trees whose fruit cattle eat and scatter across the Cerrado. Roasting is not a matter of flavour here: the raw seed carries trypsin inhibitors and is not food until it has been through the oven.",
fr:"Le baru est une légumineuse, non un fruit à coque, et relève du même genre que la fève tonka — Dipteryx — ramassé sous des arbres sauvages dont le bétail mange et disperse les fruits à travers le Cerrado. La torréfaction n’est pas ici affaire de goût : la graine crue porte des inhibiteurs de trypsine et n’est pas comestible avant le four."},
tip:{en:"Twenty minutes at 180 °C, turned once — underroasted baru tastes green and sits heavily, and colour will not tell you, only smell. Salt it after roasting rather than before; the tannic finish wants salt and something acid beside it.",
fr:"Vingt minutes à 180 °C, retournées une fois : sous-torréfié, le baru garde un goût vert et pèse, et rien dans la couleur ne le trahit — seule l’odeur. Salez après torréfaction plutôt qu’avant ; la finale tannique appelle du sel et un peu d’acidité."},
pairs:["dark-chocolate","coffee","honey","banana","cassava","tonka","salt"],
svg:'<ellipse class="f2 sf" cx="36" cy="52" rx="14" ry="18"/><ellipse class="f1 sf" cx="62" cy="54" rx="9" ry="13"/><path class="s" d="M36 36v32"/>'},

{id:"basil-seed",cat:"nuts",name:{en:"Basil seed",fr:"Graine de basilic"},latin:"Ocimum basilicum",
origin:{en:"India & Southeast Asia",fr:"Inde & Asie du Sud-Est"},season:[],
flavor:["mild","herbal","fresh"],
story:{en:"It is the seed of the same plant grown for its leaves, drunk as a cooling sherbet in Persian and Indian kitchens long before it reached anybody's dessert — tukmaria in one, sabja in the other. It hydrates in under a minute where chia takes twenty, because the mucilage sits in a thin outer layer rather than through the whole seed, and the black core stays crisp inside its halo.",
fr:"C’est la graine de la plante même que l’on cultive pour ses feuilles, bue en sorbet rafraîchissant dans les cuisines persanes et indiennes bien avant tout dessert — tukmaria ici, sabja là. Elle s’hydrate en moins d’une minute quand le chia en demande vingt, car le mucilage tient dans une fine couche externe et non dans toute la graine : le cœur noir reste croquant au milieu de son halo."},
tip:{en:"Hydrate them apart in cold water — a teaspoon to 250 ml, five minutes — and spoon them into the drink afterwards. Dropped in dry they clump and float in a raft, and no amount of stirring will separate them again.",
fr:"Hydratez-les à part dans de l’eau froide — une cuillerée à café pour 250 ml, cinq minutes — puis versez-les à la cuillère dans la boisson. Jetées sèches, elles s’agglutinent en radeau à la surface, et aucun remuage ne les séparera plus."},
pairs:["rose-water","lime","coconut-milk","lychee","palm-sugar","mint","lemon","watermelon"],
svg:'<circle class="f1 sf" cx="44" cy="44" r="16"/><circle class="f3 sf" cx="44" cy="44" r="7"/><circle class="f1 sf" cx="64" cy="64" r="10"/><circle class="f3 sf" cx="64" cy="64" r="4.5"/>'},

{id:"beechnut",cat:"nuts",name:{en:"Beechnut",fr:"Faîne"},latin:"Fagus sylvatica",
origin:{en:"European beech woods",fr:"Hêtraies d’Europe"},season:[9,10],
flavor:["nutty","bitter","woody"],
story:{en:"Beech oil — huile de faîne — was a household oil across northern France into the nineteenth century, pressed at village mills and valued because it kept for years without turning. The trees mast: a heavy crop perhaps once in five years and near nothing between, so the oil went out of use for want of material rather than want of favour.",
fr:"L’huile de faîne fut, jusqu’au XIXe siècle, une huile de ménage du nord de la France, pressée au moulin de village et appréciée parce qu’elle se gardait des années sans rancir. Le hêtre fructifie par années semencières : une grosse récolte tous les cinq ans, presque rien entre-temps — l’huile a disparu par manque de matière, non de faveur."},
tip:{en:"Roast before eating: ten minutes at 150 °C loosens the papery skin and drives off the compound long called fagin, which makes raw beechnuts unpleasant in quantity. Rub them in a cloth while hot — cold, the skins will not come away.",
fr:"Grillez-les avant de les manger : dix minutes à 150 °C décollent la pellicule et chassent le composé longtemps appelé fagine, qui rend la faîne crue désagréable en quantité. Frottez-les au torchon à chaud ; froides, la peau ne vient plus."},
pairs:["butter","honey","apple","mushroom","venison","walnut-oil","pear"],
svg:'<path class="f2 sf" d="M48 26l16 40q-16 6-32 0z"/><path class="s" d="M48 26v40M34 58q14 5 28 0"/><path class="f1 sf" d="M30 66q18 8 36 0-4 8-18 8t-18-8z"/>'},

{id:"bitter-almond",cat:"nuts",name:{en:"Bitter almond",fr:"Amande amère"},latin:"Prunus dulcis var. amara",
origin:{en:"Wild and seedling almond trees",fr:"Amandiers sauvages et de semis"},season:[],
flavor:["bitter","floral","nutty"],
story:{en:"The kernel keeps amygdalin and the enzyme that splits it in separate cells, so nothing happens until it is crushed and wetted — at which point it releases benzaldehyde, the almond smell, and hydrogen cyanide in the same breath. The two part company in the pan: cyanide boils off near 26 °C and benzaldehyde not until 178 °C, which is why a cooked preparation keeps the aroma and loses the poison.",
fr:"L'amande garde l'amygdaline et l'enzyme qui la scinde dans des cellules séparées : rien ne se produit tant qu'on ne l'a pas écrasée et mouillée, et elle libère alors d'un même souffle le benzaldéhyde, l'odeur d'amande, et l'acide cyanhydrique. Les deux se séparent à la cuisson : le cyanure part vers 26 °C, le benzaldéhyde pas avant 178 °C. C'est pourquoi une préparation cuite garde le parfum et perd le poison."},
tip:{en:"Two or three kernels per kilo of sweet almond is the working dose for marzipan or amaretti; more turns the paste acrid rather than more almondy. Never eat them raw, and never give them to a child.",
fr:"Deux ou trois amandes par kilo d'amande douce : c'est la dose de travail pour un massepain ou des amaretti, au-delà la pâte devient âcre et non plus parfumée. Ne les mangez jamais crues et n'en donnez jamais à un enfant."},
pairs:["almond-flour","marzipan","cherry","apricot","kirsch","cream"],
svg:'<path class="f2 sf" d="M46 24q-12 14-12 30t12 22q2-26 0-52z"/><path class="f1 sf" d="M50 24q12 14 12 30t-12 22q-2-26 0-52z"/><path class="s" d="M40 40q2 14 2 24M56 42q-2 12-2 22"/>'},

{id:"black-sesame",cat:"nuts",name:{en:"Black sesame",fr:"Sésame noir"},latin:"Sesamum indicum",
origin:{en:"Tropical Africa & India",fr:"Afrique tropicale & Inde"},season:[],
flavor:["nutty","toasty","bitter"],
story:{en:"The ripe capsule splits with an audible snap, and the story goes that this is where open sesame comes from. Black seed is simply seed that has not been hulled: the pigment, most of the bitterness and the mineral edge all live in the skin that white sesame has had rubbed off.",
fr:"La capsule mûre s’ouvre d’un claquement net, et l’on raconte que « Sésame, ouvre-toi » vient de là. La graine noire n’est qu’une graine non décortiquée : le pigment, l’essentiel de l’amertume et le tranchant minéral tiennent tous dans la peau que le sésame blanc a perdue au frottage."},
tip:{en:"You cannot judge them by colour, so go by sound: dry pan, medium heat, shaking, and pull them the moment they start to jump and smell — two to three minutes. Grind them warm in a suribachi; cold, the oil will not release and you are left with grit.",
fr:"La couleur ne dit rien : fiez-vous au bruit — poêle sèche, feu moyen, en secouant, et retirez dès qu’elles sautent et embaument, deux à trois minutes. Broyez-les tièdes au suribachi ; froides, l’huile ne sort pas et il ne reste que du sable."},
pairs:["rice","soy-sauce","sugar","spinach","silken-tofu","honey","salt","kabocha"],
svg:'<ellipse class="f3 sf" cx="40" cy="40" rx="6" ry="4"/><ellipse class="f3 sf" cx="57" cy="45" rx="6" ry="4"/><ellipse class="f3 sf" cx="46" cy="55" rx="6" ry="4"/><ellipse class="f3 sf" cx="62" cy="60" rx="6" ry="4"/><ellipse class="f3 sf" cx="35" cy="58" rx="6" ry="4"/>'},

{id:"brazil-nut",cat:"nuts",name:{en:"Brazil nut",fr:"Noix du Brésil"},latin:"Bertholletia excelsa",
origin:{en:"Amazon basin",fr:"Bassin amazonien"},season:[],
flavor:["creamy","nutty","earthy","rich"],
story:{en:"It cannot be farmed — the tree depends on a single orchid bee for pollination and a large rodent, the agouti, to open its cannonball pods. Every Brazil nut sold has been gathered from wild forest, which makes the trade a genuine argument for keeping it standing.",
fr:"Elle ne peut être cultivée — l’arbre dépend d’une seule abeille des orchidées pour sa pollinisation et d’un gros rongeur, l’agouti, pour ouvrir ses capsules en boulet de canon. Toute noix du Brésil vendue a été ramassée en forêt sauvage, ce qui fait du commerce un vrai argument pour la laisser debout."},
tip:{en:"One nut can carry more than a day's selenium. That is a real limit, not a health-food claim — do not eat handfuls.",
fr:"Une seule noix peut porter plus d’une journée de sélénium. C’est une limite réelle, non un argument diététique — n’en mangez pas des poignées."},
pairs:["dark-chocolate","honey","coffee","vanilla","cream","banana","coconut-milk","date"],
svg:'<path class="f1 sf" d="M36 38l16 4 6 26-18 8-8-24z"/><path class="s" d="M40 46l12 18"/>'},

{id:"bronte-pistachio",cat:"nuts",name:{en:"Bronte pistachio",fr:"Pistache de Bronte"},latin:"Pistacia vera",
origin:{en:"Bronte, Sicily",fr:"Bronte, Sicile"},season:[8,9],
flavor:["resinous","herbal","nutty","rich"],
story:{en:"The trees grow out of fissures in Etna's lava, grafted onto wild terebinth, and they crop in odd years only: growers strip the buds in the even year so the whole harvest arrives at once. Nothing mechanical holds on that ground, which is why the crop still comes down the mountain in baskets.",
fr:"Les arbres poussent dans les fissures de lave de l'Etna, greffés sur térébinthe sauvage, et ne produisent que les années impaires : on ébourgeonne l'année paire pour que tout mûrisse d'un coup. Rien de mécanique ne tient sur ce sol, et la récolte descend encore la montagne en paniers."},
tip:{en:"Never roast it — heat kills the resinous note you paid for and dulls the green. Blanch briefly to slip the skins if you want the colour, then grind cold and in short bursts, or the paste oils out.",
fr:"Ne la torréfiez jamais : la chaleur tue la note résineuse que vous avez payée et ternit le vert. Ébouillantez-la brièvement pour la monder, puis broyez à froid et par à-coups, sinon la pâte rend son huile."},
pairs:["ricotta","honey","orange-blossom-water","dark-chocolate","olive-oil","lemon"],
svg:'<path class="f1 sf" d="M48 22q14 6 14 28t-14 26q-14-4-14-26T48 22z"/><path class="f3 sf" d="M48 26q4 10 4 22t-4 22q-4-10-4-22t4-22z"/><path class="s" d="M38 34q4 16 0 32M58 34q4 16 0 32"/><circle class="dot" cx="48" cy="19" r="2"/>'},

{id:"candlenut",cat:"nuts",name:{en:"Candlenut",fr:"Noix de bancoul"},latin:"Aleurites moluccanus",
origin:{en:"Maritime Southeast Asia & the Pacific",fr:"Asie du Sud-Est insulaire & Pacifique"},season:[],
flavor:["buttery","rich","mild"],
story:{en:"The kernel is oily enough to burn: across the Pacific they were threaded onto a palm rib and lit end to end, a few minutes of light per nut, which is where the English name comes from. Kukui is the state tree of Hawaii, where the same nut is roasted, pounded with salt into inamona and eaten with raw fish.",
fr:"L’amande est assez huileuse pour brûler : dans tout le Pacifique on l’enfilait sur une nervure de palme et on l’allumait de proche en proche, quelques minutes de lumière par noix — d’où le nom de noix-chandelle. Le kukui est l’arbre emblème d’Hawaï, où la même noix, grillée et pilée au sel, devient l’inamona qui accompagne le poisson cru."},
tip:{en:"Always toast before grinding and always cook the paste: raw candlenut is purgative, and the toast is also what lets it grind smooth instead of pasty. Four to six nuts thicken a curry for four — they are doing the work of both fat and flour, so cut the oil accordingly.",
fr:"Grillez-les toujours avant de les broyer et cuisez toujours la pâte : la noix crue est purgative, et c’est la torréfaction qui permet un broyage lisse plutôt que collant. Quatre à six noix lient un curry pour quatre — elles font le travail du gras et de la farine à la fois : réduisez l’huile d’autant."},
pairs:["galangal","lemongrass","shallot","turmeric","chili","coconut-milk","shrimp-paste","garlic"],
svg:'<path class="f1 sf" d="M48 22q7 8 7 13t-7 5-7-5 7-13z"/><circle class="f2 sf" cx="48" cy="58" r="18"/><path class="s" d="M30 58q18-10 36 0M48 40v36"/>'},

{id:"cashew",cat:"nuts",name:{en:"Cashew",fr:"Noix de cajou"},latin:"Anacardium occidentale",
origin:{en:"Northeast Brazil",fr:"Nord-est du Brésil"},season:[],
flavor:["sweet","creamy","nutty","buttery"],
story:{en:"It grows hanging beneath a fleshy false fruit, and its shell contains a caustic oil related to poison ivy — which is why cashews are never sold in the shell and why shelling them by hand is genuinely hazardous work.",
fr:"Elle pousse suspendue sous un faux-fruit charnu, et sa coque contient une huile caustique apparentée au sumac vénéneux — d’où des noix jamais vendues en coque et un décorticage manuel réellement dangereux."},
tip:{en:"Soaked and blended it makes a cream that behaves like dairy. It is the base of half the vegan sauces that actually work.",
fr:"Trempée et mixée elle donne une crème qui se comporte comme un laitage. C’est la base de la moitié des sauces véganes qui fonctionnent vraiment."},
pairs:["coconut-milk","chili","lime","cilantro","ginger","garlic","curry-leaf","honey"],
svg:'<path class="f2 sf" d="M34 50q14-12 24 0t-6 20-22-4 4-16z"/><path class="s" d="M40 56q10 4 14 10"/>'},

{id:"cervione-hazelnut",cat:"nuts",name:{en:"Cervione hazelnut",fr:"Noisette de Cervione"},latin:"Corylus avellana (Fertile de Coutard)",
origin:{en:"Cervione, Corsica",fr:"Cervione, Corse"},season:[9],
flavor:["nutty","woody","resinous"],
story:{en:"Corsica's hazelnut groves had nearly gone when growers around Cervione replanted a single old cultivar in the last decades of the twentieth century, and the whole protected area still turns out a fraction of what one Piedmont valley does. The nuts are dried in moving air rather than in a kiln, which is why the kernel keeps a woody, almost resinous edge that hot-dried nuts lose.",
fr:"Les vergers de noisetiers corses avaient presque disparu lorsque les producteurs de Cervione ont replanté une seule variété ancienne dans les dernières décennies du XXᵉ siècle ; toute l'aire protégée produit encore une fraction de ce que donne une seule vallée piémontaise. Les noisettes sèchent au vent plutôt qu'au four, et c'est de là que l'amande tient sa pointe boisée, presque résineuse, que le séchage chaud efface."},
tip:{en:"Its edge is aromatic rather than sweet, so pair it with brocciu, chestnut or a bitter honey — milk chocolate flattens it entirely. Roast it lighter than a Piedmont nut: 140 °C and no colour.",
fr:"Sa pointe est aromatique plutôt que sucrée : associez-la au brocciu, à la châtaigne ou à un miel amer, car le chocolat au lait l'écrase entièrement. Torréfiez-la plus doucement qu'une piémontaise : 140 °C, sans coloration."},
pairs:["brocciu","chestnut","chestnut-honey","fig","myrtle","goat-cheese"],
svg:'<path class="s" d="M48 20v16"/><path class="f1 sf" d="M34 24q10-6 14 4-8 8-14-4z"/><path class="f1 sf" d="M62 24q-10-6-14 4 8 8 14-4z"/><path class="f2 sf" d="M48 36q14 2 14 18t-14 24q-14-8-14-24T48 36z"/><path class="s" d="M48 42v32"/>'},

{id:"chestnut",cat:"nuts",name:{en:"Chestnut",fr:"Châtaigne"},latin:"Castanea sativa",
origin:{en:"Southern Europe & Asia Minor",fr:"Europe du Sud & Asie Mineure"},season:[10,11,12],
flavor:["sweet","earthy","toasty"],
story:{en:"For centuries, mountain villages from Corsica to the Cévennes lived off the “bread tree”: chestnuts ground into flour when wheat wouldn’t grow. The candied marron glacé turned the peasant staple into a jewel — same nut, different destiny.",
fr:"Des siècles durant, les villages de montagne, de la Corse aux Cévennes, vécurent de « l’arbre à pain » : la châtaigne moulue en farine là où le blé refusait de pousser. Le marron glacé confit changea l’aliment paysan en joyau — même fruit, autre destin."},
tip:{en:"Score a cross before roasting or they explode — every fireside learns this once. Their sweetness loves mushrooms, pork and dark chocolate.",
fr:"Incisez une croix avant de les rôtir, sinon elles explosent — chaque coin du feu l’apprend une fois. Leur douceur aime les champignons, le porc et le chocolat noir."},
pairs:["mushroom","pork","cream","dark-chocolate","honey","sage"],
svg:'<path class="f2 sf" d="M48 30q16 10 16 26 0 12-16 12T32 56q0-16 16-26z"/><path class="f3 sf" d="M38 64q10 6 20 0l-2 6H40z"/><path class="s" d="M48 30v-4"/>'},

{id:"chia-seed",cat:"nuts",name:{en:"Chia seed",fr:"Graine de chia"},latin:"Salvia hispanica",
origin:{en:"Central Mexico",fr:"Mexique central"},season:[],
flavor:["mild","nutty","grassy"],
story:{en:"Chia was an Aztec tribute crop alongside maize, beans and amaranth, and Chiapas takes its name from it — chian is the Nahuatl word for the seed. The Spanish suppressed the crop for its part in temple offerings, and it stayed a regional Mexican drink until the 1990s.",
fr:"Le chia était une culture de tribut aztèque au même titre que le maïs, le haricot et l’amarante, et le Chiapas lui doit son nom — chian désigne la graine en nahuatl. Les Espagnols en ont réprimé la culture pour son rôle dans les offrandes, et il est resté une boisson régionale mexicaine jusqu’aux années 1990."},
tip:{en:"One part seed to six of liquid by weight sets a spoonable gel in about twenty minutes. Whisk again at five minutes or the seeds sink and set as a single lump under a layer of loose liquid — that is the only way this goes wrong.",
fr:"Une part de graines pour six de liquide, au poids, prend en gel à la cuillère en une vingtaine de minutes. Fouettez de nouveau à cinq minutes, sinon les graines coulent et prennent en un seul bloc sous une couche de liquide libre — c’est le seul vrai raté possible."},
pairs:["lime","coconut-milk","honey","mango","yogurt","vanilla","raspberry","maple-syrup"],
svg:'<path class="f1 sf" d="M34 26h28l-4 44q-1 6-10 6t-10-6z"/><path class="s" d="M35 42h26"/><path class="dot" d="M40 50a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M50 46a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M46 60a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M53 56a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M42 68a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"date-paste",cat:"nuts",name:{en:"Date paste",fr:"Pâte de dattes"},latin:"Phoenix dactylifera",
origin:{en:"Middle East & North Africa",fr:"Moyen-Orient & Afrique du Nord"},season:[],
flavor:["sweet","rich","earthy","honeyed"],
story:{en:"The filling of maamoul and of the Iraqi kleicha, and one of the oldest sweeteners in use — Mesopotamian tablets record date syrup as a trade good four thousand years ago, long before cane sugar reached the region.",
fr:"La garniture des maamoul et de la kleicha irakienne, et l’un des plus anciens édulcorants en usage — des tablettes mésopotamiennes mentionnent le sirop de dattes comme marchandise il y a quatre mille ans, bien avant l’arrivée du sucre de canne."},
tip:{en:"Warm it with a spoonful of water and a little butter to make it spreadable. Cold it is unworkable.",
fr:"Réchauffez-la avec une cuillerée d’eau et un peu de beurre pour la rendre étalable. Froide elle est intravaillable."},
pairs:["tahini","cardamom","orange","sesame","cinnamon","walnut","butter","coffee"],
svg:'<path class="f1 sf" d="M32 58q0-16 16-16t16 16-16 14-16-14z"/><path class="s" d="M38 54q10 6 20 0"/>'},

{id:"coconut-flakes",cat:"nuts",name:{en:"Desiccated coconut",fr:"Noix de coco râpée"},latin:"Cocos nucifera",
origin:{en:"Indo-Pacific",fr:"Indo-Pacifique"},season:[],
flavor:["sweet","nutty","creamy","toasty"],
story:{en:"Drying was what let coconut leave the tropics — fresh flesh spoils within days, dried it keeps for a year. The Victorian appetite for coconut cake and macaroons is entirely a consequence of that one process.",
fr:"C’est le séchage qui a permis à la coco de quitter les tropiques — la chair fraîche s’altère en quelques jours, séchée elle se garde un an. L’appétit victorien pour les gâteaux et macarons à la coco découle entièrement de ce seul procédé."},
tip:{en:"Toast it in a dry pan before it goes into anything. Raw desiccated coconut tastes of cardboard.",
fr:"Torréfiez-la à sec avant de l’incorporer. Crue, la coco râpée a un goût de carton."},
pairs:["dark-chocolate","lime","mango","sugar","vanilla","cardamom","pineapple","coconut-milk"],
svg:'<path class="f3 sf" d="M32 52h32v4H32zM30 60h34v4H30zM34 68h28v4H34z"/>'},

{id:"dried-apricot",cat:"nuts",name:{en:"Dried apricot",fr:"Abricot sec"},latin:"Prunus armeniaca",
origin:{en:"Turkey & Central Asia",fr:"Turquie & Asie centrale"},season:[],
flavor:["sweet","sour","fruity","honeyed"],
story:{en:"The bright orange ones are treated with sulphur dioxide to keep the colour; the brown ones are not. The brown are more honeyed and figgy, the orange fresher and more acidic — they are effectively two different ingredients.",
fr:"Les orange vif sont traités au dioxyde de soufre pour garder la couleur ; les bruns ne le sont pas. Les bruns sont plus miellés et figués, les orange plus frais et plus acides — ce sont en pratique deux ingrédients différents."},
tip:{en:"Soak them in warm tea rather than water before they go into a tagine. It plumps them without washing out the flavour.",
fr:"Faites-les gonfler dans du thé tiède plutôt que dans l’eau avant un tajine. Cela les regonfle sans lessiver le goût."},
pairs:["lamb","almond","cinnamon","pistachio","honey","ras-el-hanout","orange","cream"],
svg:'<path class="f2 sf" d="M34 56q0-14 14-14t14 14q0 12-14 14t-14-14z"/><path class="s" d="M40 50q8 6 16 0M40 62q8 4 16 0"/>'},

{id:"dried-cranberry",cat:"nuts",name:{en:"Dried cranberry",fr:"Canneberge séchée"},latin:"Vaccinium macrocarpon",
origin:{en:"North America",fr:"Amérique du Nord"},season:[],
flavor:["sweet","sour","fruity","tangy"],
story:{en:"Almost always sweetened before drying, because an unsweetened dried cranberry is close to inedible — the fruit is far too acidic. Read the label: many are sweetened with apple juice concentrate rather than sugar, and they taste different.",
fr:"Presque toujours sucrée avant séchage, car une canneberge séchée non sucrée est quasi immangeable — le fruit est bien trop acide. Lisez l’étiquette : beaucoup sont sucrées au jus de pomme concentré plutôt qu’au sucre, et le goût diffère."},
tip:{en:"Their acidity cuts fat, which is why they work in a stuffing or a grain salad far better than raisins do.",
fr:"Leur acidité coupe le gras, ce qui les rend bien meilleures qu’un raisin sec dans une farce ou une salade de céréales."},
pairs:["turkey","pecan","orange","wild-rice","goat-cheese","walnut","sage","hazelnut"],
svg:'<ellipse class="f1 sf" cx="42" cy="55" rx="6" ry="5"/><ellipse class="f1 sf" cx="55" cy="58" rx="6" ry="5"/><ellipse class="f1 sf" cx="47" cy="66" rx="6" ry="5"/>'},

{id:"dried-fig",cat:"nuts",name:{en:"Dried fig",fr:"Figue sèche"},latin:"Ficus carica",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["sweet","honeyed","earthy","nutty"],
story:{en:"Figs were being dried in the Jordan valley eleven thousand years ago, and some archaeologists argue the fig was the first plant humans ever cultivated — earlier than wheat, because a cutting will root on its own.",
fr:"On séchait des figues dans la vallée du Jourdain il y a onze mille ans, et certains archéologues soutiennent que le figuier fut la première plante cultivée par l’homme — avant le blé, parce qu’une bouture prend racine seule."},
tip:{en:"The white bloom on the surface is crystallised sugar, not mould. It is a sign of quality rather than a fault.",
fr:"Le voile blanc en surface est du sucre cristallisé, non une moisissure. C’est un signe de qualité plutôt qu’un défaut."},
pairs:["walnut","blue-cheese","honey","fennel-seed","almond","prosciutto","orange","red-wine-vinegar"],
svg:'<path class="f1 sf" d="M48 36q14 10 14 22t-14 14-14-14 14-22z"/><path class="s" d="M48 36v-6"/><path class="s" d="M40 56q8 6 16 0"/>'},

{id:"egusi-seed",cat:"nuts",name:{en:"Egusi",fr:"Graines d’egusi"},latin:"Citrullus mucosospermus",
origin:{en:"West Africa",fr:"Afrique de l’Ouest"},season:[],
flavor:["nutty","earthy","rich"],
story:{en:"The melon it comes from is grown for nothing else — the flesh is too bitter to eat — and the sprawling vines earn their keep shading yam and cassava fields while the seed matures. Roughly half fat and a third protein, milled egusi behaves like a curd rather than a thickener: it sets into soft lumps instead of dissolving, which is the whole point of the soup named after it.",
fr:"Le melon dont elle vient ne sert à rien d’autre — la chair en est trop amère — et ses lianes rampantes gagnent leur place en ombrageant les champs d’igname et de manioc pendant que la graine mûrit. À peu près moitié gras et un tiers protéines, l’egusi moulu se comporte en caillé plutôt qu’en liant : il prend en grumeaux tendres au lieu de se dissoudre, et c’est tout l’objet de la soupe qui porte son nom."},
tip:{en:"Drop the milled paste into hot oil and leave it alone for three or four minutes before you touch it. Stirred early it disperses into a grainy sludge; left to set first, it breaks into the soft lumps the dish is built on.",
fr:"Versez la pâte moulue dans l’huile chaude et n’y touchez pas pendant trois ou quatre minutes. Remuée trop tôt, elle se disperse en bouillie sableuse ; laissée prendre d’abord, elle se casse en ces grumeaux tendres sur lesquels le plat repose."},
pairs:["red-palm-oil","chili","crayfish","molokhia","onion","spinach","crevettes-sechees","beef"],
svg:'<path class="f1 sf" d="M38 26q10 8 10 24t-10 22q-10-6-10-22t10-24z"/><path class="f1 sf" d="M60 34q9 8 9 22t-9 20q-9-6-9-20t9-22z"/><path class="s" d="M38 32q6 6 6 18t-6 16M60 40q5 6 5 16t-5 14"/>'},

{id:"flax",cat:"nuts",name:{en:"Flaxseed",fr:"Graine de lin"},latin:"Linum usitatissimum",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["nutty","earthy","mild","toasty"],
story:{en:"One of the first plants humans domesticated, and for most of history it was grown for linen rather than food — the Latin name means most useful. Dyed flax fibres found in a Georgian cave are thirty thousand years old.",
fr:"L’une des premières plantes domestiquées, et pendant presque toute l’histoire cultivée pour le lin plutôt que pour l’alimentation — le nom latin signifie très utile. Des fibres de lin teintes trouvées dans une grotte géorgienne ont trente mille ans."},
tip:{en:"Whole seeds pass straight through you. Grind them just before use — ground flax goes rancid within days.",
fr:"Les graines entières traversent sans être digérées. Moulez-les juste avant emploi — le lin moulu rancit en quelques jours."},
pairs:["oats","yogurt","honey","flour-complete","raisin","banana","cinnamon","sunflower-seed"],
svg:'<ellipse class="f1 sf" cx="40" cy="52" rx="7" ry="4"/><ellipse class="f1 sf" cx="55" cy="58" rx="7" ry="4"/><ellipse class="f1 sf" cx="45" cy="66" rx="7" ry="4"/>'},

{id:"fresh-hazelnut",cat:"nuts",name:{en:"Fresh green hazelnut",fr:"Noisette fraîche"},latin:"Corylus avellana",
origin:{en:"Orchards, late summer",fr:"Vergers, fin d'été"},season:[8,9],
flavor:["milky","fresh","grassy","delicate"],
story:{en:"A green hazelnut kernel is close to half water; drying takes it below a tenth of its weight, and that single number is the entire difference between the two ingredients. It is also why the fresh nut is sold by the day in late summer and never appears on a shelf — it moulds inside its own shell within a week.",
fr:"Une noisette verte est faite de près de moitié d'eau ; le séchage la ramène sous les dix pour cent, et ce seul chiffre sépare les deux ingrédients. C'est aussi pourquoi elle se vend au jour le jour à la fin de l'été et ne tient jamais en rayon : elle moisit dans sa coque en une semaine."},
tip:{en:"Crack them the moment you want them and rub the pellicle off with a thumb — it slips while the nut is fresh and welds on within days. Shave them raw over crudo or into a sharp salad; any heat at all destroys them.",
fr:"Cassez-les au dernier moment et retirez la pellicule au pouce : elle glisse tant que la noisette est fraîche et se soude en quelques jours. Râpez-les crues sur un poisson cru ou dans une salade acidulée ; la moindre chaleur les détruit."},
pairs:["sea-bass","olive-oil","lemon","celery","goat-cheese","peach"],
svg:'<path class="f1 sf" d="M26 46l4-14 6 8 6-12 6 12 6-10 6 12 6-8 4 12z"/><circle class="f2 sf" cx="40" cy="58" r="13"/><circle class="f2 sf" cx="58" cy="60" r="12"/><path class="s" d="M48 32v-8"/>'},

{id:"fresh-walnut",cat:"nuts",name:{en:"Fresh walnut",fr:"Noix fraîche"},latin:"Juglans regia",
origin:{en:"French orchards, September",fr:"Vergers français, septembre"},season:[9,10],
flavor:["milky","fresh","delicate","mild"],
story:{en:"Everything that makes a fresh walnut taste unlike a dried one sits in the pellicle: while the nut is still moist that skin lifts away in sheets, and it carries nearly all the tannin. Give it a fortnight and the skin has bonded to the kernel and will not come off — which is the point at which a walnut starts tasting like a walnut.",
fr:"Tout ce qui distingue une noix fraîche d'une noix sèche tient dans la pellicule : tant que le fruit est humide, cette peau se lève par plaques, et elle porte presque tout le tanin. Quinze jours plus tard, elle a adhéré au cerneau et ne se retire plus — c'est le moment où la noix se met à avoir un goût de noix."},
tip:{en:"Peel them, tediously; it is worth it. A bowl of skinned fresh walnuts with salt and a young wine is a different food — keep them in their shells in the fridge and use them inside a month, since they mould rather than dry.",
fr:"Épluchez-les, fastidieusement : cela en vaut la peine. Un bol de cerneaux frais pelés, avec du sel et un vin jeune, est un tout autre aliment. Gardez-les en coque au réfrigérateur et consommez-les dans le mois, car elles moisissent au lieu de sécher."},
pairs:["grape","comte","celery","verjus","fig","cream"],
svg:'<path class="f1 sf" d="M26 46q2 26 22 30t22-30q-10 10-22 10t-22-10z"/><path class="f3 sf" d="M36 44q4-14 12-14t12 14q-6 6-12 6t-12-6z"/><path class="s" d="M48 30v14M42 36q6 4 12 0"/><path class="f2 sf" d="M70 30q10 4 8 12-8 0-10-6z"/>'},

{id:"ginkgo-nut",cat:"nuts",name:{en:"Ginkgo nut",fr:"Noix de ginkgo (ginnan)"},latin:"Ginkgo biloba",
origin:{en:"East Asia",fr:"Asie de l’Est"},season:[10,11],
flavor:["bitter","resinous","delicate"],
story:{en:"The kernel sits inside a fleshy coat that smells of rancid butter, which is why cities plant only male trees and why ginnan reaches the market already cleaned. Ginkgos standing about a kilometre from the Hiroshima hypocentre put out buds the following spring, and several are alive today.",
fr:"L’amande loge dans une enveloppe charnue qui sent le beurre rance : c’est pourquoi les villes ne plantent que des arbres mâles et que le ginnan arrive au marché déjà nettoyé. Des ginkgos situés à un kilomètre environ de l’hypocentre d’Hiroshima ont bourgeonné au printemps suivant, et plusieurs vivent encore."},
tip:{en:"Heat them in a dry pan with a spoon of coarse salt until the shells crack, then peel while hot — the inner skin slips off and the kernel turns jade green. They contain methylpyridoxine, an anti-vitamin B6: a small handful for an adult and only a few for a child, which is how kaiseki counts them out anyway.",
fr:"Faites-les éclater à la poêle sèche avec une cuillerée de gros sel, puis pelez à chaud : la peau intérieure glisse et l’amande vire au vert jade. Elles contiennent de la méthylpyridoxine, une antivitamine B6 : une petite poignée pour un adulte, quelques-unes seulement pour un enfant — c’est du reste ainsi que le kaiseki les compte."},
pairs:["kombu","egg","chicken","junmai-sake","salt","shiitake","mitsuba","yuzu"],
svg:'<path class="f2 sf" d="M48 74q-20-12-24-38 12 8 24 10 12-2 24-10-4 26-24 38z"/><path class="s" d="M48 74v6"/><ellipse class="f1 sf" cx="48" cy="28" rx="9" ry="7"/>'},

{id:"goji",cat:"nuts",name:{en:"Goji berry",fr:"Baie de goji"},latin:"Lycium barbarum",
origin:{en:"Ningxia, China",fr:"Ningxia, Chine"},season:[],
flavor:["sweet","sour","earthy","musky"],
story:{en:"Grown in China for centuries as a medicinal ingredient in soups and teas rather than a snack — it is in the same family as the tomato and the aubergine. Its Western career as a superfood dates only to the early 2000s.",
fr:"Cultivée en Chine depuis des siècles comme ingrédient médicinal des soupes et des thés plutôt que comme en-cas — elle appartient à la même famille que la tomate et l’aubergine. Sa carrière occidentale de superaliment ne date que du début des années 2000."},
tip:{en:"Simmer them in a broth or a congee the way Chinese cooks do. Eaten dry by the handful they are leathery and sour.",
fr:"Faites-les mijoter dans un bouillon ou un congee comme les cuisiniers chinois. Sèches à la poignée elles sont coriaces et acides."},
pairs:["ginger","rice","goat-cheese","honey","chicken","jasmine-rice","sesame","almond"],
svg:'<ellipse class="f1 sf" cx="42" cy="54" rx="5" ry="8"/><ellipse class="f1 sf" cx="54" cy="58" rx="5" ry="8"/><ellipse class="f1 sf" cx="47" cy="68" rx="5" ry="8"/>'},

{id:"green-almond",cat:"nuts",name:{en:"Green almond",fr:"Amande fraîche"},latin:"Prunus dulcis",
origin:{en:"Mediterranean orchards, spring",fr:"Vergers méditerranéens, printemps"},season:[4,5,6],
flavor:["sour","grassy","fresh","delicate"],
story:{en:"Across Turkey and the Levant the whole unripe fruit is a spring street food — çağla, loz akhdar — sold by the bagful with a twist of salt and eaten hull, shell and all. The window is short: once the shell lignifies, a matter of two or three weeks, you have to cut the fruit open and eat only the jelly kernel inside.",
fr:"En Turquie et au Levant, le fruit entier encore vert est une friandise de rue du printemps — çağla, loz akhdar — vendu au sachet avec une pincée de sel et mangé avec sa bogue et sa coque. La fenêtre est brève : dès que la coque se lignifie, deux ou trois semaines plus tard, il faut ouvrir le fruit et ne manger que l'amande gélatineuse."},
tip:{en:"Test with a thumbnail before you buy — if it will not sink into the hull, the shell has already hardened. Eat them cold with salt and olive oil, or brine them within a day; they brown fast once cut.",
fr:"Essayez l'ongle avant d'acheter : s'il ne s'enfonce pas dans la bogue, la coque a déjà durci. Mangez-les froides au sel et à l'huile d'olive, ou mettez-les en saumure dans la journée, car elles brunissent vite une fois entamées."},
pairs:["salt","olive-oil","feta","mint","sumac","yogurt"],
svg:'<path class="f1 sf" d="M48 28q18 6 18 24t-18 22q-18-4-18-22t18-24z"/><path class="s" d="M34 38l-5-4M32 50h-6M36 62l-5 5M62 38l5-4M64 50h6M60 62l5 5"/><path class="f2 sf" d="M50 26q10-10 20-8-4 10-18 10z"/><path class="f3 sf" d="M54 56q8 2 8 8t-8 8q-4-4-4-8t4-8z"/>'},

{id:"green-walnut",cat:"nuts",name:{en:"Green walnut",fr:"Noix verte"},latin:"Juglans regia",
origin:{en:"France and Emilia, late June",fr:"France et Émilie, fin juin"},season:[6,7],
flavor:["bitter","grassy","resinous","pungent"],
story:{en:"The traditional date is Saint John's Eve, the twenty-fourth of June, and the test is a needle: if it passes clean through the whole fruit, shell and all, the walnut is still soft enough for nocino or vin de noix. The window runs about ten days, after which the shell has begun to harden and the fruit is fit only for brining.",
fr:"La date traditionnelle est la veille de la Saint-Jean, le 24 juin, et l'épreuve est celle de l'aiguille : si elle traverse le fruit entier de part en part, coque comprise, la noix est encore assez tendre pour le nocino ou le vin de noix. La fenêtre dure une dizaine de jours ; passé ce délai la coque durcit et le fruit ne vaut plus que pour la saumure."},
tip:{en:"Wear gloves, and do not use a wooden board: the juglone in the green husk stains skin brown for a week and wood permanently. Prick or halve them before they go into spirit — whole fruit steeps far too slowly.",
fr:"Mettez des gants et n'utilisez pas de planche en bois : la juglone du brou tache la peau en brun pendant une semaine et le bois définitivement. Piquez-les ou coupez-les en deux avant de les mettre à macérer, car le fruit entier infuse beaucoup trop lentement."},
pairs:["sugar","clove","cinnamon","lemon","vanilla","dark-rum"],
svg:'<circle class="f2 sf" cx="46" cy="54" r="20"/><path class="f1 sf" d="M46 34q4-14 18-16-2 14-16 18z"/><path class="f1 sf" d="M42 34q-6-12-18-12 4 12 16 16z"/><path class="s" d="M20 60h52"/><circle class="dot" cx="75" cy="60" r="2"/>'},

{id:"grenoble-walnut",cat:"nuts",name:{en:"Grenoble walnut",fr:"Noix de Grenoble"},latin:"Juglans regia (Franquette)",
origin:{en:"Isère, Drôme and Savoie",fr:"Isère, Drôme et Savoie"},season:[9,10,11],
flavor:["nutty","buttery","mild"],
story:{en:"Three varieties are permitted and Franquette is nearly all of it: walnuts from the valleys around Grenoble took an appellation in 1938, among the first granted to anything that was not wine. The rule that carries it is that they are sold in the shell and dated by harvest, and that date is the only real information on the sack — walnut oil turns rancid inside the shell as readily as out.",
fr:"Trois variétés sont admises et la Franquette en constitue la quasi-totalité : les noix des vallées autour de Grenoble ont obtenu une appellation en 1938, parmi les premières accordées à autre chose qu'un vin. La règle qui la porte, c'est la vente en coque avec l'année de récolte ; et cette date est la seule information réelle sur le sac, car l'huile de noix rancit dans la coque aussi vite qu'à l'air."},
tip:{en:"Buy the current year and shell them yourself. Break one open before you commit: if the kernel smells of paint or crayon, the whole sack has oxidised, and no amount of toasting will bring it back.",
fr:"Achetez l'année en cours et cassez-les vous-même. Ouvrez-en une avant de vous engager : si le cerneau sent la peinture ou le crayon de couleur, tout le sac est oxydé, et aucune torréfaction ne le rattrapera."},
pairs:["roquefort","comte","pear","endive","honey","apple"],
svg:'<path class="f1 sf" d="M48 22q20 0 20 26t-20 28q-20-8-20-28t20-26z"/><path class="s" d="M48 22v54"/><path class="s" d="M36 36q8 6 0 14M60 36q-8 6 0 14M38 58q10 4 20 0"/>'},

{id:"hazelnut",cat:"nuts",name:{en:"Hazelnut",fr:"Noisette"},latin:"Corylus avellana",
origin:{en:"Europe & Asia Minor",fr:"Europe & Asie Mineure"},season:[9,10],
flavor:["nutty","sweet","toasty","buttery"],
story:{en:"In Celtic legend, nine hazel trees dropped their nuts of wisdom into a sacred pool, and the salmon who ate them knew everything. Later, Napoleon’s blockade cut Turin off from cocoa — chocolatiers stretched what little they had with local hazelnuts, and gianduja was born of scarcity.",
fr:"Dans la légende celte, neuf noisetiers laissaient tomber leurs noisettes de sagesse dans un bassin sacré, et le saumon qui les mangea sut toutes choses. Plus tard, le blocus napoléonien priva Turin de cacao — les chocolatiers étirèrent le peu qu’ils avaient avec les noisettes locales, et le gianduja naquit de la pénurie."},
tip:{en:"Roast, then rub in a tea towel: the papery skins fall away and the bitterness goes with them.",
fr:"Torréfiez, puis frottez-les dans un torchon : les peaux s’envolent et l’amertume part avec."},
pairs:["dark-chocolate","coffee","pear","butter","chanterelle"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="15"/><path class="f3 sf" d="M34 48q2-14 14-14t14 14q-6 4-14 4t-14-4z"/><path class="s" d="M48 34v-6"/>'},

{id:"hazelnut-flour",cat:"nuts",name:{en:"Hazelnut flour",fr:"Poudre de noisette"},latin:"Corylus avellana",
origin:{en:"Nut mills, Piedmont and Turkey",fr:"Moulins à fruits secs, Piémont et Turquie"},season:[],
flavor:["nutty","toasty","rich"],
story:{en:"At around sixty percent fat it is not a flour in any working sense: it builds no structure and it turns to butter under a warm blade, which is why mills grind it cold and sometimes with sugar. The same milling strips away the nut's own protection, so a bag in a warm cupboard is rancid in weeks while whole nuts keep a year.",
fr:"Avec près de soixante pour cent de matière grasse, ce n'est pas une farine au sens propre : elle ne construit aucune structure et tourne au beurre sous une lame tiède, d'où le broyage à froid et parfois sucré des meuniers. Ce même broyage supprime la protection naturelle du fruit : un sachet dans un placard tiède rancit en quelques semaines quand la noisette entière tient un an."},
tip:{en:"Replace no more than a third of the wheat by weight, and drop the oven about 10 °C — the extra fat browns the crumb long before the inside is set. Keep it in the freezer and use it straight from cold.",
fr:"Ne remplacez pas plus du tiers du poids de farine, et baissez le four d'une dizaine de degrés : le gras supplémentaire colore la mie bien avant que le cœur ne soit pris. Conservez-la au congélateur et employez-la directement froide."},
pairs:["butter","egg","dark-chocolate","sugar","flour-t55","pear"],
svg:'<path class="f1 sf" d="M32 34h32l-2 40q0 4-4 4H38q-4 0-4-4z"/><path class="s" d="M32 34q8-6 16 0t16 0"/><ellipse class="f2 sf" cx="52" cy="74" rx="18" ry="7"/><path class="f3 sf" d="M68 58q8 0 8 8t-8 10q-8-4-8-10t8-8z"/>'},

{id:"hemp-seed",cat:"nuts",name:{en:"Hemp seed",fr:"Graine de chanvre"},latin:"Cannabis sativa",
origin:{en:"Central Asia",fr:"Asie centrale"},season:[],
flavor:["nutty","grassy","creamy","mild"],
story:{en:"The same species as the drug plant but a different cultivar, bred for fibre and seed and containing almost no THC. France is the largest hemp producer in Europe and has grown it continuously since the age of sail, when it made rope.",
fr:"La même espèce que la plante à drogue mais un autre cultivar, sélectionné pour la fibre et la graine et presque dépourvu de THC. La France est le premier producteur européen de chanvre et en cultive sans interruption depuis la marine à voile, où il faisait les cordages."},
tip:{en:"Never cook it — the oil oxidises fast and turns fishy. Scatter it raw over a finished dish.",
fr:"Ne la cuisez jamais — l’huile s’oxyde vite et prend un goût de poisson. Parsemez-la crue sur un plat terminé."},
pairs:["yogurt","honey","oats","banana","flax","spinach","olive-oil","lemon"],
svg:'<circle class="f2 sf" cx="41" cy="54" r="5"/><circle class="f2 sf" cx="54" cy="52" r="5"/><circle class="f2 sf" cx="47" cy="65" r="5"/><circle class="f2 sf" cx="59" cy="63" r="4"/>'},

{id:"japanese-chestnut",cat:"nuts",name:{en:"Japanese chestnut",fr:"Châtaigne japonaise (kuri)"},latin:"Castanea crenata",
origin:{en:"Japan & Korea",fr:"Japon & Corée"},season:[9,10],
flavor:["earthy","mild","toasty"],
story:{en:"Castanea crenata carries natural resistance to the blight that erased the American chestnut, and its genes have been bred into restoration hybrids for a century. In the kitchen it is the harder chestnut: the inner shibukawa skin grips the flesh instead of flaking away, and shibukawa-ni, the dish that keeps that skin on, takes three days of simmering and changes of water before the tannin lets go.",
fr:"Castanea crenata résiste naturellement au chancre qui a effacé le châtaignier américain, et ses gènes nourrissent depuis un siècle les hybrides de restauration. En cuisine c’est la châtaigne la plus rétive : la peau intérieure, le shibukawa, adhère à la chair au lieu de s’écailler, et le shibukawa-ni, le plat qui la conserve, demande trois jours de cuissons et de changements d’eau avant que le tanin cède."},
tip:{en:"Soak them overnight before peeling — the outer shell then comes away in one piece, which dry it never does. For shibukawa-ni, simmer in water with a teaspoon of baking soda per litre and change the water three times before any sugar goes in; sugar added early sets the tannin in place.",
fr:"Faites-les tremper une nuit avant de les éplucher : la coque se détache alors d’un seul tenant, ce qu’elle ne fait jamais à sec. Pour le shibukawa-ni, cuisez à l’eau avec une cuillerée à café de bicarbonate par litre et changez l’eau trois fois avant tout sucre ; ajouté trop tôt, le sucre fixe le tanin."},
pairs:["rice","sweet-potato","soy-sauce","sugar","hon-mirin","black-sesame","kombu"],
svg:'<path class="f3 sf" d="M48 24q19 13 20 32 1 12-20 12t-20-12q1-19 20-32z"/><path class="f1 sf" d="M34 62q14 7 28 0v4q-14 6-28 0z"/><path class="s" d="M48 22v8"/>'},

{id:"kola-nut",cat:"nuts",name:{en:"Kola nut",fr:"Noix de kola"},latin:"Cola nitida",
origin:{en:"West African forest belt",fr:"Ceinture forestière ouest-africaine"},season:[],
flavor:["bitter","earthy","pungent"],
story:{en:"Among the Igbo the nut is broken and shared before any serious conversation begins — he who brings kola brings life, as the proverb has it — and the number of lobes it splits into is read as an omen. It carries more caffeine by weight than a coffee bean, which is what put the cola in the first Coca-Cola formula, though the drink has not used it in any real quantity for a century.",
fr:"Chez les Igbo, la noix se casse et se partage avant toute conversation sérieuse — qui apporte la kola apporte la vie, dit le proverbe — et le nombre de lobes qu’elle libère se lit comme un présage. Elle porte plus de caféine au poids qu’un grain de café, ce qui lui valut de donner le « cola » à la première formule du Coca-Cola, boisson qui n’en met plus en quantité depuis un siècle."},
tip:{en:"Freeze it and grate it on a microplane — dried kola is too hard to cut and far too astringent for a heavy hand. Two grams infused twenty minutes in a litre of cream or milk gives a bitter aromatic backbone; always pair it with fat, which is the only thing that blunts the tannin.",
fr:"Congelez-la et râpez-la à la microplane : sèche, elle est trop dure à couper et bien trop astringente pour la main lourde. Deux grammes infusés vingt minutes dans un litre de crème ou de lait donnent une amertume aromatique de fond ; associez-la toujours au gras, seul à émousser le tanin."},
pairs:["dark-chocolate","coffee","ginger","molasses","orange","vanilla","cocoa-nibs"],
svg:'<path class="f2 sf" d="M48 24q18 10 18 28T48 76 30 52 48 24z"/><path class="s" d="M48 24v52M48 50l-18 2M48 50l18 2"/>'},

{id:"korean-pine-nut",cat:"nuts",name:{en:"Korean pine nut",fr:"Pignon de pin de Corée"},latin:"Pinus koraiensis",
origin:{en:"Northeast Asia",fr:"Asie du Nord-Est"},season:[],
flavor:["buttery","delicate","resinous"],
story:{en:"Korean pine cones are still brought down tree by tree by climbers with a rope and a hook, and the kernels go into jatjuk, the pine-nut porridge long served to convalescents. Species matters here: the wave of pine mouth — days of metallic taste after eating pine nuts — reported across Europe in the late 2000s was traced to Pinus armandii kernels entering the trade, which is why buyers now name Pinus koraiensis on the order.",
fr:"Les cônes du pin de Corée sont encore descendus arbre par arbre, à la corde et au croc, et les amandes partent au jatjuk, la bouillie de pignons longtemps servie aux convalescents. L’espèce compte ici : la vague de « bouche de pin » — plusieurs jours de goût métallique après avoir mangé des pignons — signalée en Europe à la fin des années 2000 a été rattachée aux amandes de Pinus armandii entrées dans le commerce, et l’on précise désormais Pinus koraiensis à la commande."},
tip:{en:"They are half fat and turn rancid within weeks at room temperature — keep the bag in the freezer. Toast them dry over medium heat and do not walk away: they go from pale to burnt in about thirty seconds.",
fr:"Ils sont à moitié gras et rancissent en quelques semaines à température ambiante — gardez le sachet au congélateur. Torréfiez-les à sec à feu moyen sans vous éloigner : ils passent du blond au brûlé en une trentaine de secondes."},
pairs:["honey","jujube","rice","sesame-oil","chicken","spinach","doenjang"],
svg:'<path class="f2 sf" d="M48 22q13 9 13 26 0 20-13 26-13-6-13-26 0-17 13-26z"/><path class="s" d="M35 36q13 6 26 0M34 48q14 6 28 0M36 60q12 6 24 0M48 24v50"/>'},

{id:"largueta-almond",cat:"nuts",name:{en:"Largueta almond",fr:"Amande Largueta"},latin:"Prunus dulcis (Desmayo Largueta)",
origin:{en:"Ebro valley, Aragón",fr:"Vallée de l'Èbre, Aragon"},season:[8,9],
flavor:["nutty","toasty","bitter"],
story:{en:"Its full name is Desmayo Largueta — desmayo, a swoon, for the way the branches droop. It is also among the earliest almonds to flower, so a February frost in the Ebro valley settles that year's price before anyone has seen a nut.",
fr:"Son nom complet est Desmayo Largueta : desmayo, l'évanouissement, pour la façon dont les branches retombent. C'est aussi l'une des amandes les plus précoces à fleurir, si bien qu'une gelée de février dans la vallée de l'Èbre fixe le prix de l'année avant que personne n'ait vu un fruit."},
tip:{en:"This is the almond that stays crisp under sugar or chocolate. For garrapiñadas work at roughly one part sugar to two of almond, and keep stirring off the heat until the syrup sands and goes white before you return the pan to the flame.",
fr:"C'est l'amande qui reste croquante sous le sucre ou le chocolat. Pour les garrapiñadas, comptez environ une part de sucre pour deux d'amandes et remuez hors du feu jusqu'à ce que le sirop sable et blanchisse avant de remettre la poêle sur la flamme."},
pairs:["dark-chocolate","sugar","cinnamon","anise","honey","orange"],
svg:'<path class="f2 sf" d="M48 22q13 12 13 30t-13 24q-13-6-13-24t13-30z"/><path class="s" d="M48 30v40M42 36q-3 14 0 26M54 36q3 14 0 26"/><path class="f1 sf" d="M66 46q7 8 7 16t-7 12q-6-4-6-12t6-16z"/>'},

{id:"lotus-seed",cat:"nuts",name:{en:"Lotus seed",fr:"Graine de lotus"},latin:"Nelumbo nucifera",
origin:{en:"Asian ponds & paddies",fr:"Étangs et rizières d’Asie"},season:[7,8,9],
flavor:["mild","delicate","sweet"],
story:{en:"A lotus seed dug from a dry lakebed in Liaoning germinated after radiocarbon dating had put it at around thirteen centuries old — the seed coat is close to airtight and the embryo simply waits. Fresh in summer the whole green pod is sold at market and the seeds eaten raw like nuts, once the bitter green germ has been pushed out of the middle of each one.",
fr:"Une graine de lotus tirée d’un lac asséché du Liaoning a germé après qu’une datation au carbone 14 lui eut donné près de treize siècles — le tégument est quasi étanche et l’embryon attend, simplement. Fraîche, l’été, la capsule verte se vend entière au marché et les graines se mangent crues comme des amandes, une fois le germe vert et amer chassé du centre de chacune."},
tip:{en:"Dried seeds want an overnight soak and then forty minutes at a simmer; anything shorter leaves a chalky core that no further cooking softens. Split each one and lift out the green germ before it goes in — a dozen left in will turn a whole pot bitter.",
fr:"Les graines sèches demandent une nuit de trempage puis quarante minutes de frémissement ; en deçà, le cœur reste crayeux et aucune cuisson ultérieure ne le rattrape. Fendez-les une à une pour ôter le germe vert avant de les mettre : une douzaine d’oubliées suffit à amertumer toute la marmite."},
pairs:["pork","jujube","goji","chicken","ginger","chinese-rock-sugar","snow-fungus","fresh-lily-bulb"],
svg:'<path class="f2 sf" d="M24 44q24-14 48 0-4 22-24 22t-24-22z"/><circle class="f1 sf" cx="36" cy="46" r="5"/><circle class="f1 sf" cx="48" cy="43" r="5"/><circle class="f1 sf" cx="60" cy="46" r="5"/><circle class="f1 sf" cx="42" cy="57" r="5"/><circle class="f1 sf" cx="54" cy="57" r="5"/>'},

{id:"macadamia",cat:"nuts",name:{en:"Macadamia",fr:"Noix de macadamia"},latin:"Macadamia integrifolia",
origin:{en:"Queensland, Australia",fr:"Queensland, Australie"},season:[],
flavor:["buttery","sweet","creamy","nutty"],
story:{en:"The hardest shell of any commercial nut — it takes about three hundred atmospheres to crack, which is why it is the most expensive nut in the world. It is also toxic to dogs, for reasons nobody has fully explained.",
fr:"La coque la plus dure de toutes les noix commerciales — il faut environ trois cents atmosphères pour la briser, d’où la noix la plus chère au monde. Elle est aussi toxique pour les chiens, sans que l’on sache pleinement pourquoi."},
tip:{en:"It is over seventy per cent fat, so it burns fast. Toast it at a low temperature and watch it constantly.",
fr:"Elle est à plus de soixante-dix pour cent de gras, donc elle brûle vite. Torréfiez-la à basse température en la surveillant sans cesse."},
pairs:["cream","coffee","vanilla","honey","coconut-milk","dark-chocolate","lime","maple-syrup"],
svg:'<circle class="f3 sf" cx="42" cy="54" r="11"/><circle class="f3 sf" cx="58" cy="60" r="9"/><path class="s" d="M36 50q6-4 12 0"/>'},

{id:"marcona-almond",cat:"nuts",name:{en:"Marcona almond",fr:"Amande Marcona"},latin:"Prunus dulcis (Marcona)",
origin:{en:"Levante coast, Spain",fr:"Levant espagnol"},season:[8,9],
flavor:["buttery","sweet","rich","mild"],
story:{en:"Marcona is round where almonds are normally flattened, and carries enough extra oil that it goes soft in the fryer instead of crisping — nearer a macadamia than a baking almond. Its price is agronomy rather than fashion: the tree is a shy, irregular bearer, and Spain eats most of what it grows.",
fr:"La Marcona est ronde là où l'amande est d'ordinaire plate, et porte assez d'huile pour s'attendrir à la friture au lieu de croustiller : elle tient plus de la noix de macadamia que de l'amande de pâtisserie. Son prix tient à l'agronomie et non à la mode — l'arbre produit peu et irrégulièrement, et l'Espagne consomme l'essentiel de sa récolte."},
tip:{en:"Fry them in mild olive oil at about 140 °C and lift them out pale: they hold so much oil that they keep cooking off the heat and turn bitter if you wait for colour. Salt them wet, while the surface still holds oil.",
fr:"Faites-les frire dans une huile d'olive douce vers 140 °C et sortez-les encore blondes : elles contiennent tant d'huile qu'elles continuent de cuire hors du feu et amèrent si l'on attend la couleur. Salez-les humides, tant que la surface retient l'huile."},
pairs:["olive-oil","salt","sherry-vinegar","jamon-serrano","manchego","saffron"],
svg:'<ellipse class="f1 sf" cx="46" cy="48" rx="18" ry="20"/><path class="s" d="M46 30q-6 18 0 36M39 32q-5 16 0 32M53 32q5 16 0 32"/><path class="f2 sf" d="M64 60q10 2 10 8t-10 8q-10-2-10-8t10-8z"/>'},

{id:"peanut",cat:"nuts",name:{en:"Peanut",fr:"Cacahuète"},latin:"Arachis hypogaea",
origin:{en:"South America",fr:"Amérique du Sud"},season:[],
flavor:["nutty","sweet","rich","toasty"],
story:{en:"Not a nut at all but a legume that buries its own pods underground. Born in South America, carried to Africa, it came back to the Americas in slave-ship provisions; George Washington Carver later catalogued three hundred uses for it, rebuilding Southern farming on its back.",
fr:"Pas une noix, mais une légumineuse qui enterre elle-même ses gousses. Née en Amérique du Sud, portée en Afrique, elle revint aux Amériques dans les cales des navires ; George Washington Carver en recensa plus tard trois cents usages, rebâtissant l’agriculture du Sud sur son dos."},
tip:{en:"Ground with a little of its own oil, it becomes sauce for half of West African and Southeast Asian cooking — chili and lime are its best friends.",
fr:"Broyée avec un peu de sa propre huile, elle devient sauce pour la moitié des cuisines ouest-africaines et d’Asie du Sud-Est — piment et citron vert sont ses meilleurs amis."},
pairs:["chili","coconut-milk","soy-sauce","dark-chocolate","ginger"],
svg:'<path class="f1 sf" d="M42 32q10-2 12 6 1 4 5 6 8 4 6 14-2 12-14 10-8-1-10-8-1-4-5-7-6-5-2-13 3-7 8-8z"/><path class="s" d="M40 42q6 4 6 10M52 44q4 4 4 9"/>'},

{id:"pecan",cat:"nuts",name:{en:"Pecan",fr:"Noix de pécan"},latin:"Carya illinoinensis",
origin:{en:"Mississippi valley",fr:"Vallée du Mississippi"},season:[10,11,12],
flavor:["sweet","buttery","toasty","rich"],
story:{en:"A native North American nut that indigenous peoples gathered long before any orchard existed — the word is Algonquian, for a nut requiring a stone to crack. Jefferson planted them at Monticello and sent trees to Washington.",
fr:"Une noix d’Amérique du Nord que les peuples autochtones récoltaient bien avant tout verger — le mot est algonquin et désigne une noix qu’il faut casser avec une pierre. Jefferson en planta à Monticello et en envoya des plants à Washington."},
tip:{en:"Sweeter and softer than a walnut, with none of its bitterness. They are not interchangeable in baking despite the resemblance.",
fr:"Plus sucrée et plus tendre que la noix, sans son amertume. Elles ne sont pas interchangeables en pâtisserie malgré la ressemblance."},
pairs:["maple-syrup","butter","vanilla","dark-chocolate","honey","cream","cinnamon","coffee"],
svg:'<ellipse class="f1 sf" cx="48" cy="56" rx="12" ry="18"/><path class="s" d="M48 38v36M42 44q4 12 0 24M54 44q-4 12 0 24"/>'},

{id:"perilla-seed",cat:"nuts",name:{en:"Perilla seed",fr:"Graine de périlla"},latin:"Perilla frutescens",
origin:{en:"Korea",fr:"Corée"},season:[],
flavor:["nutty","grassy","toasty"],
story:{en:"Korea grows perilla for the seed where Japan grows the same species for the leaf: deulkkae is pressed for a green oil or roasted and milled into deulkkae-garu, the powder that thickens namul and gamjatang. The oil oxidises within months rather than years, which is why it is sold in small dark bottles and kept in the fridge, and why sesame oil cannot stand in for it.",
fr:"La Corée cultive la périlla pour la graine là où le Japon cultive la même espèce pour la feuille : le deulkkae se presse en une huile verte ou se torréfie et se moud en deulkkae-garu, la poudre qui lie namul et gamjatang. L’huile s’oxyde en quelques mois et non en quelques années — d’où les petits flacons sombres, le réfrigérateur, et l’impossibilité de lui substituer l’huile de sésame."},
tip:{en:"Stir the powder in off the heat, at the very end: held at a boil it goes grainy and the aroma flattens within a minute. A heaped tablespoon thickens and perfumes a single bowl of soup, a far heavier hand than sesame ever asks for.",
fr:"Incorporez la poudre hors du feu, tout à la fin : maintenue à ébullition, elle devient granuleuse et l’arôme s’éteint en une minute. Une cuillerée à soupe bombée lie et parfume un seul bol de soupe — la main est bien plus lourde que pour le sésame."},
pairs:["doenjang","sesame-oil","garlic","spinach","napa-cabbage","soy-sauce","pork"],
svg:'<path class="f2 sf" d="M26 52h44q-2 18-22 18T26 52z"/><path class="f1 sf" d="M32 52q6-11 16-11t16 11z"/><path class="s" d="M48 41V30"/><path class="f2 sf" d="M48 30q-14 0-16-12 14-2 16 12z"/>'},

{id:"piedmont-hazelnut",cat:"nuts",name:{en:"Piedmont hazelnut",fr:"Noisette du Piémont"},latin:"Corylus avellana (Tonda Gentile Trilobata)",
origin:{en:"Langhe, Piedmont",fr:"Langhe, Piémont"},season:[9,10],
flavor:["nutty","toasty","buttery","rich"],
story:{en:"The Tonda Gentile's distinction is mechanical before it is aromatic: roast it and the pellicle lets go completely, where most hazelnuts leave shreds of bitter skin welded to the kernel. Turin's confectioners settled on it for that while stretching scarce cocoa with ground nut under Napoleon's blockade, and gianduja still specifies it.",
fr:"La particularité de la Tonda Gentile est mécanique avant d'être aromatique : à la torréfaction, la pellicule se détache entièrement, là où la plupart des noisettes laissent des lambeaux de peau amère collés à l'amande. Les confiseurs turinois l'ont retenue pour cela en allongeant de noisette un cacao devenu rare sous le blocus napoléonien, et le gianduja la réclame toujours."},
tip:{en:"Roast at 150 °C for 15 to 20 minutes, until the skins craze and the kernel is straw-coloured all the way through, then tip them hot into a coarse towel and rub. Cold nuts do not shed.",
fr:"Torréfiez à 150 °C pendant 15 à 20 minutes, jusqu'à ce que les peaux se craquellent et que l'amande soit blonde à cœur, puis versez-les brûlantes dans un torchon rêche et frottez. Froides, elles ne se dépouillent plus."},
pairs:["dark-chocolate","milk-chocolate","butter","cream","coffee","gianduja"],
svg:'<path class="f1 sf" d="M48 26q17 0 17 20t-17 28q-17-8-17-28t17-20z"/><ellipse class="f3 sf" cx="48" cy="30" rx="9" ry="4"/><path class="s" d="M42 36q-3 16 4 30M56 38q2 14-3 26"/>'},

{id:"pili-nut",cat:"nuts",name:{en:"Pili nut",fr:"Noix de pili"},latin:"Canarium ovatum",
origin:{en:"Bicol, Philippines",fr:"Bicol, Philippines"},season:[],
flavor:["buttery","creamy","rich"],
story:{en:"The shell is hard enough that it is split one nut at a time with a struck blade, which is why pili is only ever sold shelled and priced accordingly. In Bicol nothing is wasted: the fleshy pulp around the shell is softened in hot water and eaten with salt and rice, treated as a vegetable rather than a fruit.",
fr:"La coque est si dure qu’on la fend une noix à la fois, d’un coup de lame, et c’est pourquoi le pili ne se vend jamais qu’écalé, au prix que cela suppose. Dans le Bicol rien ne se perd : la pulpe charnue qui entoure la coque s’attendrit à l’eau chaude et se mange au sel avec du riz, en légume plus qu’en fruit."},
tip:{en:"It carries more fat than any other nut in the trade and it roasts fast — 140 °C for eight to ten minutes, and stop while it is still pale. Do not wait for a crunch: a properly roasted pili melts rather than snaps, and by the time it is crisp it is burnt.",
fr:"Il est le plus gras des fruits à coque du commerce et grille vite : 140 °C, huit à dix minutes, et l’on arrête tant qu’il reste blond. N’attendez pas le croquant : un pili bien grillé fond au lieu de casser, et lorsqu’il croque il est déjà brûlé."},
pairs:["dark-chocolate","coconut","palm-sugar","vanilla","honey","salt","butter","cocoa-nibs"],
svg:'<path class="f3 sf" d="M48 18q16 16 16 32t-16 28q-16-12-16-28t16-32z"/><path class="f1 sf" d="M48 30q7 10 7 20t-7 16q-7-6-7-16t7-20z"/>'},

{id:"pine-nut",cat:"nuts",name:{en:"Pine nut",fr:"Pignon de pin"},latin:"Pinus pinea",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["nutty","buttery","delicate"],
story:{en:"Roman legionaries carried pine nuts as marching rations, and jars of them were found preserved in the ashes of Pompeii. Each stone pine takes decades to bear cones — patience, shelled one kernel at a time.",
fr:"Les légionnaires romains emportaient des pignons comme ration de marche, et l’on en retrouva des jarres conservées sous les cendres de Pompéi. Chaque pin parasol met des décennies à donner ses cônes — de la patience, décortiquée pignon par pignon."},
tip:{en:"They burn treacherously fast: toast them in a dry pan and never take your eyes off. Golden is perfect; brown is bitter.",
fr:"Ils brûlent traîtreusement vite : torréfiez-les à sec sans les quitter des yeux. Dorés, c’est parfait ; bruns, c’est amer."},
pairs:["basil","parmesan","spinach","zucchini","fig","honey"],
svg:'<path class="f1 sf" d="M42 42q-4-8 3-12 5 4 3 12-3 3-6 0zM54 46q-4-8 3-12 5 4 3 12-3 3-6 0zM40 60q-4-8 3-12 5 4 3 12-3 3-6 0zM52 62q-4-8 3-12 5 4 3 12-3 3-6 0z"/>'},

{id:"pinyon-pine-nut",cat:"nuts",name:{en:"Pinyon pine nut",fr:"Pignon pinyon"},latin:"Pinus edulis",
origin:{en:"American Southwest",fr:"Sud-ouest américain"},season:[9,10,11],
flavor:["resinous","sweet","woody"],
story:{en:"The pinyon has been the state tree of New Mexico since 1949, and its nuts are still gathered off the ground by hand under wild trees — there are no orchards, and no way to hurry a crop. The tree masts: a heavy year fills every roadside stand in the state, and the several that follow give almost nothing.",
fr:"Le pinyon est l’arbre emblème du Nouveau-Mexique depuis 1949, et ses pignons se ramassent encore à la main, à terre, sous des arbres sauvages — aucun verger, aucun moyen de hâter une récolte. L’arbre fructifie par à-coups : une bonne année remplit tous les étals du bord des routes, les suivantes ne donnent presque rien."},
tip:{en:"The shell is thin enough to crack between the teeth, so roast them in it — ten minutes at 165 °C — and shell as you eat. It is the fattiest pine nut in the trade and the first to go rancid: buy small and freeze the rest.",
fr:"La coque est assez fine pour se casser entre les dents : faites-les griller en coque, dix minutes à 165 °C, et décortiquez au fur et à mesure. C’est le pignon le plus gras du commerce et le premier à rancir ; achetez petit et congelez le reste."},
pairs:["blue-corn","corn","sage","juniper","lamb","honey","chili"],
svg:'<ellipse class="f2 sf" cx="40" cy="56" rx="8" ry="11"/><ellipse class="f1 sf" cx="56" cy="58" rx="7" ry="10"/><ellipse class="f2 sf" cx="48" cy="42" rx="7" ry="10"/><path class="s" d="M28 32q10 5 16 3M28 39q10 3 15-1"/>'},

{id:"pistachio",cat:"nuts",name:{en:"Pistachio",fr:"Pistache"},latin:"Pistacia vera",
origin:{en:"Persia & Central Asia",fr:"Perse & Asie centrale"},season:[],
flavor:["nutty","sweet","grassy"],
story:{en:"The Queen of Sheba is said to have claimed her land’s whole pistachio harvest for her court. In Persia, lovers met under pistachio trees on moonlit nights: hearing the shells crack open was a promise of good fortune.",
fr:"La reine de Saba, dit-on, réservait à sa cour toute la récolte de pistaches de son royaume. En Perse, les amoureux se retrouvaient sous les pistachiers les nuits de lune : entendre les coques s’ouvrir en craquant promettait bonne fortune."},
tip:{en:"The greener the kernel, the finer the pistachio — Sicily’s Bronte and Iran’s best are almost emerald. Crushed, they finish anything creamy with style.",
fr:"Plus le cerneau est vert, plus la pistache est fine — celles de Bronte en Sicile et les meilleures d’Iran sont presque émeraude. Concassée, elle finit avec panache tout ce qui est crémeux."},
pairs:["cherry","dark-chocolate","honey","yogurt","cardamom"],
svg:'<path class="f1 sf" d="M36 50q0-14 12-14t12 14q0 8-6 12l-6-10-6 10q-6-4-6-12z"/><path class="f3 sf" d="M44 52q4-6 8 0 2 8-4 14-6-6-4-14z"/>'},

{id:"prune",cat:"nuts",name:{en:"Prune",fr:"Pruneau"},latin:"Prunus domestica",
origin:{en:"Agen, southwest France",fr:"Agen, Sud-Ouest"},season:[],
flavor:["sweet","rich","earthy","fruity"],
story:{en:"The pruneau d'Agen comes from the ente plum, grafted from a variety crusaders brought back from Syria. It is dried in ovens rather than the sun, and Lot-et-Garonne still lives on it.",
fr:"Le pruneau d’Agen vient de la prune d’ente, greffée d’une variété rapportée de Syrie par les croisés. Il sèche au four plutôt qu’au soleil, et le Lot-et-Garonne en vit encore."},
tip:{en:"It belongs with pork and rabbit as much as with dessert. Southwest France has always treated it as a savoury ingredient.",
fr:"Il va avec le porc et le lapin autant qu’avec le dessert. Le Sud-Ouest l’a toujours traité comme un ingrédient salé."},
pairs:["rabbit","thyme","pork","cream","bay-leaf","dark-chocolate","orange","lard"],
svg:'<path class="f1 sf" d="M34 56q0-16 14-16t14 16-14 16-14-16z"/><path class="s" d="M40 48q8 8 16 2M42 64q6 4 12 0"/>'},

{id:"pumpkin-seed",cat:"nuts",name:{en:"Pumpkin seed",fr:"Graine de courge"},latin:"Cucurbita pepo",
origin:{en:"Mesoamerica",fr:"Mésoamérique"},season:[],
flavor:["nutty","toasty","earthy","grassy"],
story:{en:"Styria grows a mutant squash whose seeds have no husk at all — a single natural mutation recorded in the 1870s, which is why Austrian pepitas are dark green and naked while everyone else's need shelling.",
fr:"La Styrie cultive une courge mutante dont les graines n’ont aucune coque — une mutation naturelle unique consignée dans les années 1870, d’où des pepitas autrichiennes vert sombre et nues quand celles des autres doivent être décortiquées."},
tip:{en:"Toast them until they pop and puff. That is the moment they are done, and it happens fast.",
fr:"Torréfiez-les jusqu’à ce qu’elles éclatent et gonflent. C’est l’instant où elles sont prêtes, et il arrive vite."},
pairs:["pumpkin-seed-oil","chili","lime","salt","honey","cilantro","cumin","sunflower-seed"],
svg:'<ellipse class="f2 sf" cx="42" cy="54" rx="7" ry="10"/><ellipse class="f2 sf" cx="56" cy="60" rx="7" ry="10"/><path class="s" d="M38 50q4-3 8 0M52 56q4-3 8 0"/>'},

{id:"perigord-walnut",cat:"nuts",name:{en:"Périgord walnut",fr:"Noix du Périgord"},latin:"Juglans regia",
origin:{en:"Dordogne, Lot and Corrèze",fr:"Dordogne, Lot et Corrèze"},season:[9,10],
flavor:["nutty","toasty","woody"],
story:{en:"The appellation covers four varieties, not one, and they are not interchangeable: Marbot is picked early and sold fresh, Corne is small and hard-shelled and goes to the press, Grandjean and Franquette are the keeping nuts. So the name on the label gives you the region and not the nut — the oil and the dessert walnut come off different trees.",
fr:"L'appellation couvre quatre variétés et non une seule, et elles ne sont pas interchangeables : la Marbot se cueille tôt et se vend fraîche, la Corne, petite et à coque dure, part au moulin, la Grandjean et la Franquette sont les noix de garde. Le nom sur l'étiquette donne donc la région et non le fruit : l'huile et la noix de dessert viennent d'arbres différents."},
tip:{en:"Walnut oil pressed from roasted Corne kernel is a finishing oil and nothing else — heat drives the roast aroma off in seconds. Dress the salad away from the flame, and keep the bottle in the fridge; it goes rancid faster than olive oil.",
fr:"L'huile pressée sur cerneaux de Corne torréfiés est une huile de finition et rien d'autre : la chaleur en chasse l'arôme grillé en quelques secondes. Assaisonnez loin du feu et gardez la bouteille au réfrigérateur, car elle rancit plus vite que l'huile d'olive."},
pairs:["walnut-oil","rocamadour","endive","confit-de-canard","honey","blue-cheese"],
svg:'<path class="f2 sf" d="M42 30q-16 6-16 22t16 22q6-22 0-44z"/><path class="s" d="M36 38q6 6 0 12t0 14"/><path class="f2 sf" d="M54 34q16 6 16 20t-16 20q-6-20 0-40z"/><path class="s" d="M60 42q-6 6 0 12t0 12"/>'},

{id:"raisin",cat:"nuts",name:{en:"Raisin",fr:"Raisin sec"},latin:"Vitis vinifera",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["sweet","fruity","honeyed","earthy"],
story:{en:"Grapes that dried on the vine were almost certainly the first dried fruit anyone ate, since it happens without human help. Corinth gave its name to the currant, Smyrna to the sultana — the varieties are named after their ports.",
fr:"Des raisins séchés sur pied furent presque certainement le premier fruit sec consommé, puisque cela se produit sans intervention humaine. Corinthe a donné son nom au raisin de Corinthe, Smyrne à la sultanine — les variétés portent le nom de leurs ports."},
tip:{en:"Plump them in warm liquid — rum, tea, wine — for twenty minutes before baking. Dry, they steal moisture from the crumb.",
fr:"Faites-les gonfler vingt minutes dans un liquide tiède — rhum, thé, vin — avant cuisson. Secs, ils volent l’humidité de la mie."},
pairs:["cinnamon","almond","flour-t55","pine-nut","swiss-chard","butter","honey","orange"],
svg:'<circle class="f1 sf" cx="41" cy="52" r="6"/><circle class="f1 sf" cx="55" cy="55" r="6"/><circle class="f1 sf" cx="46" cy="64" r="6"/><circle class="f1 sf" cx="58" cy="66" r="5"/><path class="s" d="M38 48q4-3 8 0"/>'},

{id:"sacha-inchi",cat:"nuts",name:{en:"Sacha inchi",fr:"Sacha inchi"},latin:"Plukenetia volubilis",
origin:{en:"Peruvian Amazon",fr:"Amazonie péruvienne"},season:[],
flavor:["nutty","grassy","earthy"],
story:{en:"The vine's fruit dries into a woody four- or five-pointed star, which is the whole of its trade name and most of its shelf appeal; the seed inside is inedible raw and becomes a nut only in the roasting pan. Around half its oil is alpha-linolenic acid, one of the highest figures of any pressed seed — and the reason that oil goes off faster than almost anything else in the pantry.",
fr:"Le fruit de la liane sèche en une étoile ligneuse à quatre ou cinq branches, qui fait tout son nom commercial et l’essentiel de son étalage ; la graine, immangeable crue, ne devient noix qu’au poêlon. Près de la moitié de son huile est de l’acide alpha-linolénique, l’un des taux les plus élevés parmi les graines pressées — et la raison pour laquelle cette huile tourne plus vite que presque tout le placard."},
tip:{en:"Never cook with the oil. It oxidises at gentle heat and turns fishy within minutes in a hot pan; dress with it cold, keep the bottle in the fridge and finish it within a month of opening.",
fr:"Ne cuisinez jamais à cette huile. Elle s’oxyde à feu doux et tourne au poisson en quelques minutes dans une poêle chaude : assaisonnez à froid, gardez le flacon au réfrigérateur et finissez-le dans le mois qui suit l’ouverture."},
pairs:["quinoa","lime","cocoa-nibs","avocado","honey","salt","chili","sweet-potato"],
svg:'<path class="f2 sf" d="M48 24q6 18 24 24-18 6-24 24-6-18-24-24 18-6 24-24z"/><ellipse class="f1 sf" cx="48" cy="48" rx="8" ry="6"/>'},

{id:"sesame",cat:"nuts",name:{en:"Sesame",fr:"Sésame"},latin:"Sesamum indicum",
origin:{en:"India & Africa",fr:"Inde & Afrique"},season:[],
flavor:["nutty","toasty","rich"],
story:{en:"“Open sesame!” — the magic words of Ali Baba echo the plant itself: ripe sesame pods burst open at a touch, scattering their seeds. It is likely the oldest oil crop on Earth, pressed in Mesopotamia four thousand years ago.",
fr:"« Sésame, ouvre-toi ! » — la formule magique d’Ali Baba fait écho à la plante elle-même : mûres, les capsules de sésame éclatent au moindre contact, dispersant leurs graines. C’est sans doute la plus ancienne culture oléagineuse du monde, pressée en Mésopotamie il y a quatre mille ans."},
tip:{en:"Toasted and ground with salt, it becomes gomasio; toasted and pressed, tahini. Raw seeds on bread are decoration — toasted, they are flavour.",
fr:"Torréfié et broyé avec du sel, il devient gomasio ; torréfié et pressé, tahini. Cru sur le pain, il décore — torréfié, il parfume."},
pairs:["chickpeas","honey","soy-sauce","ginger","eggplant","rice","tuna"],
svg:'<path class="f2 sf" d="M40 42q3-6 6 0 2 5-3 8-5-3-3-8zM52 38q3-6 6 0 2 5-3 8-5-3-3-8zM34 56q3-6 6 0 2 5-3 8-5-3-3-8zM48 54q3-6 6 0 2 5-3 8-5-3-3-8zM60 52q3-6 6 0 2 5-3 8-5-3-3-8zM42 68q3-6 6 0 2 5-3 8-5-3-3-8z"/>'},

{id:"pine-nut-toasted",cat:"nuts",name:{en:"Stone pine kernel",fr:"Pignon de pin parasol"},latin:"Pinus pinea",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["nutty","resinous","sweet","buttery"],
story:{en:"It takes three years for a stone pine cone to ripen, and the kernels are extracted by hand — which is why Mediterranean pine nuts cost several times what Chinese ones do. Some Chinese species cause a metallic taste distortion lasting days.",
fr:"Il faut trois ans à une pomme de pin parasol pour mûrir, et les pignons s’extraient à la main — d’où un prix plusieurs fois supérieur à celui des pignons chinois. Certaines espèces chinoises provoquent une distorsion métallique du goût durant plusieurs jours."},
tip:{en:"Check the origin on the packet. Pinus pinea is the Mediterranean one and the only one worth paying for.",
fr:"Vérifiez l’origine sur le paquet. Pinus pinea est le méditerranéen, et le seul qui mérite son prix."},
pairs:["basil","parmesan","raisin","swiss-chard","olive-oil","garlic","spinach","lemon"],
svg:'<path class="f3 sf" d="M42 40q6-4 8 4t-2 24-8-4 2-24z"/><path class="f3 sf" d="M54 50q5-3 6 4t-2 18-6-3z"/>'},

{id:"sunflower-seed",cat:"nuts",name:{en:"Sunflower seed",fr:"Graine de tournesol"},latin:"Helianthus annuus",
origin:{en:"North America",fr:"Amérique du Nord"},season:[],
flavor:["nutty","toasty","mild","earthy"],
story:{en:"Domesticated in what is now the United States some four thousand years ago, then taken to Russia, industrialised, and sold back to America as a Russian crop. The head follows the sun only while growing; a mature flower faces east and stops.",
fr:"Domestiquée dans l’actuelle Amérique du Nord il y a quelque quatre mille ans, puis emportée en Russie, industrialisée et revendue à l’Amérique comme culture russe. Le capitule ne suit le soleil que pendant la croissance ; une fleur mûre regarde l’est et s’immobilise."},
tip:{en:"Toast them and they stop tasting like birdseed. Untoasted they contribute texture and very little else.",
fr:"Torréfiées, elles cessent d’avoir un goût de graine pour oiseaux. Crues elles n’apportent que de la texture et guère plus."},
pairs:["honey","flour-t65","yogurt","raisin","oats","dark-chocolate","salt","pumpkin-seed"],
svg:'<ellipse class="f1 sf" cx="42" cy="54" rx="5" ry="9"/><ellipse class="f1 sf" cx="54" cy="58" rx="5" ry="9"/><ellipse class="f1 sf" cx="47" cy="68" rx="5" ry="9"/>'},

{id:"tiger-nut",cat:"nuts",name:{en:"Tiger nut",fr:"Souchet"},latin:"Cyperus esculentus",
origin:{en:"Valencia & the Sahel",fr:"Valence & le Sahel"},season:[],
flavor:["sweet","nutty","milky"],
story:{en:"It is the tuber of a sedge, not a nut at all, and dried ones have been found in Egyptian tombs — one of the oldest foods still eaten in the same form. In Valencia the crop carries a protected designation and exists for one purpose, horchata de chufa; across the Americas the same plant is called yellow nutsedge and farmers spend real money killing it.",
fr:"C’est le tubercule d’un souchet, pas un fruit à coque, et l’on en a retrouvé de séchés dans des tombes égyptiennes — l’un des plus anciens aliments encore consommés sous la même forme. À Valence la culture porte une appellation protégée et n’existe que pour l’horchata de chufa ; dans les Amériques, la même plante passe pour une mauvaise herbe et les agriculteurs dépensent gros à la détruire."},
tip:{en:"Soak the dried tubers a full day before milling or the horchata comes out thin — roughly one part soaked chufa to four of water, blended, then strained twice through cloth. Serve it barely above freezing and never boil it: heat sets the starch and you get paste.",
fr:"Faites tremper les tubercules secs une journée entière avant de les broyer, faute de quoi l’horchata reste maigre — environ une part de chufa trempée pour quatre d’eau, mixée, puis passée deux fois au linge. Servez-la à peine au-dessus de zéro et ne la faites jamais bouillir : la chaleur fixe l’amidon et l’on obtient de la colle."},
pairs:["cinnamon","lemon","sugar","vanilla","date","coconut","honey"],
svg:'<ellipse class="f2 sf" cx="42" cy="46" rx="12" ry="16"/><path class="s" d="M31 40q11 5 22 0M31 48q11 5 22 0M31 56q11 5 22 0"/><ellipse class="f1 sf" cx="62" cy="64" rx="9" ry="12"/><path class="s" d="M54 60q8 4 16 0M54 68q8 4 16 0"/>'},

{id:"tombul-hazelnut",cat:"nuts",name:{en:"Tombul hazelnut",fr:"Noisette Tombul (de Giresun)"},latin:"Corylus avellana (Tombul)",
origin:{en:"Giresun, Black Sea coast",fr:"Giresun, côte de la mer Noire"},season:[8,9],
flavor:["nutty","sweet","toasty","mild"],
story:{en:"Tombul means plump, and the Giresun crop is the reference grade of the world hazelnut trade — most of the planet's supply grows on one stretch of Black Sea coast. Frost or hail there in a single spring moves the price of hazelnut chocolate across Europe the following year.",
fr:"Tombul veut dire « dodue », et la récolte de Giresun sert de référence à tout le négoce mondial de la noisette : l'essentiel de la production de la planète pousse sur une seule bande de côte de la mer Noire. Un gel ou une grêle là-bas, un seul printemps, et le prix du chocolat à la noisette bouge dans toute l'Europe l'année suivante."},
tip:{en:"This is the nut to buy in kilos: roast at 160 °C until the pellicle blisters, then blitz it warm for a clean nut butter that takes salt and vanilla well. Do not use it where the aroma has to carry alone — it is sweet and low in aromatics.",
fr:"C'est la noisette que l'on achète au kilo : torréfiez à 160 °C jusqu'à ce que la pellicule cloque, puis mixez-la tiède pour un beurre de noisette net, qui accepte bien le sel et la vanille. Ne l'employez pas là où l'arôme doit porter seul : elle est douce et peu aromatique."},
pairs:["dark-chocolate","milk-chocolate","salt","honey","butter","tahini"],
svg:'<path class="f1 sf" d="M20 44q4 24 14 28t14-28q-6 8-14 8t-14-8z"/><path class="f3 sf" d="M64 34q13 0 13 16t-13 24q-13-8-13-24t13-16z"/><path class="s" d="M64 40v30"/><circle class="dot" cx="52" cy="74" r="2"/>'},

{id:"walnut",cat:"nuts",name:{en:"Walnut",fr:"Noix"},latin:"Juglans regia",
origin:{en:"Persia & Central Asia",fr:"Perse & Asie centrale"},season:[9,10,11],
flavor:["nutty","bitter","rich","toasty"],
story:{en:"Romans called it Jovis glans — “Jupiter’s acorn”, food fit for a god. Because its kernel looks like a brain, medieval doctors prescribed it for head ailments; the doctrine was nonsense, but the walnut forgave them and fed them anyway.",
fr:"Les Romains l’appelaient Jovis glans — « gland de Jupiter », nourriture digne d’un dieu. Parce que son cerneau ressemble à un cerveau, les médecins médiévaux la prescrivaient pour les maux de tête ; la doctrine était absurde, mais la noix leur pardonna et les nourrit quand même."},
tip:{en:"Buy them in the shell — shelled kernels go rancid fast. Ten seconds in a hot pan and they taste twice as much of themselves.",
fr:"Achetez-les en coque — les cerneaux nus rancissent vite. Dix secondes dans une poêle chaude et elles ont deux fois plus de goût."},
pairs:["blue-cheese","pear","fig","beetroot","honey","coffee","grape","celery"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="18"/><path class="s" d="M48 36v32M42 42q-4 10 0 20M54 42q4 10 0 20"/>'},

{id:"water-caltrop",cat:"nuts",name:{en:"Water caltrop",fr:"Mâcre"},latin:"Trapa natans",
origin:{en:"Eurasian still waters",fr:"Eaux dormantes d’Eurasie"},season:[8,9,10],
flavor:["mild","earthy","sweet"],
story:{en:"It is named after the caltrop, the spiked iron thrown on the ground to lame cavalry, which is very nearly what the horned seed looks like. Trapa was a European food long before it was an Asian one — the nuts turn up in Neolithic lake-dwelling deposits — and it is now rare or protected across much of the continent while Chinese markets sell it by the kilo as ling jiao.",
fr:"Elle doit son nom à la chausse-trape, ce fer à pointes jeté au sol pour estropier la cavalerie, et la graine cornue lui ressemble presque trait pour trait. La mâcre fut européenne bien avant d’être asiatique — on la retrouve dans les dépôts des cités lacustres néolithiques — et la voilà rare ou protégée sur une grande partie du continent, tandis que les marchés chinois la vendent au kilo sous le nom de ling jiao."},
tip:{en:"Never eat it raw: in its Asian growing waters it can carry the fluke Fasciolopsis buski, and the horns are sharp enough to be a hazard in themselves. Boil twenty-five to thirty minutes in salted water, then peel with a knife — the flesh should be chalky, never squeaky.",
fr:"Ne la mangez jamais crue : dans ses eaux de culture asiatiques elle peut porter la douve Fasciolopsis buski, et les cornes coupent à elles seules. Faites-la bouillir vingt-cinq à trente minutes à l’eau salée, puis pelez au couteau — la chair doit être farineuse, jamais crissante."},
pairs:["pork","soy-sauce","ginger","shiitake","chicken","star-anise","shaoxing-wine"],
svg:'<path class="f3 sf" d="M30 34q10 10 18 10t18-10q2 12-4 20t-14 10q-8-2-14-10t-4-20z"/><path class="s" d="M40 50q8 4 16 0"/><path class="dot" d="M46.4 64a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"wattleseed",cat:"nuts",name:{en:"Wattleseed",fr:"Graines d’acacia"},latin:"Acacia victoriae",
origin:{en:"Inland Australia",fr:"Australie intérieure"},season:[],
flavor:["toasty","bitter","nutty"],
story:{en:"Australia has close to a thousand acacia species and only a handful are safe to eat, so wattleseed is bought by botanical name — Acacia victoriae above all. Roasted and ground it smells of coffee, cocoa and hazelnut while containing none of them, which is what carried it out of desert country and into the bush-food trade in the 1980s.",
fr:"L’Australie compte près de mille espèces d’acacias dont une poignée seulement est comestible : la graine s’achète donc au nom botanique, Acacia victoriae en premier lieu. Torréfiée et moulue, elle sent le café, le cacao et la noisette sans rien contenir de tout cela — ce qui l’a fait sortir du désert pour entrer dans le commerce des bush foods dans les années 1980."},
tip:{en:"Infuse it, do not stir it in: a tablespoon steeped twenty minutes in a litre of hot cream or milk, then strained, behaves exactly like coffee grounds. Left in the mix the grounds stay gritty and never dissolve, and a custard made that way is unpleasant on the tongue.",
fr:"Infusez-la, ne l’incorporez pas : une cuillerée à soupe laissée vingt minutes dans un litre de crème ou de lait chaud, puis passée, se conduit exactement comme du marc de café. Laissée dans l’appareil, la mouture reste sableuse et ne se dissout jamais — une crème anglaise ainsi faite est désagréable en bouche."},
pairs:["cream","dark-chocolate","coffee","vanilla","macadamia","honey","milk-chocolate"],
svg:'<path class="f2 sf" d="M26 30q26 6 44 40-4 4-9 4-12-26-38-36z"/><path class="dot" d="M34 38a2 2 0 104 0 2 2 0 10-4 0M44 46a2 2 0 104 0 2 2 0 10-4 0M53 56a2 2 0 104 0 2 2 0 10-4 0M60 66a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"white-poppy-seed",cat:"nuts",name:{en:"White poppy seed",fr:"Pavot blanc"},latin:"Papaver somniferum",
origin:{en:"Bengal & the Deccan",fr:"Bengale & Deccan"},season:[],
flavor:["nutty","mild","creamy"],
story:{en:"Bengal's posto habit is usually traced to the colonial opium trade: the East India Company grew poppies across Bihar and Bengal for the resin, and the seed left behind was cheap there where it was dear everywhere else. The seed itself carries no opiates worth speaking of, though eat enough of it and a drug test will still say otherwise.",
fr:"L’habitude bengalie du posto se rattache d’ordinaire au commerce colonial de l’opium : la Compagnie des Indes fit planter le pavot dans tout le Bihar et le Bengale pour la résine, et la graine restée sur place n’y valait rien quand elle coûtait cher ailleurs. La graine elle-même ne porte aucun opiacé digne de ce nom — mais mangez-en assez et un test de dépistage dira le contraire."},
tip:{en:"Soak in warm water for half an hour, then grind wet with a splash of the soaking water; dry-ground it stays gritty and will never thicken anything. Add it off the boil and keep the heat low — poppy paste catches on the base of the pan faster than any other thickener in an Indian kitchen.",
fr:"Trempez une demi-heure à l’eau tiède, puis broyez humide avec un peu de cette eau : broyée à sec, la graine reste sableuse et ne liera jamais rien. Ajoutez hors ébullition et tenez le feu bas — la pâte de pavot attache au fond plus vite que tout autre liant d’une cuisine indienne."},
pairs:["mustard-oil","potato","nigella","chili","onion","yogurt","ghee","cashew"],
svg:'<path class="f1 sf" d="M28 44q0-13 15-13t15 13-15 13-15-13z"/><path class="s" d="M57 49l15 17"/><path class="dot" d="M35 40a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M43 35a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M50 41a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M41 46a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/>'}
]);
