window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"aiguillette-baronne",cat:"cuts",name:{en:"Aiguillette baronne",fr:"Aiguillette baronne"},latin:"Bœuf — cuisse",
origin:{en:"France",fr:"France"},season:[],
flavor:["meaty","delicate","mild","umami"],
story:{en:"A long thin muscle running along the rump, and another of the butcher's private cuts — there is one per side and it is tender enough to roast whole. Most of it never reaches a display case at all.",
fr:"Un muscle long et fin courant le long du rumsteck, et encore un morceau du boucher — il y en a un par côté et il est assez tendre pour se rôtir entier. L’essentiel n’atteint jamais l’étal."},
tip:{en:"Ask for it by name and expect a shrug. Order it a week ahead if your butcher takes whole carcasses.",
fr:"Demandez-le par son nom et attendez-vous à un haussement d’épaules. Commandez-le une semaine à l’avance si votre boucher travaille en carcasse."},
pairs:["shallot","butter","thyme","black-pepper","red-wine-vinegar","mushroom","garlic","tarragon"],
svg:'<path class="f1 sf" d="M24 52q24-12 48-2v10q-24 10-48 2z"/><path class="s" d="M24 56h48"/>'},

{id:"beef-cheek",cat:"cuts",rare:true,name:{en:"Beef cheek",fr:"Joue de bœuf"},latin:"Bos taurus (masseter)",
origin:{en:"The chewing muscle of the jaw",fr:"Le muscle masticateur de la mâchoire"},season:[],
flavor:["meaty","rich","umami"],
story:{en:"A muscle that worked every waking hour of the animal’s life, woven through with collagen as payment. Braised three hours it performs the great conversion: sinew into gloss, toughness into spoon-soft daube — the cut that taught cooks that time is an ingredient.",
fr:"Un muscle qui a travaillé chaque heure éveillée de la vie de l’animal, tissé de collagène en salaire. Braisée trois heures, elle accomplit la grande conversion : le nerf en brillance, la dureté en daube fondante à la cuillère — le morceau qui apprit aux cuisiniers que le temps est un ingrédient."},
tip:{en:"Don’t trim the silverskin obsessively — that gelatine is the future body of your sauce. It is better the next day, and better still the day after.",
fr:"Ne chassez pas obsessionnellement les parures — cette gélatine est le futur corps de votre sauce. Elle est meilleure le lendemain, et encore meilleure le surlendemain."},
pairs:["carrot","onion","bay-leaf","orange","clove"],
svg:'<path class="f3 sf" d="M34 44q12-10 24-2 8 6 4 16-4 12-18 10-12-2-14-12-1-7 4-12z"/><path class="s" d="M40 50q8-4 16 0" stroke-width="1.4"/>'},

{id:"jarret-de-boeuf",cat:"cuts",name:{en:"Beef shin",fr:"Jarret de bœuf"},latin:"Bœuf — jarret",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","meaty","umami","earthy"],
story:{en:"The hardest-working muscle on the animal, and therefore the most collagen-rich — which is exactly why it makes the best braise and the best stock. Cut across the bone it becomes osso buco, though Milan uses veal.",
fr:"Le muscle le plus sollicité de l’animal, et donc le plus riche en collagène — ce qui en fait précisément le meilleur braisé et le meilleur bouillon. Tranché en travers de l’os il devient l’osso buco, que Milan fait toutefois au veau."},
tip:{en:"Three hours minimum, and it is better the next day. Rushing it produces the toughest meat in the butcher's shop.",
fr:"Trois heures minimum, et c’est meilleur le lendemain. Le presser produit la viande la plus dure de la boucherie."},
pairs:["bone-marrow","carrot","onion","red-wine-vinegar","bay-leaf","thyme","celery","garlic"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="20"/><circle class="f3 sf" cx="48" cy="56" r="7"/><path class="s" d="M28 56h40"/>'},

{id:"tenderloin",cat:"cuts",name:{en:"Beef tenderloin",fr:"Filet de bœuf"},latin:"Bos taurus (psoas major)",
origin:{en:"Along the spine — the muscle that never works",fr:"Le long de l’échine — le muscle qui ne travaille jamais"},season:[],
flavor:["delicate","meaty","mild"],
story:{en:"The laziest muscle on the animal, and therefore the tenderest — and the mildest, which is why it attracts escorts: its centre cut was named Chateaubriand by the writer’s own chef, and Rossini lent his name to the version crowned with foie gras and truffle. Tenderness invites orchestras.",
fr:"Le muscle le plus paresseux de l’animal, donc le plus tendre — et le plus discret en goût, ce qui lui vaut des escortes : son cœur fut baptisé chateaubriand par le propre cuisinier de l’écrivain, et Rossini prêta son nom à la version couronnée de foie gras et de truffe. La tendreté attire les orchestres."},
tip:{en:"It has no fat to protect it: sear hard, finish gently, rest long. Because its voice is quiet, give it a talkative sauce — pepper, truffle, or brown butter.",
fr:"Aucun gras ne le protège : saisir fort, finir doux, reposer longtemps. Sa voix étant discrète, offrez-lui une sauce bavarde — poivre, truffe ou beurre noisette."},
pairs:["black-pepper","butter","truffle","foie-gras","mushroom"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="16"/><path class="s" d="M34 46q14-6 28 0M34 58q14 6 28 0" stroke-width="1.6"/>'},

{id:"bone-marrow",cat:"cuts",rare:true,name:{en:"Bone marrow",fr:"Os à moelle"},latin:"Bos taurus (medulla ossium)",
origin:{en:"The heart of the femur",fr:"Le cœur du fémur"},season:[],
flavor:["rich","buttery","meaty","umami"],
story:{en:"The pot-au-feu’s hidden dividend, spread on toast with coarse salt by whoever claims the bone. In 1990s London, Fergus Henderson made roast marrow with parsley salad the manifesto dish of nose-to-tail cooking — the humblest part of the animal, restated as a first course.",
fr:"Le dividende caché du pot-au-feu, tartiné sur le pain grillé au gros sel par qui réclame l’os. Dans le Londres des années 1990, Fergus Henderson fit de la moelle rôtie à la salade de persil le plat-manifeste de la cuisine nose-to-tail — la part la plus humble de l’animal, réénoncée en entrée."},
tip:{en:"Soak the bones in salted water a day to draw the blood, then roast cut-side up twenty minutes — set but not melted away. Sharpness beside it: parsley, capers, pickled shallot.",
fr:"Faites dégorger les os un jour dans l’eau salée, puis rôtissez-les face coupée vers le haut vingt minutes — prise mais pas fondue. De la vivacité à côté : persil, câpres, échalote au vinaigre."},
pairs:["parsley","capers","onion","black-pepper"],
svg:'<path class="f1 sf" d="M38 34h20v36H38z" rx="6"/><path class="f1 sf" d="M34 30a5 5 0 108 2h12a5 5 0 108-2M34 74a5 5 0 018-2h12a5 5 0 018 2" fill="#e9e9e6"/><circle class="f2 sf" cx="48" cy="52" r="7"/>'},

{id:"macreuse",cat:"cuts",name:{en:"Chuck tender",fr:"Macreuse"},latin:"Bœuf — épaule",
origin:{en:"France",fr:"France"},season:[],
flavor:["meaty","mild","umami","earthy"],
story:{en:"French butchers split it in two and treat them as different products: macreuse à bifteck, lean and tender enough to grill, and macreuse à pot-au-feu, sinewy and destined for the pot. Asking for the wrong one is a common and expensive mistake.",
fr:"Les bouchers français la divisent en deux et les traitent en produits distincts : la macreuse à bifteck, maigre et assez tendre pour la grillade, et la macreuse à pot-au-feu, nerveuse et vouée au bouillon. Demander la mauvaise est une erreur fréquente et coûteuse."},
tip:{en:"Say what you are cooking, not which cut you want. The butcher knows which half to hand you.",
fr:"Dites ce que vous cuisinez, non quel morceau vous voulez. Le boucher sait laquelle des deux vous donner."},
pairs:["carrot","leek","turnip","bone-marrow","bay-leaf","black-pepper","onion","celery"],
svg:'<path class="f1 sf" d="M28 42q22-6 40 4v22q-20 8-40 2z"/><path class="s" d="M28 56q20 6 40 0"/>'},

{id:"magret",cat:"cuts",name:{en:"Duck breast",fr:"Magret de canard"},latin:"Anas (pectoralis, canard gras)",
origin:{en:"The breast of a fattened duck",fr:"La poitrine d’un canard gras"},season:[],
flavor:["rich","meaty","sweet"],
story:{en:"A cut with a birth certificate: in 1959, chef André Daguin at the Hôtel de France in Auch first cooked a fattened duck’s breast rare, like a steak — scandal, then triumph. So particular is the magret that French law reserves the name for breasts of ducks raised for foie gras.",
fr:"Une pièce avec un acte de naissance : en 1959, le chef André Daguin, à l’Hôtel de France d’Auch, cuisina pour la première fois la poitrine d’un canard gras saignante, comme un steak — scandale, puis triomphe. Le magret est si particulier que la loi française en réserve le nom aux poitrines de canards élevés pour le foie gras."},
tip:{en:"Score the skin in a diamond pattern, start in a cold pan skin-down, and render patiently — most of the cooking happens on that side. Rose inside, mahogany outside.",
fr:"Quadrillez la peau en losanges, démarrez à poêle froide côté peau, et laissez fondre patiemment — l’essentiel de la cuisson se joue de ce côté. Rosé dedans, acajou dehors."},
pairs:["honey","orange","cherry","fig","black-pepper"],
svg:'<path class="f2 sf" d="M32 44q14-10 30-4 6 3 4 10-3 12-18 14-13 1-16-10-2-6 0-10z"/><path class="s" d="M38 46l20-4M40 52l20-4M42 58l18-4" stroke-width="1.2"/>'},

{id:"paleron",cat:"cuts",name:{en:"Feather blade",fr:"Paleron"},latin:"Bœuf — épaule",
origin:{en:"France",fr:"France"},season:[],
flavor:["meaty","rich","umami","earthy"],
story:{en:"A shoulder muscle split down the middle by a broad sheet of connective tissue, which is why it looks wrong raw and behaves beautifully cooked — that sheet dissolves to gelatine over three hours and bastes the meat from inside.",
fr:"Un muscle d’épaule fendu en son milieu par une large nappe de tissu conjonctif, d’où son aspect trompeur cru et son excellent comportement cuit — cette nappe fond en gélatine en trois heures et arrose la viande de l’intérieur."},
tip:{en:"It is the cut for bourguignon and carbonnade. Sold as a steak it needs either two minutes or three hours, nothing between.",
fr:"C’est le morceau du bourguignon et de la carbonade. Vendu en steak il demande deux minutes ou trois heures, rien entre les deux."},
pairs:["red-wine-vinegar","carrot","onion","bay-leaf","thyme","lard","mushroom","garlic"],
svg:'<path class="f1 sf" d="M26 44h44v26H26z"/><path class="f3 sf" d="M26 55h44v3H26z"/><path class="s" d="M34 44v26M60 44v26"/>'},

{id:"bavette",cat:"cuts",name:{en:"Flank steak",fr:"Bavette"},latin:"Bos taurus (flank)",
origin:{en:"The abdominal flank, loose-fibred",fr:"Le flanc abdominal, à fibres lâches"},season:[],
flavor:["meaty","umami","rich"],
story:{en:"Its long open fibres are the whole story: they drink marinades like a sponge, char in minutes, and reward anyone who respects the grain. A workers’ cut that bistros elevated to a national institution — bavette-échalote — and grill cultures from Mexico to Korea claimed for their own.",
fr:"Ses longues fibres ouvertes sont toute l’histoire : elles boivent les marinades comme une éponge, grillent en quelques minutes et récompensent qui respecte le sens du grain. Une pièce d’ouvriers que les bistrots ont élevée en institution nationale — la bavette-échalote — et que les cultures du gril, du Mexique à la Corée, ont adoptée."},
tip:{en:"Hot pan, short time, long rest — then slice thin against the grain at an angle. Cut with the grain and you will chew your way into regret.",
fr:"Poêle brûlante, cuisson courte, repos long — puis tranchez fin, en biais, à contre-fibre. Coupez dans le sens du grain et vous mâcherez jusqu’au regret."},
pairs:["shallot","garlic","soy-sauce","parsley"],
svg:'<path class="f2 sf" d="M30 44h36q4 8 0 18H30q-4-10 0-18z" transform="rotate(-6 48 53)"/><path class="s" d="M34 48l28-2M34 54l28-2M34 60l28-2" stroke-width="1.2" transform="rotate(-6 48 53)"/>'},

{id:"onglet",cat:"cuts",rare:true,name:{en:"Hanger steak",fr:"Onglet"},latin:"Bos taurus (hanging tender)",
origin:{en:"Hangs from the diaphragm — one per animal",fr:"Suspendu au diaphragme — un seul par bête"},season:[],
flavor:["meaty","rich","umami","earthy"],
story:{en:"The French call it the butcher’s cut, because for generations the butcher quietly took it home — there is only one on each animal, and it never reached the display case. Loose-grained, iron-dark and twice the flavour of noble cuts, it is the bistro’s open secret, forever wedded to melted shallots.",
fr:"On l’appelle le morceau du boucher, parce que des générations de bouchers l’ont discrètement rapporté chez eux — il n’y en a qu’un par bête, et il n’atteignait jamais l’étal. À fibres lâches, sombre de fer et deux fois plus goûteux que les pièces nobles, c’est le secret de Polichinelle des bistrots, marié pour toujours aux échalotes fondues."},
tip:{en:"Rare or bleu, never beyond — past pink it turns to rope. Slice thick, across the grain, and give it the classic: shallots long-melted in butter.",
fr:"Saignant ou bleu, jamais au-delà — passé le rosé, il devient corde. Tranchez épais, à contre-fibre, et servez-lui le classique : échalotes longuement fondues au beurre."},
pairs:["shallot","butter","mustard","black-pepper"],
svg:'<path class="f3 sf" d="M30 60q4-14 18-18t18 2q4 4 0 10-8 10-22 12-12 1-14-6z"/><path class="s" d="M38 54q10-6 22-6" stroke-width="1.4"/>'},

{id:"rognons",cat:"cuts",name:{en:"Kidneys",fr:"Rognons"},latin:"Ren",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","earthy","meaty","musky"],
story:{en:"Veal kidneys are the ones worth seeking — milder and finer than lamb or beef, and a Lyonnais standard served in a mustard cream. The surrounding fat is the suet that made English steamed puddings possible.",
fr:"Les rognons de veau sont ceux qu’il faut chercher — plus doux et plus fins que ceux d’agneau ou de bœuf, et un classique lyonnais servi à la crème moutardée. Le gras qui les entoure est la graisse de rognon qui a rendu possibles les puddings anglais."},
tip:{en:"Sear them fast and serve them pink. Overcooked kidney turns grainy and ammoniac, and there is no recovery.",
fr:"Saisissez-les vivement et servez-les rosés. Trop cuits ils deviennent granuleux et ammoniaqués, sans retour possible."},
pairs:["mustard","cream","shallot","white-wine-vinegar","parsley","butter","black-pepper","thyme"],
svg:'<path class="f1 sf" d="M32 50q10-8 18 0t-2 20-20-6 4-14z"/><path class="f1 sf" d="M52 58q8-6 14 0t-2 14-15-4z"/>'},

{id:"collier-agneau",cat:"cuts",name:{en:"Lamb neck",fr:"Collier d’agneau"},latin:"Agneau — collier",
origin:{en:"France",fr:"France"},season:[3,4,5,6],
flavor:["rich","meaty","earthy","umami"],
story:{en:"The cut navarin is built on, and the one most likely to be sold cheap because it looks like offcuts. It is threaded with connective tissue that turns to gelatine, giving a sauce body no leaner cut can produce.",
fr:"Le morceau sur lequel se bâtit le navarin, et celui qu’on brade le plus volontiers parce qu’il ressemble à des parures. Il est traversé de tissu conjonctif qui tourne en gélatine et donne à la sauce un corps qu’aucun morceau maigre ne produit."},
tip:{en:"Buy it on the bone, in thick rounds. Boned and diced it loses exactly the thing that makes it worth cooking.",
fr:"Achetez-le avec l’os, en tranches épaisses. Désossé et taillé en dés, il perd précisément ce qui fait son intérêt."},
pairs:["turnip","carrot","onion","thyme","tomato","garlic","bay-leaf","pea"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="18"/><circle class="f3 sf" cx="48" cy="56" r="6"/><path class="s" d="M32 48q16 6 32 0"/>'},

{id:"lamb-shank",cat:"cuts",name:{en:"Lamb shank",fr:"Souris d’agneau"},latin:"Ovis aries (shank)",
origin:{en:"The plump muscle hugging the leg bone",fr:"Le muscle dodu qui enrobe l’os du gigot"},season:[],
flavor:["meaty","rich","sweet"],
story:{en:"The French call it the souris — the mouse — for the plump, rounded shape of the muscle clinging to the shin. Too sinewy to grill, it exists for the long braise, collapsing after hours into sweet strands that slide from the bone at the touch of a spoon.",
fr:"Les Français l’appellent la souris, pour la forme ronde et dodue du muscle accroché au tibia. Trop nerveuse pour le gril, elle n’existe que pour le long braisé, s’effondrant après des heures en filaments doux qui glissent de l’os au toucher d’une cuillère."},
tip:{en:"One shank per person, browned deeply, then hours in a low oven with honey, thyme and garlic — turn it twice and otherwise leave it in peace.",
fr:"Une souris par personne, bien colorée, puis des heures au four doux avec miel, thym et ail — retournez-la deux fois et sinon fichez-lui la paix."},
pairs:["honey","thyme","garlic","white-beans","cinnamon"],
svg:'<path class="f2 sf" d="M38 60q-4-16 8-24 10-6 16 2 4 6-2 12-8 8-14 10 8 2 8 6 0 4-8 4t-8-10z"/><path class="f1 sf" d="M60 34a4 4 0 104-4 4 4 0 10-4 4z"/>'},

{id:"epaule-agneau",cat:"cuts",name:{en:"Lamb shoulder",fr:"Épaule d’agneau"},latin:"Agneau — épaule",
origin:{en:"France",fr:"France"},season:[3,4,5,6],
flavor:["rich","meaty","earthy","umami"],
story:{en:"Fattier and far more forgiving than the leg, and the cut that made seven-hour lamb possible — cooked until a spoon goes through it. Butchers sell it cheaper than gigot for reasons of appearance rather than eating quality.",
fr:"Plus grasse et bien plus indulgente que le gigot, c’est le morceau qui a rendu possible l’agneau de sept heures — cuit jusqu’à ce qu’une cuillère le traverse. Les bouchers la vendent moins cher que le gigot pour des raisons d’allure plutôt que de qualité gustative."},
tip:{en:"Cook it longer than you think. There is no medium here — it is either pink and chewy or falling apart, and the second is the point.",
fr:"Cuisez-la plus longtemps que vous ne croyez. Il n’y a pas de rosé ici — c’est ferme et rose, ou fondant, et c’est le second qu’on cherche."},
pairs:["garlic","rosemary","thyme","anchovy","white-beans","lemon","onion","olive-oil"],
svg:'<path class="f1 sf" d="M28 44q24-8 42 2v20q-22 10-42 2z"/><path class="s" d="M38 46q6 14 4 26"/>'},

{id:"ris-agneau",cat:"cuts",name:{en:"Lamb sweetbread",fr:"Ris d’agneau"},latin:"Ovis aries (thymus)",
origin:{en:"The thymus of the lamb",fr:"Le thymus de l’agneau"},season:[],
flavor:["delicate","milky","mild","creamy"],
story:{en:"A lamb's thymus weighs a few dozen grams where a calf's runs to several hundred, so it reaches the counter as a handful of walnut-sized nuggets rather than a lobe to be pared and portioned. It sells for a fraction of the veal price, and that is roughly how the two were divided: ris de veau went to restaurants, ris d'agneau stayed at home.",
fr:"Le thymus d’agneau pèse quelques dizaines de grammes quand celui du veau en fait plusieurs centaines : il arrive à l’étal en poignée de noisettes plutôt qu’en lobe à parer et à portionner. Il coûte une fraction du prix du ris de veau, et c’est à peu près ainsi qu’on les répartissait — le veau au restaurant, l’agneau à la maison."},
tip:{en:"No overnight press, no long soak: five minutes in barely simmering acidulated water, slip the membrane off, dry them, then two minutes a side in foaming butter. Held longer they tighten and go rubbery, and nothing carves that back out of them.",
fr:"Ni pressage d’une nuit, ni long trempage : cinq minutes dans une eau vinaigrée frémissante, on retire la membrane, on éponge, puis deux minutes par face au beurre mousseux. Au-delà, ils se raidissent et deviennent caoutchouteux, sans retour."},
pairs:["butter","lemon","capers","parsley","hazelnut","raisin","shallot","sherry-vinegar"],
svg:'<path class="f1 sf" d="M30 52a9 9 0 0116 0 8 8 0 01-16 0z"/><path class="f1 sf" d="M48 58a8 8 0 0114 0 7 7 0 01-14 0z"/><path class="f2 sf" d="M44 42a7 7 0 0113 0 6 6 0 01-13 0z"/>'},

{id:"gigot",cat:"cuts",name:{en:"Leg of lamb",fr:"Gigot d’agneau"},latin:"Ovis aries (leg)",
origin:{en:"The hind leg, whole",fr:"La cuisse arrière, entière"},season:[3,4,5,6],
flavor:["meaty","rich","grassy"],
story:{en:"France’s Easter centrepiece, studded with garlic slivers and carved at the table by whoever holds rank. The seven-hour version — gigot de sept heures — cooks until it is served with a spoon, a dish old cookbooks sealed shut with a flour-and-water lute so no perfume could escape.",
fr:"La pièce maîtresse de Pâques en France, piquée d’éclats d’ail et découpée à table par qui détient le rang. La version de sept heures — le gigot de sept heures — cuit jusqu’à se servir à la cuillère, un plat que les vieux livres scellaient d’un lut de farine et d’eau pour qu’aucun parfum ne s’échappe."},
tip:{en:"Two schools, both right: hot and pink with the bone in, rested under foil — or seven hours at a whisper with garlic and white beans until the knife is unemployed.",
fr:"Deux écoles, toutes deux dans le vrai : vif et rosé sur l’os, reposé sous feuille — ou sept heures à feu murmuré avec ail et haricots blancs jusqu’au chômage du couteau."},
pairs:["garlic","rosemary","white-beans","thyme","mint"],
svg:'<path class="f2 sf" d="M30 62q2-14 18-18l14-4q8-2 10 5t-6 11l-16 6q-14 5-20 0z"/><path class="f1 sf" d="M68 38a4 4 0 104-4 4 4 0 10-4 4z"/><path class="s" d="M62 42l8-4" stroke-width="1.8"/>'},

{id:"langue",cat:"cuts",name:{en:"Ox tongue",fr:"Langue de bœuf"},latin:"Lingua bovis",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","delicate","meaty","umami"],
story:{en:"Almost pure muscle with no grain to speak of, which is why it slices so cleanly and eats so tenderly once cooked. Sauce piquante or sauce gribiche are the traditional partners, and both exist to cut its richness.",
fr:"Presque uniquement du muscle sans fibre marquée, d’où sa coupe si nette et sa tendreté une fois cuite. La sauce piquante ou la gribiche sont les accompagnements traditionnels, et toutes deux existent pour couper son gras."},
tip:{en:"Peel the skin off while it is still hot from the pot. Let it cool and it will not come away at all.",
fr:"Pelez la peau tant qu’elle est brûlante à la sortie du bouillon. Laissez refroidir et elle ne viendra plus du tout."},
pairs:["cornichon","capers","mustard","parsley","white-wine-vinegar","shallot","carrot","bay-leaf"],
svg:'<path class="f1 sf" d="M30 62q0-24 18-24t18 22q-16 12-36 2z"/><path class="s" d="M48 40v22"/>'},

{id:"oxtail",cat:"cuts",rare:true,name:{en:"Oxtail",fr:"Queue de bœuf"},latin:"Bos taurus (cauda)",
origin:{en:"The tail, ring by ring",fr:"La queue, anneau par anneau"},season:[],
flavor:["rich","meaty","umami"],
story:{en:"In Rome’s old slaughterhouse district of Testaccio, workers were paid partly in the quinto quarto — the “fifth quarter” of offal and tail — and from that wage they built coda alla vaccinara, the tail braise that now anchors trattoria menus. Poverty’s invention, gelatine’s triumph.",
fr:"Dans le vieux quartier des abattoirs de Rome, le Testaccio, les ouvriers étaient payés en partie en quinto quarto — le « cinquième quartier » d’abats et de queue — et de ce salaire ils bâtirent la coda alla vaccinara, le braisé de queue qui ancre aujourd’hui les cartes de trattoria. Invention de la pauvreté, triomphe de la gélatine."},
tip:{en:"Brown the rings hard before any liquid touches them, and skim the next day when the fat has set. The broth it leaves behind is the best stock you will ever not have to make.",
fr:"Faites colorer fort les tronçons avant tout liquide, et dégraissez le lendemain quand le gras a figé. Le bouillon qu’elle laisse est le meilleur fond que vous n’aurez jamais eu à faire."},
pairs:["leek","carrot","bone-marrow","bay-leaf"],
svg:'<path class="f2 sf" d="M34 34a8 8 0 0116 0q-1 6-8 7-7-1-8-7z"/><path class="f2 sf" d="M40 48a7 7 0 0114 0q-1 5-7 6-6-1-7-6z"/><path class="f2 sf" d="M46 60a6 6 0 0112 0q-1 5-6 5-5 0-6-5z"/><path class="s" d="M56 70q4 3 8 2" stroke-width="1.8"/>'},

{id:"pluma-iberique",cat:"cuts",name:{en:"Pluma ibérica",fr:"Pluma ibérique"},latin:"Sus scrofa domesticus (ibérico)",
origin:{en:"Extremadura and Andalusia",fr:"Estrémadure et Andalousie"},season:[],
flavor:["nutty","rich","meaty"],
story:{en:"Pluma means feather, for the flat triangle it makes: the tip of the loin where it runs out over the shoulder, about a hundred and fifty grams, two to a pig. Spanish butchers only began selling these small muscles separately in the last few decades — before that they went into the mincer with everything else.",
fr:"Pluma veut dire plume, pour le triangle plat qu’elle dessine : la pointe de l’échine là où elle déborde sur l’épaule, cent cinquante grammes environ, deux par cochon. Les bouchers espagnols n’ont commencé à détailler ces petits muscles que depuis quelques décennies — avant, ils partaient au hachoir avec le reste."},
tip:{en:"Two minutes a side over a fierce fire and no more: it is thin, and it goes from rosy to grey faster than any other Iberian cut. Salt it as it comes off the grill and rest it three minutes on a warm plate.",
fr:"Deux minutes par face sur une braise vive, et rien de plus : c’est mince, et cela passe du rosé au gris plus vite que toute autre pièce ibérique. Salez à la sortie du gril et laissez reposer trois minutes sur une assiette chaude."},
pairs:["pimenton-de-la-vera","olive-oil","fleur-de-sel-guerande","piquillo","sherry-vinegar","garlic","rosemary","potato"],
svg:'<path class="f2 sf" d="M22 60q10-25 30-29 15-2 21 8-15 6-25 18t-20 12q-7 0-6-9z"/><path class="s" d="M25 62q17-7 31-23" stroke-width="1.8"/><path class="s" d="M29 54q10-10 20-16M34 60q10-10 20-16M25 48q8-8 16-13"/>'},

{id:"pork-belly",cat:"cuts",name:{en:"Pork belly",fr:"Poitrine de porc"},latin:"Sus scrofa (venter)",
origin:{en:"The pig’s striped underside",fr:"Le ventre rayé du cochon"},season:[],
flavor:["rich","meaty","sweet","buttery"],
story:{en:"Bacon before it becomes bacon: alternating strata of fat and lean that answer to every slow method on Earth. Nagasaki braises it as kakuni, a technique borrowed from Chinese dongpo pork; Italy rolls it into porchetta — and the 2000s gastropub made its crisp-topped square a signature of the decade.",
fr:"Le lard avant qu’il ne devienne lard : des strates alternées de gras et de maigre qui répondent à toutes les cuissons lentes du monde. Nagasaki la braise en kakuni, technique empruntée au porc dongpo chinois ; l’Italie la roule en porchetta — et le gastropub des années 2000 fit de son carré à peau craquante une signature de décennie."},
tip:{en:"Two acts, always: long and low until a skewer meets no resistance, then fierce heat for the crackling. Score the skin, dry it overnight, salt it like a beach.",
fr:"Deux actes, toujours : long et doux jusqu’à ce que la brochette n’y trouve aucune résistance, puis feu vif pour la couenne. Incisez la peau, séchez-la une nuit, salez-la comme une plage."},
pairs:["soy-sauce","ginger","miso","apple","fennel"],
svg:'<path class="f1 sf" d="M30 42h36v22H30z"/><path class="f2 sf" d="M30 48h36v5H30zM30 58h36v4H30z"/><path class="f3 sf" d="M30 42h36v4H30z"/>'},

{id:"poitrine-de-porc",cat:"cuts",name:{en:"Pork belly",fr:"Poitrine de porc"},latin:"Porc — poitrine",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","meaty","umami","smoky"],
story:{en:"Layers of fat and meat in alternating bands — the same cut that becomes bacon, pancetta and lardons depending on which country cures it. Chinese red-braising and French confit arrive at almost the same result by different routes.",
fr:"Des couches alternées de gras et de chair — le même morceau qui devient bacon, pancetta ou lardons selon le pays qui le sale. Le braisage rouge chinois et le confit français aboutissent presque au même résultat par des chemins différents."},
tip:{en:"Dry the skin uncovered in the fridge overnight before roasting. It is the only reliable route to crackling.",
fr:"Séchez la couenne à découvert au réfrigérateur une nuit avant de rôtir. C’est la seule voie fiable vers une peau croustillante."},
pairs:["soy-sauce","star-anise","garlic","ginger","cider-vinegar","honey","thyme","black-pepper"],
svg:'<path class="f2 sf" d="M22 46h52v22H22z"/><path class="f3 sf" d="M22 52h52v3H22zM22 60h52v3H22z"/>'},

{id:"echine",cat:"cuts",name:{en:"Pork collar",fr:"Échine de porc"},latin:"Porc — échine",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","meaty","sweet","umami"],
story:{en:"The neck end of the loin, and the most marbled part of a pig — which is why it is the only pork cut that survives a barbecue without drying. Italy cures the same muscle into coppa and charges ten times as much.",
fr:"L’extrémité cou de la longe, et la partie la plus persillée du porc — d’où le seul morceau qui survive au barbecue sans sécher. L’Italie sale ce même muscle en coppa et le vend dix fois plus cher."},
tip:{en:"It is the cheapest good cut in the shop. Roast it whole and slowly; it is far more forgiving than the loin.",
fr:"C’est le meilleur rapport qualité-prix de la boutique. Rôtissez-la entière et lentement ; elle pardonne bien plus que le filet."},
pairs:["mustard","sage","apple","garlic","thyme","cider-vinegar","fennel-seed","onion"],
svg:'<path class="f2 sf" d="M26 46q22-8 44 0v22q-22 8-44 0z"/><path class="f3 sf" d="M36 50q8 12 20 14"/>'},

{id:"jarret-de-porc",cat:"cuts",name:{en:"Pork knuckle",fr:"Jarret de porc"},latin:"Porc — jarret",
origin:{en:"France & Germany",fr:"France & Allemagne"},season:[],
flavor:["rich","salty","meaty","smoky"],
story:{en:"Alsace and Germany brine it and serve it on sauerkraut; Bavaria roasts it to a lacquered Schweinshaxe. Either way it is one joint feeding two people for the price of a sandwich, which is most of its appeal.",
fr:"L’Alsace et l’Allemagne le saumurent et le servent sur la choucroute ; la Bavière le rôtit en Schweinshaxe laqué. Dans les deux cas c’est un jarret pour deux personnes au prix d’un sandwich, et c’est l’essentiel de son attrait."},
tip:{en:"Simmer it first, then roast it hard for twenty minutes. Roasting from raw gives leather outside and raw within.",
fr:"Pochez-le d’abord, puis rôtissez-le fort vingt minutes. Rôti cru il donne du cuir dehors et du cru dedans."},
pairs:["sauerkraut","juniper","mustard","potato","caraway","bay-leaf","onion","black-pepper"],
svg:'<path class="f2 sf" d="M32 40q18-4 24 10t-4 26-24-6 4-30z"/><path class="s" d="M52 70l8 8"/>'},

{id:"filet-mignon-porc",cat:"cuts",name:{en:"Pork tenderloin",fr:"Filet mignon de porc"},latin:"Porc — filet",
origin:{en:"France",fr:"France"},season:[],
flavor:["delicate","mild","sweet","meaty"],
story:{en:"The least-used muscle on the pig and therefore the most tender, but also the leanest — it has almost no fat at all, which makes it the easiest cut in the shop to ruin. Confusingly, the French name means something different from the English.",
fr:"Le muscle le moins sollicité du porc et donc le plus tendre, mais aussi le plus maigre — presque sans gras, ce qui en fait le morceau le plus facile à gâcher. Le nom français, prêtant à confusion, ne désigne pas la même chose que l’anglais."},
tip:{en:"Take it out at 62°C and let it rest. Pork does not need to be cooked grey, and this cut punishes it more than any other.",
fr:"Sortez-le à 62 °C et laissez-le reposer. Le porc n’a pas besoin d’être cuit gris, et ce morceau le pardonne moins que tout autre."},
pairs:["mustard","cream","sage","apple","thyme","cider-vinegar","shallot","honey"],
svg:'<path class="f3 sf" d="M22 54q26-10 52-2v6q-26 10-52 2z"/><path class="s" d="M30 54h36"/>'},

{id:"sot-l-y-laisse",cat:"cuts",name:{en:"Poultry oyster",fr:"Sot-l’y-laisse"},latin:"Gallus gallus domesticus",
origin:{en:"France, taken off the whole bird",fr:"France, prélevé sur la carcasse"},season:[],
flavor:["meaty","rich","delicate"],
story:{en:"The name is an eighteenth-century joke that explains itself: only a fool would leave it there. It is the pair of muscles sitting in the hollow of the pelvic bone above the parson's nose, which English calls oysters for the shape — two to a bird, perhaps fifteen grams each.",
fr:"Le nom est une plaisanterie du XVIIIᵉ siècle qui s’explique seule : seul un sot l’y laisserait. Ce sont les deux muscles logés dans le creux de l’os iliaque, au-dessus du croupion, que l’anglais appelle huîtres pour leur forme — deux par volaille, une quinzaine de grammes chacun."},
tip:{en:"Sold by the kilo off turkey and chicken carcasses, they want ninety seconds in foaming butter and a minute's rest — they are already the tenderest meat on the bird, and longer cooking only tightens them. Dry them well first or they will not colour.",
fr:"Vendus au kilo, prélevés sur les carcasses de dinde et de poulet, ils demandent quatre-vingt-dix secondes dans un beurre mousseux et une minute de repos : c’est déjà la chair la plus tendre de l’oiseau, et une cuisson plus longue ne fait que la raidir. Épongez-les bien ou ils ne coloreront pas."},
pairs:["butter","garlic","parsley","shallot","morel","cream","black-pepper","chives"],
svg:'<path class="f2 sf" d="M28 46q10-8 18-2t-2 16q-10 6-16-2t0-12z"/><path class="f2 sf" d="M52 54q10-8 17-2t-3 15q-9 6-15-1t1-12z"/><path class="s" d="M32 48q7 2 9 9M56 56q7 2 9 9"/><path class="s" d="M22 72q26 9 52 0"/>'},

{id:"presa-iberique",cat:"cuts",name:{en:"Presa ibérica",fr:"Presa ibérique"},latin:"Sus scrofa domesticus (ibérico)",
origin:{en:"Extremadura and Andalusia",fr:"Estrémadure et Andalousie"},season:[],
flavor:["rich","nutty","meaty","earthy"],
story:{en:"The presa sits on top of the blade at the head of the loin: a thick disc of around half a kilo, two to a pig, and the most heavily veined of the Iberian cuts. The trade's own line is that on a bellota pig it beats the ham, and that it is the piece the butcher keeps for himself.",
fr:"La presa est posée sur l’omoplate, à la naissance de l’échine : un disque épais d’environ cinq cents grammes, deux par cochon, et la plus veinée des pièces ibériques. Le métier dit que sur un bellota elle vaut mieux que le jambon, et que c’est le morceau que le boucher garde pour lui."},
tip:{en:"Thick enough to treat like a beef fillet: sear it hard, finish it in a low oven to 58 °C in the centre, rest it ten minutes. Slice across the grain — the fat veins all run one way, and cut along them it eats tough.",
fr:"Assez épaisse pour être traitée comme un filet de bœuf : saisissez fort, finissez au four doux jusqu’à 58 °C à cœur, reposez dix minutes. Tranchez en travers de la fibre — les veines de gras filent toutes dans le même sens, et coupée dans ce sens elle est coriace."},
pairs:["pimenton-de-la-vera","sherry-vinegar","olive-oil","garlic","piquillo","thyme","potato","oloroso"],
svg:'<path class="f2 sf" d="M22 46a26 13 0 1152 0v10a26 13 0 01-52 0z"/><ellipse class="f1 sf" cx="48" cy="46" rx="26" ry="13"/><path class="s" d="M32 46q8-6 16-2t14-3M34 51q8-4 14 0t12-3"/>'},

{id:"rack-of-lamb",cat:"cuts",name:{en:"Rack of lamb",fr:"Carré d’agneau"},latin:"Ovis aries (rib rack)",
origin:{en:"The first eight ribs, frenched",fr:"Les huit premières côtes, manchonnées"},season:[3,4,5,6],
flavor:["meaty","delicate","rich"],
story:{en:"Eight ribs scraped clean to the bone — “frenched” — until the rack looks architectural; two racks interlocked become the guard of honour of British wedding tables. Under its thin cap of fat sits the tenderest lamb on the animal, built for a green persillade crust.",
fr:"Huit côtes grattées jusqu’à l’os — « manchonnées » — jusqu’à ce que le carré devienne architecture ; deux carrés entrecroisés forment la haie d’honneur des tables de noces britanniques. Sous sa fine coiffe de gras loge l’agneau le plus tendre de la bête, taillé pour une croûte verte de persillade."},
tip:{en:"Sear the fat cap first, paint with mustard, press on the herb crumbs, then a short hot roast: pink at the bone, rested until the juices settle.",
fr:"Saisissez d’abord la coiffe de gras, badigeonnez de moutarde, pressez la chapelure d’herbes, puis un rôtissage court et vif : rosé à l’os, reposé jusqu’à ce que les jus se calment."},
pairs:["rosemary","garlic","mustard","honey","thyme"],
svg:'<path class="f2 sf" d="M32 58q0-12 16-14t16 10q2 8-6 12-10 5-20 0-6-3-6-8z"/><path class="s" d="M40 44V30M48 42V28M56 44V30" stroke-width="1.8"/>'},

{id:"cote-de-boeuf",cat:"cuts",name:{en:"Rib of beef",fr:"Côte de bœuf"},latin:"Bos taurus (rib section)",
origin:{en:"The rib cage, bone left in",fr:"Le train de côtes, avec son os"},season:[],
flavor:["meaty","rich","umami","toasty"],
story:{en:"The celebration cut: marbled enough to baste itself, big enough to demand company, always carved and shared. Dry-aged for a month or two, its edges develop the nutty, almost blue-cheese depth of enzymes at slow work — beef that has learned patience.",
fr:"La pièce des grandes occasions : assez persillée pour s’arroser elle-même, assez grande pour exiger de la compagnie, toujours tranchée et partagée. Maturée un mois ou deux, elle gagne sur ses bords la profondeur noisettée, presque roquefortée, des enzymes au travail lent — un bœuf qui a appris la patience."},
tip:{en:"Salt generously, sear on all faces including the fat edge, then finish low with a thermometer, not a timer. Rest it half its cooking time — the bone keeps it warm.",
fr:"Salez généreusement, saisissez toutes les faces y compris la tranche de gras, puis finissez doux au thermomètre, pas au minuteur. Reposez-la la moitié du temps de cuisson — l’os la garde chaude."},
pairs:["rosemary","garlic","black-pepper","bone-marrow","shallot"],
svg:'<path class="f2 sf" d="M38 40q16-8 26 2 6 7 0 16-8 12-22 8-12-4-10-16 2-7 6-10z"/><path class="f1 sf" d="M34 42q-6-2-8-8 6-2 10 2z"/><path class="s" d="M44 50q8-2 14 2" stroke-width="1.4"/>'},

{id:"selle-agneau",cat:"cuts",name:{en:"Saddle of lamb",fr:"Selle d’agneau"},latin:"Agneau — selle",
origin:{en:"France",fr:"France"},season:[3,4,5,6],
flavor:["delicate","rich","meaty","sweet"],
story:{en:"Both loins still joined across the backbone, and the grandest thing a butcher can hand you — it is a restaurant cut, carved at the table. Escoffier's selle d'agneau was a set piece of the classical service.",
fr:"Les deux longes encore réunies par l’échine, et la pièce la plus imposante qu’un boucher puisse tendre — un morceau de restaurant, tranché en salle. La selle d’agneau d’Escoffier était un morceau de bravoure du service classique."},
tip:{en:"Ask the butcher to remove the chine bone but leave the saddle whole. Carving it otherwise is genuinely difficult.",
fr:"Demandez au boucher d’ôter l’os de l’échine en laissant la selle entière. Sinon la découpe est réellement difficile."},
pairs:["thyme","garlic","rosemary","butter","shallot","morel","black-pepper","asparagus"],
svg:'<path class="f1 sf" d="M22 48q26-10 52 0v14q-26 10-52 0z"/><path class="s" d="M48 44v26"/><path class="f3 sf" d="M44 52h8v10h-8z"/>'},

{id:"secreto-iberique",cat:"cuts",name:{en:"Secreto ibérico",fr:"Secreto ibérique"},latin:"Sus scrofa domesticus",
origin:{en:"Dehesa oak pastures, Spain",fr:"Dehesas de chênes, Espagne"},season:[],
flavor:["rich","nutty","meaty"],
story:{en:"Spanish butchers found this fan of muscle buried under the shoulder fat, where a vertical cut misses it entirely, and kept it back for themselves — hence the name. It reached restaurant menus only once whole-carcass butchery became something worth advertising rather than an ordinary household habit.",
fr:"Les bouchers espagnols ont trouvé cet éventail de muscle enfoui sous le gras d’épaule, là où une coupe verticale le manque entièrement, et le gardaient pour eux : d’où son nom. Il n’est arrivé sur les cartes que le jour où la découpe à la carcasse entière est devenue un argument de vente plutôt qu’une habitude domestique."},
tip:{en:"Charcoal, salt, three minutes a side and no more — the piece is thin, and past medium the intramuscular fat has rendered out and left it dry. Slice across the grain and salt again at the table.",
fr:"Braise, sel, trois minutes par face et pas davantage : la pièce est fine, et au-delà du rosé le gras intramusculaire a fondu et laisse la viande sèche. Tranchez en travers des fibres et resalez à table."},
pairs:["pimenton-de-la-vera","fleur-de-sel-guerande","piquillo","sherry-vinegar","olive-oil","rosemary","padron-pepper","garlic"],
svg:'<path class="f2 sf" d="M18 58q6-24 30-26t30 22q-16 12-30 12t-30-8z"/><path class="s" d="M28 52q10-8 20-6M34 62q12-8 24-4M46 34q3 10 1 18M58 38q-1 10-4 16"/><path class="s" d="M20 56q28 8 56-4"/>'},

{id:"plat-de-cotes",cat:"cuts",name:{en:"Short rib",fr:"Plat de côtes"},latin:"Bœuf — poitrine",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","meaty","umami","smoky"],
story:{en:"Alternating layers of meat, fat and bone, which is the ideal architecture for slow cooking — the fat renders through the meat while the bone gives up gelatine. It is the cut a pot-au-feu is built around in most French households.",
fr:"Des couches alternées de viande, de gras et d’os, architecture idéale pour la cuisson lente — le gras fond à travers la chair pendant que l’os rend sa gélatine. C’est le morceau autour duquel se bâtit le pot-au-feu dans la plupart des foyers français."},
tip:{en:"Cook it the day before and chill it. The fat sets on top and lifts off in one sheet, and the meat improves overnight.",
fr:"Cuisez-le la veille et laissez-le refroidir. Le gras fige en surface et se retire d’un bloc, et la viande gagne à la nuit."},
pairs:["carrot","leek","turnip","black-pepper","bay-leaf","onion","soy-sauce","garlic"],
svg:'<path class="f1 sf" d="M24 44h48v24H24z"/><path class="f3 sf" d="M34 44v24M50 44v24M66 44v24"/>'},

{id:"hampe",cat:"cuts",name:{en:"Skirt steak",fr:"Hampe"},latin:"Bœuf — diaphragme",
origin:{en:"France",fr:"France"},season:[],
flavor:["meaty","rich","umami","earthy"],
story:{en:"Part of the diaphragm, and one of the morceaux du boucher — the cuts French butchers traditionally kept for themselves because there are only two per animal and they taste better than they look. Onglet is its neighbour.",
fr:"Une partie du diaphragme, et l’un des morceaux du boucher — ces pièces que les bouchers gardaient traditionnellement pour eux parce qu’il n’y en a que deux par bête et qu’elles ont meilleur goût que belle allure. L’onglet est son voisin."},
tip:{en:"The grain is coarse and runs lengthways. Slice it hard across the grain or it is unchewable, however rare you cook it.",
fr:"La fibre est grossière et court dans la longueur. Tranchez franchement en travers, sinon c’est immâchable, si saignant soit-il."},
pairs:["shallot","red-wine-vinegar","black-pepper","butter","garlic","thyme","mustard","parsley"],
svg:'<path class="f1 sf" d="M22 48q26-8 52 0v14q-26 8-52 0z"/><path class="s" d="M22 52h52M22 58h52"/>'},

{id:"araignee",cat:"cuts",name:{en:"Spider steak",fr:"Araignée"},latin:"Bos taurus",
origin:{en:"The hip socket, French butchery",fr:"Cavité de la hanche, boucherie française"},season:[],
flavor:["meaty","rich","umami"],
story:{en:"It is one of the morceaux du boucher: roughly 500 g on a whole animal, prised out of the hollow of the hip socket, and long kept back rather than put on the counter. The web of fat running through it, which an industrial grader reads as a fault, is exactly what keeps it juicy.",
fr:"C’est l’un des morceaux du boucher : environ 500 g sur une bête entière, dégagé du creux de la cavité de la hanche, longtemps gardé plutôt que mis en vitrine. La résille de gras qui le traverse, défaut aux yeux d’un calibrage industriel, est précisément ce qui le garde juteux."},
tip:{en:"Grill it hard and take it off at rare — the loose grain turns stringy past medium-rare and no resting fixes it. Rest five minutes, then slice across the fibres, which run diagonally rather than along the length.",
fr:"Grillez-la très chaud et retirez-la saignante : sa fibre lâche devient filandreuse au-delà, et aucun repos ne rattrape cela. Cinq minutes de repos, puis tranchez en travers des fibres, qui courent en diagonale et non dans la longueur."},
pairs:["shallot","bone-marrow","black-pepper","watercress","butter","parsley"],
svg:'<path class="f2 sf" d="M22 50q4-18 26-18t26 16q2 16-24 20T22 50z"/><path class="s" d="M48 32q-2 18 0 36M28 42q20 8 40-2M26 58q22-2 44 4"/><circle class="dot" cx="48" cy="50" r="2"/>'},

{id:"sweetbreads",cat:"cuts",rare:true,luxe:true,name:{en:"Sweetbreads",fr:"Ris de veau"},latin:"Bos taurus (thymus)",
origin:{en:"The thymus of the calf — gone by adulthood",fr:"Le thymus du veau — disparu à l’âge adulte"},season:[],
flavor:["delicate","creamy","rich","milky"],
story:{en:"Not brains, as the nervous suppose, but the thymus gland — an organ that shrinks away as the animal grows, so only young calves can offer it. Haute cuisine’s badge of nerve and technique: soaked, blanched, pressed, then seared to a gilded crust over a custard heart.",
fr:"Non pas la cervelle, comme le craignent les inquiets, mais le thymus — un organe qui s’efface à mesure que l’animal grandit, si bien que seuls les jeunes veaux peuvent l’offrir. L’insigne de nerf et de technique de la haute cuisine : trempé, blanchi, pressé, puis saisi jusqu’à la croûte dorée sur un cœur de flan."},
tip:{en:"The pressing overnight under a weight is not optional — it firms the lobe so it sears instead of steaming. Then: brown butter, capers or morels, and conviction.",
fr:"Le pressage d’une nuit sous un poids n’est pas optionnel — il raffermit la noix pour qu’elle se saisisse au lieu de suer. Ensuite : beurre noisette, câpres ou morilles, et de la conviction."},
pairs:["morel","cream","butter","capers","lemon"],
svg:'<path class="f1 sf" d="M36 50a8 8 0 019-6 8 8 0 0110 2 8 8 0 016 10 8 8 0 01-9 8 9 9 0 01-11-2 8 8 0 01-5-12z"/><path class="s" d="M44 52q4 4 9 4" stroke-width="1.4"/>'},

{id:"tendron-de-veau",cat:"cuts",name:{en:"Veal breast",fr:"Tendron de veau"},latin:"Veau — tendron",
origin:{en:"France",fr:"France"},season:[],
flavor:["delicate","rich","meaty","mild"],
story:{en:"The cartilage-laced end of the ribs, and it turns to something between meat and jelly after two hours. It is a Lyonnais bouchon staple and almost unknown outside France, where it is usually ground into mince.",
fr:"L’extrémité cartilagineuse des côtes, qui devient après deux heures quelque chose entre la viande et la gelée. C’est un classique des bouchons lyonnais et presque inconnu hors de France, où il finit généralement au hachoir."},
tip:{en:"The cartilage is the good part, not a defect to trim. Cook it long enough and it becomes translucent and unctuous.",
fr:"Le cartilage est le meilleur, non un défaut à parer. Cuisez-le assez longtemps et il devient translucide et onctueux."},
pairs:["carrot","onion","white-wine-vinegar","tarragon","cream","mushroom","bay-leaf","lemon"],
svg:'<path class="f3 sf" d="M24 48h48v20H24z"/><path class="f1 sf" d="M34 48v20M50 48v20M64 48v20"/>'},

{id:"rognon-de-veau",cat:"cuts",name:{en:"Veal kidney",fr:"Rognon de veau"},latin:"Bos taurus (ren)",
origin:{en:"France",fr:"France"},season:[],
flavor:["rich","meaty","musky","mild"],
story:{en:"Where a lamb's or a pig's kidney is one smooth lobe, the calf's is a dozen or more lobes fused into a single knobbled mass, and it comes to the counter sealed inside its own hard white fat. Ask for it still jacketed: that fat is the roasting vessel, and a rognonnade is nothing more than the veal loin rolled around the whole thing before it goes in the oven.",
fr:"Là où le rognon d’agneau ou de porc n’est qu’un lobe lisse, celui du veau en compte une douzaine ou plus, soudés en une masse bosselée, et il arrive à l’étal enfermé dans sa propre graisse blanche et dure. Demandez-le ainsi : cette graisse est le plat à rôtir, et la rognonnade n’est rien d’autre que la longe de veau roulée autour avant le four."},
tip:{en:"Roast it whole in its fat at 200°C for about 25 minutes, then rest it ten before carving — the jacket bastes it and the lobes stay rosy right through. Carve to a grey centre and it is finished; the texture never comes back.",
fr:"Rôtissez-le entier dans sa graisse à 200 °C une vingtaine de minutes, puis laissez-le reposer dix minutes avant de le trancher : la graisse l’arrose et les lobes restent rosés à cœur. Un cœur gris est perdu — la texture ne revient pas."},
pairs:["mustard","shallot","sherry-vinegar","watercress","potato","butter","juniper","parsley"],
svg:'<path class="f1 sf" d="M24 50q0-20 24-20t24 20-24 24T24 50z"/><path class="f2 sf" d="M36 46q6-6 13-2t3 16-14 2-2-16z"/><path class="s" d="M42 46q5 4 4 10"/>'},

{id:"quasi-de-veau",cat:"cuts",name:{en:"Veal rump",fr:"Quasi de veau"},latin:"Veau — quasi",
origin:{en:"France",fr:"France"},season:[],
flavor:["delicate","sweet","meaty","mild"],
story:{en:"The top of the leg where it meets the loin, and the cut French cooks reach for when they want veal to roast rather than braise. It has no direct English equivalent, which is why translated recipes usually say rump and lose the distinction.",
fr:"Le haut de la cuisse à la jonction de la longe, et le morceau que choisissent les cuisiniers français quand ils veulent rôtir le veau plutôt que le braiser. Il n’a pas d’équivalent anglais direct, d’où les recettes traduites qui disent rump et perdent la nuance."},
tip:{en:"Roast it to just pink and rest it twenty minutes. Veal cooked through is the commonest way to waste an expensive piece of meat.",
fr:"Rôtissez-le juste rosé et laissez-le reposer vingt minutes. Un veau cuit à cœur est la façon la plus courante de gâcher une pièce chère."},
pairs:["morel","cream","tarragon","butter","shallot","white-wine-vinegar","lemon","asparagus"],
svg:'<path class="f3 sf" d="M26 46q22-8 42 2v18q-20 10-42 2z"/><path class="s" d="M26 56q22 6 42 0"/>'},

{id:"ris-de-veau-noix",cat:"cuts",name:{en:"Veal sweetbread heart (noix)",fr:"Ris de veau — noix (pomme)"},latin:"Bos taurus (thymus, thoracic lobe)",
origin:{en:"The thoracic lobe of the calf's thymus",fr:"Le lobe thoracique du thymus de veau"},season:[],
flavor:["delicate","creamy","milky","rich"],
story:{en:"Butchers split the calf's thymus in two and sell the halves as different goods: the round thoracic lobe — the noix, or pomme — fetches roughly double the ragged throat piece that runs on from it. One calf yields one noix, so a menu that lists it whole-roasted is quietly telling you how many it bought.",
fr:"Le boucher partage le thymus du veau en deux et vend les moitiés comme deux produits distincts : le lobe thoracique — la noix, ou pomme — vaut environ le double du morceau de gorge, plus déchiqueté, qui le prolonge. Un veau ne donne qu’une noix ; une carte qui l’annonce rôtie entière avoue donc discrètement combien elle en a acheté."},
tip:{en:"Degorge it three hours in cold water changed twice, blanch two minutes, peel the membrane while it is still warm, then press it overnight between two plates under a kilo. An unpressed noix steams instead of searing, and no amount of hot butter afterwards will fix that.",
fr:"Faites-la dégorger trois heures à l’eau froide changée deux fois, blanchissez deux minutes, retirez la membrane tant qu’elle est tiède, puis pressez-la une nuit entre deux assiettes sous un kilo. Une noix non pressée sue au lieu de se saisir, et aucun beurre chaud ne rattrapera cela."},
pairs:["morel","cream","butter","capers","lemon","shallot","white-wine-vinegar","parsley"],
svg:'<path class="f1 sf" d="M30 60q0-16 18-16t18 16q0 10-18 10T30 60z"/><path class="s" d="M24 40h48"/><rect class="f2 sf" x="40" y="28" width="16" height="10" rx="2"/><path class="s" d="M38 64q10 4 20 0"/>'},

{id:"ris-de-veau-gorge",cat:"cuts",name:{en:"Veal throat sweetbread (gorge)",fr:"Ris de veau — gorge"},latin:"Bos taurus (thymus, cervical lobe)",
origin:{en:"The cervical lobe, along the calf's windpipe",fr:"Le lobe cervical, le long de la trachée du veau"},season:[],
flavor:["delicate","milky","mild","rich"],
story:{en:"The gorge is the long lobe that runs up the throat toward the jaw, and it never sets into the neat cushion the noix makes — it comes away in ragged strips. Classical kitchens wasted none of it: this is the sweetbread of vol-au-vent, financière garnish and quenelle farce, where shape stops mattering.",
fr:"La gorge est le lobe allongé qui remonte le long de la trachée vers la mâchoire, et elle ne prend jamais la forme du coussin régulier que donne la noix : elle se détache en lambeaux. La cuisine classique n’en perdait rien — c’est le ris du vol-au-vent, de la garniture financière et de la farce à quenelles, là où la forme ne compte plus."},
tip:{en:"Buy it for anything bound in a sauce, never for a whole roast. Blanch, cut into thumb-sized pieces and braise 25 minutes in stock and cream; seared hard like a noix, the strips shrink and go stringy.",
fr:"Achetez-la pour tout ce qui se lie en sauce, jamais pour un rôti entier. Blanchissez, taillez en morceaux gros comme le pouce et braisez 25 minutes dans un fond crémé ; saisis vivement comme une noix, les lambeaux se rétractent et filandrent."},
pairs:["cream","butter","mushroom","chicken","white-wine-vinegar","shallot","nutmeg","parsley"],
svg:'<path class="f1 sf" d="M28 56q2-10 10-10 6 0 9 5 4-6 11-5 9 2 10 10 1 9-9 11-10 2-16 0-14-3-15-11z"/><path class="s" d="M38 58q6 5 14 3"/><path class="s" d="M50 51v6"/>'}
]);
