window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"adzuki",cat:"legumes",name:{en:"Adzuki bean",fr:"Haricot azuki"},latin:"Vigna angularis",
origin:{en:"East Asia",fr:"Asie de l’Est"},season:[],
flavor:["sweet","earthy","nutty","mild"],
story:{en:"In Japan and China it is treated as a dessert ingredient rather than a savoury one — boiled with sugar into anko, the sweet red paste inside almost every traditional confection. Red beans and rice are eaten at celebrations for the auspicious colour.",
fr:"Au Japon et en Chine on le traite en ingrédient de dessert plutôt que salé — bouilli avec du sucre en anko, la pâte rouge sucrée que renferme presque toute confiserie traditionnelle. Haricots rouges et riz se mangent aux fêtes pour la couleur porte-bonheur."},
tip:{en:"Change the water once during cooking if you want a clean sweet paste. The first water carries the bitterness.",
fr:"Changez l’eau une fois en cours de cuisson pour une pâte sucrée nette. La première eau emporte l’amertume."},
pairs:["sugar","rice","sesame","vanilla","coconut-milk","ginger","dark-chocolate","honey"],
svg:'<ellipse class="f1 sf" cx="41" cy="55" rx="6.5" ry="5"/><ellipse class="f1 sf" cx="54" cy="53" rx="6.5" ry="5"/><ellipse class="f1 sf" cx="47" cy="66" rx="6.5" ry="5"/><path class="s" d="M36 55h10M49 53h10"/>'},

{id:"beluga-lentil",cat:"legumes",name:{en:"Beluga lentil",fr:"Lentille beluga"},latin:"Lens culinaris",
origin:{en:"Canada & North America",fr:"Canada & Amérique du Nord"},season:[],
flavor:["earthy","nutty","mild","umami"],
story:{en:"Named for the caviar it resembles once cooked — small, glossy and jet black. The colour is anthocyanin and it survives cooking better than most, which is why the lentil stays black rather than turning the muddy brown of its cousins.",
fr:"Nommée d’après le caviar qu’elle évoque une fois cuite — petite, brillante et noire de jais. La couleur vient des anthocyanes et résiste mieux que la plupart à la cuisson, d’où une lentille qui reste noire au lieu de virer au brun boueux de ses cousines."},
tip:{en:"Serve it where the colour shows — under white fish, beside a poached egg. Buried in a brown stew you have wasted the point.",
fr:"Servez-la là où la couleur se voit — sous un poisson blanc, à côté d’un œuf poché. Noyée dans un ragoût brun, l’intérêt est perdu."},
pairs:["salmon","creme-fraiche","shallot","lemon","dill","olive-oil","egg","chives"],
svg:'<circle class="f1 sf" cx="40" cy="52" r="6.5"/><circle class="f1 sf" cx="55" cy="55" r="6.5"/><circle class="f1 sf" cx="46" cy="65" r="6.5"/><circle class="f1 sf" cx="59" cy="66" r="5.5"/>'},

{id:"black-bean",cat:"legumes",name:{en:"Black bean",fr:"Haricot noir"},latin:"Phaseolus vulgaris",
origin:{en:"Mexico & Central America",fr:"Mexique & Amérique centrale"},season:[],
flavor:["earthy","sweet","creamy","umami"],
story:{en:"The backbone of Brazilian feijoada and Cuban moros y cristianos, and it colours its cooking liquid deep purple-black — that liquid is not waste but the sauce, and throwing it away is the commonest mistake made with this bean.",
fr:"L’ossature de la feijoada brésilienne et des moros y cristianos cubains, et il colore son eau de cuisson en noir violacé — ce liquide n’est pas un déchet mais la sauce, et le jeter est l’erreur la plus fréquente avec ce haricot."},
tip:{en:"Keep the cooking liquid and reduce it. It is where the flavour and the body of the dish live.",
fr:"Gardez l’eau de cuisson et faites-la réduire. C’est là que résident le goût et le corps du plat."},
pairs:["cumin","lime","cilantro","chili","garlic","onion","avocado","orange"],
svg:'<ellipse class="f1 sf" cx="41" cy="54" rx="8.5" ry="6"/><ellipse class="f1 sf" cx="56" cy="56" rx="8.5" ry="6"/><ellipse class="f1 sf" cx="47" cy="67" rx="8.5" ry="6"/>'},

{id:"borlotti",cat:"legumes",name:{en:"Borlotti bean",fr:"Haricot borlotti"},latin:"Phaseolus vulgaris",
origin:{en:"Italy, from the Americas",fr:"Italie, depuis les Amériques"},season:[8,9,10],
flavor:["creamy","nutty","earthy","sweet"],
story:{en:"The cranberry-splashed pod and bean are spectacular raw and lose every trace of the pattern in the pot — they cook to a uniform brown. Nothing is wrong; the pigment is simply not heat stable, and Italian cooks have never minded.",
fr:"La cosse et le grain éclaboussés de rouge sont spectaculaires crus et perdent toute trace du motif à la casserole — ils cuisent en brun uniforme. Rien d’anormal : le pigment n’est simplement pas stable à la chaleur, et les cuisiniers italiens ne s’en sont jamais souciés."},
tip:{en:"Cook them with a whole peeled onion, a carrot and a stick of celery, then discard all three. It is the Italian way and it works.",
fr:"Cuisez-les avec un oignon épluché entier, une carotte et une branche de céleri, puis jetez les trois. C’est la méthode italienne et elle fonctionne."},
pairs:["sage","olive-oil","garlic","tomato","rosemary","pecorino","guanciale","cavolo-nero"],
svg:'<ellipse class="f2 sf" cx="41" cy="54" rx="9" ry="6.5"/><ellipse class="f2 sf" cx="56" cy="57" rx="9" ry="6.5"/><ellipse class="f2 sf" cx="47" cy="68" rx="9" ry="6.5"/><circle class="dot" cx="39" cy="53" r="1.4"/><circle class="dot" cx="57" cy="56" r="1.4"/>'},

{id:"cannellini",cat:"legumes",name:{en:"Cannellini bean",fr:"Haricot cannellini"},latin:"Phaseolus vulgaris",
origin:{en:"Tuscany, Italy",fr:"Toscane, Italie"},season:[],
flavor:["creamy","mild","nutty","earthy"],
story:{en:"Tuscans are nicknamed mangiafagioli, bean-eaters, and this is the bean they mean. The classic preparation is al fiasco — cooked overnight in a wine flask buried in the dying embers of a fire, with oil, garlic and sage.",
fr:"On surnomme les Toscans mangiafagioli, mangeurs de haricots, et c’est de celui-ci qu’il s’agit. La préparation classique est al fiasco — cuits toute la nuit dans une fiasque à vin enfouie sous les braises mourantes, avec huile, ail et sauge."},
tip:{en:"Save a ladle of the cooking liquid to loosen any purée. It emulsifies with olive oil far better than water does.",
fr:"Réservez une louche d’eau de cuisson pour détendre une purée. Elle s’émulsionne avec l’huile d’olive bien mieux que l’eau."},
pairs:["sage","olive-oil","garlic","rosemary","tomato","cavolo-nero","parmesan","escarole"],
svg:'<ellipse class="f3 sf" cx="40" cy="54" rx="9" ry="6"/><ellipse class="f3 sf" cx="56" cy="57" rx="9" ry="6"/><ellipse class="f3 sf" cx="47" cy="68" rx="9" ry="6"/>'},

{id:"chickpeas",cat:"legumes",name:{en:"Chickpeas",fr:"Pois chiches"},latin:"Cicer arietinum",
origin:{en:"Fertile Crescent & Anatolia",fr:"Croissant fertile & Anatolie"},season:[],
flavor:["nutty","earthy","buttery"],
story:{en:"Rome’s greatest orator, Cicero, owed his family name to the chickpea (cicer) — an ancestor supposedly had a chickpea-shaped wart, and he refused to change the name, promising to make it glorious instead. He did.",
fr:"Le plus grand orateur de Rome, Cicéron, devait son nom au pois chiche (cicer) — un ancêtre aurait porté une verrue en forme de pois chiche, et il refusa d’en changer, promettant plutôt de rendre ce nom glorieux. Il tint parole."},
tip:{en:"Keep the cooking water: whipped, it foams like egg white. A tin of chickpeas plus sesame paste and lemon is a five-minute feast.",
fr:"Gardez l’eau de cuisson : fouettée, elle monte comme du blanc d’œuf. Une boîte de pois chiches, de la crème de sésame et du citron : festin en cinq minutes."},
pairs:["sesame","lemon","cumin","garlic","spinach","tomato"],
svg:'<path class="f1 sf" d="M40 44a8 8 0 11-1 8q-2-4 1-8z"/><path class="f1 sf" d="M56 42a8 8 0 11-1 8q-2-4 1-8z"/><path class="f1 sf" d="M48 58a8 8 0 11-1 8q-2-4 1-8z"/>'},

{id:"coco-de-paimpol",cat:"legumes",name:{en:"Coco de Paimpol",fr:"Coco de Paimpol"},latin:"Phaseolus vulgaris",
origin:{en:"Côtes-d’Armor, Brittany",fr:"Côtes-d’Armor, Bretagne"},season:[8,9,10],
flavor:["creamy","sweet","mild","earthy"],
story:{en:"A fresh shelling bean rather than a dried one, sold still in its marbled pod and podded by hand — Brittany calls the work le plumage. It holds an AOC, and the season is short enough that most of the country never sees it.",
fr:"Un haricot demi-sec plutôt que sec, vendu encore dans sa cosse marbrée et écossé à la main — la Bretagne appelle ce travail le plumage. Il détient une AOC, et la saison est assez brève pour que la plus grande part du pays ne le voie jamais."},
tip:{en:"It needs no soaking, unlike every dried bean. Forty minutes in unsalted water and it is done.",
fr:"Il ne se trempe pas, contrairement à tout haricot sec. Quarante minutes à l’eau non salée et c’est prêt."},
pairs:["thyme","garlic","tomato","olive-oil","lamb","onion","bay-leaf","parsley"],
svg:'<path class="f3 sf" d="M28 58q14-18 40-14-6 20-30 24-12 2-10-10z"/><circle class="f2 sf" cx="42" cy="54" r="5"/><circle class="f2 sf" cx="54" cy="50" r="5"/>'},

{id:"dried-fava",cat:"legumes",name:{en:"Dried broad bean",fr:"Fève sèche"},latin:"Vicia faba",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["earthy","nutty","mild","bitter"],
story:{en:"Egypt eats it at breakfast as ful medames, simmered overnight in a narrow-necked pot, and the dish is older than the pyramids. In Sicily and Puglia it is boiled to a purée called macco and served with wild greens.",
fr:"L’Égypte la mange au petit-déjeuner en ful medames, mijotée toute la nuit dans une jarre à col étroit, et le plat est plus ancien que les pyramides. En Sicile et dans les Pouilles on la réduit en purée, le macco, servi avec des herbes sauvages."},
tip:{en:"Buy them already skinned if you can. Peeling a kilo of soaked dried favas by hand is an afternoon's work.",
fr:"Achetez-les décortiquées si possible. Peler un kilo de fèves sèches trempées à la main occupe un après-midi."},
pairs:["olive-oil","cumin","lemon","garlic","parsley","chili","escarole","onion"],
svg:'<path class="f2 sf" d="M34 34q-6 22 4 34t18-4q4-16-6-28t-16-2z"/><path class="s" d="M40 46q6 12 8 20"/>'},

{id:"flageolet",cat:"legumes",name:{en:"Flageolet",fr:"Flageolet"},latin:"Phaseolus vulgaris",
origin:{en:"Brittany, France",fr:"Bretagne, France"},season:[],
flavor:["delicate","fresh","mild","grassy"],
story:{en:"Picked before maturity, which is why it stays pale green rather than turning white — the bean is harvested young and dried immature. A Breton grower named Chevrier fixed the technique in the 1870s, and the French still call it the chevrier.",
fr:"Cueilli avant maturité, d’où sa couleur vert pâle plutôt que blanche — le grain est récolté jeune et séché immature. Un maraîcher breton nommé Chevrier fixa la technique dans les années 1870, et les Français l’appellent encore le chevrier."},
tip:{en:"It is the classic bean for gigot d'agneau, and it wants nothing more than butter, garlic and parsley. Do not overwhelm it.",
fr:"C’est le haricot classique du gigot d’agneau, et il ne demande que du beurre, de l’ail et du persil. Ne le noyez pas."},
pairs:["lamb","garlic","butter","parsley","cream","thyme","shallot","rosemary"],
svg:'<ellipse class="f3 sf" cx="40" cy="54" rx="9" ry="6"/><ellipse class="f3 sf" cx="55" cy="58" rx="9" ry="6"/><ellipse class="f3 sf" cx="47" cy="68" rx="9" ry="6"/>'},

{id:"kidney-bean",cat:"legumes",name:{en:"Kidney bean",fr:"Haricot rouge"},latin:"Phaseolus vulgaris",
origin:{en:"Peru & Central America",fr:"Pérou & Amérique centrale"},season:[],
flavor:["earthy","sweet","creamy","mild"],
story:{en:"Raw or undercooked, it is genuinely poisonous — it carries phytohaemagglutinin, and as few as four raw beans can make you seriously ill. Ten minutes at a hard boil destroys it, but a slow cooker never gets hot enough on its own.",
fr:"Crus ou insuffisamment cuits, ils sont réellement toxiques — ils portent de la phytohémagglutinine, et quatre grains crus suffisent à rendre gravement malade. Dix minutes à gros bouillons la détruisent, mais une mijoteuse seule n’atteint jamais cette température."},
tip:{en:"Boil hard for ten full minutes before any slow cooking. This is the one bean where the instruction is a safety rule, not a preference.",
fr:"Faites bouillir à gros bouillons dix minutes pleines avant toute cuisson lente. C’est le seul haricot où la consigne est une règle de sécurité, non une préférence."},
pairs:["chili","cumin","onion","tomato","garlic","paprika","rice","cilantro"],
svg:'<path class="f1 sf" d="M32 56q4-12 16-10t14 12-12 12-18-14z"/><path class="f1 sf" d="M44 70q4-8 14-6t8 10-14 6-8-10z"/>'},

{id:"lentils",cat:"legumes",name:{en:"Lentils",fr:"Lentilles"},latin:"Lens culinaris",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["earthy","mild","nutty"],
story:{en:"Esau sold his birthright for a bowl of lentil stew — the most expensive lunch in scripture. The optical lens is named after this seed, not the other way round; Italians eat them at New Year, each little disc a coin of luck.",
fr:"Ésaü vendit son droit d’aînesse pour un plat de lentilles — le déjeuner le plus cher des Écritures. La lentille optique doit son nom à cette graine, et non l’inverse ; les Italiens en mangent au Nouvel An, chaque petit disque valant une pièce de fortune."},
tip:{en:"Salt them only at the end — salted water toughens their skins. The little green ones from Le Puy hold their shape best in salads.",
fr:"Ne les salez qu’en fin de cuisson — l’eau salée durcit leur peau. Les petites vertes du Puy tiennent le mieux en salade."},
pairs:["cumin","bay-leaf","carrot","pork","yogurt","cilantro","turmeric"],
svg:'<path class="f2 sf" d="M36 46a5.5 5.5 0 100 .1zM52 42a5.5 5.5 0 100 .1zM62 52a5.5 5.5 0 100 .1zM42 58a5.5 5.5 0 100 .1zM54 62a5.5 5.5 0 100 .1zM34 64a5.5 5.5 0 100 .1z"/>'},

{id:"mung-bean",cat:"legumes",name:{en:"Mung bean",fr:"Haricot mungo"},latin:"Vigna radiata",
origin:{en:"India",fr:"Inde"},season:[],
flavor:["sweet","fresh","mild","grassy"],
story:{en:"What most of the world calls bean sprouts are these, germinated in the dark for four days. Whole, they are the base of Indian moong dal; ground and made into a batter they become the noodles sold across Asia as glass or cellophane noodles.",
fr:"Ce que le monde appelle germes de soja est en réalité ce haricot, germé quatre jours à l’obscurité. Entier, il fait le moong dal indien ; broyé et transformé en pâte, il devient les nouilles vendues dans toute l’Asie sous le nom de vermicelles de verre."},
tip:{en:"It is the one pulse that genuinely needs no soaking. Twenty-five minutes from dry and it is soft.",
fr:"C’est la seule légumineuse qui ne demande réellement aucun trempage. Vingt-cinq minutes depuis le sec et il est tendre."},
pairs:["ginger","turmeric","cumin","ghee","cilantro","chili","coconut-milk","lime"],
svg:'<ellipse class="f2 sf" cx="41" cy="55" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="53" cy="52" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="47" cy="64" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="58" cy="63" rx="6" ry="4.5"/>'},

{id:"lentille-du-puy",cat:"legumes",name:{en:"Puy lentil",fr:"Lentille verte du Puy"},latin:"Lens culinaris",
origin:{en:"Haute-Loire, Auvergne",fr:"Haute-Loire, Auvergne"},season:[],
flavor:["earthy","peppery","nutty","mild"],
story:{en:"The first vegetable in France to be granted an AOC, in 1996. It grows on volcanic soil at altitude where the summers are dry, and the lack of water is what keeps the skin thin and stops the lentil bursting — scarcity as a quality control.",
fr:"Le premier légume français à recevoir une AOC, en 1996. Elle pousse sur sol volcanique en altitude, sous des étés secs, et c’est le manque d’eau qui garde la peau fine et empêche la lentille d’éclater — la rareté comme contrôle qualité."},
tip:{en:"Never salt the cooking water at the start. Salt firms the skins and they take twice as long to soften.",
fr:"Ne salez jamais l’eau de cuisson au départ. Le sel raffermit les peaux et double le temps d’attendrissement."},
pairs:["sherry-vinegar","shallot","carrot","bay-leaf","duck","mustard","parsley","lard"],
svg:'<circle class="f2 sf" cx="40" cy="52" r="7"/><circle class="f2 sf" cx="56" cy="56" r="7"/><circle class="f2 sf" cx="47" cy="66" r="7"/><path class="s" d="M36 52h8M52 56h8"/>'},

{id:"red-lentil",cat:"legumes",name:{en:"Red lentil",fr:"Lentille corail"},latin:"Lens culinaris",
origin:{en:"Near East & South Asia",fr:"Proche-Orient & Asie du Sud"},season:[],
flavor:["sweet","earthy","mild","nutty"],
story:{en:"It is a brown lentil with its skin removed, which is why it is orange rather than red and why it collapses so fast — nothing is left to hold it together. Split and skinned, it cooks in fifteen minutes and turns to purée on its own.",
fr:"C’est une lentille brune décortiquée, d’où sa couleur orange plutôt que rouge et son effondrement si rapide — plus rien ne la tient. Fendue et sans peau, elle cuit en quinze minutes et se réduit en purée d’elle-même."},
tip:{en:"Use it when you want it to disappear — dal, soup, a thickener. If you need lentils to stay whole, this is the wrong one.",
fr:"Employez-la quand vous voulez qu’elle disparaisse — dal, soupe, liant. S’il faut des lentilles entières, ce n’est pas la bonne."},
pairs:["cumin","turmeric","ghee","ginger","garlic","cilantro","coconut-milk","chili"],
svg:'<circle class="f2 sf" cx="41" cy="54" r="7"/><circle class="f2 sf" cx="56" cy="52" r="7"/><circle class="f2 sf" cx="48" cy="66" r="7"/>'},

{id:"soy-bean",cat:"legumes",name:{en:"Soybean",fr:"Soja"},latin:"Glycine max",
origin:{en:"Northeast China",fr:"Nord-est de la Chine"},season:[],
flavor:["nutty","earthy","umami","mild"],
story:{en:"Domesticated in China more than three thousand years ago, and almost nothing about it is eaten as a bean — it becomes tofu, miso, soy sauce, oil and animal feed. Fresh in the pod it is edamame, which is the exception.",
fr:"Domestiqué en Chine il y a plus de trois mille ans, et il ne se mange presque jamais tel quel — il devient tofu, miso, sauce soja, huile et aliment du bétail. Frais dans sa cosse c’est l’edamame, qui fait exception."},
tip:{en:"Dried soybeans must be boiled hard and long — they contain trypsin inhibitors that raw or gently cooked beans retain.",
fr:"Les graines sèches doivent bouillir fort et longtemps — elles contiennent des inhibiteurs de trypsine que la cuisson douce ne détruit pas."},
pairs:["soy-sauce","miso","sesame","ginger","spring-onion","garlic","chili","tamari"],
svg:'<path class="f3 sf" d="M28 60q16-20 40-16-8 22-32 26-12 2-8-10z"/><circle class="f2 sf" cx="40" cy="56" r="5"/><circle class="f2 sf" cx="53" cy="51" r="5"/>'},

{id:"split-pea",cat:"legumes",name:{en:"Split pea",fr:"Pois cassé"},latin:"Pisum sativum",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["sweet","earthy","mild","creamy"],
story:{en:"A field pea dried, skinned and split along its natural seam, which is where it wants to divide anyway. Splitting doubles the surface and halves the cooking time — a piece of food engineering several thousand years old.",
fr:"Un pois de champ séché, décortiqué et fendu le long de sa suture naturelle, là où il tend de toute façon à se séparer. La fente double la surface et divise par deux le temps de cuisson — un travail d’ingénierie alimentaire vieux de plusieurs millénaires."},
tip:{en:"It foams enormously at first boil. Skim it once and the soup stays clear instead of turning grey.",
fr:"Il mousse énormément à la première ébullition. Écumez une fois et la soupe reste nette au lieu de grisonner."},
pairs:["lard","onion","carrot","bay-leaf","mint","thyme","black-pepper","butter"],
svg:'<path class="f2 sf" d="M32 54a8 8 0 0 1 16 0z"/><path class="f2 sf" d="M48 60a8 8 0 0 1 16 0z"/><path class="f2 sf" d="M38 68a8 8 0 0 1 16 0z"/>'},

{id:"haricot-tarbais",cat:"legumes",name:{en:"Tarbais bean",fr:"Haricot tarbais"},latin:"Phaseolus vulgaris",
origin:{en:"Hautes-Pyrénées, France",fr:"Hautes-Pyrénées, France"},season:[],
flavor:["creamy","mild","earthy","nutty"],
story:{en:"Traditionally grown climbing up maize stalks, which act as living stakes — the two crops were planted together for two centuries. Its skin is unusually fine, so it absorbs the fat of a cassoulet without disintegrating, which is why the dish specifies it.",
fr:"Traditionnellement cultivé grimpant sur des tiges de maïs, qui servent de tuteurs vivants — les deux cultures étaient associées depuis deux siècles. Sa peau est exceptionnellement fine : il absorbe le gras d’un cassoulet sans se déliter, et c’est pourquoi la recette l’exige."},
tip:{en:"Soak twelve hours, then start it in cold water and bring it up slowly. Dropping beans into boiling water splits every skin.",
fr:"Trempez douze heures, puis démarrez à l’eau froide en montant lentement. Jeter des haricots dans l’eau bouillante fend toutes les peaux."},
pairs:["duck-fat","garlic","thyme","lard","onion","tomato","bay-leaf","carrot"],
svg:'<path class="f3 sf" d="M34 32q-8 24 4 38t20-6q4-18-6-30t-18-2z"/><path class="s" d="M40 44q6 14 8 22"/>'},

{id:"white-beans",cat:"legumes",name:{en:"White beans",fr:"Haricots blancs"},latin:"Phaseolus vulgaris",
origin:{en:"Americas",fr:"Amériques"},season:[],
flavor:["mild","buttery","earthy"],
story:{en:"Beans crossed from the Americas in the 1530s; Catherine de’ Medici reportedly carried a pouch of them to France in her wedding luggage. Tuscans became such devotees that the rest of Italy nicknamed them mangiafagioli — the bean-eaters.",
fr:"Le haricot arriva des Amériques dans les années 1530 ; Catherine de Médicis, dit-on, en emporta une bourse dans ses bagages de mariage vers la France. Les Toscans en devinrent si friands que le reste de l’Italie les surnomma mangiafagioli — les mangeurs de haricots."},
tip:{en:"Cook them gently — a hard boil bursts their jackets — and always with a bay leaf and a whole garlic clove. Their broth is liquid silver: keep it.",
fr:"Cuisez-les doucement — un gros bouillon fait éclater leur peau — et toujours avec du laurier et une gousse d’ail entière. Leur bouillon est de l’argent liquide : gardez-le."},
pairs:["sage","tomato","rosemary","pork","bay-leaf","olive-oil","onion"],
svg:'<path class="f1 sf" d="M34 48q2-8 10-6 6 2 6 8t-8 8q-8 0-8-10z" transform="rotate(-14 42 52)"/><path class="f1 sf" d="M50 52q2-8 10-6 6 2 6 8t-8 8q-8 0-8-10z" transform="rotate(10 58 56)"/>'}
]);
