window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"nduja",cat:"meat",rare:true,name:{en:"'Nduja",fr:"’Nduja"},latin:"Sus scrofa & Capsicum (cured)",
origin:{en:"Spilinga, Calabria",fr:"Spilinga, Calabre"},season:[],
flavor:["hot","smoky","rich","meaty"],
story:{en:"Calabria’s spreadable firebomb: pork fat kneaded with enough local chili to cure it scarlet, aged in casings until it softens into a paste. Born around the village of Spilinga as poor mountain charcuterie, cousin to Mallorca’s sobrasada, it now sets menus alight from London to Tokyo.",
fr:"La bombe incendiaire tartinable de la Calabre : du gras de porc pétri avec assez de piment local pour le saler d’écarlate, affiné en boyau jusqu’à devenir pâte. Née autour du village de Spilinga comme charcuterie pauvre de montagne, cousine de la sobrasada majorquine, elle embrase aujourd’hui les cartes de Londres à Tokyo."},
tip:{en:"Melt a spoonful into warm honey for cheese, into tomato sauce, or under a seared scallop — it dissolves into pure, fruity heat.",
fr:"Fondez-en une cuillerée dans un miel tiède pour le fromage, dans une sauce tomate ou sous une Saint-Jacques snackée — elle se dissout en chaleur pure et fruitée."},
pairs:["honey","tomato","mozzarella","egg","scallop"],
svg:'<path class="f3 sf" d="M34 40q14-10 28 0 4 14 0 26-14 8-28 0-4-12 0-26z" transform="rotate(-8 48 52)"/><path class="s" d="M34 38q-4-4-2-8M62 38q4-4 2-8" stroke-width="1.8"/><path class="f1" d="M44 50a2 2 0 104 0 2 2 0 10-4 0M52 56a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"andouille",cat:"meat",name:{en:"Andouille",fr:"Andouille"},latin:"Andouille de Guémené",
origin:{en:"Brittany & Normandy",fr:"Bretagne & Normandie"},season:[],
flavor:["smoky","earthy","salty","umami"],
story:{en:"The Guémené version is built from concentric layers of pig's intestine threaded one inside another, so a slice shows perfect rings like a tree trunk. Vire makes a chopped version instead, and the two camps have never reconciled.",
fr:"La version de Guémené est bâtie de couches concentriques de chaudins enfilés les uns dans les autres, si bien qu’une tranche montre des anneaux parfaits comme un tronc d’arbre. Vire en fait une version hachée, et les deux camps ne se sont jamais réconciliés."},
tip:{en:"It is eaten cold and thinly sliced, as a starter. Andouillette is a different and much stronger thing — do not confuse them.",
fr:"Elle se mange froide et finement tranchée, en entrée. L’andouillette est autre chose, et bien plus forte — ne les confondez pas."},
pairs:["mustard","cider-vinegar","apple","flour-t65","beurre-demi-sel","cornichon","onion","black-pepper"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="20"/><circle class="s" cx="48" cy="56" r="14"/><circle class="s" cx="48" cy="56" r="8"/><circle class="dot" cx="48" cy="56" r="3"/>'},

{id:"jambon-de-bayonne",cat:"meat",name:{en:"Bayonne ham",fr:"Jambon de Bayonne"},latin:"Jambon de Bayonne IGP",
origin:{en:"Adour basin, southwest France",fr:"Bassin de l’Adour, Sud-Ouest"},season:[],
flavor:["salty","umami","nutty","rich"],
story:{en:"Salted with salt from the Adour basin — the designation requires it — and dried through a winter in air off the Pyrenees. The producers still rub the exposed face with a paste of pork fat and flour to slow the drying, a step called the pannage.",
fr:"Salé au sel du bassin de l’Adour — l’appellation l’exige — et séché tout un hiver dans l’air des Pyrénées. Les producteurs enduisent encore la face découverte d’une pâte de saindoux et de farine pour ralentir le séchage, étape appelée le pannage."},
tip:{en:"Slice it thicker than Spanish ham and let it come to room temperature. Cold and paper-thin, it tastes only of salt.",
fr:"Tranchez-le plus épais que le jambon espagnol et laissez-le revenir à température. Froid et translucide, il n’a que le goût du sel."},
pairs:["cantaloupe","fig","butter","piquillo","olive-oil","espelette","comte","flour-t65"],
svg:'<path class="f1 sf" d="M32 34q22-6 30 12t-10 30-26-8 6-34z"/><path class="s" d="M56 68l6 10"/><path class="s" d="M40 46q10 8 12 20"/>'},

{id:"beef",cat:"meat",name:{en:"Beef",fr:"Bœuf"},latin:"Bos taurus",
origin:{en:"Domesticated in the Near East",fr:"Domestiqué au Proche-Orient"},season:[],
flavor:["meaty","rich","umami"],
story:{en:"English legend claims a king was so delighted by a loin of beef that he knighted it on the spot: “Arise, Sir Loin.” The story is too good to be true and too good to die — much like a well-aged côte de bœuf.",
fr:"La légende anglaise veut qu’un roi, ravi par une pièce de bœuf, l’ait adoubée sur-le-champ : « Levez-vous, Sir Loin. » L’histoire est trop belle pour être vraie et trop belle pour mourir — comme une côte de bœuf bien affinée."},
tip:{en:"Take it out of the fridge an hour ahead, sear it hard, rest it as long as you cooked it. The resting is not optional; it is half the recipe.",
fr:"Sortez-le une heure avant, saisissez-le fort, laissez-le reposer aussi longtemps qu’il a cuit. Le repos n’est pas une option ; c’est la moitié de la recette."},
pairs:["black-pepper","mushroom","onion","mustard","blue-cheese","thyme","soy-sauce"],
svg:'<path class="f2 sf" d="M32 44q10-10 26-6 10 3 8 14-2 12-16 14-14 2-18-8-3-8 0-14z"/><path class="f1 sf" d="M54 44q8 2 6 10-1 6-8 8" fill="none"/><path class="s" d="M54 44q8 2 6 10-1 6-8 8"/>'},

{id:"boudin-noir",cat:"meat",name:{en:"Black pudding",fr:"Boudin noir"},latin:"Botellus niger",
origin:{en:"Ancient Greece",fr:"Grèce antique"},season:[],
flavor:["rich","earthy","meaty","umami"],
story:{en:"Homer describes it in the Odyssey — a stomach filled with fat and blood, roasted on a fire — which makes it one of the oldest recorded prepared foods in Europe. Every region of France has a version, and they argue about apples.",
fr:"Homère le décrit dans l’Odyssée — une panse emplie de gras et de sang, rôtie au feu — ce qui en fait l’un des plus anciens aliments préparés attestés d’Europe. Chaque région de France en a une version, et l’on s’y dispute à propos des pommes."},
tip:{en:"Cook it gently and never pierce the skin. High heat splits the casing and the whole thing empties into the pan.",
fr:"Cuisez-le doucement et ne percez jamais la peau. Une chaleur vive fend le boyau et tout se vide dans la poêle."},
pairs:["apple","onion","potato","cider-vinegar","butter","thyme","mustard","cream"],
svg:'<path class="f1 sf" d="M28 56q0-14 20-14t20 14-20 16-20-16z"/><path class="s" d="M28 56q20 8 40 0"/>'},

{id:"bresse-chicken",cat:"meat",luxe:true,name:{en:"Bresse chicken",fr:"Poulet de Bresse"},latin:"Gallus gallus (Bresse AOP)",
origin:{en:"Bresse, France",fr:"Bresse, France"},season:[],
flavor:["meaty","delicate","rich","milky"],
story:{en:"Blue feet, white feathers, red comb — a bird in the colours of the flag, and the only poultry ever granted appellation d’origine status, in 1957. Finished on corn and milk, judged each December at the Glorieuses contests, it earned Brillat-Savarin’s verdict: the queen of poultry, the poultry of kings.",
fr:"Pattes bleues, plumage blanc, crête rouge — un oiseau aux couleurs du drapeau, et la seule volaille jamais dotée d’une appellation d’origine, en 1957. Finie au maïs et au lait, jugée chaque décembre aux concours des Glorieuses, elle a mérité le verdict de Brillat-Savarin : reine des volailles, volaille des rois."},
tip:{en:"Roast it simply and baste like a devotee — the skin and the fat are the argument. Or poach it à la crème with morels, the Bresse Sunday liturgy.",
fr:"Rôtissez-le simplement et arrosez-le avec dévotion — la peau et le gras sont l’argument. Ou pochez-le à la crème et aux morilles, liturgie dominicale bressane."},
pairs:["cream","morel","tarragon","butter"],
svg:'<path class="f1 sf" d="M36 42q-8 10-2 20t18 8q14-2 14-16 0-8-8-12-12-6-22 0z"/><path class="f1 sf" d="M60 50l10-4-4 8z"/><path class="f3 sf" d="M40 36q-2-6 3-8 3 4 1 8z"/><path class="s" d="M44 70v8M52 70v8" stroke-width="1.8"/>'},

{id:"capon",cat:"meat",name:{en:"Capon",fr:"Chapon"},latin:"Gallus gallus domesticus",
origin:{en:"Rome",fr:"Rome"},season:[11,12],
flavor:["rich","meaty","delicate","buttery"],
story:{en:"A castrated cockerel, fattened slowly, and the practice began in Rome as a workaround: a law of 162 BC limited how many hens a household could eat, and said nothing about roosters. The fat marbles into the meat instead of sitting under the skin.",
fr:"Un coq castré et engraissé lentement, pratique née à Rome comme contournement : une loi de 162 av. J.-C. limitait le nombre de poules qu’un foyer pouvait manger, et ne disait rien des coqs. Le gras se persille dans la chair au lieu de rester sous la peau."},
tip:{en:"It is the one bird that genuinely rewards a long, slow roast — the internal fat bastes it from within.",
fr:"C’est la seule volaille qui récompense réellement un rôtissage long et doux — le gras interne l’arrose de l’intérieur."},
pairs:["truffle","butter","chestnut","morel","cream","thyme","foie-gras","shallot"],
svg:'<path class="f2 sf" d="M28 62q0-24 22-24t20 22q-16 14-42 2z"/><path class="f1 sf" d="M52 38q8-10 14-4-6 8-14 4z"/><circle class="dot" cx="44" cy="54" r="1.6"/>'},

{id:"chicken",cat:"meat",name:{en:"Chicken",fr:"Poulet"},latin:"Gallus gallus domesticus",
origin:{en:"Jungle fowl of Southeast Asia",fr:"Coq sauvage d’Asie du Sud-Est"},season:[],
flavor:["mild","meaty","delicate"],
story:{en:"Every chicken descends from a shy jungle bird of Southeast Asia. Henri IV of France wished “a chicken in every peasant’s pot, every Sunday” — the poule au pot became a political promise, and the bird the most eaten meat on the planet.",
fr:"Tout poulet descend d’un timide oiseau des jungles d’Asie du Sud-Est. Henri IV souhaitait « une poule au pot pour chaque laboureur, chaque dimanche » — la poule au pot devint promesse politique, et l’oiseau la viande la plus mangée de la planète."},
tip:{en:"Salt it the night before and let it dry uncovered in the fridge: the skin will roast to glass. The carcass owes you a stock — collect the debt.",
fr:"Salez-le la veille et laissez-le sécher à découvert au réfrigérateur : la peau rôtira comme du verre. La carcasse vous doit un bouillon — réclamez votre dû."},
pairs:["lemon","garlic","tarragon","thyme","mustard","paprika","mushroom","rosemary"],
svg:'<path class="f1 sf" d="M36 40q-8 10-2 20t18 8q14-2 14-16 0-8-8-12-12-6-22 0z"/><path class="f1 sf" d="M60 48l10-4-4 8z"/><path class="s" d="M40 46q4-2 8 0"/>'},

{id:"saucisson-sec",cat:"meat",name:{en:"Dry sausage",fr:"Saucisson sec"},latin:"Salsicium siccum",
origin:{en:"France",fr:"France"},season:[],
flavor:["salty","umami","rich","meaty"],
story:{en:"The white bloom on the casing is a deliberately introduced mould, Penicillium, not a fault — it keeps unwanted moulds off and regulates drying. Lyon and the Ardèche each claim to make the best, and neither will concede.",
fr:"La fleur blanche sur le boyau est une moisissure introduite volontairement, du Penicillium, non un défaut — elle écarte les moisissures indésirables et régule le séchage. Lyon et l’Ardèche revendiquent chacune le meilleur, et aucune ne cède."},
tip:{en:"Peel the casing only on the piece you are cutting. Stripped entirely, the whole sausage dries out within a day.",
fr:"Ne pelez le boyau que sur la portion que vous coupez. Entièrement dénudé, le saucisson sèche en un jour."},
pairs:["cornichon","flour-t65","beurre-demi-sel","black-pepper","comte","red-wine-vinegar","mustard","olive"],
svg:'<path class="f1 sf" d="M34 30q12 0 12 14v28q0 8-12 8t-12-8V44q0-14 12-14z" transform="translate(14 0)"/><path class="s" d="M36 44h24M36 58h24"/>'},

{id:"duck",cat:"meat",name:{en:"Duck",fr:"Canard"},latin:"Anas platyrhynchos domesticus",
origin:{en:"Domesticated in China",fr:"Domestiqué en Chine"},season:[10,11,12,1],
flavor:["rich","meaty","sweet"],
story:{en:"China domesticated the duck millennia ago and perfected its roasting into imperial ceremony. France answered with its own schools — rare Rouen duck, pressed at the table in silver contraptions, and the Southwest’s confit, where the bird is preserved in its own gold.",
fr:"La Chine domestiqua le canard il y a des millénaires et fit de son rôtissage une cérémonie impériale. La France répondit avec ses écoles — le canard de Rouen pressé en salle dans des machines d’argent, et le confit du Sud-Ouest, où l’oiseau se conserve dans son propre or."},
tip:{en:"Score the fat, start it in a cold pan, and pour off the rendered fat as you go — then roast your next potatoes in it and understand the Southwest of France.",
fr:"Quadrillez le gras, démarrez à poêle froide, et réservez la graisse fondue au fur et à mesure — puis rôtissez-y vos prochaines pommes de terre et comprenez le Sud-Ouest."},
pairs:["orange","cherry","honey","pomegranate","thyme","turmeric"],
svg:'<path class="f2 sf" d="M32 56q0-12 14-12 6 0 8-6 2-8 10-6 6 2 4 10l-4 6q4 4 2 10-4 10-18 10t-16-12z"/><path class="dot" d="M62 38a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/><path class="s" d="M68 42l6 2-6 2"/>'},

{id:"foie-gras",cat:"meat",luxe:true,name:{en:"Foie gras",fr:"Foie gras"},latin:"Anser & Anas (foie)",
origin:{en:"Egypt of the pharaohs; Alsace & the Southwest",fr:"Égypte des pharaons ; Alsace & Sud-Ouest"},season:[],
flavor:["rich","buttery","sweet","delicate"],
story:{en:"Reliefs at Saqqara show Egyptians fattening geese 4,500 years ago; Rome fed them figs and called the delicacy iecur ficatum — “fig liver” — and ficatum became foie, fegato, hígado: the very word for liver in Romance languages descends from this dish.",
fr:"Les bas-reliefs de Saqqarah montrent des Égyptiens engraissant des oies il y a 4 500 ans ; Rome les nourrissait de figues et nomma le mets iecur ficatum — « foie aux figues » — et ficatum devint foie, fegato, hígado : le mot même du foie dans les langues romanes descend de ce plat."},
tip:{en:"Terrine barely set and eaten with a spoon’s edge, or escalopes seared in a dry, screaming pan for a minute a side — the fat it releases is a sauce in itself. Sweetness beside it, never sugar on it.",
fr:"En terrine à peine prise, mangée au bord de la cuillère, ou en escalopes saisies une minute par face à la poêle sèche et brûlante — la graisse rendue est une sauce à elle seule. Du sucré à côté, jamais du sucre dessus."},
pairs:["fig","quince","honey","grape","black-pepper"],
svg:'<path class="f1 sf" d="M32 52q0-14 16-14 20 0 18 14-1 10-10 12l-6-6-4 8q-12-2-14-14z"/><path class="s" d="M40 48q6-4 14-2" stroke-width="1.6"/>'},

{id:"goose",cat:"meat",name:{en:"Goose",fr:"Oie"},latin:"Anser anser domesticus",
origin:{en:"Europe & Egypt",fr:"Europe & Égypte"},season:[11,12,1],
flavor:["rich","meaty","umami","earthy"],
story:{en:"The Christmas bird of Europe before the turkey crossed the Atlantic, and geese were once walked to market in flocks with tar on their feet to protect them on the road. A roasting goose renders close to a litre of fat.",
fr:"L’oiseau de Noël européen avant que la dinde ne traverse l’Atlantique, et on menait jadis les oies au marché en troupeaux, les pattes enduites de goudron pour la route. Une oie rôtie rend près d’un litre de graisse."},
tip:{en:"Prick the skin all over and pour off the fat three or four times during roasting. Keep every drop of it.",
fr:"Piquez la peau partout et retirez la graisse trois ou quatre fois pendant la cuisson. Gardez-en chaque goutte."},
pairs:["apple","red-cabbage","chestnut","onion","sage","thyme","juniper","potato"],
svg:'<path class="f3 sf" d="M28 62q2-22 22-22t20 20q-16 14-42 2z"/><path class="s" d="M50 40q10-16 20-12"/><circle class="dot" cx="60" cy="32" r="1.8"/>'},

{id:"guanciale",cat:"meat",rare:true,name:{en:"Guanciale",fr:"Guanciale"},latin:"Sus scrofa (jowl, cured)",
origin:{en:"Central Italy",fr:"Italie centrale"},season:[],
flavor:["rich","salty","meaty","sweet"],
story:{en:"Pork jowl — guancia means cheek — cured with salt and pepper and hung until its fat turns to perfume. Rome guards it jealously: without guanciale there is no true carbonara, no amatriciana, and suggesting bacon in its place is the fastest way to start an argument in Trastevere.",
fr:"La joue de porc — guancia signifie joue — salée, poivrée et suspendue jusqu’à ce que son gras devienne parfum. Rome y veille jalousement : sans guanciale, pas de vraie carbonara ni d’amatriciana, et proposer des lardons à sa place est le plus court chemin vers une dispute à Trastevere."},
tip:{en:"Start it in a cold pan and let the fat melt slowly to glass-crisp — that rendered gold is the sauce; never add oil beside it.",
fr:"Démarrez-le à poêle froide et laissez le gras fondre doucement jusqu’au croustillant — cet or fondu est la sauce ; n’ajoutez jamais d’huile à côté."},
pairs:["egg","parmesan","tomato","black-pepper","white-beans"],
svg:'<path class="f1 sf" d="M32 40q16-8 32 0l-2 28q-14 6-28 0z"/><path class="f2 sf" d="M32 40q16-8 32 0l-1 8q-15-7-30 0z"/><path class="s" d="M40 56q8 4 16 0" stroke-width="1.6"/>'},

{id:"guinea-fowl",cat:"meat",name:{en:"Guinea fowl",fr:"Pintade"},latin:"Numida meleagris",
origin:{en:"West Africa",fr:"Afrique de l’Ouest"},season:[],
flavor:["meaty","earthy","delicate","umami"],
story:{en:"Domesticated in West Africa and kept by the Greeks and Romans, who called it the Numidian hen. It sits between chicken and pheasant — slightly gamey, considerably leaner, and it has a reputation for drying out that is entirely deserved.",
fr:"Domestiquée en Afrique de l’Ouest et élevée par les Grecs et les Romains, qui l’appelaient poule de Numidie. Elle se situe entre le poulet et le faisan — légèrement gibier, nettement plus maigre, et sa réputation de sécher est pleinement méritée."},
tip:{en:"Bard it with fat or cook it under a lid with liquid. Roasted naked like a chicken it will disappoint every time.",
fr:"Bardez-la de gras ou cuisez-la à couvert avec du liquide. Rôtie nue comme un poulet, elle décevra à tous les coups."},
pairs:["lard","cabbage","thyme","cream","mushroom","bay-leaf","shallot","juniper"],
svg:'<path class="f2 sf" d="M32 62q0-20 18-20t18 20q-14 12-36 0z"/><path class="s" d="M50 42q6-12 14-10"/><circle class="dot" cx="42" cy="54" r="1.6"/><circle class="dot" cx="54" cy="56" r="1.6"/>'},

{id:"hare",cat:"meat",name:{en:"Hare",fr:"Lièvre"},latin:"Lepus europaeus",
origin:{en:"Europe",fr:"Europe"},season:[10,11,12,1],
flavor:["rich","meaty","earthy","musky"],
story:{en:"Lièvre à la royale is the most demanding dish in the classical French repertoire — the hare is boned, stuffed, cooked for hours and its sauce thickened with its own blood and liver. Restaurants that offer it usually require notice of a day.",
fr:"Le lièvre à la royale est le plat le plus exigeant du répertoire classique français — le lièvre est désossé, farci, cuit des heures et sa sauce liée de son propre sang et de son foie. Les restaurants qui le proposent demandent en général un jour de prévenance."},
tip:{en:"Far stronger and darker than rabbit, and not interchangeable with it. If a recipe says hare, rabbit will taste thin.",
fr:"Bien plus fort et plus sombre que le lapin, et non interchangeable. Si une recette dit lièvre, le lapin paraîtra maigre."},
pairs:["red-wine-vinegar","juniper","foie-gras","shallot","thyme","dark-chocolate","bay-leaf","lard"],
svg:'<path class="f1 sf" d="M34 64q2-18 16-18t14 16q-12 12-30 2z"/><path class="s" d="M42 46q-4-16 0-18 4 4 4 18M52 46q4-16 8-16-2 6-4 16"/>'},

{id:"iberico-ham",cat:"meat",luxe:true,name:{en:"Ibérico ham",fr:"Jambon ibérique"},latin:"Sus scrofa (ibérico de bellota)",
origin:{en:"Dehesas of Spain & Portugal",fr:"Dehesas d’Espagne & du Portugal"},season:[],
flavor:["nutty","sweet","umami","rich"],
story:{en:"Each autumn the black-hoofed pigs enter the montanera, roaming holm-oak parkland and eating up to ten kilos of acorns a day — the fat turns silken and faintly of hazelnut. Cured for years and carved by professional cortadores in slices thin as stained glass, it is charcuterie’s absolute summit.",
fr:"Chaque automne, les porcs aux sabots noirs entrent en montanera, parcourant les chênaies et mangeant jusqu’à dix kilos de glands par jour — leur gras devient soyeux, vaguement noisetté. Affiné des années et découpé par des cortadores professionnels en tranches fines comme du vitrail, c’est le sommet absolu de la charcuterie."},
tip:{en:"Serve at warm room temperature so the fat turns translucent and melts on the tongue — never from the fridge, never with strong bread. The white streaks are the point.",
fr:"Servez-le à température ambiante chaude, que le gras devienne translucide et fonde sur la langue — jamais au sortir du froid, jamais avec un pain trop fort. Les veines blanches sont l’essentiel."},
pairs:["fig","almond","tomato","olive-oil"],
svg:'<path class="f2 sf" d="M28 62q2-12 16-16l16-6q10-2 12 6t-8 12l-18 6q-12 4-18-2z"/><path class="s" d="M60 40q4-6 10-6" stroke-width="1.8"/><path class="f1" d="M36 56q10-6 22-8" fill="none"/><path class="s" d="M36 56q10-6 22-8" stroke-width="1.4"/>'},

{id:"lamb",cat:"meat",name:{en:"Lamb",fr:"Agneau"},latin:"Ovis aries",
origin:{en:"Domesticated in Mesopotamia",fr:"Domestiqué en Mésopotamie"},season:[3,4,5,6],
flavor:["meaty","rich","grassy"],
story:{en:"Humanity’s spring meat, at Easter and Eid alike, from the first flocks of Mesopotamia. France’s most prized lambs graze the salt marshes of Mont-Saint-Michel — pré-salé, “pre-salted” by the sea itself, seasoned before the kitchen ever sees them.",
fr:"La viande du printemps de l’humanité, à Pâques comme à l’Aïd, depuis les premiers troupeaux de Mésopotamie. Les agneaux les plus prisés de France paissent les herbus du Mont-Saint-Michel — les prés-salés, assaisonnés par la mer elle-même avant que la cuisine ne les voie."},
tip:{en:"Garlic and rosemary are its old marriage; cumin and yogurt its brilliant second life. Always rest it — lamb punishes impatience with grey meat.",
fr:"L’ail et le romarin sont son vieux mariage ; le cumin et le yaourt sa brillante seconde vie. Laissez-le toujours reposer — l’agneau punit l’impatience par une viande grise."},
pairs:["rosemary","garlic","mint","cumin","yogurt","cinnamon"],
svg:'<path class="f1 sf" d="M34 50a7 7 0 015-12 8 8 0 0110-4 8 8 0 0110 4 7 7 0 015 12 7 7 0 01-4 11q-2 6-11 6t-11-6a7 7 0 01-4-11z"/><path class="f2 sf" d="M40 62q-2 8-6 10M56 62q2 8 6 10" fill="none"/><path class="s" d="M40 62q-2 8-6 10M56 62q2 8 6 10"/>'},

{id:"lardo",cat:"meat",name:{en:"Lardo",fr:"Lardo"},latin:"Lardo di Colonnata IGP",
origin:{en:"Colonnata, Tuscany",fr:"Colonnata, Toscane"},season:[],
flavor:["rich","salty","herbal","creamy"],
story:{en:"Cured in basins carved from the same Carrara marble Michelangelo used, packed with salt, rosemary and garlic, and left for months. The marble's porosity and constant cool are the point — the quarrymen who invented it ate it on bread for lunch.",
fr:"Affiné dans des bassins taillés dans le même marbre de Carrare que Michel-Ange employait, tassé avec sel, romarin et ail, et laissé des mois. La porosité et la fraîcheur constante du marbre font tout — les carriers qui l’ont inventé le mangeaient sur du pain à midi."},
tip:{en:"Slice it almost transparent and lay it on warm bread or hot potatoes. The heat is what makes it melt and release its perfume.",
fr:"Tranchez-le presque transparent et posez-le sur du pain tiède ou des pommes de terre chaudes. C’est la chaleur qui le fait fondre et libérer son parfum."},
pairs:["rosemary","flour-t65","black-pepper","garlic","potato","fig","sage","olive-oil"],
svg:'<path class="f3 sf" d="M28 46h40v20H28z"/><path class="s" d="M28 56h40"/><path class="s" d="M36 46v20M52 46v20"/>'},

{id:"partridge",cat:"meat",name:{en:"Partridge",fr:"Perdrix"},latin:"Perdix perdix",
origin:{en:"Europe & western Asia",fr:"Europe & Asie occidentale"},season:[9,10,11,12],
flavor:["delicate","meaty","earthy","sweet"],
story:{en:"French tradition distinguishes the perdreau, a young bird of the year, from the perdrix, an older one — and treats them as different ingredients entirely. The young is roasted; the old is only ever braised with cabbage.",
fr:"La tradition française distingue le perdreau, oiseau de l’année, de la perdrix plus âgée — et les traite en ingrédients entièrement différents. Le jeune se rôtit ; la vieille ne se fait jamais qu’au chou."},
tip:{en:"Ask which one you have. Roasting an old partridge produces something closer to leather than to dinner.",
fr:"Demandez lequel vous tenez. Rôtir une vieille perdrix produit quelque chose de plus proche du cuir que du dîner."},
pairs:["cabbage","lard","juniper","thyme","grape","bay-leaf","chestnut","shallot"],
svg:'<path class="f2 sf" d="M34 62q0-16 15-16t15 16q-13 10-30 0z"/><path class="s" d="M50 46q6-8 12-6"/><circle class="dot" cx="44" cy="55" r="1.4"/>'},

{id:"pheasant",cat:"meat",name:{en:"Pheasant",fr:"Faisan"},latin:"Phasianus colchicus",
origin:{en:"Caucasus & Asia",fr:"Caucase & Asie"},season:[10,11,12,1],
flavor:["meaty","earthy","delicate","musky"],
story:{en:"Its Latin name points at the river Phasis in Colchis, on the Black Sea, where the Greeks said the Argonauts found it. Farmed birds released for shooting taste almost of chicken; a genuinely wild one does not.",
fr:"Son nom latin renvoie au fleuve Phase en Colchide, sur la mer Noire, où les Grecs disaient que les Argonautes l’avaient trouvé. Les oiseaux d’élevage lâchés pour la chasse ont presque le goût du poulet ; un vrai sauvage, non."},
tip:{en:"The hen is smaller and more tender than the cock. If you are given a choice, take the hen.",
fr:"La poule est plus petite et plus tendre que le coq. Si l’on vous laisse le choix, prenez la poule."},
pairs:["cabbage","lard","apple","thyme","juniper","cream","mushroom","chestnut"],
svg:'<path class="f2 sf" d="M30 60q2-18 18-18t16 16q-12 12-34 2z"/><path class="s" d="M64 52q12 4 18 14M64 56q12 6 16 16"/>'},

{id:"pigeon",cat:"meat",name:{en:"Pigeon",fr:"Pigeon"},latin:"Columba livia domestica",
origin:{en:"Mediterranean & Near East",fr:"Méditerranée & Proche-Orient"},season:[],
flavor:["rich","meaty","earthy","umami"],
story:{en:"Every French château had a colombier, and the right to keep one was a feudal privilege abolished in 1789 — the birds ate the peasants' grain and only the lord could own them. Its breast is dark because pigeons actually fly.",
fr:"Chaque château français avait son colombier, et le droit d’en tenir un était un privilège féodal aboli en 1789 — les oiseaux mangeaient le grain des paysans et seul le seigneur pouvait les posséder. Sa poitrine est sombre parce que le pigeon vole réellement."},
tip:{en:"Serve the breast pink, closer to duck than chicken. Cooked through it turns liverish and grey.",
fr:"Servez le filet rosé, plus proche du canard que du poulet. Cuit à cœur il devient gris et goûte le foie."},
pairs:["foie-gras","cherry","beetroot","thyme","red-wine-vinegar","juniper","pea","hazelnut"],
svg:'<path class="f1 sf" d="M32 60q2-18 18-18t16 16q-12 12-34 2z"/><path class="s" d="M48 44q8-12 16-8"/><path class="s" d="M40 58q10 6 20 0"/>'},

{id:"pork",cat:"meat",name:{en:"Pork",fr:"Porc"},latin:"Sus scrofa domesticus",
origin:{en:"Domesticated in Anatolia & China",fr:"Domestiqué en Anatolie & en Chine"},season:[],
flavor:["meaty","sweet","rich"],
story:{en:"“Everything is good in the pig, from head to tail,” says the French proverb — and charcuterie is the proof: centuries of salting, smoking and patience invented to waste nothing. Every farm once measured winter by its pig.",
fr:"« Dans le cochon, tout est bon, de la tête à la queue », dit le proverbe — et la charcuterie en est la preuve : des siècles de salaisons, de fumage et de patience inventés pour ne rien perdre. Chaque ferme mesurait jadis l’hiver à son cochon."},
tip:{en:"Modern pork is lean and unforgiving: brine chops an hour before cooking, and pull them off the heat while still blushing at the bone.",
fr:"Le porc moderne est maigre et impitoyable : saumurez les côtes une heure avant cuisson, et retirez-les du feu quand l’os rosit encore."},
pairs:["apple","sage","mustard","maple-syrup","fennel","clove","lentils","chestnut"],
svg:'<path class="f1 sf" d="M30 54q0-14 18-14t18 14q0 12-18 12T30 54z"/><ellipse class="f2 sf" cx="60" cy="54" rx="6" ry="7"/><path class="dot" d="M58 52a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0M58 57a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0"/><path class="s" d="M34 42q-4-4-2-8 4 0 6 5"/>'},

{id:"poussin",cat:"meat",name:{en:"Poussin",fr:"Poussin"},latin:"Gallus gallus domesticus",
origin:{en:"France",fr:"France"},season:[],
flavor:["delicate","mild","sweet","buttery"],
story:{en:"A chicken slaughtered at about four weeks and under five hundred grams — one bird per person, which is the whole appeal. The flesh has had no time to develop much flavour, so it lives or dies on what you put on it.",
fr:"Un poulet abattu vers quatre semaines et sous les cinq cents grammes — un oiseau par personne, ce qui fait tout son intérêt. La chair n’a pas eu le temps de développer beaucoup de goût : tout dépend de ce qu’on met dessus."},
tip:{en:"Marinate it, then grill it flat under a weight. Its virtue is speed and crisp skin, not depth of flavour.",
fr:"Marinez-le, puis grillez-le à plat sous un poids. Sa vertu est la rapidité et la peau croustillante, non la profondeur."},
pairs:["lemon","garlic","thyme","olive-oil","harissa","paprika","rosemary","butter"],
svg:'<path class="f3 sf" d="M36 60q0-16 14-16t14 16q-12 10-28 0z"/><path class="s" d="M50 44q6-8 12-6"/>'},

{id:"prosciutto",cat:"meat",name:{en:"Prosciutto",fr:"Jambon cru"},latin:"Perna (dry-cured)",
origin:{en:"Parma, Italy",fr:"Parme, Italie"},season:[],
flavor:["salty","sweet","umami","delicate"],
story:{en:"Cato the Elder wrote down the method twenty-two centuries ago: salt, air, time — nothing else has been added since. The hills around Parma sell their very wind: hams hang in tall shuttered houses so the breeze off the Apennines can finish what the salt began.",
fr:"Caton l’Ancien en consigna la méthode il y a vingt-deux siècles : sel, air, temps — on n’y a rien ajouté depuis. Les collines de Parme vendent jusqu’à leur vent : les jambons pendent dans de hautes maisons à persiennes pour que la brise des Apennins achève ce que le sel a commencé."},
tip:{en:"Sliced so thin you can read through it, served at room temperature — never cooked into oblivion. Its salt loves sweet fruit: figs, melon, peaches.",
fr:"Tranché si fin qu’on lit au travers, servi à température ambiante — jamais cuit à l’oubli. Son sel adore les fruits doux : figues, melon, pêches."},
pairs:["fig","mozzarella","asparagus","peach","parmesan","balsamic"],
svg:'<path class="f2 sf" d="M30 44q10-8 22-4-6 8 2 10 10-8 14 2 2 8-8 12-16 6-26-2-8-8-4-18z"/><path class="f1" d="M36 48q8-4 14 0" fill="none"/><path class="s" d="M36 48q8-4 14 0M40 58q8-4 16-1" stroke-width="1.8"/>'},

{id:"quail",cat:"meat",name:{en:"Quail",fr:"Caille"},latin:"Coturnix coturnix",
origin:{en:"Eurasia & Africa",fr:"Eurasie & Afrique"},season:[],
flavor:["delicate","meaty","sweet","earthy"],
story:{en:"The Israelites in Exodus are fed on quail driven in by the wind, which matches the real thing — migrating quail cross the Mediterranean in exhausted flocks and drop on the far shore in numbers. Egypt has netted them that way for millennia.",
fr:"Les Hébreux de l’Exode sont nourris de cailles poussées par le vent, ce qui correspond au réel — les cailles migratrices traversent la Méditerranée en vols épuisés et s’abattent en nombre sur l’autre rive. L’Égypte les y capture au filet depuis des millénaires."},
tip:{en:"Spatchcock it and cook it fast and hot. A whole quail roasted slowly is dry breast and raw thigh at the same moment.",
fr:"Ouvrez-la en crapaudine et cuisez-la vite et fort. Une caille entière rôtie doucement donne un blanc sec et une cuisse crue au même instant."},
pairs:["grape","thyme","lard","fig","honey","juniper","sage","hazelnut"],
svg:'<path class="f2 sf" d="M36 60q0-16 14-16t14 16q-12 10-28 0z"/><path class="s" d="M50 44q5-10 12-8"/><circle class="dot" cx="45" cy="54" r="1.4"/>'},

{id:"rabbit",cat:"meat",name:{en:"Rabbit",fr:"Lapin"},latin:"Oryctolagus cuniculus",
origin:{en:"Iberian peninsula",fr:"Péninsule ibérique"},season:[],
flavor:["delicate","mild","meaty","sweet"],
story:{en:"Spain may be named after it — one theory derives Hispania from a Phoenician word for the land of hyraxes, the sailors having mistaken rabbits for something familiar. Monks farmed them in medieval France as a Lenten loophole.",
fr:"L’Espagne lui doit peut-être son nom — une hypothèse fait venir Hispania d’un mot phénicien pour terre de damans, les marins ayant pris les lapins pour un animal connu. Les moines les élevaient dans la France médiévale comme échappatoire au Carême."},
tip:{en:"The saddle and the legs cook completely differently — the saddle in fifteen minutes, the legs in an hour. Separate them.",
fr:"Le râble et les cuisses ne cuisent pas du tout pareil — le râble en quinze minutes, les cuisses en une heure. Séparez-les."},
pairs:["mustard","thyme","lard","white-wine-vinegar","bay-leaf","shallot","cream","tarragon"],
svg:'<path class="f3 sf" d="M34 64q2-16 16-16t14 14q-12 12-30 2z"/><path class="s" d="M42 48q-3-14 0-16 3 3 3 16M52 48q3-14 6-15-2 5-3 15"/>'},

{id:"turkey",cat:"meat",name:{en:"Turkey",fr:"Dinde"},latin:"Meleagris gallopavo",
origin:{en:"Mexico",fr:"Mexique"},season:[11,12],
flavor:["mild","meaty","delicate","umami"],
story:{en:"A Mexican bird that English speakers named after Turkey and the French after India — dinde, from poule d'Inde — because both assumed anything exotic came from somewhere east. Neither guess was even close.",
fr:"Un oiseau mexicain que les anglophones ont nommé d’après la Turquie et les Français d’après l’Inde — dinde, de poule d’Inde — parce que les deux supposaient qu’un produit exotique venait d’Orient. Aucune des deux hypothèses n’était proche."},
tip:{en:"Brine it or cook the legs and breast separately. They want temperatures forty minutes apart and no roasting method reconciles them.",
fr:"Saumurez-la ou cuisez cuisses et blanc séparément. Ils veulent des cuissons distantes de quarante minutes qu’aucune méthode de rôtissage ne réconcilie."},
pairs:["chestnut","sage","cranberry","butter","thyme","onion","bay-leaf","lard"],
svg:'<path class="f2 sf" d="M30 62q0-22 20-22t20 22q-16 12-40 0z"/><path class="f3 sf" d="M64 40q10-6 14 2-8 6-14 2z"/><path class="s" d="M28 56q-6-2-8-8"/>'},

{id:"venison",cat:"meat",name:{en:"Venison",fr:"Chevreuil"},latin:"Capreolus capreolus",
origin:{en:"Europe",fr:"Europe"},season:[9,10,11,12,1],
flavor:["meaty","earthy","rich","musky"],
story:{en:"Almost fat-free, because a wild animal that runs does not store marbling — which is why it dries out at temperatures beef would shrug off. Medieval forest law reserved it for the king, and poaching it could cost a hand.",
fr:"Presque sans gras, parce qu’un animal sauvage qui court ne stocke pas de persillé — d’où son dessèchement à des températures qu’un bœuf supporterait sans peine. Le droit forestier médiéval le réservait au roi, et le braconner pouvait coûter une main."},
tip:{en:"Serve it rare and rest it long. There is no fat to keep it moist and no forgiveness past medium.",
fr:"Servez-le saignant et laissez-le reposer longtemps. Il n’a pas de gras pour le garder moelleux et aucune indulgence au-delà du rosé."},
pairs:["juniper","red-wine-vinegar","blackberry","chestnut","cubeb","thyme","celeriac","dark-chocolate"],
svg:'<path class="f1 sf" d="M30 64q4-22 20-22t18 20q-14 12-38 2z"/><path class="s" d="M40 42l-6-12 8 6M56 42l6-12-8 6"/>'},

{id:"wagyu",cat:"meat",luxe:true,name:{en:"Wagyu beef",fr:"Bœuf wagyu"},latin:"Bos taurus (wagyū)",
origin:{en:"Japan",fr:"Japon"},season:[],
flavor:["rich","buttery","meaty","umami"],
story:{en:"Closed Japanese bloodlines bred for a century until the marbling threads through the muscle like frost on a window — graded to the strictest scale in meat, up to A5. The legends of beer rations and daily massages are mostly folklore; the miracle is genetics, and fat that melts below body temperature.",
fr:"Des lignées japonaises fermées, sélectionnées un siècle durant jusqu’à ce que le persillage traverse le muscle comme le givre une vitre — noté sur l’échelle la plus stricte de la viande, jusqu’à A5. Les légendes de bière et de massages quotidiens relèvent surtout du folklore ; le miracle est génétique, avec un gras qui fond sous la température du corps."},
tip:{en:"Forget the steakhouse slab: cut thin, sear seconds on cast iron, salt only. A little goes far — this is meat to eat by the slice, like a great ham.",
fr:"Oubliez la pièce de steakhouse : tranchez fin, saisissez quelques secondes sur fonte, salez seulement. Il en faut peu — c’est une viande à manger à la tranche, comme un grand jambon."},
pairs:["soy-sauce","rice","black-pepper","garlic"],
svg:'<path class="f2 sf" d="M32 42q14-8 30-2 8 3 6 12-2 12-16 14-14 2-20-8-4-9 0-16z"/><path class="f1" d="M38 48q6-4 12-2M42 58q7-3 14-3M52 46q5-1 8 2" fill="none"/><path class="s" d="M38 48q6-4 12-2M42 58q7-3 14-3M52 46q5-1 8 2" stroke-width="1.4"/>'},

{id:"wild-boar",cat:"meat",name:{en:"Wild boar",fr:"Sanglier"},latin:"Sus scrofa",
origin:{en:"Eurasia",fr:"Eurasie"},season:[10,11,12,1,2],
flavor:["meaty","earthy","rich","musky"],
story:{en:"The ancestor of every domestic pig, and the animal Obelix hunts — the joke lands in France because boar really was the meat of Gaul. Its diet of acorns and roots gives the fat a nutty, forest note domestic pork lost centuries ago.",
fr:"L’ancêtre de tous les porcs domestiques, et l’animal que chasse Obélix — la plaisanterie fonctionne en France parce que le sanglier fut réellement la viande de la Gaule. Son régime de glands et de racines donne au gras une note de noisette et de forêt que le porc domestique a perdue depuis des siècles."},
tip:{en:"Marinate it overnight in red wine with juniper and bay. Young boar needs less; an old one needs two days.",
fr:"Marinez-le une nuit au vin rouge avec genièvre et laurier. Un jeune en demande moins ; un vieux en réclame deux jours."},
pairs:["juniper","red-wine-vinegar","chestnut","bay-leaf","thyme","onion","carrot","dark-chocolate"],
svg:'<path class="f1 sf" d="M28 62q4-20 22-20t18 18q-14 12-40 2z"/><path class="s" d="M30 56l-6 4 6 2"/><circle class="dot" cx="40" cy="54" r="1.6"/>'}
]);
