// The prestige shelf — premium ingredients. Additive layer; original files untouched.
// `luxe: true` marks premium (◆); `rare: true` still marks lesser-known (✦).

// A few original entries are premium too — tag them here rather than editing their files.
(window.INGREDIENTS || []).forEach(function (i) {
  if (["truffle", "saffron", "vanilla"].indexOf(i.id) !== -1) i.luxe = true;
});

window.INGREDIENTS = (window.INGREDIENTS || []).concat([

{id:"caviar",cat:"seafood",luxe:true,name:{en:"Caviar",fr:"Caviar"},latin:"Acipenser spp. (roe)",
origin:{en:"Caspian Sea, now farmed worldwide",fr:"Mer Caspienne, désormais élevé partout"},season:[],
flavor:["briny","marine","rich","buttery"],
story:{en:"Sturgeon roe cured malossol — “little salt” in Russian, the only seasoning it tolerates. In 19th-century America sturgeon were so plentiful that saloons gave caviar away free, like peanuts, to make drinkers thirsty; two centuries of appetite later, it is weighed out like jewellery.",
fr:"Des œufs d’esturgeon salés malossol — « peu de sel » en russe, le seul assaisonnement qu’il tolère. Dans l’Amérique du XIXe siècle, l’esturgeon abondait tant que les saloons offraient le caviar, comme des cacahuètes, pour donner soif ; deux siècles d’appétit plus tard, on le pèse comme un bijou."},
tip:{en:"Never metal on the roe — a mother-of-pearl or horn spoon, straight from the chilled tin. If you must dress it, only blini, potato and thick cream have earned the right.",
fr:"Jamais de métal sur le grain — cuillère de nacre ou de corne, à même la boîte glacée. S’il faut l’accompagner, seuls le blini, la pomme de terre et la crème épaisse en ont gagné le droit."},
pairs:["cream","potato","egg","chives","butter"],
svg:'<circle class="f1 sf" cx="48" cy="52" r="19"/><path class="s" d="M32 46h32" stroke-width="1.6"/><path class="dot" d="M40 54a2 2 0 104 0 2 2 0 10-4 0M47 52a2 2 0 104 0 2 2 0 10-4 0M54 55a2 2 0 104 0 2 2 0 10-4 0M43 60a2 2 0 104 0 2 2 0 10-4 0M51 61a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"lobster",cat:"seafood",luxe:true,name:{en:"Lobster",fr:"Homard"},latin:"Homarus gammarus",
origin:{en:"North Atlantic; Brittany prizes the blue",fr:"Atlantique Nord ; la Bretagne vénère le bleu"},season:[5,6,7,8,9],
flavor:["sweet","marine","rich","delicate"],
story:{en:"Colonial New England fed lobster to prisoners and servants — the story goes that some contracts capped it at three meals a week. The rails and the rich reversed its fortune entirely; Brittany’s cobalt-shelled homard bleu now outranks nearly everything else in the tank.",
fr:"La Nouvelle-Angleterre coloniale servait le homard aux prisonniers et aux domestiques — certains contrats, raconte-t-on, le limitaient à trois repas par semaine. Le chemin de fer et les riches renversèrent entièrement sa fortune ; le homard bleu breton à carapace de cobalt surclasse aujourd’hui presque tout le vivier."},
tip:{en:"Undercook rather than over — the flesh turns to eraser past its point. Roast the shells for bisque, and dare the old Senderens pairing: a whisper of vanilla in the butter.",
fr:"Sous-cuisez plutôt que trop — la chair devient gomme passé son point. Rôtissez les carcasses pour la bisque, et osez le vieux pari de Senderens : un souffle de vanille dans le beurre."},
pairs:["butter","vanilla","tarragon","lemon","corn"],
svg:'<path class="f2 sf" d="M44 36q4-4 8 0l2 20q3 10-6 14-9-4-6-14z"/><path class="f2 sf" d="M40 34q-8-6-6-14 8 0 10 10zM56 34q8-6 6-14-8 0-10 10z"/><path class="s" d="M42 48l-8 2M42 56l-8 4M54 48l8 2M54 56l8 4M46 72l-3 5M50 72l3 5"/>'},

{id:"langoustine",cat:"seafood",luxe:true,name:{en:"Langoustine",fr:"Langoustine"},latin:"Nephrops norvegicus",
origin:{en:"North-East Atlantic",fr:"Atlantique Nord-Est"},season:[4,5,6,7,8],
flavor:["sweet","delicate","marine"],
story:{en:"The most impatient of shellfish: it dies fast out of water and sulks fast on ice, which is why for centuries only port towns ever tasted it at its best. The English called them Dublin Bay prawns after the boats that landed them; chefs simply call them the finest sweetness the Atlantic makes.",
fr:"Le plus impatient des crustacés : il meurt vite hors de l’eau et boude vite sur la glace — c’est pourquoi, des siècles durant, seules les villes portuaires l’ont connu à son sommet. Les Anglais les nomment « crevettes de la baie de Dublin », d’après les bateaux qui les débarquaient ; les chefs les appellent simplement la plus fine douceur que fabrique l’Atlantique."},
tip:{en:"Seconds, not minutes: flash them in foaming butter or poach them barely, and serve while they still remember the sea. The heads make a ten-minute sauce that outclasses most week-long ones.",
fr:"Des secondes, pas des minutes : passez-les dans un beurre mousseux ou pochez-les à peine, et servez tant qu’elles se souviennent de la mer. Les têtes font en dix minutes une sauce qui surclasse bien des sauces d’une semaine."},
pairs:["butter","lemon","garlic","finger-lime","chervil"],
svg:'<path class="f1 sf" d="M46 34q3-3 6 0l1 22q2 9-4.5 12-6.5-3-4.5-12z"/><path class="s" d="M46 34q-4-8-2-14M52 34q4-8 2-14M44 44l-7 1M44 52l-7 3M54 44l7 1M54 52l7 3"/>'},

{id:"king-crab",cat:"seafood",luxe:true,name:{en:"King crab",fr:"Crabe royal"},latin:"Paralithodes camtschaticus",
origin:{en:"Bering Sea & Barents Sea",fr:"Mer de Béring & mer de Barents"},season:[1,10,11,12],
flavor:["sweet","marine","rich","briny"],
story:{en:"A giant whose legs can span nearly two metres, fished in some of the deadliest waters on Earth. Soviet scientists released it near Murmansk in the 1960s; it marched west into Norwegian fjords, where fishermen — torn between plague and windfall — still call it “Stalin’s crab”.",
fr:"Un géant dont les pattes frôlent les deux mètres d’envergure, pêché dans certaines des eaux les plus meurtrières du globe. Des scientifiques soviétiques l’ont relâché près de Mourmansk dans les années 1960 ; il a marché vers l’ouest jusqu’aux fjords norvégiens, où les pêcheurs — partagés entre fléau et aubaine — l’appellent encore « le crabe de Staline »."},
tip:{en:"The legs hold all the treasure and are nearly always sold cooked: never boil them again. Warm them gently in butter or serve them cold with lemon — anything more is vandalism.",
fr:"Tout le trésor est dans les pattes, presque toujours vendues cuites : ne les rebouillez jamais. Tiédissez-les au beurre ou servez-les froides au citron — tout le reste est du vandalisme."},
pairs:["butter","lemon","ginger","chives"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="12"/><path class="s" d="M38 44l-10-8M36 52H22M38 60l-10 8M58 44l10-8M60 52h14M58 60l10 8"/><path class="s" d="M28 36l-2-5M68 36l2-5"/>'},

{id:"turbot",cat:"seafood",luxe:true,name:{en:"Turbot",fr:"Turbot"},latin:"Scophthalmus maximus",
origin:{en:"North-East Atlantic & Mediterranean",fr:"Atlantique Nord-Est & Méditerranée"},season:[],
flavor:["delicate","marine","rich","buttery"],
story:{en:"The “king of fish” has convened parliaments: in Juvenal’s satire, a turbot too vast for any dish forced Emperor Domitian to summon the Roman Senate, which gravely advised building a pot around it. France still forges the turbotière, a diamond-shaped vessel that exists for this fish alone.",
fr:"Le « roi des poissons » a convoqué des parlements : dans la satire de Juvénal, un turbot trop vaste pour tout plat contraignit l’empereur Domitien à réunir le Sénat romain, qui conseilla gravement de bâtir une marmite autour. La France forge encore la turbotière, ustensile en losange qui n’existe que pour ce poisson."},
tip:{en:"Cook it on the bone, always — the gelatine bastes the pearl-white flesh from within. Butter and lemon complete the coronation; a morel cream is the state occasion.",
fr:"Cuisez-le sur l’arête, toujours — la gélatine arrose de l’intérieur sa chair blanc nacré. Beurre et citron achèvent le sacre ; une crème aux morilles est le dîner d’État."},
pairs:["butter","lemon","egg","morel","cream"],
svg:'<path class="f1 sf" d="M48 30q22 10 22 24T48 76Q26 66 26 54t22-24z" transform="rotate(45 48 53)"/><path class="dot" d="M42 44a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M48 40a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/><path class="s" d="M40 56q8 6 18 2" stroke-width="1.6"/>'},

{id:"dover-sole",cat:"seafood",luxe:true,name:{en:"Dover sole",fr:"Sole"},latin:"Solea solea",
origin:{en:"English Channel & North Sea",fr:"Manche & mer du Nord"},season:[],
flavor:["delicate","sweet","marine"],
story:{en:"Named for the port that rushed it to London’s tables, it earned immortality in Rouen in 1948: one sole meunière — browned butter, lemon, parsley — struck the young Julia Child as “the most exciting meal of my life” and rerouted American cooking through France.",
fr:"Nommée d’après le port qui la précipitait vers les tables de Londres, elle gagna l’immortalité à Rouen en 1948 : une sole meunière — beurre noisette, citron, persil — frappa la jeune Julia Child comme « le repas le plus exaltant de ma vie » et fit passer la cuisine américaine par la France."},
tip:{en:"Its firm, sweet flesh peels from the bone in four perfect fillets — but cook it whole and skin-on for the true meunière. The pan does the sauce: butter, lemon, and the fond it leaves behind.",
fr:"Sa chair ferme et douce se détache de l’arête en quatre filets parfaits — mais cuisez-la entière pour la vraie meunière. La poêle fait la sauce : beurre, citron, et les sucs qu’elle abandonne."},
pairs:["butter","lemon","parsley","capers"],
svg:'<path class="f1 sf" d="M30 54q6-16 24-16 14 0 12 14-2 16-20 16-14 0-16-14z" transform="rotate(-8 48 52)"/><path class="dot" d="M36 46a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/><path class="s" d="M64 50l8-4-2 8" stroke-width="1.8"/>'},

{id:"abalone",cat:"seafood",luxe:true,rare:true,name:{en:"Abalone",fr:"Ormeau"},latin:"Haliotis tuberculata",
origin:{en:"Brittany, Channel Islands & Japan",fr:"Bretagne, îles Anglo-Normandes & Japon"},season:[1,2,10,11,12],
flavor:["marine","sweet","meaty","briny"],
story:{en:"A sea snail in a mother-of-pearl ear, prised off rocks at the lowest tides. Japan’s ama — women free-divers whose craft is two thousand years old — have gathered them for emperors; in Brittany the ormeau is so coveted that its harvest is rationed to a handful of big-tide days a year.",
fr:"Un escargot de mer dans une oreille de nacre, décollé des roches aux plus grandes marées basses. Les ama du Japon — plongeuses en apnée dont l’art a deux mille ans — les cueillent depuis les empereurs ; en Bretagne, l’ormeau est si convoité que sa pêche est rationnée à quelques jours de vives-eaux par an.",},
tip:{en:"Tenderise or braise — there is no middle path: pound the escalopes and flash them in butter, or steam it hours with kombu until it slices like a wild mushroom.",
fr:"Attendrir ou braiser — pas de voie médiane : battez les escalopes et saisissez-les au beurre, ou cuisez-le des heures à la vapeur de kombu jusqu’à ce qu’il se tranche comme un champignon sauvage."},
pairs:["butter","kombu","soy-sauce","shiitake"],
svg:'<path class="f1 sf" d="M32 56q-2-18 16-20 20-2 18 14-2 18-20 18-12 0-14-12z"/><path class="s" d="M38 48q10-6 22-2M40 58q10 4 20 0" stroke-width="1.6"/><path class="dot" d="M36 44a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0M42 40a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0M49 38a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0"/>'},

{id:"percebes",cat:"seafood",luxe:true,rare:true,name:{en:"Goose barnacles",fr:"Pouces-pieds"},latin:"Pollicipes pollicipes",
origin:{en:"Costa da Morte, Galicia",fr:"Costa da Morte, Galice"},season:[],
flavor:["marine","briny","sweet"],
story:{en:"Harvested from wave-battered cliffs on Galicia’s “Coast of Death” by percebeiros roped against the swell — Europe’s most expensive seafood partly prices the danger of picking it. Medieval Europe believed barnacle geese hatched from them, which conveniently made goose acceptable dinner during Lent.",
fr:"Récoltés sur les falaises battues par la houle de la « Côte de la Mort » galicienne par des percebeiros encordés contre les vagues — le fruit de mer le plus cher d’Europe facture en partie le danger de sa cueillette. L’Europe médiévale croyait que les oies bernaches en éclosaient, ce qui rendait commodément l’oie acceptable au carême."},
tip:{en:"Thirty seconds in boiling seawater — or salted water with a bay leaf — then straight to the table under a cloth. Twist, peel, bite: it tastes of the wave that nearly took the picker.",
fr:"Trente secondes dans l’eau de mer bouillante — ou une eau salée au laurier — puis droit à table sous un linge. Tordre, peler, mordre : cela a le goût de la vague qui a failli emporter le cueilleur."},
pairs:["lemon","olive-oil","bay-leaf"],
svg:'<path class="f3 sf" d="M40 74q-4-16 2-26l6 4q-4 12-2 22zM52 72q-2-14 4-24l6 4q-5 10-4 20z"/><path class="f1 sf" d="M44 44l8 6 8-4-2-10-8-2-8 4z"/><path class="s" d="M48 40l6 4" stroke-width="1.4"/>'},

{id:"foie-gras",cat:"meat",luxe:true,name:{en:"Foie gras",fr:"Foie gras"},latin:"Anser & Anas (foie)",
origin:{en:"Egypt of the pharaohs; Alsace & the Southwest",fr:"Égypte des pharaons ; Alsace & Sud-Ouest"},season:[],
flavor:["rich","buttery","sweet","delicate"],
story:{en:"Reliefs at Saqqara show Egyptians fattening geese 4,500 years ago; Rome fed them figs and called the delicacy iecur ficatum — “fig liver” — and ficatum became foie, fegato, hígado: the very word for liver in Romance languages descends from this dish.",
fr:"Les bas-reliefs de Saqqarah montrent des Égyptiens engraissant des oies il y a 4 500 ans ; Rome les nourrissait de figues et nomma le mets iecur ficatum — « foie aux figues » — et ficatum devint foie, fegato, hígado : le mot même du foie dans les langues romanes descend de ce plat."},
tip:{en:"Terrine barely set and eaten with a spoon’s edge, or escalopes seared in a dry, screaming pan for a minute a side — the fat it releases is a sauce in itself. Sweetness beside it, never sugar on it.",
fr:"En terrine à peine prise, mangée au bord de la cuillère, ou en escalopes saisies une minute par face à la poêle sèche et brûlante — la graisse rendue est une sauce à elle seule. Du sucré à côté, jamais du sucre dessus."},
pairs:["fig","quince","honey","grape","black-pepper"],
svg:'<path class="f1 sf" d="M32 52q0-14 16-14 20 0 18 14-1 10-10 12l-6-6-4 8q-12-2-14-14z"/><path class="s" d="M40 48q6-4 14-2" stroke-width="1.6"/>'},

{id:"iberico-ham",cat:"meat",luxe:true,name:{en:"Ibérico ham",fr:"Jambon ibérique"},latin:"Sus scrofa (ibérico de bellota)",
origin:{en:"Dehesas of Spain & Portugal",fr:"Dehesas d’Espagne & du Portugal"},season:[],
flavor:["nutty","sweet","umami","rich"],
story:{en:"Each autumn the black-hoofed pigs enter the montanera, roaming holm-oak parkland and eating up to ten kilos of acorns a day — the fat turns silken and faintly of hazelnut. Cured for years and carved by professional cortadores in slices thin as stained glass, it is charcuterie’s absolute summit.",
fr:"Chaque automne, les porcs aux sabots noirs entrent en montanera, parcourant les chênaies et mangeant jusqu’à dix kilos de glands par jour — leur gras devient soyeux, vaguement noisetté. Affiné des années et découpé par des cortadores professionnels en tranches fines comme du vitrail, c’est le sommet absolu de la charcuterie."},
tip:{en:"Serve at warm room temperature so the fat turns translucent and melts on the tongue — never from the fridge, never with strong bread. The white streaks are the point.",
fr:"Servez-le à température ambiante chaude, que le gras devienne translucide et fonde sur la langue — jamais au sortir du froid, jamais avec un pain trop fort. Les veines blanches sont l’essentiel."},
pairs:["fig","almond","tomato","olive-oil"],
svg:'<path class="f2 sf" d="M28 62q2-12 16-16l16-6q10-2 12 6t-8 12l-18 6q-12 4-18-2z"/><path class="s" d="M60 40q4-6 10-6" stroke-width="1.8"/><path class="f1" d="M36 56q10-6 22-8" fill="none"/><path class="s" d="M36 56q10-6 22-8" stroke-width="1.4"/>'},

{id:"wagyu",cat:"meat",luxe:true,name:{en:"Wagyu beef",fr:"Bœuf wagyu"},latin:"Bos taurus (wagyū)",
origin:{en:"Japan",fr:"Japon"},season:[],
flavor:["rich","buttery","meaty","umami"],
story:{en:"Closed Japanese bloodlines bred for a century until the marbling threads through the muscle like frost on a window — graded to the strictest scale in meat, up to A5. The legends of beer rations and daily massages are mostly folklore; the miracle is genetics, and fat that melts below body temperature.",
fr:"Des lignées japonaises fermées, sélectionnées un siècle durant jusqu’à ce que le persillage traverse le muscle comme le givre une vitre — noté sur l’échelle la plus stricte de la viande, jusqu’à A5. Les légendes de bière et de massages quotidiens relèvent surtout du folklore ; le miracle est génétique, avec un gras qui fond sous la température du corps."},
tip:{en:"Forget the steakhouse slab: cut thin, sear seconds on cast iron, salt only. A little goes far — this is meat to eat by the slice, like a great ham.",
fr:"Oubliez la pièce de steakhouse : tranchez fin, saisissez quelques secondes sur fonte, salez seulement. Il en faut peu — c’est une viande à manger à la tranche, comme un grand jambon."},
pairs:["soy-sauce","rice","black-pepper","garlic"],
svg:'<path class="f2 sf" d="M32 42q14-8 30-2 8 3 6 12-2 12-16 14-14 2-20-8-4-9 0-16z"/><path class="f1" d="M38 48q6-4 12-2M42 58q7-3 14-3M52 46q5-1 8 2" fill="none"/><path class="s" d="M38 48q6-4 12-2M42 58q7-3 14-3M52 46q5-1 8 2" stroke-width="1.4"/>'},

{id:"bresse-chicken",cat:"meat",luxe:true,name:{en:"Bresse chicken",fr:"Poulet de Bresse"},latin:"Gallus gallus (Bresse AOP)",
origin:{en:"Bresse, France",fr:"Bresse, France"},season:[],
flavor:["meaty","delicate","rich","milky"],
story:{en:"Blue feet, white feathers, red comb — a bird in the colours of the flag, and the only poultry ever granted appellation d’origine status, in 1957. Finished on corn and milk, judged each December at the Glorieuses contests, it earned Brillat-Savarin’s verdict: the queen of poultry, the poultry of kings.",
fr:"Pattes bleues, plumage blanc, crête rouge — un oiseau aux couleurs du drapeau, et la seule volaille jamais dotée d’une appellation d’origine, en 1957. Finie au maïs et au lait, jugée chaque décembre aux concours des Glorieuses, elle a mérité le verdict de Brillat-Savarin : reine des volailles, volaille des rois."},
tip:{en:"Roast it simply and baste like a devotee — the skin and the fat are the argument. Or poach it à la crème with morels, the Bresse Sunday liturgy.",
fr:"Rôtissez-le simplement et arrosez-le avec dévotion — la peau et le gras sont l’argument. Ou pochez-le à la crème et aux morilles, liturgie dominicale bressane."},
pairs:["cream","morel","tarragon","butter"],
svg:'<path class="f1 sf" d="M36 42q-8 10-2 20t18 8q14-2 14-16 0-8-8-12-12-6-22 0z"/><path class="f1 sf" d="M60 50l10-4-4 8z"/><path class="f3 sf" d="M40 36q-2-6 3-8 3 4 1 8z"/><path class="s" d="M44 70v8M52 70v8" stroke-width="1.8"/>'},

{id:"white-truffle",cat:"mushrooms",luxe:true,name:{en:"White truffle",fr:"Truffe blanche d’Alba"},latin:"Tuber magnatum",
origin:{en:"Piedmont, Italy",fr:"Piémont, Italie"},season:[10,11,12],
flavor:["earthy","pungent","umami","rich"],
story:{en:"The black truffle submitted to orchards long ago; the white of Alba never has — every one is found wild, by dog and secret, in a few Piedmont valleys in autumn. The great specimens are auctioned at Grinzane Cavour castle to bidders on satellite link, and Rossini reportedly crowned the truffle “the Mozart of mushrooms”.",
fr:"La truffe noire s’est pliée aux vergers depuis longtemps ; la blanche d’Albe, jamais — chacune se trouve sauvage, au chien et au secret, dans quelques vallées piémontaises à l’automne. Les grands spécimens s’adjugent au château de Grinzane Cavour devant des enchérisseurs par satellite, et Rossini aurait sacré la truffe « Mozart des champignons »."},
tip:{en:"It must never see the pan: shave it raw, at the table, over hot silk — buttered pasta, risotto, a fried egg. The heat below is what unlocks it.",
fr:"Elle ne doit jamais voir la poêle : rasez-la crue, à table, sur une soie chaude — pâtes au beurre, risotto, œuf au plat. C’est la chaleur du dessous qui l’ouvre."},
pairs:["egg","rice","butter","parmesan","potato"],
svg:'<path class="f1 sf" d="M34 50q-2-13 12-16 15-3 17 10 2 11-7 16-10 5-18-2-4-4-4-8z"/><path class="s" d="M42 44l5 4-2 6M53 42l2 7-6 3" stroke-width="1.6"/>'},

{id:"matsutake",cat:"mushrooms",luxe:true,rare:true,name:{en:"Matsutake",fr:"Matsutaké"},latin:"Tricholoma matsutake",
origin:{en:"Pine forests of Japan & Korea",fr:"Pinèdes du Japon & de Corée"},season:[9,10,11],
flavor:["woody","resinous","earthy","fresh"],
story:{en:"Japan’s autumn treasure, wedded to pine roots and impossible to farm — a boxed matsutake is a gift as weighty as a great bottle of wine. It is also famously resilient: matsutake is said to have been among the first living things to push up through the scorched earth of Hiroshima in 1945.",
fr:"Le trésor d’automne du Japon, marié aux racines des pins et impossible à cultiver — un matsutaké en coffret est un cadeau aussi grave qu’une grande bouteille. Il est aussi célèbre pour sa résilience : le matsutaké aurait été parmi les premiers êtres vivants à percer la terre brûlée d’Hiroshima en 1945."},
tip:{en:"Its perfume — pine, cinnamon, autumn rain — is the whole point: never wash it, never drown it in fat. Steam it in a dobin teapot broth or grill it dry and tear it by hand.",
fr:"Son parfum — pin, cannelle, pluie d’automne — est tout l’enjeu : ne le lavez jamais, ne le noyez pas dans le gras. Cuisez-le dans un bouillon en théière dobin ou grillez-le à sec et déchirez-le à la main."},
pairs:["rice","kombu","katsuobushi","chicken"],
svg:'<path class="f2 sf" d="M32 44q4-14 16-14t16 14q0 4-4 4H36q-4 0-4-4z"/><path class="f1 sf" d="M43 48h10l-1 22q0 6-4 6t-4-6z"/><path class="s" d="M38 42h20" stroke-width="1.4"/>'},

{id:"shallot",cat:"vegetables",name:{en:"Shallot",fr:"Échalote"},latin:"Allium ascalonicum",
origin:{en:"Central Asia, via Ascalon",fr:"Asie centrale, via Ascalon"},season:[],
flavor:["pungent","sweet","delicate"],
story:{en:"Its name remembers Ascalon, the ancient port from which crusaders reportedly carried it home. The onion’s finishing-school graduate, it underwrites half of French sauce-making — béarnaise, beurre blanc, red-wine reductions, the mignonette on your oysters — while almost never being named on the menu.",
fr:"Son nom se souvient d’Ascalon, le port antique d’où les croisés l’auraient rapportée. Diplômée de l’école de maintien des oignons, elle cautionne la moitié de la saucier­­ie française — béarnaise, beurre blanc, réductions au vin, mignonette des huîtres — sans presque jamais figurer sur la carte."},
tip:{en:"Mince it fine and sweat it without colour: browned shallot turns bitter where onion turns sweet. Raw in a vinaigrette, ten minutes in the vinegar first tames it.",
fr:"Ciselez-la fin et suez-la sans coloration : brunie, l’échalote devient amère là où l’oignon devient doux. Crue en vinaigrette, dix minutes dans le vinaigre d’abord l’apprivoisent."},
pairs:["butter","tarragon","mustard","oyster","cream"],
svg:'<path class="f2 sf" d="M46 30q-14 10-12 26 2 14 14 14t14-14q2-16-12-26z" transform="rotate(8 48 50)"/><path class="s" d="M44 36q-4 10-3 22M52 36q4 10 3 22M48 32v38" stroke-width="1.8"/><path class="s" d="M48 30q0-6 4-9"/>'}

]);
