window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"angelica",cat:"herbs",name:{en:"Angelica",fr:"Angélique"},latin:"Angelica archangelica",
origin:{en:"Northern Europe",fr:"Europe du Nord"},season:[5,6,7],
flavor:["sweet","herbal","anise","musky"],
story:{en:"Niort in the Deux-Sèvres has candied its hollow green stems since the eighteenth century, and the town still runs on it. The name comes from a legend that an archangel revealed the plant as a cure during a plague year.",
fr:"Niort, dans les Deux-Sèvres, en confit les tiges creuses depuis le XVIIIe siècle, et la ville en vit encore. Le nom vient d’une légende selon laquelle un archange révéla la plante comme remède durant une année de peste."},
tip:{en:"The candied stem is the usable form for most cooks — dice it into a cake or a fruit compote where you would use citrus peel.",
fr:"La tige confite est la forme utilisable pour la plupart — taillez-la en dés dans un gâteau ou une compote, là où vous mettriez de l’écorce d’agrume."},
pairs:["rhubarb","apple","honey","cream","almond","gooseberry","sugar","juniper"],
svg:'<path class="f3 sf" d="M44 78V38h8v40z"/><path class="s" d="M48 38q-14-4-16-14 14-2 18 10M48 38q14-4 16-14-14-2-18 10"/>'},

{id:"anise-hyssop",cat:"herbs",name:{en:"Anise hyssop",fr:"Agastache (hysope anisée)"},latin:"Agastache foeniculum",
origin:{en:"Northern plains of North America",fr:"Grandes plaines d’Amérique du Nord"},season:[7,8,9],
flavor:["anise","floral","sweet"],
story:{en:"It is neither anise nor hyssop but a North American mint whose leaves happen to carry methyl chavicol, the same molecule that scents tarragon. Plains nations brewed it and used it to sweeten other infusions, so settlers first met the plant as a sugar rather than as a herb.",
fr:"Ce n’est ni de l’anis ni de l’hysope, mais une menthacée d’Amérique du Nord dont les feuilles portent le méthylchavicol, la molécule même qui parfume l’estragon. Les nations des Plaines en faisaient une infusion et s’en servaient pour adoucir les autres, si bien que les colons l’ont d’abord rencontrée comme un sucre, pas comme une herbe."},
tip:{en:"Heat destroys the aroma — infuse the leaves off the boil, covered, twenty minutes in cream or syrup, then strain. Keep the flowers raw and scatter them at the end; they hold what the leaves lose in a pan.",
fr:"La chaleur détruit le parfum : infusez les feuilles hors ébullition, à couvert, vingt minutes dans une crème ou un sirop, puis passez. Gardez les fleurs crues, jetées au dernier moment — elles retiennent ce que les feuilles perdent à la poêle."},
pairs:["strawberry","peach","apricot","cream","honey","raspberry"],
svg:'<path class="f2 sf" d="M48 17c7 0 11 7 11 15s-4 17-11 17-11-9-11-17 4-15 11-15z"/><path class="s" d="M38 24h20M37 32h22M38 40h20M40 45h16"/><path class="s" d="M48 49v30"/><path class="f1 sf" d="M48 60q-14-4-15-13 13 0 15 13zM48 70q14-4 15-13-13 0-15 13z"/>'},

{id:"basil",cat:"herbs",name:{en:"Basil",fr:"Basilic"},latin:"Ocimum basilicum",
origin:{en:"India",fr:"Inde"},season:[6,7,8,9],
flavor:["herbal","anise","peppery","fresh"],
story:{en:"Its name comes from basileus — Greek for king — and in India its cousin tulsi is holy enough to be planted in temple courtyards. A royal and sacred plant that ended up, gloriously, on tomatoes.",
fr:"Son nom vient de basileus — « roi » en grec — et en Inde son cousin le tulsi est assez sacré pour pousser dans les cours des temples. Une plante royale et sainte qui a fini, glorieusement, sur des tomates."},
tip:{en:"Heat murders it: tear the leaves by hand and add them off the flame, at the very last moment.",
fr:"La chaleur l’assassine : déchirez les feuilles à la main et ajoutez-les hors du feu, au tout dernier moment."},
pairs:["tomato","mozzarella","garlic","lemon","strawberry","pine-nut","zucchini","peach"],
svg:'<path class="s" d="M48 78V34"/><path class="f2 sf" d="M46 44q-14-2-14-14 14-2 16 10zM50 44q14-2 14-14-14-2-16 10zM46 60q-12-2-12-12 12-2 14 9zM50 60q12-2 12-12-12-2-14 9z"/><path class="f3 sf" d="M48 34q-4-8 0-12 4 4 0 12z"/>'},

{id:"bay-leaf",cat:"herbs",name:{en:"Bay leaf",fr:"Laurier"},latin:"Laurus nobilis",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["woody","herbal","warm"],
story:{en:"Daphne became a laurel tree to escape Apollo, and the god wore its leaves ever after — hence crowned poets “laureates” and every “baccalauréat”. In the pot, it works the same quiet magic: present everywhere, seen nowhere, always fished out at the end.",
fr:"Daphné se changea en laurier pour échapper à Apollon, et le dieu en porta les feuilles à jamais — d’où les poètes « lauréats » et le « baccalauréat ». Dans la marmite, même magie discrète : présent partout, visible nulle part, toujours repêché à la fin."},
tip:{en:"One leaf per pot is plenty — two is a statement, three is a mistake. Dried is often better than fresh, and it needs time to speak.",
fr:"Une feuille par marmite suffit — deux, c’est une déclaration ; trois, une erreur. Sec, il est souvent meilleur que frais, et il lui faut du temps pour parler."},
pairs:["onion","tomato","lentils","white-beans","beef","potato"],
svg:'<path class="f2 sf" d="M48 24q16 14 12 34-3 16-12 20-9-4-12-20-4-20 12-34z"/><path class="s" d="M48 30v42M48 40l-6-3M48 40l6-3M48 52l-7-3M48 52l7-3M48 64l-6-3M48 64l6-3"/>'},

{id:"borage",cat:"herbs",name:{en:"Borage",fr:"Bourrache"},latin:"Borago officinalis",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[5,6,7,8],
flavor:["fresh","marine","grassy","delicate"],
story:{en:"The leaf tastes startlingly of cucumber and oyster, which is why Ligurians stuff pansotti with it and the English drop the blue star flowers into summer drinks. Roman soldiers took it before battle, believing it gave courage.",
fr:"La feuille a un goût saisissant de concombre et d’huître, d’où les pansotti ligures qu’on en farcit et les fleurs bleues en étoile que les Anglais jettent dans les boissons d’été. Les soldats romains en prenaient avant la bataille, la croyant source de courage."},
tip:{en:"The leaves are covered in prickly hairs that soften only with cooking or fine chopping. Use the flowers raw and the leaves cooked.",
fr:"Les feuilles sont couvertes de poils piquants qui ne s’assouplissent qu’à la cuisson ou au hachage fin. Fleurs crues, feuilles cuites."},
pairs:["ricotta","cucumber","lemon","olive-oil","parmesan","egg","oyster","cream"],
svg:'<path class="s" d="M48 76V44"/><path class="f2 sf" d="M44 52q-14 0-16-8 12-6 18 4z"/><path class="f3 sf" d="M52 38l4 6 6 1-5 4 2 6-7-4-7 4 2-6-5-4 6-1z"/>'},

{id:"chervil",cat:"herbs",rare:true,name:{en:"Chervil",fr:"Cerfeuil"},latin:"Anthriscus cerefolium",
origin:{en:"Caucasus & Southern Russia",fr:"Caucase & Russie du Sud"},season:[3,4,5,6],
flavor:["delicate","anise","fresh","grassy"],
story:{en:"The most fragile of the fines herbes — the classic French quartet with parsley, chives and tarragon — whispering anise where the others speak. Old Europe ate it at Easter as a herb of renewal; today it is the connoisseur’s test of a kitchen’s finesse, since heat erases it entirely.",
fr:"La plus fragile des fines herbes — le quatuor français classique avec persil, ciboulette et estragon — murmurant l’anis là où les autres parlent. La vieille Europe en mangeait à Pâques, herbe de renouveau ; c’est aujourd’hui le test du connaisseur pour jauger la finesse d’une cuisine, car la chaleur l’efface entièrement."},
tip:{en:"Never chop it hard, never cook it: pluck the lacy leaves whole over eggs, carrots or a cream soup at the moment of serving.",
fr:"Ne le hachez jamais fort, ne le cuisez jamais : effeuillez ses pluches entières sur des œufs, des carottes ou un velouté au moment de servir."},
pairs:["egg","carrot","asparagus","cream","tarragon","chives","parsley"],
svg:'<path class="s" d="M48 78V36M40 60q8-3 8-12M56 60q-8-3-8-12"/><path class="f1 sf" d="M36 42a5 5 0 106-5 5 5 0 10-6 5zM54 37a5 5 0 106 5 5 5 0 10-6-5zM45 28a4.5 4.5 0 107 0 4.5 4.5 0 10-7 0z"/>'},

{id:"chives",cat:"herbs",name:{en:"Chives",fr:"Ciboulette"},latin:"Allium schoenoprasum",
origin:{en:"Europe & Asia",fr:"Europe & Asie"},season:[4,5,6,7,8,9],
flavor:["mild","fresh","pungent"],
story:{en:"The gentlest member of the onion clan, gathered wild in Europe since the Middle Ages, when bunches were hung against evil spells. It offers the allium idea — without the allium consequences.",
fr:"Le membre le plus doux du clan des oignons, cueilli sauvage en Europe depuis le Moyen Âge, où l’on en suspendait des bouquets contre les mauvais sorts. Elle offre l’idée de l’oignon — sans les conséquences de l’oignon."},
tip:{en:"Scissors beat the knife: snip it directly over eggs, potatoes or cream, and its purple pompom flowers are edible too.",
fr:"Les ciseaux battent le couteau : taillez-la directement sur les œufs, les pommes de terre ou la crème ; ses fleurs en pompons mauves se mangent aussi."},
pairs:["egg","potato","cream","scallop","asparagus","cod","yogurt"],
svg:'<path class="s" d="M40 78Q38 46 36 30M46 78Q46 44 46 26M52 78Q54 48 56 30M58 78Q60 52 62 38"/><path class="f3" d="M34 28a3 3 0 106 0 3 3 0 10-6 0M44 24a3 3 0 106 0 3 3 0 10-6 0M54 28a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"cilantro",cat:"herbs",name:{en:"Cilantro / Coriander",fr:"Coriandre"},latin:"Coriandrum sativum",
origin:{en:"Eastern Mediterranean",fr:"Méditerranée orientale"},season:[5,6,7,8,9],
flavor:["fresh","citrus","herbal","pungent"],
story:{en:"Coriander seeds were found in Tutankhamun’s tomb, making it one of the oldest herbs humans carry with them. A single gene decides its fate on your tongue: for most it sings of citrus, for the unlucky few it tastes of soap.",
fr:"Des graines de coriandre furent trouvées dans la tombe de Toutânkhamon — l’une des plus vieilles herbes que l’humanité emporte avec elle. Un seul gène décide de son destin sur votre langue : pour la plupart elle chante l’agrume, pour quelques malchanceux elle a un goût de savon."},
tip:{en:"Leaves and seeds are two different ingredients: the leaf is a finishing herb, the seed a warm spice. Never swap one for the other.",
fr:"Feuilles et graines sont deux ingrédients différents : la feuille se cisèle au dernier moment, la graine est une épice chaude. Ne troquez jamais l’une pour l’autre."},
pairs:["chili","coconut-milk","ginger","mango","cumin","shrimp","rice"],
svg:'<path class="s" d="M48 78V38M40 60q8-2 8-10M56 60q-8-2-8-10"/><path class="f1 sf" d="M40 40q-10 0-10-9 8-3 12 4zM56 40q10 0 10-9-8-3-12 4zM44 30q-2-8 4-10 6 2 4 10-4 3-8 0z"/>'},

{id:"curry-leaf",cat:"herbs",name:{en:"Curry leaf",fr:"Feuille de curry"},latin:"Murraya koenigii",
origin:{en:"India & Sri Lanka",fr:"Inde & Sri Lanka"},season:[],
flavor:["citrus","herbal","warm","resinous"],
story:{en:"Nothing to do with curry powder, which contains none of it. The leaf is thrown into hot oil at the very start of a South Indian dish, where it crackles and perfumes the fat — a step called tempering, and the dish is unrecognisable without it.",
fr:"Rien à voir avec le curry en poudre, qui n’en contient pas. La feuille est jetée dans l’huile chaude au tout début d’un plat sud-indien, où elle crépite et parfume le gras — une étape appelée tempérage, sans laquelle le plat est méconnaissable."},
tip:{en:"Dried curry leaves are close to worthless. Buy them fresh and freeze what you do not use — they freeze perfectly.",
fr:"Les feuilles de curry séchées ne valent presque rien. Achetez-les fraîches et congelez le reste — elles se congèlent parfaitement."},
pairs:["mustard-seed","coconut-milk","turmeric","ghee","chili","red-lentil","ginger","lime"],
svg:'<path class="s" d="M48 74V30"/><path class="f2 sf" d="M46 38q-12-4-14 2 10 8 14 2zM50 46q12-4 14 2-10 8-14 2zM46 54q-12-4-14 2 10 8 14 2zM50 62q12-4 14 2-10 8-14 2z"/>'},

{id:"dill",cat:"herbs",name:{en:"Dill",fr:"Aneth"},latin:"Anethum graveolens",
origin:{en:"Western Asia",fr:"Asie occidentale"},season:[5,6,7,8,9],
flavor:["anise","fresh","grassy"],
story:{en:"Old Norse dilla means “to soothe” — the herb once calmed babies’ colic. The North never let it go: gravlax, that Scandinavian invention of salmon “buried” in salt and dill, remains its masterpiece.",
fr:"Le vieux norrois dilla signifie « apaiser » — l’herbe calmait jadis les coliques des nourrissons. Le Nord ne l’a jamais lâchée : le gravlax, cette invention scandinave de saumon « enterré » sous sel et aneth, reste son chef-d’œuvre."},
tip:{en:"Dill hates heat and long waits: snip it over the dish at the table, especially anything with yogurt, eggs or fish.",
fr:"L’aneth déteste la chaleur et l’attente : ciselez-le sur le plat au moment de servir, surtout sur le yaourt, les œufs ou le poisson."},
pairs:["salmon","beetroot","yogurt","potato","egg","mustard"],
svg:'<path class="s" d="M48 78V40"/><path class="s" d="M48 40l-12-8M48 40l12-8M48 40v-14M48 40l-6-12M48 40l6-12"/><path class="dot" d="M34 31a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M40 27a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M46.3 24a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M52.6 27a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M58.6 31a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0"/>'},

{id:"epazote",cat:"herbs",name:{en:"Epazote",fr:"Épazote"},latin:"Dysphania ambrosioides",
origin:{en:"Mexico & Central America",fr:"Mexique & Amérique centrale"},season:[6,7,8,9],
flavor:["pungent","bitter","herbal","resinous"],
story:{en:"Mexican cooks put it in black beans for the same reason Germans put savory in theirs — it is held to reduce the gas. Its taste is genuinely divisive: descriptions run from petrol to turpentine to oregano, and all three are fair.",
fr:"Les cuisiniers mexicains la mettent dans les haricots noirs pour la même raison que les Allemands y mettent de la sarriette — on lui prête un effet anti-flatulence. Son goût divise franchement : les descriptions vont de l’essence à la térébenthine en passant par l’origan, et les trois sont justes."},
tip:{en:"One sprig for a whole pot, added in the last ten minutes. It is not an herb you scatter generously.",
fr:"Une branche pour toute une casserole, ajoutée dans les dix dernières minutes. Ce n’est pas une herbe que l’on parsème généreusement."},
pairs:["black-bean","chili","corn","onion","garlic","tomatillo","cilantro","lime"],
svg:'<path class="s" d="M48 76V32"/><path class="f1 sf" d="M46 40q-14-2-16 6 12 8 16 0zM50 54q14-2 16 6-12 8-16 0z"/>'},

{id:"hyssop",cat:"herbs",name:{en:"Hyssop",fr:"Hysope"},latin:"Hyssopus officinalis",
origin:{en:"Southern Europe",fr:"Europe du Sud"},season:[6,7,8,9],
flavor:["bitter","herbal","floral","resinous"],
story:{en:"Named in the Bible and grown in monastery gardens for a thousand years, it fell almost entirely out of cooking — too bitter, too medicinal for modern palates. It survives mainly in Chartreuse and a handful of other monastic liqueurs.",
fr:"Nommée dans la Bible et cultivée mille ans dans les jardins de monastère, elle a presque entièrement quitté la cuisine — trop amère, trop médicinale pour les palais modernes. Elle survit surtout dans la Chartreuse et quelques autres liqueurs monastiques."},
tip:{en:"Treat it like a bitter rather than an herb. A few leaves in a fruit compote or a game sauce, and no more.",
fr:"Traitez-la comme un amer plutôt que comme une herbe. Quelques feuilles dans une compote de fruits ou une sauce de gibier, pas davantage."},
pairs:["apricot","peach","honey","venison","thyme","rosemary","plum","juniper"],
svg:'<path class="s" d="M48 76V32"/><path class="f2 sf" d="M46 38q-8 0-9 5 7 5 9 0zM50 48q8 0 9 5-7 5-9 0zM46 58q-8 0-9 5 7 5 9 0z"/><circle class="f3 sf" cx="48" cy="30" r="3"/>'},

{id:"lemon-verbena",cat:"herbs",rare:true,name:{en:"Lemon verbena",fr:"Verveine citronnelle"},latin:"Aloysia citrodora",
origin:{en:"Andes of Chile & Peru",fr:"Andes du Chili & du Pérou"},season:[6,7,8,9],
flavor:["citrus","floral","fresh","delicate"],
story:{en:"Brought from the Andes in the 18th century and named for a Spanish queen, it settled into French life as the grandmother’s tisane of Provence. Pastry chefs rediscovered what the grandmothers knew: no other leaf smells this purely of lemon without a drop of acidity.",
fr:"Rapportée des Andes au XVIIIe siècle et nommée en l’honneur d’une reine d’Espagne, elle s’est installée dans la vie française comme la tisane des grands-mères de Provence. Les pâtissiers ont redécouvert ce que les grands-mères savaient : aucune autre feuille ne sent aussi purement le citron sans une goutte d’acidité."},
tip:{en:"Infuse it in warm cream or syrup off the heat, covered, ten minutes — boiling murders its perfume. Transcendent with peaches and apricots.",
fr:"Infusez-la dans une crème ou un sirop tiède, hors du feu, à couvert, dix minutes — l’ébullition assassine son parfum. Transcendante avec pêches et abricots."},
pairs:["peach","strawberry","cream","honey","raspberry"],
svg:'<path class="s" d="M48 78V30"/><path class="f1 sf" d="M46 44q-14 0-16-12 14-2 17 8zM50 44q14 0 16-12-14-2-17 8zM46 60q-12 0-14-10 12-2 15 7zM50 60q12 0 14-10-12-2-15 7z"/>'},

{id:"lemongrass",cat:"herbs",rare:true,name:{en:"Lemongrass",fr:"Citronnelle"},latin:"Cymbopogon citratus",
origin:{en:"Maritime Southeast Asia",fr:"Asie du Sud-Est insulaire"},season:[],
flavor:["citrus","fresh","floral","grassy"],
story:{en:"A grass that decided to be a citrus: its stalks carry citral, the same aromatic soul as lemon zest, without any of the acid. It is the upright backbone of Thai tom yum and Vietnamese broths — always present, always fished out, never chewed.",
fr:"Une herbe qui a décidé d’être un agrume : ses tiges portent le citral, l’âme aromatique du zeste de citron, sans rien de son acidité. C’est la colonne vertébrale du tom yum thaï et des bouillons vietnamiens — toujours présente, toujours repêchée, jamais mâchée."},
tip:{en:"Use only the pale lower third; bruise it flat with the knife’s spine to crack the perfume open before it goes in the pot.",
fr:"N’utilisez que le tiers inférieur, pâle ; écrasez-le du dos du couteau pour fendre le parfum avant la marmite."},
pairs:["coconut-milk","ginger","chili","shrimp","chicken","cilantro"],
svg:'<path class="f1 sf" d="M44 76V40q0-8 4-14 4 6 4 14v36z"/><path class="s" d="M44 48q-6-2-8-8M52 48q6-2 8-8M44 60q-6-2-9-7M52 60q6-2 9-7" stroke-width="1.8"/>'},

{id:"lovage",cat:"herbs",rare:true,name:{en:"Lovage",fr:"Livèche"},latin:"Levisticum officinale",
origin:{en:"Mediterranean & Persia",fr:"Méditerranée & Perse"},season:[5,6,7,8,9],
flavor:["herbal","pungent","fresh","warm"],
story:{en:"Charlemagne ordered it grown in every imperial garden, and German kitchens still call it Maggikraut — the Maggi herb — because it tastes uncannily of the famous seasoning, though the sauce never contained it. Celery’s louder, wilder great-uncle, one leaf deep.",
fr:"Charlemagne ordonna sa culture dans tous les jardins impériaux, et les cuisines allemandes l’appellent encore Maggikraut — l’herbe Maggi — car son goût rappelle étrangement le célèbre arôme, qui n’en a pourtant jamais contenu. Le grand-oncle du céleri, plus sonore et plus sauvage, à une feuille de profondeur."},
tip:{en:"Ferociously potent: one leaf perfumes a whole pot of broth or a potato salad. Its hollow stems make edible straws for a tomato juice.",
fr:"Férocement puissante : une feuille parfume toute une marmite de bouillon ou une salade de pommes de terre. Ses tiges creuses font des pailles comestibles pour un jus de tomate."},
pairs:["potato","chicken","tomato","cream","lentils"],
svg:'<path class="s" d="M48 78V34M48 60q-10-2-12-10M48 60q10-2 12-10"/><path class="f2 sf" d="M32 50q-2-8 6-10 4 6-1 11zM64 50q2-8-6-10-4 6 1 11zM44 34q-2-8 4-10 6 2 4 10-4 3-8 0z"/>'},

{id:"kaffir-lime-leaf",cat:"herbs",name:{en:"Makrut lime leaf",fr:"Feuille de combava"},latin:"Citrus hystrix",
origin:{en:"Southeast Asia",fr:"Asie du Sud-Est"},season:[],
flavor:["citrus","floral","fresh","resinous"],
story:{en:"The leaf grows in a distinctive double lobe, one leaf apparently joined to another end to end. It carries far more perfume than the fruit, which is knobbly, dry and yields almost no juice — here the tree's value is entirely in the foliage.",
fr:"La feuille pousse en double lobe caractéristique, comme deux feuilles jointes bout à bout. Elle porte bien plus de parfum que le fruit, bosselé, sec et presque sans jus — ici toute la valeur de l’arbre est dans le feuillage."},
tip:{en:"Tear the leaf along the central rib before it goes in. Whole and intact it releases almost nothing.",
fr:"Déchirez la feuille le long de la nervure centrale avant de l’ajouter. Entière et intacte elle ne libère presque rien."},
pairs:["lemongrass","coconut-milk","galangal","chili","fish-sauce","lime","cilantro","ginger"],
svg:'<path class="f2 sf" d="M48 30q10 8 10 18t-10 10-10-10 10-18z"/><path class="f2 sf" d="M48 58q9 7 9 16t-9 8-9-8 9-16z"/><path class="s" d="M48 30v52"/>'},

{id:"marjoram",cat:"herbs",name:{en:"Marjoram",fr:"Marjolaine"},latin:"Origanum majorana",
origin:{en:"Cyprus & southern Turkey",fr:"Chypre & sud de la Turquie"},season:[6,7,8,9],
flavor:["herbal","floral","sweet","warm"],
story:{en:"Oregano's gentler sister — the same genus, but sweeter and more floral where oregano is peppery and blunt. Greeks planted it on graves for a peaceful sleep, and the Romans made wedding crowns from it.",
fr:"La sœur plus douce de l’origan — même genre, mais plus sucrée et plus florale là où l’origan est poivré et franc. Les Grecs en plantaient sur les tombes pour un sommeil paisible, et les Romains en faisaient des couronnes de mariage."},
tip:{en:"Add it at the end, never at the start. Unlike oregano it is fragile and long cooking flattens it completely.",
fr:"Ajoutez-la à la fin, jamais au début. Contrairement à l’origan elle est fragile et une cuisson longue l’efface entièrement."},
pairs:["tomato","olive-oil","lamb","garlic","mozzarella","zucchini","lemon","thyme"],
svg:'<path class="s" d="M48 76V34"/><circle class="f2 sf" cx="41" cy="44" r="4"/><circle class="f2 sf" cx="55" cy="48" r="4"/><circle class="f2 sf" cx="42" cy="58" r="4"/><circle class="f2 sf" cx="55" cy="62" r="4"/>'},

{id:"mint",cat:"herbs",name:{en:"Mint",fr:"Menthe"},latin:"Mentha spicata",
origin:{en:"Mediterranean & Near East",fr:"Méditerranée & Proche-Orient"},season:[5,6,7,8,9],
flavor:["fresh","sweet","herbal"],
story:{en:"Minthe was a nymph whom jealous Persephone crushed underfoot; Hades could only give her a scent that rises whenever she is stepped on. From Marrakech tea to Vietnamese tables, no herb refreshes more of the planet.",
fr:"Minthé était une nymphe que Perséphone, jalouse, écrasa sous son pied ; Hadès ne put que lui offrir un parfum qui s’élève chaque fois qu’on la foule. Du thé de Marrakech aux tables vietnamiennes, aucune herbe ne rafraîchit davantage la planète."},
tip:{en:"It spreads like gossip in a garden — grow it in a pot. Bruise the leaves, don’t chop them, for drinks.",
fr:"Au jardin, elle s’étend comme une rumeur — cultivez-la en pot. Pour les boissons, froissez les feuilles au lieu de les ciseler."},
pairs:["strawberry","yogurt","lamb","dark-chocolate","zucchini","mango","pomegranate"],
svg:'<path class="s" d="M48 78V30"/><path class="f2 sf" d="M46 40q-12 2-14-10 12-4 15 6zM50 40q12 2 14-10-12-4-15 6zM46 56q-10 2-12-8 10-4 13 5zM50 56q10 2 12-8-10-4-13 5z"/><path class="s" d="M34 32l-2-3M62 32l2-3"/>'},

{id:"oregano",cat:"herbs",name:{en:"Oregano",fr:"Origan"},latin:"Origanum vulgare",
origin:{en:"Mediterranean mountains",fr:"Montagnes méditerranéennes"},season:[6,7,8,9],
flavor:["herbal","peppery","warm"],
story:{en:"Greek for “joy of the mountain”, it perfumed hillsides long before pizza existed. American soldiers came home from Italy in 1945 asking for “the pizza herb” — and oregano sales rose five-thousand percent in a decade.",
fr:"« Joie de la montagne » en grec, il parfumait les collines bien avant l’existence de la pizza. Les soldats américains revinrent d’Italie en 1945 en réclamant « l’herbe à pizza » — et les ventes d’origan bondirent de cinq mille pour cent en une décennie."},
tip:{en:"One of the rare herbs that is stronger dried than fresh. Bloom it in warm oil to release its perfume before it touches the dish.",
fr:"L’une des rares herbes plus puissante sèche que fraîche. Réveillez-le dans une huile tiède pour libérer son parfum avant qu’il ne touche le plat."},
pairs:["tomato","olive-oil","lemon","chicken","eggplant","olive","mozzarella"],
svg:'<path class="s" d="M48 78V30M40 62q8-2 8-10M56 62q-8-2-8-10M42 44q6-2 6-8M54 44q-6-2-6-8"/><path class="f2" d="M36 60a3 3 0 106 0 3 3 0 10-6 0M54 60a3 3 0 106 0 3 3 0 10-6 0M38 42a3 3 0 106 0 3 3 0 10-6 0M52 42a3 3 0 106 0 3 3 0 10-6 0M45 28a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"parsley",cat:"herbs",name:{en:"Parsley",fr:"Persil"},latin:"Petroselinum crispum",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[3,4,5,6,7,8,9,10],
flavor:["grassy","fresh","peppery"],
story:{en:"Greeks planted parsley on graves and crowned victors with it at the Nemean games — an herb of both mourning and triumph. French cooking made it a daily workhorse: half the savoury dishes of the repertoire end in a flurry of chopped parsley.",
fr:"Les Grecs plantaient le persil sur les tombes et en couronnaient les vainqueurs aux jeux de Némée — herbe de deuil et de triomphe à la fois. La cuisine française en fit un ouvrier du quotidien : la moitié du répertoire salé se termine sous une pluie de persil haché."},
tip:{en:"Flat-leaf for flavour, curly for looks. The stems carry more taste than the leaves — tie them into every stock.",
fr:"Le plat pour le goût, le frisé pour l’œil. Les tiges ont plus de goût que les feuilles — glissez-les dans tous les bouillons."},
pairs:["garlic","lemon","mushroom","cod","chickpeas","egg","potato"],
svg:'<path class="s" d="M48 78V40M38 62q10-4 10-14M58 62q-10-4-10-14"/><path class="f2 sf" d="M34 44a7 7 0 108-6 7 7 0 10-8 6zM54 38a7 7 0 108 6 7 7 0 10-8-6zM43 30a6 6 0 1010 0 6 6 0 10-10 0z"/>'},

{id:"purple-basil",cat:"herbs",name:{en:"Purple basil",fr:"Basilic pourpre"},latin:"Ocimum basilicum var. purpurascens",
origin:{en:"India & Southeast Asia",fr:"Inde & Asie du Sud-Est"},season:[6,7,8,9],
flavor:["anise","herbal","warm","floral"],
story:{en:"More clove and anise than green basil, and considerably tougher-leaved. Its anthocyanins bleed pink into vinegar within minutes, which is why it is grown as much for infusing as for the leaf itself.",
fr:"Plus giroflé et anisé que le basilic vert, et à la feuille nettement plus coriace. Ses anthocyanes rosissent le vinaigre en quelques minutes, d’où une culture autant pour l’infusion que pour la feuille elle-même."},
tip:{en:"It does not make good pesto — the colour turns muddy brown. Use it whole in salads or steep it in vinegar.",
fr:"Il ne fait pas un bon pesto — la couleur vire au brun boueux. Employez-le entier en salade ou faites-le infuser dans du vinaigre."},
pairs:["tomato","white-wine-vinegar","olive-oil","peach","mozzarella","garlic","strawberry","lemon"],
svg:'<path class="s" d="M48 76V38"/><path class="f1 sf" d="M46 44q-14-6-16 2 12 10 16 2zM50 56q14-6 16 2-12 10-16 2z"/>'},

{id:"rosemary",cat:"herbs",name:{en:"Rosemary",fr:"Romarin"},latin:"Salvia rosmarinus",
origin:{en:"Mediterranean scrubland",fr:"Garrigue méditerranéenne"},season:[],
flavor:["woody","herbal","peppery"],
story:{en:"Its name means “dew of the sea”, for the coastal cliffs it clings to. Greek students wore rosemary crowns while studying, believing it strengthened memory — Ophelia agreed: “rosemary, that’s for remembrance.”",
fr:"Son nom signifie « rosée de mer », pour les falaises côtières où il s’accroche. Les étudiants grecs portaient des couronnes de romarin en étudiant, persuadés qu’il fortifiait la mémoire — Ophélie confirme : « le romarin, c’est pour le souvenir »."},
tip:{en:"Its needles survive long cooking where soft herbs die — throw a sprig under roasting potatoes or lamb and remove it before serving.",
fr:"Ses aiguilles survivent aux longues cuissons où les herbes tendres meurent — glissez une branche sous des pommes de terre ou un agneau au four, retirez-la avant de servir."},
pairs:["lamb","potato","garlic","chicken","olive-oil","honey","lemon"],
svg:'<path class="s" d="M48 78V26"/><path class="s" d="M48 68l-10-6M48 68l10-6M48 58l-11-6M48 58l11-6M48 48l-10-6M48 48l10-6M48 38l-8-5M48 38l8-5"/>'},

{id:"sage",cat:"herbs",name:{en:"Sage",fr:"Sauge"},latin:"Salvia officinalis",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["herbal","peppery","earthy"],
story:{en:"Salvia comes from salvare, “to save” — the medieval school of Salerno asked: “Why should a man die who has sage in his garden?” In the kitchen it saved something humbler: pork, butter and beans from blandness.",
fr:"Salvia vient de salvare, « sauver » — l’école de Salerne demandait au Moyen Âge : « Pourquoi mourrait-il, celui qui a de la sauge au jardin ? » En cuisine, elle sauva plus modestement le porc, le beurre et les haricots de la fadeur."},
tip:{en:"Fry whole leaves in butter until crisp: the butter turns nutty and the leaves become savoury chips.",
fr:"Faites frire les feuilles entières au beurre jusqu’à croustiller : le beurre prend un goût de noisette et les feuilles deviennent des chips salées."},
pairs:["pork","butter","onion","apple","white-beans","chestnut"],
svg:'<path class="s" d="M48 78V32"/><path class="f2 sf" d="M46 50q-14 4-18-8 12-8 19 3zM50 50q14 4 18-8-12-8-19 3zM46 34q-10 0-12-8 10-4 13 3z"/>'},

{id:"savory",cat:"herbs",name:{en:"Savory",fr:"Sarriette"},latin:"Satureja hortensis",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[6,7,8,9],
flavor:["peppery","herbal","warm","resinous"],
story:{en:"Germany calls it Bohnenkraut, the bean herb, because it does two things at once: it tastes right with beans and it genuinely helps digest them. Provence puts it on goat's cheese, where it is called pèbre d'ail, garlic pepper.",
fr:"L’Allemagne l’appelle Bohnenkraut, l’herbe aux haricots, parce qu’elle fait deux choses à la fois : elle va avec les haricots et aide réellement à les digérer. La Provence la met sur le chèvre, où on la nomme pèbre d’ail, poivre d’ail."},
tip:{en:"Put a sprig in the water with any dried bean or lentil. It is the oldest trick in European bean cookery and it works.",
fr:"Mettez une branche dans l’eau de tout haricot ou lentille sec. C’est la plus vieille astuce de la cuisine européenne des légumineuses, et elle fonctionne."},
pairs:["white-beans","goat-cheese","fava-bean","lamb","olive-oil","thyme","green-bean","garlic"],
svg:'<path class="s" d="M48 76V32"/><path class="f2 sf" d="M46 40q-10-2-12 4 8 6 12 0zM50 50q10-2 12 4-8 6-12 0zM46 60q-10-2-12 4 8 6 12 0z"/>'},

{id:"shiso",cat:"herbs",rare:true,name:{en:"Shiso",fr:"Shiso"},latin:"Perilla frutescens",
origin:{en:"China & Japan",fr:"Chine & Japon"},season:[6,7,8,9],
flavor:["herbal","fresh","anise","citrus"],
story:{en:"The jagged leaf beside your sashimi is not decoration but a thousand-year-old palate cleanser — mint’s enigmatic Japanese cousin, tasting of cumin, basil and citrus at once. Its red variety dyes umeboshi plums their warning shade of crimson.",
fr:"La feuille dentelée près de vos sashimis n’est pas un décor mais un rince-palais millénaire — cousine japonaise et énigmatique de la menthe, au goût de cumin, de basilic et d’agrume à la fois. Sa variété rouge teint les prunes umeboshi de leur cramoisi d’avertissement."},
tip:{en:"Roll several leaves and slice them into needles at the last second — bruising blackens them. Magnificent scattered over rice, tuna or strawberries.",
fr:"Roulez plusieurs feuilles et taillez-les en aiguilles à la dernière seconde — meurtries, elles noircissent. Magnifique sur un riz, un thon ou des fraises."},
pairs:["tuna","rice","umeboshi","salmon","ginger"],
svg:'<path class="f2 sf" d="M48 26q18 8 14 28-3 16-14 20-11-4-14-20-4-20 14-28z"/><path class="s" d="M48 32v36M48 42l-8-4M48 42l8-4M48 54l-9-4M48 54l9-4M36 36l-3-2M60 36l3-2M34 48l-3-1M62 48l3-1" stroke-width="1.8"/>'},

{id:"sorrel",cat:"herbs",rare:true,name:{en:"Sorrel",fr:"Oseille"},latin:"Rumex acetosa",
origin:{en:"Europe & Western Asia",fr:"Europe & Asie occidentale"},season:[4,5,6,7,8,9],
flavor:["sour","grassy","fresh"],
story:{en:"A leaf that tastes of green lemon, beloved of peasant soups for centuries — then, in 1973, the Troisgros brothers laid a barely-cooked salmon escalope on sorrel cream and produced the signature dish of nouvelle cuisine. One acid leaf rewrote French fish cookery.",
fr:"Une feuille au goût de citron vert, pilier des soupes paysannes pendant des siècles — puis, en 1973, les frères Troisgros posèrent une escalope de saumon à peine cuite sur une crème d’oseille et signèrent le plat emblème de la nouvelle cuisine. Une feuille acide a réécrit la cuisine française du poisson."},
tip:{en:"It melts to khaki in seconds of heat — that’s normal. Add half in the pan for flavour, the rest raw at the end for colour and bite.",
fr:"Elle fond et vire au kaki en quelques secondes de feu — c’est normal. Mettez-en la moitié à la poêle pour le goût, le reste cru à la fin pour la couleur et le mordant."},
pairs:["salmon","egg","cream","potato","lentils","butter"],
svg:'<path class="f1 sf" d="M48 28q14 10 10 30-2 12-10 16-8-4-10-16-4-20 10-30z"/><path class="s" d="M48 34v38M43 74l5 4 5-4" stroke-width="1.8"/>'},

{id:"tarragon",cat:"herbs",name:{en:"Tarragon",fr:"Estragon"},latin:"Artemisia dracunculus",
origin:{en:"Central Asia & Siberia",fr:"Asie centrale & Sibérie"},season:[5,6,7,8,9],
flavor:["anise","herbal","delicate"],
story:{en:"Its name means “little dragon” — medieval healers claimed it cured serpent bites, and its roots do coil like one. France adopted the orphan of the steppes and built béarnaise sauce around its quiet anise breath.",
fr:"Son nom signifie « petit dragon » — les guérisseurs médiévaux le disaient efficace contre les morsures de serpent, et ses racines s’enroulent comme tel. La France adopta cet orphelin des steppes et bâtit la béarnaise autour de son discret souffle anisé."},
tip:{en:"It overwhelms fast: a few leaves perfume a whole chicken. With eggs and mustard, it is the most French of accents.",
fr:"Il domine vite : quelques feuilles parfument un poulet entier. Avec des œufs et de la moutarde, c’est le plus français des accents."},
pairs:["chicken","egg","mustard","mushroom","cream","lemon"],
svg:'<path class="s" d="M48 78V28"/><path class="f1 sf" d="M48 66q-14-2-16-10 12-2 16 6zM48 66q14-2 16-10-12-2-16 6zM48 50q-12-2-14-9 11-2 14 5zM48 50q12-2 14-9-11-2-14 5zM48 36q-9-2-10-8 9-1 10 5zM48 36q9-2 10-8-9-1-10 5z"/>'},

{id:"thyme",cat:"herbs",name:{en:"Thyme",fr:"Thym"},latin:"Thymus vulgaris",
origin:{en:"Mediterranean hills",fr:"Collines méditerranéennes"},season:[],
flavor:["herbal","woody","warm"],
story:{en:"Medieval ladies embroidered a bee hovering over thyme on the scarves of their knights — the herb meant courage. Egyptians used it for embalming; cooks use it for nearly everything that simmers.",
fr:"Les dames du Moyen Âge brodaient une abeille survolant un brin de thym sur l’écharpe de leur chevalier — l’herbe signifiait le courage. Les Égyptiens l’utilisaient pour embaumer ; les cuisiniers, pour presque tout ce qui mijote."},
tip:{en:"Strip the leaves by sliding your fingers down the stem against the grain. Whole sprigs can simmer and be fished out like bay leaves.",
fr:"Effeuillez-le en glissant les doigts à rebrousse-tige. Les branches entières peuvent mijoter puis se repêcher comme le laurier."},
pairs:["onion","chicken","mushroom","carrot","honey","lemon","white-beans","duck"],
svg:'<path class="s" d="M48 78Q44 50 48 26"/><path class="f2" d="M44 64a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M50 56a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M41 50a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M49 42a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M43 36a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M46 28a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0"/>'},

{id:"wild-garlic",cat:"herbs",rare:true,name:{en:"Wild garlic",fr:"Ail des ours"},latin:"Allium ursinum",
origin:{en:"European woodlands",fr:"Forêts d’Europe"},season:[3,4,5],
flavor:["pungent","grassy","fresh"],
story:{en:"“Bear’s garlic” in half of Europe’s languages: legend says bears eat it first thing after hibernation to wake their blood. For a few weeks each spring, whole forests smell of garlic, and foragers fill baskets with the leaves — the kitchen’s brief, green thunderclap.",
fr:"« Ail des ours » dans la moitié des langues d’Europe : la légende veut que les ours en mangent au sortir de l’hibernation pour réveiller leur sang. Quelques semaines chaque printemps, des forêts entières sentent l’ail, et les cueilleurs remplissent des paniers de feuilles — le bref coup de tonnerre vert de la cuisine."},
tip:{en:"Beware its deadly lookalike, lily of the valley: crush a leaf — no garlic smell, no picking. Blitzed with pine nuts and parmesan it makes spring’s definitive pesto.",
fr:"Gare à son sosie mortel, le muguet : froissez une feuille — pas d’odeur d’ail, pas de cueillette. Mixé avec pignons et parmesan, il fait le pesto définitif du printemps."},
pairs:["potato","butter","egg","pine-nut","parmesan","salmon"],
svg:'<path class="f1 sf" d="M40 30q8 14 4 46-8-10-8-28 0-12 4-18z"/><path class="f1 sf" d="M56 30q-8 14-4 46 8-10 8-28 0-12-4-18z"/><path class="dot" d="M46 26a2 2 0 104 0 2 2 0 10-4 0"/>'}
]);
