window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"absinthe",cat:"cellar",name:{en:"Absinthe",fr:"Absinthe"},latin:"Artemisia absinthium",
origin:{en:"Val-de-Travers, Switzerland & Pontarlier",fr:"Val-de-Travers, Suisse, et Pontarlier"},season:[],
flavor:["bitter","anise","herbal","pungent"],
story:{en:"France banned it in 1915 and the name did not return to a French label until 2011; wormwood took the blame, though the modern reading is that alcohol at seventy percent was doing most of the damage. The milky clouding when water hits it is anise oil coming out of solution, which is exactly what happens the moment it meets a hot pan.",
fr:"La France l’a interdite en 1915 et le nom n’est revenu sur une étiquette française qu’en 2011 ; on a accusé l’absinthe, alors qu’on lit aujourd’hui qu’un alcool à soixante-dix degrés faisait l’essentiel des dégâts. Le trouble laiteux à l’arrivée de l’eau, c’est l’huile d’anis qui sort de solution - exactement ce qui se produit dès qu’elle touche une poêle chaude."},
tip:{en:"A teaspoon is a full dose in a shellfish sauce: the wormwood bitterness builds as the sauce reduces while the anise evaporates, so add it at the end and taste. Over opened oysters, one drop each and nothing more.",
fr:"Une cuillère à café fait une dose entière dans une sauce de coquillages : l’amertume de l’absinthe monte à la réduction quand l’anis s’évapore, alors ajoutez-la à la fin et goûtez. Sur des huîtres ouvertes, une goutte par huître et rien de plus."},
pairs:["oyster","scallop","fennel","cream","lobster","mussel","butter","shallot"],
svg:'<path class="f1 sf" d="M34 34h28l-4 26q-1 6-10 6t-10-6z"/><path class="f2" d="M39 52h18l-2 8q-1 4-7 4t-7-4z"/><path class="s" d="M48 66v12M38 80h20"/><path class="s" d="M28 30h40"/><path class="f3 sf" d="M42 22h12v8H42z"/>'},

{id:"amontillado",cat:"cellar",name:{en:"Amontillado",fr:"Amontillado"},latin:"Vitis vinifera 'Palomino'",
origin:{en:"Jerez, Andalusia",fr:"Jerez, Andalousie"},season:[],
flavor:["nutty","woody","rich"],
story:{en:"The name means in the manner of Montilla, the neighbouring region whose wines aged without a flor veil. An amontillado begins as a fino, then the veil is killed — by a further dose of spirit, or simply by starving it — and the wine spends years exposed to air, so it carries the yeast notes of its first life and hazelnut oxidation from its second.",
fr:"Le nom veut dire « à la manière de Montilla », la région voisine dont les vins vieillissaient sans voile de flor. Un amontillado commence en fino, puis on tue le voile — par une dose d’alcool supplémentaire ou en le laissant simplement mourir de faim — et le vin passe des années à l’air : il porte donc les notes levuriennes de sa première vie et l’oxydation à la noisette de la seconde."},
tip:{en:"It is dry, however deep it smells; taste before you sweeten anything it goes into. A spoonful in a finished consommé, or in a sauce built on jamón bones, does more than a whole glass boiled in from the start.",
fr:"Il est sec, si profond que soit son nez : goûtez avant de sucrer quoi que ce soit qui l’accompagne. Une cuillerée dans un consommé terminé, ou dans une sauce montée sur des os de jambon, fait plus qu’un verre entier bouilli dès le départ."},
pairs:["jamon-serrano","porc-iberique-bellota","mushroom","almond","onion","chicken"],
svg:'<ellipse class="f1 sf" cx="34" cy="62" rx="14" ry="12"/><ellipse class="f1 sf" cx="62" cy="62" rx="14" ry="12"/><ellipse class="f2 sf" cx="48" cy="36" rx="14" ry="12"/><path class="s" d="M34 50v24M62 50v24M48 24v24"/><circle class="dot" cx="48" cy="36" r="3"/>'},

{id:"armagnac",cat:"cellar",luxe:true,name:{en:"Armagnac",fr:"Armagnac"},latin:"Vitis vinifera 'Baco'",
origin:{en:"Gascony, southwest France",fr:"Gascogne, Sud-Ouest de la France"},season:[],
flavor:["fruity","woody","warm","rich"],
story:{en:"Baco 22A is a hybrid, crossed at the end of the nineteenth century in the wake of phylloxera, and Armagnac is the one French appellation still allowed to keep a hybrid in the vineyard. A single low-strength run through the alambic armagnacais leaves in the heavy aromatics that a second distillation would strip, which is why it reads as prune and violet where Cognac reads as flowers.",
fr:"Le baco 22A est un hybride, croisé à la fin du XIXe siècle dans le sillage du phylloxéra, et l’armagnac est la seule appellation française à garder encore un hybride dans ses vignes. Le passage unique et à faible degré dans l’alambic armagnacais laisse les composés lourds qu’une seconde distillation emporterait : d’où le pruneau et la violette là où le cognac donne des fleurs."},
tip:{en:"Those extra congeners survive heat, so it holds where Cognac vanishes: a spoonful worked into the forcemeat of a duck or pork terrine before it goes into the mould, or poured over prunes left to swell overnight. Do not flambe the old bottles - the wood is what you paid for, and the flame takes it first.",
fr:"Ces composés lourds tiennent la chaleur là où le cognac disparaît : une cuillerée travaillée dans la farce d’une terrine de canard ou de porc avant le moulage, ou versée sur des pruneaux à gonfler toute une nuit. Ne flambez pas les vieilles bouteilles - c’est le bois que vous avez payé, et la flamme l’emporte en premier."},
pairs:["prune","foie-gras","duck","magret","walnut","dark-chocolate","pork","pear"],
svg:'<path class="f2 sf" d="M22 48q0-16 15-16t15 16v18q0 8-8 8H30q-8 0-8-8z"/><path class="s" d="M22 62h30M37 32V22"/><path class="s" d="M37 22h22q9 0 9 11v13"/><path class="f1 sf" d="M60 46h16v10q0 10-8 10t-8-10z"/>'},

{id:"banyuls-wine",cat:"cellar",name:{en:"Banyuls",fr:"Banyuls"},latin:"Vitis vinifera 'Grenache noir'",
origin:{en:"Banyuls, Roussillon",fr:"Banyuls, Roussillon"},season:[],
flavor:["sweet","nutty","rich"],
story:{en:"Mutage — killing the ferment with spirit while the sugar is still the grape's own — is credited to Arnaud de Villeneuve, physician at Montpellier around 1285, and it underlies every vin doux naturel. At Banyuls the wine then spends years in glass bonbonnes left out in the sun and in old foudres, deliberately oxidising into the walnut-and-cocoa note the trade calls rancio.",
fr:"Le mutage — arrêter la fermentation à l’alcool pendant que le sucre est encore celui du raisin — est attribué à Arnaud de Villeneuve, médecin à Montpellier vers 1285, et fonde tous les vins doux naturels. À Banyuls, le vin passe ensuite des années en bonbonnes de verre laissées au soleil et en vieux foudres, oxydé volontairement jusqu’à la noix et au cacao que le métier appelle rancio."},
tip:{en:"Reduce it with a duck fond and a strip of orange peel, and stop while it still coats a spoon — pushed further the sugar catches and turns acrid. It is the one wine that will stand up to both Roquefort and dark chocolate.",
fr:"Réduisez-le avec un fond de canard et un zeste d’orange, et arrêtez tant qu’il nappe la cuillère : plus loin, le sucre accroche et tourne à l’âcre. C’est le seul vin qui tienne à la fois devant le roquefort et le chocolat noir."},
pairs:["duck","dark-chocolate","roquefort","walnut","orange","fig"],
svg:'<circle class="f1 sf" cx="44" cy="58" r="21"/><path class="f3 sf" d="M38 39h12v-10H38z"/><path class="s" d="M25 56q19 9 38 0"/><circle class="s" cx="72" cy="24" r="7"/>'},

{id:"brandy-de-jerez",cat:"cellar",name:{en:"Brandy de Jerez",fr:"Brandy de Jerez"},latin:"Vitis vinifera 'Airén'",
origin:{en:"Jerez, Andalusia",fr:"Jerez, Andalousie"},season:[],
flavor:["sweet","woody","nutty","rich"],
story:{en:"The wine is Airen from La Mancha, but the spirit only becomes Brandy de Jerez by ageing inside the sherry triangle, in butts that already held oloroso or Pedro Ximenez: here the appellation is the cask, not the vineyard. It moves down through criaderas and a solera exactly as the sherry does, so no bottle is ever of one single year.",
fr:"Le vin est de l’airén de la Manche, mais l’eau-de-vie ne devient brandy de Jerez qu’en vieillissant dans le triangle du xérès, en fûts ayant déjà porté l’oloroso ou le pedro ximénez : ici, l’appellation tient au bois et non à la vigne. Il descend les criaderas et la solera exactement comme le xérès, si bien qu’aucune bouteille n’est jamais d’une seule année."},
tip:{en:"It arrives already carrying raisin and oxidised sweetness, so cut the sugar elsewhere - a sauce for kidneys or pork needs no added Pedro Ximenez on top of it. Deglaze and reduce it hard; a light splash leaves the dish tasting of the bottle rather than of the pan.",
fr:"Il arrive déjà chargé de raisin sec et de sucre oxydé : réduisez le sucre ailleurs - une sauce pour des rognons ou du porc n’a pas besoin qu’on y ajoute du pedro ximénez par-dessus. Déglacez et réduisez fort ; un simple filet laisse le goût de la bouteille plutôt que celui de la poêle."},
pairs:["pork","oloroso","raisin","almond","jamon-serrano","rognons","dark-chocolate","orange"],
svg:'<path class="f2 sf" d="M22 54q12-4 24 0 4 9 0 18-12 4-24 0-4-9 0-18z"/><path class="f2 sf" d="M50 54q12-4 24 0 4 9 0 18-12 4-24 0-4-9 0-18z"/><path class="f1 sf" d="M36 28q12-4 24 0 4 9 0 18-12 4-24 0-4-9 0-18z"/><path class="s" d="M28 55v16M40 55v16M56 55v16M68 55v16M42 29v16M54 29v16"/>'},

{id:"calvados",cat:"cellar",name:{en:"Calvados",fr:"Calvados"},latin:"Malus domestica",
origin:{en:"Normandy",fr:"Normandie"},season:[],
flavor:["fruity","warm","woody"],
story:{en:"Calvados Domfrontais must be at least thirty percent pear, which is why it smells of orchard rather than of apple alone, and the Pays d'Auge is distilled twice in a pot still where the rest of Normandy runs once through a column. The cider apples behind it are bitter, tannic varieties no one would eat out of hand - they were bred for tannin, not for the fruit bowl.",
fr:"Le calvados Domfrontais doit compter au moins trente pour cent de poires, d’où ce nez de verger plutôt que de pomme seule, et le pays d’Auge se distille deux fois à repasse là où le reste de la Normandie passe une seule fois en colonne. Les pommes à cidre qui le font sont des variétés amères et tanniques que personne ne croquerait : on les a sélectionnées pour le tanin, pas pour la corbeille."},
tip:{en:"Deglaze pork or tripe while the pan is still fierce, then add the cream off the heat - done the other way round, the acidity splits the cream. A tablespoon a head is plenty; past that the apple gives way to spirit heat.",
fr:"Déglacez le porc ou les tripes tant que la poêle est vive, puis ajoutez la crème hors du feu - dans l’autre sens, l’acidité tranche la crème. Une cuillère à soupe par personne suffit largement ; au-delà, la pomme cède la place à la chaleur de l’alcool."},
pairs:["apple","pork","cream","camembert","butter","andouille","chicken","pear"],
svg:'<path class="f2 sf" d="M42 34q-7-7-15-2t-4 22 13 22q6 3 6 3t6-3q9-4 13-22t-4-22-15 2z"/><path class="s" d="M42 34v-9"/><path class="f1 sf" d="M42 27q7-10 15-7-2 11-15 7z"/><path class="f1 sf" d="M62 52h14v10q0 8-7 8t-7-8z"/><path class="s" d="M69 70v6M63 76h12"/>'},

{id:"champagne-vinegar",cat:"cellar",name:{en:"Champagne vinegar",fr:"Vinaigre de Champagne"},latin:"Vitis vinifera 'Chardonnay'",
origin:{en:"Champagne & Reims",fr:"Champagne, Reims"},season:[],
flavor:["sour","delicate","floral","fresh"],
story:{en:"Vinegar became an Orleans trade because wine barged up the Loire towards Paris turned before it arrived, and the slow surface method that took the town's name is still how the good Champagne vinegars are made - weeks in oak rather than a day in a tank. The wine behind it is the region's still base wine, taken before it ever sees a second fermentation.",
fr:"Le vinaigre est devenu un métier orléanais parce que le vin remonté vers Paris tournait en chemin, et la méthode lente de surface qui porte le nom de la ville reste celle des bons vinaigres de Champagne - des semaines en fût de chêne plutôt qu’un jour en cuve. Le vin qui les fait est le vin de base de la région, tranquille, pris avant toute seconde fermentation."},
tip:{en:"It is usually bottled near six percent against seven for an ordinary white wine vinegar, so a vinaigrette can go to one part in three of oil rather than one in four. On raw fish or oysters serve it neat as a mignonette with shallot, since the acid is low enough not to cook the flesh.",
fr:"Il titre en général autour de six pour cent contre sept pour un vinaigre de vin blanc ordinaire : une vinaigrette peut monter à une part pour trois d’huile plutôt qu’une pour quatre. Sur du poisson cru ou des huîtres, servez-le pur en mignonnette avec de l’échalote, son acidité étant assez basse pour ne pas cuire la chair."},
pairs:["oyster","shallot","scallop","sea-bass","cream","butter","chives","cucumber"],
svg:'<path class="f1 sf" d="M42 34h12v6q12 8 12 22v14q0 4-4 4H36q-4 0-4-4V62q0-14 10-22z"/><path class="f2 sf" d="M40 18q8-4 16 0v10H40z"/><path class="s" d="M40 24h16M44 28v6M52 28v6"/><path class="s" d="M32 68h32"/>'},

{id:"cheongju",cat:"cellar",rare:true,name:{en:"Cheongju",fr:"Cheongju"},latin:"Oryza sativa",
origin:{en:"Korea",fr:"Corée"},season:[],
flavor:["sweet","mild","umami"],
story:{en:"Cheongju is the clear wine drawn off the top of a fermented rice mash; stir water into what is left at the bottom and you have makgeolli, so the two are one brew divided. It is the wine of jesa, the rite for the ancestors, which is why it sits in Korean kitchens for reasons that have nothing to do with the pan.",
fr:"Le cheongju est le vin clair que l’on soutire au-dessus d’une purée de riz fermentée ; délayez d’eau ce qui reste au fond et vous obtenez du makgeolli - même brassin, partagé en deux. C’est le vin du jesa, le rite aux ancêtres, et c’est pour cela qu’il est présent dans les cuisines coréennes bien au-delà de la casserole."},
tip:{en:"It is the odour-stripper of the Korean kitchen: a tablespoon over raw beef, pork or fish, ten minutes to sit, then patted dry before it goes near heat. In a galbi marinade add it raw and never boiled, so the alcohol carries the aromatics into the meat and burns off on the grill.",
fr:"C’est le désodorisant de la cuisine coréenne : une cuillère à soupe sur du bœuf, du porc ou du poisson crus, dix minutes de repos, puis on éponge avant toute chaleur. Dans une marinade de galbi, ajoutez-le cru et jamais bouilli : l’alcool emporte les arômes dans la viande et s’évapore au gril."},
pairs:["beef","pork","garlic","ginger","gochujang","doenjang","spring-onion","pear"],
svg:'<path class="f1 sf" d="M20 50h56q-5 22-28 22T20 50z"/><path class="s" d="M20 50h56M28 60q20 8 40 0"/><ellipse class="f2 sf" cx="44" cy="44" rx="12" ry="7"/><path class="f3 sf" d="M54 42l17-13 3 4-17 13z"/>'},

{id:"mei-kuei-lu-chiew",cat:"cellar",rare:true,name:{en:"Chinese rose wine",fr:"Alcool de rose chinois (mei kuei lu)"},latin:"Rosa rugosa",
origin:{en:"Northern China, Cantonese kitchens",fr:"Chine du Nord, cuisines cantonaises"},season:[],
flavor:["floral","sweet","warm"],
story:{en:"Sorghum spirit is steeped with rose petals and rock sugar and bottled at around fifty-four percent, strong enough that a spoonful is the whole dose. It is what makes Cantonese lap cheong smell of roses rather than of pork, and no rice or grain wine stands in for it.",
fr:"Un alcool de sorgho est macéré avec des pétales de rose et du sucre candi, puis embouteillé autour de cinquante-quatre degrés : une cuillerée fait la dose entière. C’est lui qui donne au lap cheong cantonais une odeur de rose plutôt que de porc, et aucun vin de riz ou de céréale ne le remplace."},
tip:{en:"A teaspoon per 500 g of pork is the working dose in char siu; beyond that the rose turns soapy. Put it into the marinade cold, since heat drives the aroma off, and brush on another half-teaspoon at the end of the roasting so something reaches the table.",
fr:"Une cuillère à café pour 500 g de porc est la juste mesure au char siu ; au-delà, la rose vire au savon. Mettez-le froid dans la marinade, la chaleur en chassant le parfum, et badigeonnez une demi-cuillère de plus en fin de rôtissage pour qu’il en reste à table."},
pairs:["pork","honey","soy-sauce","star-anise","chinese-five-spice","garlic","ginger","hoisin-sauce"],
svg:'<path class="f2 sf" d="M42 34h12v6q10 6 10 18v14q0 6-6 6H38q-6 0-6-6V58q0-12 10-18z"/><path class="s" d="M32 62h32"/><path class="f1 sf" d="M48 12q9 0 9 8t-9 10q-9-2-9-10t9-8z"/><path class="s" d="M43 20q5-4 10 0M48 30v4"/>'},

{id:"cognac",cat:"cellar",luxe:true,name:{en:"Cognac",fr:"Cognac"},latin:"Vitis vinifera 'Ugni blanc'",
origin:{en:"Charente & Charente-Maritime",fr:"Charente et Charente-Maritime"},season:[],
flavor:["fruity","floral","warm","woody"],
story:{en:"Ugni blanc makes a wine too thin and too acid to drink, around nine percent, which is precisely what the charentais still wants - and it is now very nearly all that Cognac plants. The angels' share, two or three percent of each cask lost to the air every year, feeds a black fungus called Baudoinia on the town's walls, so the ageing cellars can be found by their soot.",
fr:"L’ugni blanc donne un vin trop maigre et trop acide pour être bu, autour de neuf degrés, ce qui est exactement ce que demande l’alambic charentais - et il occupe aujourd’hui la quasi-totalité du vignoble. La part des anges, ces deux ou trois pour cent que chaque fût perd chaque année, nourrit un champignon noir, la baudoinia, sur les murs de la ville : les chais se repèrent à la suie."},
tip:{en:"Flambe off the heat and away from the extractor: pour, let it warm for a few seconds, then light it, because cold spirit hitting a hot pan will not catch. In a sauce, reduce it almost to dry before the stock goes in, or the finished sauce keeps a raw spirit edge that nothing later will cover.",
fr:"Flambez hors du feu et loin de la hotte : versez, laissez tiédir quelques secondes, puis enflammez - un alcool froid jeté dans une poêle brûlante ne prend pas. En sauce, réduisez-le presque à sec avant d’ajouter le fond, sinon il reste une pointe d’alcool cru que rien ne rattrapera ensuite."},
pairs:["lobster","foie-gras","cream","shallot","butter","prune","tarragon","chestnut"],
svg:'<path class="f1 sf" d="M32 26h32q4 20-16 30-20-10-16-30z"/><path class="f2" d="M34 40q14 6 28 0-4 12-14 16-10-4-14-16z"/><path class="s" d="M48 56v16M36 74h24"/>'},

{id:"creme-de-cassis",cat:"cellar",name:{en:"Crème de cassis de Dijon",fr:"Crème de cassis de Dijon"},latin:"Ribes nigrum",
origin:{en:"Côte-d'Or, Burgundy",fr:"Côte-d’Or, Bourgogne"},season:[],
flavor:["sweet","fruity","sour","rich"],
story:{en:"European law reserves the word creme for a minimum of 250 grams of sugar a litre, and raises it to 400 for blackcurrant alone, because the fruit's acidity demands it. The aperitif took the name of Felix Kir, a canon and post-war mayor of Dijon who served blanc-cassis at his receptions - the drink itself was a good deal older than he was.",
fr:"Le droit européen réserve le mot crème à un minimum de 250 grammes de sucre par litre, et le porte à 400 pour le seul cassis, parce que l’acidité du fruit l’exige. L’apéritif a pris le nom de Félix Kir, chanoine et maire de Dijon d’après-guerre, qui servait le blanc-cassis dans ses réceptions - le mélange, lui, était bien plus vieux que lui."},
tip:{en:"Its sugar burns, so build the gastrique the other way round: reduce the vinegar and stock first, then add the cassis off the boil and let it thicken in the residual heat. One part cassis to two of red wine vinegar holds up against duck or venison.",
fr:"Son sucre brûle : montez la gastrique à l’envers - réduisez d’abord le vinaigre et le fond, puis ajoutez le cassis hors ébullition et laissez épaissir à la chaleur résiduelle. Une part de cassis pour deux de vinaigre de vin rouge tient devant un canard ou un chevreuil."},
pairs:["duck","venison","blackcurrant","dark-chocolate","pigeon","red-wine-vinegar","pear","cream"],
svg:'<path class="f1 sf" d="M56 30h10v8q6 4 6 12v20q0 4-4 4H54q-4 0-4-4V50q0-8 6-12z"/><circle class="f3 sf" cx="30" cy="46" r="9"/><circle class="f3 sf" cx="38" cy="64" r="8"/><path class="s" d="M30 37V26M38 56V30M26 26h18"/>'},

{id:"dark-rum",cat:"cellar",name:{en:"Dark rum",fr:"Rhum brun"},latin:"Saccharum officinarum",
origin:{en:"Caribbean & Latin America",fr:"Caraïbes et Amérique latine"},season:[],
flavor:["sweet","warm","woody","rich"],
story:{en:"The story goes that the exiled Polish king Stanislas Leszczynski, finding a kouglof too dry, drowned it in sweet wine; the rum came later, at Stohrer in Paris, and the cake kept the name baba. Colour is not age in rum - caramel is permitted in most origins, so a very dark bottle can be a very young one.",
fr:"On raconte que le roi de Pologne en exil Stanislas Leszczynski, trouvant un kouglof trop sec, le noya de vin doux ; le rhum est venu plus tard, chez Stohrer à Paris, et le gâteau a gardé le nom de baba. La couleur n’est pas l’âge : le caramel est autorisé dans la plupart des origines, et une bouteille très sombre peut être toute jeune."},
tip:{en:"For a baba, soak at about 55 °C and add the rum to the syrup off the heat: hotter and the crumb collapses while the alcohol leaves anyway. Count roughly 100 ml of rum to a litre of syrup.",
fr:"Pour un baba, imbibez autour de 55 °C et ajoutez le rhum au sirop hors du feu : plus chaud, la mie s’affaisse et l’alcool s’en va de toute façon. Comptez environ 100 ml de rhum par litre de sirop."},
pairs:["vanilla","raisin","dark-chocolate","banana","coffee","pineapple","butter","cinnamon"],
svg:'<path class="f3 sf" d="M40 28h16v10q12 8 12 20v16q0 6-6 6H34q-6 0-6-6V58q0-12 12-20z"/><path class="f1 sf" d="M30 56h36v14H30z"/><path class="s" d="M34 63h28"/><path class="f2 sf" d="M38 20h20v8H38z"/>'},

{id:"fino-sherry",cat:"cellar",name:{en:"Fino sherry",fr:"Xérès fino"},latin:"Vitis vinifera 'Palomino'",
origin:{en:"Jerez de la Frontera, Andalusia",fr:"Jerez de la Frontera, Andalousie"},season:[],
flavor:["nutty","briny","delicate"],
story:{en:"Fortify Palomino to about fifteen degrees and a film of yeast, the flor, grows across the surface of the butt and lives there, eating the last sugar and glycerol and sealing the wine from air. Push the spirit half a degree higher and the veil dies, which is the whole difference between a fino and an amontillado.",
fr:"Mutez du palomino à quinze degrés environ et un voile de levures, la flor, s’installe à la surface du fût et y vit, mangeant le dernier sucre et le glycérol tout en coupant le vin de l’air. Un demi-degré d’alcool de plus et le voile meurt : c’est là toute la différence entre un fino et un amontillado."},
tip:{en:"Treat it as a live product, not a fortified one: refrigerate the open bottle and finish it in three days, after which the bread-dough and almond notes are simply gone. Pour it into a jamón or almond sauce at the end, never as the braising liquid.",
fr:"Traitez-le comme un produit vivant, pas comme un vin muté : bouteille ouverte au froid, finie en trois jours, passé quoi les notes de pâte à pain et d’amande ont disparu. Versez-le en fin de cuisson dans une sauce au jambon ou à l’amande, jamais comme liquide de braisage."},
pairs:["jamon-serrano","almond","olive-gordal","anchovy","manchego","shrimp"],
svg:'<path class="f1 sf" d="M36 24h24q0 24-12 30-12-6-12-30z"/><path class="s" d="M48 54v16M38 72h20"/><path class="s" d="M37 32h22"/><circle class="dot" cx="42" cy="29" r="1.8"/><circle class="dot" cx="48" cy="28" r="1.8"/><circle class="dot" cx="54" cy="29" r="1.8"/>'},

{id:"floc-de-gascogne",cat:"cellar",name:{en:"Floc de Gascogne",fr:"Floc de Gascogne"},latin:"Vitis vinifera",
origin:{en:"Gascony, Gers",fr:"Gascogne, Gers"},season:[],
flavor:["sweet","fruity","warm"],
story:{en:"Lo floc is Gascon for a bouquet of flowers, and the appellation, recognised in 1990, is the region's own mistelle: fresh must muted with Armagnac from the same estate. Armagnac is distilled once, at low strength, and keeps more of the grape than Cognac does — which is why Floc arrives with prune and rancio weight where Pineau stays bright.",
fr:"« Lo floc » veut dire bouquet de fleurs en gascon, et l’appellation, reconnue en 1990, est la mistelle du pays : moût frais muté à l’armagnac du même domaine. L’armagnac est distillé une seule fois, à faible degré, et garde plus de raisin que le cognac — d’où le pruneau et le rancio du floc, là où le pineau reste vif."},
tip:{en:"Deglaze duck or magret with it and drop in two prunes to swell in the reduction; the sauce will need no added sugar afterwards. Serve the rest very cold, 6 to 8 °C, as the Gascons do before the meal.",
fr:"Déglacez un magret avec, en y jetant deux pruneaux qui gonfleront dans la réduction : la sauce n’a plus besoin de sucre. Le reste se boit très frais, 6 à 8 °C, à la gasconne, avant le repas."},
pairs:["duck","prune","foie-gras","armagnac","walnut","cantaloupe"],
svg:'<path class="f2 sf" d="M36 22h12v10q10 6 10 16v28a5 5 0 0 1-5 5H31a5 5 0 0 1-5-5V48q0-10 10-16z"/><path class="f3 sf" d="M36 19h12v6H36z"/><circle class="f1 sf" cx="70" cy="40" r="5"/><circle class="f1 sf" cx="70" cy="52" r="5"/><circle class="f1 sf" cx="76" cy="46" r="5"/><circle class="dot" cx="70" cy="46" r="2.5"/>'},

{id:"grape-must",cat:"cellar",name:{en:"Grape must",fr:"Moût de raisin"},latin:"Vitis vinifera",
origin:{en:"Wine regions, at harvest",fr:"Vignobles, à la vendange"},season:[9,10],
flavor:["sweet","fruity","tangy"],
story:{en:"The word mostarda comes from mustum ardens, burning must - grape must cooked down with ground mustard, long before it came to mean candied fruit in syrup. Must is only itself for a few days, since the wild yeast on the skins starts fermenting it in the vat, so everything made from it is made at harvest or not at all.",
fr:"Le mot mostarda vient de mustum ardens, le moût brûlant - du moût de raisin cuit avec de la moutarde broyée, bien avant qu’il ne désigne des fruits confits au sirop. Le moût n’est lui-même que quelques jours, les levures des peaux le faisant partir en fermentation dans la cuve : tout ce qu’on en tire se fait aux vendanges ou pas du tout."},
tip:{en:"Reduce it uncovered in a wide pan and skim as you go: it falls by three quarters to a syrup, while a lid turns the same must into jam. In the fridge it will ferment inside a week, so freeze whatever you are not cooking down that day.",
fr:"Réduisez-le à découvert dans une large bassine en écumant au fur et à mesure : il tombe des trois quarts pour donner un sirop, là où un couvercle transforme le même moût en confiture. Au réfrigérateur, il fermente en moins d’une semaine : congelez ce que vous ne cuisez pas le jour même."},
pairs:["walnut","chestnut","quince","mustard-seed","pork","cinnamon","grape","ricotta"],
svg:'<path class="f1 sf" d="M22 38h52l-6 34a6 6 0 0 1-6 4H34a6 6 0 0 1-6-4z"/><path class="f2" d="M26 52h44l-3 20a6 6 0 0 1-6 4H35a6 6 0 0 1-6-4z"/><path class="s" d="M22 38h52M27 54h42"/><circle class="dot" cx="40" cy="60" r="2.5"/><circle class="dot" cx="56" cy="64" r="2.5"/>'},

{id:"grappa",cat:"cellar",name:{en:"Grappa",fr:"Grappa"},latin:"Vitis vinifera",
origin:{en:"Italy (Friuli, Veneto, Piedmont)",fr:"Italie (Frioul, Vénétie, Piémont)"},season:[],
flavor:["floral","fruity","warm","pungent"],
story:{en:"Grappa was sold by the demijohn as a peasant spirit until 1973, when the Nonino distillery ran a single grape variety, Picolit, on its own and bottled it like a wine; every single-varietal grappa since dates from that one decision. The law asks for Italian pomace distilled in Italy, and the fresher the marc reaches the still, the more flowers and the less earth end up in the glass.",
fr:"La grappa se vendait à la dame-jeanne, alcool de paysans, jusqu’en 1973, quand la distillerie Nonino passa un seul cépage, le picolit, à l’alambic et l’embouteilla comme un vin ; toutes les grappas monocépages datent de cette décision-là. La loi exige un marc italien distillé en Italie, et plus le marc arrive frais à l’alambic, plus il donne de fleurs et moins de terre."},
tip:{en:"Serve it and cook with it cool, around 10 °C for a young one, or it reads as nothing but spirit. Off the heat, a spoonful stirred into a risotto at the mantecatura lifts the whole dish; boiled into it, the same spoonful turns bitter.",
fr:"Servez-la et cuisinez-la fraîche, autour de 10 °C pour une jeune, sans quoi elle n’est plus que de l’alcool. Hors du feu, une cuillerée dans un risotto au moment de la mantecatura relève tout le plat ; bouillie dedans, la même cuillerée devient amère."},
pairs:["pear","peach","coffee","dark-chocolate","cream","gorgonzola-dolce","apricot","grape"],
svg:'<path class="f1 sf" d="M38 16h20q2 14-4 20 6 6 4 18-6 6-10 6t-10-6q-2-12 4-18-6-6-4-20z"/><path class="f2" d="M40 46q8 6 16 0 1 8-2 12-6 4-12 0-3-4-2-12z"/><path class="s" d="M48 60v20M36 82h24"/>'},

{id:"junmai-sake",cat:"cellar",name:{en:"Junmai sake",fr:"Saké junmai"},latin:"Oryza sativa",
origin:{en:"Japan (Nada, Fushimi)",fr:"Japon (Nada, Fushimi)"},season:[],
flavor:["umami","mild","rich"],
story:{en:"Sake sold in Japan as cooking sake is salted to a couple of percent so that it counts as a seasoning rather than a drink, and escapes liquor tax; junmai means pure rice, and carries nothing but rice, water, koji and yeast. The category once demanded a polishing ratio as well, a requirement dropped in the 2000s - today the single rule is that no distilled alcohol goes in.",
fr:"Le saké vendu au Japon comme saké de cuisine est salé à deux ou trois pour cent pour compter comme assaisonnement et non comme boisson, échappant ainsi à la taxe sur les alcools ; junmai veut dire riz pur, et ne contient que du riz, de l’eau, du koji et des levures. La catégorie exigeait autrefois un taux de polissage, abandonné dans les années 2000 : la seule règle aujourd’hui est qu’aucun alcool distillé n’y entre."},
tip:{en:"Let it boil for a minute before it meets anything delicate: the alcohol leaves and the amino acids stay, and it is those that soften fish odour and round out a broth. Because it carries no salt, count it as liquid rather than seasoning, and season only once it has reduced.",
fr:"Faites-le bouillir une minute avant qu’il ne rencontre un produit délicat : l’alcool part, les acides aminés restent, et ce sont eux qui adoucissent l’odeur du poisson et arrondissent un bouillon. Comme il n’est pas salé, comptez-le comme liquide et non comme assaisonnement, et salez seulement après réduction."},
pairs:["clam","salmon","ginger","kombu","hon-mirin","soy-sauce","daikon","chicken"],
svg:'<path class="f2 sf" d="M44 20h8v8q14 8 14 24v14q0 10-18 10t-18-10V52q0-16 14-24z"/><path class="s" d="M34 60q14 6 28 0M44 26h8"/><path class="f1 sf" d="M68 62h14q0 12-7 12t-7-12z"/>'},

{id:"kirsch",cat:"cellar",name:{en:"Kirsch",fr:"Kirsch"},latin:"Prunus avium",
origin:{en:"Fougerolles, Alsace and the Black Forest",fr:"Fougerolles, Alsace et Forêt-Noire"},season:[],
flavor:["fruity","bitter","warm"],
story:{en:"The stones are crushed in with the fruit and ferment alongside it: amygdalin from the kernels becomes benzaldehyde in the still, and that bitter-almond note is what no cherry liqueur has. Fougerolles in the Haute-Saone holds an appellation of its own for its kirsch, and it takes something like ten kilos of cherries to fill a bottle.",
fr:"Les noyaux sont broyés avec les fruits et fermentent avec eux : l’amygdaline des amandons devient du benzaldéhyde à l’alambic, et c’est cette amande amère qu’aucune liqueur de cerise ne possède. Fougerolles, en Haute-Saône, tient une appellation propre pour son kirsch, et il faut une dizaine de kilos de cerises pour remplir une bouteille."},
tip:{en:"In fondue it is mechanics rather than flavour - a spoonful stirred in with the cornflour is what traditionally keeps the melted cheese loose instead of stringy. In a pate a bombe or a syrup, add it once the pan is off the heat, since most of the aroma leaves within the first minute of boiling.",
fr:"Dans la fondue, ce n’est pas un arôme mais une mécanique : une cuillerée avec la fécule est ce qui garde traditionnellement le fromage souple au lieu de filant. Dans une pâte à bombe ou un sirop, ajoutez-le hors du feu, l’essentiel du parfum s’en allant dès la première minute d’ébullition."},
pairs:["cherry","dark-chocolate","gruyere","emmentaler","cream","almond","apricot","griotte"],
svg:'<path class="f1 sf" d="M44 14h8v20q8 8 8 20v20q0 4-4 4H40q-4 0-4-4V54q0-12 8-20z"/><path class="s" d="M36 62h24"/><circle class="f3 sf" cx="26" cy="66" r="8"/><circle class="f2 sf" cx="70" cy="68" r="7"/><path class="s" d="M26 58q2-14 14-18M70 61q0-12-12-16"/>'},

{id:"macvin-du-jura",cat:"cellar",rare:true,name:{en:"Macvin du Jura",fr:"Macvin du Jura"},latin:"Vitis vinifera",
origin:{en:"Jura, France",fr:"Jura, France"},season:[],
flavor:["sweet","warm","woody"],
story:{en:"Macvin is the only French appellation whose mistelle is muted with marc — oak-aged pomace brandy — rather than with a wine brandy, and the name carries it: mac, for marc. Recognised in 1991, it is the youngest of the Jura appellations and the one that tastes least like wine, all pressed skins and warm spice.",
fr:"Le macvin est la seule appellation française dont la mistelle est mutée au marc — l’eau-de-vie de marc de raisin, vieillie en fût — et non à une eau-de-vie de vin ; son nom le dit : mac, pour marc. Reconnue en 1991, c’est la plus jeune des appellations jurassiennes et celle qui ressemble le moins à du vin, toute en peaux pressées et en épice chaude."},
tip:{en:"A spoonful stirred into a cream sauce off the heat gives a spice note no wine reduction produces; cook it hard and the marc turns to fusel. In the Jura it is poured over aged Comté, and the salt of the cheese is what makes the sweetness readable.",
fr:"Une cuillerée dans une sauce à la crème, hors du feu, apporte une note épicée qu’aucune réduction de vin ne donne ; trop cuit, le marc tourne à l’alcool lourd. Dans le Jura, on l’arrose sur du comté vieux : c’est le sel du fromage qui rend le sucre lisible."},
pairs:["comte","walnut","cream","morel","pear","chestnut"],
svg:'<path class="f2 sf" d="M26 56a18 18 0 0 1 36 0v14a6 6 0 0 1-6 6H32a6 6 0 0 1-6-6z"/><path class="f1 sf" d="M36 42h16v10H36z"/><path class="s" d="M52 44q14 0 16 12t0 18"/><circle class="dot" cx="68" cy="80" r="2"/>'},

{id:"madeira-malmsey",cat:"cellar",luxe:true,name:{en:"Malmsey Madeira",fr:"Madère Malvoisie"},latin:"Vitis vinifera 'Malvasia'",
origin:{en:"Madeira, Portugal",fr:"Madère, Portugal"},season:[],
flavor:["sweet","rich","nutty","warm"],
story:{en:"Malmsey is an English mangling of Monemvasia, the Peloponnesian port that shipped Malvasia wine across medieval Europe long before the vine reached Madeira. Chroniclers record that the Duke of Clarence, condemned in 1478, was allowed to choose his death and asked to be drowned in a butt of it — a story repeated for five centuries with no way left to check it.",
fr:"« Malmsey » est une déformation anglaise de Monemvasia, le port du Péloponnèse qui expédiait le malvoisie dans toute l’Europe médiévale bien avant que la vigne n’atteigne Madère. Les chroniques rapportent que le duc de Clarence, condamné en 1478, put choisir sa mort et demanda d’être noyé dans un fût de ce vin — récit répété depuis cinq siècles, et devenu invérifiable."},
tip:{en:"Its acidity is what keeps the sugar from cloying, so reduce it gently: a hard boil drives off the volatile acidity and leaves syrup. A spoonful stirred into melted dark chocolate off the heat loosens a ganache without adding water.",
fr:"C’est son acidité qui empêche le sucre d’écœurer : réduisez doucement, une grosse ébullition ne laisse que du sirop. Une cuillerée dans du chocolat noir fondu, hors du feu, détend une ganache sans y mettre d’eau."},
pairs:["dark-chocolate","dried-fig","walnut","medjool-date","orange","cream"],
svg:'<path class="f2 sf" d="M28 30h40q7 20 0 40H28q-7-20 0-40z"/><path class="s" d="M25 42h46M25 58h46"/><path class="f3 sf" d="M45 70h6v6h-6z"/><circle class="dot" cx="48" cy="82" r="2"/>'},

{id:"manzanilla-sherry",cat:"cellar",name:{en:"Manzanilla",fr:"Manzanilla"},latin:"Vitis vinifera 'Palomino'",
origin:{en:"Sanlúcar de Barrameda, Cádiz",fr:"Sanlúcar de Barrameda, Cadix"},season:[],
flavor:["briny","delicate","fresh"],
story:{en:"Same grape and same flor as a fino, but only wine aged in Sanlúcar's bodegas at the mouth of the Guadalquivir may be called manzanilla: Atlantic humidity keeps the yeast veil thick through the summer, when it thins and lets air in further inland. The result is lighter and openly saline, which is why the sherry towns pour it with shellfish and with little else.",
fr:"Même cépage et même flor qu’un fino, mais seul le vin élevé dans les bodegas de Sanlúcar, à l’embouchure du Guadalquivir, peut s’appeler manzanilla : l’humidité atlantique y maintient le voile épais tout l’été, quand il s’amincit et laisse passer l’air plus à l’intérieur des terres. Il en résulte un vin plus léger et franchement salin, que les villes du xérès servent avec les coquillages et guère avec autre chose."},
tip:{en:"Cook prawns or clams in it rather than in white wine — a splash the moment the shells open, then straight off the heat. Buy the smallest bottle you will finish; three days after opening it is a duller wine.",
fr:"Faites-y cuire gambas ou palourdes plutôt qu’au vin blanc : un trait au moment où les coquilles s’ouvrent, puis hors du feu aussitôt. Achetez le plus petit format que vous finirez — trois jours après ouverture, ce n’est plus le même vin."},
pairs:["clam","common-prawn","olive-gordal","anchovy","boquerones","lemon"],
svg:'<path class="f1 sf" d="M30 50h36l-4 26H34z"/><path class="s" d="M27 50h42"/><path class="f2 sf" d="M42 18h12v10l4 8v14H38V36z"/><path class="s" d="M34 60q6-7 12 0M50 60q6-7 12 0"/>'},

{id:"maraschino",cat:"cellar",name:{en:"Maraschino liqueur",fr:"Marasquin"},latin:"Prunus cerasus var. marasca",
origin:{en:"Zadar, Dalmatia; now the Veneto",fr:"Zadar, Dalmatie ; aujourd’hui la Vénétie"},season:[],
flavor:["fruity","bitter","nutty","sweet"],
story:{en:"The Marasca is a small sour cherry of the Dalmatian coast, and the distillation takes the whole fruit - stems, leaves and stones together - which is where the nutty bitterness comes from. Luxardo, founded at Zadar in 1821, ages it in ash rather than oak precisely so that it stays colourless, then sweetens it; the straw jacket on the bottle is its old shipping armour.",
fr:"La marasca est une petite cerise acide de la côte dalmate, et la distillation prend le fruit entier - queues, feuilles et noyaux ensemble - d’où cette amertume d’amande. Luxardo, fondée à Zadar en 1821, l’élève sous frêne et non sous chêne précisément pour qu’elle reste incolore, puis la sucre ; la robe de paille de la bouteille est son ancienne armure de transport."},
tip:{en:"It is dry for a liqueur and will not sweeten a syrup on its own, so in a savarin soak count it as flavour and leave the sugar where it is. A teaspoon through a fruit salad reads as almond rather than as cherry, which is exactly the point of it.",
fr:"C’est une liqueur sèche, qui ne sucrera pas un sirop à elle seule : dans un sirop à savarin, comptez-la comme parfum et laissez le sucre où il est. Une cuillère à café dans une salade de fruits se lit comme de l’amande et non comme de la cerise - c’est tout son intérêt."},
pairs:["cherry","griotte","amarena","cream","vanilla","dark-chocolate","peach","pistachio"],
svg:'<path class="f2 sf" d="M44 14h8v14q16 8 16 26t-20 22-20-22 16-26z"/><path class="f1 sf" d="M30 52q4-8 18-8t18 8q2 22-18 24T30 52z"/><path class="s" d="M32 52l32 14M64 52l-32 14M48 44v32"/>'},

{id:"marc-de-bourgogne",cat:"cellar",name:{en:"Marc de Bourgogne",fr:"Marc de Bourgogne"},latin:"Vitis vinifera",
origin:{en:"Burgundy",fr:"Bourgogne"},season:[],
flavor:["earthy","woody","warm","pungent"],
story:{en:"It is made from what the press leaves behind - skins, pips and stalks, wetted down and fermented a second time - which is why it was the grower's own drink rather than the merchant's. Epoisses and Ami du Chambertin are washed with it through their ripening, so a good part of what you smell in the cheese is the spirit.",
fr:"Il se fait avec ce que le pressoir laisse - peaux, pépins et rafles, remouillés et refermentés - et c’est pourquoi il était la boisson du vigneron et non celle du négociant. L’époisses et l’ami du Chambertin sont lavés au marc pendant leur affinage : une bonne part de ce que l’on sent dans le fromage est celle de l’eau-de-vie."},
tip:{en:"To wash a soft cheese, work with roughly one part marc to five or six of brine, brushed on every two or three days - neat spirit kills the rind's bacteria and the crust dries out. In the pan it grips far harder than Cognac, so use half as much.",
fr:"Pour laver une pâte molle, comptez environ une part de marc pour cinq ou six de saumure, au pinceau tous les deux ou trois jours : l’alcool pur tue les bactéries de la croûte, qui sèche alors. À la poêle, il accroche bien plus fort que le cognac - moitié moins suffit."},
pairs:["epoisses","cream","mushroom","chicken","butter","shallot","grape","comte"],
svg:'<path class="f2 sf" d="M26 44h44v26a6 6 0 0 1-6 6H32a6 6 0 0 1-6-6z"/><path class="s" d="M36 44v32M48 44v32M60 44v32"/><path class="f3 sf" d="M30 34h36v10H30z"/><path class="s" d="M48 34V18M38 18h20"/>'},

{id:"marsala-dolce",cat:"cellar",name:{en:"Marsala dolce",fr:"Marsala doux"},latin:"Vitis vinifera 'Grillo'",
origin:{en:"Marsala, Sicily",fr:"Marsala, Sicile"},season:[],
flavor:["sweet","rich","toasty","fruity"],
story:{en:"The sweetness is added rather than fermented in: producers stop the wine with mosto cotto, must boiled down to caramel, and with sifone, a mistelle of must muted with spirit. That is why dolce and secco stand on different shelves in a Sicilian kitchen and are never poured from the same bottle by mistake.",
fr:"Le sucre n’est pas fermentaire, il est ajouté : les maisons arrêtent le vin au mosto cotto, moût réduit jusqu’au caramel, et au sifone, une mistelle mutée à l’alcool. D’où deux étagères distinctes dans une cuisine sicilienne, et jamais une bouteille prise pour l’autre."},
tip:{en:"For zabaglione the working ratio is per egg yolk: one half-eggshell of sugar, one of Marsala, whisked over water that trembles rather than boils. Past about 82 °C the yolk sets in threads and no whisking brings it back.",
fr:"Pour le sabayon, par jaune d’œuf : une demi-coquille de sucre, une de marsala, fouettés sur une eau frémissante et jamais bouillante. Au-delà de 82 °C, le jaune coagule en filaments et rien ne le rattrape."},
pairs:["egg","sugar","mascarpone","coffee","dark-chocolate","almond"],
svg:'<path class="f1 sf" d="M24 44h48q-5 28-24 28T24 44z"/><path class="f2 sf" d="M26 44q5-9 12-5t10 0 12 1 8 4z"/><path class="s" d="M70 20L58 40"/><path class="s" d="M62 34q-8 8-4 14M67 37q-6 6-3 12"/>'},

{id:"marsala-secco",cat:"cellar",name:{en:"Marsala secco",fr:"Marsala sec"},latin:"Vitis vinifera 'Grillo'",
origin:{en:"Marsala, Sicily",fr:"Marsala, Sicile"},season:[],
flavor:["bitter","nutty","woody"],
story:{en:"John Woodhouse, a Liverpool merchant sheltering at Marsala in 1773, fortified the local wine for the voyage home and found that England would buy it; a quarter-century later Nelson's fleet was ordering it by the pipe. The dry bottling, from Grillo grown on the western Sicilian plain, finishes on bitter almond — the note that reads as savoury depth in a pan sauce.",
fr:"John Woodhouse, marchand de Liverpool réfugié à Marsala en 1773, muta le vin local pour le voyage de retour et découvrit que l’Angleterre l’achetait ; un quart de siècle plus tard, la flotte de Nelson en commandait à la pipe. La version sèche, issue du grillo de la plaine occidentale sicilienne, finit sur l’amande amère — la note qui donne sa profondeur salée à une sauce de poêle."},
tip:{en:"Buy the bottle marked secco or vergine; the sweet one turns a scaloppine into dessert. Deglaze off the flame and reduce by half before any butter goes in, or the sauce will split.",
fr:"Prenez la bouteille marquée secco ou vergine : la version douce transforme une escalope en dessert. Déglacez hors du feu et réduisez de moitié avant d’ajouter le beurre, sinon la sauce tranche."},
pairs:["quasi-de-veau","chicken","mushroom","sage","butter","parmesan"],
svg:'<path class="f1 sf" d="M22 46h40v10a12 12 0 0 1-12 12H34a12 12 0 0 1-12-12z"/><path class="s" d="M62 50l16-6"/><path class="s" d="M26 46q8-9 16-3t18-3"/><path class="f2 sf" d="M70 60q6 4 6 9t-6 7q-5-2-5-7t5-9z"/>'},

{id:"maury",cat:"cellar",rare:true,name:{en:"Maury",fr:"Maury"},latin:"Vitis vinifera 'Grenache noir'",
origin:{en:"Agly valley, Roussillon",fr:"Vallée de l’Agly, Roussillon"},season:[],
flavor:["sweet","fruity","rich"],
story:{en:"Maury's Grenache grows on a band of black schist in the Agly valley, under the ruined Cathar fortress of Quéribus — rock that holds heat and almost no water. Most of it is bottled young in the grenat style, sealed against air, so where Banyuls goes nutty Maury stays black-fruited and tight.",
fr:"Le grenache de Maury pousse sur une bande de schiste noir dans la vallée de l’Agly, sous les ruines du château cathare de Quéribus — une roche qui garde la chaleur et presque pas d’eau. L’essentiel est mis en bouteille jeune, en grenat, à l’abri de l’air : là où le banyuls part sur la noix, le maury reste sur le fruit noir, serré."},
tip:{en:"Grenat is reductive: unlike an oxidative fortified wine it does spoil once opened, so refrigerate and use it within a week. Reduce it with game stock and black pepper rather than with chocolate — the fruit is the point.",
fr:"Le grenat est un vin réduit : contrairement aux mutés oxydatifs, il s’abîme une fois ouvert — au froid, et consommé dans la semaine. Réduisez-le avec un fond de gibier et du poivre noir plutôt qu’avec du chocolat : c’est le fruit qui compte."},
pairs:["venison","cherry","black-pepper","blackcurrant","duck","juniper"],
svg:'<path class="s" d="M48 26v10"/><circle class="f3 sf" cx="40" cy="42" r="7"/><circle class="f3 sf" cx="56" cy="42" r="7"/><circle class="f2 sf" cx="48" cy="54" r="7"/><circle class="f2 sf" cx="33" cy="55" r="7"/><circle class="f2 sf" cx="63" cy="55" r="7"/>'},

{id:"eau-de-vie-mirabelle",cat:"cellar",name:{en:"Mirabelle eau-de-vie",fr:"Eau-de-vie de mirabelle"},latin:"Prunus domestica subsp. syriaca",
origin:{en:"Lorraine",fr:"Lorraine"},season:[],
flavor:["fruity","honeyed","nutty","warm"],
story:{en:"Lorraine grows the great majority of the world's mirabelles, in a season of barely six weeks in August, and the fruit bruises too easily to travel far - distilling was how the surplus was kept. The eau-de-vie is clear and unsweetened, so the honeyed note in the glass belongs to the plum and not to any sugar.",
fr:"La Lorraine produit la très grande majorité des mirabelles du monde, sur une saison d’à peine six semaines en août, et le fruit se meurtrit trop vite pour voyager loin : distiller était la façon de garder le surplus. L’eau-de-vie est claire et non sucrée, si bien que la note miellée du verre appartient à la prune et non à un sucre ajouté."},
tip:{en:"Warm it in the hand before flaming a tart or a souffle omelette, since a spirit straight from a cold cupboard will not light. To macerate, one part spirit to four of halved mirabelles with a spoon of sugar, sealed for a month, gives you the fruit for the tart and the syrup for its glaze.",
fr:"Tiédissez-la dans la main avant de flamber une tarte ou une omelette soufflée : un alcool sorti d’un placard froid ne s’enflamme pas. Pour macérer, une part d’alcool pour quatre de mirabelles dénoyautées avec une cuillerée de sucre, un mois au frais, donne les fruits pour la tarte et le sirop pour son glaçage."},
pairs:["mirabelle","cream","almond","vanilla","butter","apricot","honey","quetsche"],
svg:'<circle class="f2 sf" cx="40" cy="50" r="18"/><path class="s" d="M40 32v36M40 32v-8"/><path class="f1 sf" d="M40 28q10-9 18-5-4 11-18 5z"/><path class="f1 sf" d="M62 58h16q0 12-8 12t-8-12z"/><path class="s" d="M70 70v8M64 78h12"/>'},

{id:"muscat-beaumes-de-venise",cat:"cellar",name:{en:"Muscat de Beaumes-de-Venise",fr:"Muscat de Beaumes-de-Venise"},latin:"Vitis vinifera 'Muscat à petits grains'",
origin:{en:"Beaumes-de-Venise, Vaucluse",fr:"Beaumes-de-Venise, Vaucluse"},season:[],
flavor:["sweet","floral","fruity","citrus"],
story:{en:"The Venise in the name is the Comtat Venaissin, the papal territory around Avignon, not the Italian city; the appellation was recognised in 1945 and remains the Rhône valley's only vin doux naturel. It is made to keep air out rather than let it in, so the grape's own terpenes — rose, lychee, orange flower — survive into the glass.",
fr:"Le « Venise » du nom est le Comtat Venaissin, la terre papale autour d’Avignon, et non la ville italienne ; l’appellation, reconnue en 1945, reste le seul vin doux naturel de la vallée du Rhône. Il est élevé à l’abri de l’air plutôt qu’à son contact, de sorte que les terpènes du raisin — rose, litchi, fleur d’oranger — arrivent intacts dans le verre."},
tip:{en:"Never boil it: those terpenes are volatile and the first minute of heat takes them. Spoon it cold over melon, or fold it into a sabayon once the pan is off the flame.",
fr:"Ne le faites jamais bouillir : ses terpènes sont volatils et la première minute de chaleur les emporte. Arrosez-en le melon bien froid, ou incorporez-le au sabayon une fois la casserole hors du feu."},
pairs:["cantaloupe","peach","apricot","lychee","raspberry","egg"],
svg:'<path class="f1 sf" d="M44 24h8v13q13 8 13 22a17 17 0 0 1-34 0q0-14 13-22z"/><path class="s" d="M32 56q16 9 32 0"/><path class="s" d="M70 33v9"/><circle class="f2 sf" cx="70" cy="29" r="4"/><circle class="f1 sf" cx="64" cy="23" r="4"/><circle class="f1 sf" cx="75" cy="23" r="4"/>'},

{id:"oloroso",cat:"cellar",name:{en:"Oloroso",fr:"Oloroso"},latin:"Vitis vinifera 'Palomino'",
origin:{en:"Jerez, Andalusia",fr:"Jerez, Andalousie"},season:[],
flavor:["nutty","rich","woody"],
story:{en:"Oloroso is fortified to seventeen degrees or more at the outset, above what the flor yeast can survive, so it never grows a veil and oxidises from its first year in cask. Oloroso means fragrant, and the confusion follows from there: it smells of raisin and walnut and is, in the classic style, bone dry — the sweet supermarket bottle is oloroso with syrup added afterwards.",
fr:"L’oloroso est muté d’emblée à dix-sept degrés ou plus, au-dessus de ce que la flor supporte : il ne fait jamais de voile et s’oxyde dès sa première année en fût. Oloroso veut dire « odorant », d’où la confusion — il sent le raisin sec et la noix, et il est, dans le style classique, parfaitement sec ; la bouteille sucrée de supermarché est un oloroso auquel on a ajouté du sirop après coup."},
tip:{en:"This is the sherry with body — glycerol and extract — so it thickens a braise where an amontillado would read thin. Reduce it with oxtail or beef-cheek liquor and resist adding sugar to chase the sweetness the nose promised.",
fr:"C’est le xérès qui a du corps — glycérol et extrait sec — et qui épaissit un braisé là où un amontillado paraîtrait maigre. Réduisez-le avec un jus de queue de bœuf ou de joue, et n’ajoutez surtout pas de sucre pour courir après la douceur que le nez promettait."},
pairs:["oxtail","beef-cheek","mushroom","walnut","onion","black-pepper"],
svg:'<path class="s" d="M48 16v46"/><path class="s" d="M48 16q9 0 9 9"/><path class="f2 sf" d="M40 60h16v18a6 6 0 0 1-6 6h-4a6 6 0 0 1-6-6z"/><path class="s" d="M40 68h16"/><circle class="dot" cx="66" cy="58" r="2.5"/><circle class="dot" cx="70" cy="68" r="2"/>'},

{id:"triple-sec",cat:"cellar",name:{en:"Orange liqueur (triple sec)",fr:"Triple sec (curaçao)"},latin:"Citrus × aurantium",
origin:{en:"Saumur & Angers, Loire",fr:"Saumur et Angers, Val de Loire"},season:[],
flavor:["sweet","citrus","bitter","floral"],
story:{en:"Jean-Baptiste Combier at Saumur claimed the first triple sec in the 1830s and Cointreau followed at Angers, but neither the term nor the method is protected - so a triple sec may be a distillate of bitter-orange peel or simply sweetened neutral spirit with essence. The bitter orange gives what the fresh fruit cannot: the oil of the peel without the acid of the juice.",
fr:"Jean-Baptiste Combier, à Saumur, revendique le premier triple sec dans les années 1830 et Cointreau suit à Angers, mais ni le nom ni la méthode ne sont protégés : un triple sec peut être une distillation d’écorces d’orange amère comme un simple alcool neutre sucré et aromatisé. L’orange amère donne ce que le fruit frais ne peut pas : l’huile de l’écorce sans l’acidité du jus."},
tip:{en:"For crepes Suzette the alcohol goes in twice: a spoonful into the beurre Suzette to dissolve the zest, the rest flamed at the pass. In a souffle, fold it into the warm base and never into the whites, which it will thin.",
fr:"Pour les crêpes Suzette, l’alcool entre deux fois : une cuillerée dans le beurre Suzette pour dissoudre les zestes, le reste flambé à l’envoi. En soufflé, incorporez-le à l’appareil tiède et jamais aux blancs, qu’il liquéfie."},
pairs:["orange","butter","dark-chocolate","vanilla","lemon","cream","almond","strawberry"],
svg:'<circle class="f2 sf" cx="38" cy="54" r="18"/><path class="s" d="M38 36v36M20 54h36M26 42l24 24M50 42L26 66"/><path class="f1 sf" d="M62 26q12 4 10 16t-14 10 8-12-4-14z"/>'},

{id:"pastis",cat:"cellar",name:{en:"Pastis",fr:"Pastis"},latin:"Illicium verum",
origin:{en:"Marseille & Provence",fr:"Marseille et Provence"},season:[],
flavor:["anise","sweet","herbal","warm"],
story:{en:"Paul Ricard put his pastis on the market in 1932, seventeen years after the absinthe ban, building it on star anise and liquorice rather than wormwood - the liquorice is what makes it round where absinthe is bitter. Its anethole is macerated in rather than distilled, so it clouds harder and it will sweeten a sauce that absinthe would only perfume.",
fr:"Paul Ricard met son pastis sur le marché en 1932, dix-sept ans après l’interdiction de l’absinthe, en le bâtissant sur la badiane et la réglisse plutôt que sur l’armoise - c’est la réglisse qui l’arrondit là où l’absinthe est amère. Son anéthol est macéré et non distillé : il trouble plus fort, et il sucre une sauce que l’absinthe se contenterait de parfumer."},
tip:{en:"Reduce it before any liquid goes in, because the sugar in pastis will catch and burn in a dry, hot pan. For a bouillabaisse or a rouille, 20 ml for four people alongside the saffron; beyond that the fish disappears behind the anise.",
fr:"Réduisez-le avant d’ajouter le moindre liquide : le sucre du pastis attache et brûle dans une poêle sèche et chaude. Pour une bouillabaisse ou une rouille, 20 ml pour quatre personnes, en même temps que le safran ; au-delà, le poisson disparaît derrière l’anis."},
pairs:["fennel","saffron","tomato","mussel","monkfish","garlic","red-mullet","orange"],
svg:'<path class="f1 sf" d="M36 26h24l-3 46q-1 6-9 6t-9-6z"/><path class="f2" d="M36 46h24l-3 26q-1 6-9 6t-9-6z"/><path class="s" d="M35 44h26"/><path class="f3 sf" d="M48 6l4 7 8-1-4 7 4 7-8-1-4 7-4-7-8 1 4-7-4-7 8 1z"/>'},

{id:"pedro-ximenez",cat:"cellar",name:{en:"Pedro Ximénez",fr:"Pedro Ximénez (PX)"},latin:"Vitis vinifera 'Pedro Ximénez'",
origin:{en:"Montilla-Moriles, Andalusia",fr:"Montilla-Moriles, Andalousie"},season:[],
flavor:["sweet","rich","fruity","toasty"],
story:{en:"The grapes are laid out on esparto mats in the September sun for a week or more — the soleo — until they are raisins, and the press yields a must so sugary that yeast can barely work on it. What is bottled carries around 400 grams of sugar a litre, black as treacle, tasting of raisin, fig and liquorice.",
fr:"Les raisins sèchent sur des nattes de sparte au soleil de septembre, une semaine ou plus — c’est le soleo — jusqu’à devenir des passerillés, et le moût pressé est si sucré que la levure y travaille à peine. La bouteille titre autour de 400 grammes de sucre par litre, noire comme de la mélasse, et sent le raisin sec, la figue et la réglisse."},
tip:{en:"Use it as a sauce, not a wine: a spoonful over vanilla ice cream, or over blue cheese. In a jus a tablespoon is the ceiling — more and it sets to toffee on the plate as it cools.",
fr:"C’est une sauce plus qu’un vin : une cuillerée sur une glace vanille, ou sur un fromage bleu. Dans un jus, une cuillère à soupe est le plafond — au-delà, il fige en caramel dans l’assiette en refroidissant."},
pairs:["vanilla","dark-chocolate","blue-cheese","raisin","fig","walnut"],
svg:'<ellipse class="f3 sf" cx="44" cy="56" rx="21" ry="11"/><path class="s" d="M64 52L76 34"/><path class="f2 sf" d="M36 43q7-3 10 2t-3 8q-8 1-9-4t2-6z"/><path class="f2 sf" d="M52 41q8-2 9 4t-6 7q-7 0-8-5t5-6z"/><circle class="dot" cx="24" cy="72" r="3"/>'},

{id:"pineau-des-charentes",cat:"cellar",name:{en:"Pineau des Charentes",fr:"Pineau des Charentes"},latin:"Vitis vinifera",
origin:{en:"Charente, France",fr:"Charentes, France"},season:[],
flavor:["sweet","fruity","honeyed","warm"],
story:{en:"Pineau is a mistelle, not a wine: unfermented Charentais grape must muted with young Cognac, so the sugar in the bottle is grape sugar that never met a yeast. Legend has it a sixteenth-century vigneron poured must into a cask still holding eau-de-vie and left the mistake in the cellar for years before tasting it.",
fr:"Le pineau est une mistelle et non un vin : du moût charentais non fermenté, muté au cognac jeune, si bien que le sucre de la bouteille n’a jamais rencontré de levure. La légende veut qu’un vigneron du XVIᵉ siècle ait versé du moût dans une barrique contenant encore de l’eau-de-vie et ait laissé sa méprise vieillir des années avant d’y goûter."},
tip:{en:"In a shellfish sauce add it early and give it a full minute of heat — the young Cognac tastes raw if it goes in at the end. Once opened it fades fast: refrigerate, and drink or cook it within a fortnight.",
fr:"Dans une sauce aux coquillages, versez-le tôt et laissez-le cuire une bonne minute : le cognac jeune reste cru s’il arrive en fin de cuisson. Une fois ouvert, il s’affaisse vite — au réfrigérateur, et fini sous quinze jours."},
pairs:["cantaloupe","foie-gras","scallop","langoustine","butter","shallot"],
svg:'<path class="f1 sf" d="M28 34h26l-4 40H32z"/><path class="s" d="M29 44h24"/><path class="f2 sf" d="M60 26q16 4 16 18-14-2-16-18z"/><path class="s" d="M62 31q11 5 12 12"/>'},

{id:"eau-de-vie-framboise",cat:"cellar",luxe:true,name:{en:"Raspberry eau-de-vie",fr:"Eau-de-vie de framboise"},latin:"Rubus idaeus",
origin:{en:"Alsace & Baden",fr:"Alsace et pays de Bade"},season:[],
flavor:["fruity","floral","warm"],
story:{en:"Raspberries carry so little sugar that fermenting them yields barely any alcohol, so most framboise is not fermented at all: the fruit is steeped in neutral spirit and the whole macerate is then distilled. Something like twenty-five kilos of berries stand behind a single litre, which is the whole explanation for the price.",
fr:"La framboise contient si peu de sucre que la fermenter ne donne presque pas d’alcool : la plupart des eaux-de-vie de framboise ne sont donc pas fermentées mais macérées dans un alcool neutre, puis distillées avec leur macérat. Il y a quelque chose comme vingt-cinq kilos de fruits derrière un seul litre, ce qui explique le prix à lui seul."},
tip:{en:"It perfumes without sweetening: two teaspoons into a litre of sorbet base once it has cooled and no more, or the alcohol will keep the sorbet from setting firm. Never let it boil.",
fr:"Elle parfume sans sucrer : deux cuillères à café pour un litre de base à sorbet une fois refroidie, pas davantage, faute de quoi l’alcool empêchera la prise au froid. Ne la laissez jamais bouillir."},
pairs:["raspberry","dark-chocolate","cream","peach","vanilla","almond","redcurrant","fromage-blanc"],
svg:'<path class="f2 sf" d="M34 28q14-10 28 0 2 16-14 22-16-6-14-22z"/><path class="s" d="M41 30q7 18 14 0M34 38h28"/><path class="f1 sf" d="M42 24q6-6 12 0-6 3-12 0z"/><path class="f1 sf" d="M34 56h28q0 16-14 20-14-4-14-20z"/><path class="s" d="M48 76v6M40 84h16"/>'},

{id:"raspberry-vinegar",cat:"cellar",name:{en:"Raspberry vinegar",fr:"Vinaigre de framboise"},latin:"Rubus idaeus",
origin:{en:"French vinegar houses",fr:"Vinaigreries françaises"},season:[],
flavor:["sour","fruity","tangy"],
story:{en:"For two centuries raspberry vinegar was a drink rather than a seasoning: a sweetened vinegar syrup let down with cold water in summer and given for sore throats in winter. It only crossed into the kitchen in the 1970s, when nouvelle cuisine deglazed so much calf liver and duck with it that the bottle became the decade's punchline.",
fr:"Pendant deux siècles, le vinaigre de framboise fut une boisson plutôt qu'un assaisonnement : un sirop vinaigré que l'on allongeait d'eau fraîche l'été et que l'on donnait contre les maux de gorge l'hiver. Il n'est passé en cuisine que dans les années 1970, lorsque la nouvelle cuisine en a déglacé tant de foies de veau et de magrets que la bouteille est devenue la caricature de l'époque."},
tip:{en:"Add it off the heat. The fruit esters boil away in seconds while the acid stays, so a pan deglazed and then reduced tastes only sharp — a spoonful into the resting juices with a knob of butter is the whole technique.",
fr:"Ajoutez-le hors du feu. Les arômes de fruit s'évaporent en quelques secondes quand l'acidité, elle, reste : un déglaçage suivi d'une réduction ne donne plus que du mordant. Une cuillerée dans le jus de repos, une noisette de beurre, et c'est tout."},
pairs:["duck","foie-de-veau","shallot","butter","raspberry","beetroot"],
svg:'<path class="f2 sf" d="M43 22h10v12l7 11v33q0 4-4 4H40q-4 0-4-4V45l7-11z"/><path class="s" d="M36 54h24"/><circle class="f1 sf" cx="68" cy="68" r="9"/><path class="s" d="M68 59v-6"/><path class="s" d="M63 65a3 3 0 006 0M63 72a3 3 0 006 0"/>'},

{id:"verjus-rouge",cat:"cellar",rare:true,name:{en:"Red verjuice",fr:"Verjus rouge"},latin:"Vitis vinifera",
origin:{en:"Périgord & the Loire",fr:"Périgord et Val de Loire"},season:[],
flavor:["sour","fruity","tangy"],
story:{en:"Before lemons were cheap, verjuice was the everyday acid of French kitchens, and the red kind came from the grappillons - the second, late bunches a vine sets that never ripen and were otherwise dropped on the ground. Because it is never fermented it has no alcohol and no acetic sting: its acidity is tartaric and malic, which is why it does not fight the wine at the table.",
fr:"Avant que le citron ne devienne bon marché, le verjus était l’acide quotidien des cuisines françaises, et le rouge venait des grappillons - ces secondes grappes tardives que la vigne noue et qui ne mûrissent jamais, autrefois laissées au sol. Comme il n’est jamais fermenté, il n’a ni alcool ni piquant acétique : son acidité est tartrique et malique, et c’est pourquoi il ne se bat pas avec le vin à table."},
tip:{en:"It reduces without turning sharp, so deglaze game or duck with it neat and let it fall by half before the stock goes in, with no sugar to correct it. In a vinaigrette work at one part to two of oil rather than the one to three a vinegar takes, since it is roughly half as acidic.",
fr:"Il réduit sans devenir agressif : déglacez le gibier ou le canard au verjus pur et laissez tomber de moitié avant d’ajouter le fond, sans sucre pour corriger. En vinaigrette, comptez une part pour deux d’huile plutôt qu’une pour trois comme avec un vinaigre, puisqu’il est environ deux fois moins acide."},
pairs:["duck","venison","pigeon","redcurrant","foie-gras","beetroot","shallot","cherry"],
svg:'<path class="f2 sf" d="M48 28q10 0 12 8t-2 14q-2 12-10 20-8-8-10-20t-2-14 12-8z"/><path class="s" d="M36 42h24M40 56h16M48 28v42"/><path class="f1 sf" d="M48 26q10-12 20-6-6 12-20 6z"/><path class="s" d="M48 26v-8"/>'},

{id:"rhum-agricole",cat:"cellar",name:{en:"Rhum agricole",fr:"Rhum agricole"},latin:"Saccharum officinarum",
origin:{en:"Martinique & Guadeloupe",fr:"Martinique et Guadeloupe"},season:[],
flavor:["grassy","fruity","warm","briny"],
story:{en:"Cane juice begins fermenting on its own within hours of pressing, so an agricole distillery runs only during the harvest and stands idle the rest of the year - molasses, by contrast, keeps indefinitely, which is why most of the world's rum is made from it. Martinique's rhum has held an appellation of origin since 1996, the only one of its kind for a rum.",
fr:"Le jus de canne se met à fermenter tout seul dans les heures qui suivent le pressage : une distillerie agricole ne tourne donc qu’en campagne et chôme le reste de l’année - la mélasse, elle, se garde indéfiniment, et c’est pourquoi la plus grande part des rhums du monde en est tirée. Le rhum de Martinique porte une appellation d’origine depuis 1996, la seule de ce genre pour un rhum."},
tip:{en:"It is grassy and high-toned, so it goes in at the end: a spoonful into a fruit macerate or a ti-punch, never into a pastry syrup, which is dark rum's job. To flambe bananas, take it at 50 percent or more - the 40 percent bottling will not catch cleanly.",
fr:"Il est vert et haut de ton : il se met à la fin - une cuillerée dans une macération de fruits ou dans un ti-punch, jamais dans un sirop de pâtisserie, qui revient au rhum brun. Pour flamber des bananes, prenez-le à 50 degrés ou plus : à 40, il prend mal."},
pairs:["lime","banana","pineapple","mango","coconut","passion-fruit","ginger","vanilla"],
svg:'<path class="f2 sf" d="M30 78l6-56 8 1-6 55z"/><path class="s" d="M31 64h8M33 50h8M35 36h8"/><path class="f2 sf" d="M52 78l8-52 8 2-8 50z"/><path class="s" d="M53 64h9M56 50h9M59 36h9"/><path class="f1 sf" d="M44 24q14-10 24-4-12 10-24 4z"/>'},

{id:"rivesaltes-ambre",cat:"cellar",rare:true,name:{en:"Rivesaltes ambré",fr:"Rivesaltes ambré"},latin:"Vitis vinifera 'Grenache blanc'",
origin:{en:"Rivesaltes, Roussillon",fr:"Rivesaltes, Roussillon"},season:[],
flavor:["sweet","nutty","honeyed","fruity"],
story:{en:"Rivesaltes is the largest vin doux naturel appellation in France, and ambré is its white face: Grenache blanc and Macabeu, muted with spirit and then held at least two years in deliberately oxidative conditions, often in demijohns left outdoors. What comes out smells of dried apricot, hazelnut and candied peel, with none of the red-fruit weight of its Grenache noir neighbours.",
fr:"Rivesaltes est la plus vaste appellation de vin doux naturel de France, et l’ambré en est le visage blanc : grenache blanc et macabeu, mutés puis élevés au moins deux ans en milieu volontairement oxydatif, souvent en bonbonnes dehors. Il en sort un vin d’abricot sec, de noisette et d’écorce confite, sans rien du poids de fruit rouge de ses voisins en grenache noir."},
tip:{en:"Serve it cool but not cold, around 12 °C; straight from the refrigerator the candied-peel aromatics flatten out. In a sauce for poultry, reduce it with shallot alone — it carries enough sugar that anything else added will read as jam.",
fr:"Servez-le frais mais non glacé, vers 12 °C : sorti du réfrigérateur, il perd ses notes d’écorce confite. En sauce pour une volaille, réduisez-le avec de l’échalote seule — il a déjà assez de sucre pour que tout ajout vire à la confiture."},
pairs:["foie-gras","apricot","hazelnut","poularde","peach","orange"],
svg:'<path class="f1 sf" d="M34 30h28q2 16-14 24-16-8-14-24z"/><path class="s" d="M48 54v14M38 70h20"/><circle class="f2 sf" cx="70" cy="44" r="11"/><path class="s" d="M70 33v22"/>'},

{id:"ruby-port",cat:"cellar",name:{en:"Ruby port",fr:"Porto ruby"},latin:"Vitis vinifera 'Touriga Nacional'",
origin:{en:"Douro valley, Portugal",fr:"Vallée du Douro, Portugal"},season:[],
flavor:["sweet","fruity","rich","warm"],
story:{en:"Ruby is held in vats large enough that almost no air reaches the wine, then bottled young — the opposite intention to tawny, which is left in small casks precisely so that it oxidises. What it brings a sauce is colour and grip: anthocyanin and tannin from Touriga Nacional skins, trodden in the best lodges still by foot in granite lagares.",
fr:"Le ruby vieillit dans des cuves assez grandes pour que presque aucun air n’atteigne le vin, puis part en bouteille jeune — l’intention exactement inverse du tawny, laissé en petits fûts précisément pour qu’il s’oxyde. Ce qu’il apporte à une sauce, c’est la couleur et la mâche : anthocyanes et tanins de peaux de touriga nacional, foulées dans les meilleures maisons encore au pied, en lagares de granit."},
tip:{en:"Reduce it by two-thirds on its own before it meets the stock; added late it stays sweet and raw. A bay leaf and a strip of orange in the reduction keep it from reading as jam against game.",
fr:"Réduisez-le des deux tiers à part, avant de le joindre au fond : ajouté tard, il reste sucré et cru. Une feuille de laurier et un zeste d’orange dans la réduction l’empêchent de virer à la confiture sur le gibier."},
pairs:["venison","fig","blue-cheese","black-pepper","cherry","orange"],
svg:'<path class="f3 sf" d="M32 26h22v12q0 12-11 15-11-3-11-15z"/><path class="s" d="M43 53v14M35 69h16"/><path class="f2 sf" d="M68 34q8 6 8 16t-8 12q-8-2-8-12t8-16z"/><path class="s" d="M68 34v-6M60 52h16"/>'},

{id:"madeira-sercial",cat:"cellar",name:{en:"Sercial Madeira",fr:"Madère Sercial"},latin:"Vitis vinifera 'Esgana Cão'",
origin:{en:"Madeira, Portugal",fr:"Madère, Portugal"},season:[],
flavor:["sour","briny","nutty"],
story:{en:"Casks shipped to the Indies as ballast came back better than they left, so Madeira's growers reproduced the tropical crossing on land: estufagem, months of gentle heat that cook the wine and leave it nearly indestructible. Sercial is the driest of the noble grapes, known on the island as Esgana Cão, dog-strangler, for an acidity that scrapes the mouth clean.",
fr:"Les fûts partis aux Indes comme lest revenaient meilleurs qu’à l’aller ; les vignerons de Madère ont recopié la traversée à terre sous le nom d’estufagem : des mois de chaleur douce qui cuisent le vin et le rendent presque indestructible. Le sercial est le plus sec des cépages nobles, appelé sur l’île Esgana Cão, « étrangle-chien », pour une acidité qui râpe la bouche."},
tip:{en:"It has already been cooked and oxidised, so an open bottle keeps for months standing in a cupboard. Add it to a consommé or a veal jus off the heat, at the very end — boiled hard it loses the saline lift you bought it for.",
fr:"Déjà cuit et oxydé, il se garde des mois debout dans un placard une fois ouvert. Ajoutez-le au consommé ou au jus de veau hors du feu, à la toute fin : une forte ébullition emporte le tranchant salin qu’on est venu chercher."},
pairs:["beef","mushroom","shallot","black-pepper","quasi-de-veau","bay-leaf"],
svg:'<path class="f1 sf" d="M42 22h12v14l6 10v34a4 4 0 0 1-4 4H40a4 4 0 0 1-4-4V46l6-10z"/><path class="f3 sf" d="M36 56h24v14H36z"/><path class="s" d="M66 38q6 4 0 8t0 8"/><path class="s" d="M74 38q6 4 0 8t0 8"/>'},

{id:"shanxi-vinegar",cat:"cellar",rare:true,name:{en:"Shanxi aged vinegar",fr:"Vinaigre noir du Shanxi"},latin:"Sorghum bicolor",
origin:{en:"Qingxu, Shanxi",fr:"Qingxu, Shanxi (Chine)"},season:[],
flavor:["sour","smoky","umami","pungent"],
story:{en:"After fermenting on sorghum, barley and pea, the solid mash is smoked in sealed jars for several days — that is where the colour and the burnt edge come from, not from any added caramel. The raw vinegar then ages outdoors by a rule of two seasons: evaporate under the summer sun, lift the ice off in winter, and what stays behind is thicker and sharper every year.",
fr:"Après fermentation sur sorgho, orge et pois, la drêche solide est fumée plusieurs jours en jarres closes : c'est de là que viennent la couleur et l'amertume grillée, non d'un caramel ajouté. Le vinaigre jeune vieillit ensuite dehors selon une règle de deux saisons : s'évaporer au soleil d'été, se laisser retirer sa glace en hiver. Ce qui reste s'épaissit et s'aiguise chaque année."},
tip:{en:"It is drier and far more pungent than Chinkiang, so a straight swap into a sweet Shanghai braise tastes thin — add a pinch of rock sugar if you substitute. On dumplings and cold noodles use it neat, with nothing but slivered garlic.",
fr:"Plus sec et bien plus piquant que le Chinkiang : si vous le substituez dans un braisé shanghaien, ajoutez une pincée de sucre candi, sinon le plat paraîtra maigre. Sur les raviolis et les nouilles froides, servez-le pur, avec seulement de l'ail émincé."},
pairs:["garlic","ginger","soy-sauce","chili-crisp","pork","cucumber"],
svg:'<path class="f2 sf" d="M34 42q-4 12-4 20 0 14 18 14t18-14q0-8-4-20z"/><path class="f1 sf" d="M32 40q16-8 32 0l-3 5H35z"/><path class="s" d="M33 41q15 5 30 0"/><path class="s" d="M48 26q7-5 2-10M58 28q7-6 2-11"/>'},

{id:"sweet-vermouth",cat:"cellar",name:{en:"Sweet red vermouth",fr:"Vermouth rouge"},latin:"Artemisia absinthium",
origin:{en:"Turin, Piedmont",fr:"Turin, Piémont"},season:[],
flavor:["sweet","bitter","warm","herbal"],
story:{en:"Antonio Benedetto Carpano is credited with the first sweet vermouth, made in Turin in 1786 by sweetening and spicing a white wine for a court that found wormwood tonics too austere. The German root of the name — Wermut, wormwood — survives even though the modern bottle leans on cinchona bark, vanilla and burnt-sugar caramel for its bitterness and its colour.",
fr:"On attribue à Antonio Benedetto Carpano le premier vermouth doux, à Turin en 1786 : un vin blanc sucré et épicé pour une cour qui trouvait les toniques à l’absinthe trop austères. La racine allemande du nom — Wermut, l’absinthe — a survécu, alors que la bouteille moderne doit son amertume et sa couleur à l’écorce de quinquina, à la vanille et au caramel."},
tip:{en:"Add it at the start of a braise and let it reduce with the stock; poured over a finished sauce it tastes raw and medicinal. Once open it oxidises like any wine — refrigerate and finish it within a month.",
fr:"Versez-le en début de braisage et laissez-le réduire avec le fond ; ajouté en fin de cuisson, il reste cru et médicinal. Une fois ouverte, la bouteille s’oxyde comme un vin : au froid, et finie dans le mois."},
pairs:["beef-cheek","orange","juniper","bay-leaf","dark-chocolate","shallot"],
svg:'<path class="f2 sf" d="M27 33h42a21 19 0 0 1-42 0z"/><path class="s" d="M48 52v16"/><path class="s" d="M36 70q12 4 24 0"/><path class="s" d="M60 26a7 7 0 1 0 4 9"/>'},

{id:"tawny-port",cat:"cellar",luxe:true,name:{en:"Tawny port",fr:"Porto tawny"},latin:"Vitis vinifera 'Touriga Nacional'",
origin:{en:"Vila Nova de Gaia, Portugal",fr:"Vila Nova de Gaia, Portugal"},season:[],
flavor:["sweet","nutty","rich","toasty"],
story:{en:"The ten, twenty or forty years on a tawny label is the average age of the blend, not a vintage — the house holds parcels in small casks and marries young wine into old to keep the style constant. Decades of that slow oxidation drop the colour out and put walnut, caramel and dried apricot in its place.",
fr:"Les dix, vingt ou quarante ans d’une étiquette de tawny désignent l’âge moyen de l’assemblage, non un millésime : la maison garde des lots en petits fûts et marie du vin jeune à du vieux pour tenir le style. Des décennies de cette oxydation lente font tomber la couleur et installent à sa place la noix, le caramel et l’abricot sec."},
tip:{en:"It is already oxidised, so an opened bottle holds a month or more in the fridge. Add it at the end of a veal or mushroom jus, off the heat — its aromatics are the finish, not the base.",
fr:"Déjà oxydé, il tient un mois ou plus au réfrigérateur une fois ouvert. Ajoutez-le en fin de course à un jus de veau ou de champignons, hors du feu : ses arômes sont la finition, pas la base."},
pairs:["foie-gras","walnut","mushroom","dried-apricot","blue-cheese","quasi-de-veau"],
svg:'<path class="f1 sf" d="M40 34h16l9 33a6 6 0 0 1-6 8H37a6 6 0 0 1-6-8z"/><path class="f3 sf" d="M43 22h10v12H43z"/><circle class="f2 sf" cx="48" cy="18" r="6"/><circle class="f2 sf" cx="74" cy="36" r="9"/><path class="s" d="M74 27v18M66 33q8 6 16 0"/>'},

{id:"umeshu",cat:"cellar",name:{en:"Umeshu",fr:"Umeshu"},latin:"Prunus mume",
origin:{en:"Wakayama and across Japan",fr:"Wakayama et tout le Japon"},season:[],
flavor:["sour","sweet","fruity","nutty"],
story:{en:"Home brewing is illegal in Japan, but steeping fruit in a spirit of at least twenty percent is expressly allowed - which is why nearly every household made umeshu and almost none made beer. The almond note is the stone's doing: amygdalin in the kernels yields benzaldehyde as the fruit sits in the jar.",
fr:"Le brassage domestique est interdit au Japon, mais la macération de fruits dans un alcool titrant au moins vingt pour cent est expressément autorisée - d’où une maison sur deux qui faisait son umeshu et presque aucune sa bière. La note d’amande vient du noyau : l’amygdaline des amandons donne du benzaldéhyde pendant que le fruit repose dans le bocal."},
tip:{en:"Green ume are not eaten raw, and the steeping needs three months at the very least - a year is better, and the jar only improves. To deglaze pork or duck, a splash off the heat reduced by half needs no added sugar at all.",
fr:"Les ume verts ne se mangent pas crus, et la macération demande trois mois au minimum - une année vaut mieux, le bocal ne fait que gagner. Pour déglacer un porc ou un canard, un trait hors du feu réduit de moitié se passe entièrement de sucre."},
pairs:["pork","duck","shiso","ginger","soy-sauce","apricot","honey","plum"],
svg:'<path class="f1 sf" d="M30 34h36v34a8 8 0 0 1-8 8H38a8 8 0 0 1-8-8z"/><path class="f3 sf" d="M26 26h44v8H26z"/><circle class="f2 sf" cx="42" cy="52" r="8"/><circle class="f2 sf" cx="58" cy="63" r="6"/><path class="s" d="M42 44v16M58 57v12"/>'},

{id:"vincotto",cat:"cellar",rare:true,name:{en:"Vincotto",fr:"Vincotto"},latin:"Vitis vinifera 'Negroamaro'",
origin:{en:"Puglia, Italy",fr:"Pouilles, Italie"},season:[],
flavor:["sweet","sour","woody","rich"],
story:{en:"The name says cooked wine, but nothing is fermented first: late-picked Negroamaro and Primitivo are pressed and the must is boiled down, then left in wood for years. In Puglia the pot traditionally went on the night of the harvest and the must was taken down by four fifths, which is why the result tastes of tannin and fig rather than of caramel.",
fr:"Le nom dit vin cuit, mais rien n’est fermenté au départ : le negroamaro et le primitivo de fin de récolte sont pressés et le moût réduit à l’ébullition, puis laissé des années sous bois. En Pouilles, la marmite se mettait traditionnellement en route le soir des vendanges et le moût tombait des quatre cinquièmes : d’où un goût de tanin et de figue plutôt que de caramel."},
tip:{en:"Use it where you would reach for balsamic but expect more grip: a teaspoon over grilled lamb, pecorino or roasted onions once they are off the fire. It scorches easily, so keep it out of a hot pan and mount it into a warm sauce instead.",
fr:"Employez-le là où vous prendriez du balsamique, mais attendez-vous à plus d’accroche : une cuillère à café sur un agneau grillé, un pecorino ou des oignons rôtis, hors du feu. Il brûle vite : tenez-le à l’écart d’une poêle chaude et montez-le plutôt dans une sauce tiède."},
pairs:["lamb","pecorino","fig","walnut","ricotta","eggplant","olive-oil","orange"],
svg:'<path class="f3 sf" d="M42 34h10v10q8 6 8 16v14q0 4-4 4H38q-4 0-4-4V60q0-10 8-16z"/><path class="f2 sf" d="M43 26h8v8h-8z"/><path class="s" d="M51 30q16 2 18 18M34 66h26"/><circle class="dot" cx="69" cy="54" r="3"/>'},

{id:"white-port",cat:"cellar",name:{en:"White port",fr:"Porto blanc"},latin:"Vitis vinifera 'Malvasia Fina'",
origin:{en:"Douro valley, Portugal",fr:"Vallée du Douro, Portugal"},season:[],
flavor:["citrus","nutty","warm"],
story:{en:"White port is fortified exactly like the red — spirit into fermenting must — but from Douro whites such as Malvasia Fina and Gouveio, and it is bottled dry to off-dry rather than sweet. In the Douro itself almost none of it is drunk neat: the summer drink is porto tónico, half white port, half tonic, over ice with a strip of lemon.",
fr:"Le porto blanc est muté exactement comme le rouge — l’alcool dans le moût en fermentation — mais à partir de cépages blancs du Douro comme la malvasia fina et le gouveio, et il est mis en bouteille de sec à demi-sec. Sur place, on ne le boit presque jamais pur : la boisson d’été est le porto tónico, moitié porto blanc, moitié tonic, sur glace avec un zeste de citron."},
tip:{en:"Buy the bottle labelled seco or extra dry, and use it where a red port would stain: chicken livers, sole, a shellfish butter. Deglaze while the pan is still fierce so the alcohol goes and the citrus stays.",
fr:"Prenez la bouteille marquée seco ou extra dry, et servez-vous-en là où un porto rouge tacherait : foies de volaille, sole, beurre de crustacés. Déglacez sur feu vif pour chasser l’alcool et garder l’agrume."},
pairs:["foie-de-volaille","dover-sole","shrimp","butter","lemon","shallot"],
svg:'<path class="f1 sf" d="M30 26h28l-3 48H33z"/><path class="s" d="M31 38h26"/><circle class="s" cx="70" cy="36" r="10"/><path class="s" d="M70 26v20M60 36h20"/>'}
]);
