window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"almond",cat:"nuts",name:{en:"Almond",fr:"Amande"},latin:"Prunus amygdalus",
origin:{en:"Central & Western Asia",fr:"Asie centrale & occidentale"},season:[],
flavor:["nutty","sweet","milky"],
story:{en:"The almond tree flowers before it leafs — a white promise in bare February orchards that van Gogh painted for his newborn nephew. Sugared almonds have marked weddings since Roman times: bitterness coated in sweetness, like marriage, says the joke.",
fr:"L’amandier fleurit avant de feuiller — une promesse blanche dans les vergers nus de février, que van Gogh peignit pour son neveu nouveau-né. Les dragées marquent les noces depuis Rome : de l’amer enrobé de sucre, comme le mariage, dit la plaisanterie."},
tip:{en:"Toast them always — raw almonds are only a rumour of themselves. Ground with sugar, they become frangipane, the soul of French tarts.",
fr:"Torréfiez-les toujours — l’amande crue n’est qu’une rumeur d’elle-même. Moulue avec du sucre, elle devient la frangipane, âme des tartes françaises."},
pairs:["peach","raspberry","dark-chocolate","honey","cherry","saffron"],
svg:'<path class="f2 sf" d="M48 30q14 14 12 30-1 14-12 14t-12-14q-2-16 12-30z"/><path class="dot" d="M43 50a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M50 44a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M50 58a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M43 62a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/>'},

{id:"brazil-nut",cat:"nuts",name:{en:"Brazil nut",fr:"Noix du Brésil"},latin:"Bertholletia excelsa",
origin:{en:"Amazon basin",fr:"Bassin amazonien"},season:[],
flavor:["creamy","nutty","earthy","rich"],
story:{en:"It cannot be farmed — the tree depends on a single orchid bee for pollination and a large rodent, the agouti, to open its cannonball pods. Every Brazil nut sold has been gathered from wild forest, which makes the trade a genuine argument for keeping it standing.",
fr:"Elle ne peut être cultivée — l’arbre dépend d’une seule abeille des orchidées pour sa pollinisation et d’un gros rongeur, l’agouti, pour ouvrir ses capsules en boulet de canon. Toute noix du Brésil vendue a été ramassée en forêt sauvage, ce qui fait du commerce un vrai argument pour la laisser debout."},
tip:{en:"One nut can carry more than a day's selenium. That is a real limit, not a health-food claim — do not eat handfuls.",
fr:"Une seule noix peut porter plus d’une journée de sélénium. C’est une limite réelle, non un argument diététique — n’en mangez pas des poignées."},
pairs:["dark-chocolate","honey","coffee","vanilla","cream","banana","coconut-milk","date"],
svg:'<path class="f1 sf" d="M36 38l16 4 6 26-18 8-8-24z"/><path class="s" d="M40 46l12 18"/>'},

{id:"cashew",cat:"nuts",name:{en:"Cashew",fr:"Noix de cajou"},latin:"Anacardium occidentale",
origin:{en:"Northeast Brazil",fr:"Nord-est du Brésil"},season:[],
flavor:["sweet","creamy","nutty","buttery"],
story:{en:"It grows hanging beneath a fleshy false fruit, and its shell contains a caustic oil related to poison ivy — which is why cashews are never sold in the shell and why shelling them by hand is genuinely hazardous work.",
fr:"Elle pousse suspendue sous un faux-fruit charnu, et sa coque contient une huile caustique apparentée au sumac vénéneux — d’où des noix jamais vendues en coque et un décorticage manuel réellement dangereux."},
tip:{en:"Soaked and blended it makes a cream that behaves like dairy. It is the base of half the vegan sauces that actually work.",
fr:"Trempée et mixée elle donne une crème qui se comporte comme un laitage. C’est la base de la moitié des sauces véganes qui fonctionnent vraiment."},
pairs:["coconut-milk","chili","lime","cilantro","ginger","garlic","curry-leaf","honey"],
svg:'<path class="f2 sf" d="M34 50q14-12 24 0t-6 20-22-4 4-16z"/><path class="s" d="M40 56q10 4 14 10"/>'},

{id:"chestnut",cat:"nuts",name:{en:"Chestnut",fr:"Châtaigne"},latin:"Castanea sativa",
origin:{en:"Southern Europe & Asia Minor",fr:"Europe du Sud & Asie Mineure"},season:[10,11,12],
flavor:["sweet","earthy","toasty"],
story:{en:"For centuries, mountain villages from Corsica to the Cévennes lived off the “bread tree”: chestnuts ground into flour when wheat wouldn’t grow. The candied marron glacé turned the peasant staple into a jewel — same nut, different destiny.",
fr:"Des siècles durant, les villages de montagne, de la Corse aux Cévennes, vécurent de « l’arbre à pain » : la châtaigne moulue en farine là où le blé refusait de pousser. Le marron glacé confit changea l’aliment paysan en joyau — même fruit, autre destin."},
tip:{en:"Score a cross before roasting or they explode — every fireside learns this once. Their sweetness loves mushrooms, pork and dark chocolate.",
fr:"Incisez une croix avant de les rôtir, sinon elles explosent — chaque coin du feu l’apprend une fois. Leur douceur aime les champignons, le porc et le chocolat noir."},
pairs:["mushroom","pork","cream","dark-chocolate","honey","sage"],
svg:'<path class="f2 sf" d="M48 30q16 10 16 26 0 12-16 12T32 56q0-16 16-26z"/><path class="f3 sf" d="M38 64q10 6 20 0l-2 6H40z"/><path class="s" d="M48 30v-4"/>'},

{id:"date-paste",cat:"nuts",name:{en:"Date paste",fr:"Pâte de dattes"},latin:"Phoenix dactylifera",
origin:{en:"Middle East & North Africa",fr:"Moyen-Orient & Afrique du Nord"},season:[],
flavor:["sweet","rich","earthy","honeyed"],
story:{en:"The filling of maamoul and of the Iraqi kleicha, and one of the oldest sweeteners in use — Mesopotamian tablets record date syrup as a trade good four thousand years ago, long before cane sugar reached the region.",
fr:"La garniture des maamoul et de la kleicha irakienne, et l’un des plus anciens édulcorants en usage — des tablettes mésopotamiennes mentionnent le sirop de dattes comme marchandise il y a quatre mille ans, bien avant l’arrivée du sucre de canne."},
tip:{en:"Warm it with a spoonful of water and a little butter to make it spreadable. Cold it is unworkable.",
fr:"Réchauffez-la avec une cuillerée d’eau et un peu de beurre pour la rendre étalable. Froide elle est intravaillable."},
pairs:["tahini","cardamom","orange","sesame","cinnamon","walnut","butter","coffee"],
svg:'<path class="f1 sf" d="M32 58q0-16 16-16t16 16-16 14-16-14z"/><path class="s" d="M38 54q10 6 20 0"/>'},

{id:"coconut-flakes",cat:"nuts",name:{en:"Desiccated coconut",fr:"Noix de coco râpée"},latin:"Cocos nucifera",
origin:{en:"Indo-Pacific",fr:"Indo-Pacifique"},season:[],
flavor:["sweet","nutty","creamy","toasty"],
story:{en:"Drying was what let coconut leave the tropics — fresh flesh spoils within days, dried it keeps for a year. The Victorian appetite for coconut cake and macaroons is entirely a consequence of that one process.",
fr:"C’est le séchage qui a permis à la coco de quitter les tropiques — la chair fraîche s’altère en quelques jours, séchée elle se garde un an. L’appétit victorien pour les gâteaux et macarons à la coco découle entièrement de ce seul procédé."},
tip:{en:"Toast it in a dry pan before it goes into anything. Raw desiccated coconut tastes of cardboard.",
fr:"Torréfiez-la à sec avant de l’incorporer. Crue, la coco râpée a un goût de carton."},
pairs:["dark-chocolate","lime","mango","sugar","vanilla","cardamom","pineapple","coconut-milk"],
svg:'<path class="f3 sf" d="M32 52h32v4H32zM30 60h34v4H30zM34 68h28v4H34z"/>'},

{id:"dried-apricot",cat:"nuts",name:{en:"Dried apricot",fr:"Abricot sec"},latin:"Prunus armeniaca",
origin:{en:"Turkey & Central Asia",fr:"Turquie & Asie centrale"},season:[],
flavor:["sweet","sour","fruity","honeyed"],
story:{en:"The bright orange ones are treated with sulphur dioxide to keep the colour; the brown ones are not. The brown are more honeyed and figgy, the orange fresher and more acidic — they are effectively two different ingredients.",
fr:"Les orange vif sont traités au dioxyde de soufre pour garder la couleur ; les bruns ne le sont pas. Les bruns sont plus miellés et figués, les orange plus frais et plus acides — ce sont en pratique deux ingrédients différents."},
tip:{en:"Soak them in warm tea rather than water before they go into a tagine. It plumps them without washing out the flavour.",
fr:"Faites-les gonfler dans du thé tiède plutôt que dans l’eau avant un tajine. Cela les regonfle sans lessiver le goût."},
pairs:["lamb","almond","cinnamon","pistachio","honey","ras-el-hanout","orange","cream"],
svg:'<path class="f2 sf" d="M34 56q0-14 14-14t14 14q0 12-14 14t-14-14z"/><path class="s" d="M40 50q8 6 16 0M40 62q8 4 16 0"/>'},

{id:"dried-cranberry",cat:"nuts",name:{en:"Dried cranberry",fr:"Canneberge séchée"},latin:"Vaccinium macrocarpon",
origin:{en:"North America",fr:"Amérique du Nord"},season:[],
flavor:["sweet","sour","fruity","tangy"],
story:{en:"Almost always sweetened before drying, because an unsweetened dried cranberry is close to inedible — the fruit is far too acidic. Read the label: many are sweetened with apple juice concentrate rather than sugar, and they taste different.",
fr:"Presque toujours sucrée avant séchage, car une canneberge séchée non sucrée est quasi immangeable — le fruit est bien trop acide. Lisez l’étiquette : beaucoup sont sucrées au jus de pomme concentré plutôt qu’au sucre, et le goût diffère."},
tip:{en:"Their acidity cuts fat, which is why they work in a stuffing or a grain salad far better than raisins do.",
fr:"Leur acidité coupe le gras, ce qui les rend bien meilleures qu’un raisin sec dans une farce ou une salade de céréales."},
pairs:["turkey","pecan","orange","wild-rice","goat-cheese","walnut","sage","hazelnut"],
svg:'<ellipse class="f1 sf" cx="42" cy="55" rx="6" ry="5"/><ellipse class="f1 sf" cx="55" cy="58" rx="6" ry="5"/><ellipse class="f1 sf" cx="47" cy="66" rx="6" ry="5"/>'},

{id:"dried-fig",cat:"nuts",name:{en:"Dried fig",fr:"Figue sèche"},latin:"Ficus carica",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["sweet","honeyed","earthy","nutty"],
story:{en:"Figs were being dried in the Jordan valley eleven thousand years ago, and some archaeologists argue the fig was the first plant humans ever cultivated — earlier than wheat, because a cutting will root on its own.",
fr:"On séchait des figues dans la vallée du Jourdain il y a onze mille ans, et certains archéologues soutiennent que le figuier fut la première plante cultivée par l’homme — avant le blé, parce qu’une bouture prend racine seule."},
tip:{en:"The white bloom on the surface is crystallised sugar, not mould. It is a sign of quality rather than a fault.",
fr:"Le voile blanc en surface est du sucre cristallisé, non une moisissure. C’est un signe de qualité plutôt qu’un défaut."},
pairs:["walnut","blue-cheese","honey","fennel-seed","almond","prosciutto","orange","red-wine-vinegar"],
svg:'<path class="f1 sf" d="M48 36q14 10 14 22t-14 14-14-14 14-22z"/><path class="s" d="M48 36v-6"/><path class="s" d="M40 56q8 6 16 0"/>'},

{id:"flax",cat:"nuts",name:{en:"Flaxseed",fr:"Graine de lin"},latin:"Linum usitatissimum",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["nutty","earthy","mild","toasty"],
story:{en:"One of the first plants humans domesticated, and for most of history it was grown for linen rather than food — the Latin name means most useful. Dyed flax fibres found in a Georgian cave are thirty thousand years old.",
fr:"L’une des premières plantes domestiquées, et pendant presque toute l’histoire cultivée pour le lin plutôt que pour l’alimentation — le nom latin signifie très utile. Des fibres de lin teintes trouvées dans une grotte géorgienne ont trente mille ans."},
tip:{en:"Whole seeds pass straight through you. Grind them just before use — ground flax goes rancid within days.",
fr:"Les graines entières traversent sans être digérées. Moulez-les juste avant emploi — le lin moulu rancit en quelques jours."},
pairs:["oats","yogurt","honey","flour-complete","raisin","banana","cinnamon","sunflower-seed"],
svg:'<ellipse class="f1 sf" cx="40" cy="52" rx="7" ry="4"/><ellipse class="f1 sf" cx="55" cy="58" rx="7" ry="4"/><ellipse class="f1 sf" cx="45" cy="66" rx="7" ry="4"/>'},

{id:"goji",cat:"nuts",name:{en:"Goji berry",fr:"Baie de goji"},latin:"Lycium barbarum",
origin:{en:"Ningxia, China",fr:"Ningxia, Chine"},season:[],
flavor:["sweet","sour","earthy","musky"],
story:{en:"Grown in China for centuries as a medicinal ingredient in soups and teas rather than a snack — it is in the same family as the tomato and the aubergine. Its Western career as a superfood dates only to the early 2000s.",
fr:"Cultivée en Chine depuis des siècles comme ingrédient médicinal des soupes et des thés plutôt que comme en-cas — elle appartient à la même famille que la tomate et l’aubergine. Sa carrière occidentale de superaliment ne date que du début des années 2000."},
tip:{en:"Simmer them in a broth or a congee the way Chinese cooks do. Eaten dry by the handful they are leathery and sour.",
fr:"Faites-les mijoter dans un bouillon ou un congee comme les cuisiniers chinois. Sèches à la poignée elles sont coriaces et acides."},
pairs:["ginger","rice","goat-cheese","honey","chicken","jasmine-rice","sesame","almond"],
svg:'<ellipse class="f1 sf" cx="42" cy="54" rx="5" ry="8"/><ellipse class="f1 sf" cx="54" cy="58" rx="5" ry="8"/><ellipse class="f1 sf" cx="47" cy="68" rx="5" ry="8"/>'},

{id:"hazelnut",cat:"nuts",name:{en:"Hazelnut",fr:"Noisette"},latin:"Corylus avellana",
origin:{en:"Europe & Asia Minor",fr:"Europe & Asie Mineure"},season:[9,10],
flavor:["nutty","sweet","toasty","buttery"],
story:{en:"In Celtic legend, nine hazel trees dropped their nuts of wisdom into a sacred pool, and the salmon who ate them knew everything. Later, Napoleon’s blockade cut Turin off from cocoa — chocolatiers stretched what little they had with local hazelnuts, and gianduja was born of scarcity.",
fr:"Dans la légende celte, neuf noisetiers laissaient tomber leurs noisettes de sagesse dans un bassin sacré, et le saumon qui les mangea sut toutes choses. Plus tard, le blocus napoléonien priva Turin de cacao — les chocolatiers étirèrent le peu qu’ils avaient avec les noisettes locales, et le gianduja naquit de la pénurie."},
tip:{en:"Roast, then rub in a tea towel: the papery skins fall away and the bitterness goes with them.",
fr:"Torréfiez, puis frottez-les dans un torchon : les peaux s’envolent et l’amertume part avec."},
pairs:["dark-chocolate","coffee","pear","butter","chanterelle"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="15"/><path class="f3 sf" d="M34 48q2-14 14-14t14 14q-6 4-14 4t-14-4z"/><path class="s" d="M48 34v-6"/>'},

{id:"hemp-seed",cat:"nuts",name:{en:"Hemp seed",fr:"Graine de chanvre"},latin:"Cannabis sativa",
origin:{en:"Central Asia",fr:"Asie centrale"},season:[],
flavor:["nutty","grassy","creamy","mild"],
story:{en:"The same species as the drug plant but a different cultivar, bred for fibre and seed and containing almost no THC. France is the largest hemp producer in Europe and has grown it continuously since the age of sail, when it made rope.",
fr:"La même espèce que la plante à drogue mais un autre cultivar, sélectionné pour la fibre et la graine et presque dépourvu de THC. La France est le premier producteur européen de chanvre et en cultive sans interruption depuis la marine à voile, où il faisait les cordages."},
tip:{en:"Never cook it — the oil oxidises fast and turns fishy. Scatter it raw over a finished dish.",
fr:"Ne la cuisez jamais — l’huile s’oxyde vite et prend un goût de poisson. Parsemez-la crue sur un plat terminé."},
pairs:["yogurt","honey","oats","banana","flax","spinach","olive-oil","lemon"],
svg:'<circle class="f2 sf" cx="41" cy="54" r="5"/><circle class="f2 sf" cx="54" cy="52" r="5"/><circle class="f2 sf" cx="47" cy="65" r="5"/><circle class="f2 sf" cx="59" cy="63" r="4"/>'},

{id:"macadamia",cat:"nuts",name:{en:"Macadamia",fr:"Noix de macadamia"},latin:"Macadamia integrifolia",
origin:{en:"Queensland, Australia",fr:"Queensland, Australie"},season:[],
flavor:["buttery","sweet","creamy","nutty"],
story:{en:"The hardest shell of any commercial nut — it takes about three hundred atmospheres to crack, which is why it is the most expensive nut in the world. It is also toxic to dogs, for reasons nobody has fully explained.",
fr:"La coque la plus dure de toutes les noix commerciales — il faut environ trois cents atmosphères pour la briser, d’où la noix la plus chère au monde. Elle est aussi toxique pour les chiens, sans que l’on sache pleinement pourquoi."},
tip:{en:"It is over seventy per cent fat, so it burns fast. Toast it at a low temperature and watch it constantly.",
fr:"Elle est à plus de soixante-dix pour cent de gras, donc elle brûle vite. Torréfiez-la à basse température en la surveillant sans cesse."},
pairs:["cream","coffee","vanilla","honey","coconut-milk","dark-chocolate","lime","maple-syrup"],
svg:'<circle class="f3 sf" cx="42" cy="54" r="11"/><circle class="f3 sf" cx="58" cy="60" r="9"/><path class="s" d="M36 50q6-4 12 0"/>'},

{id:"peanut",cat:"nuts",name:{en:"Peanut",fr:"Cacahuète"},latin:"Arachis hypogaea",
origin:{en:"South America",fr:"Amérique du Sud"},season:[],
flavor:["nutty","sweet","rich","toasty"],
story:{en:"Not a nut at all but a legume that buries its own pods underground. Born in South America, carried to Africa, it came back to the Americas in slave-ship provisions; George Washington Carver later catalogued three hundred uses for it, rebuilding Southern farming on its back.",
fr:"Pas une noix, mais une légumineuse qui enterre elle-même ses gousses. Née en Amérique du Sud, portée en Afrique, elle revint aux Amériques dans les cales des navires ; George Washington Carver en recensa plus tard trois cents usages, rebâtissant l’agriculture du Sud sur son dos."},
tip:{en:"Ground with a little of its own oil, it becomes sauce for half of West African and Southeast Asian cooking — chili and lime are its best friends.",
fr:"Broyée avec un peu de sa propre huile, elle devient sauce pour la moitié des cuisines ouest-africaines et d’Asie du Sud-Est — piment et citron vert sont ses meilleurs amis."},
pairs:["chili","coconut-milk","soy-sauce","dark-chocolate","ginger"],
svg:'<path class="f1 sf" d="M42 32q10-2 12 6 1 4 5 6 8 4 6 14-2 12-14 10-8-1-10-8-1-4-5-7-6-5-2-13 3-7 8-8z"/><path class="s" d="M40 42q6 4 6 10M52 44q4 4 4 9"/>'},

{id:"pecan",cat:"nuts",name:{en:"Pecan",fr:"Noix de pécan"},latin:"Carya illinoinensis",
origin:{en:"Mississippi valley",fr:"Vallée du Mississippi"},season:[10,11,12],
flavor:["sweet","buttery","toasty","rich"],
story:{en:"A native North American nut that indigenous peoples gathered long before any orchard existed — the word is Algonquian, for a nut requiring a stone to crack. Jefferson planted them at Monticello and sent trees to Washington.",
fr:"Une noix d’Amérique du Nord que les peuples autochtones récoltaient bien avant tout verger — le mot est algonquin et désigne une noix qu’il faut casser avec une pierre. Jefferson en planta à Monticello et en envoya des plants à Washington."},
tip:{en:"Sweeter and softer than a walnut, with none of its bitterness. They are not interchangeable in baking despite the resemblance.",
fr:"Plus sucrée et plus tendre que la noix, sans son amertume. Elles ne sont pas interchangeables en pâtisserie malgré la ressemblance."},
pairs:["maple-syrup","butter","vanilla","dark-chocolate","honey","cream","cinnamon","coffee"],
svg:'<ellipse class="f1 sf" cx="48" cy="56" rx="12" ry="18"/><path class="s" d="M48 38v36M42 44q4 12 0 24M54 44q-4 12 0 24"/>'},

{id:"pine-nut",cat:"nuts",name:{en:"Pine nut",fr:"Pignon de pin"},latin:"Pinus pinea",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["nutty","buttery","delicate"],
story:{en:"Roman legionaries carried pine nuts as marching rations, and jars of them were found preserved in the ashes of Pompeii. Each stone pine takes decades to bear cones — patience, shelled one kernel at a time.",
fr:"Les légionnaires romains emportaient des pignons comme ration de marche, et l’on en retrouva des jarres conservées sous les cendres de Pompéi. Chaque pin parasol met des décennies à donner ses cônes — de la patience, décortiquée pignon par pignon."},
tip:{en:"They burn treacherously fast: toast them in a dry pan and never take your eyes off. Golden is perfect; brown is bitter.",
fr:"Ils brûlent traîtreusement vite : torréfiez-les à sec sans les quitter des yeux. Dorés, c’est parfait ; bruns, c’est amer."},
pairs:["basil","parmesan","spinach","zucchini","fig","honey"],
svg:'<path class="f1 sf" d="M42 42q-4-8 3-12 5 4 3 12-3 3-6 0zM54 46q-4-8 3-12 5 4 3 12-3 3-6 0zM40 60q-4-8 3-12 5 4 3 12-3 3-6 0zM52 62q-4-8 3-12 5 4 3 12-3 3-6 0z"/>'},

{id:"pistachio",cat:"nuts",name:{en:"Pistachio",fr:"Pistache"},latin:"Pistacia vera",
origin:{en:"Persia & Central Asia",fr:"Perse & Asie centrale"},season:[],
flavor:["nutty","sweet","grassy"],
story:{en:"The Queen of Sheba is said to have claimed her land’s whole pistachio harvest for her court. In Persia, lovers met under pistachio trees on moonlit nights: hearing the shells crack open was a promise of good fortune.",
fr:"La reine de Saba, dit-on, réservait à sa cour toute la récolte de pistaches de son royaume. En Perse, les amoureux se retrouvaient sous les pistachiers les nuits de lune : entendre les coques s’ouvrir en craquant promettait bonne fortune."},
tip:{en:"The greener the kernel, the finer the pistachio — Sicily’s Bronte and Iran’s best are almost emerald. Crushed, they finish anything creamy with style.",
fr:"Plus le cerneau est vert, plus la pistache est fine — celles de Bronte en Sicile et les meilleures d’Iran sont presque émeraude. Concassée, elle finit avec panache tout ce qui est crémeux."},
pairs:["cherry","dark-chocolate","honey","yogurt","cardamom"],
svg:'<path class="f1 sf" d="M36 50q0-14 12-14t12 14q0 8-6 12l-6-10-6 10q-6-4-6-12z"/><path class="f3 sf" d="M44 52q4-6 8 0 2 8-4 14-6-6-4-14z"/>'},

{id:"prune",cat:"nuts",name:{en:"Prune",fr:"Pruneau"},latin:"Prunus domestica",
origin:{en:"Agen, southwest France",fr:"Agen, Sud-Ouest"},season:[],
flavor:["sweet","rich","earthy","fruity"],
story:{en:"The pruneau d'Agen comes from the ente plum, grafted from a variety crusaders brought back from Syria. It is dried in ovens rather than the sun, and Lot-et-Garonne still lives on it.",
fr:"Le pruneau d’Agen vient de la prune d’ente, greffée d’une variété rapportée de Syrie par les croisés. Il sèche au four plutôt qu’au soleil, et le Lot-et-Garonne en vit encore."},
tip:{en:"It belongs with pork and rabbit as much as with dessert. Southwest France has always treated it as a savoury ingredient.",
fr:"Il va avec le porc et le lapin autant qu’avec le dessert. Le Sud-Ouest l’a toujours traité comme un ingrédient salé."},
pairs:["rabbit","thyme","pork","cream","bay-leaf","dark-chocolate","orange","lard"],
svg:'<path class="f1 sf" d="M34 56q0-16 14-16t14 16-14 16-14-16z"/><path class="s" d="M40 48q8 8 16 2M42 64q6 4 12 0"/>'},

{id:"pumpkin-seed",cat:"nuts",name:{en:"Pumpkin seed",fr:"Graine de courge"},latin:"Cucurbita pepo",
origin:{en:"Mesoamerica",fr:"Mésoamérique"},season:[],
flavor:["nutty","toasty","earthy","grassy"],
story:{en:"Styria grows a mutant squash whose seeds have no husk at all — a single natural mutation recorded in the 1870s, which is why Austrian pepitas are dark green and naked while everyone else's need shelling.",
fr:"La Styrie cultive une courge mutante dont les graines n’ont aucune coque — une mutation naturelle unique consignée dans les années 1870, d’où des pepitas autrichiennes vert sombre et nues quand celles des autres doivent être décortiquées."},
tip:{en:"Toast them until they pop and puff. That is the moment they are done, and it happens fast.",
fr:"Torréfiez-les jusqu’à ce qu’elles éclatent et gonflent. C’est l’instant où elles sont prêtes, et il arrive vite."},
pairs:["pumpkin-seed-oil","chili","lime","salt","honey","cilantro","cumin","sunflower-seed"],
svg:'<ellipse class="f2 sf" cx="42" cy="54" rx="7" ry="10"/><ellipse class="f2 sf" cx="56" cy="60" rx="7" ry="10"/><path class="s" d="M38 50q4-3 8 0M52 56q4-3 8 0"/>'},

{id:"raisin",cat:"nuts",name:{en:"Raisin",fr:"Raisin sec"},latin:"Vitis vinifera",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["sweet","fruity","honeyed","earthy"],
story:{en:"Grapes that dried on the vine were almost certainly the first dried fruit anyone ate, since it happens without human help. Corinth gave its name to the currant, Smyrna to the sultana — the varieties are named after their ports.",
fr:"Des raisins séchés sur pied furent presque certainement le premier fruit sec consommé, puisque cela se produit sans intervention humaine. Corinthe a donné son nom au raisin de Corinthe, Smyrne à la sultanine — les variétés portent le nom de leurs ports."},
tip:{en:"Plump them in warm liquid — rum, tea, wine — for twenty minutes before baking. Dry, they steal moisture from the crumb.",
fr:"Faites-les gonfler vingt minutes dans un liquide tiède — rhum, thé, vin — avant cuisson. Secs, ils volent l’humidité de la mie."},
pairs:["cinnamon","almond","flour-t55","pine-nut","swiss-chard","butter","honey","orange"],
svg:'<circle class="f1 sf" cx="41" cy="52" r="6"/><circle class="f1 sf" cx="55" cy="55" r="6"/><circle class="f1 sf" cx="46" cy="64" r="6"/><circle class="f1 sf" cx="58" cy="66" r="5"/><path class="s" d="M38 48q4-3 8 0"/>'},

{id:"sesame",cat:"nuts",name:{en:"Sesame",fr:"Sésame"},latin:"Sesamum indicum",
origin:{en:"India & Africa",fr:"Inde & Afrique"},season:[],
flavor:["nutty","toasty","rich"],
story:{en:"“Open sesame!” — the magic words of Ali Baba echo the plant itself: ripe sesame pods burst open at a touch, scattering their seeds. It is likely the oldest oil crop on Earth, pressed in Mesopotamia four thousand years ago.",
fr:"« Sésame, ouvre-toi ! » — la formule magique d’Ali Baba fait écho à la plante elle-même : mûres, les capsules de sésame éclatent au moindre contact, dispersant leurs graines. C’est sans doute la plus ancienne culture oléagineuse du monde, pressée en Mésopotamie il y a quatre mille ans."},
tip:{en:"Toasted and ground with salt, it becomes gomasio; toasted and pressed, tahini. Raw seeds on bread are decoration — toasted, they are flavour.",
fr:"Torréfié et broyé avec du sel, il devient gomasio ; torréfié et pressé, tahini. Cru sur le pain, il décore — torréfié, il parfume."},
pairs:["chickpeas","honey","soy-sauce","ginger","eggplant","rice","tuna"],
svg:'<path class="f2 sf" d="M40 42q3-6 6 0 2 5-3 8-5-3-3-8zM52 38q3-6 6 0 2 5-3 8-5-3-3-8zM34 56q3-6 6 0 2 5-3 8-5-3-3-8zM48 54q3-6 6 0 2 5-3 8-5-3-3-8zM60 52q3-6 6 0 2 5-3 8-5-3-3-8zM42 68q3-6 6 0 2 5-3 8-5-3-3-8z"/>'},

{id:"pine-nut-toasted",cat:"nuts",name:{en:"Stone pine kernel",fr:"Pignon de pin parasol"},latin:"Pinus pinea",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["nutty","resinous","sweet","buttery"],
story:{en:"It takes three years for a stone pine cone to ripen, and the kernels are extracted by hand — which is why Mediterranean pine nuts cost several times what Chinese ones do. Some Chinese species cause a metallic taste distortion lasting days.",
fr:"Il faut trois ans à une pomme de pin parasol pour mûrir, et les pignons s’extraient à la main — d’où un prix plusieurs fois supérieur à celui des pignons chinois. Certaines espèces chinoises provoquent une distorsion métallique du goût durant plusieurs jours."},
tip:{en:"Check the origin on the packet. Pinus pinea is the Mediterranean one and the only one worth paying for.",
fr:"Vérifiez l’origine sur le paquet. Pinus pinea est le méditerranéen, et le seul qui mérite son prix."},
pairs:["basil","parmesan","raisin","swiss-chard","olive-oil","garlic","spinach","lemon"],
svg:'<path class="f3 sf" d="M42 40q6-4 8 4t-2 24-8-4 2-24z"/><path class="f3 sf" d="M54 50q5-3 6 4t-2 18-6-3z"/>'},

{id:"sunflower-seed",cat:"nuts",name:{en:"Sunflower seed",fr:"Graine de tournesol"},latin:"Helianthus annuus",
origin:{en:"North America",fr:"Amérique du Nord"},season:[],
flavor:["nutty","toasty","mild","earthy"],
story:{en:"Domesticated in what is now the United States some four thousand years ago, then taken to Russia, industrialised, and sold back to America as a Russian crop. The head follows the sun only while growing; a mature flower faces east and stops.",
fr:"Domestiquée dans l’actuelle Amérique du Nord il y a quelque quatre mille ans, puis emportée en Russie, industrialisée et revendue à l’Amérique comme culture russe. Le capitule ne suit le soleil que pendant la croissance ; une fleur mûre regarde l’est et s’immobilise."},
tip:{en:"Toast them and they stop tasting like birdseed. Untoasted they contribute texture and very little else.",
fr:"Torréfiées, elles cessent d’avoir un goût de graine pour oiseaux. Crues elles n’apportent que de la texture et guère plus."},
pairs:["honey","flour-t65","yogurt","raisin","oats","dark-chocolate","salt","pumpkin-seed"],
svg:'<ellipse class="f1 sf" cx="42" cy="54" rx="5" ry="9"/><ellipse class="f1 sf" cx="54" cy="58" rx="5" ry="9"/><ellipse class="f1 sf" cx="47" cy="68" rx="5" ry="9"/>'},

{id:"walnut",cat:"nuts",name:{en:"Walnut",fr:"Noix"},latin:"Juglans regia",
origin:{en:"Persia & Central Asia",fr:"Perse & Asie centrale"},season:[9,10,11],
flavor:["nutty","bitter","rich","toasty"],
story:{en:"Romans called it Jovis glans — “Jupiter’s acorn”, food fit for a god. Because its kernel looks like a brain, medieval doctors prescribed it for head ailments; the doctrine was nonsense, but the walnut forgave them and fed them anyway.",
fr:"Les Romains l’appelaient Jovis glans — « gland de Jupiter », nourriture digne d’un dieu. Parce que son cerneau ressemble à un cerveau, les médecins médiévaux la prescrivaient pour les maux de tête ; la doctrine était absurde, mais la noix leur pardonna et les nourrit quand même."},
tip:{en:"Buy them in the shell — shelled kernels go rancid fast. Ten seconds in a hot pan and they taste twice as much of themselves.",
fr:"Achetez-les en coque — les cerneaux nus rancissent vite. Dix secondes dans une poêle chaude et elles ont deux fois plus de goût."},
pairs:["blue-cheese","pear","fig","beetroot","honey","coffee","grape","celery"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="18"/><path class="s" d="M48 36v32M42 42q-4 10 0 20M54 42q4 10 0 20"/>'}
]);
