// Herbs
window.INGREDIENTS = (window.INGREDIENTS || []).concat([

{id:"basil",cat:"herbs",name:{en:"Basil",fr:"Basilic"},latin:"Ocimum basilicum",
origin:{en:"India",fr:"Inde"},season:[6,7,8,9],
flavor:["herbal","anise","peppery","fresh"],
story:{en:"Its name comes from basileus — Greek for king — and in India its cousin tulsi is holy enough to be planted in temple courtyards. A royal and sacred plant that ended up, gloriously, on tomatoes.",
fr:"Son nom vient de basileus — « roi » en grec — et en Inde son cousin le tulsi est assez sacré pour pousser dans les cours des temples. Une plante royale et sainte qui a fini, glorieusement, sur des tomates."},
tip:{en:"Heat murders it: tear the leaves by hand and add them off the flame, at the very last moment.",
fr:"La chaleur l’assassine : déchirez les feuilles à la main et ajoutez-les hors du feu, au tout dernier moment."},
pairs:["tomato","mozzarella","garlic","lemon","strawberry","pine-nut","zucchini","peach"],
svg:'<path class="s" d="M48 78V34"/><path class="f2 sf" d="M46 44q-14-2-14-14 14-2 16 10zM50 44q14-2 14-14-14-2-16 10zM46 60q-12-2-12-12 12-2 14 9zM50 60q12-2 12-12-12-2-14 9z"/><path class="f3 sf" d="M48 34q-4-8 0-12 4 4 0 12z"/>'},

{id:"parsley",cat:"herbs",name:{en:"Parsley",fr:"Persil"},latin:"Petroselinum crispum",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[3,4,5,6,7,8,9,10],
flavor:["grassy","fresh","peppery"],
story:{en:"Greeks planted parsley on graves and crowned victors with it at the Nemean games — an herb of both mourning and triumph. French cooking made it a daily workhorse: half the savoury dishes of the repertoire end in a flurry of chopped parsley.",
fr:"Les Grecs plantaient le persil sur les tombes et en couronnaient les vainqueurs aux jeux de Némée — herbe de deuil et de triomphe à la fois. La cuisine française en fit un ouvrier du quotidien : la moitié du répertoire salé se termine sous une pluie de persil haché."},
tip:{en:"Flat-leaf for flavour, curly for looks. The stems carry more taste than the leaves — tie them into every stock.",
fr:"Le plat pour le goût, le frisé pour l’œil. Les tiges ont plus de goût que les feuilles — glissez-les dans tous les bouillons."},
pairs:["garlic","lemon","mushroom","cod","chickpeas","egg","potato"],
svg:'<path class="s" d="M48 78V40M38 62q10-4 10-14M58 62q-10-4-10-14"/><path class="f2 sf" d="M34 44a7 7 0 108-6 7 7 0 10-8 6zM54 38a7 7 0 108 6 7 7 0 10-8-6zM43 30a6 6 0 1010 0 6 6 0 10-10 0z"/>'},

{id:"cilantro",cat:"herbs",name:{en:"Cilantro / Coriander",fr:"Coriandre"},latin:"Coriandrum sativum",
origin:{en:"Eastern Mediterranean",fr:"Méditerranée orientale"},season:[5,6,7,8,9],
flavor:["fresh","citrus","herbal","pungent"],
story:{en:"Coriander seeds were found in Tutankhamun’s tomb, making it one of the oldest herbs humans carry with them. A single gene decides its fate on your tongue: for most it sings of citrus, for the unlucky few it tastes of soap.",
fr:"Des graines de coriandre furent trouvées dans la tombe de Toutânkhamon — l’une des plus vieilles herbes que l’humanité emporte avec elle. Un seul gène décide de son destin sur votre langue : pour la plupart elle chante l’agrume, pour quelques malchanceux elle a un goût de savon."},
tip:{en:"Leaves and seeds are two different ingredients: the leaf is a finishing herb, the seed a warm spice. Never swap one for the other.",
fr:"Feuilles et graines sont deux ingrédients différents : la feuille se cisèle au dernier moment, la graine est une épice chaude. Ne troquez jamais l’une pour l’autre."},
pairs:["chili","coconut-milk","ginger","mango","cumin","shrimp","rice"],
svg:'<path class="s" d="M48 78V38M40 60q8-2 8-10M56 60q-8-2-8-10"/><path class="f1 sf" d="M40 40q-10 0-10-9 8-3 12 4zM56 40q10 0 10-9-8-3-12 4zM44 30q-2-8 4-10 6 2 4 10-4 3-8 0z"/>'},

{id:"mint",cat:"herbs",name:{en:"Mint",fr:"Menthe"},latin:"Mentha spicata",
origin:{en:"Mediterranean & Near East",fr:"Méditerranée & Proche-Orient"},season:[5,6,7,8,9],
flavor:["fresh","sweet","herbal"],
story:{en:"Minthe was a nymph whom jealous Persephone crushed underfoot; Hades could only give her a scent that rises whenever she is stepped on. From Marrakech tea to Vietnamese tables, no herb refreshes more of the planet.",
fr:"Minthé était une nymphe que Perséphone, jalouse, écrasa sous son pied ; Hadès ne put que lui offrir un parfum qui s’élève chaque fois qu’on la foule. Du thé de Marrakech aux tables vietnamiennes, aucune herbe ne rafraîchit davantage la planète."},
tip:{en:"It spreads like gossip in a garden — grow it in a pot. Bruise the leaves, don’t chop them, for drinks.",
fr:"Au jardin, elle s’étend comme une rumeur — cultivez-la en pot. Pour les boissons, froissez les feuilles au lieu de les ciseler."},
pairs:["strawberry","yogurt","lamb","dark-chocolate","zucchini","mango","pomegranate"],
svg:'<path class="s" d="M48 78V30"/><path class="f2 sf" d="M46 40q-12 2-14-10 12-4 15 6zM50 40q12 2 14-10-12-4-15 6zM46 56q-10 2-12-8 10-4 13 5zM50 56q10 2 12-8-10-4-13 5z"/><path class="s" d="M34 32l-2-3M62 32l2-3"/>'},

{id:"rosemary",cat:"herbs",name:{en:"Rosemary",fr:"Romarin"},latin:"Salvia rosmarinus",
origin:{en:"Mediterranean scrubland",fr:"Garrigue méditerranéenne"},season:[],
flavor:["woody","herbal","peppery"],
story:{en:"Its name means “dew of the sea”, for the coastal cliffs it clings to. Greek students wore rosemary crowns while studying, believing it strengthened memory — Ophelia agreed: “rosemary, that’s for remembrance.”",
fr:"Son nom signifie « rosée de mer », pour les falaises côtières où il s’accroche. Les étudiants grecs portaient des couronnes de romarin en étudiant, persuadés qu’il fortifiait la mémoire — Ophélie confirme : « le romarin, c’est pour le souvenir »."},
tip:{en:"Its needles survive long cooking where soft herbs die — throw a sprig under roasting potatoes or lamb and remove it before serving.",
fr:"Ses aiguilles survivent aux longues cuissons où les herbes tendres meurent — glissez une branche sous des pommes de terre ou un agneau au four, retirez-la avant de servir."},
pairs:["lamb","potato","garlic","chicken","olive-oil","honey","lemon"],
svg:'<path class="s" d="M48 78V26"/><path class="s" d="M48 68l-10-6M48 68l10-6M48 58l-11-6M48 58l11-6M48 48l-10-6M48 48l10-6M48 38l-8-5M48 38l8-5"/>'},

{id:"thyme",cat:"herbs",name:{en:"Thyme",fr:"Thym"},latin:"Thymus vulgaris",
origin:{en:"Mediterranean hills",fr:"Collines méditerranéennes"},season:[],
flavor:["herbal","woody","warm"],
story:{en:"Medieval ladies embroidered a bee hovering over thyme on the scarves of their knights — the herb meant courage. Egyptians used it for embalming; cooks use it for nearly everything that simmers.",
fr:"Les dames du Moyen Âge brodaient une abeille survolant un brin de thym sur l’écharpe de leur chevalier — l’herbe signifiait le courage. Les Égyptiens l’utilisaient pour embaumer ; les cuisiniers, pour presque tout ce qui mijote."},
tip:{en:"Strip the leaves by sliding your fingers down the stem against the grain. Whole sprigs can simmer and be fished out like bay leaves.",
fr:"Effeuillez-le en glissant les doigts à rebrousse-tige. Les branches entières peuvent mijoter puis se repêcher comme le laurier."},
pairs:["onion","chicken","mushroom","carrot","honey","lemon","white-beans","duck"],
svg:'<path class="s" d="M48 78Q44 50 48 26"/><path class="f2" d="M44 64a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M50 56a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M41 50a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M49 42a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M43 36a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0M46 28a2.4 2.4 0 104.8 0 2.4 2.4 0 10-4.8 0"/>'},

{id:"sage",cat:"herbs",name:{en:"Sage",fr:"Sauge"},latin:"Salvia officinalis",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["herbal","peppery","earthy"],
story:{en:"Salvia comes from salvare, “to save” — the medieval school of Salerno asked: “Why should a man die who has sage in his garden?” In the kitchen it saved something humbler: pork, butter and beans from blandness.",
fr:"Salvia vient de salvare, « sauver » — l’école de Salerne demandait au Moyen Âge : « Pourquoi mourrait-il, celui qui a de la sauge au jardin ? » En cuisine, elle sauva plus modestement le porc, le beurre et les haricots de la fadeur."},
tip:{en:"Fry whole leaves in butter until crisp: the butter turns nutty and the leaves become savoury chips.",
fr:"Faites frire les feuilles entières au beurre jusqu’à croustiller : le beurre prend un goût de noisette et les feuilles deviennent des chips salées."},
pairs:["pork","butter","onion","apple","white-beans","chestnut"],
svg:'<path class="s" d="M48 78V32"/><path class="f2 sf" d="M46 50q-14 4-18-8 12-8 19 3zM50 50q14 4 18-8-12-8-19 3zM46 34q-10 0-12-8 10-4 13 3z"/>'},

{id:"tarragon",cat:"herbs",name:{en:"Tarragon",fr:"Estragon"},latin:"Artemisia dracunculus",
origin:{en:"Central Asia & Siberia",fr:"Asie centrale & Sibérie"},season:[5,6,7,8,9],
flavor:["anise","herbal","delicate"],
story:{en:"Its name means “little dragon” — medieval healers claimed it cured serpent bites, and its roots do coil like one. France adopted the orphan of the steppes and built béarnaise sauce around its quiet anise breath.",
fr:"Son nom signifie « petit dragon » — les guérisseurs médiévaux le disaient efficace contre les morsures de serpent, et ses racines s’enroulent comme tel. La France adopta cet orphelin des steppes et bâtit la béarnaise autour de son discret souffle anisé."},
tip:{en:"It overwhelms fast: a few leaves perfume a whole chicken. With eggs and mustard, it is the most French of accents.",
fr:"Il domine vite : quelques feuilles parfument un poulet entier. Avec des œufs et de la moutarde, c’est le plus français des accents."},
pairs:["chicken","egg","mustard","mushroom","cream","lemon"],
svg:'<path class="s" d="M48 78V28"/><path class="f1 sf" d="M48 66q-14-2-16-10 12-2 16 6zM48 66q14-2 16-10-12-2-16 6zM48 50q-12-2-14-9 11-2 14 5zM48 50q12-2 14-9-11-2-14 5zM48 36q-9-2-10-8 9-1 10 5zM48 36q9-2 10-8-9-1-10 5z"/>'},

{id:"dill",cat:"herbs",name:{en:"Dill",fr:"Aneth"},latin:"Anethum graveolens",
origin:{en:"Western Asia",fr:"Asie occidentale"},season:[5,6,7,8,9],
flavor:["anise","fresh","grassy"],
story:{en:"Old Norse dilla means “to soothe” — the herb once calmed babies’ colic. The North never let it go: gravlax, that Scandinavian invention of salmon “buried” in salt and dill, remains its masterpiece.",
fr:"Le vieux norrois dilla signifie « apaiser » — l’herbe calmait jadis les coliques des nourrissons. Le Nord ne l’a jamais lâchée : le gravlax, cette invention scandinave de saumon « enterré » sous sel et aneth, reste son chef-d’œuvre."},
tip:{en:"Dill hates heat and long waits: snip it over the dish at the table, especially anything with yogurt, eggs or fish.",
fr:"L’aneth déteste la chaleur et l’attente : ciselez-le sur le plat au moment de servir, surtout sur le yaourt, les œufs ou le poisson."},
pairs:["salmon","beetroot","yogurt","potato","egg","mustard"],
svg:'<path class="s" d="M48 78V40"/><path class="s" d="M48 40l-12-8M48 40l12-8M48 40v-14M48 40l-6-12M48 40l6-12"/><path class="dot" d="M34 31a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M40 27a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M46.3 24a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M52.6 27a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0M58.6 31a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0"/>'},

{id:"chives",cat:"herbs",name:{en:"Chives",fr:"Ciboulette"},latin:"Allium schoenoprasum",
origin:{en:"Europe & Asia",fr:"Europe & Asie"},season:[4,5,6,7,8,9],
flavor:["mild","fresh","pungent"],
story:{en:"The gentlest member of the onion clan, gathered wild in Europe since the Middle Ages, when bunches were hung against evil spells. It offers the allium idea — without the allium consequences.",
fr:"Le membre le plus doux du clan des oignons, cueilli sauvage en Europe depuis le Moyen Âge, où l’on en suspendait des bouquets contre les mauvais sorts. Elle offre l’idée de l’oignon — sans les conséquences de l’oignon."},
tip:{en:"Scissors beat the knife: snip it directly over eggs, potatoes or cream, and its purple pompom flowers are edible too.",
fr:"Les ciseaux battent le couteau : taillez-la directement sur les œufs, les pommes de terre ou la crème ; ses fleurs en pompons mauves se mangent aussi."},
pairs:["egg","potato","cream","scallop","asparagus","cod","yogurt"],
svg:'<path class="s" d="M40 78Q38 46 36 30M46 78Q46 44 46 26M52 78Q54 48 56 30M58 78Q60 52 62 38"/><path class="f3" d="M34 28a3 3 0 106 0 3 3 0 10-6 0M44 24a3 3 0 106 0 3 3 0 10-6 0M54 28a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"bay-leaf",cat:"herbs",name:{en:"Bay leaf",fr:"Laurier"},latin:"Laurus nobilis",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["woody","herbal","warm"],
story:{en:"Daphne became a laurel tree to escape Apollo, and the god wore its leaves ever after — hence crowned poets “laureates” and every “baccalauréat”. In the pot, it works the same quiet magic: present everywhere, seen nowhere, always fished out at the end.",
fr:"Daphné se changea en laurier pour échapper à Apollon, et le dieu en porta les feuilles à jamais — d’où les poètes « lauréats » et le « baccalauréat ». Dans la marmite, même magie discrète : présent partout, visible nulle part, toujours repêché à la fin."},
tip:{en:"One leaf per pot is plenty — two is a statement, three is a mistake. Dried is often better than fresh, and it needs time to speak.",
fr:"Une feuille par marmite suffit — deux, c’est une déclaration ; trois, une erreur. Sec, il est souvent meilleur que frais, et il lui faut du temps pour parler."},
pairs:["onion","tomato","lentils","white-beans","beef","potato"],
svg:'<path class="f2 sf" d="M48 24q16 14 12 34-3 16-12 20-9-4-12-20-4-20 12-34z"/><path class="s" d="M48 30v42M48 40l-6-3M48 40l6-3M48 52l-7-3M48 52l7-3M48 64l-6-3M48 64l6-3"/>'},

{id:"oregano",cat:"herbs",name:{en:"Oregano",fr:"Origan"},latin:"Origanum vulgare",
origin:{en:"Mediterranean mountains",fr:"Montagnes méditerranéennes"},season:[6,7,8,9],
flavor:["herbal","peppery","warm"],
story:{en:"Greek for “joy of the mountain”, it perfumed hillsides long before pizza existed. American soldiers came home from Italy in 1945 asking for “the pizza herb” — and oregano sales rose five-thousand percent in a decade.",
fr:"« Joie de la montagne » en grec, il parfumait les collines bien avant l’existence de la pizza. Les soldats américains revinrent d’Italie en 1945 en réclamant « l’herbe à pizza » — et les ventes d’origan bondirent de cinq mille pour cent en une décennie."},
tip:{en:"One of the rare herbs that is stronger dried than fresh. Bloom it in warm oil to release its perfume before it touches the dish.",
fr:"L’une des rares herbes plus puissante sèche que fraîche. Réveillez-le dans une huile tiède pour libérer son parfum avant qu’il ne touche le plat."},
pairs:["tomato","olive-oil","lemon","chicken","eggplant","olive","mozzarella"],
svg:'<path class="s" d="M48 78V30M40 62q8-2 8-10M56 62q-8-2-8-10M42 44q6-2 6-8M54 44q-6-2-6-8"/><path class="f2" d="M36 60a3 3 0 106 0 3 3 0 10-6 0M54 60a3 3 0 106 0 3 3 0 10-6 0M38 42a3 3 0 106 0 3 3 0 10-6 0M52 42a3 3 0 106 0 3 3 0 10-6 0M45 28a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"marjoram",cat:"herbs",name:{en:"Marjoram",fr:"Marjolaine"},latin:"Origanum majorana",
origin:{en:"Cyprus & southern Turkey",fr:"Chypre & sud de la Turquie"},season:[6,7,8,9],
flavor:["herbal","floral","sweet","warm"],
story:{en:"Oregano's gentler sister — the same genus, but sweeter and more floral where oregano is peppery and blunt. Greeks planted it on graves for a peaceful sleep, and the Romans made wedding crowns from it.",
fr:"La sœur plus douce de l’origan — même genre, mais plus sucrée et plus florale là où l’origan est poivré et franc. Les Grecs en plantaient sur les tombes pour un sommeil paisible, et les Romains en faisaient des couronnes de mariage."},
tip:{en:"Add it at the end, never at the start. Unlike oregano it is fragile and long cooking flattens it completely.",
fr:"Ajoutez-la à la fin, jamais au début. Contrairement à l’origan elle est fragile et une cuisson longue l’efface entièrement."},
pairs:["tomato","olive-oil","lamb","garlic","mozzarella","zucchini","lemon","thyme"],
svg:'<path class="s" d="M48 76V34"/><circle class="f2 sf" cx="41" cy="44" r="4"/><circle class="f2 sf" cx="55" cy="48" r="4"/><circle class="f2 sf" cx="42" cy="58" r="4"/><circle class="f2 sf" cx="55" cy="62" r="4"/>'},

{id:"savory",cat:"herbs",name:{en:"Savory",fr:"Sarriette"},latin:"Satureja hortensis",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[6,7,8,9],
flavor:["peppery","herbal","warm","resinous"],
story:{en:"Germany calls it Bohnenkraut, the bean herb, because it does two things at once: it tastes right with beans and it genuinely helps digest them. Provence puts it on goat's cheese, where it is called pèbre d'ail, garlic pepper.",
fr:"L’Allemagne l’appelle Bohnenkraut, l’herbe aux haricots, parce qu’elle fait deux choses à la fois : elle va avec les haricots et aide réellement à les digérer. La Provence la met sur le chèvre, où on la nomme pèbre d’ail, poivre d’ail."},
tip:{en:"Put a sprig in the water with any dried bean or lentil. It is the oldest trick in European bean cookery and it works.",
fr:"Mettez une branche dans l’eau de tout haricot ou lentille sec. C’est la plus vieille astuce de la cuisine européenne des légumineuses, et elle fonctionne."},
pairs:["white-beans","goat-cheese","fava-bean","lamb","olive-oil","thyme","green-bean","garlic"],
svg:'<path class="s" d="M48 76V32"/><path class="f2 sf" d="M46 40q-10-2-12 4 8 6 12 0zM50 50q10-2 12 4-8 6-12 0zM46 60q-10-2-12 4 8 6 12 0z"/>'},

{id:"curry-leaf",cat:"herbs",name:{en:"Curry leaf",fr:"Feuille de curry"},latin:"Murraya koenigii",
origin:{en:"India & Sri Lanka",fr:"Inde & Sri Lanka"},season:[],
flavor:["citrus","herbal","warm","resinous"],
story:{en:"Nothing to do with curry powder, which contains none of it. The leaf is thrown into hot oil at the very start of a South Indian dish, where it crackles and perfumes the fat — a step called tempering, and the dish is unrecognisable without it.",
fr:"Rien à voir avec le curry en poudre, qui n’en contient pas. La feuille est jetée dans l’huile chaude au tout début d’un plat sud-indien, où elle crépite et parfume le gras — une étape appelée tempérage, sans laquelle le plat est méconnaissable."},
tip:{en:"Dried curry leaves are close to worthless. Buy them fresh and freeze what you do not use — they freeze perfectly.",
fr:"Les feuilles de curry séchées ne valent presque rien. Achetez-les fraîches et congelez le reste — elles se congèlent parfaitement."},
pairs:["mustard-seed","coconut-milk","turmeric","ghee","chili","red-lentil","ginger","lime"],
svg:'<path class="s" d="M48 74V30"/><path class="f2 sf" d="M46 38q-12-4-14 2 10 8 14 2zM50 46q12-4 14 2-10 8-14 2zM46 54q-12-4-14 2 10 8 14 2zM50 62q12-4 14 2-10 8-14 2z"/>'},

{id:"kaffir-lime-leaf",cat:"herbs",name:{en:"Makrut lime leaf",fr:"Feuille de combava"},latin:"Citrus hystrix",
origin:{en:"Southeast Asia",fr:"Asie du Sud-Est"},season:[],
flavor:["citrus","floral","fresh","resinous"],
story:{en:"The leaf grows in a distinctive double lobe, one leaf apparently joined to another end to end. It carries far more perfume than the fruit, which is knobbly, dry and yields almost no juice — here the tree's value is entirely in the foliage.",
fr:"La feuille pousse en double lobe caractéristique, comme deux feuilles jointes bout à bout. Elle porte bien plus de parfum que le fruit, bosselé, sec et presque sans jus — ici toute la valeur de l’arbre est dans le feuillage."},
tip:{en:"Tear the leaf along the central rib before it goes in. Whole and intact it releases almost nothing.",
fr:"Déchirez la feuille le long de la nervure centrale avant de l’ajouter. Entière et intacte elle ne libère presque rien."},
pairs:["lemongrass","coconut-milk","galangal","chili","fish-sauce","lime","cilantro","ginger"],
svg:'<path class="f2 sf" d="M48 30q10 8 10 18t-10 10-10-10 10-18z"/><path class="f2 sf" d="M48 58q9 7 9 16t-9 8-9-8 9-16z"/><path class="s" d="M48 30v52"/>'},

{id:"epazote",cat:"herbs",name:{en:"Epazote",fr:"Épazote"},latin:"Dysphania ambrosioides",
origin:{en:"Mexico & Central America",fr:"Mexique & Amérique centrale"},season:[6,7,8,9],
flavor:["pungent","bitter","herbal","resinous"],
story:{en:"Mexican cooks put it in black beans for the same reason Germans put savory in theirs — it is held to reduce the gas. Its taste is genuinely divisive: descriptions run from petrol to turpentine to oregano, and all three are fair.",
fr:"Les cuisiniers mexicains la mettent dans les haricots noirs pour la même raison que les Allemands y mettent de la sarriette — on lui prête un effet anti-flatulence. Son goût divise franchement : les descriptions vont de l’essence à la térébenthine en passant par l’origan, et les trois sont justes."},
tip:{en:"One sprig for a whole pot, added in the last ten minutes. It is not an herb you scatter generously.",
fr:"Une branche pour toute une casserole, ajoutée dans les dix dernières minutes. Ce n’est pas une herbe que l’on parsème généreusement."},
pairs:["black-bean","chili","corn","onion","garlic","tomatillo","cilantro","lime"],
svg:'<path class="s" d="M48 76V32"/><path class="f1 sf" d="M46 40q-14-2-16 6 12 8 16 0zM50 54q14-2 16 6-12 8-16 0z"/>'},

{id:"borage",cat:"herbs",name:{en:"Borage",fr:"Bourrache"},latin:"Borago officinalis",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[5,6,7,8],
flavor:["fresh","marine","grassy","delicate"],
story:{en:"The leaf tastes startlingly of cucumber and oyster, which is why Ligurians stuff pansotti with it and the English drop the blue star flowers into summer drinks. Roman soldiers took it before battle, believing it gave courage.",
fr:"La feuille a un goût saisissant de concombre et d’huître, d’où les pansotti ligures qu’on en farcit et les fleurs bleues en étoile que les Anglais jettent dans les boissons d’été. Les soldats romains en prenaient avant la bataille, la croyant source de courage."},
tip:{en:"The leaves are covered in prickly hairs that soften only with cooking or fine chopping. Use the flowers raw and the leaves cooked.",
fr:"Les feuilles sont couvertes de poils piquants qui ne s’assouplissent qu’à la cuisson ou au hachage fin. Fleurs crues, feuilles cuites."},
pairs:["ricotta","cucumber","lemon","olive-oil","parmesan","egg","oyster","cream"],
svg:'<path class="s" d="M48 76V44"/><path class="f2 sf" d="M44 52q-14 0-16-8 12-6 18 4z"/><path class="f3 sf" d="M52 38l4 6 6 1-5 4 2 6-7-4-7 4 2-6-5-4 6-1z"/>'},

{id:"hyssop",cat:"herbs",name:{en:"Hyssop",fr:"Hysope"},latin:"Hyssopus officinalis",
origin:{en:"Southern Europe",fr:"Europe du Sud"},season:[6,7,8,9],
flavor:["bitter","herbal","floral","resinous"],
story:{en:"Named in the Bible and grown in monastery gardens for a thousand years, it fell almost entirely out of cooking — too bitter, too medicinal for modern palates. It survives mainly in Chartreuse and a handful of other monastic liqueurs.",
fr:"Nommée dans la Bible et cultivée mille ans dans les jardins de monastère, elle a presque entièrement quitté la cuisine — trop amère, trop médicinale pour les palais modernes. Elle survit surtout dans la Chartreuse et quelques autres liqueurs monastiques."},
tip:{en:"Treat it like a bitter rather than an herb. A few leaves in a fruit compote or a game sauce, and no more.",
fr:"Traitez-la comme un amer plutôt que comme une herbe. Quelques feuilles dans une compote de fruits ou une sauce de gibier, pas davantage."},
pairs:["apricot","peach","honey","venison","thyme","rosemary","plum","juniper"],
svg:'<path class="s" d="M48 76V32"/><path class="f2 sf" d="M46 38q-8 0-9 5 7 5 9 0zM50 48q8 0 9 5-7 5-9 0zM46 58q-8 0-9 5 7 5 9 0z"/><circle class="f3 sf" cx="48" cy="30" r="3"/>'},

{id:"angelica",cat:"herbs",name:{en:"Angelica",fr:"Angélique"},latin:"Angelica archangelica",
origin:{en:"Northern Europe",fr:"Europe du Nord"},season:[5,6,7],
flavor:["sweet","herbal","anise","musky"],
story:{en:"Niort in the Deux-Sèvres has candied its hollow green stems since the eighteenth century, and the town still runs on it. The name comes from a legend that an archangel revealed the plant as a cure during a plague year.",
fr:"Niort, dans les Deux-Sèvres, en confit les tiges creuses depuis le XVIIIe siècle, et la ville en vit encore. Le nom vient d’une légende selon laquelle un archange révéla la plante comme remède durant une année de peste."},
tip:{en:"The candied stem is the usable form for most cooks — dice it into a cake or a fruit compote where you would use citrus peel.",
fr:"La tige confite est la forme utilisable pour la plupart — taillez-la en dés dans un gâteau ou une compote, là où vous mettriez de l’écorce d’agrume."},
pairs:["rhubarb","apple","honey","cream","almond","gooseberry","sugar","juniper"],
svg:'<path class="f3 sf" d="M44 78V38h8v40z"/><path class="s" d="M48 38q-14-4-16-14 14-2 18 10M48 38q14-4 16-14-14-2-18 10"/>'},

{id:"purple-basil",cat:"herbs",name:{en:"Purple basil",fr:"Basilic pourpre"},latin:"Ocimum basilicum var. purpurascens",
origin:{en:"India & Southeast Asia",fr:"Inde & Asie du Sud-Est"},season:[6,7,8,9],
flavor:["anise","herbal","warm","floral"],
story:{en:"More clove and anise than green basil, and considerably tougher-leaved. Its anthocyanins bleed pink into vinegar within minutes, which is why it is grown as much for infusing as for the leaf itself.",
fr:"Plus giroflé et anisé que le basilic vert, et à la feuille nettement plus coriace. Ses anthocyanes rosissent le vinaigre en quelques minutes, d’où une culture autant pour l’infusion que pour la feuille elle-même."},
tip:{en:"It does not make good pesto — the colour turns muddy brown. Use it whole in salads or steep it in vinegar.",
fr:"Il ne fait pas un bon pesto — la couleur vire au brun boueux. Employez-le entier en salade ou faites-le infuser dans du vinaigre."},
pairs:["tomato","white-wine-vinegar","olive-oil","peach","mozzarella","garlic","strawberry","lemon"],
svg:'<path class="s" d="M48 76V38"/><path class="f1 sf" d="M46 44q-14-6-16 2 12 10 16 2zM50 56q14-6 16 2-12 10-16 2z"/>'}

]);
