window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"caviar-naccarii",cat:"seafood",name:{en:"Adriatic sturgeon caviar",fr:"Caviar naccarii"},latin:"Acipenser naccarii",
origin:{en:"Po valley, Lombardy",fr:"Vallée du Pô, Lombardie"},season:[],
flavor:["nutty","milky","briny","delicate"],
story:{en:"The Adriatic sturgeon was fished out of the Po and its tributaries and is now listed as critically endangered in the wild, so every grain sold comes from farms that also raise fingerlings for restocking the river. Its roe carries an almond-milk sweetness no other species gives, which is the only reason the fish had a commercial future at all.",
fr:"L’esturgeon adriatique a disparu du Pô et de ses affluents — l’espèce est classée en danger critique à l’état sauvage, et chaque grain vendu sort d’élevages qui fournissent aussi les alevins de réintroduction. Son œuf porte une douceur d’amande fraîche qu’aucune autre espèce ne donne, et c’est la seule raison pour laquelle le poisson a gardé un avenir commercial."},
tip:{en:"Serve at 8–10 °C on the back of the hand or a nacre spoon; metal turns the almond note metallic within seconds. Keep lemon away from it — the acid erases exactly the sweetness you paid for.",
fr:"Servez-le à 8–10 °C sur le dos de la main ou à la cuillère de nacre : le métal métallise la note d’amande en quelques secondes. Pas de citron — l’acide efface précisément la douceur que vous avez payée."},
pairs:["creme-fraiche","potato","egg","chives","butter","oyster"],
svg:'<ellipse class="f2 sf" cx="48" cy="52" rx="26" ry="19"/><ellipse class="s" cx="48" cy="52" rx="20" ry="13"/><circle class="dot" cx="42" cy="47" r="2.4"/><circle class="dot" cx="53" cy="47" r="2.4"/><circle class="dot" cx="46" cy="56" r="2.4"/><circle class="dot" cx="56" cy="55" r="2.2"/>'},

{id:"anchovy",cat:"seafood",name:{en:"Anchovy",fr:"Anchois"},latin:"Engraulis encrasicolus",
origin:{en:"Mediterranean & Atlantic",fr:"Méditerranée & Atlantique"},season:[],
flavor:["salty","umami","marine","pungent"],
story:{en:"Rome ran on garum — fermented anchovy sauce traded like oil, its factories worth fortunes. The little fish still works undercover: melted into a sauce it disappears entirely, leaving only depth, and people who “hate anchovies” praise the dish.",
fr:"Rome carburait au garum — sauce d’anchois fermentés négociée comme le pétrole, ses fabriques valant des fortunes. Le petit poisson travaille toujours sous couverture : fondu dans une sauce il disparaît entièrement, ne laissant que la profondeur, et ceux qui « détestent les anchois » complimentent le plat."},
tip:{en:"One or two fillets, melted in warm olive oil at the start of a tomato sauce or a lamb braise, is seasoning, not fish. Nobody will know; everybody will notice.",
fr:"Un ou deux filets, fondus dans l’huile tiède au départ d’une sauce tomate ou d’un agneau braisé, c’est de l’assaisonnement, pas du poisson. Personne ne saura ; tout le monde remarquera."},
pairs:["garlic","tomato","capers","olive","lemon","olive-oil"],
svg:'<path class="f3 sf" d="M28 50q12-6 28-5l10-4-2 5 2 5-10-4q-16 1-28 3z"/><path class="f3 sf" d="M34 62q10-5 22-4l8-3-2 4 2 4-8-3q-12 1-22 2z"/><path class="dot" d="M34 48a1.2 1.2 0 102.4 0 1.2 1.2 0 10-2.4 0"/>'},

{id:"foie-de-lotte",cat:"seafood",name:{en:"Ankimo",fr:"Foie de lotte (ankimo)"},latin:"Lophius piscatorius",
origin:{en:"Cold Japanese coastal waters",fr:"Eaux côtières froides du Japon"},season:[11,12,1,2],
flavor:["rich","creamy","marine","umami"],
story:{en:"Japan calls it the foie gras of the sea, and the comparison is anatomical rather than poetic: in cold water the liver can reach a tenth of the fish's weight. Salted, rinsed with sake, rolled in cloth and steamed — ankimo is a preparation, not a cut, and the lean tail it comes from tastes nothing like it.",
fr:"Au Japon on l’appelle le foie gras de la mer, et la comparaison tient à l’anatomie plus qu’à la poésie : par eau froide, le foie atteint le dixième du poids du poisson. Salé, rincé au saké, roulé dans un linge puis cuit à la vapeur — l’ankimo est une préparation, pas un morceau, et la queue maigre dont il vient n’a rien de ce goût."},
tip:{en:"Devein it while the liver is still cold and firm, then salt thirty minutes and rinse with sake before rolling — skip either step and the terrine turns bitter and grainy. Steam thirty minutes, chill overnight, slice with a wetted blade.",
fr:"Dénervez à froid, tant que le foie est ferme, puis salez trente minutes et rincez au saké avant de rouler : sautez l’une des deux étapes et la terrine devient amère et granuleuse. Vapeur trente minutes, une nuit au froid, tranchez à la lame mouillée."},
pairs:["radish","spring-onion","soy-sauce","yuzu","rice-vinegar","chives"],
svg:'<path class="f2 sf" d="M34 38h26a12 12 0 0 1 0 24H34a12 12 0 0 1 0-24z"/><ellipse class="f1 sf" cx="34" cy="50" rx="7" ry="12"/><path class="s" d="M30 45q4 3 8 0M30 55q4-3 8 0"/><path class="s" d="M48 38v24M58 39v22"/>'},

{id:"char",cat:"seafood",name:{en:"Arctic char",fr:"Omble chevalier"},latin:"Salvelinus alpinus",
origin:{en:"Arctic & alpine lakes",fr:"Lacs arctiques & alpins"},season:[6,7,8,9,10],
flavor:["delicate","rich","sweet","marine"],
story:{en:"It lives in the coldest fresh water on Earth, further north than any other freshwater fish, and in the deep alpine lakes of Savoie and Switzerland. Somewhere between salmon and trout in richness, and rarer than either.",
fr:"Il vit dans les eaux douces les plus froides du globe, plus au nord qu’aucun autre poisson d’eau douce, et dans les lacs alpins profonds de Savoie et de Suisse. À mi-chemin du saumon et de la truite pour le gras, et plus rare que l’un comme l’autre."},
tip:{en:"Cook it barely — it is at its best still translucent at the centre. It goes from perfect to chalky in under a minute.",
fr:"Cuisez-le à peine — il est à son meilleur encore translucide au cœur. Il passe du parfait au crayeux en moins d’une minute."},
pairs:["butter","lemon","dill","creme-fraiche","hazelnut","chives","beetroot","horseradish"],
svg:'<path class="f1 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f1 sf" d="M78 56l10-8v16z"/><circle class="dot" cx="38" cy="53" r="1.8"/><circle class="dot" cx="52" cy="57" r="1.8"/>'},

{id:"caviar-baeri",cat:"seafood",name:{en:"Baerii caviar",fr:"Caviar baeri"},latin:"Acipenser baerii",
origin:{en:"Ponds of Aquitaine and Sologne",fr:"Étangs d’Aquitaine et de Sologne"},season:[],
flavor:["buttery","briny","delicate"],
story:{en:"France banned fishing its native Gironde sturgeon in 1982; a decade later the farms restarted with Siberian baerii imported for the purpose, and the Aquitaine caviar trade is entirely built on that substitution. The fish gives roe at around seven years where a beluga needs fifteen, which is why baerii is the caviar a kitchen can afford to put near heat.",
fr:"La France a interdit la pêche de son esturgeon de Gironde en 1982 ; dix ans plus tard, les fermes repartaient avec le baeri sibérien importé pour cela, et tout le caviar d’Aquitaine repose sur cette substitution. Le poisson donne ses œufs vers sept ans quand le béluga en demande quinze : c’est pourquoi le baeri est le caviar qu’une cuisine peut se permettre d’approcher du feu."},
tip:{en:"It is the one caviar to warm: spoon the grains onto a sauce off the heat, below 40 °C, and they hold their shape. Above that they burst and go oily, and no amount of stirring brings them back.",
fr:"C’est le seul caviar à tiédir : posez les grains sur une sauce hors du feu, sous 40 °C, ils tiennent. Au-delà, ils éclatent et graissent, et rien ne les rattrape."},
pairs:["cream","potato","egg","chives","scallop","leek"],
svg:'<ellipse class="f1 sf" cx="40" cy="56" rx="16" ry="11"/><path class="f2 sf" d="M54 50q9-8 16-14-4 9-12 17z"/><path class="s" d="M30 53q9-7 19-2"/><circle class="dot" cx="36" cy="57" r="2.3"/><circle class="dot" cx="44" cy="59" r="2.3"/><circle class="dot" cx="42" cy="51" r="2.3"/>'},

{id:"oursin-bafun",cat:"seafood",name:{en:"Bafun uni",fr:"Oursin bafun"},latin:"Hemicentrotus pulcherrimus",
origin:{en:"Rocky shallows of Japan",fr:"Fonds rocheux du Japon"},season:[6,7,8],
flavor:["umami","briny","marine","sweet"],
story:{en:"The Japanese name means horse-dung urchin, for a flattened, dull shell that sits on the rock like a dropping. Under it are five short tongues of gonad, darker and far denser than the Mediterranean urchin's, tasting closer to caramel than to sea water.",
fr:"Son nom japonais, bafun, veut dire crottin de cheval : la coquille est plate et terne, posée sur la roche comme une bouse. Dessous, cinq langues de gonade courtes, plus sombres et bien plus denses que chez l’oursin de Méditerranée, plus proches du caramel que de l’eau de mer."},
tip:{en:"Buy it in the wooden tray, never loose in brine — the alum used to firm uni in holding water is what makes it taste bitter and metallic. Eat it within a day, at cellar temperature; fridge-cold flattens it.",
fr:"Achetez-le en barquette de bois, jamais au bain de saumure : c’est l’alun qui raffermit l’oursin dans l’eau de maintien qui le rend amer et métallique. À manger dans la journée, à température de cave — glacé, il s’éteint."},
pairs:["rice","nori","soy-sauce","egg","wasabi","scallop"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="20"/><path class="s" d="M48 32V19M28 52H15M68 52h13M34 38l-9-9M62 38l9-9M34 66l-9 9M62 66l9 9"/><path class="f1 sf" d="M39 45q9-6 18 0-3 12-9 14t-9-14z"/><path class="s" d="M48 45v14"/>'},

{id:"brill",cat:"seafood",name:{en:"Brill",fr:"Barbue"},latin:"Scophthalmus rhombus",
origin:{en:"Northeast Atlantic",fr:"Atlantique Nord-Est"},season:[4,5,6,7,8,9],
flavor:["delicate","sweet","marine","rich"],
story:{en:"Turbot's slightly cheaper cousin, and the difference is real but small — brill is softer-fleshed and less firm. Chefs who cannot justify turbot buy brill and rarely mention the substitution, which tells you how close they are.",
fr:"La cousine un peu moins chère du turbot, et la différence est réelle mais mince — la barbue a la chair plus tendre et moins ferme. Les chefs qui ne peuvent justifier le turbot prennent de la barbue et mentionnent rarement l’échange, ce qui dit assez leur proximité."},
tip:{en:"Cook it on the bone. Both flat fish lose most of what makes them worth the money once filleted.",
fr:"Cuisez-la sur l’arête. Les deux poissons plats perdent l’essentiel de ce qui justifie leur prix une fois levés en filets."},
pairs:["butter","shallot","white-wine-vinegar","cream","chives","lemon","mushroom","spinach"],
svg:'<ellipse class="f3 sf" cx="46" cy="56" rx="27" ry="17"/><path class="f3 sf" d="M73 56l11-6v12z"/><circle class="dot" cx="38" cy="52" r="2"/><path class="s" d="M30 56q16 6 34 0"/>'},

{id:"cod",cat:"seafood",name:{en:"Cod",fr:"Cabillaud / Morue"},latin:"Gadus morhua",
origin:{en:"North Atlantic",fr:"Atlantique Nord"},season:[1,2,3,10,11,12],
flavor:["mild","delicate","marine"],
story:{en:"The fish that built nations: Vikings dried it into ship's biscuit, Basques salted it and may have reached America chasing it before Columbus. Wars were fought over it, banks named after it — all for a flaky white fillet.",
fr:"Le poisson qui bâtit des nations : les Vikings le séchaient en biscuit de mer, les Basques le salaient et l’auraient poursuivi jusqu’en Amérique avant Colomb. On lui fit des guerres, on baptisa des bancs en son nom — tout ça pour un filet blanc et feuilleté."},
tip:{en:"Salt the fillets twenty minutes before cooking: the flesh firms and the flakes hold. It carries bold friends — chorizo, capers, saffron — with grace.",
fr:"Salez les filets vingt minutes avant cuisson : la chair se raffermit et les écailles de chair se tiennent. Il porte avec grâce des amis puissants — chorizo, câpres, safran."},
pairs:["potato","leek","olive-oil","garlic","capers","parsley","saffron"],
svg:'<path class="f1 sf" d="M26 54q12-12 32-10l10-6-2 8 2 8-10-6q-20 4-32 6z" transform="translate(0 2)"/><path class="s" d="M30 56q4 4 8 4M40 48q0 8-2 10" transform="translate(0 2)"/><path class="dot" d="M32 52a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0" transform="translate(0 1)"/>'},

{id:"dover-sole",cat:"seafood",luxe:true,name:{en:"Dover sole",fr:"Sole"},latin:"Solea solea",
origin:{en:"English Channel & North Sea",fr:"Manche & mer du Nord"},season:[],
flavor:["delicate","sweet","marine"],
story:{en:"Named for the port that rushed it to London’s tables, it earned immortality in Rouen in 1948: one sole meunière — browned butter, lemon, parsley — struck the young Julia Child as “the most exciting meal of my life” and rerouted American cooking through France.",
fr:"Nommée d’après le port qui la précipitait vers les tables de Londres, elle gagna l’immortalité à Rouen en 1948 : une sole meunière — beurre noisette, citron, persil — frappa la jeune Julia Child comme « le repas le plus exaltant de ma vie » et fit passer la cuisine américaine par la France."},
tip:{en:"Its firm, sweet flesh peels from the bone in four perfect fillets — but cook it whole and skin-on for the true meunière. The pan does the sauce: butter, lemon, and the fond it leaves behind.",
fr:"Sa chair ferme et douce se détache de l’arête en quatre filets parfaits — mais cuisez-la entière pour la vraie meunière. La poêle fait la sauce : beurre, citron, et les sucs qu’elle abandonne."},
pairs:["butter","lemon","parsley","capers"],
svg:'<path class="f1 sf" d="M30 54q6-16 24-16 14 0 12 14-2 16-20 16-14 0-16-14z" transform="rotate(-8 48 52)"/><path class="dot" d="M36 46a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/><path class="s" d="M64 50l8-4-2 8" stroke-width="1.8"/>'},

{id:"eel",cat:"seafood",name:{en:"Eel",fr:"Anguille"},latin:"Anguilla anguilla",
origin:{en:"Sargasso Sea",fr:"Mer des Sargasses"},season:[9,10,11,12],
flavor:["rich","smoky","meaty","umami"],
story:{en:"Every European eel is born in the Sargasso Sea, drifts to Europe as a transparent larva, lives decades in fresh water, then swims back across the Atlantic to spawn and die. Aristotle thought they emerged from mud; nobody has ever seen them breed.",
fr:"Toute anguille européenne naît dans la mer des Sargasses, dérive vers l’Europe en larve transparente, vit des décennies en eau douce, puis retraverse l’Atlantique pour frayer et mourir. Aristote les croyait nées de la boue ; personne n’a jamais assisté à leur reproduction."},
tip:{en:"Its blood is toxic raw and destroyed by heat, which is why eel is never served raw anywhere in the world.",
fr:"Son sang est toxique cru et détruit par la chaleur, et c’est pourquoi l’anguille n’est jamais servie crue nulle part au monde."},
pairs:["soy-sauce","rice","ginger","parsley","garlic","red-wine-vinegar","bay-leaf","lemon"],
svg:'<path class="f1 sf" d="M16 60q14-14 28 0t30-6"/><path class="s" d="M16 62q14-14 28 0t30-6"/><circle class="dot" cx="76" cy="52" r="2"/>'},

{id:"sea-bream",cat:"seafood",name:{en:"Gilt-head bream",fr:"Daurade royale"},latin:"Sparus aurata",
origin:{en:"Mediterranean & eastern Atlantic",fr:"Méditerranée & Atlantique Est"},season:[6,7,8,9,10],
flavor:["sweet","delicate","marine","nutty"],
story:{en:"The gold band between its eyes gives it both its names — aurata in Latin, royale in French. It was sacred to Aphrodite, and the Romans farmed it in coastal ponds two thousand years before anyone used the word aquaculture.",
fr:"Le bandeau doré entre ses yeux lui vaut ses deux noms — aurata en latin, royale en français. Consacrée à Aphrodite, elle était élevée par les Romains dans des viviers côtiers deux mille ans avant qu’on emploie le mot aquaculture."},
tip:{en:"Bake it whole in a salt crust. The flesh steams in its own moisture and stays far juicier than any fillet.",
fr:"Cuisez-la entière en croûte de sel. La chair cuit dans sa propre humidité et reste bien plus juteuse qu’un filet."},
pairs:["lemon","olive-oil","fennel","potato","thyme","garlic","tomato","salt"],
svg:'<path class="f2 sf" d="M20 56q16-16 40-12t16 12q-8 12-30 12T20 56z"/><path class="f2 sf" d="M76 56l10-8v16z"/><path class="s" d="M30 48h8"/><circle class="dot" cx="33" cy="53" r="2"/>'},

{id:"percebes",cat:"seafood",luxe:true,rare:true,name:{en:"Goose barnacles",fr:"Pouces-pieds"},latin:"Pollicipes pollicipes",
origin:{en:"Costa da Morte, Galicia",fr:"Costa da Morte, Galice"},season:[],
flavor:["marine","briny","sweet"],
story:{en:"Harvested from wave-battered cliffs on Galicia’s “Coast of Death” by percebeiros roped against the swell — Europe’s most expensive seafood partly prices the danger of picking it. Medieval Europe believed barnacle geese hatched from them, which conveniently made goose acceptable dinner during Lent.",
fr:"Récoltés sur les falaises battues par la houle de la « Côte de la Mort » galicienne par des percebeiros encordés contre les vagues — le fruit de mer le plus cher d’Europe facture en partie le danger de sa cueillette. L’Europe médiévale croyait que les oies bernaches en éclosaient, ce qui rendait commodément l’oie acceptable au carême."},
tip:{en:"Thirty seconds in boiling seawater — or salted water with a bay leaf — then straight to the table under a cloth. Twist, peel, bite: it tastes of the wave that nearly took the picker.",
fr:"Trente secondes dans l’eau de mer bouillante — ou une eau salée au laurier — puis droit à table sous un linge. Tordre, peler, mordre : cela a le goût de la vague qui a failli emporter le cueilleur."},
pairs:["lemon","olive-oil","bay-leaf"],
svg:'<path class="f3 sf" d="M40 74q-4-16 2-26l6 4q-4 12-2 22zM52 72q-2-14 4-24l6 4q-5 10-4 20z"/><path class="f1 sf" d="M44 44l8 6 8-4-2-10-8-2-8 4z"/><path class="s" d="M48 40l6 4" stroke-width="1.4"/>'},

{id:"gurnard",cat:"seafood",name:{en:"Gurnard",fr:"Grondin"},latin:"Chelidonichthys lucerna",
origin:{en:"Eastern Atlantic & Mediterranean",fr:"Atlantique Est & Méditerranée"},season:[10,11,12,1,2,3],
flavor:["sweet","marine","mild","meaty"],
story:{en:"It grunts audibly when landed, using its swim bladder — which is where both names come from, grondin from gronder, to growl. Long dismissed as bycatch, it is one of the essential fish of a real bouillabaisse.",
fr:"Il grogne distinctement quand on le remonte, en faisant vibrer sa vessie natatoire — d’où ses deux noms, grondin venant de gronder. Longtemps méprisé comme prise accessoire, c’est l’un des poissons indispensables d’une vraie bouillabaisse."},
tip:{en:"Mind the spines on the head and gill covers — they are genuinely sharp. Ask the fishmonger to trim them.",
fr:"Attention aux épines de la tête et des opercules — elles sont réellement coupantes. Demandez au poissonnier de les parer."},
pairs:["saffron","fennel","tomato","garlic","olive-oil","potato","orange","thyme"],
svg:'<path class="f1 sf" d="M20 56q16-14 40-10t16 10q-8 12-30 12T20 56z"/><path class="f2 sf" d="M40 46q10-12 20-4-10 6-20 4z"/><circle class="dot" cx="30" cy="53" r="2"/>'},

{id:"hake",cat:"seafood",name:{en:"Hake",fr:"Merlu"},latin:"Merluccius merluccius",
origin:{en:"Northeast Atlantic",fr:"Atlantique Nord-Est"},season:[3,4,5,6,7,8],
flavor:["delicate","mild","marine","sweet"],
story:{en:"Spain eats more of it than anyone and treats the throat — the kokotxa — as the finest part, a gelatinous morsel Basque cooks turn into pil-pil sauce by nothing more than swirling it in warm oil until it emulsifies.",
fr:"L’Espagne en mange plus que quiconque et tient la gorge — la kokotxa — pour la meilleure part, un morceau gélatineux dont les cuisiniers basques tirent la sauce pil-pil rien qu’en la faisant tourner dans l’huile tiède jusqu’à émulsion."},
tip:{en:"Its flesh is fragile and falls apart if turned twice. Cook it on one side only and finish it under the grill.",
fr:"Sa chair est fragile et se défait si on la retourne deux fois. Cuisez-la d’un seul côté et finissez au gril."},
pairs:["garlic","olive-oil","parsley","clam","chili","potato","lemon","white-wine-vinegar"],
svg:'<path class="f3 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f3 sf" d="M78 56l10-8v16z"/><circle class="dot" cx="32" cy="53" r="2"/>'},

{id:"herring",cat:"seafood",name:{en:"Herring",fr:"Hareng"},latin:"Clupea harengus",
origin:{en:"North Atlantic & Baltic",fr:"Atlantique Nord & Baltique"},season:[10,11,12,1,2],
flavor:["rich","salty","marine","smoky"],
story:{en:"The fish that built cities. The Hanseatic League ran on salted herring, Amsterdam is said to be built on its bones, and a fourteenth-century Dutchman's method of gutting it at sea gave the Netherlands a two-century commercial advantage.",
fr:"Le poisson qui a bâti des villes. La Ligue hanséatique vivait du hareng salé, on dit qu’Amsterdam est bâtie sur ses arêtes, et la méthode d’un Néerlandais du XIVe siècle pour l’étêter en mer donna aux Pays-Bas deux siècles d’avance commerciale."},
tip:{en:"Smoked, salted or soused, it wants something starchy and something sour alongside — potato and onion, or apple and cream.",
fr:"Fumé, salé ou mariné, il appelle un féculent et un acide à côté — pomme de terre et oignon, ou pomme et crème."},
pairs:["potato","onion","cream","apple","dill","cider-vinegar","rye-flour","black-pepper"],
svg:'<path class="f3 sf" d="M18 56q18-12 42-8t18 8q-8 12-32 12T18 56z"/><path class="f3 sf" d="M78 56l10-8v16z"/><circle class="dot" cx="32" cy="54" r="2"/>'},

{id:"john-dory",cat:"seafood",name:{en:"John Dory",fr:"Saint-Pierre"},latin:"Zeus faber",
origin:{en:"Eastern Atlantic & Mediterranean",fr:"Atlantique Est & Méditerranée"},season:[1,2,3,4,10,11,12],
flavor:["delicate","sweet","marine","mild"],
story:{en:"The dark spot on its flank is said to be Saint Peter's thumbprint, left when he lifted the fish to take a coin from its mouth — hence saint-pierre. It is so thin from the side that a large one yields surprisingly little flesh.",
fr:"La tache sombre sur son flanc serait l’empreinte du pouce de saint Pierre, laissée en soulevant le poisson pour prendre une pièce dans sa bouche — d’où saint-pierre. Il est si mince de profil qu’un gros individu rend étonnamment peu de chair."},
tip:{en:"Ask for it filleted and keep the bones — the head and frame make one of the best fish stocks there is.",
fr:"Demandez-le en filets et gardez l’arête — la tête et la carcasse font l’un des meilleurs fumets qui soient."},
pairs:["butter","lemon","shallot","cream","chives","white-wine-vinegar","spinach","thyme"],
svg:'<path class="f2 sf" d="M24 56q6-22 26-22t26 22q-8 16-26 16t-26-16z"/><circle class="dot" cx="38" cy="52" r="4"/><path class="s" d="M32 40l4 6"/>'},

{id:"mackerel",cat:"seafood",name:{en:"Mackerel",fr:"Maquereau"},latin:"Scomber scombrus",
origin:{en:"North Atlantic",fr:"Atlantique Nord"},season:[5,6,7,8,9],
flavor:["rich","marine","umami","meaty"],
story:{en:"It has no swim bladder and must keep swimming to stay off the bottom, which is why the flesh is so dark and oily — it is pure endurance muscle. That same oil means it spoils faster than almost any other fish.",
fr:"Il n’a pas de vessie natatoire et doit nager sans cesse pour ne pas couler, d’où une chair si sombre et si grasse — c’est du muscle d’endurance pur. Ce même gras le fait s’altérer plus vite que presque tout autre poisson."},
tip:{en:"Buy it the day it was landed or not at all. Its acidity partners — gooseberry, rhubarb, mustard — are not decoration but necessity.",
fr:"Achetez-le le jour du débarquement ou pas du tout. Ses partenaires acides — groseille à maquereau, rhubarbe, moutarde — ne sont pas décoratifs mais nécessaires."},
pairs:["gooseberry","mustard","rhubarb","lemon","horseradish","cider-vinegar","black-pepper","beetroot"],
svg:'<path class="f1 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f1 sf" d="M78 56l10-8v16z"/><path class="s" d="M30 48q8 4 16 0M38 62q8 4 16 0"/>'},

{id:"monkfish",cat:"seafood",name:{en:"Monkfish",fr:"Lotte"},latin:"Lophius piscatorius",
origin:{en:"Northeast Atlantic",fr:"Atlantique Nord-Est"},season:[10,11,12,1,2,3],
flavor:["sweet","meaty","marine","rich"],
story:{en:"So ugly that fishmongers traditionally removed the head before display, and it was once thrown back as worthless. Its dense tail meat behaves like meat rather than fish, which is why it is called the poor man's lobster — a name it has long outgrown in price.",
fr:"Si laide que les poissonniers ôtaient traditionnellement la tête avant l’étal, et qu’on la rejetait jadis comme sans valeur. La chair dense de la queue se comporte comme de la viande plutôt que du poisson, d’où le surnom de homard du pauvre — que son prix a depuis longtemps démenti."},
tip:{en:"Strip off every trace of the grey membrane. It shrinks violently in the pan and curls the fillet into a knot.",
fr:"Ôtez toute trace de la membrane grise. Elle se rétracte violemment à la cuisson et noue le filet."},
pairs:["lard","garlic","saffron","tomato","thyme","white-wine-vinegar","leek","olive-oil"],
svg:'<path class="f1 sf" d="M18 54q10-14 26-10t30 12q-10 12-32 10T18 54z"/><path class="s" d="M28 48q4-8 10-6"/><circle class="dot" cx="30" cy="54" r="2.5"/>'},

{id:"pike",cat:"seafood",name:{en:"Pike",fr:"Brochet"},latin:"Esox lucius",
origin:{en:"Northern hemisphere fresh water",fr:"Eaux douces de l’hémisphère nord"},season:[10,11,12,1,2,3],
flavor:["delicate","mild","sweet","earthy"],
story:{en:"Lyon built a dish around its worst feature: pike is riddled with fine forked bones, so cooks pounded the flesh, sieved it and bound it into quenelles. The bones are the reason the technique exists.",
fr:"Lyon a bâti un plat sur son pire défaut : le brochet est truffé d’arêtes fines et fourchues, si bien que les cuisiniers ont pilé la chair, l’ont tamisée et liée en quenelles. Les arêtes sont la raison d’être de la technique."},
tip:{en:"Do not attempt a plain fillet unless someone very skilled has boned it. Quenelles or a terrine are the safe routes.",
fr:"N’essayez pas un simple filet à moins qu’un professionnel ne l’ait désarêté. Quenelles ou terrine sont les voies sûres."},
pairs:["cream","butter","shallot","nutmeg","egg","crayfish","white-wine-vinegar","chives"],
svg:'<path class="f2 sf" d="M14 56q22-12 48-8t20 8q-10 12-36 10T14 56z"/><path class="s" d="M20 52q6-4 12-2"/><circle class="dot" cx="26" cy="54" r="2"/>'},

{id:"plaice",cat:"seafood",name:{en:"Plaice",fr:"Carrelet"},latin:"Pleuronectes platessa",
origin:{en:"North Atlantic & North Sea",fr:"Atlantique Nord & mer du Nord"},season:[4,5,6,7,8,9],
flavor:["delicate","sweet","mild","marine"],
story:{en:"It is born symmetrical, swimming upright like any fish, and then one eye migrates across the skull over a few weeks until both sit on the same side. The orange spots are unmistakable and fade within hours of death.",
fr:"Il naît symétrique, nageant droit comme tout poisson, puis un œil migre à travers le crâne en quelques semaines jusqu’à ce que les deux soient du même côté. Les taches orange sont sans équivoque et pâlissent dans les heures qui suivent la mort."},
tip:{en:"It is thin and cooks in three or four minutes. Flour, butter, lemon — anything more elaborate buries it.",
fr:"Il est mince et cuit en trois ou quatre minutes. Farine, beurre, citron — plus élaboré l’enterre."},
pairs:["butter","lemon","capers","parsley","flour-t55","shrimp","black-pepper","cream"],
svg:'<ellipse class="f2 sf" cx="46" cy="56" rx="28" ry="16"/><path class="f2 sf" d="M74 56l10-6v12z"/><circle class="dot" cx="40" cy="50" r="2.5"/><circle class="dot" cx="52" cy="60" r="2.5"/><circle class="dot" cx="58" cy="50" r="2.5"/>'},

{id:"pollock",cat:"seafood",name:{en:"Pollock",fr:"Lieu noir"},latin:"Pollachius virens",
origin:{en:"North Atlantic",fr:"Atlantique Nord"},season:[10,11,12,1,2,3],
flavor:["mild","marine","delicate","sweet"],
story:{en:"For decades it was the cheap alternative nobody wanted, sold as a filler and processed into surimi. Overfishing of cod turned it into the sustainable choice, and the same fish that was once a compromise is now the recommendation.",
fr:"Pendant des décennies ce fut l’alternative bon marché dont personne ne voulait, vendue comme produit de remplissage et transformée en surimi. La surpêche du cabillaud en a fait le choix durable, et le poisson qui était un compromis est devenu la recommandation."},
tip:{en:"It is drier than cod, so brine it briefly — twenty minutes in salted water before cooking makes a visible difference.",
fr:"Il est plus sec que le cabillaud : saumurez-le brièvement — vingt minutes en eau salée avant cuisson font une différence visible."},
pairs:["butter","parsley","potato","lemon","cream","leek","black-pepper","mustard"],
svg:'<path class="f2 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f2 sf" d="M78 56l10-8v16z"/><path class="s" d="M40 44q6 4 14 2"/>'},

{id:"red-mullet",cat:"seafood",name:{en:"Red mullet",fr:"Rouget barbet"},latin:"Mullus surmuletus",
origin:{en:"Mediterranean & eastern Atlantic",fr:"Méditerranée & Atlantique Est"},season:[5,6,7,8,9,10],
flavor:["rich","marine","sweet","earthy"],
story:{en:"Rome paid absurd sums for large ones and kept them alive at table so guests could watch the colour change as they died. Its liver is traditionally left inside during cooking, which is unusual and gives the flesh its distinctive depth.",
fr:"Rome payait des sommes absurdes pour les gros individus et les gardait vivants à table pour que les convives voient la couleur changer à l’agonie. Son foie est traditionnellement laissé en place à la cuisson, fait rare qui donne à la chair sa profondeur particulière."},
tip:{en:"Scale it gently — the skin is fragile and the colour is half the point. Grill it whole and eat it with your fingers.",
fr:"Écaillez-le délicatement — la peau est fragile et la couleur fait la moitié de l’intérêt. Grillez-le entier et mangez-le avec les doigts."},
pairs:["olive-oil","fennel","tomato","saffron","thyme","garlic","olive","lemon"],
svg:'<path class="f1 sf" d="M20 56q16-16 40-12t16 12q-8 12-30 12T20 56z"/><path class="f1 sf" d="M76 56l10-8v16z"/><path class="s" d="M26 60q-4 6-2 8"/>'},

{id:"salmon",cat:"seafood",name:{en:"Salmon",fr:"Saumon"},latin:"Salmo salar",
origin:{en:"North Atlantic rivers",fr:"Rivières de l’Atlantique Nord"},season:[],
flavor:["rich","buttery","marine","delicate"],
story:{en:"Its Latin name may come from salire, “to leap” — the fish that climbs waterfalls to die where it was born. Scandinavian fishermen once buried salted salmon in the sand above the tide line: grav lax, “buried salmon”, now cured in dill on every smörgåsbord.",
fr:"Son nom latin viendrait de salire, « bondir » — le poisson qui remonte les cascades pour mourir là où il est né. Les pêcheurs scandinaves enterraient jadis le saumon salé dans le sable au-dessus des marées : grav lax, « saumon enterré », aujourd’hui confit à l’aneth sur chaque smörgåsbord."},
tip:{en:"Cook it less than you dare — the centre should still be silk. Skin-side down almost the whole way, and the skin becomes the best part.",
fr:"Cuisez-le moins que vous n’osez — le cœur doit rester soyeux. Côté peau presque tout du long, et la peau devient le meilleur morceau."},
pairs:["dill","lemon","fennel","soy-sauce","ginger","miso","cream"],
svg:'<path class="f2 sf" d="M26 52q12-12 30-10l12-8-2 10 2 10-12-8q-18 2-30 6z" transform="translate(0 4)"/><path class="s" d="M36 50q0 8-2 12M46 48q0 10-2 14" transform="translate(0 2)"/><path class="dot" d="M32 52a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0" transform="translate(0 2)"/>'},

{id:"sardine",cat:"seafood",name:{en:"Sardine",fr:"Sardine"},latin:"Sardina pilchardus",
origin:{en:"Mediterranean & East Atlantic",fr:"Méditerranée & Atlantique Est"},season:[5,6,7,8,9],
flavor:["rich","marine","salty","umami"],
story:{en:"Named for Sardinia, whose waters once teemed with them, and immortalised by Marseille, where a ship called the Sartine sank at the harbour mouth — letting the whole town claim, forever, that “a sardine once blocked the port”. Napoleon’s era canned them: the first fish to be sealed in tin.",
fr:"Nommée d’après la Sardaigne, dont les eaux en regorgeaient, et immortalisée par Marseille, où un navire nommé la Sartine coula à l’entrée de la rade — permettant à toute la ville de jurer, pour toujours, qu’« une sardine a bouché le port ». L’époque napoléonienne la mit en boîte : premier poisson scellé dans le fer-blanc."},
tip:{en:"Fresh, they want nothing but a grill, coarse salt and lemon. Tinned, they improve with age like wine — collectors cellar good vintages.",
fr:"Fraîches, elles ne demandent qu’un gril, du gros sel et du citron. En boîte, elles se bonifient avec l’âge comme le vin — les amateurs cavent les bons millésimes."},
pairs:["lemon","tomato","olive-oil","fennel","oregano"],
svg:'<path class="f1 sf" d="M28 48q10-8 24-7l8-5-1 6 1 6-8-5q-14 1-24 5z"/><path class="f1 sf" d="M32 62q10-8 24-7l8-5-1 6 1 6-8-5q-14 1-24 5z"/><path class="dot" d="M33 46a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0M37 60a1.3 1.3 0 102.6 0 1.3 1.3 0 10-2.6 0"/>'},

{id:"sea-bass",cat:"seafood",name:{en:"Sea bass",fr:"Bar"},latin:"Dicentrarchus labrax",
origin:{en:"Northeast Atlantic & Mediterranean",fr:"Atlantique Nord-Est & Méditerranée"},season:[9,10,11,12,1,2],
flavor:["delicate","marine","sweet","mild"],
story:{en:"France calls it bar in the north and loup in the Mediterranean — the wolf, for the way it hunts. A line-caught bar de ligne carries a tag through the gill and sells for several times the price of a netted or farmed fish.",
fr:"La France l’appelle bar au nord et loup en Méditerranée — le loup, pour sa façon de chasser. Un bar de ligne porte une étiquette passée dans l’ouïe et se vend plusieurs fois le prix d’un poisson de filet ou d’élevage."},
tip:{en:"Its skin crisps better than almost any fish. Dry it thoroughly, press it flat in the pan for the first minute, and do not move it.",
fr:"Sa peau croustille mieux que celle de presque tout poisson. Séchez-la bien, pressez-la à plat la première minute, et ne la bougez pas."},
pairs:["fennel","lemon","olive-oil","thyme","white-wine-vinegar","tomato","butter","dill"],
svg:'<path class="f3 sf" d="M20 56q16-16 40-12t16 12q-8 12-30 12T20 56z"/><path class="f3 sf" d="M76 56l10-8v16z"/><circle class="dot" cx="34" cy="52" r="2"/>'},

{id:"skate",cat:"seafood",name:{en:"Skate wing",fr:"Aile de raie"},latin:"Raja clavata",
origin:{en:"Northeast Atlantic",fr:"Atlantique Nord-Est"},season:[10,11,12,1,2,3],
flavor:["sweet","marine","delicate","rich"],
story:{en:"It has cartilage rather than bone, so the flesh comes away in ribbed strands rather than flakes. It also smells faintly of ammonia if it is even slightly old — one of the few fish where the nose gives an unambiguous verdict.",
fr:"Elle a du cartilage plutôt que des arêtes : la chair se détache en filaments côtelés plutôt qu’en lamelles. Elle sent aussi légèrement l’ammoniaque dès qu’elle n’est plus très fraîche — l’un des rares poissons où le nez tranche sans ambiguïté."},
tip:{en:"Raie au beurre noisette is the dish: browned butter, capers, a splash of vinegar. It has been the standard for two centuries because nothing beats it.",
fr:"La raie au beurre noisette est le plat : beurre noisette, câpres, un trait de vinaigre. C’est la norme depuis deux siècles parce que rien ne fait mieux."},
pairs:["capers","butter","white-wine-vinegar","parsley","potato","lemon","black-pepper","shallot"],
svg:'<path class="f2 sf" d="M14 56q20-18 34-18t34 18q-16 12-34 12T14 56z"/><path class="s" d="M48 68v14"/><circle class="dot" cx="40" cy="50" r="2"/><circle class="dot" cx="56" cy="50" r="2"/>'},

{id:"trout",cat:"seafood",name:{en:"Trout",fr:"Truite"},latin:"Salmo trutta",
origin:{en:"Europe & western Asia",fr:"Europe & Asie occidentale"},season:[3,4,5,6,7,8,9],
flavor:["delicate","sweet","marine","mild"],
story:{en:"Truite au bleu depends on the fish being killed moments before cooking — a film of natural mucus on the skin reacts with vinegar and turns steel blue. Touch the fish with your hands and the effect is ruined.",
fr:"La truite au bleu exige un poisson tué juste avant cuisson — un film de mucus naturel sur la peau réagit au vinaigre et vire au bleu acier. Touchez le poisson à mains nues et l’effet est perdu."},
tip:{en:"Stuff the cavity with lemon and herbs and bake it whole. Fillets of trout dry out faster than almost any other fish.",
fr:"Garnissez la cavité de citron et d’herbes et cuisez-la entière. Les filets de truite sèchent plus vite que presque tout autre poisson."},
pairs:["almond","butter","lemon","parsley","white-wine-vinegar","dill","cream","hazelnut"],
svg:'<path class="f2 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f2 sf" d="M78 56l10-8v16z"/><circle class="dot" cx="36" cy="52" r="1.6"/><circle class="dot" cx="48" cy="58" r="1.6"/><circle class="dot" cx="56" cy="51" r="1.6"/>'},

{id:"tuna",cat:"seafood",name:{en:"Tuna",fr:"Thon"},latin:"Thunnus thynnus",
origin:{en:"Mediterranean & open oceans",fr:"Méditerranée & océans"},season:[5,6,7,8,9],
flavor:["meaty","rich","marine","umami"],
story:{en:"Phoenicians and Sicilians netted bluefin in the same channels for three thousand years — the mattanza was fishing as ritual theatre. Today a single great bluefin can fetch the price of a house at Tokyo’s dawn auctions: the ocean’s most contested muscle.",
fr:"Phéniciens et Siciliens prirent le thon rouge dans les mêmes passes pendant trois mille ans — la mattanza était une pêche en théâtre rituel. Aujourd’hui, un grand thon rouge peut atteindre le prix d’une maison aux enchères de l’aube à Tokyo : le muscle le plus disputé de l’océan."},
tip:{en:"Treat it like beef: sear the outside hard, leave the centre rare, rest it. Cooked through, the king becomes cat food.",
fr:"Traitez-le comme du bœuf : saisissez fort l’extérieur, laissez le cœur rouge, laissez reposer. Cuit à cœur, le roi devient pâtée."},
pairs:["sesame","soy-sauce","ginger","olive","capers"],
svg:'<path class="f2 sf" d="M24 54q14-16 36-12l6-8 2 8 8 4-8 4-2 8-6-8q-22 4-36 4z" transform="translate(0 2)"/><path class="s" d="M44 44v16" transform="translate(0 2)"/><path class="dot" d="M32 52a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/>'},

{id:"turbot",cat:"seafood",luxe:true,name:{en:"Turbot",fr:"Turbot"},latin:"Scophthalmus maximus",
origin:{en:"North-East Atlantic & Mediterranean",fr:"Atlantique Nord-Est & Méditerranée"},season:[],
flavor:["delicate","marine","rich","buttery"],
story:{en:"The “king of fish” has convened parliaments: in Juvenal’s satire, a turbot too vast for any dish forced Emperor Domitian to summon the Roman Senate, which gravely advised building a pot around it. France still forges the turbotière, a diamond-shaped vessel that exists for this fish alone.",
fr:"Le « roi des poissons » a convoqué des parlements : dans la satire de Juvénal, un turbot trop vaste pour tout plat contraignit l’empereur Domitien à réunir le Sénat romain, qui conseilla gravement de bâtir une marmite autour. La France forge encore la turbotière, ustensile en losange qui n’existe que pour ce poisson."},
tip:{en:"Cook it on the bone, always — the gelatine bastes the pearl-white flesh from within. Butter and lemon complete the coronation; a morel cream is the state occasion.",
fr:"Cuisez-le sur l’arête, toujours — la gélatine arrose de l’intérieur sa chair blanc nacré. Beurre et citron achèvent le sacre ; une crème aux morilles est le dîner d’État."},
pairs:["butter","lemon","egg","morel","cream"],
svg:'<path class="f1 sf" d="M48 30q22 10 22 24T48 76Q26 66 26 54t22-24z" transform="rotate(45 48 53)"/><path class="dot" d="M42 44a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M48 40a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/><path class="s" d="M40 56q8 6 18 2" stroke-width="1.6"/>'},

{id:"zander",cat:"seafood",name:{en:"Zander",fr:"Sandre"},latin:"Sander lucioperca",
origin:{en:"Central & eastern Europe",fr:"Europe centrale & orientale"},season:[9,10,11,12,1],
flavor:["delicate","sweet","mild","marine"],
story:{en:"A perch that behaves like a pike, and the freshwater fish French restaurants reach for when they want something firm and white without sea flavour. It was introduced to western European rivers deliberately in the twentieth century.",
fr:"Une perche qui se comporte en brochet, et le poisson d’eau douce que les restaurants français choisissent quand ils veulent du ferme et du blanc sans goût de mer. Il fut introduit délibérément dans les rivières d’Europe de l’Ouest au XXe siècle."},
tip:{en:"The skin is thin and crisps beautifully, unlike most freshwater fish. Cook it skin-side down and leave it alone.",
fr:"La peau est fine et croustille superbement, contrairement à la plupart des poissons d’eau douce. Cuisez-le côté peau et n’y touchez pas."},
pairs:["butter","white-wine-vinegar","shallot","cream","chives","leek","lemon","morel"],
svg:'<path class="f3 sf" d="M18 56q18-14 42-10t18 10q-8 12-32 12T18 56z"/><path class="f3 sf" d="M78 56l10-8v16z"/><path class="s" d="M34 44q6 4 12 2"/>'}
]);
