window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"caviar-beluga",cat:"roe",rare:true,luxe:true,name:{en:"Beluga caviar",fr:"Caviar beluga"},latin:"Huso huso (roe)",
origin:{en:"Caspian basin, now farmed",fr:"Bassin caspien, aujourd'hui d'élevage"},season:[],
flavor:["creamy","marine","delicate","mild"],
story:{en:"A beluga sturgeon can take twenty years to spawn for the first time, which is why its roe has sat on CITES Appendix II since 1998 and has been barred from the United States since 2005. What reaches a French table now comes from farms in Italy, China or the Gulf, and arrives under a numbered CITES label rather than a fisherman's name.",
fr:"Un esturgeon béluga peut mettre vingt ans avant de frayer une première fois : ses œufs figurent à l'annexe II de la CITES depuis 1998 et sont interdits d'importation aux États-Unis depuis 2005. Ce qui arrive aujourd'hui sur une table française vient d'élevages d'Italie, de Chine ou du Golfe, sous étiquette CITES numérotée plutôt que sous le nom d'un pêcheur."},
tip:{en:"Hold the tin between 0 and 4 °C and open it only at the table. Never a steel spoon: the membrane is thin enough to burst under the edge, and the metal leaves an iron taste — use nacre, horn or bone.",
fr:"Gardez la boîte entre 0 et 4 °C et ne l'ouvrez qu'à table. Jamais de cuillère en acier : la membrane est assez fine pour éclater dessous, et le métal laisse un goût ferreux — nacre, corne ou os."},
pairs:["creme-fraiche","beurre-de-baratte","egg","potato","chives","lemon"],
svg:'<circle class="f2 sf" cx="48" cy="50" r="27"/><circle class="f3" cx="48" cy="50" r="21"/><circle class="f1 sf" cx="40" cy="44" r="5"/><circle class="f1 sf" cx="52" cy="47" r="5"/><circle class="f1 sf" cx="44" cy="57" r="5"/><circle class="f1 sf" cx="56" cy="58" r="5"/>'},

{id:"bottarga",cat:"roe",rare:true,name:{en:"Bottarga",fr:"Poutargue"},latin:"Mugil cephalus (roe)",
origin:{en:"Sardinia & Provence",fr:"Sardaigne & Provence"},season:[],
flavor:["briny","umami","salty","rich"],
story:{en:"Mullet roe salted, pressed and air-dried into an amber ingot — a technique the Phoenicians carried across the Mediterranean three thousand years ago. Sardinia grates its “Mediterranean caviar” over pasta; Martigues, near Marseille, guards its own as le caviar provençal.",
fr:"Des œufs de mulet salés, pressés et séchés à l’air en lingot d’ambre — une technique que les Phéniciens promenèrent en Méditerranée il y a trois mille ans. La Sardaigne râpe son « caviar méditerranéen » sur les pâtes ; Martigues, près de Marseille, garde le sien comme le caviar provençal."},
tip:{en:"Shave it paper-thin or grate it at the very end, never cooked. With lemon, olive oil and raw celery, it needs exactly nothing else.",
fr:"Tranchez-la en copeaux ou râpez-la tout à la fin, jamais cuite. Avec citron, huile d’olive et céleri cru, elle n’a besoin d’exactement rien d’autre."},
pairs:["lemon","olive-oil","garlic","celery","egg"],
svg:'<path class="f2 sf" d="M34 44q14-8 28 0 4 10 0 20-14 8-28 0-4-10 0-20z" transform="rotate(-14 48 54)"/><path class="s" d="M40 46q8-4 16 0M40 60q8 4 16 0" transform="rotate(-14 48 54)" stroke-width="1.6"/>'},

{id:"caviar",cat:"roe",luxe:true,name:{en:"Caviar",fr:"Caviar"},latin:"Acipenser spp. (roe)",
origin:{en:"Caspian Sea, now farmed worldwide",fr:"Mer Caspienne, désormais élevé partout"},season:[],
flavor:["briny","marine","rich","buttery"],
story:{en:"Sturgeon roe cured malossol — “little salt” in Russian, the only seasoning it tolerates. In 19th-century America sturgeon were so plentiful that saloons gave caviar away free, like peanuts, to make drinkers thirsty; two centuries of appetite later, it is weighed out like jewellery.",
fr:"Des œufs d’esturgeon salés malossol — « peu de sel » en russe, le seul assaisonnement qu’il tolère. Dans l’Amérique du XIXe siècle, l’esturgeon abondait tant que les saloons offraient le caviar, comme des cacahuètes, pour donner soif ; deux siècles d’appétit plus tard, on le pèse comme un bijou."},
tip:{en:"Never metal on the roe — a mother-of-pearl or horn spoon, straight from the chilled tin. If you must dress it, only blini, potato and thick cream have earned the right.",
fr:"Jamais de métal sur le grain — cuillère de nacre ou de corne, à même la boîte glacée. S’il faut l’accompagner, seuls le blini, la pomme de terre et la crème épaisse en ont gagné le droit."},
pairs:["cream","potato","egg","chives","butter"],
svg:'<circle class="f1 sf" cx="48" cy="52" r="19"/><path class="s" d="M32 46h32" stroke-width="1.6"/><path class="dot" d="M40 54a2 2 0 104 0 2 2 0 10-4 0M47 52a2 2 0 104 0 2 2 0 10-4 0M54 55a2 2 0 104 0 2 2 0 10-4 0M43 60a2 2 0 104 0 2 2 0 10-4 0M51 61a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"dried-shrimp-roe",cat:"roe",rare:true,name:{en:"Dried shrimp roe",fr:"Œufs de crevette séchés (xiazi)"},latin:"Macrobrachium nipponense",
origin:{en:"Suzhou and Shanghai, China",fr:"Suzhou et Shanghai, Chine"},season:[],
flavor:["umami","briny","marine","salty"],
story:{en:"Scraped from freshwater river shrimp and dried to a dark grit, xiazi is one of three separate parts a Suzhou kitchen takes from the same animal — meat, roe and head fat all go into san xia mian, three-shrimp noodles, as distinct ingredients. Drying shrinks the eggs smaller still and concentrates them, so the roe alone is sold as a seasoning rather than as seafood.",
fr:"Grattés sur la crevette de rivière puis séchés en une poudre sombre, les xiazi sont l’une des trois parties qu’une cuisine de Suzhou tire du même animal : chair, œufs et graisse de tête entrent séparément dans les san xia mian, les nouilles aux trois crevettes. Le séchage rétrécit encore les œufs et les concentre, si bien que la rogue seule se vend comme assaisonnement et non comme produit de la mer."},
tip:{en:"It is already salty — season the dish after adding it, never before. Bloom a teaspoon in warm oil or lard for ten seconds to wake the aroma, then toss it through noodles off the heat; scorched, it goes acrid.",
fr:"C’est déjà salé : salez le plat après l’avoir ajoutée, jamais avant. Réveillez une cuillère à café dix secondes dans l’huile ou le saindoux chaud, puis mêlez-la aux nouilles hors du feu — brûlée, elle devient âcre."},
pairs:["sheng-chou","lard","spring-onion","silken-tofu","shaoxing-wine","ginger"],
svg:'<ellipse class="f1 sf" cx="38" cy="46" rx="17" ry="13"/><path class="s" d="M54 46 78 62"/><path class="f3 sf" d="M28 44q10-8 20 0-4 6-10 6t-10-6z"/><circle class="dot" cx="60" cy="34" r="1.8"/><circle class="dot" cx="66" cy="29" r="1.8"/><circle class="dot" cx="56" cy="26" r="1.8"/>'},

{id:"fugu-shirako",cat:"roe",rare:true,luxe:true,name:{en:"Fugu shirako",fr:"Laitance de fugu"},latin:"Takifugu rubripes (milt)",
origin:{en:"Shimonoseki, in winter",fr:"Shimonoseki, en hiver"},season:[12,1,2],
flavor:["creamy","rich","marine","delicate"],
story:{en:"In a fish whose liver and ovaries can kill, the milt is harmless — it is the one internal organ a licensed fugu cook may serve, and it peaks in the weeks before the winter spawn. It has nothing to do with the cod milt sold under the same word: firmer, sweeter, and priced accordingly.",
fr:"Chez un poisson dont le foie et les ovaires peuvent tuer, la laitance est inoffensive — c’est le seul organe interne qu’un cuisinier agréé fugu ait le droit de servir, et elle atteint son point dans les semaines qui précèdent le frai d’hiver. Elle n’a rien à voir avec la laitance de morue vendue sous le même mot : plus ferme, plus douce, et tarifée en conséquence."},
tip:{en:"Salt it and blister it close to the coals, a minute a side — the skin should mottle while the inside stays liquid. Ponzu and grated daikon; anything creamy is redundant.",
fr:"Salez et faites-la cloquer tout près de la braise, une minute par face : la peau doit se marbrer tandis que l’intérieur reste coulant. Ponzu et daikon râpé ; toute crème serait de trop."},
pairs:["ponzu","daikon","negi","salt","junmai-sake","yuzu","koikuchi-shoyu"],
svg:'<path class="f1 sf" d="M28 54q-4-14 10-18 6-10 16-4 12-4 14 8 8 6 2 16-4 14-18 12t-24-14z"/><path class="s" d="M36 46q6 6 4 14M50 40q-4 10 2 18M62 48q-6 4-4 14"/><path class="s" d="M30 58q18 6 36-2"/>'},

{id:"laitance-de-hareng",cat:"roe",name:{en:"Herring milt",fr:"Laitance de hareng"},latin:"Clupea harengus (milt)",
origin:{en:"North Sea and Baltic",fr:"Mer du Nord et Baltique"},season:[1,2,10,11,12],
flavor:["creamy","delicate","marine","rich"],
story:{en:"Laitance is the male herring's milt, named for the milky liquid it releases, and classical French service used it twice over: fried whole as a garnish, and pounded raw into butter to bind a sauce. Victorian breakfast tables ate the same thing on toast as soft roe, and it has quietly vanished from both countries since.",
fr:"La laitance est la semence du hareng mâle, ainsi nommée pour le liquide laiteux qu'elle rend, et la cuisine classique l'employait deux fois : frite entière en garniture, ou pilée crue dans le beurre pour lier une sauce. Les tables anglaises du XIXe siècle la mangeaient sur toast sous le nom de soft roe ; elle a discrètement disparu des deux côtés depuis."},
tip:{en:"Poach it two or three minutes in barely trembling salted water with a dash of vinegar, or flour it and fry it in foaming butter. Anything approaching a boil splits it and turns it grainy.",
fr:"Pochez-la deux à trois minutes dans une eau salée à peine frémissante, avec un trait de vinaigre, ou farinez-la et faites-la sauter au beurre mousseux. Dès que l'eau bout, elle se défait et devient granuleuse."},
pairs:["butter","lemon","parsley","capers","shallot","cream","herring"],
svg:'<path class="s" d="M20 66q28 12 56 0"/><path class="f1 sf" d="M26 52q4-14 20-12t16 12-12 10-24 2 0-12z"/><path class="f2 sf" d="M46 58q10-8 20-2t-2 12-20-10z"/><path class="s" d="M34 50q8 5 14 0M52 60q6 3 10 0"/>'},

{id:"ikura",cat:"roe",name:{en:"Ikura",fr:"Œufs de saumon (ikura)"},latin:"Oncorhynchus keta (roe)",
origin:{en:"Hokkaido rivers",fr:"Rivières d'Hokkaido"},season:[9,10,11],
flavor:["briny","rich","umami","marine"],
story:{en:"Ikura is a Russian word — икра means roe of any kind — taken into Japanese in the Taishō era, when producers in Hokkaido copied the Russian method of salting salmon eggs. In Japanese it narrowed to one meaning: eggs freed from the membrane, as opposed to sujiko, which is the whole sac salted intact.",
fr:"Ikura est un mot russe — икра désigne n'importe quelle œuvre de poisson — passé en japonais à l'ère Taishō, quand les producteurs d'Hokkaido ont repris la méthode russe de salage des œufs de saumon. En japonais, le sens s'est resserré : les grains détachés de la membrane, par opposition au sujiko, la poche entière salée telle quelle."},
tip:{en:"Free the eggs in hand-hot 3 % brine rather than cold water — the membrane relaxes and lets go in a minute — then cure them only two to four hours in soy, sake and mirin. Left overnight they toughen and turn flatly salty.",
fr:"Détachez les grains dans une saumure à 3 % à peine chaude plutôt qu'à l'eau froide : la membrane se relâche et cède en une minute. Ne les marinez que deux à quatre heures dans sauce soja, saké et mirin — une nuit entière les durcit et les rend platement salés."},
pairs:["rice","nori","soy-sauce","wasabi","shiso","cucumber","junmai-sake","daikon"],
svg:'<path class="f3 sf" d="M28 46h40v22q0 4-4 4H32q-4 0-4-4z"/><path class="f1" d="M32 58h32v10H32z"/><circle class="f2 sf" cx="38" cy="44" r="6"/><circle class="f2 sf" cx="50" cy="42" r="6"/><circle class="f2 sf" cx="61" cy="45" r="6"/>'},

{id:"caviar-kaluga",cat:"roe",luxe:true,name:{en:"Kaluga caviar",fr:"Caviar kaluga"},latin:"Huso dauricus (roe)",
origin:{en:"Amur basin, farmed in Zhejiang",fr:"Bassin de l'Amour, élevé au Zhejiang"},season:[],
flavor:["buttery","marine","rich","mild"],
story:{en:"Kaluga is the beluga's eastern cousin, the other giant Huso, native to the Amur and reaching the same grain calibre. Almost all of it now comes from farms at Qiandao Lake in Zhejiang, frequently as a cross with the Amur sturgeon — the shift that made China the largest caviar producer in the world.",
fr:"Le kaluga est le cousin oriental du beluga, l'autre Huso géant, natif du fleuve Amour et capable du même calibre de grain. Il vient aujourd'hui presque entièrement des fermes du lac Qiandao, au Zhejiang, souvent sous forme de croisement avec l'esturgeon de l'Amour — le basculement qui a fait de la Chine le premier producteur mondial de caviar."},
tip:{en:"Its shell is firmer than beluga's, so it survives contact with something warm: it is the large-grain caviar to spoon over a hot ratte or soft scrambled eggs without the grains collapsing.",
fr:"Sa membrane est plus ferme que celle du beluga et supporte le contact d'un plat chaud : c'est le gros grain qu'on peut déposer sur une ratte tiède ou des œufs brouillés sans le voir s'affaisser."},
pairs:["ratte-potato","egg","creme-epaisse","chives","butter","lemon"],
svg:'<path class="f2 sf" d="M24 46h48v18q0 6-6 6H30q-6 0-6-6z"/><ellipse class="f3 sf" cx="48" cy="46" rx="24" ry="9"/><path class="s" d="M26 58h44"/><circle class="f1 sf" cx="42" cy="44" r="4"/><circle class="f1 sf" cx="54" cy="47" r="4"/>'},

{id:"kazunoko",cat:"roe",rare:true,name:{en:"Kazunoko",fr:"Kazunoko (œufs de hareng)"},latin:"Clupea pallasii (roe)",
origin:{en:"North Pacific herring grounds",fr:"Pêcheries de hareng du Pacifique Nord"},season:[1,12],
flavor:["briny","umami","marine","mild"],
story:{en:"The name reads as child of number: one sac holds tens of thousands of eggs, which is why kazunoko sits in the New Year osechi box as a wish for descendants. It is bought as much for its sound as its taste — the eggs stay bound together in the sac and crack between the teeth instead of bursting.",
fr:"Le nom se lit enfant du nombre : une seule poche contient des dizaines de milliers d'œufs, ce qui vaut au kazunoko sa place dans la boîte osechi du Nouvel An comme vœu de descendance. On l'achète autant pour le bruit que pour le goût : les grains restent soudés en poche et craquent sous la dent au lieu d'éclater."},
tip:{en:"Desalt it in a light 1 % brine, changed twice over a day, rather than plain water — fresh water pulls the salt out too fast and leaves a bitter edge. Then marinate a full day in dashi with soy and mirin.",
fr:"Dessalez-le dans une saumure légère à 1 %, renouvelée deux fois sur une journée, plutôt qu'à l'eau claire : l'eau pure tire le sel trop vite et laisse une amertume. Marinez ensuite une journée entière dans un dashi additionné de soja et de mirin."},
pairs:["katsuobushi","soy-sauce","kombu","hon-mirin","junmai-sake","daikon"],
svg:'<path class="f1 sf" d="M26 44q18-8 44-2 8 2 6 8t-10 8q-24 6-40-2-6-4 0-12z"/><path class="s" d="M32 47q20 8 40 2M30 56q22 6 42-2"/><circle class="dot" cx="40" cy="52" r="1.5"/><circle class="dot" cx="52" cy="49" r="1.5"/><circle class="dot" cx="62" cy="54" r="1.5"/>'},

{id:"oeufs-de-lump",cat:"roe",name:{en:"Lumpfish roe",fr:"Œufs de lump"},latin:"Cyclopterus lumpus (roe)",
origin:{en:"Iceland and Greenland",fr:"Islande et Groenland"},season:[],
flavor:["salty","briny","marine"],
story:{en:"Lumpfish roe comes out of the fish a dull grey-pink and is dyed before it ever reaches a jar, black with cuttlefish ink or red with a food colour. It is then pasteurised, which is why an unopened jar keeps for a year and why the grains are firm and slightly rubbery rather than fragile.",
fr:"Les œufs de lump sortent du poisson d'un gris rosé terne et sont teintés avant même la mise en pot, en noir à l'encre de seiche ou en rouge par un colorant. Ils sont ensuite pasteurisés : d'où un pot fermé qui se garde un an, et un grain ferme, un peu élastique, plutôt que fragile."},
tip:{en:"Add them at the very last moment and never stir them into anything pale. The dye bleeds on contact with acid, moisture or heat, and will grey out a cream or a potato salad within minutes.",
fr:"Ajoutez-les au tout dernier moment et ne les mélangez jamais à une préparation claire : le colorant dégorge au contact de l'acide, de l'humidité ou de la chaleur, et grise une crème ou une salade de pommes de terre en quelques minutes."},
pairs:["potato","creme-fraiche","egg","cucumber","dill","lemon","rye"],
svg:'<path class="f1 sf" d="M32 40h32v28q0 5-5 5H37q-5 0-5-5z"/><path class="f2 sf" d="M30 28h36v12H30z"/><path class="f3" d="M36 48h24v18H36z"/><path class="s" d="M36 44h24"/>'},

{id:"masago",cat:"roe",name:{en:"Masago",fr:"Masago (œufs de capelan)"},latin:"Mallotus villosus (roe)",
origin:{en:"Iceland and Newfoundland",fr:"Islande et Terre-Neuve"},season:[],
flavor:["briny","salty","bitter","marine"],
story:{en:"Masago is capelin roe, from a small Arctic forage fish netted by the million off Iceland and Newfoundland — the same fish that feeds the cod swimming above it. It is routinely coloured and sold as tobiko, though the eggs are smaller, softer and faintly bitter, and they behave differently the moment they meet a sauce.",
fr:"Le masago est l'œuvre du capelan, petit poisson fourrage arctique pêché par millions au large de l'Islande et de Terre-Neuve — celui-là même qui nourrit la morue au-dessus de lui. On le colore couramment pour le vendre comme tobiko, alors que ses grains sont plus petits, plus mous, légèrement amers, et qu'ils réagissent tout autrement dès qu'ils rencontrent une sauce."},
tip:{en:"Because the grains break, use it stirred into mayonnaise or a spicy dressing where tobiko would be wasted. Keep tobiko for the top of the roll and masago for the inside.",
fr:"Comme les grains éclatent, employez-le mélangé à une mayonnaise ou à une sauce relevée, là où le tobiko serait gâché. Gardez le tobiko pour le dessus du maki et le masago pour l'intérieur."},
pairs:["rice","nori","cucumber","avocado","sesame","soy-sauce","spring-onion"],
svg:'<path class="f1 sf" d="M22 58h52q-4 12-26 12T22 58z"/><path class="f2 sf" d="M28 58q6-14 20-14t20 14z"/><circle class="dot" cx="38" cy="52" r="1.6"/><circle class="dot" cx="48" cy="48" r="1.6"/><circle class="dot" cx="58" cy="53" r="1.6"/><circle class="dot" cx="78" cy="66" r="1.6"/>'},

{id:"mentaiko",cat:"roe",rare:true,name:{en:"Mentaiko",fr:"Mentaiko (œufs de colin marinés)"},latin:"Gadus chalcogrammus (roe)",
origin:{en:"Fukuoka, Japan",fr:"Fukuoka, Japon"},season:[],
flavor:["salty","umami","hot","marine"],
story:{en:"Karashi mentaiko was worked out in Fukuoka in 1949 by Kawahara Toshio, who had grown up in Busan and spent years rebuilding the Korean myeongnan-jeot he remembered, with less salt and a chilli cure pitched at Japanese palates. Even the name is borrowed: mentai comes from myeongtae, the Korean word for pollock.",
fr:"Le karashi mentaiko a été mis au point à Fukuoka en 1949 par Kawahara Toshio, qui avait grandi à Busan et passa des années à reconstituer le myeongnan-jeot coréen de son enfance, moins salé et relevé d'un piment ajusté au goût japonais. Le nom lui-même est emprunté : mentai vient de myeongtae, le nom coréen du colin."},
tip:{en:"Split the sac and scrape the roe off the membrane with the back of a knife, then fold it into hot pasta or soft butter off the heat. A minute of direct heat turns it grainy and a dull pink.",
fr:"Fendez la poche et raclez les œufs de la membrane avec le dos d'un couteau, puis incorporez-les hors du feu à des pâtes chaudes ou à un beurre pommade. Une minute de feu direct les rend granuleux et d'un rose terne."},
pairs:["rice","butter","nori","spring-onion","cream","soy-sauce","egg","shiso"],
svg:'<path class="f2 sf" d="M24 52q6-14 22-12t14 10-8 14-22 2-6-14z"/><path class="f1 sf" d="M52 58q10-14 22-6t-4 18-20-4z"/><path class="s" d="M30 48q10 8 22 6M58 60q8 2 12 8"/><circle class="dot" cx="36" cy="54" r="1.6"/><circle class="dot" cx="46" cy="50" r="1.6"/><circle class="dot" cx="64" cy="63" r="1.6"/>'},

{id:"oursin-murasaki",cat:"roe",rare:true,luxe:true,name:{en:"Murasaki uni",fr:"Oursin murasaki"},latin:"Heliocidaris crassispina",
origin:{en:"Warm coasts of western Japan",fr:"Côtes chaudes de l'ouest du Japon"},season:[6,7,8,9],
flavor:["creamy","marine","sweet","delicate"],
story:{en:"Murasaki is the long-spined purple urchin of warmer Japanese water, and its tongues of roe come out larger, paler and gentler than the deep orange bafun. Chefs name the species and often the bay, never simply uni, because the two ripen in opposite halves of the year and taste nothing alike.",
fr:"Le murasaki est l'oursin violet à longues épines des eaux japonaises tempérées, et ses langues de gonade sortent plus grandes, plus pâles et plus douces que celles du bafun, d'un orange soutenu. Les chefs nomment l'espèce, souvent la baie, jamais un simple uni : les deux mûrissent aux saisons opposées et n'ont rien du même goût."},
tip:{en:"Buy it in the wooden ita trays only if the tongues hold a clean edge. Slumping, weeping uni has been dosed with alum to firm it, and that leaves a metallic bitterness no amount of rice will cover.",
fr:"N'achetez les plateaux de bois ita que si les langues gardent une arête nette. Un uni affaissé et suintant a été traité à l'alun pour le raffermir, ce qui laisse une amertume métallique qu'aucun riz ne masque."},
pairs:["rice","nori","wasabi","sudachi","junmai-sake","soy-sauce"],
svg:'<path class="f2 sf" d="M22 50a26 26 0 0 1 52 0q-4 15-26 15T22 50z"/><path class="s" d="M22 50l-9-5M31 34l-6-10M48 27V15M65 34l6-10M74 50l9-5"/><path class="f1 sf" d="M33 46q6-9 12 0t-6 9-6-9z"/><path class="f1 sf" d="M51 46q6-9 12 0t-6 9-6-9z"/>'},

{id:"caviar-oscietre",cat:"roe",luxe:true,name:{en:"Osetra caviar",fr:"Caviar osciètre"},latin:"Acipenser gueldenstaedtii (roe)",
origin:{en:"Caspian and Black Sea basins",fr:"Bassins caspien et de la mer Noire"},season:[],
flavor:["nutty","marine","buttery","rich"],
story:{en:"Osetra is simply the Russian word for sturgeon, and the grain runs from near-black to the pale amber that trade calls imperial — a colour that comes with the age of the fish rather than with quality, though it is priced as though it were the same thing. It remains the reference caviar of French service: firm shell, walnut finish, a grain that survives a warm spoon.",
fr:"Osciètre n'est que le mot russe pour esturgeon, et le grain va du presque noir à l'ambre pâle que le négoce appelle impérial — une couleur qui tient à l'âge du poisson, non à sa qualité, même si elle se paie comme telle. Il reste le caviar de référence du service à la française : membrane ferme, finale de noix, un grain qui supporte une cuillère tiède."},
tip:{en:"Let the tin come to about 12 °C before opening — half an hour out of the fridge — and taste it flat on the back of the hand. Served ice-cold it reads salty and surrenders the walnut entirely.",
fr:"Laissez la boîte revenir vers 12 °C avant de l'ouvrir, une demi-heure hors du réfrigérateur, et goûtez-le à plat sur le dos de la main. Servi glacé, il ne donne que du sel et abandonne toute sa noix."},
pairs:["beurre-de-baratte","egg","potato","creme-fraiche","chives","vin-jaune"],
svg:'<ellipse class="f1 sf" cx="38" cy="58" rx="18" ry="12"/><path class="s" d="M55 51q10-6 19-15"/><path class="f3 sf" d="M24 55q7-11 21-9t9 9q-14 7-30 0z"/><circle class="dot" cx="34" cy="51" r="2"/><circle class="dot" cx="44" cy="50" r="2"/>'},

{id:"caviar-polyodon",cat:"roe",rare:true,name:{en:"Paddlefish caviar",fr:"Caviar de polyodon"},latin:"Polyodon spathula (roe)",
origin:{en:"Mississippi basin, United States",fr:"Bassin du Mississippi, États-Unis"},season:[],
flavor:["earthy","marine","mild","creamy"],
story:{en:"The paddlefish is not a sturgeon at all: it sits in its own family, filters plankton through a rostrum nearly a third of its own length, and lives in the Mississippi basin. Its roe travels under the CITES species code SPA, and those three letters are how you tell a legitimate tin from one quietly calling itself something dearer.",
fr:"Le polyodon n'est pas un esturgeon : il forme sa propre famille, filtre le plancton avec un rostre représentant près du tiers de sa longueur et vit dans le bassin du Mississippi. Ses œufs circulent sous le code d'espèce CITES SPA, et ces trois lettres sont ce qui distingue une boîte honnête de celle qui se fait discrètement passer pour plus cher."},
tip:{en:"It is softer than sturgeon roe and goes flat within a day of opening, so buy the small tin. Its earthy side holds up better against warm potato and soured cream than against a plain blini.",
fr:"Plus tendre que l'œuf d'esturgeon, il s'affadit en une journée une fois ouvert : achetez la petite boîte. Son côté terreux tient mieux face à une pomme de terre tiède et à de la crème acidulée qu'à un blini nature."},
pairs:["egg","potato","creme-fraiche","chives","cucumber","dill"],
svg:'<path class="f1 sf" d="M30 50h36q0 14-18 14t-18-14z"/><path class="f3 sf" d="M30 50q6-13 18-13t18 13z"/><path class="s" d="M48 64v8M36 74h24"/><circle class="dot" cx="42" cy="45" r="2"/><circle class="dot" cx="53" cy="43" r="2"/>'},

{id:"caviar-presse",cat:"roe",rare:true,name:{en:"Pressed caviar",fr:"Caviar pressé (payusnaya)"},latin:"Acipenser spp. (pressed roe)",
origin:{en:"Caspian tradition, Astrakhan",fr:"Tradition caspienne, Astrakhan"},season:[],
flavor:["salty","rich","umami","marine"],
story:{en:"Payusnaya is built from the grains that burst on the sieve: salted, drained in muslin and compressed into a dark slab, with several kilos of roe going into each kilo of block. It was never the lesser product in Russia — it kept for months where loose grain kept for weeks, which made it the caviar that could travel.",
fr:"Le payusnaya se fait avec les grains qui crèvent au tamis : salés, égouttés dans une mousseline, puis comprimés en une dalle sombre, plusieurs kilos d'œufs pour un kilo de bloc. En Russie, il n'a jamais été le parent pauvre : il se gardait des mois là où le grain libre tenait des semaines, ce qui en faisait le caviar capable de voyager."},
tip:{en:"Slice it cold with a hot blade into sheets, or melt a spoonful into a warm butter sauce. It is the one caviar that takes heat without loss, because its grains are already broken.",
fr:"Tranchez-le froid, à la lame chaude, en fines feuilles, ou faites fondre une cuillerée dans un beurre monté. C'est le seul caviar qui accepte la chaleur sans rien perdre : ses grains sont déjà rompus."},
pairs:["butter","rye","egg","shallot","creme-fraiche","black-pepper"],
svg:'<ellipse class="f3 sf" cx="44" cy="42" rx="22" ry="9"/><path class="f3 sf" d="M22 42v14q0 9 22 9t22-9V42"/><path class="s" d="M30 46q14 5 28 0"/><path class="f2 sf" d="M58 72q12-7 20-3-8 9-20 7z"/>'},

{id:"chevreuil",cat:"roe",luxe:true,name:{en:"Roe deer",fr:"Chevreuil"},latin:"Capreolus capreolus",
origin:{en:"European woodland edge",fr:"Lisières forestières d’Europe"},season:[9,10,11,12,1],
flavor:["delicate","mild","meaty","earthy"],
story:{en:"The roe is the only hoofed animal in Europe with delayed implantation: it mates in July and the embryo lies dormant until December, so the fawn arrives in spring. The carcass is small — twenty kilos or less — and the meat correspondingly fine-grained and barely gamey.",
fr:"Le chevreuil est le seul ongulé d’Europe à pratiquer la diapause embryonnaire : il s’accouple en juillet et l’embryon reste dormant jusqu’en décembre, pour que le faon naisse au printemps. La carcasse est petite — vingt kilos ou moins — et la chair d’autant plus fine et à peine gibier."},
tip:{en:"A saddle or a loin needs four minutes a side and a rest, no more. The long juniper-and-red-wine marinade that red deer expects bruises and sours it — roe is better with butter and pepper alone.",
fr:"Une selle ou un filet demandent quatre minutes par face et un repos, pas davantage. La longue marinade genièvre-vin rouge que réclame le cerf le meurtrit et l’aigrit : le chevreuil est meilleur au beurre et au poivre, seuls."},
pairs:["blackcurrant","chestnut","celeriac","butter","quince","black-pepper","cream","mushroom"],
svg:'<path class="f1 sf" d="M40 46q8-4 16 0 4 10 2 18-2 12-10 12t-10-12q-2-8 2-18z"/><path class="s" d="M44 44V31l-4-6M44 34l5-7M52 44V31l4-6M52 34l-5-7" stroke-width="1.8"/><path class="f2 sf" d="M40 48q-13-9-15-2t13 10zM56 48q13-9 15-2t-13 10z"/><path class="dot" d="M42 57a2 2 0 104 0 2 2 0 10-4 0M50 57a2 2 0 104 0 2 2 0 10-4 0"/><path class="s" d="M45 70q3 3 6 0"/>'},

{id:"caviar-schrenckii",cat:"roe",luxe:true,name:{en:"Schrenckii caviar",fr:"Caviar schrenckii"},latin:"Acipenser schrenckii (roe)",
origin:{en:"Amur basin & Chinese farms",fr:"Bassin de l’Amour et fermes chinoises"},season:[],
flavor:["briny","marine","mild","umami"],
story:{en:"The Amur sturgeon is named for the river that divides Russia from China, and its roe is the backbone of a Chinese industry that in 2017 produced over a hundred of the world’s roughly 360 tonnes of caviar. A trade the Caspian held for two centuries moved east in barely one decade.",
fr:"L’esturgeon de l’Amour porte le nom du fleuve qui sépare la Russie de la Chine, et ses œufs sont la colonne vertébrale d’une industrie chinoise qui produisait en 2017 plus de cent des quelque 360 tonnes de caviar du monde. Un commerce que la Caspienne a tenu deux siècles a basculé vers l’est en une décennie."},
tip:{en:"The grain has an unusually tough membrane, which makes it the caviar that survives a warm base — a quenelle on hot potato or a just-set custard reaches the table intact. Serve it at 8-10 °C, never colder, or the taste closes up.",
fr:"Le grain a une membrane exceptionnellement résistante : c’est le caviar qui supporte un support tiède — une quenelle sur une pomme de terre chaude ou un flan tout juste pris arrive intacte à table. Servez-le entre 8 et 10 °C, jamais plus froid, sinon le goût se referme."},
pairs:["potato","creme-fraiche","egg","chives","butter","scallop","vin-jaune"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="24"/><circle class="s" cx="48" cy="52" r="18"/><circle class="dot" cx="42" cy="46" r="2.6"/><circle class="dot" cx="53" cy="47" r="2.6"/><circle class="dot" cx="47" cy="56" r="2.6"/><circle class="dot" cx="57" cy="57" r="2.6"/>'},

{id:"caviar-sevruga",cat:"roe",luxe:true,name:{en:"Sevruga caviar",fr:"Caviar sévruga"},latin:"Acipenser stellatus (roe)",
origin:{en:"Caspian & Black Sea",fr:"Caspienne et mer Noire"},season:[],
flavor:["briny","salty","marine","umami"],
story:{en:"Stellatus means starry — the fish carries star-shaped bony plates along its flanks and a snout like a blade. It ripens in about seven years where beluga needs twenty, which once made it the cheapest of the Caspian three and now, with the wild stock collapsed, one of the hardest to find.",
fr:"Stellatus veut dire étoilé : le poisson porte des plaques osseuses en étoile le long des flancs et un rostre en lame de couteau. Il mûrit en sept ans là où le béluga en demande vingt, ce qui en fit longtemps le moins cher des trois caspiens et, le stock sauvage effondré, l’un des plus difficiles à trouver aujourd’hui."},
tip:{en:"Its grain is the smallest and most saline of the classic three, so it is the one to use when the caviar has to be tasted through something else — in a cream, a beurre blanc, on a warm blini. Never a metal spoon: bone, horn or nacre, or you taste the metal.",
fr:"Son grain est le plus petit et le plus iodé des trois classiques : c’est celui qu’on choisit quand le caviar doit se faire entendre à travers autre chose — dans une crème, un beurre blanc, sur un blini tiède. Jamais de cuillère en métal : corne, os ou nacre, sinon vous goûtez le métal."},
pairs:["creme-fraiche","egg","butter","lemon","shallot","sturgeon"],
svg:'<path class="f1 sf" d="M26 44q0-12 14-12t14 12q0 12-14 12t-14-12z"/><path class="s" d="M54 40l18 22"/><circle class="dot" cx="35" cy="40" r="2"/><circle class="dot" cx="43" cy="38" r="2"/><circle class="dot" cx="39" cy="46" r="2"/><circle class="dot" cx="47" cy="45" r="2"/>'},

{id:"oeufs-d-alose",cat:"roe",rare:true,name:{en:"Shad roe",fr:"Œufs d’alose"},latin:"Alosa spp. (roe)",
origin:{en:"Atlantic rivers",fr:"Fleuves atlantiques"},season:[3,4,5],
flavor:["rich","meaty","mild","earthy"],
story:{en:"Shad run up rivers to spawn each spring, and the roe comes out as a pair of lobes joined by a membrane — sold, priced and cooked as one piece. John McPhee called it America’s founding fish for how much of it the colonies ate; in France the same run once fed every town along the Loire and the Gironde.",
fr:"L’alose remonte les fleuves pour frayer au printemps, et les œufs sortent en deux lobes réunis par une membrane — vendus, tarifés et cuits d’une seule pièce. John McPhee l’a surnommée « le poisson fondateur » de l’Amérique tant les colonies en vivaient ; en France, la même montaison a nourri chaque bourg de la Loire et de la Gironde."},
tip:{en:"Prick the membrane in a few places or the lobes burst in the pan. Six to eight minutes over gentle heat in butter or bacon fat, turned once — pushed further it goes chalky and there is no way back.",
fr:"Piquez la membrane en quelques points, sinon les lobes éclatent à la poêle. Six à huit minutes à feu doux dans du beurre ou de la graisse de poitrine fumée, retournés une seule fois : poussés plus loin, ils deviennent crayeux et rien ne les rattrape."},
pairs:["butter","lemon","parsley","sorrel","poitrine-fumee","capers","shallot"],
svg:'<path class="f2 sf" d="M46 22q-14 8-16 26 0 20 16 26 4-14 4-26t-4-26z"/><path class="f3 sf" d="M50 22q14 8 16 26 0 20-16 26-4-14-4-26t4-26z"/><path class="s" d="M38 36q4 10 2 22M58 36q-4 10-2 22"/>'},

{id:"shirako",cat:"roe",rare:true,name:{en:"Shirako",fr:"Shirako (laitance de morue)"},latin:"Gadus macrocephalus (milt)",
origin:{en:"Hokkaido",fr:"Hokkaidō"},season:[11,12,1,2],
flavor:["creamy","rich","delicate","marine"],
story:{en:"Cod milt, sold only while the fish is in spawning condition — roughly November to February. Hokkaido calls it tachi, Kyoto calls it kumoko, the cloud child, for the folded white shape.",
fr:"Laitance de morue, vendue seulement tant que le poisson est en frai — de novembre à février, en gros. Hokkaidō l’appelle tachi, Kyoto l’appelle kumoko, l’enfant nuage, pour sa forme blanche et repliée."},
tip:{en:"Blanch it thirty seconds in salted water with a splash of sake before anything else: the membrane firms so the lobes hold together, and the faint metallic edge goes. Then ponzu, or a hot grill with salt — a long cook curdles it.",
fr:"Blanchissez-la trente secondes à l’eau salée avec un trait de saké avant toute chose : la membrane se raffermit, les lobes tiennent ensemble et la pointe métallique disparaît. Ensuite ponzu, ou gril brûlant et sel — une cuisson longue la fait cailler."},
pairs:["ponzu","yuzu","daikon","negi","junmai-sake","chives","shiso"],
svg:'<path class="f1 sf" d="M26 52q-2-16 14-20 10-3 16 4 12-4 16 8 4 14-10 20-16 8-26 2-8-5-10-14z"/><path class="s" d="M34 44q6 6 2 12 6 2 8 10M50 40q-4 8 2 12-4 6 0 12M60 46q-6 4-2 10 4 4 0 10"/>'},

{id:"oeufs-de-cabillaud-fumes",cat:"roe",name:{en:"Smoked cod roe",fr:"Œufs de cabillaud fumés"},latin:"Gadus morhua (smoked roe)",
origin:{en:"North Sea & Baltic",fr:"Mer du Nord et Baltique"},season:[],
flavor:["smoky","salty","umami","briny"],
story:{en:"The Greek meze that made it famous takes its name from tarama, an Ottoman Turkish word for fish roe borrowed in turn from Persian, and it was Lenten food before it was a dip. Carp and mullet roe came first; cod is the northern substitute, the one that travelled.",
fr:"Le mezzé grec qui l’a rendu célèbre tient son nom du tarama, mot turc ottoman pour la rogue de poisson, lui-même emprunté au persan, et c’était une nourriture de carême avant d’être une entrée. La carpe et le mulet sont venus d’abord ; le cabillaud est le substitut du Nord, celui qui a voyagé."},
tip:{en:"Peel the sac before blending or you keep the grit — slit the membrane and scrape the roe out with a spoon. Then work it like mayonnaise: soaked bread or potato first, lemon, oil in a thread, and stop the moment it pales and stiffens.",
fr:"Pelez la poche avant de mixer, sinon vous garderez du grain sous la dent : fendez la membrane et raclez les œufs à la cuillère. Ensuite travaillez comme une mayonnaise — mie trempée ou pomme de terre d’abord, citron, puis l’huile en filet, et arrêtez dès que la masse pâlit et raidit."},
pairs:["olive-oil","lemon","potato","garlic","red-onion","dill","cucumber"],
svg:'<path class="f2 sf" d="M48 20q6 10 4 18 12 10 12 26 0 14-16 14t-16-14q0-16 12-26 2-8 4-18z"/><path class="s" d="M42 38q6 3 12 0"/><path class="s" d="M40 56q8 5 16 0M38 66q10 5 20 0"/>'},

{id:"caviar-sterlet",cat:"roe",rare:true,name:{en:"Sterlet caviar",fr:"Caviar sterlet"},latin:"Acipenser ruthenus (roe)",
origin:{en:"Volga & Danube",fr:"Volga et Danube"},season:[],
flavor:["nutty","delicate","mild","creamy"],
story:{en:"Before Russia reached the Caspian and its giant sturgeons, the caviar it sold to the courts of Europe through the eighteenth and nineteenth centuries came from the Volga sterlet — a fish rarely a metre long, called the tsar fish for the table it was kept for. It ripens in a handful of years where beluga needs twenty, which is why it is the sturgeon small European farms now stock.",
fr:"Avant que la Russie n’atteigne la Caspienne et ses esturgeons géants, le caviar qu’elle vendait aux cours d’Europe aux XVIIIe et XIXe siècles venait du sterlet de la Volga — un poisson qui dépasse rarement le mètre, appelé poisson du tsar pour la table à laquelle on le réservait. Il mûrit en quelques années là où le béluga en demande vingt : c’est l’esturgeon des petites fermes européennes d’aujourd’hui."},
tip:{en:"The grain is thin-skinned and collapses at the first sign of heat, so it goes on cold or barely warm and last of all. Its salt is low, which means it keeps for days rather than weeks — buy it for the meal you are cooking.",
fr:"Le grain est à peau fine et s’effondre au premier signe de chaleur : il se pose froid ou tout juste tiède, et en dernier. Sa salaison est basse, donc il se garde des jours et non des semaines — achetez-le pour le repas que vous cuisinez."},
pairs:["creme-fraiche","potato","egg","butter","cucumber","hazelnut","dill"],
svg:'<path class="f1 sf" d="M34 40h28v26q0 8-14 8t-14-8z"/><path class="s" d="M30 40h36M38 32h20v8H38z"/><circle class="dot" cx="42" cy="52" r="1.8"/><circle class="dot" cx="50" cy="50" r="1.8"/><circle class="dot" cx="57" cy="54" r="1.8"/><circle class="dot" cx="46" cy="60" r="1.8"/>'},

{id:"sujiko",cat:"roe",rare:true,name:{en:"Sujiko",fr:"Sujiko (œufs de saumon en poche)"},latin:"Oncorhynchus spp. (roe sac)",
origin:{en:"Hokkaido & Tohoku",fr:"Hokkaidō et Tōhoku"},season:[9,10,11],
flavor:["salty","rich","umami","briny"],
story:{en:"Suji is the streak of membrane still holding the eggs: roe taken before it ripens and salted inside its sac, so it stays smaller, darker and denser than loose grain. The loose version took a foreign name — ikura is Russian, икра, brought back by Japanese fishermen in the early twentieth century — while the older sac form kept its Japanese one.",
fr:"Suji, c’est le fil de membrane qui tient encore les œufs : une rogue prélevée avant maturité et salée dans sa poche, donc plus petite, plus sombre et plus dense que le grain détaché. La version libre a pris un nom étranger — ikura vient du russe икра, rapporté par les pêcheurs japonais au début du XXe siècle — tandis que la forme en poche, plus ancienne, a gardé le sien."},
tip:{en:"Slice it across the sac a centimetre thick and lay it on hot rice — the membrane holds the block together and anything thinner falls apart. It is saltier than ikura by design, so serve half as much.",
fr:"Tranchez le bloc en travers, un centimètre d’épaisseur, et posez-le sur du riz chaud : la membrane tient l’ensemble et plus fin, tout se défait. Il est plus salé que l’ikura par construction — servez-en moitié moins."},
pairs:["rice","nori","shiso","daikon","junmai-sake","wasabi","kombu"],
svg:'<path class="f3 sf" d="M24 38h44q4 0 4 6v18q0 6-6 6H26q-4 0-4-6V44q0-6 2-6z"/><path class="s" d="M56 38v30"/><circle class="dot" cx="34" cy="48" r="2.4"/><circle class="dot" cx="44" cy="52" r="2.4"/><circle class="dot" cx="36" cy="60" r="2.4"/><circle class="dot" cx="48" cy="61" r="2.4"/>'},

{id:"tobiko",cat:"roe",name:{en:"Tobiko",fr:"Tobiko (œufs de poisson volant)"},latin:"Cheilopogon spp. (roe)",
origin:{en:"Japan & Southeast Asia",fr:"Japon et Asie du Sud-Est"},season:[],
flavor:["briny","salty","mild","marine"],
story:{en:"Flying fish spawn onto anything floating, so the roe is taken from rafts of straw and palm frond set out for them rather than from the fish — the egg mats are lifted off and washed clean. The wasabi, yuzu and squid-ink colours are dyes added afterwards; the roe itself is a dull orange.",
fr:"Le poisson volant fraye sur tout ce qui flotte : on récolte donc ses œufs sur des radeaux de paille et de palme posés pour lui, et non dans le poisson — les nappes d’œufs sont soulevées puis rincées. Les couleurs wasabi, yuzu et encre de seiche sont des colorants ajoutés ensuite ; l’œuf lui-même est d’un orange terne."},
tip:{en:"Add it at the very end and off the heat: the shell is what you are buying, and it softens within a minute in anything hot. Folded through cold mayonnaise or crème fraîche it keeps its crunch for hours.",
fr:"Ajoutez-le tout à la fin et hors du feu : c’est la coque que vous achetez, et elle s’amollit en une minute dans n’importe quoi de chaud. Mêlé à une mayonnaise ou une crème fraîche froide, il garde son croquant des heures."},
pairs:["rice","nori","cucumber","avocado","wasabi","sesame","soy-sauce"],
svg:'<path class="f3 sf" d="M28 52h40v20q0 4-4 4H32q-4 0-4-4z"/><path class="f1 sf" d="M28 52q6-10 20-10t20 10q-10 6-20 6t-20-6z"/><circle class="dot" cx="38" cy="48" r="1.4"/><circle class="dot" cx="45" cy="45" r="1.4"/><circle class="dot" cx="53" cy="46" r="1.4"/><circle class="dot" cx="59" cy="50" r="1.4"/>'},

{id:"oeufs-de-truite",cat:"roe",name:{en:"Trout roe",fr:"Œufs de truite"},latin:"Oncorhynchus mykiss (roe)",
origin:{en:"Trout farms, Aquitaine & the Alps",fr:"Élevages de truite, Aquitaine et Alpes"},season:[10,11,12,1],
flavor:["briny","sweet","delicate","mild"],
story:{en:"The rainbow trout is a Californian fish, shipped to European hatcheries in the 1880s and now the backbone of freshwater farming from the Pyrenees to Denmark. Its roe is stripped from live females that go back in the water, which is the whole difference between this and caviar.",
fr:"La truite arc-en-ciel est un poisson californien, expédié aux écloseries européennes dans les années 1880 et devenu l’ossature de la pisciculture d’eau douce, des Pyrénées au Danemark. Ses œufs sont pressés sur des femelles vivantes qui retournent à l’eau : c’est toute la différence avec le caviar."},
tip:{en:"The cure is light and holds far less salt than salmon roe, so spoon it in where ikura would be too oily — into a hot potato, over a soft-boiled egg, across a beurre blanc. Once opened it lasts about four days, and do not salt it further: it is already at the limit.",
fr:"La salaison est légère et retient bien moins de sel que la rogue de saumon : servez-la à la cuillère là où l’ikura serait trop grasse — dans une pomme de terre chaude, sur un œuf mollet, sur un beurre blanc. Une fois ouverte elle tient environ quatre jours, et ne la salez pas davantage : elle est déjà à la limite."},
pairs:["egg","potato","creme-fraiche","chives","cucumber","butter","dill"],
svg:'<circle class="f1 sf" cx="36" cy="42" r="11"/><circle class="f1 sf" cx="58" cy="40" r="10"/><circle class="f1 sf" cx="46" cy="62" r="12"/><circle class="f1 sf" cx="66" cy="60" r="9"/><circle class="dot" cx="34" cy="40" r="2.4"/><circle class="dot" cx="44" cy="60" r="2.4"/>'},

{id:"poutargue-de-thon",cat:"roe",rare:true,name:{en:"Tuna bottarga",fr:"Poutargue de thon"},latin:"Thunnus thynnus (roe)",
origin:{en:"Sicily & Sardinia",fr:"Sicile et Sardaigne"},season:[],
flavor:["umami","salty","meaty","rich"],
story:{en:"The trap fisheries of western Sicily took bluefin on their spawning run, and the roe of the trapped females was salted and pressed into slabs; the great tonnara of Favignana ran from 1859 until it closed in 1977. What comes out is darker, meatier and far louder than mullet bottarga — the same technique on a fish twenty times the size.",
fr:"Les tonnare de Sicile occidentale prenaient le thon rouge sur sa montaison de frai, et la rogue des femelles piégées était salée puis pressée en plaques ; la grande tonnara de Favignana a tourné de 1859 jusqu’à sa fermeture en 1977. Ce qui en sort est plus sombre, plus carné et bien plus sonore que la poutargue de mulet — la même technique sur un poisson vingt fois plus gros."},
tip:{en:"Grate it, do not shave it — the block is coarser and drier than mullet, and a slice sits on the tongue like leather. It will carry a dish that already has garlic, chilli and breadcrumbs in it, where mullet bottarga would vanish.",
fr:"Râpez-la, ne la tranchez pas : le bloc est plus grossier et plus sec que le mulet, et un copeau reste sur la langue comme du cuir. Elle porte un plat qui contient déjà ail, piment et chapelure, là où la poutargue de mulet disparaîtrait."},
pairs:["olive-oil","garlic","lemon","chili","parsley","tomato","olive-taggiasca","celery"],
svg:'<path class="f3 sf" d="M24 38l38-10q4-1 5 3l7 24q1 4-3 5l-38 10q-4 1-5-3l-7-24q-1-4 3-5z"/><path class="s" d="M30 42l36-9M33 54l36-9"/><path class="s" d="M28 76q10-6 20-2M34 82q10-5 20-1"/>'},

{id:"oeufs-de-coregone",cat:"roe",rare:true,name:{en:"Vendace roe",fr:"Œufs de corégone"},latin:"Coregonus albula (roe)",
origin:{en:"Bothnian Bay, Sweden",fr:"Golfe de Botnie, Suède"},season:[9,10],
flavor:["sweet","delicate","briny","mild"],
story:{en:"Kalix löjrom took a European protected designation in 2010, one of a handful Sweden holds, and the fishery runs for a regulated five weeks from around the twentieth of September. The brackish water of the Bothnian Bay is what makes it orange — vendace caught in fresh water give roe that is plainly yellow.",
fr:"Le kalix löjrom a obtenu une appellation d’origine protégée européenne en 2010, l’une des rares que possède la Suède, et la pêche ne dure que cinq semaines réglementées à partir du 20 septembre environ. C’est l’eau saumâtre du golfe de Botnie qui le rend orange — le corégone pris en eau douce donne une rogue franchement jaune."},
tip:{en:"Serve it cold on a warm blini with sour cream and finely diced red onion, and cut the onion at the last second so its juice never sits on the grain.",
fr:"Servez-le froid sur un blini tiède avec crème aigre et oignon rouge en dés minuscules, et taillez l’oignon à la dernière seconde pour que son jus ne séjourne jamais sur le grain."},
pairs:["creme-fraiche","red-onion","dill","potato","butter","rye","lemon"],
svg:'<ellipse class="f1 sf" cx="48" cy="66" rx="26" ry="9"/><path class="f2 sf" d="M26 64q4-18 22-18t22 18q-10 6-22 6t-22-6z"/><circle class="s" cx="48" cy="40" r="7"/><circle class="dot" cx="40" cy="56" r="1.6"/><circle class="dot" cx="48" cy="53" r="1.6"/><circle class="dot" cx="56" cy="56" r="1.6"/>'},

{id:"vendace-roe",cat:"roe",luxe:true,name:{en:"Vendace roe (Kalix löjrom)",fr:"Œufs de corégone (Kalix löjrom)"},latin:"Coregonus albula",
origin:{en:"Bothnian Bay, Kalix",fr:"Golfe de Botnie, Kalix"},season:[9,10],
flavor:["nutty","briny","delicate","creamy"],
story:{en:"The Bothnian Bay is brackish enough to turn the eggs orange — the same fish in fresh water gives yellow roe — and that colour, with the feed behind it, is what the 2010 protected designation on Kalix löjrom actually defends. The whole year's catch comes out of a five-week window opening around 20 September, and a good share of it goes to the Nobel banquet.",
fr:"Le golfe de Botnie est assez saumâtre pour rendre les œufs orange — le même poisson en eau douce donne un frai jaune — et c’est cette couleur, et l’alimentation derrière elle, que protège l’AOP accordée au Kalix löjrom en 2010. Toute la récolte de l’année tient dans une fenêtre de cinq semaines qui s’ouvre vers le 20 septembre, et une bonne part part au banquet Nobel."},
tip:{en:"Keep it away from heat and from vinegar entirely: build it cold on the plate with sour cream, finely diced raw red onion and dill, and salt nothing further. If it was frozen, thaw it overnight in the fridge — a fast thaw bursts the eggs and leaves a milky pool.",
fr:"Tenez-le à l’écart de la chaleur et de tout vinaigre : dressez-le froid avec crème acidulée, oignon rouge cru en brunoise et aneth, sans rien resaler. S’il a été congelé, décongelez-le une nuit au réfrigérateur : une décongélation rapide fait éclater les grains et laisse une flaque laiteuse."},
pairs:["creme-fraiche","red-onion","dill","potato","butter","rye","lemon"],
svg:'<path class="s" d="M60 46q14-8 24-18"/><ellipse class="f1 sf" cx="44" cy="54" rx="19" ry="13"/><circle class="dot" cx="38" cy="49" r="2"/><circle class="dot" cx="48" cy="47" r="2"/><circle class="dot" cx="42" cy="58" r="2"/><circle class="dot" cx="52" cy="55" r="2"/>'},

{id:"caviar-esturgeon-blanc",cat:"roe",luxe:true,name:{en:"White sturgeon caviar",fr:"Caviar d’esturgeon blanc"},latin:"Acipenser transmontanus (roe)",
origin:{en:"Sacramento valley, California",fr:"Vallée du Sacramento, Californie"},season:[],
flavor:["buttery","rich","marine","delicate"],
story:{en:"North America's largest freshwater fish gave the continent its first farmed caviar: white sturgeon roe was harvested at Wilton, California in 1993, from broodstock that began as a UC Davis research project in 1979. The Po valley now raises the same Pacific species, so a tin stamped Italian may hold a fish native to the Sacramento River.",
fr:"Le plus grand poisson d’eau douce d’Amérique du Nord a donné le premier caviar d’élevage du continent : les œufs d’esturgeon blanc ont été récoltés à Wilton, en Californie, en 1993, à partir d’un cheptel né d’un programme de recherche lancé à UC Davis en 1979. La plaine du Pô élève aujourd’hui la même espèce pacifique, si bien qu’une boîte estampillée italienne peut renfermer un poisson originaire du Sacramento."},
tip:{en:"Serve it at 8–10 °C from a nacre or horn spoon; steel oxidises the grain within seconds and leaves a tinny edge you cannot wash out. Being low in iodine it holds its own under cream and warm blini — but never under lemon, which flattens it.",
fr:"Servez-le entre 8 et 10 °C à la cuillère de nacre ou de corne : l’acier oxyde le grain en quelques secondes et y laisse un goût de métal. Peu iodé, il tient sous la crème et le blini tiède sans disparaître — mais jamais sous le citron, qui l’aplatit."},
pairs:["creme-fraiche","egg","potato","chives","butter","cream"],
svg:'<ellipse class="f2 sf" cx="70" cy="34" rx="13" ry="7"/><ellipse class="f1 sf" cx="46" cy="56" rx="24" ry="16"/><ellipse class="f3 sf" cx="46" cy="56" rx="18" ry="11"/><circle class="dot" cx="40" cy="53" r="2.2"/><circle class="dot" cx="50" cy="59" r="2.2"/><circle class="dot" cx="48" cy="51" r="2.2"/>'}
]);
