window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"apple",cat:"fruits",name:{en:"Apple",fr:"Pomme"},latin:"Malus domestica",
origin:{en:"Tian Shan mountains, Kazakhstan",fr:"Monts Tian Shan, Kazakhstan"},season:[1,2,9,10,11,12],
flavor:["sweet","tangy","fresh"],
story:{en:"Every apple on Earth descends from wild forests near Almaty — a city whose name means “father of apples”. Traders carried seeds down the Silk Road, and humanity has since named more than seven thousand varieties.",
fr:"Toutes les pommes du monde descendent des forêts sauvages proches d’Almaty — ville dont le nom signifie « père des pommes ». Les marchands emportèrent ses pépins le long de la route de la soie, et l’humanité a depuis nommé plus de sept mille variétés."},
tip:{en:"Firm, tart apples hold their shape in the pan; sweet ones collapse into sauce. A knob of butter and cinnamon suits them all.",
fr:"Les pommes fermes et acidulées tiennent à la poêle ; les sucrées s’effondrent en compote. Une noix de beurre et de la cannelle vont à toutes."},
pairs:["cinnamon","butter","pork","sage","walnut","blue-cheese","celery","maple-syrup"],
svg:'<path class="f2 sf" d="M48 38q14-8 20 4 5 12-4 22-6 7-16 3-10 4-16-3-9-10-4-22 6-12 20-4z"/><path class="s" d="M48 38q0-8 4-12"/><path class="f3 sf" d="M52 30q6-6 12-4-2 8-10 8z"/>'},

{id:"apricot",cat:"fruits",name:{en:"Apricot",fr:"Abricot"},latin:"Prunus armeniaca",
origin:{en:"Central Asia & China",fr:"Asie centrale & Chine"},season:[6,7,8],
flavor:["sweet","sour","floral","fruity"],
story:{en:"Its Latin name blames Armenia, but the tree came from China, where it was cultivated four thousand years ago. The name travelled through Latin praecoquum, the early-ripening one, into Arabic and back into Europe with the article attached.",
fr:"Son nom latin accuse l’Arménie, mais l’arbre vient de Chine, où on le cultivait il y a quatre mille ans. Le nom voyagea par le latin praecoquum, le précoce, jusqu’à l’arabe et revint en Europe avec l’article collé."},
tip:{en:"It does not ripen after picking — only softens. A hard pale apricot will never become sweet, so buy by smell.",
fr:"Il ne mûrit pas après cueillette — il ne fait que s’attendrir. Un abricot dur et pâle ne deviendra jamais sucré : achetez au parfum."},
pairs:["almond","honey","vanilla","peach","rosemary","pistachio","cream","thyme"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="18"/><path class="s" d="M48 38v36"/><path class="f3 sf" d="M50 40q10-10 16-6-4 10-14 10z"/>'},

{id:"avocado",cat:"fruits",name:{en:"Avocado",fr:"Avocat"},latin:"Persea americana",
origin:{en:"Central Mexico",fr:"Mexique central"},season:[],
flavor:["creamy","nutty","mild","buttery"],
story:{en:"It evolved to be swallowed whole by giant ground sloths and other megafauna that have been extinct for ten thousand years. Without them it should have died out too — it survives because humans took over the job of moving the seed.",
fr:"Il a évolué pour être avalé entier par des paresseux terrestres géants et d’autres mégafaunes disparues depuis dix mille ans. Sans eux il aurait dû s’éteindre — il survit parce que les humains ont repris le travail de déplacer le noyau."},
tip:{en:"The stone does nothing to stop guacamole browning. Only acid and keeping air off the surface actually work.",
fr:"Le noyau n’empêche en rien le guacamole de noircir. Seuls l’acide et l’absence d’air au contact fonctionnent réellement."},
pairs:["lime","cilantro","chili","tomato","red-onion","olive-oil","black-pepper","shrimp"],
svg:'<path class="f3 sf" d="M48 28q14 6 14 24t-14 22-14-22 14-24z"/><circle class="f1 sf" cx="48" cy="58" r="8"/>'},

{id:"banana",cat:"fruits",name:{en:"Banana",fr:"Banane"},latin:"Musa acuminata",
origin:{en:"Southeast Asia",fr:"Asie du Sud-Est"},season:[],
flavor:["sweet","creamy","fruity","floral"],
story:{en:"Almost every banana exported on Earth is the Cavendish, a single clone with no genetic variation at all. Its predecessor, the Gros Michel, was wiped out by a fungus in the 1950s — and the same disease is now working through the Cavendish.",
fr:"Presque toutes les bananes exportées dans le monde sont des Cavendish, un clone unique sans aucune variation génétique. Sa devancière, la Gros Michel, fut anéantie par un champignon dans les années 1950 — et la même maladie progresse aujourd’hui dans la Cavendish."},
tip:{en:"Keep them off the fruit bowl. They give off enough ethylene to ripen everything within reach days early.",
fr:"Tenez-les à l’écart de la corbeille. Elles dégagent assez d’éthylène pour faire mûrir tout ce qui les entoure avec des jours d’avance."},
pairs:["dark-chocolate","vanilla","cinnamon","peanut","hazelnut","cream","honey","coconut-milk"],
svg:'<path class="f2 sf" d="M28 42q4 30 32 32 8-2 4-8-22-4-28-26-4-6-8 2z"/><path class="s" d="M32 40l-2-8"/>'},

{id:"bergamot",cat:"fruits",rare:true,name:{en:"Bergamot",fr:"Bergamote"},latin:"Citrus bergamia",
origin:{en:"Calabria, Italy",fr:"Calabre, Italie"},season:[1,2,11,12],
flavor:["citrus","floral","bitter","fresh"],
story:{en:"A narrow strip of Calabrian coast grows nearly all the world’s bergamot, a citrus too bitter to eat that conquered the planet by scent alone: it is the soul of eau de Cologne and the perfume in every cup of Earl Grey. Cooks are only now reclaiming it from the perfumers.",
fr:"Une étroite bande de côte calabraise produit presque toute la bergamote du monde, agrume trop amer pour être croqué qui a conquis la planète par le seul parfum : c’est l’âme de l’eau de Cologne et la senteur de chaque tasse d’Earl Grey. Les cuisiniers commencent seulement à la reprendre aux parfumeurs."},
tip:{en:"Treat the zest like a spice and the juice like a vinegar. A drop transforms a crème brûlée, a vinaigrette or a dark chocolate ganache into something people can’t name.",
fr:"Traitez le zeste comme une épice et le jus comme un vinaigre. Une goutte transforme une crème brûlée, une vinaigrette ou une ganache au chocolat noir en quelque chose que personne ne sait nommer."},
pairs:["dark-chocolate","honey","cream","almond","olive-oil"],
svg:'<path class="f2 sf" d="M48 36q18 0 18 18 0 16-18 16t-18-16q0-18 18-18z"/><path class="s" d="M48 36q-1-6 3-10"/><path class="dot" d="M48 54a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"blackberry",cat:"fruits",name:{en:"Blackberry",fr:"Mûre"},latin:"Rubus fruticosus",
origin:{en:"Europe",fr:"Europe"},season:[8,9,10],
flavor:["sweet","sour","fruity","earthy"],
story:{en:"English country lore holds that blackberries must not be picked after Michaelmas, the twenty-ninth of September, because the devil spits on them. The superstition is sound agronomy: autumn damp brings a mould that does turn the late fruit sour.",
fr:"La tradition anglaise veut qu’on ne cueille pas de mûres après la Saint-Michel, le 29 septembre, parce que le diable crache dessus. La superstition est de bonne agronomie : l’humidité d’automne amène une moisissure qui aigrit réellement les fruits tardifs."},
tip:{en:"Never wash them until the moment you use them. They absorb water instantly and collapse.",
fr:"Ne les lavez qu’au moment de les utiliser. Elles absorbent l’eau instantanément et s’effondrent."},
pairs:["apple","cream","vanilla","dark-chocolate","hazelnut","honey","thyme","black-pepper"],
svg:'<circle class="f1 sf" cx="42" cy="52" r="6"/><circle class="f1 sf" cx="54" cy="50" r="6"/><circle class="f1 sf" cx="48" cy="62" r="6"/><circle class="f1 sf" cx="38" cy="63" r="5"/><circle class="f1 sf" cx="58" cy="61" r="5"/>'},

{id:"blackcurrant",cat:"fruits",name:{en:"Blackcurrant",fr:"Cassis"},latin:"Ribes nigrum",
origin:{en:"Northern Europe & Asia",fr:"Europe du Nord & Asie"},season:[7,8],
flavor:["sour","earthy","fruity","musky"],
story:{en:"Banned in much of the United States for most of the twentieth century, because the bush hosts a rust that kills white pines and the timber industry had the louder lobby. Dijon meanwhile built crème de cassis into an institution.",
fr:"Interdit dans une grande partie des États-Unis durant presque tout le XXe siècle, parce que l’arbuste héberge une rouille qui tue les pins blancs et que l’industrie du bois avait le lobby le plus fort. Dijon, pendant ce temps, faisait de la crème de cassis une institution."},
tip:{en:"The leaves are as useful as the fruit — infuse a few in cream or syrup for a green, resinous note nothing else gives.",
fr:"Les feuilles valent le fruit — infusez-en quelques-unes dans une crème ou un sirop pour une note verte et résineuse inimitable."},
pairs:["dark-chocolate","cream","vanilla","mint","almond","honey","duck","black-pepper"],
svg:'<path class="s" d="M48 26v14"/><circle class="f1 sf" cx="41" cy="50" r="7"/><circle class="f1 sf" cx="56" cy="52" r="7"/><circle class="f1 sf" cx="47" cy="64" r="7"/><path class="s" d="M48 40l-7 3M48 40l8 5"/>'},

{id:"blood-orange",cat:"fruits",name:{en:"Blood orange",fr:"Orange sanguine"},latin:"Citrus × sinensis",
origin:{en:"Sicily",fr:"Sicile"},season:[1,2,3,4],
flavor:["sweet","sour","fruity","floral"],
story:{en:"The crimson comes from anthocyanins, and the tree only makes them when nights turn cold — which is why Sicily's slopes under Etna produce them and warmer groves cannot. A mild winter yields a disappointingly orange orange.",
fr:"Le pourpre vient des anthocyanes, que l’arbre ne fabrique que si les nuits fraîchissent — d’où les pentes siciliennes de l’Etna qui en produisent quand des vergers plus chauds n’y parviennent pas. Un hiver doux donne une orange décevante de banalité."},
tip:{en:"Segment it over a bowl to catch the juice, and use that juice in the dressing. Nothing else gives that colour.",
fr:"Levez les suprêmes au-dessus d’un bol pour recueillir le jus, et mettez ce jus dans l’assaisonnement. Rien d’autre ne donne cette couleur."},
pairs:["fennel","olive-oil","olive","red-onion","dark-chocolate","almond","mint","black-pepper"],
svg:'<circle class="f1 sf" cx="48" cy="54" r="20"/><path class="s" d="M48 34v40M28 54h40M34 40l28 28M62 40L34 68"/>'},

{id:"blueberry",cat:"fruits",name:{en:"Blueberry",fr:"Myrtille"},latin:"Vaccinium spp.",
origin:{en:"North America & Europe",fr:"Amérique du Nord & Europe"},season:[7,8,9],
flavor:["sweet","sour","fruity","floral"],
story:{en:"The cultivated blueberry is barely a century old — Elizabeth White and Frederick Coville produced the first crop in New Jersey in 1916, after she paid local pickers to find the largest wild bushes in the pine barrens.",
fr:"La myrtille cultivée a à peine un siècle — Elizabeth White et Frederick Coville en obtinrent la première récolte dans le New Jersey en 1916, après qu’elle eut payé des cueilleurs pour trouver les plus gros buissons sauvages des pinèdes."},
tip:{en:"Toss them in flour before folding into a batter. Naked, they sink straight to the bottom of the tin.",
fr:"Roulez-les dans la farine avant de les incorporer à une pâte. Nues, elles tombent droit au fond du moule."},
pairs:["lemon","vanilla","cream","almond","honey","cinnamon","yogurt","maple-syrup"],
svg:'<circle class="f1 sf" cx="40" cy="54" r="9"/><circle class="f1 sf" cx="57" cy="58" r="9"/><path class="s" d="M40 48l-2-6M57 52l2-6"/><path class="s" d="M36 52q4 3 8 0M53 56q4 3 8 0"/>'},

{id:"calamansi",cat:"fruits",name:{en:"Calamansi",fr:"Calamansi"},latin:"Citrus × microcarpa",
origin:{en:"Philippines",fr:"Philippines"},season:[],
flavor:["sour","citrus","floral","bitter"],
story:{en:"A cross between a kumquat and a mandarin, green outside and orange within, and the default sourness of Filipino cooking the way lemon is of European. It is squeezed over almost everything, and a saucer of it sits on most tables.",
fr:"Un croisement de kumquat et de mandarine, vert dehors et orange dedans, et l’acidité par défaut de la cuisine philippine comme le citron l’est de l’européenne. On le presse sur presque tout, et une soucoupe en trône sur la plupart des tables."},
tip:{en:"Squeeze it gently. Press too hard and you crush the peel oils into the juice, which turns it bitter fast.",
fr:"Pressez-le doucement. Trop fort, vous écrasez les huiles de l’écorce dans le jus, qui devient vite amer."},
pairs:["soy-sauce","chili","garlic","fish-sauce","ginger","cilantro","honey","coconut-milk"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="17"/><path class="s" d="M48 39v34M31 56h34M37 45l22 22M59 45L37 67"/>'},

{id:"cantaloupe",cat:"fruits",name:{en:"Cantaloupe melon",fr:"Melon"},latin:"Cucumis melo var. cantalupensis",
origin:{en:"Persia & Armenia",fr:"Perse & Arménie"},season:[6,7,8,9],
flavor:["sweet","musky","floral","fruity"],
story:{en:"Named for Cantalupo, a papal estate outside Rome where the seed was first grown in Europe. In France Cavaillon claims it so completely that Alexandre Dumas willed the town his complete works in exchange for an annuity of twelve melons a year.",
fr:"Nommé d’après Cantalupo, un domaine pontifical près de Rome où la graine fut cultivée pour la première fois en Europe. En France, Cavaillon se l’approprie si bien qu’Alexandre Dumas légua à la ville ses œuvres complètes contre une rente de douze melons par an."},
tip:{en:"Judge it by weight and by the scent at the stem end. A heavy melon that smells of nothing was picked far too early.",
fr:"Jugez au poids et au parfum côté pédoncule. Un melon lourd qui ne sent rien a été cueilli bien trop tôt."},
pairs:["prosciutto","mint","black-pepper","basil","lime","goat-cheese","olive-oil","honey"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="20"/><path class="s" d="M34 42q6 14 0 28M48 36v40M62 42q-6 14 0 28"/>'},

{id:"cherry",cat:"fruits",name:{en:"Cherry",fr:"Cerise"},latin:"Prunus avium",
origin:{en:"Around the Black Sea",fr:"Autour de la mer Noire"},season:[5,6,7],
flavor:["sweet","tangy","fruity"],
story:{en:"The Roman general Lucullus, famous for his banquets, brought the cherry tree to Rome from Kerasus on the Black Sea — the town that gave the fruit its name in half of Europe’s languages. Some victories are edible.",
fr:"Le général romain Lucullus, célèbre pour ses banquets, rapporta le cerisier de Kerasos, sur la mer Noire — la ville qui donna son nom au fruit dans la moitié des langues d’Europe. Certaines victoires se mangent."},
tip:{en:"Cherries and almond are cousins — a drop of almond or a kernel left in the jar makes cherry desserts taste more of themselves.",
fr:"Cerise et amande sont cousines — une goutte d’amande ou un noyau laissé dans le bocal donne aux desserts de cerise un goût plus profond d’eux-mêmes."},
pairs:["almond","dark-chocolate","duck","vanilla","pistachio"],
svg:'<path class="s" d="M42 56Q44 32 58 26M58 58Q56 36 58 26"/><circle class="f2 sf" cx="40" cy="60" r="9"/><circle class="f3 sf" cx="58" cy="62" r="9"/><path class="f2 sf" d="M58 26q8-4 12 0-4 5-12 3z"/>'},

{id:"citron",cat:"fruits",name:{en:"Citron",fr:"Cédrat"},latin:"Citrus medica",
origin:{en:"India & Southeast Asia",fr:"Inde & Asie du Sud-Est"},season:[10,11,12],
flavor:["citrus","floral","bitter","delicate"],
story:{en:"The first citrus to reach the Mediterranean, carried west with Alexander's armies, and one of the three parents of all the rest. It is almost all pith and rind with barely any juice — grown for its perfume and its peel, never for drinking.",
fr:"Le premier agrume parvenu en Méditerranée, rapporté par les armées d’Alexandre, et l’un des trois parents de tous les autres. Il est presque tout en ziste et en écorce, avec à peine du jus — cultivé pour son parfum et son écorce, jamais pour la boisson."},
tip:{en:"The white pith is the edible part here, not a fault. Candy it, or slice it thin and dress it raw as a salad.",
fr:"Le ziste blanc est ici la partie comestible, non un défaut. Confisez-le, ou taillez-le fin et assaisonnez-le cru en salade."},
pairs:["honey","vanilla","almond","olive-oil","pistachio","orange","mint","lemon"],
svg:'<path class="f2 sf" d="M34 56q0-22 14-22t14 22-14 22-14-22z"/><path class="s" d="M48 34v44"/><path class="s" d="M48 34q4-8 10-8"/>'},

{id:"clementine",cat:"fruits",name:{en:"Clementine",fr:"Clémentine"},latin:"Citrus × clementina",
origin:{en:"Oran, Algeria",fr:"Oran, Algérie"},season:[11,12,1],
flavor:["sweet","citrus","delicate","floral"],
story:{en:"Found around 1900 in the garden of an orphanage near Oran by Brother Clément Rodier, who was tending the trees — a chance seedling that turned out to be seedless and sweeter than its neighbours. It carries his name and nothing else.",
fr:"Découverte vers 1900 dans le jardin d’un orphelinat près d’Oran par le frère Clément Rodier, qui soignait les arbres — un semis fortuit qui se révéla sans pépins et plus sucré que ses voisins. Elle porte son nom, et rien d’autre."},
tip:{en:"Buy them with the leaves still attached. It is the only reliable freshness signal on a citrus fruit at the market.",
fr:"Achetez-les avec les feuilles. C’est le seul indice de fraîcheur fiable sur un agrume au marché."},
pairs:["dark-chocolate","vanilla","cinnamon","almond","honey","pistachio","cream","fennel"],
svg:'<circle class="f2 sf" cx="46" cy="58" r="17"/><path class="s" d="M46 41v34M29 58h34"/><path class="f3 sf" d="M50 42q10-10 16-6-4 10-14 10z"/>'},

{id:"coconut",cat:"fruits",name:{en:"Coconut",fr:"Noix de coco"},latin:"Cocos nucifera",
origin:{en:"Indo-Pacific",fr:"Indo-Pacifique"},season:[],
flavor:["sweet","nutty","creamy","mild"],
story:{en:"The husk is a flotation device: a coconut can drift on ocean currents for months and still germinate on landfall, which is how it colonised nearly every tropical coast before any boat carried it. The three dark spots are germination pores.",
fr:"La bourre est un flotteur : une noix de coco peut dériver des mois sur les courants et germer en touchant terre, et c’est ainsi qu’elle a colonisé presque toutes les côtes tropicales avant qu’aucun bateau ne la transporte. Les trois taches sombres sont des pores de germination."},
tip:{en:"One of the three eyes is soft. Push a skewer through it to drain the water before you crack the shell.",
fr:"L’un des trois yeux est mou. Percez-le d’une brochette pour vider l’eau avant de casser la coque."},
pairs:["lime","chili","mango","dark-chocolate","ginger","pineapple","vanilla","cilantro"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="20"/><circle class="dot" cx="42" cy="46" r="2.5"/><circle class="dot" cx="52" cy="45" r="2.5"/><circle class="dot" cx="47" cy="52" r="2.5"/><path class="s" d="M30 60q18 8 36 0"/>'},

{id:"cranberry",cat:"fruits",name:{en:"Cranberry",fr:"Canneberge"},latin:"Vaccinium macrocarpon",
origin:{en:"North America",fr:"Amérique du Nord"},season:[10,11,12],
flavor:["sour","bitter","tangy","fruity"],
story:{en:"Harvested by flooding the bog and beating the fruit loose — each berry has four internal air chambers that float it to the surface. A ripe one bounces, and growers once graded them by dropping them down wooden steps.",
fr:"Récoltée en inondant la tourbière et en détachant les fruits — chaque baie possède quatre chambres à air internes qui la font flotter. Une baie mûre rebondit, et les producteurs les triaient jadis en les laissant dévaler des marches de bois."},
tip:{en:"Stop cooking as soon as they pop. Past that the skins break down and the pectin that would have set the sauce is destroyed.",
fr:"Arrêtez la cuisson dès qu’elles éclatent. Au-delà, les peaux se défont et la pectine qui aurait fait prendre la sauce est détruite."},
pairs:["orange","cinnamon","clove","turkey","honey","walnut","ginger","maple-syrup"],
svg:'<ellipse class="f1 sf" cx="42" cy="56" rx="8" ry="10"/><ellipse class="f1 sf" cx="56" cy="58" rx="8" ry="10"/><path class="s" d="M42 46v-6M56 48v-6"/>'},

{id:"damson",cat:"fruits",name:{en:"Damson",fr:"Prune de Damas"},latin:"Prunus domestica subsp. insititia",
origin:{en:"Damascus, Syria",fr:"Damas, Syrie"},season:[8,9,10],
flavor:["sour","bitter","fruity","tangy"],
story:{en:"Named for Damascus, where Roman traders found it, and far too astringent to eat off the tree. Its whole purpose is transformation: the acidity and heavy pectin make a jam and a gin that no sweeter plum can match.",
fr:"Nommée d’après Damas, où les marchands romains la trouvèrent, et bien trop âpre pour se manger sur l’arbre. Sa raison d’être est la transformation : son acidité et sa pectine abondante donnent une confiture et un gin qu’aucune prune plus douce n’égale."},
tip:{en:"Do not try to stone them raw. Cook them whole and lift the stones out with a slotted spoon as they float free.",
fr:"N’essayez pas de les dénoyauter crues. Cuisez-les entières et retirez les noyaux à l’écumoire à mesure qu’ils se détachent."},
pairs:["cinnamon","clove","honey","juniper","almond","vanilla","black-pepper","bay-leaf"],
svg:'<circle class="f1 sf" cx="48" cy="58" r="16"/><path class="s" d="M48 42v32"/><path class="s" d="M48 42q5-9 11-9"/>'},

{id:"date",cat:"fruits",name:{en:"Date",fr:"Datte"},latin:"Phoenix dactylifera",
origin:{en:"Mesopotamia & the Gulf",fr:"Mésopotamie & Golfe"},season:[10,11,12],
flavor:["sweet","honeyed","rich","earthy"],
story:{en:"Cultivated for at least six thousand years, and in 2005 Israeli researchers germinated a two-thousand-year-old seed recovered from Masada. The tree that grew from it was named Methuselah and has since fathered a crop.",
fr:"Cultivée depuis au moins six mille ans, et en 2005 des chercheurs israéliens ont fait germer une graine vieille de deux mille ans retrouvée à Massada. L’arbre qui en est né fut nommé Mathusalem et a depuis engendré une récolte."},
tip:{en:"Medjool for eating, Deglet Nour for cooking — the first is soft and caramel, the second firmer and less sweet.",
fr:"Medjool pour manger, Deglet Nour pour cuisiner — la première est moelleuse et caramel, la seconde plus ferme et moins sucrée."},
pairs:["almond","orange","cinnamon","goat-cheese","tahini","walnut","cardamom","coffee"],
svg:'<ellipse class="f1 sf" cx="48" cy="56" rx="11" ry="19"/><path class="s" d="M48 38v36"/><path class="s" d="M42 46q6 4 12 0M42 66q6 4 12 0"/>'},

{id:"dragon-fruit",cat:"fruits",name:{en:"Dragon fruit",fr:"Pitaya"},latin:"Selenicereus undatus",
origin:{en:"Central America",fr:"Amérique centrale"},season:[],
flavor:["sweet","delicate","fresh","mild"],
story:{en:"It is the fruit of a climbing cactus whose flower opens for a single night and is pollinated by bats and moths. Commercial growers in Vietnam light their fields after dark to trick the plant into flowering out of season.",
fr:"C’est le fruit d’un cactus grimpant dont la fleur s’ouvre une seule nuit, pollinisée par des chauves-souris et des papillons nocturnes. Les producteurs vietnamiens éclairent leurs champs la nuit pour tromper la plante et la faire fleurir hors saison."},
tip:{en:"Expect looks rather than flavour — it is mild by nature. Lime, and serving it very cold, are what make it worth eating.",
fr:"Attendez-en l’allure plus que le goût — il est doux par nature. Le citron vert et un service très froid sont ce qui le rend intéressant."},
pairs:["lime","mint","passion-fruit","coconut-milk","honey","yogurt","mango","ginger"],
svg:'<ellipse class="f1 sf" cx="48" cy="58" rx="16" ry="19"/><circle class="dot" cx="43" cy="52" r="1.5"/><circle class="dot" cx="52" cy="55" r="1.5"/><circle class="dot" cx="46" cy="63" r="1.5"/><path class="f3 sf" d="M36 44q-10-4-12-12 12 0 16 8zM60 44q10-4 12-12-12 0-16 8z"/>'},

{id:"elderberry",cat:"fruits",name:{en:"Elderberry",fr:"Sureau"},latin:"Sambucus nigra",
origin:{en:"Europe",fr:"Europe"},season:[8,9],
flavor:["sour","earthy","fruity","musky"],
story:{en:"The tree gives twice a year and in two registers — a heady white flower in June that perfumes cordials, and a dark, almost medicinal berry in September. Folklore forbade cutting the wood without asking the tree's permission first.",
fr:"L’arbre donne deux fois l’an et sur deux registres — une fleur blanche capiteuse en juin qui parfume les sirops, et une baie sombre, presque médicinale, en septembre. Le folklore interdisait d’en couper le bois sans demander d’abord la permission à l’arbre."},
tip:{en:"The raw berries are mildly toxic and must be cooked. Strip them from the stalks with a fork — the stems are the worst part.",
fr:"Les baies crues sont légèrement toxiques et doivent être cuites. Égrappez-les à la fourchette — les tiges sont le pire."},
pairs:["apple","lemon","honey","cinnamon","clove","blackberry","vanilla","ginger"],
svg:'<path class="s" d="M48 24v16M48 40l-12 8M48 40l12 8"/><circle class="f1 sf" cx="34" cy="54" r="5"/><circle class="f1 sf" cx="46" cy="58" r="5"/><circle class="f1 sf" cx="60" cy="54" r="5"/><circle class="f1 sf" cx="40" cy="68" r="5"/><circle class="f1 sf" cx="54" cy="68" r="5"/>'},

{id:"fig",cat:"fruits",name:{en:"Fig",fr:"Figue"},latin:"Ficus carica",
origin:{en:"Western Asia & Mediterranean",fr:"Asie occidentale & Méditerranée"},season:[7,8,9,10],
flavor:["sweet","honeyed","earthy"],
story:{en:"Possibly the first plant humans ever farmed — fig remains in the Jordan Valley predate wheat. Each fig is an inverted garden of flowers, pollinated by a wasp the size of a comma; Cleopatra reportedly loved figs above all fruit.",
fr:"Peut-être la première plante jamais cultivée — des restes de figues dans la vallée du Jourdain précèdent le blé. Chaque figue est un jardin de fleurs inversé, pollinisé par une guêpe grande comme une virgule ; Cléopâtre, dit-on, la préférait à tout autre fruit."},
tip:{en:"A fig never ripens off the tree — buy it soft, drooping, almost tearing. Then it needs only good ham or a slice of cheese.",
fr:"Une figue ne mûrit jamais après la cueillette — achetez-la souple, affaissée, presque fendue. Il ne lui faut alors qu’un bon jambon ou une tranche de fromage."},
pairs:["prosciutto","goat-cheese","honey","walnut","balsamic","blue-cheese"],
svg:'<path class="f2 sf" d="M48 34q3 10 10 16 6 6 6 12a16 14 0 01-32 0q0-6 6-12 7-6 10-16z"/><path class="s" d="M48 34q0-6-4-9M48 44v24"/>'},

{id:"finger-lime",cat:"fruits",rare:true,name:{en:"Finger lime",fr:"Citron caviar"},latin:"Citrus australasica",
origin:{en:"Australian rainforest",fr:"Forêt pluviale australienne"},season:[9,10,11,12],
flavor:["citrus","tangy","fresh","delicate"],
story:{en:"Australia’s rainforest kept this secret for millennia: a finger-shaped citrus whose flesh falls apart into hundreds of pearls that pop on the tongue like sour caviar. Aboriginal peoples ate it long before bush-food chefs made it the most photographed garnish in fine dining.",
fr:"La forêt australienne a gardé ce secret des millénaires : un agrume en forme de doigt dont la chair s’égrène en centaines de perles qui éclatent sur la langue comme un caviar acidulé. Les peuples aborigènes le mangeaient bien avant que les chefs du bush food n’en fassent la garniture la plus photographiée de la haute cuisine."},
tip:{en:"Halve it and squeeze gently — the pearls flow out intact. Spoon them over oysters or scallops at the very last second; heat collapses the caviar.",
fr:"Coupez-le en deux et pressez doucement — les perles s’écoulent intactes. Déposez-les sur huîtres ou Saint-Jacques à la toute dernière seconde ; la chaleur fait s’effondrer le caviar."},
pairs:["oyster","scallop","shrimp","salmon"],
svg:'<path class="f2 sf" d="M32 40q16-10 32 8 8 10-2 16-16 8-30-10-6-9 0-14z" transform="rotate(-10 48 52)"/><path class="dot" d="M42 50a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M49 52a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M45 57a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M54 56a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/>'},

{id:"gooseberry",cat:"fruits",name:{en:"Gooseberry",fr:"Groseille à maquereau"},latin:"Ribes uva-crispa",
origin:{en:"Europe",fr:"Europe"},season:[6,7,8],
flavor:["sour","tangy","fresh","fruity"],
story:{en:"Nineteenth-century Lancashire mill workers competed in gooseberry clubs to grow the heaviest single berry, with records kept to the grain. Some of those societies still meet, and the winning weights have barely been beaten in a century.",
fr:"Les ouvriers des filatures du Lancashire du XIXe siècle rivalisaient dans des clubs de groseilles pour produire la baie la plus lourde, avec des registres tenus au grain près. Certaines de ces sociétés se réunissent encore, et les records n’ont guère été battus en un siècle."},
tip:{en:"The French name points at the classic use: a sharp sauce for mackerel. The acidity cuts oily fish better than lemon.",
fr:"Le nom français indique l’usage classique : une sauce acidulée pour le maquereau. Son acidité coupe le poisson gras mieux que le citron."},
pairs:["mackerel","cream","elderberry","vanilla","almond","honey","butter","mint"],
svg:'<circle class="f3 sf" cx="48" cy="56" r="17"/><path class="s" d="M36 50q12 6 24 0M34 60q14 6 28 0"/><path class="s" d="M48 39v-8"/>'},

{id:"grape",cat:"fruits",name:{en:"Grape",fr:"Raisin"},latin:"Vitis vinifera",
origin:{en:"Caucasus (Georgia)",fr:"Caucase (Géorgie)"},season:[8,9,10],
flavor:["sweet","fruity","tangy"],
story:{en:"Eight-thousand-year-old jars in Georgia still carry wine residue — humans domesticated the grape before writing, the wheel or most cities. The table grape is the sober sibling of history’s most storied fruit.",
fr:"Des jarres vieilles de huit mille ans, en Géorgie, portent encore des traces de vin — l’homme domestiqua le raisin avant l’écriture, la roue et la plupart des villes. Le raisin de table est le frère sobre du fruit le plus raconté de l’histoire."},
tip:{en:"Freeze a bunch on a summer day: frozen grapes are tiny sorbets. Roasted, they turn jammy and love cheese.",
fr:"Congelez une grappe un jour d’été : les grains gelés sont de petits sorbets. Rôtis, ils confisent et adorent le fromage."},
pairs:["blue-cheese","walnut","chicken","almond","goat-cheese"],
svg:'<path class="f2 sf" d="M40 42a5.5 5.5 0 100 .1zM56 42a5.5 5.5 0 100 .1zM48 50a5.5 5.5 0 100 .1zM40 58a5.5 5.5 0 100 .1zM56 58a5.5 5.5 0 100 .1zM48 66a5.5 5.5 0 100 .1z"/><path class="s" d="M48 38V26"/><path class="f3 sf" d="M48 28q-8-6-14-2 4 6 14 4z"/>'},

{id:"grapefruit",cat:"fruits",name:{en:"Grapefruit",fr:"Pamplemousse"},latin:"Citrus × paradisi",
origin:{en:"Barbados",fr:"Barbade"},season:[11,12,1,2,3,4],
flavor:["bitter","sour","citrus","fruity"],
story:{en:"An accidental hybrid of the pomelo and the sweet orange, found growing in Barbados in the eighteenth century. Its name is agricultural rather than poetic: the fruit hangs in tight clusters on the branch, like grapes.",
fr:"Un hybride accidentel du pomélo et de l’orange douce, découvert à la Barbade au XVIIIe siècle. Son nom anglais est agricole plutôt que poétique : le fruit pend en grappes serrées sur la branche."},
tip:{en:"A pinch of salt on the cut half suppresses the bitterness far better than sugar does — it blocks the receptors directly.",
fr:"Une pincée de sel sur la demi-coupe atténue l’amertume bien mieux que le sucre — elle bloque directement les récepteurs."},
pairs:["honey","mint","avocado","olive-oil","black-pepper","fennel","shrimp","basil"],
svg:'<circle class="f1 sf" cx="48" cy="54" r="21"/><circle class="s" cx="48" cy="54" r="15"/><path class="s" d="M48 39v30M33 54h30M38 44l20 20M58 44L38 64"/>'},

{id:"greengage",cat:"fruits",name:{en:"Greengage",fr:"Reine-claude"},latin:"Prunus domestica subsp. italica",
origin:{en:"France",fr:"France"},season:[8,9],
flavor:["sweet","honeyed","floral","fruity"],
story:{en:"Named in French for Claude of France, queen to François I, and in English after Sir William Gage, who received the trees with the labels lost. Two countries named the same fruit after two different people, and both names stuck.",
fr:"Nommée en français pour Claude de France, épouse de François Ier, et en anglais d’après sir William Gage, qui reçut les arbres sans leurs étiquettes. Deux pays ont nommé le même fruit d’après deux personnes différentes, et les deux noms sont restés."},
tip:{en:"Ignore the colour. A ripe greengage stays green — judge it by give under the thumb and by scent alone.",
fr:"Ne vous fiez pas à la couleur. Une reine-claude mûre reste verte — jugez à la souplesse sous le pouce et au parfum."},
pairs:["almond","vanilla","honey","cream","pistachio","butter","cinnamon","hazelnut"],
svg:'<circle class="f3 sf" cx="48" cy="57" r="17"/><path class="s" d="M48 40v34"/><path class="s" d="M48 40q5-9 11-9"/>'},

{id:"guava",cat:"fruits",name:{en:"Guava",fr:"Goyave"},latin:"Psidium guajava",
origin:{en:"Central America",fr:"Amérique centrale"},season:[],
flavor:["sweet","floral","musky","fruity"],
story:{en:"It spread across the tropics faster than almost any other fruit because birds and pigs carry the seed and the tree grows anywhere — in parts of the Pacific it is now classed as an invasive weed rather than a crop.",
fr:"Elle s’est répandue sous les tropiques plus vite que presque tout autre fruit, parce que les oiseaux et les porcs en transportent les graines et que l’arbre pousse n’importe où — dans certaines îles du Pacifique elle est aujourd’hui classée mauvaise herbe invasive plutôt que culture."},
tip:{en:"The perfume tells you far more than the colour. A ripe guava scents a whole room, and that is the moment to use it.",
fr:"Le parfum en dit bien plus que la couleur. Une goyave mûre embaume une pièce entière, et c’est le moment de l’utiliser."},
pairs:["lime","chili","cream","vanilla","coconut-milk","honey","mint","dark-chocolate"],
svg:'<circle class="f3 sf" cx="48" cy="58" r="18"/><circle class="s" cx="48" cy="58" r="9"/><circle class="dot" cx="45" cy="56" r="1.6"/><circle class="dot" cx="51" cy="59" r="1.6"/><path class="s" d="M48 40v-8"/>'},

{id:"honeydew",cat:"fruits",name:{en:"Honeydew melon",fr:"Melon miel"},latin:"Cucumis melo var. inodorus",
origin:{en:"Central Asia",fr:"Asie centrale"},season:[7,8,9,10],
flavor:["sweet","honeyed","fresh","delicate"],
story:{en:"Its Latin name, inodorus, is a fair criticism — unlike the cantaloupe it gives almost no scent even when perfectly ripe, which is why so many people buy it at the wrong moment. It keeps far longer in exchange.",
fr:"Son nom latin, inodorus, est une critique méritée — contrairement au cantaloup, il n’exhale presque rien même parfaitement mûr, d’où tant d’achats au mauvais moment. Il se conserve bien plus longtemps en échange."},
tip:{en:"Judge it by the skin, which turns waxy and faintly sticky when ripe, and by a slight give at the blossom end.",
fr:"Jugez-le à la peau, qui devient cireuse et légèrement collante à maturité, et à une souplesse à l’opposé du pédoncule."},
pairs:["mint","lime","prosciutto","ginger","cucumber","yogurt","basil","honey"],
svg:'<circle class="f3 sf" cx="48" cy="56" r="20"/><path class="s" d="M30 50q18 6 36 0M30 62q18 6 36 0"/>'},

{id:"kumquat",cat:"fruits",name:{en:"Kumquat",fr:"Kumquat"},latin:"Citrus japonica",
origin:{en:"Southern China",fr:"Chine du Sud"},season:[12,1,2,3],
flavor:["sour","sweet","citrus","bitter"],
story:{en:"The citrus that inverts itself: the peel is sweet and the flesh is sharp, so it is eaten whole and the order of flavours runs backwards. In southern China a potted kumquat tree at New Year is a wish for prosperity.",
fr:"L’agrume qui s’inverse : l’écorce est sucrée et la chair acide, si bien qu’on le mange entier et que l’ordre des saveurs s’inverse. En Chine du Sud, un kumquat en pot au Nouvel An est un vœu de prospérité."},
tip:{en:"Roll it between your fingers before eating to burst the oil glands in the skin. It doubles the perfume.",
fr:"Roulez-le entre les doigts avant de le manger pour crever les glandes à huile de la peau. Le parfum en est doublé."},
pairs:["honey","vanilla","dark-chocolate","ginger","duck","cinnamon","almond","clove"],
svg:'<ellipse class="f2 sf" cx="48" cy="56" rx="14" ry="18"/><path class="s" d="M48 38v36M34 56h28"/><path class="s" d="M48 38q3-8 8-8"/>'},

{id:"lemon",cat:"fruits",name:{en:"Lemon",fr:"Citron"},latin:"Citrus limon",
origin:{en:"Foothills of the Himalayas",fr:"Contreforts de l’Himalaya"},season:[1,2,3,11,12],
flavor:["sour","citrus","fresh"],
story:{en:"Roman aristocrats displayed lemons as proof of wealth long before anyone squeezed one over fish. Centuries later, the British Navy loaded ships with citrus against scurvy — a fruit that won battles without firing a shot.",
fr:"Les aristocrates romains exposaient des citrons comme preuve de richesse bien avant qu’on n’en presse un sur un poisson. Des siècles plus tard, la marine britannique chargea ses navires d’agrumes contre le scorbut — un fruit qui gagna des batailles sans tirer un coup de feu."},
tip:{en:"The zest holds the perfume, the juice the acidity. A squeeze at the very end of cooking sharpens almost any dish that tastes flat.",
fr:"Le zeste porte le parfum, le jus l’acidité. Un trait en toute fin de cuisson réveille presque tout plat qui semble plat."},
pairs:["garlic","parsley","olive-oil","salmon","chicken","honey","thyme","capers"],
svg:'<ellipse class="f1 sf" cx="48" cy="54" rx="23" ry="16"/><path class="f1 sf" d="M25 54q-4-2-6-1 2 3 6 1zM71 54q4-2 6-1-2 3-6 1z"/><path class="f2 sf" d="M52 36q4-8 12-8-1 8-8 10z"/>'},

{id:"lime",cat:"fruits",name:{en:"Lime",fr:"Citron vert"},latin:"Citrus aurantiifolia",
origin:{en:"Indo-Malayan region",fr:"Région indo-malaise"},season:[],
flavor:["sour","citrus","fresh","floral"],
story:{en:"The Royal Navy switched from lemons to West Indian limes in the 1860s to save money, not knowing limes carry far less vitamin C. Scurvy quietly returned to British ships — but the nickname limey stuck to the sailors regardless.",
fr:"La Royal Navy troqua les citrons contre les limes des Antilles dans les années 1860 par économie, ignorant que la lime porte bien moins de vitamine C. Le scorbut revint discrètement à bord — mais le sobriquet limey resta collé aux marins."},
tip:{en:"Roll it hard on the counter before juicing and take the zest first. Once cut, the zest is impossible to get cleanly.",
fr:"Roulez-le fermement sur le plan de travail avant de presser, et zestez d’abord. Une fois coupé, le zeste est impossible à prélever proprement."},
pairs:["chili","coconut-milk","cilantro","fish-sauce","ginger","mint","avocado","shrimp"],
svg:'<circle class="f2 sf" cx="48" cy="54" r="20"/><path class="s" d="M48 34v40M28 54h40M34 40l28 28M62 40L34 68"/>'},

{id:"lychee",cat:"fruits",name:{en:"Lychee",fr:"Litchi"},latin:"Litchi chinensis",
origin:{en:"Southern China",fr:"Chine du Sud"},season:[6,7,12,1],
flavor:["sweet","floral","fruity","delicate"],
story:{en:"Yang Guifei, consort of a Tang emperor, so loved them that riders were run in relay from Guangdong to the capital to deliver the fruit still fresh — a distance of more than a thousand kilometres, and a byword ever since for imperial excess.",
fr:"Yang Guifei, favorite d’un empereur Tang, les aimait tant que des cavaliers se relayaient du Guangdong jusqu’à la capitale pour livrer le fruit encore frais — plus de mille kilomètres, et depuis lors le symbole même de la démesure impériale."},
tip:{en:"The shell should be pink and give slightly. Brown and hard means it was picked weeks ago and the perfume is gone.",
fr:"La coque doit être rose et légèrement souple. Brune et dure, elle a été cueillie il y a des semaines et le parfum a disparu."},
pairs:["raspberry","lime","mint","coconut-milk","vanilla","ginger","cream","passion-fruit"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="17"/><path class="s" d="M38 46l4 4M48 42l3 5M58 46l-4 4M40 62l4 4M56 62l-4 4M48 68v-4"/><path class="s" d="M48 39v-8"/>'},

{id:"mandarin",cat:"fruits",name:{en:"Mandarin",fr:"Mandarine"},latin:"Citrus reticulata",
origin:{en:"Southern China",fr:"Chine du Sud"},season:[11,12,1,2],
flavor:["sweet","citrus","floral","fruity"],
story:{en:"One of the three ancestral citrus species — nearly every orange, lemon and grapefruit on Earth descends from crosses between the mandarin, the pomelo and the citron. It is a parent, not a variety.",
fr:"L’une des trois espèces ancestrales d’agrumes — presque toutes les oranges, citrons et pamplemousses du monde descendent de croisements entre la mandarine, le pomélo et le cédrat. C’est un parent, non une variété."},
tip:{en:"The loose skin is the giveaway of ripeness and the best part of it. Dry the peel and keep it — it is a spice in Chinese cooking.",
fr:"La peau lâche signale la maturité et c’est le meilleur du fruit. Séchez l’écorce et gardez-la — c’est une épice en cuisine chinoise."},
pairs:["dark-chocolate","cinnamon","star-anise","honey","almond","vanilla","duck","ginger"],
svg:'<circle class="f2 sf" cx="48" cy="56" r="19"/><path class="s" d="M48 37v38M29 56h38M36 43l24 26M60 43L36 69"/><path class="s" d="M48 37q4-8 10-8"/>'},

{id:"mango",cat:"fruits",name:{en:"Mango",fr:"Mangue"},latin:"Mangifera indica",
origin:{en:"India & Southeast Asia",fr:"Inde & Asie du Sud-Est"},season:[1,2,3,4,5,12],
flavor:["sweet","fruity","floral"],
story:{en:"India has grown mangoes for four thousand years; Buddha is said to have rested in a mango grove. Indian leaders still send crates of prized varieties to neighbouring heads of state — “mango diplomacy”, sweeter than treaties.",
fr:"L’Inde cultive la mangue depuis quatre mille ans ; Bouddha, dit-on, se reposait dans un verger de manguiers. Les dirigeants indiens envoient encore des caisses de variétés d’exception aux chefs d’État voisins — la « diplomatie de la mangue », plus douce que les traités."},
tip:{en:"Ripe mango with chili, salt and lime is a lesson in balance; green mango, shredded, is practically a different — and equally great — ingredient.",
fr:"La mangue mûre avec piment, sel et citron est une leçon d’équilibre ; la mangue verte, râpée, est presque un autre ingrédient — tout aussi grand."},
pairs:["chili","coconut-milk","cilantro","lemon","rice","yogurt"],
svg:'<path class="f2 sf" d="M34 44q6-12 20-10 16 2 14 18-2 14-16 18-14 4-20-8-4-9 2-18z"/><path class="f3 sf" d="M56 32q6-6 12-4-2 7-10 8z"/>'},

{id:"medlar",cat:"fruits",name:{en:"Medlar",fr:"Nèfle"},latin:"Mespilus germanica",
origin:{en:"Caucasus & Persia",fr:"Caucase & Perse"},season:[11,12],
flavor:["sweet","sour","earthy","musky"],
story:{en:"It is only edible once it has half-rotted on the branch or in straw, a process politely called bletting — and Shakespeare and Chaucer both made the obvious jokes. It was a staple winter fruit for centuries before sugar arrived.",
fr:"Elle n’est comestible qu’après avoir à demi blettit sur l’arbre ou dans la paille, procédé poliment nommé blettissement — et Shakespeare comme Chaucer en ont tiré les plaisanteries attendues. Ce fut un fruit d’hiver essentiel des siècles durant, avant le sucre."},
tip:{en:"Wait until it is brown and yielding — that is ripe, not spoiled. Then scoop the pulp out with a spoon.",
fr:"Attendez qu’elle soit brune et molle — c’est mûr, non gâté. Prélevez alors la pulpe à la cuillère."},
pairs:["cream","honey","cinnamon","clove","apple","walnut","quince","vanilla"],
svg:'<path class="f1 sf" d="M32 52q0-14 16-14t16 14q0 16-16 20T32 52z"/><path class="s" d="M40 44q8-6 16 0"/><circle class="dot" cx="48" cy="46" r="4"/>'},

{id:"mirabelle",cat:"fruits",name:{en:"Mirabelle",fr:"Mirabelle"},latin:"Prunus domestica subsp. syriaca",
origin:{en:"Lorraine, France",fr:"Lorraine, France"},season:[8,9],
flavor:["sweet","honeyed","floral","fruity"],
story:{en:"Lorraine grows the overwhelming majority of the world's crop, and the season lasts about six weeks in August and September before it is simply over. Most of the harvest goes to tarts and to eau-de-vie; very little travels.",
fr:"La Lorraine produit l’écrasante majorité de la récolte mondiale, et la saison dure environ six semaines en août-septembre avant de s’achever, simplement. L’essentiel part en tartes et en eau-de-vie ; très peu voyage."},
tip:{en:"Bake the tart on a base of ground almonds. They absorb the juice the fruit releases, which would otherwise soak the pastry.",
fr:"Montez la tarte sur un fond de poudre d’amandes. Elle absorbe le jus rendu par le fruit, qui détremperait la pâte."},
pairs:["almond","vanilla","butter","cinnamon","honey","cream","hazelnut","pistachio"],
svg:'<circle class="f2 sf" cx="48" cy="58" r="15"/><path class="s" d="M48 43v30"/><path class="s" d="M48 43q4-10 10-11"/>'},

{id:"mulberry",cat:"fruits",name:{en:"Mulberry",fr:"Mûre de mûrier"},latin:"Morus nigra",
origin:{en:"Western Asia",fr:"Asie occidentale"},season:[7,8],
flavor:["sweet","sour","fruity","honeyed"],
story:{en:"James I tried to found an English silk industry in 1608 by planting thousands of mulberries, and reportedly bought the wrong species — black rather than white, which silkworms will not eat. The trees survived; the industry never began.",
fr:"Jacques Ier voulut fonder une industrie de la soie anglaise en 1608 en plantant des milliers de mûriers, et acheta, dit-on, la mauvaise espèce — le noir plutôt que le blanc, dont les vers à soie ne veulent pas. Les arbres ont survécu ; l’industrie n’a jamais commencé."},
tip:{en:"They will not travel and barely keep a day, which is why you never see them in shops. Spread a sheet and shake the branch.",
fr:"Elles ne voyagent pas et tiennent à peine un jour, d’où leur absence des étals. Étendez un drap et secouez la branche."},
pairs:["cream","vanilla","almond","honey","lemon","yogurt","pistachio","cinnamon"],
svg:'<path class="s" d="M48 28v10"/><ellipse class="f1 sf" cx="48" cy="56" rx="11" ry="18"/><path class="s" d="M40 46q8 4 16 0M38 56q10 4 20 0M40 66q8 4 16 0"/>'},

{id:"nectarine",cat:"fruits",name:{en:"Nectarine",fr:"Nectarine"},latin:"Prunus persica var. nucipersica",
origin:{en:"China",fr:"Chine"},season:[7,8,9],
flavor:["sweet","fruity","floral","tangy"],
story:{en:"Not a hybrid of anything — it is a peach with a single recessive gene that switches off the fuzz. Peach trees occasionally throw nectarines and nectarine trees throw peaches; growers have found both on the same branch.",
fr:"Ce n’est l’hybride de rien — c’est une pêche portant un gène récessif qui supprime le duvet. Des pêchers donnent parfois des nectarines et des nectariniers des pêches ; on en a trouvé les deux sur une même branche."},
tip:{en:"The smooth skin means it bruises where a peach would not show it. Buy them loose and lay them in a single layer.",
fr:"La peau lisse marque là où une pêche ne montrerait rien. Achetez-les en vrac et posez-les sur une seule épaisseur."},
pairs:["basil","almond","vanilla","prosciutto","honey","mint","cream","raspberry"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="18"/><path class="s" d="M42 40q6 18 0 34"/><path class="f3 sf" d="M50 40q10-10 16-6-4 10-14 10z"/>'},

{id:"orange",cat:"fruits",name:{en:"Orange",fr:"Orange"},latin:"Citrus sinensis",
origin:{en:"Southern China",fr:"Chine méridionale"},season:[1,2,3,11,12],
flavor:["sweet","citrus","floral"],
story:{en:"The word travelled with the fruit: Sanskrit naranga became Persian narang, Arabic naranj, then orange. Kings built glass palaces — orangeries — just to keep these trees alive through northern winters.",
fr:"Le mot a voyagé avec le fruit : le sanskrit naranga devint le persan narang, l’arabe naranj, puis orange. Des rois bâtirent des palais de verre — les orangeries — pour garder ces arbres en vie sous les hivers du Nord."},
tip:{en:"Its zest loves dark chocolate and duck; its segments lift a fennel or beet salad out of winter gloom.",
fr:"Son zeste adore le chocolat noir et le canard ; ses quartiers sortent une salade de fenouil ou de betterave de la grisaille d’hiver."},
pairs:["duck","fennel","carrot","cinnamon","dark-chocolate","cardamom","beetroot"],
svg:'<circle class="f2 sf" cx="48" cy="55" r="20"/><path class="f3 sf" d="M46 35q-2-8 4-12 4 6-1 12z"/><path class="dot" d="M48 55a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"papaya",cat:"fruits",name:{en:"Papaya",fr:"Papaye"},latin:"Carica papaya",
origin:{en:"Central America",fr:"Amérique centrale"},season:[],
flavor:["sweet","musky","fruity","delicate"],
story:{en:"Its enzyme papain breaks down protein so effectively that the green fruit is used as a meat tenderiser across the tropics, and the leaves are wrapped around tough cuts overnight. The same enzyme is what makes an unripe one taste of almost nothing.",
fr:"Son enzyme, la papaïne, dégrade si bien les protéines que le fruit vert sert d’attendrisseur à viande dans tous les tropiques, et qu’on enveloppe les morceaux coriaces dans ses feuilles une nuit durant. C’est cette même enzyme qui rend une papaye verte presque sans goût."},
tip:{en:"A squeeze of lime is not optional — the fruit is musky and slightly flat on its own, and the acid lifts the whole thing.",
fr:"Un trait de citron vert n’est pas facultatif — le fruit est musqué et un peu plat seul, et l’acide relève l’ensemble."},
pairs:["lime","chili","coconut-milk","fish-sauce","mint","ginger","yogurt","honey"],
svg:'<path class="f2 sf" d="M48 30q16 10 16 28t-16 20-16-20 16-28z"/><circle class="dot" cx="44" cy="58" r="2"/><circle class="dot" cx="52" cy="56" r="2"/><circle class="dot" cx="48" cy="64" r="2"/>'},

{id:"passion-fruit",cat:"fruits",name:{en:"Passion fruit",fr:"Fruit de la passion"},latin:"Passiflora edulis",
origin:{en:"Southern Brazil",fr:"Sud du Brésil"},season:[],
flavor:["sour","floral","fruity","tangy"],
story:{en:"Spanish missionaries named the flower for the Passion of Christ, reading the corona as the crown of thorns and the three stigmas as the nails. The fruit took the name by association — it has nothing to do with passion in the ordinary sense.",
fr:"Des missionnaires espagnols nommèrent la fleur d’après la Passion du Christ, lisant la couronne comme celle d’épines et les trois stigmates comme les clous. Le fruit hérita du nom par association — il n’a rien à voir avec la passion au sens courant."},
tip:{en:"Wrinkled is ripe. A smooth, taut passion fruit is under-ripe and will be sharply acidic.",
fr:"Ridé veut dire mûr. Un fruit lisse et tendu n’est pas mûr et sera franchement acide."},
pairs:["mango","coconut-milk","vanilla","dark-chocolate","lime","cream","banana","honey"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="19"/><path class="s" d="M29 56a19 19 0 0 0 38 0"/><circle class="dot" cx="42" cy="48" r="2"/><circle class="dot" cx="52" cy="46" r="2"/><circle class="dot" cx="47" cy="52" r="2"/>'},

{id:"peach",cat:"fruits",name:{en:"Peach",fr:"Pêche"},latin:"Prunus persica",
origin:{en:"China",fr:"Chine"},season:[6,7,8,9],
flavor:["sweet","floral","fruity"],
story:{en:"Its Latin name says “Persian”, but the peach is Chinese — the West simply met it halfway along the trade routes. In Chinese legend, the peaches of immortality ripen once every few thousand years, and the gods wait for them.",
fr:"Son nom latin dit « persique », mais la pêche est chinoise — l’Occident l’a simplement rencontrée à mi-chemin des routes marchandes. Dans la légende chinoise, les pêches d’immortalité mûrissent tous les quelques millénaires, et les dieux les attendent."},
tip:{en:"A ripe peach smells ripe from a step away. Split it, grill it cut-side down, and serve it with almost anything creamy.",
fr:"Une pêche mûre se sent à un pas de distance. Fendez-la, grillez-la côté chair, et servez-la avec presque tout ce qui est crémeux."},
pairs:["almond","raspberry","vanilla","prosciutto","basil","honey"],
svg:'<circle class="f2 sf" cx="48" cy="55" r="20"/><path class="s" d="M48 37q-4 9-4 18t4 18"/><path class="f3 sf" d="M50 35q2-9 12-9-1 9-9 11z"/>'},

{id:"pear",cat:"fruits",name:{en:"Pear",fr:"Poire"},latin:"Pyrus communis",
origin:{en:"Caucasus & Western Asia",fr:"Caucase & Asie occidentale"},season:[1,8,9,10,11,12],
flavor:["sweet","floral","delicate"],
story:{en:"Louis XIV’s gardener grew some five hundred pear varieties at Versailles, racing to hand the king the year’s first perfect fruit. A pear is a rendez-vous: it is ripe for a single evening, and connoisseurs plan for it.",
fr:"Le jardinier de Louis XIV cultivait près de cinq cents variétés de poires à Versailles, pressé d’offrir au roi le premier fruit parfait de l’année. Une poire est un rendez-vous : elle n’est mûre qu’un seul soir, et les connaisseurs s’y préparent."},
tip:{en:"Ripen pears on the counter, then catch them at the neck: when it yields near the stem, the whole fruit is ready.",
fr:"Faites mûrir les poires à l’air libre, puis guettez le col : quand il cède près de la queue, tout le fruit est prêt."},
pairs:["blue-cheese","walnut","dark-chocolate","honey","ginger","vanilla","hazelnut"],
svg:'<path class="f1 sf" d="M48 32q4 10 10 16 8 8 4 18-4 10-14 10T34 66q-4-10 4-18 6-6 10-16z"/><path class="s" d="M48 32q-1-6 3-10"/><path class="f2 sf" d="M51 24q6-4 10-2-2 6-9 6z"/>'},

{id:"persimmon",cat:"fruits",name:{en:"Persimmon",fr:"Kaki"},latin:"Diospyros kaki",
origin:{en:"China",fr:"Chine"},season:[10,11,12],
flavor:["sweet","honeyed","floral","fruity"],
story:{en:"The astringent varieties are inedible until they are almost liquid — the tannins that dry the mouth only break down at the point most people would throw the fruit away. Its Latin name means food of the gods, awarded optimistically.",
fr:"Les variétés astringentes sont immangeables jusqu’à ce qu’elles soient presque liquides — les tanins qui assèchent la bouche ne se dégradent qu’au moment où la plupart des gens jetteraient le fruit. Son nom latin signifie nourriture des dieux, décerné avec optimisme."},
tip:{en:"Learn which one you have. Fuyu is squat and eaten firm like an apple; Hachiya is pointed and must be spoon-soft.",
fr:"Sachez lequel vous tenez. Le Fuyu est trapu et se mange ferme comme une pomme ; le Hachiya est pointu et doit être mou à la cuillère."},
pairs:["cinnamon","cream","walnut","honey","vanilla","goat-cheese","prosciutto","orange"],
svg:'<circle class="f1 sf" cx="48" cy="58" r="18"/><path class="f2 sf" d="M48 40q-12 0-14-6 6-4 14-4t14 4q-2 6-14 6z"/><path class="s" d="M48 30v-6"/>'},

{id:"pineapple",cat:"fruits",name:{en:"Pineapple",fr:"Ananas"},latin:"Ananas comosus",
origin:{en:"Southern Brazil & Paraguay",fr:"Sud du Brésil & Paraguay"},season:[],
flavor:["sweet","sour","fruity","tangy"],
story:{en:"So costly in Georgian England that a single fruit could be rented for an evening to sit at the centre of a dinner table, returned uneaten the next morning. It was architecture as much as food — stone pineapples still crown gateposts across Britain.",
fr:"Si coûteux dans l’Angleterre géorgienne qu’on louait un seul fruit pour une soirée, trônant au centre de la table et rendu intact le lendemain. C’était de l’architecture autant que de la nourriture — des ananas de pierre couronnent encore les piliers de portails britanniques."},
tip:{en:"It contains bromelain, which digests protein — it will stop gelatine setting and will curdle dairy if left too long.",
fr:"Il contient de la broméline, qui digère les protéines — elle empêche la gélatine de prendre et fait tourner les laitages si on la laisse agir."},
pairs:["chili","lime","coconut-milk","cilantro","mint","vanilla","ginger","black-pepper"],
svg:'<ellipse class="f2 sf" cx="48" cy="60" rx="16" ry="18"/><path class="s" d="M36 52l24 16M60 52L36 68"/><path class="f3 sf" d="M48 42q-8-16-4-18 6 6 4 18zM48 42q8-16 4-18-6 6-4 18z"/>'},

{id:"plum",cat:"fruits",name:{en:"Plum",fr:"Prune"},latin:"Prunus domestica",
origin:{en:"Caucasus & Central Asia",fr:"Caucase & Asie centrale"},season:[7,8,9],
flavor:["sweet","sour","fruity","tangy"],
story:{en:"The dusty bloom on the skin is not dirt but a wax the fruit makes itself, to hold water in and rain off. Rubbing it away is the fastest way to shorten a plum's life, and a heavy bloom is the mark of one barely handled.",
fr:"La pruine poudreuse sur la peau n’est pas de la poussière mais une cire que le fruit fabrique, pour retenir l’eau et repousser la pluie. La frotter est le moyen le plus sûr d’écourter la vie d’une prune, et une pruine épaisse signale un fruit peu manipulé."},
tip:{en:"Under-ripe plums are the ones to cook. Their acidity and pectin set a compote that ripe fruit turns to soup.",
fr:"Ce sont les prunes un peu fermes qu’il faut cuire. Leur acidité et leur pectine prennent en compote là où un fruit mûr tourne à la soupe."},
pairs:["cinnamon","star-anise","almond","vanilla","duck","black-pepper","honey","thyme"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="18"/><path class="s" d="M48 38v36"/><path class="s" d="M48 38q6-10 12-10"/>'},

{id:"pomegranate",cat:"fruits",name:{en:"Pomegranate",fr:"Grenade"},latin:"Punica granatum",
origin:{en:"Persia & Northern India",fr:"Perse & Inde du Nord"},season:[9,10,11,12],
flavor:["tangy","sweet","fruity"],
story:{en:"Persephone ate six pomegranate seeds in the underworld, and the Greeks used that to explain winter itself. The Spanish city of Granada carries its name, and its jewelled seeds have decorated feasts from Persia to Andalusia.",
fr:"Perséphone mangea six grains de grenade aux Enfers, et les Grecs en firent l’explication de l’hiver. La ville de Grenade porte son nom, et ses grains-joyaux ornent les fêtes de la Perse à l’Andalousie."},
tip:{en:"Halve it and slap the back with a wooden spoon over a bowl — the seeds rain out. They wake up anything rich or creamy.",
fr:"Coupez-la en deux et tapez le dos avec une cuillère en bois au-dessus d’un bol — les grains pleuvent. Ils réveillent tout ce qui est riche ou crémeux."},
pairs:["walnut","yogurt","mint","orange","cinnamon","duck","quinoa"],
svg:'<circle class="f1 sf" cx="48" cy="56" r="19"/><path class="f1 sf" d="M42 38l3-8h6l3 8"/><path class="dot" d="M41 52a2 2 0 104 0 2 2 0 10-4 0M51 52a2 2 0 104 0 2 2 0 10-4 0M46 60a2 2 0 104 0 2 2 0 10-4 0M55 60a2 2 0 104 0 2 2 0 10-4 0M41 62a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"quince",cat:"fruits",rare:true,name:{en:"Quince",fr:"Coing"},latin:"Cydonia oblonga",
origin:{en:"Caucasus & Persia",fr:"Caucase & Perse"},season:[10,11],
flavor:["floral","musky","tangy","honeyed"],
story:{en:"Scholars suspect the “golden apples” of Greek myth were quinces — and the word marmalade comes from marmelo, Portuguese for quince, whose paste was the original marmalade. Inedibly hard and astringent raw, it performs the kitchen’s quietest miracle: hours of slow heat turn its pale flesh ruby.",
fr:"Les érudits soupçonnent les « pommes d’or » des mythes grecs d’avoir été des coings — et le mot marmelade vient de marmelo, « coing » en portugais, dont la pâte fut la marmelade originelle. Immangeable cru, dur et astringent, il accomplit le plus discret miracle de la cuisine : des heures de feu doux teintent sa chair pâle de rubis."},
tip:{en:"Poach it whole and slow with honey and saffron, or roast it beside lamb — its perfume forgives every hour it demands.",
fr:"Pochez-le entier et longuement avec miel et safran, ou rôtissez-le près d’un agneau — son parfum pardonne chaque heure qu’il exige."},
pairs:["lamb","cinnamon","honey","walnut","vanilla","saffron"],
svg:'<path class="f1 sf" d="M48 34q6 2 10 0 10 4 8 18-2 16-18 16T30 52q-2-14 8-18 4 2 10 0z"/><path class="s" d="M48 34q0-6 4-9"/><path class="f2 sf" d="M52 27q5-5 10-3-2 6-9 6z"/>'},

{id:"raspberry",cat:"fruits",name:{en:"Raspberry",fr:"Framboise"},latin:"Rubus idaeus",
origin:{en:"Mount Ida, per Greek myth",fr:"Mont Ida, selon le mythe grec"},season:[6,7,8,9],
flavor:["tangy","fruity","floral"],
story:{en:"Its Latin name, Rubus idaeus, points to Mount Ida, where Greek myth says the nymph Ida pricked her finger picking berries for the infant Zeus — staining white fruit red forever. Botany keeps the poetry on file.",
fr:"Son nom latin, Rubus idaeus, désigne le mont Ida, où la nymphe Ida, dit le mythe grec, se piqua le doigt en cueillant des baies pour Zeus enfant — teignant à jamais de rouge un fruit blanc. La botanique garde la poésie en archive."},
tip:{en:"Too fragile to wash, too fleeting to keep: eat them the day you buy them, or crush them into a five-minute sauce with a spoon of sugar.",
fr:"Trop fragile pour être lavée, trop éphémère pour attendre : mangez-les le jour même, ou écrasez-les en sauce de cinq minutes avec une cuillère de sucre."},
pairs:["dark-chocolate","almond","peach","cream","vanilla","lemon"],
svg:'<path class="f3 sf" d="M40 46a5 5 0 105 6 5 5 0 105.5 0 5 5 0 105-6 5 5 0 10-3-8 5 5 0 10-9.5 0 5 5 0 10-3 8z"/><path class="f2 sf" d="M42 36l6-2 6 2-3 5h-6z"/><path class="s" d="M48 34v-8"/>'},

{id:"redcurrant",cat:"fruits",name:{en:"Redcurrant",fr:"Groseille"},latin:"Ribes rubrum",
origin:{en:"Western Europe",fr:"Europe de l’Ouest"},season:[6,7,8],
flavor:["sour","tangy","fresh","fruity"],
story:{en:"Bar-le-Duc still makes a jam from redcurrants seeded one berry at a time with a goose quill, a craft recorded since the fourteenth century. A skilled worker manages a few kilos a day, and the jar has always cost accordingly.",
fr:"Bar-le-Duc fabrique encore une confiture de groseilles épépinées une à une à la plume d’oie, un savoir-faire attesté depuis le XIVe siècle. Une ouvrière habile en fait quelques kilos par jour, et le pot a toujours coûté en conséquence."},
tip:{en:"They are loaded with pectin, so a jelly sets with nothing added. Strip them from the stalk with a fork, not your fingers.",
fr:"Elles sont riches en pectine : une gelée prend sans rien ajouter. Égrappez-les à la fourchette, pas aux doigts."},
pairs:["cream","vanilla","almond","honey","raspberry","mint","dark-chocolate","lemon"],
svg:'<path class="s" d="M48 26v14"/><circle class="f1 sf" cx="40" cy="48" r="6"/><circle class="f1 sf" cx="55" cy="50" r="6"/><circle class="f1 sf" cx="46" cy="62" r="6"/><path class="s" d="M48 40l-8 2M48 40l7 4M48 40l-2 16"/>'},

{id:"rhubarb",cat:"fruits",rare:true,name:{en:"Rhubarb",fr:"Rhubarbe"},latin:"Rheum rhabarbarum",
origin:{en:"Siberia & China",fr:"Sibérie & Chine"},season:[4,5,6],
flavor:["sour","fruity","fresh","grassy"],
story:{en:"Botanically a vegetable, legally a fruit — a US court ruled it so in 1947, since it was eaten as one. In Yorkshire’s “rhubarb triangle”, forced stalks grow in pitch-dark sheds and are harvested by candlelight; growers say you can hear them creak as they rise.",
fr:"Légume pour la botanique, fruit pour la loi — un tribunal américain en décida ainsi en 1947, usage faisant foi. Dans le « triangle de la rhubarbe » du Yorkshire, les tiges forcées poussent dans des hangars obscurs et se récoltent à la bougie ; les producteurs jurent qu’on les entend craquer en montant."},
tip:{en:"Never the leaves — they are toxic. Roast the stalks rather than stewing them: they keep their shape, their colour, and their proud acidity.",
fr:"Jamais les feuilles — elles sont toxiques. Rôtissez les tiges plutôt que de les compoter : elles gardent leur tenue, leur couleur et leur fière acidité."},
pairs:["strawberry","vanilla","ginger","cream","almond","honey"],
svg:'<path class="f2 sf" d="M38 34l6-2 4 44q-3 4-6 0zM52 30l6 0 0 46q-3 4-6 0z" transform="rotate(-4 48 52)"/><path class="f1 sf" d="M36 32q-8-8-2-14 8 2 8 12z"/>'},

{id:"sea-buckthorn",cat:"fruits",rare:true,name:{en:"Sea buckthorn",fr:"Argousier"},latin:"Hippophae rhamnoides",
origin:{en:"Coasts & steppes of Eurasia",fr:"Côtes & steppes d’Eurasie"},season:[9,10],
flavor:["sour","fruity","citrus"],
story:{en:"Blazing orange berries on a thorned shrub that thrives where nothing should — dunes, steppes, roadsides. Soviet science put its oil in cosmonauts’ skin cream; the New Nordic movement put its juice on tasting menus, where it plays the citrus that northern latitudes never had.",
fr:"Des baies d’un orange incandescent sur un arbuste épineux qui prospère là où rien ne devrait — dunes, steppes, bords de route. La science soviétique mit son huile dans la crème des cosmonautes ; la cuisine nouvelle nordique mit son jus au menu, où il joue l’agrume que les latitudes du Nord n’ont jamais eu."},
tip:{en:"Pure, it is brutally sour — cut it with honey or fold it into cream. With roasted carrots it performs a duet nobody sees coming.",
fr:"Pur, il est brutalement acide — adoucissez-le au miel ou glissez-le dans une crème. Avec des carottes rôties, il joue un duo que personne ne voit venir."},
pairs:["carrot","honey","cream","yogurt","dark-chocolate"],
svg:'<path class="s" d="M48 78V26M48 60l-14-8M48 60l14-8M48 44l-12-7M48 44l12-7"/><path class="f2" d="M36 50a3 3 0 106 0 3 3 0 10-6 0M54 50a3 3 0 106 0 3 3 0 10-6 0M40 36a3 3 0 106 0 3 3 0 10-6 0M50 36a3 3 0 106 0 3 3 0 10-6 0M45 26a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"strawberry",cat:"fruits",name:{en:"Strawberry",fr:"Fraise"},latin:"Fragaria × ananassa",
origin:{en:"Born in Brittany, France",fr:"Née en Bretagne, France"},season:[4,5,6,7],
flavor:["sweet","tangy","fruity"],
story:{en:"The modern strawberry was born around 1750 in Brittany, when a plant smuggled from Chile by the spy-engineer Frézier crossed with a Virginian one in French soil. His name, fittingly, sounds like fraisier — strawberry plant.",
fr:"La fraise moderne naquit vers 1750 en Bretagne, quand un plant rapporté du Chili par l’ingénieur-espion Frézier croisa un plant de Virginie en terre française. Son nom, joliment, sonne comme « fraisier »."},
tip:{en:"Never wash them until the last minute, and try a drop of balsamic or a turn of black pepper — it deepens their perfume.",
fr:"Ne les lavez qu’à la dernière minute, et essayez une goutte de balsamique ou un tour de poivre noir — cela creuse leur parfum."},
pairs:["balsamic","black-pepper","mint","cream","basil","dark-chocolate"],
svg:'<path class="f2 sf" d="M48 40q16 0 16 14 0 12-16 22-16-10-16-22 0-14 16-14z"/><path class="f3 sf" d="M38 40l10-2 10 2-4 6h-12z"/><path class="s" d="M48 38v-8"/><path class="dot" d="M42 52a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M51 52a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M46.5 62a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/>'},

{id:"watermelon",cat:"fruits",name:{en:"Watermelon",fr:"Pastèque"},latin:"Citrullus lanatus",
origin:{en:"Northeast Africa",fr:"Afrique du Nord-Est"},season:[7,8,9],
flavor:["sweet","fresh","delicate","fruity"],
story:{en:"Seeds have been found in Egyptian tombs, including Tutankhamun's, where it was left as a water source for the afterlife rather than as food — the fruit is over ninety per cent water and keeps for months unopened.",
fr:"On en a trouvé des graines dans des tombes égyptiennes, dont celle de Toutânkhamon, où elle était déposée comme réserve d’eau pour l’au-delà plutôt que comme nourriture — le fruit est à plus de quatre-vingt-dix pour cent d’eau et se garde des mois non entamé."},
tip:{en:"Salt brings out the sweetness dramatically, which is why the feta pairing works. Serve it cool, not ice cold — the cold mutes it.",
fr:"Le sel exalte spectaculairement le sucré, d’où la réussite de l’accord avec la feta. Servez-la fraîche, non glacée — le froid l’éteint."},
pairs:["feta","mint","lime","black-pepper","basil","olive-oil","cucumber","red-onion"],
svg:'<path class="f1 sf" d="M24 44a24 24 0 0 0 48 0z"/><path class="s" d="M24 44h48"/><circle class="dot" cx="40" cy="54" r="2"/><circle class="dot" cx="52" cy="52" r="2"/><circle class="dot" cx="46" cy="62" r="2"/>'},

{id:"yuzu",cat:"fruits",rare:true,name:{en:"Yuzu",fr:"Yuzu"},latin:"Citrus junos",
origin:{en:"Japan & Korea",fr:"Japon & Corée"},season:[1,11,12],
flavor:["citrus","floral","tangy","fresh"],
story:{en:"A gnarled, seed-choked citrus that gives barely a spoonful of juice — and perfumes a whole room. On the winter solstice, Japanese bathers float whole yuzu in hot tubs to ward off colds; French pastry chefs discovered it in the 2000s and have refused to let go since.",
fr:"Un agrume noueux, gorgé de pépins, qui donne à peine une cuillerée de jus — et parfume une pièce entière. Au solstice d’hiver, les Japonais font flotter des yuzus entiers dans leurs bains chauds pour éloigner les rhumes ; les pâtissiers français l’ont découvert dans les années 2000 et refusent depuis de le lâcher."},
tip:{en:"The zest carries the magic — the juice is a bonus. A few gratings over scallops, chocolate or a beurre blanc do what no lemon can.",
fr:"Le zeste porte la magie — le jus est un bonus. Quelques râpures sur des Saint-Jacques, un chocolat ou un beurre blanc font ce qu’aucun citron ne sait faire."},
pairs:["honey","ginger","scallop","miso","soy-sauce","dark-chocolate"],
svg:'<circle class="f1 sf" cx="48" cy="55" r="19"/><path class="s" d="M40 48q3-3 6 0M50 48q3-3 6 0" stroke-width="1.8"/><path class="f2 sf" d="M46 36q-2-8 4-11 4 5-1 11z"/>'}
]);
