window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"abondance",cat:"dairy",name:{en:"Abondance",fr:"Abondance"},latin:"Abondance AOP",
origin:{en:"Vallée d'Abondance, Haute-Savoie",fr:"Vallée d’Abondance, Haute-Savoie"},season:[],
flavor:["nutty","fruity","creamy","mild"],
story:{en:"Savoyard tradition has it that in 1381 the monks of Abondance abbey sent fifteen quintals of their cheese to the papal conclave at Avignon; what is certain is that the abbey cleared the high pastures, let them for rent paid in cheese, and gave its name to the cattle breed still milked for it. The curd is only half-cooked, gentler than Beaufort's, which is why the paste stays supple and faintly lactic.",
fr:"La tradition savoyarde veut qu’en 1381 les moines de l’abbaye d’Abondance aient envoyé quinze quintaux de leur fromage au conclave d’Avignon ; ce qui est sûr, c’est que l’abbaye a défriché les alpages, les a loués contre des redevances payées en fromage, et a donné son nom à la race laitière qui le produit encore. La pâte n’est que mi-cuite, plus douce que celle du beaufort : elle reste souple et légèrement lactée."},
tip:{en:"Melt it rather than grate it dry. A berthoud is a ramekin of Abondance cubes with a splash of dry Savoie white and a scrape of garlic, blistered ten minutes in a very hot oven and eaten with a spoon and boiled potatoes.",
fr:"Faites-le fondre plutôt que de le râper à sec. Un berthoud, c’est un ramequin de cubes d’abondance, un trait de vin blanc de Savoie et une pointe d’ail, passé dix minutes à four très chaud et mangé à la cuillère avec des pommes de terre à l’eau."},
pairs:["potato","garlic","black-pepper","onion","walnut","jambon-de-bayonne","cornichon","white-wine-vinegar"],
svg:'<path class="f2 sf" d="M26 40q-3 14 0 26 6 5 22 5t22-5q3-12 0-26z"/><ellipse class="f1 sf" cx="48" cy="40" rx="22" ry="7"/><path class="s" d="M26 54q22 6 44 0"/>'},

{id:"appenzeller",cat:"dairy",name:{en:"Appenzeller",fr:"Appenzeller"},latin:"Appenzeller",
origin:{en:"Appenzell, north-east Switzerland",fr:"Appenzell, nord-est de la Suisse"},season:[],
flavor:["pungent","herbal","nutty","rich"],
story:{en:"Every wheel is rubbed down through months of ageing with a herbal brine called Sulz — wine or cider, salt, and a mixture said to run to some twenty-five herbs, roots, barks and seeds. The recipe sits in a bank vault two people can open, and it is that wash, not the milk, that puts the fermented, almost meaty bite into the rind.",
fr:"Chaque meule est frottée pendant des mois d’affinage avec une saumure d’herbes, la Sulz : vin ou cidre, sel, et un mélange qui compterait quelque vingt-cinq herbes, racines, écorces et graines. La recette dort dans un coffre de banque que deux personnes seulement peuvent ouvrir, et c’est ce lavage, non le lait, qui donne à la croûte sa morsure fermentée, presque carnée."},
tip:{en:"Eat the rind — it is where the Sulz is, and the paste alone tastes like an ordinary mountain cheese. Melted it bullies everything around it, so cut a gratin half and half with Gruyère rather than letting it stand on its own.",
fr:"Mangez la croûte : c’est là qu’est la Sulz, et la pâte seule a le goût d’un fromage de montagne quelconque. Fondu, il écrase tout ce qui l’entoure — coupez un gratin moitié appenzeller, moitié gruyère plutôt que de le laisser seul."},
pairs:["potato","onion","cider-vinegar","black-pepper","rye","apple","cumin","pear"],
svg:'<circle class="f2 sf" cx="44" cy="56" r="20"/><path class="s" d="M30 48q14 8 28 0"/><rect class="f3 sf" x="58" y="26" width="12" height="9" rx="2" transform="rotate(20 64 30)"/><path class="s" d="M68 26l6-8"/>'},

{id:"asiago-d-allevo",cat:"dairy",name:{en:"Asiago d'allevo",fr:"Asiago d’allevo"},latin:"Asiago d’allevo DOP",
origin:{en:"Altopiano di Asiago, Veneto",fr:"Plateau d’Asiago, Vénétie"},season:[],
flavor:["nutty","salty","umami","pungent"],
story:{en:"The Asiago plateau was sheep country first, and the cheese was made from ewes' milk until cattle displaced the flocks around the sixteenth century. Allevo marks the wheel made to be kept: under one DOP name, it and the soft young pressato are in practice two unrelated cheeses that no counter should sell as the same thing.",
fr:"Le plateau d’Asiago fut d’abord un pays de moutons, et le fromage se fit au lait de brebis jusqu’à ce que les vaches y remplacent les troupeaux, vers le XVIe siècle. Allevo désigne la meule faite pour se garder : sous une même DOP, elle et le jeune pressato sont en pratique deux fromages sans rapport, qu’aucune crémerie ne devrait vendre pour un seul."},
tip:{en:"Take it vecchio at ten months to slice and stravecchio past fifteen to grate — that is when the crystals appear and it stops melting cleanly. Grate it over a hot soup at the table rather than stirring it in: held at a simmer it separates and goes oily.",
fr:"Prenez-le vecchio à dix mois pour le trancher, stravecchio au-delà de quinze pour le râper — c’est alors que les cristaux apparaissent et qu’il cesse de fondre proprement. Râpez-le sur la soupe à table plutôt que dans la casserole : maintenu au frémissement, il se sépare et graisse."},
pairs:["corn","honey","walnut","pear","black-pepper","balsamic","prosciutto","rye"],
svg:'<path class="f2 sf" d="M32 34l20-8 14 8-20 8z"/><path class="f1 sf" d="M32 34v22l20 10V42z"/><path class="f3 sf" d="M52 42l14-8v22l-14 10z"/><path class="s" d="M28 74q6-6 12 0M44 76q6-6 12 0"/>'},

{id:"banon",cat:"dairy",name:{en:"Banon",fr:"Banon"},latin:"Banon AOP",
origin:{en:"Haute-Provence, France",fr:"Haute-Provence, France"},season:[],
flavor:["creamy","herbal","woody","mild"],
story:{en:"In winter, when the goats dried up and no new cheese could be made, Provençal farms folded the last rounds into chestnut leaves to carry them through to spring. The leaves are gathered brown in autumn, when their tannin is lowest, soaked in five-per-cent vinegar water and tied with raffia, and the cheese then ferments inside them for at least ten days — the only French AOP ripened wrapped in leaves.",
fr:"L’hiver, quand les chèvres se tarissaient et qu’on ne pouvait plus fabriquer, les fermes provençales pliaient les dernières tomes dans des feuilles de châtaignier pour les tenir jusqu’au printemps. Les feuilles sont ramassées brunes à l’automne, quand leur teneur en tanin est la plus basse, réhydratées à l’eau vinaigrée à 5 %, liées au raphia, et le fromage fermente dedans au moins dix jours — seule AOP française affinée sous feuille."},
tip:{en:"Let it come fully to room temperature and untie the parcel at the table: the vegetal, mushroomy smell that lifts off it is half of what you paid for. Scrape the paste off the leaf and leave the leaf.",
fr:"Laissez-le revenir tout à fait à température et dénouez le paquet à table : l’odeur végétale et champignonnée qui s’en échappe fait la moitié du prix. Raclez la pâte de la feuille et laissez la feuille."},
pairs:["honey","thyme","rosemary","fig","walnut","olive-oil","pear","rye"],
svg:'<ellipse class="f2 sf" cx="48" cy="56" rx="22" ry="14"/><path class="f1 sf" d="M26 52q8-16 22-12 14-4 22 12-10 8-22 8t-22-8z"/><path class="s" d="M26 56q22 10 44 0"/><path class="s" d="M48 40v-8M44 34l4-4 4 4"/>'},

{id:"beaufort",cat:"dairy",name:{en:"Beaufort",fr:"Beaufort"},latin:"Beaufort AOP",
origin:{en:"Beaufortain, Savoie",fr:"Beaufortain, Savoie"},season:[],
flavor:["nutty","sweet","rich","floral"],
story:{en:"Brillat-Savarin called it the prince of gruyères. You can identify it blind by its waist: the wheel is pressed in a beechwood hoop that curves inward, leaving a concave heel no other alpine cheese has. Summer wheels, made from cows grazing high pasture, are marked chalet d'alpage.",
fr:"Brillat-Savarin l’appelait le prince des gruyères. On le reconnaît les yeux fermés à sa taille : la meule est pressée dans un cercle de hêtre incurvé, qui lui laisse un talon concave qu’aucun autre alpage ne possède. Les meules d’été, montées en alpage, portent la mention chalet d’alpage."},
tip:{en:"It is the fondue cheese that refuses to string badly — it melts smooth. Rub the pot with garlic first and keep the heat low.",
fr:"C’est le fromage à fondue qui refuse de filer mal — il fond lisse. Frottez le caquelon à l’ail et gardez un feu doux."},
pairs:["garlic","white-wine-vinegar","potato","black-pepper","nutmeg","walnut","onion","flour-t65"],
svg:'<path class="f2 sf" d="M26 66q-4-14 0-28h44q4 14 0 28z"/><path class="s" d="M26 52h44"/><circle class="dot" cx="40" cy="44" r="2"/><circle class="dot" cx="56" cy="58" r="2"/>'},

{id:"blue-cheese",cat:"dairy",name:{en:"Blue cheese",fr:"Fromage bleu"},latin:"Penicillium roqueforti",
origin:{en:"Roquefort caves, France",fr:"Caves de Roquefort, France"},season:[],
flavor:["pungent","salty","creamy","rich"],
story:{en:"A shepherd boy, the story goes, abandoned his bread-and-cheese lunch in a Roquefort cave to chase a shepherdess; returning weeks later, he found the cheese veined with blue — and delicious. The caves’ natural draughts still raise every true Roquefort today.",
fr:"Un jeune berger, raconte-t-on, abandonna son casse-croûte de pain et de fromage dans une grotte de Roquefort pour courtiser une bergère ; revenu des semaines plus tard, il trouva le fromage veiné de bleu — et délicieux. Les courants d’air naturels des caves élèvent encore chaque vrai roquefort aujourd’hui."},
tip:{en:"Its salt and power beg for sweetness: pears, figs, honey, sweet wines. Crumbled over a hot steak, it becomes an instant sauce.",
fr:"Son sel et sa puissance appellent le sucré : poires, figues, miel, vins doux. Émietté sur un steak chaud, il devient une sauce instantanée."},
pairs:["pear","walnut","honey","fig","celery","grape","beef"],
svg:'<path class="f1 sf" d="M30 62l18-30 18 30q-18 8-36 0z"/><path class="f3" d="M44 48a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M50 56a2 2 0 104 0 2 2 0 10-4 0M40 58a2 2 0 104 0 2 2 0 10-4 0M47 62a1.7 1.7 0 103.4 0 1.7 1.7 0 10-3.4 0"/>'},

{id:"brie",cat:"dairy",name:{en:"Brie",fr:"Brie"},latin:"Brie de Meaux AOP",
origin:{en:"Seine-et-Marne, Île-de-France",fr:"Seine-et-Marne, Île-de-France"},season:[],
flavor:["creamy","buttery","mild","earthy"],
story:{en:"At the Congress of Vienna in 1815, while Europe was being carved up, the diplomats held a side contest for the best cheese of their nations. Talleyrand entered Brie and won. It has been called the king of cheeses ever since — elected, unusually, by foreigners.",
fr:"Au congrès de Vienne en 1815, tandis que l’Europe se redécoupait, les diplomates organisèrent un concours parallèle du meilleur fromage de leur nation. Talleyrand présenta le brie et l’emporta. On l’appelle le roi des fromages depuis — élu, fait rare, par des étrangers."},
tip:{en:"Take it out an hour before serving. Cold Brie is chalk; at room temperature it slumps and smells of mushroom and cream.",
fr:"Sortez-le une heure avant. Froid, le brie est plâtreux ; à température il s’affaisse et sent le champignon et la crème."},
pairs:["apple","walnut","honey","grape","butter","mushroom","truffle","fig"],
svg:'<circle class="f3 sf" cx="48" cy="52" r="24"/><path class="s" d="M48 28v48M24 52h48"/><circle class="s" cx="48" cy="52" r="16"/>'},

{id:"burrata",cat:"dairy",name:{en:"Burrata",fr:"Burrata"},latin:"Burrata di Andria IGP",
origin:{en:"Puglia, Italy",fr:"Pouilles, Italie"},season:[],
flavor:["creamy","milky","delicate","sweet"],
story:{en:"Invented on a Puglian farm around 1900 to use up mozzarella offcuts: the scraps were shredded, drowned in cream, and wrapped in a pouch of fresh curd. A cheese designed so that nothing would be thrown away is now the most expensive thing on the antipasti list.",
fr:"Inventée dans une ferme des Pouilles vers 1900 pour écouler les chutes de mozzarella : les parures étaient effilochées, noyées de crème et enfermées dans une poche de caillé frais. Un fromage conçu pour ne rien jeter est devenu le plus cher des antipasti."},
tip:{en:"Eat it the day you buy it, at room temperature, and open it at the table. Its whole appeal is the moment the cream runs out.",
fr:"Mangez-la le jour même, à température, et ouvrez-la à table. Tout son charme est l’instant où la crème s’échappe."},
pairs:["tomato","basil","olive-oil","black-pepper","prosciutto","fig","balsamic","peach"],
svg:'<circle class="f3 sf" cx="48" cy="54" r="21"/><path class="s" d="M40 36q8-6 16 0"/><path class="s" d="M40 54q8 6 16 0"/>'},

{id:"butter",cat:"dairy",name:{en:"Butter",fr:"Beurre"},latin:"Butyrum",
origin:{en:"Steppes of Central Asia",fr:"Steppes d’Asie centrale"},season:[],
flavor:["creamy","rich","milky","buttery"],
story:{en:"Archaeologists keep finding “bog butter” — barrels buried in Irish peat two thousand years ago, still recognisable. Why France splits into salted Brittany and sweet-cream everywhere else is a tax story: Brittany was exempt from the salt tax, so its butter kept the salt.",
fr:"Les archéologues trouvent régulièrement du « beurre des tourbières » — des barils enfouis dans la tourbe irlandaise il y a deux mille ans, encore reconnaissables. Si la France se partage entre Bretagne salée et beurre doux partout ailleurs, c’est une histoire d’impôt : la Bretagne, exemptée de la gabelle, garda le sel dans son beurre."},
tip:{en:"Cook it past melting and it becomes beurre noisette — brown butter that smells of hazelnut and improves nearly everything, from fish to financiers.",
fr:"Poussez-le au-delà de la fonte et il devient beurre noisette — un beurre bruni qui sent la noisette et améliore presque tout, du poisson aux financiers."},
pairs:["potato","egg","corn","sage","mushroom","honey","spinach","scallop"],
svg:'<path class="f1 sf" d="M30 50h28v16H30z"/><path class="f1 sf" d="M30 50l8-8h28l-8 8z"/><path class="f1 sf" d="M58 50l8-8v16l-8 8z"/><path class="s" d="M62 60l6 6"/>'},

{id:"buttermilk",cat:"dairy",name:{en:"Buttermilk",fr:"Lait ribot"},latin:"Lait fermenté",
origin:{en:"Brittany & northern Europe",fr:"Bretagne & Europe du Nord"},season:[],
flavor:["tangy","milky","fresh","mild"],
story:{en:"The thin liquid left in the churn once the butter has come — Brittany calls it lait ribot and drinks it cold with buckwheat galettes. Its acidity reacts with bicarbonate of soda, which is the entire reason soda bread and American pancakes rise.",
fr:"Le liquide clair resté dans la baratte une fois le beurre pris — la Bretagne l’appelle lait ribot et le boit froid avec les galettes de sarrasin. Son acidité réagit avec le bicarbonate, et c’est toute la raison pour laquelle le soda bread et les pancakes lèvent."},
tip:{en:"It tenderises meat as well as it raises cakes. An overnight soak is the classic before frying chicken.",
fr:"Il attendrit la viande aussi bien qu’il fait lever les gâteaux. Une nuit de trempage est le classique avant de frire un poulet."},
pairs:["buckwheat","butter","honey","lemon","chives","dill","black-pepper","oats"],
svg:'<path class="f3 sf" d="M36 68V40h24v28z"/><path class="s" d="M36 40h24M36 50h24"/><path class="s" d="M42 58v6M54 58v6"/>'},

{id:"camembert",cat:"dairy",name:{en:"Camembert",fr:"Camembert"},latin:"Camembert de Normandie AOP",
origin:{en:"Normandy, France",fr:"Normandie, France"},season:[],
flavor:["creamy","earthy","rich","mild"],
story:{en:"Marie Harel is said to have made the first in 1791, sheltering a priest fleeing the Revolution who taught her a Brie technique. It went national a century later for a duller reason: the thin poplar box, invented in 1890, let it survive a train journey — and then a war, in every soldier's ration.",
fr:"Marie Harel en aurait fait le premier en 1791, en cachant un prêtre réfractaire qui lui enseigna une méthode briarde. Il devint national un siècle plus tard pour une raison plus prosaïque : la boîte en peuplier, inventée en 1890, lui permit de survivre au train — puis à une guerre, dans la ration de chaque soldat."},
tip:{en:"Buy it barely yielding at the centre and let it finish at home. A camembert already runny on the shelf has gone past its best.",
fr:"Achetez-le à peine souple au centre et laissez-le finir chez vous. Un camembert déjà coulant en rayon a passé son heure."},
pairs:["apple","walnut","potato","butter","cider-vinegar","onion","thyme","flour-t65"],
svg:'<circle class="f3 sf" cx="48" cy="52" r="23"/><circle class="s" cx="48" cy="52" r="17"/><path class="s" d="M38 44q10-6 20 0M38 60q10 6 20 0"/>'},

{id:"cantal",cat:"dairy",name:{en:"Cantal",fr:"Cantal"},latin:"Cantal AOP",
origin:{en:"Auvergne, France",fr:"Auvergne, France"},season:[],
flavor:["tangy","nutty","mild","earthy"],
story:{en:"Pliny the Elder praised a cheese from these mountains two thousand years ago, which makes Cantal a plausible claimant to the oldest in France. It is sold at three ages, and they are three different cheeses: jeune is springy and lactic, entre-deux rounded, vieux dry and almost bitter.",
fr:"Pline l’Ancien vantait il y a deux mille ans un fromage de ces montagnes, ce qui fait du cantal un prétendant crédible au titre de plus ancien de France. Il se vend à trois âges, et ce sont trois fromages : le jeune, souple et lacté ; l’entre-deux, rond ; le vieux, sec et presque amer."},
tip:{en:"Young Cantal is what makes truffade and aligot stretch. Old Cantal will not stretch at all — buy by age, not by name.",
fr:"C’est le cantal jeune qui fait filer la truffade et l’aligot. Le vieux ne file pas du tout — achetez selon l’âge, pas selon le nom."},
pairs:["potato","garlic","butter","black-pepper","onion","walnut","apple","thyme"],
svg:'<path class="f2 sf" d="M24 68V38l24-10 24 10v30z"/><path class="s" d="M24 38l24 10 24-10M48 48v20"/>'},

{id:"chaource",cat:"dairy",name:{en:"Chaource",fr:"Chaource"},latin:"Chaource AOP",
origin:{en:"Champagne & Burgundy border",fr:"Limite Champagne–Bourgogne"},season:[],
flavor:["creamy","tangy","milky","mild"],
story:{en:"A tall white cylinder that keeps a chalky, faintly sour core long after the outside has turned to cream — the two textures in one mouthful are the point. Its home sits on the Champagne border, and the local pairing has never needed defending.",
fr:"Un haut cylindre blanc qui conserve un cœur crayeux, légèrement acidulé, longtemps après que l’extérieur a tourné à la crème — les deux textures dans une même bouchée, c’est tout l’intérêt. Son pays borde la Champagne, et l’accord local n’a jamais eu besoin d’être défendu."},
tip:{en:"Buy it young if you want the chalk. Fully ripe it is uniformly soft, and the contrast that makes it interesting is gone.",
fr:"Achetez-le jeune si vous voulez le crayeux. À pleine maturité il est uniformément fondant, et le contraste qui fait son intérêt a disparu."},
pairs:["strawberry","cream","walnut","apple","chives","black-pepper","grape","butter"],
svg:'<path class="f3 sf" d="M32 68V40q16-8 32 0v28z"/><path class="s" d="M32 40q16 8 32 0"/><path class="s" d="M40 50v14M56 50v14"/>'},

{id:"cheddar",cat:"dairy",name:{en:"Cheddar",fr:"Cheddar"},latin:"West Country Farmhouse Cheddar PDO",
origin:{en:"Somerset, England",fr:"Somerset, Angleterre"},season:[],
flavor:["tangy","nutty","salty","rich"],
story:{en:"Cheddar is a verb before it is a place: to cheddar is to stack and turn slabs of curd so the whey presses out and the texture goes fibrous. The caves of Cheddar Gorge did the ageing. The technique travelled so well that most cheddar in the world has never been near Somerset.",
fr:"Cheddar est un verbe avant d’être un lieu : cheddariser, c’est empiler et retourner des blocs de caillé pour en presser le petit-lait et rendre la pâte fibreuse. Les grottes des gorges de Cheddar faisaient l’affinage. La technique a si bien voyagé que le cheddar du monde n’a jamais approché le Somerset."},
tip:{en:"Age is everything here. Anything under a year is a sandwich cheese; past two it develops crystals and a genuine sharpness.",
fr:"Tout est dans l’âge. En dessous d’un an c’est un fromage à sandwich ; passé deux ans il développe des cristaux et une vraie vivacité."},
pairs:["apple","onion","mustard","potato","black-pepper","chives","flour-t65","butter"],
svg:'<path class="f2 sf" d="M26 66V40h44v26z"/><path class="s" d="M26 40h44M26 53h44"/>'},

{id:"beurre-de-baratte",cat:"dairy",name:{en:"Churned butter",fr:"Beurre de baratte"},latin:"Beurre de baratte AOP",
origin:{en:"Normandy & Poitou-Charentes",fr:"Normandie & Poitou-Charentes"},season:[],
flavor:["creamy","rich","nutty","milky"],
story:{en:"Made in a slow rotating churn from cream that has been left to ripen with lactic cultures for up to twenty hours before churning. That maturation is where the hazelnut note comes from — industrial butter skips it entirely.",
fr:"Fabriqué en baratte tournante lente à partir d’une crème laissée maturer avec des ferments lactiques jusqu’à vingt heures avant barattage. C’est de cette maturation que vient la note de noisette — le beurre industriel la saute entièrement."},
tip:{en:"Keep it for spreading and for finishing sauces, where you can actually taste it. Frying with it is a waste of money.",
fr:"Gardez-le pour la tartine et pour monter les sauces, là où on le goûte vraiment. Le cuire à la poêle est un gâchis."},
pairs:["flour-t65","radish","sardine","potato","honey","chives","asparagus","comte"],
svg:'<path class="f3 sf" d="M32 68V52h32v16z"/><path class="s" d="M32 58h32"/><path class="s" d="M40 52v16M56 52v16"/>'},

{id:"comte",cat:"dairy",name:{en:"Comté",fr:"Comté"},latin:"Gruyère de Comté AOP",
origin:{en:"Jura massif, France",fr:"Massif du Jura, France"},season:[],
flavor:["nutty","sweet","rich","umami"],
story:{en:"One wheel of Comté drinks the milk of some thirty cows — more than any single farm could give. So Jura villages pooled their milk in fruitières, cooperative dairies, from the thirteenth century onward. The cheese exists because neighbours agreed to trust each other.",
fr:"Une meule de comté boit le lait d’une trentaine de vaches — plus qu’aucune ferme seule ne pouvait fournir. Dès le XIIIe siècle, les villages jurassiens ont donc mis leur lait en commun dans des fruitières, ces laiteries coopératives. Le fromage existe parce que des voisins ont accepté de se faire confiance."},
tip:{en:"Ask the age. Under twelve months it is milky and gentle; past eighteen it turns to hazelnut and brown butter, and tiny crunchy crystals appear.",
fr:"Demandez l’âge. En dessous de douze mois il est lacté et doux ; passé dix-huit il vire à la noisette et au beurre noisette, avec de petits cristaux croquants."},
pairs:["walnut","apple","honey","white-wine-vinegar","cumin","hazelnut","onion","potato"],
svg:'<path class="f2 sf" d="M22 68 L48 26 L74 68 Z"/><path class="s" d="M30 62h36M36 52h24"/><circle class="dot" cx="42" cy="58" r="2"/><circle class="dot" cx="54" cy="60" r="2"/>'},

{id:"cream",cat:"dairy",name:{en:"Cream",fr:"Crème"},latin:"Crema lactis",
origin:{en:"Wherever cows graze",fr:"Partout où paissent les vaches"},season:[],
flavor:["creamy","milky","sweet","rich"],
story:{en:"Cream is simply milk’s patience: leave it and the richness rises. Legend ties whipped cream to the château of Chantilly, where the maître d’hôtel Vatel staged feasts for Louis XIV — the name stuck to the cloud, and the cloud stuck to dessert.",
fr:"La crème n’est que la patience du lait : laissez-le reposer et la richesse remonte. La légende attache la crème fouettée au château de Chantilly, où le maître d’hôtel Vatel orchestrait les fêtes de Louis XIV — le nom est resté au nuage, et le nuage au dessert."},
tip:{en:"For whipping, everything must be cold — bowl, whisk, cream. In sauces, add it late and never quite boil it again.",
fr:"Pour la monter, tout doit être froid — bol, fouet, crème. En sauce, ajoutez-la tard et ne la refaites jamais tout à fait bouillir."},
pairs:["potato","leek","mushroom","strawberry","vanilla","coffee","chanterelle"],
svg:'<path class="f1 sf" d="M38 40h24l-4 32q-8 4-16 0z"/><path class="f2 sf" d="M36 40q12-6 28 0l-2 4q-12-5-24 0z"/><path class="s" d="M64 42q6-2 6-8"/>'},

{id:"creme-fraiche",cat:"dairy",name:{en:"Crème fraîche",fr:"Crème fraîche"},latin:"Crème fraîche d’Isigny AOP",
origin:{en:"Normandy, France",fr:"Normandie, France"},season:[],
flavor:["creamy","tangy","rich","milky"],
story:{en:"Cream left to ripen with its own lactic bacteria until it thickens and turns faintly sour. That acidity is the whole trick: it holds the fat together, so crème fraîche can boil in a sauce without splitting where ordinary cream curdles.",
fr:"De la crème laissée mûrir avec ses propres bactéries lactiques jusqu’à épaissir et tourner légèrement acide. Cette acidité est tout le secret : elle tient la matière grasse, si bien que la crème fraîche bout dans une sauce sans trancher là où la crème ordinaire caille."},
tip:{en:"It is the safe cream for anything acidic — lemon, wine, tomato. Add ordinary cream to those and it will split.",
fr:"C’est la crème sûre pour tout ce qui est acide — citron, vin, tomate. Une crème ordinaire y trancherait."},
pairs:["shallot","chives","lemon","mushroom","potato","dill","salmon","black-pepper"],
svg:'<path class="f3 sf" d="M34 66V44h28v22z"/><path class="s" d="M34 44q14-8 28 0"/><path class="s" d="M38 56q10 4 20 0"/>'},

{id:"egg",cat:"dairy",name:{en:"Egg",fr:"Œuf"},latin:"Ovum",
origin:{en:"Domesticated in Southeast Asia",fr:"Domestiqué en Asie du Sud-Est"},season:[],
flavor:["mild","rich","creamy"],
story:{en:"Kitchen lore says the hundred folds of a chef’s toque stand for the hundred ways to cook an egg. It binds, it lifts, it enriches, it clarifies — no single ingredient does more jobs in a kitchen, and none does them more quietly.",
fr:"La légende de cuisine veut que les cent plis de la toque d’un chef représentent les cent façons de cuire un œuf. Il lie, il fait lever, il enrichit, il clarifie — aucun ingrédient ne remplit plus de rôles en cuisine, et aucun ne le fait plus discrètement."},
tip:{en:"Old eggs peel easily but poach raggedly; fresh ones hold together in water. Know your egg’s age and give it the job it deserves.",
fr:"Les œufs vieux s’écalent bien mais pochent mal ; les frais se tiennent dans l’eau. Connaissez l’âge de votre œuf et donnez-lui l’emploi qu’il mérite."},
pairs:["butter","chives","asparagus","truffle","spinach","mustard","black-pepper","tarragon"],
svg:'<path class="f1 sf" d="M48 28q16 14 16 30a16 16 0 01-32 0q0-16 16-30z"/><circle class="f2 sf" cx="48" cy="58" r="7"/>'},

{id:"feta",cat:"dairy",name:{en:"Feta",fr:"Feta"},latin:"Φέτα PDO",
origin:{en:"Greece",fr:"Grèce"},season:[],
flavor:["salty","tangy","milky","fresh"],
story:{en:"In the Odyssey, the Cyclops curdles ewe's milk in wicker baskets and stores the cheese in brine — a recognisable description of feta written some three thousand years ago. Its name is much younger and merely Italian: fetta, a slice.",
fr:"Dans l’Odyssée, le Cyclope fait cailler du lait de brebis dans des paniers d’osier et conserve le fromage en saumure — une description reconnaissable de la feta, écrite il y a quelque trois mille ans. Son nom est bien plus jeune et simplement italien : fetta, une tranche."},
tip:{en:"Rinse it and let it sit in fresh water for ten minutes if it is fiercely salty. Never refrigerate it out of its brine — it dries to chalk.",
fr:"Rincez-la et laissez-la dix minutes dans l’eau claire si elle est trop salée. Ne la gardez jamais hors de sa saumure au froid — elle se dessèche en craie."},
pairs:["tomato","cucumber","olive","olive-oil","oregano","watermelon","mint","red-onion"],
svg:'<path class="f3 sf" d="M28 62V42h40v20z"/><path class="s" d="M28 42h40M28 52h40"/><circle class="dot" cx="38" cy="47" r="1.4"/><circle class="dot" cx="56" cy="57" r="1.4"/>'},

{id:"fromage-blanc",cat:"dairy",name:{en:"Fromage blanc",fr:"Fromage blanc"},latin:"Caillé frais",
origin:{en:"France",fr:"France"},season:[],
flavor:["tangy","milky","fresh","delicate"],
story:{en:"Fresh curd drained but never aged, never salted, never ripened — a cheese caught at the first hour of its life. In its loosest form, faisselle, it is sold still dripping in the perforated pot it drained in, and eaten with nothing but sugar or a little cream.",
fr:"Du caillé frais égoutté mais jamais affiné, jamais salé, jamais mûri — un fromage saisi à la première heure de sa vie. Dans sa forme la plus lâche, la faisselle, il se vend encore ruisselant dans le pot perforé où il s’est égoutté, et se mange avec rien d’autre qu’un peu de sucre ou de crème."},
tip:{en:"Whip it with a fork before serving and it lightens completely. Sweet with honey, savoury with shallot and herbs — it goes either way.",
fr:"Fouettez-le à la fourchette avant de servir, il s’allège complètement. Sucré au miel, salé à l’échalote et aux herbes — il va des deux côtés."},
pairs:["honey","strawberry","chives","shallot","raspberry","cream","black-pepper","dill"],
svg:'<path class="f3 sf" d="M34 66V46h28v20z"/><path class="s" d="M34 46q14-6 28 0"/><circle class="dot" cx="42" cy="56" r="1.4"/><circle class="dot" cx="54" cy="58" r="1.4"/>'},

{id:"goat-cheese",cat:"dairy",name:{en:"Goat cheese",fr:"Fromage de chèvre"},latin:"Caprae caseus",
origin:{en:"Loire Valley, France & antiquity",fr:"Val de Loire, France & Antiquité"},season:[3,4,5,6,7,8,9,10],
flavor:["tangy","creamy","earthy","fresh"],
story:{en:"Goats were milked before cows, making this perhaps the oldest cheese lineage on Earth. Loire legend credits the Saracens, halted at Poitiers in 732: they left behind their goats and their cheese recipes, and the valley has been grateful ever since.",
fr:"On a trait les chèvres avant les vaches — c’est peut-être la plus ancienne lignée fromagère du monde. La légende ligérienne crédite les Sarrasins, arrêtés à Poitiers en 732 : ils laissèrent derrière eux chèvres et recettes, et la vallée leur en sait gré depuis."},
tip:{en:"Young and fresh, it loves herbs and olive oil; aged and firm, honey and walnuts. Ten minutes under the grill on bread, and any salad becomes lunch.",
fr:"Jeune et frais, il aime les herbes et l’huile d’olive ; affiné et ferme, le miel et les noix. Dix minutes sous le gril sur du pain, et toute salade devient déjeuner."},
pairs:["beetroot","fig","honey","thyme","walnut","spinach"],
svg:'<path class="f1 sf" d="M34 44h28v20H34z" rx="4"/><ellipse class="f1 sf" cx="48" cy="44" rx="14" ry="5"/><ellipse class="f2 sf" cx="48" cy="64" rx="14" ry="5"/><path class="s" d="M34 44v20M62 44v20" stroke-width="1.6"/>'},

{id:"gruyere",cat:"dairy",name:{en:"Gruyère",fr:"Gruyère"},latin:"Le Gruyère AOP",
origin:{en:"Fribourg, Switzerland",fr:"Fribourg, Suisse"},season:[],
flavor:["nutty","salty","rich","sweet"],
story:{en:"The holes belong to Emmental, not to Gruyère — the Swiss are firm about this, and true Gruyère is dense and nearly blind. The confusion is French: for centuries gruyère was a generic word for any large pressed alpine wheel, which is why French recipes still say it when they mean almost anything.",
fr:"Les trous sont ceux de l’emmental, pas du gruyère — les Suisses y tiennent, et le vrai gruyère est dense et presque aveugle. La confusion est française : pendant des siècles, gruyère a désigné n’importe quelle grande meule pressée d’alpage, d’où les recettes qui l’écrivent encore pour dire à peu près tout."},
tip:{en:"For a gratin, grate it cold and coarse. Fine grating turns to paste in the hand and clumps rather than covering.",
fr:"Pour un gratin, râpez-le froid et gros. Râpé fin, il se met en pâte dans la main et fait des paquets au lieu de couvrir."},
pairs:["potato","onion","nutmeg","cream","garlic","black-pepper","butter","egg"],
svg:'<path class="f2 sf" d="M24 66q-3-13 0-26h48q3 13 0 26z"/><circle class="dot" cx="40" cy="50" r="2.5"/><circle class="dot" cx="56" cy="56" r="2"/>'},

{id:"halloumi",cat:"dairy",name:{en:"Halloumi",fr:"Halloumi"},latin:"Χαλλούμι",
origin:{en:"Cyprus",fr:"Chypre"},season:[],
flavor:["salty","milky","mild","umami"],
story:{en:"It survives a hot pan because the curd is cooked in whey before it is salted, which sets the proteins so firmly they will not flow again. Cypriot makers fold a mint leaf into the fold before brining — originally to keep it, now simply because that is how it is done.",
fr:"Il résiste à la poêle brûlante parce que le caillé est cuit dans le petit-lait avant d’être salé, ce qui fixe les protéines au point qu’elles ne coulent plus. Les fabricants chypriotes plient une feuille de menthe dans le pli avant la saumure — jadis pour le conserver, aujourd’hui parce que c’est ainsi."},
tip:{en:"Dry-fry it, no oil, in a very hot pan and do not move it until it releases. Eat it hot; cold halloumi turns to rubber.",
fr:"Poêlez-le à sec, sans huile, dans une poêle très chaude, sans le bouger tant qu’il n’accroche plus. Mangez-le chaud ; froid, il devient caoutchouteux."},
pairs:["mint","lemon","watermelon","olive-oil","oregano","tomato","honey","cucumber"],
svg:'<path class="f2 sf" d="M28 62V42h40v20z"/><path class="s" d="M34 42v20M46 42v20M58 42v20"/><path class="s" d="M28 52h40"/>'},

{id:"manchego",cat:"dairy",name:{en:"Manchego",fr:"Manchego"},latin:"Queso Manchego DOP",
origin:{en:"La Mancha, Spain",fr:"La Manche, Espagne"},season:[],
flavor:["nutty","tangy","rich","mild"],
story:{en:"The zigzag pattern round its side is a fossil. Wheels were once pressed inside plaited esparto grass belts, and the weave printed itself into the rind; the moulds are plastic now but the pattern is required by the designation. Don Quixote's saddlebags carried it.",
fr:"Le zigzag sur son flanc est un fossile. Les meules étaient jadis pressées dans des ceintures tressées d’alfa, dont le tissage s’imprimait dans la croûte ; les moules sont en plastique aujourd’hui mais le motif est exigé par l’appellation. Les besaces de Don Quichotte en portaient."},
tip:{en:"Cut it in thin triangles from the wedge, never in cubes. With quince paste and a few almonds it is a finished course.",
fr:"Coupez-le en triangles fins depuis la pointe, jamais en cubes. Avec de la pâte de coing et quelques amandes, c’est un plat fini."},
pairs:["quince","almond","olive-oil","fig","honey","iberico-ham","grape","paprika"],
svg:'<path class="f2 sf" d="M24 66q-3-13 0-26h48q3 13 0 26z"/><path class="s" d="M24 44l8 6-8 6M40 44l8 6-8 6M56 44l8 6-8 6"/>'},

{id:"mascarpone",cat:"dairy",name:{en:"Mascarpone",fr:"Mascarpone"},latin:"Mascarpone",
origin:{en:"Lombardy, Italy",fr:"Lombardie, Italie"},season:[],
flavor:["creamy","sweet","rich","milky"],
story:{en:"Cream set with a little acid and nothing else — no rennet, no ageing, no rind. That simplicity is why it carries other flavours so completely, and why tiramisù, invented in the Veneto in the 1960s or 70s, could not have been built on anything else.",
fr:"De la crème prise avec un peu d’acide et rien d’autre — ni présure, ni affinage, ni croûte. Cette simplicité explique qu’il porte si totalement les autres saveurs, et que le tiramisù, né en Vénétie dans les années 1960 ou 70, n’ait pu se bâtir sur rien d’autre."},
tip:{en:"Beat it as little as possible. Overworked mascarpone breaks and turns grainy, and it will not come back.",
fr:"Travaillez-le le moins possible. Trop battu, le mascarpone tranche et devient granuleux, sans retour possible."},
pairs:["coffee","dark-chocolate","vanilla","lemon","strawberry","honey","egg","raspberry"],
svg:'<path class="f3 sf" d="M32 64V44q16-8 32 0v20z"/><path class="s" d="M32 44q16 8 32 0"/><path class="s" d="M38 56q10 4 20 0"/>'},

{id:"morbier",cat:"dairy",name:{en:"Morbier",fr:"Morbier"},latin:"Morbier AOP",
origin:{en:"Jura, France",fr:"Jura, France"},season:[],
flavor:["creamy","nutty","mild","earthy"],
story:{en:"The black seam through the middle is a scar. Jura farmers with too little milk for a full Comté wheel saved the morning curd, covered it with soot from the cauldron to keep it clean, and added the evening curd on top. The ash is vegetable dye now, but the line is kept.",
fr:"La raie noire au milieu est une cicatrice. Les fermiers jurassiens qui n’avaient pas assez de lait pour une meule de comté gardaient le caillé du matin, le couvraient de suie du chaudron pour le protéger, et ajoutaient celui du soir par-dessus. La cendre est un colorant végétal aujourd’hui, mais la ligne est restée."},
tip:{en:"It melts kindly and is far cheaper than Comté for a gratin. Keep the line horizontal when you slice or the wedge falls apart.",
fr:"Il fond bien et coûte bien moins cher que le comté pour un gratin. Gardez la raie horizontale à la coupe, sinon la part se défait."},
pairs:["potato","onion","walnut","black-pepper","butter","apple","thyme","garlic"],
svg:'<path class="f2 sf" d="M24 68V38h48v30z"/><path class="s" d="M24 53h48" stroke-width="4"/><path class="s" d="M24 38h48"/>'},

{id:"mozzarella",cat:"dairy",name:{en:"Mozzarella",fr:"Mozzarella"},latin:"Mozzarella di bufala",
origin:{en:"Campania, Italy",fr:"Campanie, Italie"},season:[],
flavor:["milky","delicate","fresh","creamy"],
story:{en:"Named for the gesture — mozzare, to lop off — as cheesemakers tear each ball from the stretched curd by hand. The true one comes from water buffalo, brought to Italian marshlands centuries ago, and connoisseurs eat it the day it was pulled, never chilled.",
fr:"Nommée d’après le geste — mozzare, trancher — car le fromager arrache chaque boule à la pâte filée à la main. La vraie vient des bufflonnes, amenées dans les marais italiens il y a des siècles, et les connaisseurs la mangent le jour même du filage, jamais réfrigérée."},
tip:{en:"Take it out of the fridge an hour ahead — cold numbs its milky perfume. Tear it, never slice it, and salt it just before serving.",
fr:"Sortez-la du réfrigérateur une heure avant — le froid engourdit son parfum lacté. Déchirez-la, ne la tranchez jamais, et salez juste avant de servir."},
pairs:["tomato","basil","olive-oil","prosciutto","peach","oregano"],
svg:'<circle class="f1 sf" cx="48" cy="54" r="19"/><path class="s" d="M40 44q6-6 16-2" stroke-width="1.8"/><path class="f2 sf" d="M56 38q4-4 8-3-1 5-6 6z"/>'},

{id:"munster",cat:"dairy",name:{en:"Munster",fr:"Munster"},latin:"Munster-Géromé AOP",
origin:{en:"Vosges, Alsace",fr:"Vosges, Alsace"},season:[],
flavor:["pungent","creamy","salty","meaty"],
story:{en:"Irish monks settled the Vosges valleys in the seventh century and built a monasterium — the word wore down to Munster, and so did the cheese made there. Its orange coat is not mould but bacteria, washed on by hand every two days.",
fr:"Des moines irlandais s’installèrent dans les vallées vosgiennes au VIIe siècle et bâtirent un monasterium — le mot s’est usé en Munster, et le fromage avec. Sa robe orange n’est pas une moisissure mais une bactérie, lavée à la main tous les deux jours."},
tip:{en:"Alsace eats it with a saucer of cumin seed alongside, not mixed in. The seed cuts the barnyard and the two arrive together.",
fr:"L’Alsace le mange avec une soucoupe de cumin à côté, non mélangé. La graine coupe le côté étable et les deux arrivent ensemble."},
pairs:["cumin","potato","onion","black-pepper","caraway","flour-t65","butter","apple"],
svg:'<circle class="f1 sf" cx="48" cy="52" r="21"/><circle class="s" cx="48" cy="52" r="14"/><circle class="dot" cx="40" cy="46" r="1.6"/><circle class="dot" cx="56" cy="56" r="1.6"/><circle class="dot" cx="48" cy="62" r="1.6"/>'},

{id:"ossau-iraty",cat:"dairy",name:{en:"Ossau-Iraty",fr:"Ossau-Iraty"},latin:"Ossau-Iraty AOP",
origin:{en:"Béarn & Basque Country",fr:"Béarn & Pays basque"},season:[],
flavor:["nutty","sweet","rich","mild"],
story:{en:"Made from the milk of Manech and Basco-Béarnaise ewes, whose shepherds still move them up to summer pasture on foot. The Basques eat it with black cherry jam from Itxassou — a pairing so fixed that the cheese is rarely served without it.",
fr:"Fait du lait des brebis manech et basco-béarnaises, que les bergers montent encore à l’estive à pied. Les Basques le mangent avec la confiture de cerise noire d’Itxassou — accord si établi que le fromage se sert rarement sans elle."},
tip:{en:"If you cannot find black cherry jam, quince paste does the same job: the sheep's milk needs something sweet and slightly tart against it.",
fr:"À défaut de confiture de cerise noire, la pâte de coing fait le même office : ce lait de brebis appelle un sucré légèrement acidulé."},
pairs:["cherry","quince","walnut","honey","fig","almond","grape","espelette"],
svg:'<path class="f2 sf" d="M26 64q-3-12 0-24h44q3 12 0 24z"/><path class="s" d="M34 40v24M48 40v24M62 40v24"/>'},

{id:"parmesan",cat:"dairy",name:{en:"Parmesan",fr:"Parmesan"},latin:"Parmigiano Reggiano",
origin:{en:"Emilia-Romagna, Italy",fr:"Émilie-Romagne, Italie"},season:[],
flavor:["umami","salty","nutty","rich"],
story:{en:"Boccaccio, in 1350, dreamed up a paradise with a mountain of grated parmesan where cooks rolled pasta down the slopes. The dream still has a bank branch: Italian banks accept wheels of aging Parmigiano as loan collateral, guarded in climate-controlled vaults.",
fr:"Boccace, en 1350, imagina un paradis fait d’une montagne de parmesan râpé d’où les cuisiniers faisaient rouler les pâtes. Le rêve a encore une agence bancaire : des banques italiennes acceptent les meules en affinage comme garantie de prêt, gardées dans des chambres fortes climatisées."},
tip:{en:"Never discard the rind: dropped into a soup or a pot of beans, it melts its umami into the broth like a bouillon cube from heaven.",
fr:"Ne jetez jamais la croûte : glissée dans une soupe ou une marmite de haricots, elle fond son umami dans le bouillon comme un cube doré tombé du ciel."},
pairs:["balsamic","tomato","rice","egg","asparagus","fennel","porcini","pine-nut"],
svg:'<path class="f1 sf" d="M30 62l18-30 18 30q-18 8-36 0z"/><path class="s" d="M34 56l28 0" stroke-width="1.6"/><path class="dot" d="M44 52a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M50 58a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M42 60a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0M54 50a1.4 1.4 0 102.8 0 1.4 1.4 0 10-2.8 0"/>'},

{id:"pecorino",cat:"dairy",name:{en:"Pecorino Romano",fr:"Pecorino romano"},latin:"Pecorino Romano DOP",
origin:{en:"Lazio & Sardinia, Italy",fr:"Latium & Sardaigne, Italie"},season:[],
flavor:["salty","umami","tangy","rich"],
story:{en:"Roman legionaries carried a daily ration of it — around twenty-seven grams a man, recorded in the military accounts, because it kept for months and did not spoil on the march. It is the salt in carbonara and cacio e pepe, and it is much saltier than parmesan.",
fr:"Les légionnaires romains en portaient une ration quotidienne — environ vingt-sept grammes par homme, consignés dans les comptes militaires, parce qu’il se gardait des mois sans tourner en campagne. C’est le sel de la carbonara et du cacio e pepe, et il sale bien plus que le parmesan."},
tip:{en:"Salt the pasta water lightly when pecorino is coming. It seasons the dish on its own and there is no way back.",
fr:"Salez l’eau des pâtes légèrement quand le pecorino arrive. Il assaisonne le plat à lui seul, et il n’y a pas de retour en arrière."},
pairs:["black-pepper","guanciale","egg","fava-bean","olive-oil","tomato","basil","garlic"],
svg:'<path class="f1 sf" d="M24 66q-3-13 0-26h48q3 13 0 26z"/><path class="s" d="M32 40v26M48 40v26M64 40v26"/>'},

{id:"reblochon",cat:"dairy",name:{en:"Reblochon",fr:"Reblochon"},latin:"Reblochon de Savoie AOP",
origin:{en:"Haute-Savoie, France",fr:"Haute-Savoie, France"},season:[],
flavor:["creamy","nutty","mild","earthy"],
story:{en:"Its name comes from reblocher — to milk a second time. Savoyard tenants were taxed on the volume they drew, so they left the udder half-empty while the landlord's man watched, then milked again once he had gone. The richest milk of the day became a cheese made from fraud.",
fr:"Son nom vient de reblocher — traire une seconde fois. Les tenanciers savoyards étaient taxés sur le volume tiré : ils laissaient le pis à moitié plein devant l’homme du seigneur, puis retrayaient une fois celui-ci parti. Le lait le plus riche de la journée est devenu un fromage né d’une fraude."},
tip:{en:"The whole point of a tartiflette is that it melts without splitting. Split the wheel through its waist, rind up, and let it collapse into the potatoes.",
fr:"Tout l’intérêt de la tartiflette est qu’il fond sans trancher. Coupez la meule dans l’épaisseur, croûte au-dessus, et laissez-le s’affaisser sur les pommes de terre."},
pairs:["potato","onion","guanciale","cream","black-pepper","white-wine-vinegar","garlic","thyme"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="22"/><circle class="s" cx="48" cy="52" r="15"/><circle class="dot" cx="48" cy="52" r="3"/>'},

{id:"ricotta",cat:"dairy",name:{en:"Ricotta",fr:"Ricotta"},latin:"Ricotta — recooked",
origin:{en:"Italy",fr:"Italie"},season:[],
flavor:["milky","sweet","delicate","creamy"],
story:{en:"Not a cheese at all, strictly — it is made from the whey left over after cheesemaking, reheated until the last proteins surface. The name says so: ricotta, recooked. It is the thrift of the dairy, and half of Italian pastry rests on it.",
fr:"Pas un fromage à proprement parler — elle est faite du petit-lait resté après la fabrication, réchauffé jusqu’à ce que les dernières protéines remontent. Le nom le dit : ricotta, recuite. C’est l’économie de la laiterie, et la moitié de la pâtisserie italienne repose dessus."},
tip:{en:"Drain it in a sieve for an hour before it goes into a filling, or the water comes out in the oven and ruins the pastry.",
fr:"Égouttez-la une heure dans une passoire avant de la mettre en garniture, sinon l’eau ressort au four et ruine la pâte."},
pairs:["honey","lemon","spinach","basil","dark-chocolate","orange","pistachio","tomato"],
svg:'<path class="f3 sf" d="M30 64q0-20 18-26 18 6 18 26z"/><path class="s" d="M36 56q12-6 24 0"/>'},

{id:"roquefort",cat:"dairy",name:{en:"Roquefort",fr:"Roquefort"},latin:"Penicillium roqueforti",
origin:{en:"Roquefort-sur-Soulzon, Aveyron",fr:"Roquefort-sur-Soulzon, Aveyron"},season:[],
flavor:["salty","umami","rich","pungent"],
story:{en:"It ripens only in the Combalou caves, where a collapsed mountain left natural chimneys called fleurines that breathe damp air through the rock. In 1925 it became the first French cheese granted an appellation — the law arrived to protect a draught.",
fr:"Il n’affine que dans les caves du Combalou, où l’effondrement de la montagne a laissé des cheminées naturelles, les fleurines, qui font respirer l’air humide à travers la roche. En 1925, il devint le premier fromage français protégé par une appellation — la loi est venue protéger un courant d’air."},
tip:{en:"Never cook it hard. Melt it off the heat into warm cream, or it turns bitter and grainy.",
fr:"Ne le cuisez jamais fort. Faites-le fondre hors du feu dans de la crème chaude, sinon il devient amer et granuleux."},
pairs:["pear","walnut","honey","fig","celery","butter","grape","banyuls-vinegar"],
svg:'<path class="f1 sf" d="M24 66 L48 28 L72 66 Z"/><circle class="dot" cx="42" cy="52" r="2.5"/><circle class="dot" cx="52" cy="58" r="2.5"/><circle class="dot" cx="46" cy="61" r="2"/><circle class="dot" cx="56" cy="48" r="2"/>'},

{id:"saint-nectaire",cat:"dairy",name:{en:"Saint-Nectaire",fr:"Saint-Nectaire"},latin:"Saint-Nectaire AOP",
origin:{en:"Monts Dore, Auvergne",fr:"Monts Dore, Auvergne"},season:[],
flavor:["earthy","nutty","mild","umami"],
story:{en:"It ripens on rye straw in volcanic cellars, and takes on the cellar: mushroom, damp stone, hazelnut. It reached Versailles through Marshal de Senectaire, who served it to Louis XIV — one of the few French cheeses named after the courtier who marketed it rather than the village that made it.",
fr:"Il s’affine sur paille de seigle dans des caves volcaniques, et prend la cave : champignon, pierre humide, noisette. Il arriva à Versailles par le maréchal de Senectaire, qui le servit à Louis XIV — l’un des rares fromages français nommé d’après le courtisan qui l’a vendu plutôt que du village qui le fait."},
tip:{en:"Look for the green casein plate on the rind: oval means farmhouse, square means dairy. The difference is real.",
fr:"Cherchez la plaque de caséine verte sur la croûte : ovale pour le fermier, carrée pour le laitier. La différence est réelle."},
pairs:["potato","mushroom","walnut","onion","butter","thyme","apple","black-pepper"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="22"/><path class="s" d="M30 44h36M30 52h36M30 60h36"/>'},

{id:"beurre-demi-sel",cat:"dairy",name:{en:"Salted butter",fr:"Beurre demi-sel"},latin:"Beurre demi-sel",
origin:{en:"Brittany, France",fr:"Bretagne, France"},season:[],
flavor:["salty","creamy","rich","buttery"],
story:{en:"Brittany was exempt from the gabelle, the salt tax that crushed the rest of France, so Breton dairies salted their butter freely while everyone else could not afford to. A tax boundary drawn centuries ago still divides French breakfast tables.",
fr:"La Bretagne était exemptée de la gabelle, l’impôt sur le sel qui écrasait le reste de la France, si bien que les beurriers bretons salaient à volonté quand les autres ne le pouvaient pas. Une frontière fiscale tracée il y a des siècles partage encore les tables du petit-déjeuner français."},
tip:{en:"Reduce the salt elsewhere in the recipe, especially in baking. Demi-sel carries enough to matter in a cake.",
fr:"Réduisez le sel ailleurs dans la recette, surtout en pâtisserie. Le demi-sel en apporte assez pour compter dans un gâteau."},
pairs:["flour-t65","maple-syrup","radish","dark-chocolate","apple","buckwheat","honey","potato"],
svg:'<path class="f3 sf" d="M32 68V52h32v16z"/><path class="s" d="M32 58h32"/><circle class="dot" cx="40" cy="63" r="1.4"/><circle class="dot" cx="50" cy="63" r="1.4"/><circle class="dot" cx="58" cy="63" r="1.4"/>'},

{id:"creme-epaisse",cat:"dairy",name:{en:"Thick double cream",fr:"Crème épaisse"},latin:"Crème épaisse, 30–40% MG",
origin:{en:"Normandy, France",fr:"Normandie, France"},season:[],
flavor:["rich","creamy","milky","sweet"],
story:{en:"French dairy counters split cream two ways and the difference matters more than shoppers think: liquide whips and pours, épaisse does neither well but enriches without thinning. Confusing the two is the most common reason a home sauce goes wrong.",
fr:"Les crémeries françaises séparent la crème en deux, et la différence compte plus qu’on ne croit : la liquide monte et se verse, l’épaisse ne fait bien ni l’un ni l’autre mais enrichit sans délayer. Les confondre est la première cause d’une sauce ratée à la maison."},
tip:{en:"It will not whip — the fat is already set. For chantilly you need crème liquide entière at 30% or above, and very cold.",
fr:"Elle ne monte pas — la matière grasse est déjà prise. Pour une chantilly il faut de la crème liquide entière à 30 % au moins, et très froide."},
pairs:["potato","mushroom","shallot","nutmeg","black-pepper","leek","egg","butter"],
svg:'<path class="f3 sf" d="M32 66V46q16-8 32 0v20z"/><path class="s" d="M32 46q16 8 32 0"/>'},

{id:"tomme-de-savoie",cat:"dairy",name:{en:"Tomme de Savoie",fr:"Tomme de Savoie"},latin:"Tomme de Savoie IGP",
origin:{en:"Savoie, France",fr:"Savoie, France"},season:[],
flavor:["earthy","mild","nutty","milky"],
story:{en:"This is what was left over. Savoyard farms skimmed the cream for butter and made tomme from what remained, which is why it is lean where alpine cheeses are usually fat. Its grey, bloomed, faintly ugly rind was never meant to be looked at.",
fr:"C’est ce qui restait. Les fermes savoyardes écrémaient le lait pour le beurre et faisaient la tomme avec le reste, d’où sa maigreur là où les fromages d’alpage sont gras. Sa croûte grise, fleurie, un peu laide, n’a jamais été faite pour être regardée."},
tip:{en:"Do not trim the rind away entirely — most of the cellar smell lives there, and the paste alone is quiet.",
fr:"Ne parez pas toute la croûte — l’odeur de cave y loge, et la pâte seule est muette."},
pairs:["potato","apple","walnut","onion","black-pepper","grape","butter","thyme"],
svg:'<circle class="f1 sf" cx="48" cy="52" r="22"/><circle class="s" cx="48" cy="52" r="16"/><circle class="dot" cx="38" cy="44" r="1.4"/><circle class="dot" cx="58" cy="48" r="1.4"/><circle class="dot" cx="44" cy="62" r="1.4"/><circle class="dot" cx="58" cy="60" r="1.4"/>'},

{id:"yogurt",cat:"dairy",name:{en:"Yogurt",fr:"Yaourt"},latin:"Lac fermentatum",
origin:{en:"Central Asia & Balkans",fr:"Asie centrale & Balkans"},season:[],
flavor:["tangy","creamy","milky","fresh"],
story:{en:"Nomads discovered it by accident: milk carried in animal-skin bags fermented on horseback into something tart that kept. Centuries later, a scientist studying Bulgarian villages full of centenarians credited their yogurt — and Europe has eaten it for breakfast ever since.",
fr:"Les nomades le découvrirent par accident : le lait transporté dans des outres fermentait à dos de cheval en quelque chose d’acidulé qui se gardait. Des siècles plus tard, un savant étudiant des villages bulgares peuplés de centenaires en crédita leur yaourt — et l’Europe en mange au petit-déjeuner depuis."},
tip:{en:"To cook with it without curdling, temper it: whisk a little hot liquid into the yogurt before the yogurt goes into the pot.",
fr:"Pour le cuisiner sans qu’il tranche, tempérez-le : fouettez un peu de liquide chaud dans le yaourt avant que le yaourt n’aille dans la marmite."},
pairs:["honey","mint","cumin","dill","mango","pomegranate","beetroot","chives"],
svg:'<path class="f1 sf" d="M36 42h24v24q0 8-12 8t-12-8z"/><path class="f2 sf" d="M34 38h28v6H34z"/><path class="s" d="M42 56q6 4 12 0" stroke-width="1.8"/>'},

{id:"epoisses",cat:"dairy",name:{en:"Époisses",fr:"Époisses"},latin:"Époisses AOP",
origin:{en:"Côte-d’Or, Burgundy",fr:"Côte-d’Or, Bourgogne"},season:[],
flavor:["pungent","creamy","salty","rich"],
story:{en:"Washed with Marc de Bourgogne three times a week for its whole ripening, which is why it smells the way it does and why its rind glows brick orange. Cistercian monks devised it in the sixteenth century; by the 1950s only two producers were left, and it nearly vanished.",
fr:"Lavé au marc de Bourgogne trois fois par semaine durant tout l’affinage, d’où son odeur et sa croûte orange brique. Des moines cisterciens le mirent au point au XVIe siècle ; dans les années 1950 il ne restait que deux producteurs, et il faillit disparaître."},
tip:{en:"Serve it in its wooden box with a spoon. At full ripeness it has no structure to cut, and a knife just pushes it around.",
fr:"Servez-le dans sa boîte, à la cuillère. À pleine maturité il n’a plus de tenue, et le couteau ne fait que le pousser."},
pairs:["potato","walnut","black-pepper","butter","onion","grape","flour-t65","cream"],
svg:'<circle class="f1 sf" cx="48" cy="53" r="20"/><path class="s" d="M28 53q20 12 40 0"/><circle class="s" cx="48" cy="53" r="13"/>'}
]);
