// Chefs — chronological. Descriptive only: dates, documented work, recorded
// influence. No rankings, no superlatives, no judgement of anyone's cooking.
window.CHEFS = (window.CHEFS || []).concat([

{id:"taillevent", name:"Guillaume Tirel, dit Taillevent", born:1310, died:1395, approx:true,
 place:{en:"France — court of Charles V",fr:"France — cour de Charles V"},
 role:{en:"Cook to the French court",fr:"Queux de la cour de France"},
 work:{en:"Le Viandier",fr:"Le Viandier"},
 contribution:{en:"Cooked for Charles V and Charles VI and is associated with Le Viandier, one of the earliest recipe collections written in French. The manuscripts predate his career in part, so authorship is shared and disputed. The recipes show a cuisine built on spices, verjuice and bread-thickened sauces, with little of the butter and stock that came later.",
 fr:"Cuisinier de Charles V puis de Charles VI, son nom est attaché au Viandier, l’un des plus anciens recueils de recettes rédigés en français. Une partie des manuscrits est antérieure à sa carrière : la paternité en est donc partagée et discutée. Les recettes montrent une cuisine d’épices, de verjus et de sauces liées au pain, sans le beurre ni les fonds qui viendront plus tard."},
 legacy:{en:"His tomb at Saint-Germain-en-Laye shows him in armour between three cooking pots — among the earliest images of a cook commemorated as a figure of standing.",
 fr:"Sa pierre tombale à Saint-Germain-en-Laye le montre en armure entre trois marmites — l’une des plus anciennes images d’un cuisinier commémoré comme un personnage de rang."},
 ingredients:["verjus","black-pepper","cinnamon","ginger","saffron","clove","nutmeg","almond"]},

{id:"lavarenne", name:"François Pierre de La Varenne", born:1618, died:1678,
 place:{en:"Dijon, France",fr:"Dijon, France"},
 role:{en:"Cook to the Marquis d’Uxelles",fr:"Cuisinier du marquis d’Uxelles"},
 work:{en:"Le Cuisinier françois (1651)",fr:"Le Cuisinier françois (1651)"},
 contribution:{en:"His book is generally treated as the boundary between medieval and modern French cooking. It moves away from heavy spicing towards butter, local herbs and reduced cooking liquids, and contains early written descriptions of roux, bouquet garni and stock-based sauces. Duxelles is named after his employer.",
 fr:"Son ouvrage est généralement tenu pour la frontière entre cuisine médiévale et cuisine française moderne. Il s’éloigne des épices lourdes au profit du beurre, des herbes locales et des jus réduits, et contient des descriptions écrites précoces du roux, du bouquet garni et des sauces montées sur fonds. La duxelles porte le nom de son employeur."},
 legacy:{en:"The book was reprinted for over a century and translated across Europe, which spread the new style well beyond France.",
 fr:"L’ouvrage fut réimprimé plus d’un siècle et traduit dans toute l’Europe, ce qui diffusa le nouveau style bien au-delà de la France."},
 ingredients:["beurre-de-baratte","mushroom","shallot","thyme","bay-leaf","parsley","flour-t55","white-wine-vinegar"]},

{id:"careme", name:"Marie-Antoine Carême", born:1784, died:1833,
 place:{en:"Paris — Talleyrand, later foreign courts",fr:"Paris — Talleyrand, puis cours étrangères"},
 role:{en:"Cook and pastry chef",fr:"Cuisinier et pâtissier"},
 work:{en:"L’Art de la cuisine française au XIXe siècle",fr:"L’Art de la cuisine française au XIXe siècle"},
 contribution:{en:"Worked for Talleyrand, the Prince Regent in London and the Russian court. He grouped sauces into families under a set of base preparations — the system later reduced to the mother sauces — and wrote extensively on organisation and presentation. His pièces montées were built as architectural constructions, a discipline he had studied.",
 fr:"Au service de Talleyrand, du prince régent à Londres et de la cour de Russie. Il regroupa les sauces en familles sous quelques préparations de base — le système ramené plus tard aux sauces mères — et écrivit abondamment sur l’organisation et la présentation. Ses pièces montées étaient conçues comme des constructions architecturales, discipline qu’il avait étudiée."},
 legacy:{en:"He worked at a scale and for a clientele that made French cooking a European reference, and his written system gave later cooks something to revise rather than invent.",
 fr:"Il travailla à une échelle et pour une clientèle qui firent de la cuisine française une référence européenne, et son système écrit donna aux suivants quelque chose à réviser plutôt qu’à inventer."},
 ingredients:["beurre-de-baratte","flour-t45","sugar","egg","cream","truffle","almond","vanilla"]},

{id:"escoffier", name:"Auguste Escoffier", born:1846, died:1935,
 place:{en:"Savoy and Carlton hotels, London",fr:"Hôtels Savoy et Carlton, Londres"},
 role:{en:"Chef de cuisine and author",fr:"Chef de cuisine et auteur"},
 work:{en:"Le Guide culinaire (1903)",fr:"Le Guide culinaire (1903)"},
 contribution:{en:"Working with the hotelier César Ritz, he reorganised professional kitchens into the brigade system — separate stations, each with a defined role, reporting to a chef de cuisine. Le Guide culinaire condensed and simplified Carême's repertoire into a working reference, and reduced the sauce families to a shorter list still taught today.",
 fr:"Avec l’hôtelier César Ritz, il réorganisa les cuisines professionnelles en brigade — des parties distinctes, chacune au rôle défini, sous l’autorité d’un chef de cuisine. Le Guide culinaire condensa et simplifia le répertoire de Carême en un ouvrage de travail, et ramena les familles de sauces à une liste plus courte, toujours enseignée."},
 legacy:{en:"The brigade structure and much of the vocabulary in Le Guide culinaire remain in use in professional kitchens internationally.",
 fr:"La structure en brigade et une grande part du vocabulaire du Guide culinaire restent en usage dans les cuisines professionnelles du monde entier."},
 ingredients:["tenderloin","beurre-de-baratte","shallot","truffle","tarragon","flour-t55","cream","tomato"]},

{id:"brazier", name:"Eugénie Brazier, la Mère Brazier", born:1895, died:1977,
 stars:{n:3, years:"1933",
  note:{en:"Three stars at two restaurants at once — six in total, and the first three awarded to a woman.",fr:"Trois étoiles dans deux maisons à la fois — six au total, et les trois premières décernées à une femme."}},
 place:{en:"Lyon and col de la Luère",fr:"Lyon et col de la Luère"},
 role:{en:"Cook and restaurateur",fr:"Cuisinière et restauratrice"},
 work:{en:"La Mère Brazier, rue Royale",fr:"La Mère Brazier, rue Royale"},
 contribution:{en:"Came from the mères lyonnaises, women who had cooked in bourgeois households and then opened their own restaurants. In 1933 she was awarded three Michelin stars at two establishments at once — the first person to hold six stars simultaneously, and the first woman awarded three. Her cooking stayed close to the Lyonnais repertoire.",
 fr:"Issue des mères lyonnaises, ces femmes passées des maisons bourgeoises à leurs propres restaurants. En 1933, elle obtint trois étoiles Michelin dans deux établissements à la fois — première personne à détenir six étoiles simultanément, et première femme à en obtenir trois. Sa cuisine resta proche du répertoire lyonnais."},
 legacy:{en:"Paul Bocuse trained in her kitchen. No woman was awarded three stars in France again until 2007.",
 fr:"Paul Bocuse fit son apprentissage dans sa cuisine. Aucune femme ne fut à nouveau distinguée de trois étoiles en France avant 2007."},
 ingredients:["chicken","truffle","artichoke","foie-gras","beurre-de-baratte","cream","morel","tarragon"]},

{id:"point", name:"Fernand Point", born:1897, died:1955,
 stars:{n:3, years:"1933–1955",
  note:{en:"Three stars held continuously from 1933 until his death.",fr:"Trois étoiles conservées sans interruption de 1933 à sa mort."}},
 place:{en:"La Pyramide, Vienne",fr:"La Pyramide, Vienne"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"Ma Gastronomie (published 1969)",fr:"Ma Gastronomie (paru en 1969)"},
 contribution:{en:"Ran La Pyramide from 1925, holding three stars from 1933. He worked with lighter treatments and shorter cooking than the hotel repertoire of the period, and insisted on buying produce daily. He took apprentices who later ran their own three-star kitchens.",
 fr:"Il tint La Pyramide à partir de 1925, trois étoiles depuis 1933. Il travailla des cuissons plus légères et plus courtes que le répertoire hôtelier de l’époque, et imposa un approvisionnement quotidien. Il forma des apprentis qui dirigèrent ensuite leurs propres maisons trois étoiles."},
 legacy:{en:"Bocuse, the Troisgros brothers, Alain Chapel and François Bise all passed through his kitchen, which is why he is often placed at the start of the line leading to nouvelle cuisine.",
 fr:"Bocuse, les frères Troisgros, Alain Chapel et François Bise passèrent tous par sa cuisine, ce qui le place souvent à l’origine de la lignée menant à la nouvelle cuisine."},
 ingredients:["beurre-de-baratte","cream","morel","truffle","crayfish","asparagus","chicken","tarragon"]},

{id:"bocuse", name:"Paul Bocuse", born:1926, died:2018,
 stars:{n:3, years:"1965–2019",
  note:{en:"Fifty-four consecutive years at three stars, among the longest runs recorded.",fr:"Cinquante-quatre années consécutives à trois étoiles, l’une des plus longues séries enregistrées."}},
 place:{en:"Collonges-au-Mont-d’Or",fr:"Collonges-au-Mont-d’Or"},
 role:{en:"Chef-patron",fr:"Chef-propriétaire"},
 work:{en:"L’Auberge du Pont de Collonges",fr:"L’Auberge du Pont de Collonges"},
 contribution:{en:"Trained with Eugénie Brazier and Fernand Point. His restaurant held three Michelin stars from 1965 to 2019, one of the longest unbroken runs recorded. He was among the chefs associated with nouvelle cuisine in the 1970s, though he continued to cook classical dishes alongside it.",
 fr:"Formé chez Eugénie Brazier puis Fernand Point. Son restaurant conserva trois étoiles Michelin de 1965 à 2019, l’une des plus longues séries ininterrompues enregistrées. Il fut de ceux qu’on associa à la nouvelle cuisine dans les années 1970, tout en continuant de cuisiner le répertoire classique."},
 legacy:{en:"He founded the Bocuse d’Or competition in 1987 and a cookery school in Écully, and was among the first chefs widely known to the public outside the profession.",
 fr:"Il fonda le concours du Bocuse d’Or en 1987 et une école de cuisine à Écully, et fut l’un des premiers cuisiniers largement connus du public hors de la profession."},
 ingredients:["truffle","chicken","foie-gras","beurre-de-baratte","bresse-chicken","morel","cream","potato"]}

]);
