// Work trees — an ingredient at the core, its preparations as branches.
// Pilot: potato only. Each branch carries the technique, the variety it needs,
// concrete tips, and the pairings that work *in that form* — which differ per branch.
window.TREES = (window.TREES || []).concat([

{id:"potato", branches:[

  {id:"puree", name:{en:"Purée",fr:"Purée"},
   variety:{en:"Floury — bintje, agria, russet",fr:"Farineuse — bintje, agria, russet"},
   technique:{en:"Cook them whole and unpeeled so they take on no water, then peel while too hot to hold. Pass through a ricer or a food mill — never a blender, which bursts the starch cells and turns the whole thing to glue in seconds. Cold cubed butter first, then hot milk, off the heat.",
   fr:"Cuisez-les entières et non pelées pour qu’elles ne prennent pas l’eau, puis épluchez-les brûlantes. Passez au presse-purée ou au moulin à légumes — jamais au blender, qui fait éclater les cellules d’amidon et transforme le tout en colle en quelques secondes. Beurre froid en cubes d’abord, puis lait chaud, hors du feu."},
   tips:[{en:"Waxy potatoes will not make a good purée. The variety decides this before you start.",fr:"Une pomme de terre à chair ferme ne fera pas une bonne purée. La variété décide avant même de commencer."},
         {en:"Robuchon's version is up to half butter by weight. You do not have to go that far, but the butter goes in cold and the milk goes in hot — reverse it and it splits.",fr:"La version de Robuchon monte à moitié beurre en poids. Nul besoin d’aller si loin, mais le beurre entre froid et le lait chaud — l’inverse la fait trancher."}],
   pairs:["beurre-de-baratte","cream","nutmeg","black-pepper","chives","comte","garlic","olive-oil"]},

  {id:"roasted", name:{en:"Roasted",fr:"Rôties"},
   variety:{en:"Floury",fr:"Farineuse"},
   technique:{en:"Par-boil until the edges just soften, drain completely, then shake them hard in the dry pan until the surfaces go rough and floury. That broken surface is the whole crust. Into fat that is already shimmering, in a single layer, and left alone.",
   fr:"Précuisez jusqu’à ce que les arêtes s’attendrissent, égouttez à fond, puis secouez-les fermement dans la casserole sèche jusqu’à ce que la surface devienne rugueuse et farineuse. Cette surface éclatée fait toute la croûte. Dans une graisse déjà fumante, en une seule couche, et qu’on ne touche plus."},
   tips:[{en:"Crowding the tin steams them. Two tins beats one full one, every time.",fr:"Une plaque surchargée les cuit à la vapeur. Deux plaques valent toujours mieux qu’une pleine."},
         {en:"Duck fat and beef dripping hold a higher heat than butter and taste of more than oil.",fr:"La graisse de canard et celle de bœuf tiennent une chaleur plus vive que le beurre et ont plus de goût qu’une huile."}],
   pairs:["duck-fat","rosemary","garlic","thyme","lard","black-pepper","salt","bay-leaf"]},

  {id:"confites", art:"confit", name:{en:"Confit",fr:"Confites"},
   variety:{en:"Waxy or new",fr:"Chair ferme ou primeur"},
   technique:{en:"Submerged whole in fat held at around 85–90°C — low enough that nothing fries. The fat is a cooking medium, not a fryer: it conducts heat evenly and keeps air off the surface. They should stay pale until you raise the heat at the very end.",
   fr:"Immergées entières dans une graisse tenue autour de 85–90 °C — assez basse pour que rien ne frise. La graisse est un milieu de cuisson, non une friture : elle conduit la chaleur uniformément et écarte l’air de la surface. Elles doivent rester pâles jusqu’à ce qu’on monte le feu tout à la fin."},
   tips:[{en:"If it bubbles vigorously the fat is too hot. You want the barest tremble.",fr:"Si ça bouillonne franchement, la graisse est trop chaude. On cherche un frémissement à peine visible."},
         {en:"Strain the fat and keep it. It gets better each time you use it.",fr:"Filtrez la graisse et gardez-la. Elle s’améliore à chaque usage."}],
   pairs:["duck-fat","garlic","thyme","bay-leaf","rosemary","black-pepper","shallot","lard"]},

  {id:"gratin", name:{en:"Gratin",fr:"Gratin"},
   variety:{en:"Waxy or all-purpose",fr:"Chair ferme ou polyvalente"},
   technique:{en:"Sliced two or three millimetres thin and — this is the part people get wrong — never rinsed. The surface starch is what thickens the cream into a sauce. Simmer the slices in the cream on the stove first, then bake; going straight to the oven leaves them chalky.",
   fr:"Taillées à deux ou trois millimètres et — c’est là qu’on se trompe — jamais rincées. L’amidon de surface est ce qui lie la crème en sauce. Faites d’abord frémir les tranches dans la crème sur le feu, puis enfournez ; passer directement au four les laisse crayeuses."},
   tips:[{en:"A true dauphinois has no cheese and no egg. Cream, garlic, nutmeg, and time.",fr:"Un vrai dauphinois n’a ni fromage ni œuf. Crème, ail, muscade, et du temps."},
         {en:"Rub the dish with a cut garlic clove rather than adding chopped garlic, which catches and burns.",fr:"Frottez le plat d’une gousse coupée plutôt que d’ajouter de l’ail haché, qui accroche et brûle."}],
   pairs:["cream","garlic","nutmeg","comte","beaufort","black-pepper","thyme","creme-epaisse"]},

  {id:"gnocchi", art:"dumpling", name:{en:"Gnocchi",fr:"Gnocchi"},
   variety:{en:"Floury",fr:"Farineuse"},
   technique:{en:"Bake the potatoes rather than boiling them — boiled ones drink water, and every gram of water costs you a gram of flour later. Rice them hot and let the steam escape. Then the least flour you can get away with, worked fast and barely at all.",
   fr:"Cuisez les pommes de terre au four plutôt qu’à l’eau — bouillies elles boivent, et chaque gramme d’eau se paie en un gramme de farine ensuite. Passez-les chaudes au presse-purée et laissez la vapeur s’échapper. Puis le moins de farine possible, travaillée vite et à peine."},
   tips:[{en:"Every extra handful of flour makes them tougher. The dough should feel barely holdable.",fr:"Chaque poignée de farine en trop les rend plus fermes. La pâte doit tenir tout juste."},
         {en:"They are done seconds after they float. Waiting turns them to paste.",fr:"Ils sont prêts quelques secondes après avoir remonté. Attendre les transforme en pâte."}],
   pairs:["flour-t55","egg","parmesan","sage","beurre-de-baratte","nutmeg","black-pepper","semolina"]},

  {id:"frites", art:"chips", name:{en:"Chips",fr:"Frites"},
   variety:{en:"Floury",fr:"Farineuse"},
   technique:{en:"Cut, rinse off the loose starch, then dry them properly — water is what makes fat spit and skins go leathery. Two fries: around 150°C to cook them through without colour, cool completely, then 180–190°C to crisp. The rest between the two matters as much as either.",
   fr:"Taillez, rincez l’amidon libre, puis séchez-les vraiment — c’est l’eau qui fait crépiter la graisse et cuirasse la peau. Deux bains : environ 150 °C pour les cuire à cœur sans coloration, refroidissement complet, puis 180–190 °C pour croustiller. Le repos entre les deux compte autant que les bains."},
   tips:[{en:"One fry gives you either raw middles or burnt outsides. There is no single temperature that does both.",fr:"Un seul bain donne un cœur cru ou un extérieur brûlé. Aucune température ne fait les deux."},
         {en:"Salt them the instant they leave the fat, while the surface can still take it.",fr:"Salez-les à la seconde où elles sortent du bain, tant que la surface peut le prendre."}],
   pairs:["salt","peanut-oil","duck-fat","black-pepper","malt-vinegar","paprika","garlic","parsley"]}

]},

{id:"egg", branches:[

  {id:"coque", name:{en:"Soft-boiled",fr:"À la coque"},
   variety:{en:"3 min runny · 6 min mollet · 9 min hard",fr:"3 min coque · 6 min mollet · 9 min dur"},
   technique:{en:"Lower them into water already at a rolling boil and start the clock — starting cold makes the timing depend on your pan, your hob and how much water you used. Straight into iced water at the end, which stops the cooking dead and contracts the white away from the shell.",
   fr:"Plongez-les dans une eau déjà à gros bouillons et lancez le chronomètre — démarrer à froid fait dépendre le temps de votre casserole, de votre feu et du volume d’eau. Glace à la fin, ce qui arrête net la cuisson et décolle le blanc de la coquille."},
   tips:[{en:"Older eggs peel cleanly, fresh ones tear. The membrane detaches as the egg ages — the one job a week-old egg does better.",fr:"Les œufs un peu vieux s’écalent net, les très frais s’arrachent. La membrane se décolle avec l’âge — la seule tâche qu’un œuf d’une semaine fait mieux."},
         {en:"A green ring around the yolk is overcooking, not spoilage: iron and sulphur meeting at heat.",fr:"L’auréole verte autour du jaune est une surcuisson, non une altération : du fer et du soufre qui se rencontrent à la chaleur."}],
   pairs:["salt","beurre-de-baratte","asparagus","black-pepper","chives","truffle","flour-t65","anchovy"]},

  {id:"poche", art:"poached", name:{en:"Poached",fr:"Poché"},
   variety:{en:"The freshest egg you have",fr:"L’œuf le plus frais possible"},
   technique:{en:"Freshness does almost all the work. A white has two layers; the outer one thins with age and becomes the wisps everyone blames on technique. Water at a bare tremble, never a boil, which tears the egg apart.",
   fr:"La fraîcheur fait presque tout. Un blanc a deux couches ; l’extérieure se liquéfie avec l’âge et devient les filaments qu’on impute à tort à la technique. Une eau à peine frémissante, jamais bouillante, qui déchirerait l’œuf."},
   tips:[{en:"Crack it into a fine sieve first and let the loose white drain away. That does more than vinegar and whirlpools combined.",fr:"Cassez-le d’abord dans une passoire fine et laissez s’égoutter le blanc liquide. Cela fait plus que le vinaigre et le tourbillon réunis."},
         {en:"They poach perfectly the day before — into iced water, then thirty seconds in hot water to serve.",fr:"Ils se pochent très bien la veille — glace aussitôt, puis trente secondes à l’eau chaude au service."}],
   pairs:["white-wine-vinegar","spinach","lard","chives","black-pepper","frisee","escarole","beurre-de-baratte"]},

  {id:"brouilles", art:"scrambled", name:{en:"Scrambled",fr:"Brouillés"},
   variety:{en:"Low heat, constant motion",fr:"Feu doux, mouvement constant"},
   technique:{en:"The French way is low and slow with a spatula never stopping — small glossy curds that pour rather than pile. Anything approaching a proper heat gives large dry curds and weeping water. Butter or cream goes in off the heat, at the end.",
   fr:"À la française : feu doux et spatule qui ne s’arrête jamais — des grains fins et brillants qui coulent plutôt qu’ils ne s’empilent. Une chaleur un peu vive donne de gros grains secs et rend de l’eau. Beurre ou crème hors du feu, à la fin."},
   tips:[{en:"Take them off looking distinctly underdone. The pan keeps cooking them for another thirty seconds in your hand.",fr:"Retirez-les alors qu’ils semblent nettement pas assez cuits. La casserole continue trente secondes dans votre main."},
         {en:"Salt at the end. Salted early, the proteins tighten and the eggs weep.",fr:"Salez à la fin. Salés tôt, les protéines se resserrent et les œufs rendent de l’eau."}],
   pairs:["beurre-de-baratte","cream","chives","truffle","comte","black-pepper","salmon","morel"]},

  {id:"omelette", name:{en:"Omelette",fr:"Omelette"},
   variety:{en:"French rolled — no colour",fr:"Roulée à la française — sans coloration"},
   technique:{en:"A French omelette takes no colour at all: high heat but very short, fork stirring while the pan shakes, then stop and let a thin skin set on the base. Rolled out still baveuse — visibly loose in the middle, which finishes on the plate.",
   fr:"Une omelette française ne prend aucune couleur : feu vif mais très court, fourchette qui brasse pendant que la poêle secoue, puis on arrête et on laisse une fine peau prendre au fond. Roulée encore baveuse — visiblement coulante au centre, ce qui finit dans l’assiette."},
   tips:[{en:"Beat only until yolks and whites combine. Over-beaten eggs go foamy and cook spongy.",fr:"Battez juste jusqu’à mélange des jaunes et des blancs. Trop battus, les œufs moussent et cuisent en éponge."},
         {en:"A browned omelette is a different dish, not a mistake — but it is not this one.",fr:"Une omelette dorée est un autre plat, non une erreur — mais ce n’est pas celui-ci."}],
   pairs:["beurre-de-baratte","chives","gruyere","parsley","tarragon","mushroom","comte","prosciutto"]},

  {id:"auplat", art:"friedegg", name:{en:"Fried",fr:"Au plat"},
   variety:{en:"Hot fat for lace · gentle for tender",fr:"Gras chaud pour la dentelle · doux pour le fondant"},
   technique:{en:"The fat temperature decides which egg you get, and they are two different foods. Very hot oil gives crisp brown lace at the edges and a firm base; gentle butter gives a tender, pale, silky white. Neither is more correct.",
   fr:"La température du gras décide de l’œuf obtenu, et ce sont deux aliments différents. Une huile très chaude donne une dentelle brune et croustillante et un fond ferme ; un beurre doux donne un blanc pâle, tendre et soyeux. Aucun n’est plus juste."},
   tips:[{en:"To set the top without flipping, spoon hot fat over it or cover the pan for twenty seconds.",fr:"Pour saisir le dessus sans retourner, arrosez de gras chaud ou couvrez vingt secondes."},
         {en:"Crack it into a cup first. Dropped straight from the shell into hot fat it spreads before it sets.",fr:"Cassez-le d’abord dans un bol. Lâché de sa coquille dans le gras brûlant, il s’étale avant de prendre."}],
   pairs:["olive-oil","beurre-de-baratte","black-pepper","paprika","sage","tomato","chili","flour-t65"]},

  {id:"mayonnaise", art:"emulsion", name:{en:"Mayonnaise",fr:"Mayonnaise"},
   variety:{en:"Everything at the same temperature",fr:"Tout à la même température"},
   technique:{en:"An emulsion held by lecithin in the yolk: oil forced into droplets small enough to stay suspended. Drop by drop at the start — the first spoonful decides whether it takes at all — then a thin steady stream once it has thickened.",
   fr:"Une émulsion tenue par la lécithine du jaune : l’huile forcée en gouttelettes assez fines pour rester en suspension. Goutte à goutte au début — la première cuillerée décide si elle prendra — puis en filet régulier une fois épaissie."},
   tips:[{en:"Cold yolk with room-temperature oil is the commonest cause of a split. Take the eggs out an hour before.",fr:"Un jaune froid avec une huile à température est la première cause de mayonnaise tranchée. Sortez les œufs une heure avant."},
         {en:"To rescue a split one, start again with a fresh yolk and whisk the broken mixture into it drop by drop.",fr:"Pour la rattraper, repartez d’un jaune frais et incorporez-y la mayonnaise tranchée goutte à goutte."}],
   pairs:["mustard","lemon","olive-oil","garlic","tarragon","capers","cornichon","saffron"]},

  {id:"anglaise", art:"custard", name:{en:"Custard",fr:"Crème anglaise"},
   variety:{en:"Sets 82–84 °C · scrambles past 85",fr:"Prend à 82–84 °C · tranche au-delà de 85"},
   technique:{en:"Yolk proteins coagulate in a window three degrees wide. Temper first — hot milk poured slowly onto the yolks while whisking, so nothing sets on contact — then back on the lowest heat, stirring in a figure of eight so nothing catches in the corner of the pan.",
   fr:"Les protéines du jaune coagulent dans une fenêtre de trois degrés. Tempérez d’abord — lait chaud versé lentement sur les jaunes en fouettant, pour que rien ne prenne au contact — puis retour sur le feu le plus doux, en remuant en huit pour que rien n’accroche dans l’angle."},
   tips:[{en:"The nappe test: it coats the spoon and a line drawn with your finger holds its edges. That moment passes quickly.",fr:"Le test de la nappe : elle nappe la cuillère et un trait tracé au doigt garde ses bords nets. Cet instant passe vite."},
         {en:"If it does catch, a blender rescues it more often than you would think.",fr:"Si elle tranche, un coup de mixeur la rattrape plus souvent qu’on ne croit."}],
   pairs:["vanilla","cream","sugar","coffee","dark-chocolate","orange","cinnamon","tonka"]},

  {id:"meringue", name:{en:"Meringue",fr:"Meringue"},
   variety:{en:"French raw · Swiss warmed · Italian syrup",fr:"Française crue · suisse chauffée · italienne au sirop"},
   technique:{en:"Whites whipped into a protein foam that sugar then stabilises. Three versions in ascending order of stability: French beats raw sugar in, Swiss warms whites and sugar over water first, Italian pours in boiling syrup and is near-indestructible.",
   fr:"Des blancs montés en mousse protéique que le sucre vient stabiliser. Trois versions par stabilité croissante : la française incorpore le sucre cru, la suisse chauffe blancs et sucre au bain-marie, l’italienne verse un sirop bouillant et devient presque indestructible."},
   tips:[{en:"Any trace of fat kills it — a speck of yolk, a greasy bowl. Wipe the bowl with vinegar if unsure.",fr:"La moindre trace de gras la tue — un éclat de jaune, un cul-de-poule mal essuyé. Passez le bol au vinaigre dans le doute."},
         {en:"Add the sugar only once the whites hold soft peaks. Too early and they never gain volume.",fr:"N’ajoutez le sucre qu’une fois les blancs en bec souple. Trop tôt, ils ne prennent jamais de volume."}],
   pairs:["sugar","lemon","raspberry","vanilla","almond","pistachio","strawberry","passion-fruit"]}

]},

{id:"onion", branches:[
  {id:"cru", art:"raw", name:{en:"Raw",fr:"Cru"},
   variety:{en:"Red or sweet — never a storage onion",fr:"Rouge ou doux — jamais un oignon de garde"},
   technique:{en:"Raw onion is a different ingredient from cooked, not a lesser version of it. The bite is a sulphur compound made on contact with air the moment cells rupture, so a coarse chop is milder than a fine one. Ten minutes in cold water draws most of it out.",
   fr:"L’oignon cru est un autre ingrédient que le cuit, non une version inférieure. Le mordant est un composé soufré fabriqué au contact de l’air dès que les cellules se rompent : un hachis grossier est donc plus doux qu’un hachis fin. Dix minutes à l’eau froide en ôtent l’essentiel."},
   tips:[{en:"Slice with the grain, pole to pole, rather than across. Fewer cells burst and it stays sweeter.",fr:"Émincez dans le sens des fibres, d’un pôle à l’autre, plutôt qu’en travers. Moins de cellules éclatent et il reste plus doux."},
         {en:"A brief soak in vinegar turns red onion bright pink and takes the aggression out at the same time.",fr:"Un court passage au vinaigre rosit vivement l’oignon rouge et lui ôte son agressivité au passage."}],
   pairs:["lime","cilantro","tomato","chili","olive-oil","cucumber","feta","black-pepper"]},

  {id:"sue", art:"sweated", name:{en:"Sweated",fr:"Suée"},
   variety:{en:"Low heat, no colour, with salt",fr:"Feu doux, sans coloration, avec du sel"},
   technique:{en:"The foundation of most of European cooking and the step people rush. Gentle heat with a pinch of salt draws water out and softens the onion without browning it — you want translucent and sweet, with no colour at all, which takes ten to fifteen minutes and cannot be hurried.",
   fr:"Le fondement d’une grande part de la cuisine européenne, et l’étape que l’on presse. Une chaleur douce avec une pincée de sel tire l’eau et attendrit sans colorer — on cherche translucide et sucré, sans aucune coloration, ce qui prend dix à quinze minutes et ne se bouscule pas."},
   tips:[{en:"Salt at the start here, unusually. It pulls water out and speeds the softening.",fr:"Salez dès le début, exceptionnellement. Cela tire l’eau et accélère le fondant."},
         {en:"A lid traps steam and keeps colour away if your pan runs hot.",fr:"Un couvercle retient la vapeur et empêche la coloration si votre poêle chauffe fort."}],
   pairs:["beurre-de-baratte","carrot","celery","bay-leaf","thyme","garlic","olive-oil","white-wine-vinegar"]},

  {id:"caramelisees", art:"caramel", name:{en:"Caramelised",fr:"Caramélisées"},
   variety:{en:"Forty minutes minimum. Truly.",fr:"Quarante minutes minimum. Vraiment."},
   technique:{en:"Not a browner version of sweating — a different chemical event. The onion's own sugars break down and brown over a long slow heat, and no recipe promising this in ten minutes is describing it. What you get in ten minutes is scorched onion that tastes bitter, not sweet.",
   fr:"Non pas une version colorée de la suée — un autre événement chimique. Les sucres propres de l’oignon se décomposent et brunissent sur une chaleur longue et douce, et aucune recette promettant cela en dix minutes ne décrit ce plat. En dix minutes on obtient un oignon brûlé, amer et non sucré."},
   tips:[{en:"Deglaze with a splash of water whenever the base darkens. That fond is the flavour and it will burn if left.",fr:"Déglacez d’un trait d’eau dès que le fond fonce. Ce fond est le goût, et il brûlera si on le laisse."},
         {en:"This is the branch that changes what onion pairs with — sweet now, so it meets beef, wine and hard cheese.",fr:"C’est la branche qui change les accords de l’oignon — sucré désormais, il rencontre le bœuf, le vin et les fromages de garde."}],
   pairs:["thyme","beef","comte","red-wine-vinegar","beaufort","flour-t65","beurre-de-baratte","black-pepper"]},

  {id:"confites", art:"confit", name:{en:"Confit",fr:"Confites"},
   variety:{en:"Submerged in fat, barely trembling",fr:"Immergées dans le gras, à peine frémissantes"},
   technique:{en:"Whole small onions or thick wedges held under fat at low heat until they collapse without colouring. Where caramelising concentrates by drying, confit keeps everything in — the result is silkier, milder and holds its shape.",
   fr:"Petits oignons entiers ou gros quartiers tenus sous le gras à feu doux jusqu’à ce qu’ils s’affaissent sans colorer. Là où la caramélisation concentre en asséchant, le confit garde tout — le résultat est plus soyeux, plus doux, et tient sa forme."},
   tips:[{en:"They keep for weeks under their own fat in the fridge and improve for the first few days.",fr:"Ils se gardent des semaines sous leur graisse au réfrigérateur et s’améliorent les premiers jours."},
         {en:"A strip of orange peel and a bay leaf in the fat costs nothing and changes everything.",fr:"Un zeste d’orange et une feuille de laurier dans le gras ne coûtent rien et changent tout."}],
   pairs:["duck-fat","thyme","bay-leaf","garlic","black-pepper","lard","rosemary","sherry-vinegar"]},

  {id:"rotis", art:"roasted", name:{en:"Roasted whole",fr:"Rôtis entiers"},
   variety:{en:"Skin on, halved, cut side down",fr:"En chemise, coupés en deux, face contre la plaque"},
   technique:{en:"Left in their skins and roasted hard, the layers steam inside their own jacket while the cut face caramelises against the tray. The skin is doing the work — peel first and you get a dry, browned onion instead of a soft one with a charred face.",
   fr:"Laissés en chemise et rôtis fort, les couches cuisent à la vapeur dans leur propre enveloppe pendant que la face coupée caramélise contre la plaque. C’est la peau qui travaille — épluchez d’abord et vous obtenez un oignon sec et bruni plutôt qu’un oignon fondant à face grillée."},
   tips:[{en:"Cut side down and do not move them. The whole point is one deeply caramelised face.",fr:"Face coupée dessous et n’y touchez plus. Tout l’intérêt est cette face profondément caramélisée."},
         {en:"Squeeze the flesh out of the skins afterwards — it makes an instant purée.",fr:"Pressez ensuite la chair hors des peaux — cela fait une purée instantanée."}],
   pairs:["olive-oil","thyme","balsamic","rosemary","black-pepper","garlic","sage","honey"]},

  {id:"frits", art:"fried", name:{en:"Crisp-fried",fr:"Frits"},
   variety:{en:"Sliced paper thin, floured, hot oil",fr:"Émincés très fin, farinés, huile chaude"},
   technique:{en:"Thin rings tossed in seasoned flour and fried until the moisture is gone. Crispness is dryness — anything still holding water goes soft within minutes, which is why they must drain on a rack rather than paper, and be salted while still hot.",
   fr:"Des anneaux fins roulés dans une farine assaisonnée et frits jusqu’à disparition de l’humidité. Le croustillant, c’est la sécheresse — tout ce qui retient de l’eau ramollit en quelques minutes, d’où l’égouttage sur grille plutôt que sur papier, et le salage à chaud."},
   tips:[{en:"Fry in small batches. A crowded pan drops the oil temperature and they stew rather than crisp.",fr:"Frire en petites quantités. Une friture chargée fait chuter la température et ils s’étuvent au lieu de croustiller."},
         {en:"They are a garnish, not a dish — a texture against something soft.",fr:"C’est une garniture, non un plat — une texture contre quelque chose de fondant."}],
   pairs:["flour-t55","paprika","salt","black-pepper","peanut-oil","cumin","chili","yogurt"]},

  {id:"marines", art:"pickled", name:{en:"Pickled",fr:"Marinés"},
   variety:{en:"Thirty minutes is enough",fr:"Trente minutes suffisent"},
   technique:{en:"Thin slices in vinegar with a little sugar and salt. This is the fastest useful pickle there is — half an hour gives you acidity, crunch and, with red onion, a startling pink from the anthocyanins reacting to the acid.",
   fr:"Des lamelles fines dans du vinaigre avec un peu de sucre et de sel. C’est le pickle utile le plus rapide qui soit — une demi-heure donne acidité, croquant et, avec de l’oignon rouge, un rose saisissant dû aux anthocyanes réagissant à l’acide."},
   tips:[{en:"Pour the vinegar over warm and it works in fifteen minutes instead of thirty.",fr:"Versez le vinaigre tiède et cela agit en quinze minutes au lieu de trente."},
         {en:"Keep the pink liquid. It dresses a salad on its own.",fr:"Gardez le liquide rose. Il assaisonne une salade à lui seul."}],
   pairs:["red-wine-vinegar","sugar","salt","bay-leaf","black-pepper","chili","cider-vinegar","cilantro"]}
]},

{id:"butter", branches:[
  {id:"pommade", art:"whipped", name:{en:"Creamed",fr:"En pommade"},
   variety:{en:"Soft but not melted — around 18 °C",fr:"Souple sans être fondu — environ 18 °C"},
   technique:{en:"Beaten until pale and aerated, which is a mechanical job, not a flavour one: you are forcing air into the fat so it can hold bubbles a batter will later set around. Melted butter cannot do this at all — once the crystal structure is gone, it will not trap air again.",
   fr:"Battu jusqu’à blanchir et foisonner, ce qui est un travail mécanique et non gustatif : on force de l’air dans la matière grasse pour qu’elle retienne des bulles que la pâte fixera ensuite. Le beurre fondu en est incapable — la structure cristalline perdue, il ne piège plus l’air."},
   tips:[{en:"Too cold and it stays in lumps; too warm and it greases instead of aerating. The window is narrow.",fr:"Trop froid il reste en morceaux ; trop chaud il graisse au lieu de foisonner. La fenêtre est étroite."},
         {en:"Pale and doubled in volume is the finish line, and it takes longer than you expect.",fr:"Blanchi et doublé de volume est l’arrivée, et cela prend plus longtemps qu’on ne croit."}],
   pairs:["sugar","flour-t45","egg","vanilla","lemon","almond","cinnamon","salt"]},

  {id:"clarifie", art:"clarified", name:{en:"Clarified",fr:"Clarifié"},
   variety:{en:"Burns at 250 °C instead of 150 °C",fr:"Brûle à 250 °C au lieu de 150 °C"},
   technique:{en:"Butter burns because of its milk solids, not its fat. Melt it gently, skim the foam, pour off the gold and leave the milky sediment behind — the same fat now takes a hundred degrees more heat. Do not let it colour; that is the line between clarified butter and ghee.",
   fr:"Le beurre brûle à cause de ses solides du lait, non de sa matière grasse. Fondez doucement, écumez, versez l’or et laissez le dépôt laiteux — la même graisse encaisse cent degrés de plus. Ne le laissez pas colorer ; c’est la frontière entre beurre clarifié et ghee."},
   tips:[{en:"Keep a jar beside the stove. It is the correct fat for searing anything you want to taste of butter.",fr:"Gardez-en un pot près du feu. C’est le gras juste pour saisir tout ce qui doit garder un goût de beurre."},
         {en:"It keeps for months where ordinary butter would turn — the water and solids are what spoil.",fr:"Il se garde des mois là où le beurre ordinaire tournerait — ce sont l’eau et les solides qui s’altèrent."}],
   pairs:["scallop","dover-sole","shallot","lemon","thyme","garlic","parsley","turbot"]},

  {id:"noisette", name:{en:"Brown butter",fr:"Beurre noisette"},
   variety:{en:"Fifteen seconds from perfect to burnt",fr:"Quinze secondes entre parfait et brûlé"},
   technique:{en:"The opposite decision to clarifying: here the milk solids are the point. Keep melting past the foaming stage and they toast on the base, turning the butter amber and giving it the hazelnut smell it is named for. It goes from noisette to noir to ruined very fast.",
   fr:"La décision inverse du clarifié : ici les solides du lait sont le sujet. Poursuivez la fonte au-delà du moussage et ils grillent au fond, ambrant le beurre et lui donnant l’odeur de noisette qui le nomme. Il passe de noisette à noir puis au perdu très vite."},
   tips:[{en:"Use a pale pan. In a black one you cannot see the colour turn, which is the only signal you get.",fr:"Utilisez une casserole claire. Dans une noire on ne voit pas la couleur virer, et c’est le seul signal."},
         {en:"Off the heat and into a cold bowl the moment it smells of nuts. The pan alone will take it too far.",fr:"Hors du feu et dans un bol froid dès l’odeur de noisette. La casserole seule le pousserait trop loin."}],
   pairs:["dover-sole","almond","lemon","capers","sage","hazelnut","skate","parsley"]},

  {id:"blanc", art:"emulsion", name:{en:"Beurre blanc",fr:"Beurre blanc"},
   variety:{en:"Cold cubes, never boiling",fr:"Cubes froids, jamais à ébullition"},
   technique:{en:"Shallots reduced in white wine and vinegar almost to dryness, then cold butter whisked in cube by cube off a low heat. It is an emulsion, so it lives in a temperature band: too cool and it seizes, too hot and the fat separates out and there is no coming back.",
   fr:"Des échalotes réduites au vin blanc et au vinaigre presque à sec, puis du beurre froid monté cube par cube sur un feu très doux. C’est une émulsion : elle vit dans une plage de température — trop froide elle fige, trop chaude la matière grasse se sépare et rien ne la rattrape."},
   tips:[{en:"A spoonful of cream in the reduction makes it far more forgiving. Purists object; it works.",fr:"Une cuillerée de crème dans la réduction le rend bien plus tolérant. Les puristes s’en offusquent ; cela fonctionne."},
         {en:"It will not wait. Make it last and keep it barely warm in a bain-marie.",fr:"Il n’attend pas. Faites-le en dernier et gardez-le à peine tiède au bain-marie."}],
   pairs:["shallot","white-wine-vinegar","cream","turbot","chives","black-pepper","lemon","tarragon"]},

  {id:"monte", art:"sauce", name:{en:"Beurre monté",fr:"Beurre monté"},
   variety:{en:"Butter emulsified into water",fr:"Beurre émulsionné dans l’eau"},
   technique:{en:"A spoonful of water brought to a simmer, then cold butter whisked in until it becomes a glossy, creamy sauce rather than melted fat. Restaurant kitchens hold vegetables and fish in it — it seasons, glazes and keeps things warm without cooking them further.",
   fr:"Une cuillerée d’eau portée à frémissement, puis du beurre froid monté au fouet jusqu’à obtenir une sauce brillante et crémeuse plutôt que du gras fondu. Les cuisines de restaurant y tiennent légumes et poissons — cela assaisonne, glace et maintient au chaud sans cuire davantage."},
   tips:[{en:"The ratio is roughly one part water to five of butter. More water and it will not hold.",fr:"Le rapport est d’environ une part d’eau pour cinq de beurre. Plus d’eau et cela ne tient pas."},
         {en:"Never let it boil. The emulsion breaks and you are left with butter and water again.",fr:"Ne le laissez jamais bouillir. L’émulsion casse et il ne reste que du beurre et de l’eau."}],
   pairs:["asparagus","scallop","lemon","chives","tarragon","morel","shallot","cream"]},

  {id:"compose", art:"chopped", name:{en:"Compound",fr:"Composé"},
   variety:{en:"Rolled, chilled, sliced",fr:"Roulé, refroidi, tranché"},
   technique:{en:"Softened butter worked with something strong — herbs, anchovy, garlic, citrus zest — then rolled in paper and chilled hard. A disc melting over hot meat or fish is a sauce that needed no pan, and it keeps for weeks in the freezer.",
   fr:"Du beurre pommade travaillé avec quelque chose de puissant — herbes, anchois, ail, zestes — puis roulé en papier et bien refroidi. Une rondelle fondant sur une viande ou un poisson chaud est une sauce qui n’a demandé aucune casserole, et elle se garde des semaines au congélateur."},
   tips:[{en:"Season it harder than feels right. It is being diluted across a whole plate.",fr:"Assaisonnez plus fort qu’il ne semble juste. Il sera dilué sur toute une assiette."},
         {en:"Anchovy dissolves completely and nobody identifies it — they just say the steak tastes better.",fr:"L’anchois s’y dissout entièrement et personne ne l’identifie — on dit simplement que le steak est meilleur."}],
   pairs:["parsley","garlic","tarragon","anchovy","lemon","espelette","chives","shallot"]}
]},

{id:"tomato", branches:[
  {id:"cru", art:"raw", name:{en:"Raw",fr:"Crue"},
   variety:{en:"Room temperature, never the fridge",fr:"À température, jamais au réfrigérateur"},
   technique:{en:"Cold destroys tomato aroma and the damage is permanent — below about 12 °C the compounds that make it smell of tomato stop being produced and do not return on warming. Salt the cut slices ten minutes ahead; the water it draws out concentrates what is left.",
   fr:"Le froid détruit l’arôme de la tomate, et le dommage est définitif — sous 12 °C environ, les composés qui lui donnent son odeur cessent d’être produits et ne reviennent pas au réchauffage. Salez les tranches dix minutes avant ; l’eau qu’il tire concentre le reste."},
   tips:[{en:"This is the branch basil belongs to. Torn, raw, at the last second — cooked it turns bitter.",fr:"C’est la branche du basilic. Déchiré, cru, à la dernière seconde — cuit il devient amer."},
         {en:"Salt the cut face, not the bowl. It draws water where you want it drawn.",fr:"Salez la face coupée, pas le saladier. Cela tire l’eau là où on le souhaite."}],
   pairs:["basil","olive-oil","salt","mozzarella","black-pepper","cucumber","oregano","burrata"]},

  {id:"confite", art:"confit", name:{en:"Confit",fr:"Confite"},
   variety:{en:"Two hours at 90 °C",fr:"Deux heures à 90 °C"},
   technique:{en:"Halved, seeded, laid cut side up with oil, thyme and a pinch of sugar, and left in a very low oven until they collapse and intensify. Nothing browns. What you are doing is removing water slowly enough that the sugars concentrate rather than caramelise.",
   fr:"Coupées en deux, épépinées, posées face coupée en l’air avec huile, thym et une pincée de sucre, puis oubliées dans un four très doux jusqu’à ce qu’elles s’affaissent et se concentrent. Rien ne colore. On retire de l’eau assez lentement pour que les sucres se concentrent sans caraméliser."},
   tips:[{en:"Peel them first — a minute in boiling water and the skins slip off. Skins toughen over two hours.",fr:"Mondez-les d’abord — une minute à l’eau bouillante et la peau glisse. Les peaux durcissent en deux heures."},
         {en:"They keep a week under oil and make anything they touch taste like more work than it was.",fr:"Elles se gardent une semaine sous l’huile et donnent à tout ce qu’elles touchent l’air d’un travail plus long qu’il ne fut."}],
   pairs:["olive-oil","thyme","garlic","sugar","basil","oregano","burrata","anchovy"]},

  {id:"rotie", art:"roasted", name:{en:"Roasted",fr:"Rôtie"},
   variety:{en:"Hot and fast — colour is the point",fr:"Chaud et rapide — la couleur est le but"},
   technique:{en:"The opposite of confit: high heat, short time, and browning very much wanted. The skins blister and split, the edges catch, and you get a smoky bitterness that confit deliberately avoids. Two techniques, two entirely different tomatoes.",
   fr:"L’inverse du confit : forte chaleur, temps court, et coloration franchement recherchée. Les peaux cloquent et se fendent, les bords accrochent, et l’on obtient une amertume fumée que le confit évite délibérément. Deux techniques, deux tomates entièrement différentes."},
   tips:[{en:"Do not crowd the tray or they steam in their own liquid and never colour.",fr:"Ne chargez pas la plaque, sinon elles s’étuvent dans leur jus et ne colorent jamais."},
         {en:"Scrape every scorched bit off the tray into the dish. That is where the flavour went.",fr:"Raclez tout ce qui a accroché sur la plaque dans le plat. C’est là qu’est parti le goût."}],
   pairs:["olive-oil","garlic","thyme","rosemary","black-pepper","feta","oregano","chili"]},

  {id:"sauce", name:{en:"Sauce",fr:"Sauce"},
   variety:{en:"Long and slow, lid off",fr:"Longue et douce, sans couvercle"},
   technique:{en:"A sauce is a reduction — you are removing water, and a lid stops that happening. Long cooking breaks the fruit down and mellows the acidity, but it also destroys the fresh aroma entirely, which is why a good long-cooked sauce and a good raw tomato taste nothing alike.",
   fr:"Une sauce est une réduction — on retire de l’eau, et un couvercle l’en empêche. Une cuisson longue défait le fruit et adoucit l’acidité, mais elle détruit aussi tout l’arôme frais, d’où deux goûts sans rapport entre une bonne sauce longue et une bonne tomate crue."},
   tips:[{en:"A grated carrot balances acidity better than sugar and nobody tastes it.",fr:"Une carotte râpée équilibre l’acidité mieux que le sucre, et personne ne la détecte."},
         {en:"Basil goes in off the heat at the very end, never at the start.",fr:"Le basilic entre hors du feu tout à la fin, jamais au début."}],
   pairs:["garlic","basil","olive-oil","onion","carrot","oregano","bay-leaf","parmesan"]},

  {id:"sechee", art:"dried", name:{en:"Dried",fr:"Séchée"},
   variety:{en:"Water out, umami up",fr:"L’eau part, l’umami monte"},
   technique:{en:"Drying concentrates glutamates, which is why a dried tomato tastes savoury in a way a fresh one never does — closer to anchovy or parmesan than to fruit. Salt before drying draws water out faster and seasons through rather than on the surface.",
   fr:"Le séchage concentre les glutamates, d’où une tomate séchée au goût savoureux que la fraîche n’a jamais — plus proche de l’anchois ou du parmesan que du fruit. Saler avant séchage tire l’eau plus vite et assaisonne à cœur plutôt qu’en surface."},
   tips:[{en:"Rehydrate in warm water, not oil. Then keep the soaking water — it is concentrated tomato.",fr:"Réhydratez à l’eau tiède, non dans l’huile. Puis gardez l’eau de trempage — c’est de la tomate concentrée."},
         {en:"Use it where you would use an anchovy: a savoury undertone nobody can name.",fr:"Employez-la là où vous mettriez un anchois : un fond savoureux que personne ne sait nommer."}],
   pairs:["olive-oil","capers","oregano","garlic","pine-nut","anchovy","basil","chili"]},

  {id:"eau", art:"clarified", name:{en:"Tomato water",fr:"Eau de tomate"},
   variety:{en:"Clear, and it tastes more of tomato than tomato",fr:"Limpide, et plus tomate que la tomate"},
   technique:{en:"Blend ripe tomatoes with salt and hang the pulp in muslin overnight. What drips through is colourless and carries the aroma almost purely, without the acidity of the flesh or the sweetness of the pulp. It is the clearest demonstration that colour and flavour are unrelated.",
   fr:"Mixez des tomates mûres avec du sel et suspendez la pulpe dans une étamine une nuit. Ce qui s’égoutte est incolore et porte l’arôme presque pur, sans l’acidité de la chair ni le sucré de la pulpe. C’est la démonstration la plus nette que couleur et goût n’ont rien à voir."},
   tips:[{en:"Never squeeze the cloth. Pressure pushes pulp through and the liquid clouds instantly.",fr:"Ne pressez jamais l’étamine. La pression fait passer la pulpe et le liquide se trouble aussitôt."},
         {en:"Serve it very cold as a clear soup, or use it instead of stock under a white fish.",fr:"Servez-la très froide en soupe claire, ou employez-la à la place d’un fumet sous un poisson blanc."}],
   pairs:["basil","olive-oil","salt","scallop","cucumber","black-pepper","shrimp","lemon"]}
]},

{id:"chicken", branches:[
  {id:"roti", art:"roasted", name:{en:"Roasted",fr:"Rôti"},
   variety:{en:"Dry skin, hot start, long rest",fr:"Peau sèche, départ chaud, long repos"},
   technique:{en:"Two problems fight each other: the breast is done at 65 °C and the thigh needs 75 °C. Everything about roasting a whole bird is managing that gap — start breast-down so the legs face the heat, or salt it uncovered in the fridge overnight so the skin dries and browns before the breast overcooks.",
   fr:"Deux problèmes s’opposent : le blanc est cuit à 65 °C et la cuisse en réclame 75. Tout l’art du rôtissage entier consiste à gérer cet écart — démarrez blanc en dessous pour exposer les cuisses à la chaleur, ou salez-le à découvert au réfrigérateur une nuit pour que la peau sèche et colore avant que le blanc ne surcuise."},
   tips:[{en:"Rest it as long as you roasted it, at least twenty minutes. Carving early loses the juice onto the board.",fr:"Reposez-le aussi longtemps que vous l’avez rôti, vingt minutes au moins. Trancher tôt, c’est perdre le jus sur la planche."},
         {en:"Nothing inside the cavity cooks. Aromatics there perfume the steam, not the meat — put them under the skin instead.",fr:"Rien ne cuit dans la cavité. Les aromates y parfument la vapeur, non la chair — glissez-les plutôt sous la peau."}],
   pairs:["thyme","lemon","garlic","beurre-de-baratte","bay-leaf","black-pepper","tarragon","onion"]},

  {id:"poche", art:"poached", name:{en:"Poached",fr:"Poché"},
   variety:{en:"Never above a tremble",fr:"Jamais au-delà du frémissement"},
   technique:{en:"Barely moving water, and the bird is often best left to cool in its own broth rather than lifted out hot. Boiling tightens muscle fibres and squeezes water out, which is the whole reason poached chicken has a reputation for being dry — the method is not at fault, the temperature is.",
   fr:"Une eau à peine mobile, et la volaille gagne souvent à refroidir dans son bouillon plutôt qu’à en sortir chaude. L’ébullition resserre les fibres et en chasse l’eau, ce qui explique la réputation de sécheresse du poulet poché — la méthode n’est pas en cause, la température l’est."},
   tips:[{en:"You get two dishes: the meat and the broth. Neither is a by-product.",fr:"On obtient deux plats : la chair et le bouillon. Aucun n’est un sous-produit."},
         {en:"Cooling it in the liquid reabsorbs juice. Lifting it out hot loses it.",fr:"Le refroidissement dans le liquide fait réabsorber le jus. Le sortir chaud le perd."}],
   pairs:["leek","carrot","celery","bay-leaf","black-pepper","tarragon","cream","parsley"]},

  {id:"confit", name:{en:"Confit",fr:"Confit"},
   variety:{en:"Salted overnight, then fat at 85 °C",fr:"Salé une nuit, puis gras à 85 °C"},
   technique:{en:"Legs only — breast has neither the fat nor the connective tissue for it. Salted for a day, rinsed, then submerged in fat well below frying temperature for hours. The salt draws water out and seasons through; the fat excludes air, which is why it keeps for months.",
   fr:"Les cuisses seulement — le blanc n’a ni le gras ni le collagène pour cela. Salées un jour, rincées, puis immergées dans un gras bien en deçà de la friture, des heures durant. Le sel tire l’eau et assaisonne à cœur ; le gras exclut l’air, d’où une conservation de plusieurs mois."},
   tips:[{en:"Crisp the skin hard in a dry pan before serving. Confit alone gives you tenderness, not texture.",fr:"Croustillez la peau à sec avant de servir. Le confit seul donne le fondant, non la texture."},
         {en:"Rinse the salt off properly or the result is inedible. This is the step people skip.",fr:"Rincez bien le sel ou le résultat sera immangeable. C’est l’étape que l’on saute."}],
   pairs:["duck-fat","thyme","garlic","bay-leaf","black-pepper","lard","rosemary","salt"]},

  {id:"frit", art:"fried", name:{en:"Fried",fr:"Frit"},
   variety:{en:"Buttermilk brine, then a dry crust",fr:"Saumure au lait ribot, puis croûte sèche"},
   technique:{en:"An acidic brine — buttermilk is the classic — tenderises and seasons through over several hours. The crust is a separate problem: it needs to be dry going into the oil, so let the coated pieces sit fifteen minutes until the flour turns pasty and clings.",
   fr:"Une saumure acide — le lait ribot est le classique — attendrit et assaisonne à cœur en quelques heures. La croûte est un autre problème : elle doit être sèche à l’entrée dans l’huile, alors laissez les morceaux panés reposer quinze minutes jusqu’à ce que la farine devienne pâteuse et adhère."},
   tips:[{en:"Oil at 165–170 °C. Hotter and the crust colours before the meat is cooked.",fr:"Huile à 165–170 °C. Plus chaud et la croûte colore avant que la chair ne soit cuite."},
         {en:"Drain on a rack, never on paper. Paper traps steam and softens the underside.",fr:"Égouttez sur grille, jamais sur papier. Le papier retient la vapeur et ramollit le dessous."}],
   pairs:["buttermilk","flour-t55","paprika","black-pepper","chili","peanut-oil","salt","garlic"]},

  {id:"braise", art:"braised", name:{en:"Braised",fr:"Braisé"},
   variety:{en:"Brown first, then barely cover",fr:"Colorer d’abord, puis mouiller à hauteur"},
   technique:{en:"Colour the pieces hard before any liquid goes near them — that browning is most of the finished flavour and it cannot happen once the pan is wet. Then liquid only part way up, not submerging: what is above the line roasts while what is below stews.",
   fr:"Colorez fortement les morceaux avant tout liquide — cette coloration fait l’essentiel du goût final et ne peut plus advenir dans une casserole mouillée. Puis du liquide à mi-hauteur seulement, sans immerger : ce qui dépasse rôtit pendant que le reste mijote."},
   tips:[{en:"Legs and thighs only. Breast in a braise goes stringy long before the sauce is ready.",fr:"Cuisses et hauts de cuisse seulement. Le blanc en braisé file bien avant que la sauce ne soit prête."},
         {en:"It is better the next day, and that is not folklore — collagen keeps setting as it cools.",fr:"C’est meilleur le lendemain, et ce n’est pas du folklore — le collagène continue de prendre en refroidissant."}],
   pairs:["white-wine-vinegar","mushroom","shallot","thyme","cream","bay-leaf","carrot","lard"]},

  {id:"grille", art:"grilled", name:{en:"Grilled",fr:"Grillé"},
   variety:{en:"Spatchcocked, or it will not cook evenly",fr:"En crapaudine, sinon la cuisson sera inégale"},
   technique:{en:"Flatten it — remove the backbone and press it out — or the legs and breast will never finish together over direct heat. Two zones on the grill: sear over the hot side, then move it to the cool side with the lid down to finish through.",
   fr:"Aplatissez-le — ôtez l’échine et pressez — sinon cuisses et blanc ne finiront jamais ensemble sur une chaleur directe. Deux zones : saisir sur le côté chaud, puis déplacer sur le côté doux, couvercle fermé, pour finir à cœur."},
   tips:[{en:"Sugary marinades burn. Brush them on in the last few minutes, not at the start.",fr:"Les marinades sucrées brûlent. Badigeonnez dans les dernières minutes, non au départ."},
         {en:"Skin side down first and leave it. Moving it early is what tears the skin off.",fr:"Peau dessous d’abord, et n’y touchez pas. C’est le déplacer trop tôt qui arrache la peau."}],
   pairs:["harissa","lemon","olive-oil","garlic","paprika","oregano","chili","yogurt"]},

  {id:"bouillon", art:"stock", name:{en:"Stock",fr:"Bouillon"},
   variety:{en:"Never boils. Ever.",fr:"Ne bout jamais. Jamais."},
   technique:{en:"Cold water, brought up slowly, and held at a bare tremble for hours while you skim. A boiling stock emulsifies its fat and its scum back into the liquid, which is exactly what makes a stock cloudy — the difference between clear and murky is entirely temperature.",
   fr:"Eau froide, montée lentement, tenue à peine frémissante des heures en écumant. Un bouillon qui bout réémulsionne son gras et ses impuretés dans le liquide, ce qui le trouble — la différence entre limpide et trouble tient entièrement à la température."},
   tips:[{en:"Roast the bones first for a brown stock, use them raw for a white one. Two different products.",fr:"Rôtissez les os pour un fond brun, employez-les crus pour un blanc. Deux produits différents."},
         {en:"Salt it at the end, never at the start. It will reduce by half and the salt will not.",fr:"Salez à la fin, jamais au début. Il réduira de moitié, le sel non."}],
   pairs:["leek","carrot","celery","bay-leaf","thyme","black-pepper","onion","parsley"]}
]},

{id:"garlic", branches:[
  {id:"cru", art:"raw", name:{en:"Raw",fr:"Cru"},
   variety:{en:"Crushed is fiercer than sliced",fr:"Écrasé est plus féroce que tranché"},
   technique:{en:"Allicin does not exist in an intact clove — it is manufactured the instant the cells are broken, by an enzyme meeting a compound it is normally kept apart from. So how you cut it is a seasoning decision: a whole clove is mild, sliced is moderate, crushed to a paste is fierce.",
   fr:"L’allicine n’existe pas dans une gousse intacte — elle se fabrique à l’instant où les cellules se rompent, une enzyme rencontrant un composé dont elle est normalement séparée. La découpe est donc un choix d’assaisonnement : gousse entière douce, tranchée moyenne, écrasée en pâte féroce."},
   tips:[{en:"Let crushed garlic stand ten minutes before it meets heat. The reaction needs time and heat stops it.",fr:"Laissez l’ail écrasé reposer dix minutes avant la chaleur. La réaction a besoin de temps, et la chaleur l’interrompt."},
         {en:"Crush it with salt to a paste — the salt is an abrasive and gives a smoothness a knife cannot.",fr:"Écrasez-le en pâte avec du sel — le sel fait abrasif et donne un lisse que le couteau n’atteint pas."}],
   pairs:["olive-oil","lemon","parsley","basil","anchovy","chili","tomato","salt"]},

  {id:"roti", art:"roasted", name:{en:"Roasted whole",fr:"Rôti en chemise"},
   variety:{en:"Head intact, an hour at 180 °C",fr:"Tête entière, une heure à 180 °C"},
   technique:{en:"The most complete transformation of any ingredient here. Heat destroys the allicin entirely and the sugars caramelise instead — what comes out is sweet, nutty and spreadable, with none of the raw bite. It is barely the same ingredient.",
   fr:"La transformation la plus complète de tous les ingrédients présentés. La chaleur détruit entièrement l’allicine et les sucres caramélisent à la place — il en sort une chair sucrée, de noisette, à tartiner, sans aucun mordant. Ce n’est presque plus le même ingrédient."},
   tips:[{en:"Cut the top off the head so the cloves are exposed, oil it, and wrap in foil for the first half.",fr:"Décalottez la tête pour exposer les gousses, huilez, et enveloppez de papier pour la première moitié."},
         {en:"Squeeze it into mashed potato, a vinaigrette, or onto bread. It needs nothing else.",fr:"Pressez-le dans une purée, une vinaigrette, ou sur du pain. Il ne demande rien d’autre."}],
   pairs:["olive-oil","thyme","rosemary","flour-t65","cream","potato","chicken","black-pepper"]},

  {id:"confit", name:{en:"Confit",fr:"Confit"},
   variety:{en:"Peeled cloves under oil at 90 °C",fr:"Gousses épluchées sous l’huile à 90 °C"},
   technique:{en:"Individual cloves held under oil, low and slow, until they are soft enough to crush with a spoon but still pale. Unlike roasting there is no browning, so the result is sweet and mellow rather than nutty — and the oil left behind is as useful as the garlic.",
   fr:"Des gousses individuelles tenues sous l’huile, doucement, jusqu’à s’écraser à la cuillère tout en restant pâles. Contrairement au rôtissage il n’y a pas de coloration : le résultat est doux et rond plutôt que noisette — et l’huile restante vaut autant que l’ail."},
   tips:[{en:"Keep it in the fridge and use it within a week — garlic under oil at room temperature is a genuine botulism risk.",fr:"Gardez-le au réfrigérateur et consommez-le dans la semaine — l’ail sous huile à température ambiante présente un vrai risque botulique."},
         {en:"The oil is the bonus. Use it for the vinaigrette that goes with whatever the garlic went into.",fr:"L’huile est le bonus. Employez-la pour la vinaigrette qui accompagnera le plat."}],
   pairs:["olive-oil","thyme","bay-leaf","rosemary","black-pepper","duck-fat","lamb","potato"]},

  {id:"sue", art:"sweated", name:{en:"Sweated",fr:"Sué"},
   variety:{en:"Thirty seconds, and never brown",fr:"Trente secondes, et jamais brun"},
   technique:{en:"The most-failed step in home cooking. Garlic burns in well under a minute and burnt garlic is acridly bitter — it cannot be rescued and it ruins whatever it is in. It goes into the pan after the onion, not with it, and it comes off the heat almost immediately.",
   fr:"L’étape la plus ratée de la cuisine domestique. L’ail brûle en moins d’une minute et l’ail brûlé est âcrement amer — irrattrapable, il gâche tout ce qui l’entoure. Il entre après l’oignon, non avec lui, et quitte le feu presque aussitôt."},
   tips:[{en:"If a recipe says to add onion and garlic together, add the garlic five minutes later anyway.",fr:"Si une recette dit d’ajouter oignon et ail ensemble, ajoutez l’ail cinq minutes plus tard quand même."},
         {en:"The moment it smells of garlic, it is done. Waiting for colour is waiting too long.",fr:"Dès que ça sent l’ail, c’est prêt. Attendre la couleur, c’est attendre trop."}],
   pairs:["olive-oil","onion","tomato","parsley","white-wine-vinegar","thyme","shallot","chili"]},

  {id:"frit", art:"fried", name:{en:"Crisp chips",fr:"Frit en chips"},
   variety:{en:"Paper-thin, cold oil start",fr:"Très fines, départ à froid"},
   technique:{en:"Wafer-thin slices started in cold oil and brought up slowly, which cooks the moisture out evenly instead of colouring the outside first. Lift them out while still barely golden — like nuts, they carry on darkening on the plate and bitter is one shade past perfect.",
   fr:"Des lamelles très fines démarrées à l’huile froide et montées lentement, ce qui évacue l’humidité régulièrement au lieu de colorer d’abord l’extérieur. Sortez-les à peine dorées — comme les fruits secs, elles continuent de foncer hors du feu, et l’amer est à une nuance du parfait."},
   tips:[{en:"Keep the oil. It is now garlic oil, and it is the better half of the exercise.",fr:"Gardez l’huile. C’est désormais une huile d’ail, et c’est la meilleure moitié de l’opération."},
         {en:"A mandoline, not a knife. Uneven slices mean some burn while others are still raw.",fr:"À la mandoline, non au couteau. Des tranches inégales font brûler les unes quand les autres sont crues."}],
   pairs:["chili","peanut-oil","salt","cilantro","rice","spring-onion","black-pepper","ginger"]},

  {id:"noir", art:"cured", name:{en:"Black garlic",fr:"Ail noir"},
   variety:{en:"Six weeks at 60 °C and high humidity",fr:"Six semaines à 60 °C et forte humidité"},
   technique:{en:"Not fermented, despite what every label says — there are no microbes involved. It is the Maillard reaction running for weeks at a temperature low enough not to cook: sugars and amino acids browning slowly until the cloves turn black, soft and sweet, tasting of balsamic and liquorice.",
   fr:"Non fermenté, quoi qu’en disent les étiquettes — aucun microbe n’intervient. C’est la réaction de Maillard qui court pendant des semaines à une température trop basse pour cuire : sucres et acides aminés brunissent lentement jusqu’à des gousses noires, molles et sucrées, au goût de balsamique et de réglisse."},
   tips:[{en:"There is no garlic pungency left at all. Treat it as a sweet-savoury condiment, not as garlic.",fr:"Il ne reste aucun piquant d’ail. Traitez-le en condiment sucré-salé, non comme de l’ail."},
         {en:"It is remarkable with beef and, genuinely, with dark chocolate.",fr:"Il est remarquable avec le bœuf et, sérieusement, avec le chocolat noir."}],
   pairs:["soy-sauce","beef","dark-chocolate","balsamic","mushroom","black-pepper","beurre-de-baratte","miso"]}
]},

{id:"cream", branches:[
  {id:"fouettee", art:"whipped", name:{en:"Whipped",fr:"Fouettée"},
   variety:{en:"30% fat minimum, and very cold",fr:"30 % MG minimum, et très froide"},
   technique:{en:"Whipping forces air in while the fat globules link into a network that holds the bubbles. Two things decide whether it works and neither is effort: fat content below about 30% will never hold, and warm cream melts the fat before it can build a structure.",
   fr:"Le fouettage force l’air pendant que les globules gras se lient en réseau qui retient les bulles. Deux facteurs décident, et aucun n’est l’effort : sous 30 % de matière grasse elle ne tiendra jamais, et une crème tiède fond avant de pouvoir se structurer."},
   tips:[{en:"Chill the bowl and the whisk too, not just the cream. Ten minutes in the freezer is enough.",fr:"Refroidissez aussi le bol et le fouet, pas seulement la crème. Dix minutes au congélateur suffisent."},
         {en:"Over-whipped cream is on its way to butter. Stop at the point it holds a soft peak and no further.",fr:"Une crème trop fouettée devient du beurre. Arrêtez au bec souple, pas au-delà."}],
   pairs:["sugar","vanilla","strawberry","dark-chocolate","coffee","raspberry","cinnamon","orange"]},

  {id:"reduite", art:"reduced", name:{en:"Reduced",fr:"Réduite"},
   variety:{en:"Fat protects it — thin cream splits",fr:"Le gras protège — une crème allégée tranche"},
   technique:{en:"Cream can be boiled hard where milk cannot, because its fat content stabilises the proteins. Reducing concentrates flavour and thickens without any flour or starch, which is why classic French sauces so often need no thickener at all — just time and a wide pan.",
   fr:"La crème supporte une forte ébullition là où le lait non, car sa matière grasse stabilise les protéines. La réduction concentre le goût et épaissit sans farine ni fécule, d’où tant de sauces classiques françaises qui n’ont besoin d’aucun liant — seulement de temps et d’une large casserole."},
   tips:[{en:"A wide pan reduces far faster than a tall one. Surface area is the whole variable.",fr:"Une casserole large réduit bien plus vite qu’une haute. La surface est la seule variable."},
         {en:"Add acid — lemon, wine — only at the end, and off the heat, or it will curdle.",fr:"N’ajoutez l’acide — citron, vin — qu’à la fin et hors du feu, sinon elle tranche."}],
   pairs:["shallot","white-wine-vinegar","morel","nutmeg","black-pepper","tarragon","mushroom","comte"]},

  {id:"fermentee", art:"cured", name:{en:"Soured",fr:"Fermentée"},
   variety:{en:"Cultures, 24 hours, room temperature",fr:"Ferments, 24 heures, à température"},
   technique:{en:"Lactic bacteria turn some of the lactose to acid, and that acidity does something useful: it stabilises the proteins so the cream can meet lemon, wine or tomato without splitting. Fresh cream in an acidic sauce curdles; soured cream does not.",
   fr:"Des bactéries lactiques transforment une part du lactose en acide, et cette acidité rend un vrai service : elle stabilise les protéines, si bien que la crème peut rencontrer citron, vin ou tomate sans trancher. Une crème fraîche non fermentée caille dans une sauce acide ; celle-ci non."},
   tips:[{en:"A spoonful of live yoghurt in warm cream, left overnight, makes a very passable version.",fr:"Une cuillerée de yaourt vivant dans une crème tiède, laissée une nuit, en donne une version très acceptable."},
         {en:"This is the cream for anything with lemon or wine in it. The choice is chemical, not a preference.",fr:"C’est la crème de tout ce qui contient citron ou vin. Le choix est chimique, non une préférence."}],
   pairs:["chives","lemon","dill","salmon","cucumber","black-pepper","shallot","potato"]},

  {id:"ganache", name:{en:"Ganache",fr:"Ganache"},
   variety:{en:"An emulsion, not a mixture",fr:"Une émulsion, non un mélange"},
   technique:{en:"Hot cream poured over chopped chocolate and left a minute before stirring — the waiting matters, because agitating it too early breaks the emulsion. Start stirring from the centre in small circles and work outwards; it will look split before it suddenly comes together and turns glossy.",
   fr:"De la crème chaude versée sur du chocolat haché et laissée une minute avant de remuer — l’attente compte, car agiter trop tôt casse l’émulsion. Remuez du centre en petits cercles vers l’extérieur ; elle semblera tranchée puis se rassemblera d’un coup et deviendra brillante."},
   tips:[{en:"If it splits, a spoonful of warm milk and hard whisking almost always brings it back.",fr:"Si elle tranche, une cuillerée de lait tiède et un fouettage énergique la rattrapent presque toujours."},
         {en:"Equal weights for a soft ganache, twice the chocolate for one you can roll into truffles.",fr:"À poids égaux pour une ganache souple, deux fois plus de chocolat pour une ganache à rouler en truffes."}],
   pairs:["dark-chocolate","beurre-de-baratte","orange","coffee","vanilla","raspberry","cardamom","honey"]},

  {id:"glacee", art:"custard", name:{en:"Ice cream base",fr:"Base glacée"},
   variety:{en:"Fat and sugar control the texture",fr:"Gras et sucre gouvernent la texture"},
   technique:{en:"Everything about ice cream is keeping ice crystals small. Fat coats the crystals and stops them joining; sugar lowers the freezing point so less water freezes at all. Cut either one and you get something hard and grainy — this is why low-fat ice cream is a texture problem, not a flavour one.",
   fr:"Tout, en glace, consiste à garder de petits cristaux. Le gras enrobe les cristaux et les empêche de fusionner ; le sucre abaisse le point de congélation, si bien que moins d’eau gèle. Réduisez l’un ou l’autre et vous obtenez du dur et du granuleux — d’où le problème de texture, non de goût, des glaces allégées."},
   tips:[{en:"Age the base overnight in the fridge before churning. The fat crystallises and the texture is visibly better.",fr:"Faites maturer la base une nuit au froid avant turbinage. Le gras cristallise et la texture est visiblement meilleure."},
         {en:"Churn it as cold as you can get it. A warm base spends longer in the crystal-growing zone.",fr:"Turbinez-la aussi froide que possible. Une base tiède passe plus de temps dans la zone de croissance des cristaux."}],
   pairs:["vanilla","sugar","egg","dark-chocolate","pistachio","coffee","strawberry","tonka"]}
]},

{id:"mushroom", branches:[
  {id:"cru", art:"raw", name:{en:"Raw",fr:"Cru"},
   variety:{en:"Firm, dry, very fresh only",fr:"Fermes, secs, très frais seulement"},
   technique:{en:"Sliced thin and dressed at the last moment, raw mushroom is crisp and faintly nutty — nothing like its cooked self. Acid firms it and stops it browning, but dress it early and it collapses into something grey and weeping within twenty minutes.",
   fr:"Émincé fin et assaisonné au dernier moment, le champignon cru est croquant et légèrement noiseté — rien à voir avec sa version cuite. L’acide le raffermit et l’empêche de brunir, mais assaisonné trop tôt il s’effondre en une chose grise et suintante en vingt minutes."},
   tips:[{en:"Only for cultivated mushrooms you trust. Many wild species are genuinely not safe raw.",fr:"Réservé aux champignons de culture, en confiance. Beaucoup d’espèces sauvages ne sont réellement pas sûres crues."},
         {en:"Lemon and oil at the table, not in the kitchen. Twenty minutes is the whole window.",fr:"Citron et huile à table, non en cuisine. Vingt minutes, c’est toute la fenêtre."}],
   pairs:["lemon","olive-oil","parmesan","black-pepper","parsley","hazelnut-oil","celery","chives"]},

  {id:"sautes", art:"fried", name:{en:"Sautéed",fr:"Sautés"},
   variety:{en:"Hot pan, few at a time, salt last",fr:"Poêle brûlante, peu à la fois, sel en dernier"},
   technique:{en:"A mushroom is mostly water, and that water is the enemy of browning. A crowded pan or an early pinch of salt draws it all out at once and they stew grey in their own liquid. Hot pan, single layer, no salt until they have taken colour.",
   fr:"Un champignon est surtout de l’eau, et cette eau est l’ennemie de la coloration. Une poêle chargée ou une pincée de sel trop tôt la tire d’un coup et ils s’étuvent, gris, dans leur jus. Poêle chaude, une seule couche, pas de sel avant coloration."},
   tips:[{en:"Do not wash them under a tap — they are sponges. Brush them, or wipe with a damp cloth.",fr:"Ne les lavez pas au robinet — ce sont des éponges. Brossez-les, ou essuyez-les d’un linge humide."},
         {en:"If they do release water, keep going. Once it boils off they will finally start to brown.",fr:"S’ils rendent leur eau, continuez. Une fois évaporée, ils commenceront enfin à colorer."}],
   pairs:["garlic","parsley","beurre-de-baratte","thyme","shallot","black-pepper","cream","olive-oil"]},

  {id:"duxelles", art:"chopped", name:{en:"Duxelles",fr:"Duxelles"},
   variety:{en:"Chopped fine, cooked to almost dry",fr:"Hachés fin, cuits presque à sec"},
   technique:{en:"Finely chopped mushroom and shallot cooked down until nearly all the moisture has gone — a paste rather than a garnish, and one of the most concentrated savoury things in the French repertoire. It is the stuffing inside a Wellington and the base of a great many sauces.",
   fr:"Champignons et échalote hachés très fin, cuits jusqu’à évaporation presque complète — une pâte plutôt qu’une garniture, et l’une des choses les plus savoureuses et concentrées du répertoire français. C’est la farce d’un Wellington et la base de bien des sauces."},
   tips:[{en:"Chop by hand if you can. A processor bruises them and they release water before they hit the pan.",fr:"Hachez au couteau si possible. Un robot les meurtrit et ils rendent leur eau avant la poêle."},
         {en:"It freezes perfectly in spoonfuls. A cube dropped into a sauce is an instant depth charge.",fr:"Elle se congèle parfaitement en cuillerées. Un cube jeté dans une sauce est une charge de profondeur."}],
   pairs:["shallot","beurre-de-baratte","thyme","white-wine-vinegar","parsley","cream","black-pepper","garlic"]},

  {id:"rotis", art:"roasted", name:{en:"Roasted",fr:"Rôtis"},
   variety:{en:"Whole or halved, high heat",fr:"Entiers ou en deux, four chaud"},
   technique:{en:"The oven solves the crowding problem a pan cannot — dry heat from all sides evaporates the moisture as it comes out rather than pooling it. Large mushrooms roast far better than small ones, and they want more oil than seems reasonable because they absorb it and give it back.",
   fr:"Le four résout le problème de surcharge que la poêle ne peut pas — une chaleur sèche de tous côtés évapore l’humidité à mesure au lieu de la laisser s’accumuler. Les gros champignons rôtissent bien mieux que les petits, et réclament plus d’huile qu’il ne semble raisonnable, car ils l’absorbent puis la rendent."},
   tips:[{en:"Gills up, so the juices collect in the cap rather than running out onto the tray.",fr:"Lames vers le haut, pour que les sucs se rassemblent dans le chapeau au lieu de couler sur la plaque."},
         {en:"Add garlic and herbs only for the last five minutes. Twenty minutes at that heat burns them.",fr:"N’ajoutez ail et herbes que dans les cinq dernières minutes. Vingt minutes à cette chaleur les brûlent."}],
   pairs:["olive-oil","thyme","garlic","rosemary","black-pepper","parmesan","parsley","balsamic"]},

  {id:"seches", art:"dried", name:{en:"Dried",fr:"Séchés"},
   variety:{en:"Umami multiplied several times over",fr:"L’umami multiplié plusieurs fois"},
   technique:{en:"Drying concentrates glutamates dramatically — a dried cep carries several times the savoury intensity of a fresh one, which is why a small handful transforms a stock. Rehydrate in warm water, never boiling, and the soaking liquid is worth more than the mushrooms.",
   fr:"Le séchage concentre spectaculairement les glutamates — un cèpe sec porte plusieurs fois l’intensité savoureuse du frais, d’où une petite poignée qui transforme un bouillon. Réhydratez à l’eau tiède, jamais bouillante, et le liquide de trempage vaut plus que les champignons."},
   tips:[{en:"Strain the soaking water through cloth — there is always grit — then use it as the liquid in the dish.",fr:"Filtrez l’eau de trempage à travers un linge — il y a toujours du sable — puis employez-la comme liquide du plat."},
         {en:"A few dried ceps in a beef stew is the cheapest way to make it taste long-cooked.",fr:"Quelques cèpes secs dans un bœuf mijoté sont le moyen le moins cher de lui donner l’air d’une longue cuisson."}],
   pairs:["porcini","white-wine-vinegar","thyme","cream","garlic","black-pepper","beef","arborio"]},

  {id:"marines", art:"pickled", name:{en:"Pickled",fr:"Marinés"},
   variety:{en:"Blanched first, then into the vinegar",fr:"Blanchis d’abord, puis au vinaigre"},
   technique:{en:"Small firm mushrooms blanched briefly, then covered in warm vinegar with oil, bay and peppercorns. The blanching matters — raw mushrooms in vinegar go slimy, because their cell walls collapse without the brief heat to set them first.",
   fr:"De petits champignons fermes brièvement blanchis, puis couverts d’un vinaigre tiède avec huile, laurier et grains de poivre. Le blanchiment compte — crus dans le vinaigre ils deviennent gluants, leurs parois s’effondrant faute d’une brève chaleur pour les fixer."},
   tips:[{en:"Give them three days before eating. On day one all you taste is vinegar.",fr:"Laissez-leur trois jours avant de les manger. Le premier jour, on ne goûte que le vinaigre."},
         {en:"Oil floating on top seals them. Keep them submerged and they last a month.",fr:"Une couche d’huile en surface les protège. Gardés immergés, ils tiennent un mois."}],
   pairs:["white-wine-vinegar","bay-leaf","black-pepper","olive-oil","garlic","thyme","shallot","coriander-seed"]}
]},

{id:"apple", branches:[
  {id:"crue", art:"raw", name:{en:"Raw",fr:"Crue"},
   variety:{en:"Acid and crunch — not the cooking kind",fr:"Acidité et croquant — pas les variétés à cuire"},
   technique:{en:"Browning is an enzyme meeting oxygen at a cut surface, and acid stops it — lemon works, but so does salted water, which does not sweeten the fruit. Varieties bred for eating hold their acid and structure raw; varieties bred for cooking often taste flat and mealy uncooked.",
   fr:"Le brunissement est une enzyme rencontrant l’oxygène sur une surface coupée, et l’acide l’arrête — le citron marche, l’eau salée aussi, sans sucrer le fruit. Les variétés de table gardent acidité et tenue crues ; les variétés à cuire sont souvent plates et farineuses crues."},
   tips:[{en:"Salted water — a teaspoon in a litre — browns nothing and leaves no lemon taste.",fr:"Une eau salée — une cuillère à café par litre — n’altère rien et ne laisse aucun goût de citron."},
         {en:"Raw apple is acid and crunch. That is what it brings to a plate, not sweetness.",fr:"La pomme crue apporte acidité et croquant. C’est ce qu’elle donne à l’assiette, non du sucre."}],
   pairs:["celery","walnut","blue-cheese","cider-vinegar","hazelnut-oil","black-pepper","comte","mache"]},

  {id:"compote", name:{en:"Compote",fr:"Compote"},
   variety:{en:"Falls apart on purpose",fr:"Se défait volontairement"},
   technique:{en:"Cooking breaks down pectin and the cell walls give way — which is exactly what you want here and exactly what you do not want in a tart. Varieties that collapse fast are the right ones. A splash of water, a lid, and low heat; sugar only at the end, once you know how sweet the fruit was.",
   fr:"La cuisson dégrade la pectine et les parois cèdent — ce que l’on cherche ici et ce que l’on fuit dans une tarte. Les variétés qui s’effondrent vite sont les bonnes. Un trait d’eau, un couvercle, un feu doux ; le sucre à la fin seulement, une fois connue la douceur du fruit."},
   tips:[{en:"Leave some pieces barely broken. A compote of uniform purée has lost its texture.",fr:"Laissez quelques morceaux à peine défaits. Une compote uniformément lisse a perdu sa texture."},
         {en:"A strip of lemon zest, not juice. The oils carry further and the acid is already there.",fr:"Un zeste de citron, non du jus. Les huiles portent plus loin et l’acidité est déjà présente."}],
   pairs:["cinnamon","vanilla","beurre-de-baratte","lemon","clove","sugar","cardamom","cider-vinegar"]},

  {id:"caramelisee", art:"caramel", name:{en:"Caramelised",fr:"Caramélisée"},
   variety:{en:"Firm varieties that hold their shape",fr:"Variétés fermes qui tiennent à la cuisson"},
   technique:{en:"The tarte tatin problem: apples that collapse make a purée under pastry, not a tatin. You need a variety that holds — reine des reinettes, boskoop — cooked in butter and sugar until the caramel takes, with the fruit still recognisably in pieces.",
   fr:"Le problème de la tarte Tatin : des pommes qui s’effondrent donnent une purée sous la pâte, non une Tatin. Il faut une variété qui tient — reine des reinettes, boskoop — cuite au beurre et au sucre jusqu’à prise du caramel, le fruit encore nettement en morceaux."},
   tips:[{en:"Cook the caramel before the apples go in, not with them. Fruit water stops sugar caramelising.",fr:"Faites le caramel avant d’ajouter les pommes, non avec elles. L’eau du fruit empêche le sucre de caraméliser."},
         {en:"Pack them in tightly. They shrink by a third and a loose tatin falls apart when turned out.",fr:"Serrez-les bien. Elles perdent un tiers de volume, et une Tatin lâche s’effondre au démoulage."}],
   pairs:["sugar","beurre-de-baratte","vanilla","cinnamon","cream","flour-t45","lemon","walnut"]},

  {id:"aufour", art:"baked", name:{en:"Baked whole",fr:"Au four"},
   variety:{en:"Cored, scored, an hour at 180 °C",fr:"Évidée, incisée, une heure à 180 °C"},
   technique:{en:"Baked in its own skin, the apple steams from the inside and the flesh turns to a fluff that holds its shape until you break it. Score a line around the middle or the skin splits where it chooses — usually messily.",
   fr:"Cuite dans sa peau, la pomme cuit à la vapeur de l’intérieur et la chair devient une mousse qui tient jusqu’à ce qu’on la rompe. Incisez un trait autour du milieu, sinon la peau se fend où elle veut — en général salement."},
   tips:[{en:"Fill the core with butter, sugar and something dried. It bastes the fruit from within as it melts.",fr:"Garnissez le cœur de beurre, de sucre et d’un fruit sec. En fondant, cela arrose le fruit de l’intérieur."},
         {en:"A splash of water in the dish stops the sugar catching before the apple is soft.",fr:"Un fond d’eau dans le plat empêche le sucre d’accrocher avant que la pomme ne soit tendre."}],
   pairs:["raisin","beurre-de-baratte","cinnamon","sugar","walnut","cream","clove","honey"]},

  {id:"sechee", art:"dried", name:{en:"Dried",fr:"Séchée"},
   variety:{en:"Thin rings, low oven, hours",fr:"Anneaux fins, four doux, des heures"},
   technique:{en:"Thin rings dried slowly until leathery — or further, until they snap. Drying concentrates the sugars and the acidity in equal measure, so a dried apple is not simply a sweeter apple; it is a more intense one in both directions.",
   fr:"De fins anneaux séchés lentement jusqu’au cuir — ou plus loin, jusqu’à ce qu’ils cassent net. Le séchage concentre autant les sucres que l’acidité : une pomme séchée n’est pas simplement plus sucrée, elle est plus intense dans les deux sens."},
   tips:[{en:"Dip the rings in acidulated water first or they dry to an unappetising brown.",fr:"Trempez les anneaux dans une eau citronnée d’abord, sinon ils sèchent d’un brun peu appétissant."},
         {en:"Leathery keeps a month; snapping-crisp keeps six, but must be perfectly dry or it moulds.",fr:"Souples elles tiennent un mois ; cassantes six, mais parfaitement sèches sous peine de moisissure."}],
   pairs:["cinnamon","walnut","honey","oats","raisin","almond","yogurt","dark-chocolate"]}
]},

{id:"dark-chocolate", branches:[
  {id:"tempere", art:"tempered", name:{en:"Tempered",fr:"Tempéré"},
   variety:{en:"45 °C → 27 °C → 31 °C",fr:"45 °C → 27 °C → 31 °C"},
   technique:{en:"Cocoa butter can set into six different crystal forms and only one of them — form V — is glossy, snaps and melts at body temperature. Tempering is the process of persuading it to form only that one: melt fully, cool to force crystallisation, then warm slightly to melt the unstable forms back out.",
   fr:"Le beurre de cacao peut cristalliser sous six formes et une seule — la forme V — est brillante, cassante et fond à température du corps. Le tempérage consiste à ne laisser subsister que celle-là : fondre complètement, refroidir pour forcer la cristallisation, puis réchauffer légèrement pour refaire fondre les formes instables."},
   tips:[{en:"Untempered chocolate sets dull, soft, and streaked with white. That bloom is fat, not mould.",fr:"Un chocolat non tempéré prend terne, mou et zébré de blanc. Ce voile est du gras, non une moisissure."},
         {en:"A single drop of water will seize the whole bowl. Dry hands, dry bowl, dry spatula.",fr:"Une seule goutte d’eau fige tout le bol. Mains sèches, bol sec, spatule sèche."}],
   pairs:["orange","hazelnut","coffee","salt","cardamom","pistachio","vanilla","timut-pepper"]},

  {id:"ganache", name:{en:"Ganache",fr:"Ganache"},
   variety:{en:"Emulsion: fat suspended in water",fr:"Émulsion : du gras en suspension dans l’eau"},
   technique:{en:"Counter-intuitively, cream is mostly water and chocolate is mostly fat — a ganache is an emulsion, not a melt. Pour hot cream over chopped chocolate, wait a minute, then stir from the centre outward. It looks broken right up until it suddenly turns glossy and comes together.",
   fr:"Contre-intuitivement, la crème est surtout de l’eau et le chocolat surtout du gras — une ganache est une émulsion, non une fonte. Versez la crème chaude sur le chocolat haché, attendez une minute, puis remuez du centre vers l’extérieur. Elle paraît tranchée jusqu’à devenir soudain brillante et se rassembler."},
   tips:[{en:"Chop it fine and evenly. Large chunks melt slowly and you over-stir waiting for them.",fr:"Hachez fin et régulier. De gros morceaux fondent lentement et l’on remue trop en les attendant."},
         {en:"Equal weights gives a soft ganache; two parts chocolate to one of cream gives truffles.",fr:"À poids égaux, ganache souple ; deux parts de chocolat pour une de crème, des truffes."}],
   pairs:["cream","beurre-de-baratte","orange","raspberry","coffee","cardamom","honey","vanilla"]},

  {id:"mousse", art:"whipped", name:{en:"Mousse",fr:"Mousse"},
   variety:{en:"Temperature match or it seizes",fr:"Températures accordées, sinon ça fige"},
   technique:{en:"Air held in a chocolate base by either whipped whites or whipped cream. The failure everyone hits is temperature: cold foam folded into hot chocolate sets the cocoa butter instantly into grains. Both parts must be close to the same temperature before they meet.",
   fr:"De l’air retenu dans une base chocolatée par des blancs ou une crème montés. L’échec universel est thermique : une mousse froide incorporée à un chocolat chaud fige instantanément le beurre de cacao en grains. Les deux parties doivent être proches en température avant de se rencontrer."},
   tips:[{en:"Fold in a third of the foam first to loosen the base, then the rest gently. Two stages, always.",fr:"Incorporez d’abord un tiers de la mousse pour détendre la base, puis le reste délicatement. Deux temps, toujours."},
         {en:"Stop folding while a few streaks remain. Perfectly uniform means you have knocked the air out.",fr:"Arrêtez tant que quelques marbrures subsistent. Parfaitement homogène signifie que l’air est parti."}],
   pairs:["egg","cream","sugar","orange","coffee","vanilla","raspberry","cardamom"]},

  {id:"sauce", name:{en:"Sauce",fr:"Sauce"},
   variety:{en:"Water-based — it will not split",fr:"À base d’eau — elle ne tranche pas"},
   technique:{en:"Chocolate melted into water, syrup or milk rather than cream. Counter to instinct, more water makes it more stable, not less: the seizing that ruins a bowl of melting chocolate happens when a *little* water meets a lot of cocoa solids and glues them together.",
   fr:"Du chocolat fondu dans de l’eau, un sirop ou du lait plutôt que de la crème. À rebours de l’intuition, plus d’eau la rend plus stable, non moins : le figeage qui ruine un bol de chocolat fondu survient quand *un peu* d’eau rencontre beaucoup de matière sèche de cacao et l’agglomère."},
   tips:[{en:"If melting chocolate does seize, add more liquid, not less. It comes back smooth.",fr:"Si du chocolat fondu fige, ajoutez plus de liquide, non moins. Il redevient lisse."},
         {en:"A pinch of salt does more for chocolate than more sugar does.",fr:"Une pincée de sel fait plus pour le chocolat qu’un surcroît de sucre."}],
   pairs:["sugar","cream","vanilla","orange","coffee","cinnamon","chili","salt"]}
]}

]);
