window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"argan-oil",cat:"fats",name:{en:"Argan oil",fr:"Huile d’argan"},latin:"Argania spinosa",
origin:{en:"Souss valley, Morocco",fr:"Vallée du Souss, Maroc"},season:[],
flavor:["nutty","toasty","rich","earthy"],
story:{en:"The tree grows nowhere but southwestern Morocco, and the kernels are still cracked by hand between two stones because no machine has managed it. Berber women's cooperatives control most of the production, which is unusual and deliberate.",
fr:"L’arganier ne pousse qu’au sud-ouest du Maroc, et les amandons se concassent encore à la main entre deux pierres, aucune machine n’y étant parvenue. Des coopératives de femmes berbères contrôlent l’essentiel de la production, ce qui est rare et voulu."},
tip:{en:"The culinary version is pressed from roasted kernels and is darker. The cosmetic one is raw, paler, and tastes of very little.",
fr:"La version culinaire est pressée d’amandons torréfiés et plus foncée. La cosmétique est crue, plus claire, et n’a presque aucun goût."},
pairs:["almond","honey","flour-t65","cumin","lemon","olive","orange","chickpeas"],
svg:'<path class="f1 sf" d="M42 76V46h12v30z"/><path class="s" d="M42 54h12"/><path class="f2 sf" d="M44 42q-6-8 4-12t4 12z"/>'},

{id:"avocado-oil",cat:"fats",name:{en:"Avocado oil",fr:"Huile d’avocat"},latin:"Persea americana",
origin:{en:"Mexico & New Zealand",fr:"Mexique & Nouvelle-Zélande"},season:[],
flavor:["mild","grassy","buttery","fresh"],
story:{en:"Pressed from the flesh rather than a seed, which makes it one of the very few fruit oils alongside olive and palm. It also has one of the highest smoke points of any unrefined oil, which is unusual for something pressed cold.",
fr:"Pressée de la chair plutôt que d’une graine, ce qui en fait l’une des très rares huiles de fruit avec l’olive et le palme. Elle possède aussi l’un des points de fumée les plus élevés parmi les huiles non raffinées, chose rare pour un pressage à froid."},
tip:{en:"It takes a hard sear without smoking, so use it where you want high heat but a clean, buttery background.",
fr:"Elle supporte une saisie vive sans fumer : employez-la quand vous voulez une forte chaleur avec un fond net et beurré."},
pairs:["lime","cilantro","tomato","chili","black-pepper","avocado","red-onion","lemon"],
svg:'<path class="f3 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f2 sf" d="M48 26q6 4 6 10t-6 8-6-8 6-10z"/>'},

{id:"clarified-butter",cat:"fats",name:{en:"Clarified butter",fr:"Beurre clarifié"},latin:"Butyrum clarificatum",
origin:{en:"France",fr:"France"},season:[],
flavor:["buttery","rich","delicate","mild"],
story:{en:"Butter burns at around 150°C because of its milk solids, not its fat. Remove them and the same fat will take 250°C — which is why every classical French kitchen keeps a pot of it beside the stove for searing.",
fr:"Le beurre brûle vers 150 °C à cause de ses solides du lait, non de sa matière grasse. Ôtez-les et la même graisse tient 250 °C — d’où le pot que toute cuisine classique française garde près du fourneau pour saisir."},
tip:{en:"Melt gently and do not let it colour — that is the difference from ghee. Skim the foam, pour off the gold, leave the milky base.",
fr:"Fondez doucement sans laisser colorer — c’est ce qui le distingue du ghee. Écumez la mousse, versez l’or, laissez le fond laiteux."},
pairs:["shallot","lemon","thyme","garlic","scallop","black-pepper","parsley","turbot"],
svg:'<path class="f3 sf" d="M36 72V48q12-5 24 0v24z"/><path class="s" d="M36 48q12 5 24 0M36 58h24"/>'},

{id:"coconut-oil",cat:"fats",name:{en:"Coconut oil",fr:"Huile de coco"},latin:"Cocos nucifera",
origin:{en:"Indo-Pacific",fr:"Indo-Pacifique"},season:[],
flavor:["sweet","nutty","creamy","mild"],
story:{en:"Almost uniquely among plant fats it is solid at room temperature, because it is overwhelmingly saturated — which is also why it keeps for years without turning. Kerala and Sri Lanka have cooked in nothing else for centuries.",
fr:"Presque unique parmi les graisses végétales, elle est solide à température ambiante parce qu’elle est massivement saturée — ce qui explique aussi qu’elle se garde des années sans rancir. Le Kerala et le Sri Lanka n’ont cuisiné qu’avec elle pendant des siècles."},
tip:{en:"Virgin coconut oil tastes strongly of coconut; the refined version tastes of nothing. Choose deliberately, they are not interchangeable.",
fr:"L’huile vierge a un goût marqué de coco ; la raffinée n’a aucun goût. Choisissez sciemment, elles ne sont pas interchangeables."},
pairs:["chili","lime","ginger","turmeric","cilantro","coconut-milk","curry-leaf","garlic"],
svg:'<path class="f3 sf" d="M36 74V46h24v28z"/><path class="s" d="M36 54h24"/><circle class="f1 sf" cx="48" cy="34" r="8"/><circle class="dot" cx="45" cy="32" r="1.6"/><circle class="dot" cx="51" cy="32" r="1.6"/>'},

{id:"duck-fat",cat:"fats",name:{en:"Duck fat",fr:"Graisse de canard"},latin:"Adeps anatis",
origin:{en:"Southwest France",fr:"Sud-Ouest de la France"},season:[],
flavor:["rich","meaty","earthy","umami"],
story:{en:"Confit exists because of it: submerge a leg in rendered fat, cook it slowly and store it under the set fat, and it keeps for months without refrigeration. The fat is the preservative, the cooking medium and the seal all at once.",
fr:"Le confit existe grâce à elle : immerger une cuisse dans la graisse fondue, la cuire lentement et la conserver sous la graisse figée, et elle se garde des mois sans froid. La graisse est à la fois conservateur, milieu de cuisson et opercule."},
tip:{en:"Nothing makes a better roast potato. Get it smoking hot before the potatoes go in, or they absorb it instead of frying.",
fr:"Rien ne réussit mieux les pommes de terre rôties. Faites-la fumer avant d’y jeter les pommes de terre, sinon elles l’absorbent au lieu de frire."},
pairs:["potato","garlic","thyme","duck","black-pepper","onion","white-beans","bay-leaf"],
svg:'<path class="f2 sf" d="M34 72V48q14-6 28 0v24z"/><path class="s" d="M34 48q14 6 28 0"/><path class="s" d="M40 60q8 4 16 0"/>'},

{id:"ghee",cat:"fats",name:{en:"Ghee",fr:"Ghee"},latin:"Butyrum depuratum",
origin:{en:"India",fr:"Inde"},season:[],
flavor:["nutty","rich","toasty","buttery"],
story:{en:"Butter simmered until the water boils off and the milk solids brown at the bottom, then strained — which removes everything that would spoil. In a climate without refrigeration it keeps for a year, and Vedic texts treat it as sacred.",
fr:"Du beurre mijoté jusqu’à évaporation de l’eau et coloration des solides du lait au fond, puis filtré — ce qui ôte tout ce qui pourrait tourner. Sous un climat sans réfrigération il se garde un an, et les textes védiques le tiennent pour sacré."},
tip:{en:"Let the solids brown, do not just melt the butter. That browning is the difference between ghee and clarified butter.",
fr:"Laissez colorer les solides, ne vous contentez pas de fondre le beurre. Cette coloration fait toute la différence avec un beurre clarifié."},
pairs:["cumin","turmeric","cardamom","garlic","ginger","rice","curry-leaf","chili"],
svg:'<path class="f2 sf" d="M36 72V46q12-6 24 0v26z"/><path class="s" d="M36 46q12 6 24 0"/><circle class="dot" cx="44" cy="60" r="2"/><circle class="dot" cx="53" cy="64" r="2"/>'},

{id:"grapeseed-oil",cat:"fats",name:{en:"Grapeseed oil",fr:"Huile de pépins de raisin"},latin:"Vitis vinifera",
origin:{en:"Wine regions of Europe",fr:"Régions viticoles d’Europe"},season:[],
flavor:["mild","delicate","fresh","grassy"],
story:{en:"A by-product of winemaking — the pomace left after pressing holds seeds that would otherwise be waste, and it takes roughly forty kilos of grapes to yield a single litre. Nothing in a vineyard is thrown away twice.",
fr:"Un sous-produit de la vinification — le marc laissé après pressage contient des pépins qui seraient sinon perdus, et il faut environ quarante kilos de raisin pour un seul litre. Rien dans une vigne ne se jette deux fois."},
tip:{en:"Its very high smoke point and clean taste make it the right oil for mayonnaise and for searing, where olive oil would dominate.",
fr:"Son point de fumée très élevé et son goût net en font l’huile juste pour la mayonnaise et les saisies, là où l’olive dominerait."},
pairs:["lemon","egg","mustard","garlic","black-pepper","thyme","shallot","white-wine-vinegar"],
svg:'<path class="f3 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="dot" cx="44" cy="62" r="2"/><circle class="dot" cx="52" cy="66" r="2"/>'},

{id:"hazelnut-oil",cat:"fats",name:{en:"Hazelnut oil",fr:"Huile de noisette"},latin:"Corylus avellana",
origin:{en:"Piedmont & southwest France",fr:"Piémont & Sud-Ouest de la France"},season:[],
flavor:["nutty","toasty","rich","sweet"],
story:{en:"Sweeter and rounder than walnut oil, and rarer, because hazelnuts give less oil for the same weight. Piedmont uses it where Provence would reach for olive, and it turns a plain green salad into something that tastes cooked.",
fr:"Plus douce et plus ronde que l’huile de noix, et plus rare, la noisette rendant moins d’huile à poids égal. Le Piémont l’emploie là où la Provence prendrait l’olive, et elle transforme une simple salade verte en quelque chose qui a l’air cuisiné."},
tip:{en:"A teaspoon at the end of a soup or a purée does more than a whole spoonful of butter. Add it off the heat.",
fr:"Une cuillère à café en fin de soupe ou de purée fait plus qu’une cuillerée de beurre. Ajoutez-la hors du feu."},
pairs:["hazelnut","mache","goat-cheese","pear","sherry-vinegar","apple","beetroot","comte"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="f1 sf" cx="48" cy="34" r="7"/><path class="s" d="M44 30q4-4 8 0"/>'},

{id:"lard",cat:"fats",name:{en:"Lard",fr:"Saindoux"},latin:"Adeps suillus",
origin:{en:"Europe & China",fr:"Europe & Chine"},season:[],
flavor:["rich","meaty","mild","creamy"],
story:{en:"Its large fat crystals coat flour particles better than butter does, which is why lard pastry is flakier than any other and why it dominated baking until vegetable shortening arrived and marketing pushed it out.",
fr:"Ses gros cristaux de gras enrobent les particules de farine mieux que le beurre, d’où une pâte au saindoux plus feuilletée que toute autre, et sa domination de la boulangerie jusqu’à l’arrivée des graisses végétales et de leur publicité."},
tip:{en:"Ask for leaf lard, from around the kidneys, if you are baking. The back fat is fine for frying but tastes of pork.",
fr:"Demandez la panne, prise autour des rognons, si vous pâtissez. Le lard dorsal convient à la friture mais garde le goût de porc."},
pairs:["potato","onion","garlic","black-pepper","thyme","cabbage","flour-t65","paprika"],
svg:'<path class="f3 sf" d="M32 70V50h32v20z"/><path class="s" d="M32 58h32"/><path class="s" d="M42 50v20M54 50v20"/>'},

{id:"olive-oil",cat:"fats",name:{en:"Olive oil",fr:"Huile d’olive"},latin:"Olea europaea",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["fruity","grassy","peppery","bitter"],
story:{en:"Athens is named for a bet: Athena offered the olive tree, Poseidon a salt spring, and the citizens chose the tree. Homer called its oil “liquid gold”; athletes wore it, lamps burned it, and the Mediterranean still cooks in it before anything else.",
fr:"Athènes doit son nom à un pari : Athéna offrit l’olivier, Poséidon une source salée, et les citoyens choisirent l’arbre. Homère appelait son huile « l’or liquide » ; les athlètes s’en oignaient, les lampes la brûlaient, et la Méditerranée cuisine toujours avec elle avant toute chose."},
tip:{en:"The peppery catch in the throat of a young oil is a virtue, not a flaw. Keep a modest oil for the pan and a great one for the final thread over the plate.",
fr:"Le piquant en gorge d’une huile jeune est une vertu, pas un défaut. Gardez une huile modeste pour la poêle et une grande pour le filet final sur l’assiette."},
pairs:["tomato","garlic","lemon","basil","white-beans","cod","eggplant"],
svg:'<path class="f1 sf" d="M44 26h8v10l4 6v30q0 6-8 6t-8-6V42l4-6z"/><path class="s" d="M44 26h8"/><path class="f3 sf" d="M40 66a4 4 0 108 0 4 4 0 10-8 0z" transform="translate(4 0)"/><path class="s" d="M52 62q4-4 8-4"/>'},

{id:"peanut-oil",cat:"fats",name:{en:"Peanut oil",fr:"Huile d’arachide"},latin:"Arachis hypogaea",
origin:{en:"South America, via West Africa",fr:"Amérique du Sud, via l’Afrique de l’Ouest"},season:[],
flavor:["mild","nutty","toasty","delicate"],
story:{en:"Its smoke point is high enough that it fries chips twice without breaking down, which is why chip shops and Chinese kitchens both settled on it. Refined, it carries almost none of the protein that triggers nut allergy.",
fr:"Son point de fumée est assez haut pour frire deux fois des frites sans se dégrader, d’où son adoption par les friteries comme par les cuisines chinoises. Raffinée, elle ne porte presque rien de la protéine qui déclenche l’allergie."},
tip:{en:"It can be strained and reused several times for deep frying, which no delicate oil tolerates. Filter it while still warm.",
fr:"Elle se filtre et se réutilise plusieurs fois en friture, ce qu’aucune huile délicate ne tolère. Filtrez-la encore tiède."},
pairs:["chili","garlic","ginger","soy-sauce","spring-onion","potato","peanut","sesame"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f1 sf" d="M42 38q-4-6 0-8t6 2 6-2 0 8-6 2z"/>'},

{id:"pumpkin-seed-oil",cat:"fats",name:{en:"Pumpkin seed oil",fr:"Huile de pépins de courge"},latin:"Cucurbita pepo var. styriaca",
origin:{en:"Styria, Austria",fr:"Styrie, Autriche"},season:[],
flavor:["nutty","toasty","rich","earthy"],
story:{en:"So dark it looks black in the bottle and bright green in a thin film — an optical effect called dichromatism, rare in food. Styria protects it with a European designation, and the seeds come from a squash that grows without a husk.",
fr:"Si sombre qu’elle paraît noire en bouteille et vert vif en film mince — un effet optique appelé dichromatisme, rare en alimentation. La Styrie la protège par une appellation européenne, et les graines viennent d’une courge qui pousse sans coque."},
tip:{en:"Austrians pour it over vanilla ice cream, and it is not a joke — the toasted, salty note against cold cream works.",
fr:"Les Autrichiens la versent sur la glace vanille, et ce n’est pas une plaisanterie — la note grillée et salée contre la crème froide fonctionne."},
pairs:["vanilla","pumpkin","cider-vinegar","potato","cream","honey","walnut","lettuce"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><ellipse class="f3 sf" cx="48" cy="34" rx="6" ry="8"/>'},

{id:"rapeseed-oil",cat:"fats",name:{en:"Rapeseed oil",fr:"Huile de colza"},latin:"Brassica napus",
origin:{en:"Europe",fr:"Europe"},season:[],
flavor:["grassy","nutty","mild","fresh"],
story:{en:"The original plant made an oil too high in erucic acid to eat safely, and it was sold as a machine lubricant. Canadian breeders bred that compound out in the 1970s and renamed the result canola — a new food invented by subtraction.",
fr:"La plante d’origine donnait une huile trop riche en acide érucique pour être consommée sans risque, et on la vendait comme lubrifiant. Des sélectionneurs canadiens éliminèrent ce composé dans les années 1970 et rebaptisèrent le résultat canola — un aliment nouveau créé par soustraction."},
tip:{en:"Buy the cold-pressed version for dressings — it is grassy and bright yellow. The refined one is for heat and nothing else.",
fr:"Prenez la version vierge pour les assaisonnements — herbacée et jaune vif. La raffinée est pour la chaleur, rien d’autre."},
pairs:["mustard","potato","white-wine-vinegar","chives","lemon","black-pepper","shallot","dill"],
svg:'<path class="f2 sf" d="M40 76V42h16v34z"/><path class="s" d="M40 50h16"/><path class="f3 sf" d="M44 38V28h8v10z"/>'},

{id:"suet",cat:"fats",name:{en:"Suet",fr:"Graisse de rognon"},latin:"Sebum bovis",
origin:{en:"Britain",fr:"Grande-Bretagne"},season:[],
flavor:["rich","meaty","mild","earthy"],
story:{en:"The hard fat from around beef kidneys, and it melts far higher than butter — so in a steamed pudding it stays solid while the flour sets around it, then melts and leaves the batter airy. British puddings depend entirely on that timing.",
fr:"La graisse dure prise autour des rognons de bœuf, dont le point de fusion dépasse largement celui du beurre — dans un pudding vapeur elle reste solide le temps que la farine prenne autour, puis fond et laisse la pâte aérée. Les puddings britanniques reposent entièrement sur ce décalage."},
tip:{en:"It must go in cold and grated, never melted. Warm suet blends into the flour and the whole point is lost.",
fr:"Elle doit entrer froide et râpée, jamais fondue. Tiède, elle se fond dans la farine et tout l’intérêt disparaît."},
pairs:["flour-t65","beef","onion","black-pepper","thyme","raisin","cinnamon","bay-leaf"],
svg:'<path class="f3 sf" d="M34 70V48h28v22z"/><path class="s" d="M40 48v22M48 48v22M56 48v22"/>'},

{id:"sunflower-oil",cat:"fats",name:{en:"Sunflower oil",fr:"Huile de tournesol"},latin:"Helianthus annuus",
origin:{en:"Russia & Ukraine",fr:"Russie & Ukraine"},season:[],
flavor:["mild","nutty","delicate","toasty"],
story:{en:"The Russian Orthodox Church banned most fats during Lent but had never heard of the sunflower, so it escaped the list — and by the nineteenth century Russia was pressing it by the shipload. A loophole created an industry.",
fr:"L’Église orthodoxe russe interdisait la plupart des corps gras pendant le Carême mais ignorait le tournesol, qui échappa donc à la liste — et au XIXe siècle la Russie le pressait par cargaisons entières. Une faille a créé une industrie."},
tip:{en:"Its neutrality and high smoke point make it the default frying oil. Do not use it where you want the fat to taste of something.",
fr:"Sa neutralité et son point de fumée élevé en font l’huile de friture par défaut. Ne l’employez pas là où le gras doit avoir du goût."},
pairs:["potato","egg","onion","garlic","paprika","black-pepper","white-wine-vinegar","mustard"],
svg:'<path class="f2 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><path class="f3 sf" d="M44 40V30h8v10z"/><circle class="dot" cx="48" cy="62" r="3"/>'},

{id:"sesame-oil",cat:"fats",name:{en:"Toasted sesame oil",fr:"Huile de sésame grillé"},latin:"Sesamum indicum",
origin:{en:"East Asia",fr:"Asie de l’Est"},season:[],
flavor:["nutty","toasty","rich","umami"],
story:{en:"Two entirely different products share the name: the pale oil from raw seed, used for frying, and the dark oil from toasted seed, which is a seasoning and not a cooking fat at all. Buying the wrong one ruins the dish either way.",
fr:"Deux produits entièrement différents partagent le nom : l’huile claire de graines crues, pour la friture, et l’huile sombre de graines torréfiées, qui est un assaisonnement et pas du tout une matière grasse de cuisson. Se tromper gâche le plat dans les deux sens."},
tip:{en:"Add it at the very end, by the half-teaspoon. Heated, its whole aroma burns off within seconds.",
fr:"Ajoutez-la tout à la fin, à la demi-cuillère. Chauffée, tout son arôme s’évapore en quelques secondes."},
pairs:["soy-sauce","ginger","garlic","spring-onion","chili","sesame","fish-sauce","shiitake"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><ellipse class="f2 sf" cx="44" cy="34" rx="4" ry="3"/><ellipse class="f2 sf" cx="53" cy="36" rx="4" ry="3"/>'},

{id:"walnut-oil",cat:"fats",name:{en:"Walnut oil",fr:"Huile de noix"},latin:"Juglans regia",
origin:{en:"Périgord & Dauphiné",fr:"Périgord & Dauphiné"},season:[],
flavor:["nutty","rich","toasty","earthy"],
story:{en:"Pressed in stone mills in the Périgord, where the kernels are roasted before crushing — that roasting is the whole flavour. Before it was a condiment it lit lamps and thinned the paints of Renaissance workshops.",
fr:"Pressée dans des moulins de pierre en Périgord, où les cerneaux sont torréfiés avant broyage — cette torréfaction fait tout le goût. Avant d’être un condiment, elle éclairait les lampes et diluait les peintures des ateliers de la Renaissance."},
tip:{en:"Never heat it. It turns bitter almost immediately, and it goes rancid fast — keep the bottle in the fridge.",
fr:"Ne la chauffez jamais. Elle tourne à l’amer presque aussitôt, et rancit vite — gardez la bouteille au réfrigérateur."},
pairs:["walnut","endive","blue-cheese","mache","apple","sherry-vinegar","pear","comte"],
svg:'<path class="f1 sf" d="M40 76V44h16v32z"/><path class="s" d="M40 52h16"/><circle class="f2 sf" cx="48" cy="34" r="7"/><path class="s" d="M48 28v12"/>'}
]);
