window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"arborio",cat:"grains",name:{en:"Arborio rice",fr:"Riz arborio"},latin:"Oryza sativa",
origin:{en:"Po valley, Italy",fr:"Plaine du Pô, Italie"},season:[],
flavor:["mild","creamy","sweet","delicate"],
story:{en:"The creaminess of a risotto is not cream but amylopectin, a starch that leaches out of these short fat grains as they are stirred. Arborio holds a firm core longest, which is why it forgives an inattentive cook.",
fr:"Le crémeux d’un risotto n’est pas de la crème mais de l’amylopectine, un amidon qui s’échappe de ces grains courts et gras à mesure qu’on remue. L’arborio garde son cœur ferme le plus longtemps, et pardonne donc au cuisinier distrait."},
tip:{en:"Never rinse it. Washing removes exactly the surface starch that makes the dish work.",
fr:"Ne le rincez jamais. Le lavage ôte précisément l’amidon de surface qui fait tout le plat."},
pairs:["parmesan","butter","onion","white-wine-vinegar","saffron","porcini","black-pepper","thyme"],
svg:'<ellipse class="f3 sf" cx="40" cy="52" rx="5" ry="9"/><ellipse class="f3 sf" cx="54" cy="50" rx="5" ry="9"/><ellipse class="f3 sf" cx="47" cy="66" rx="5" ry="9"/>'},

{id:"yeast",cat:"grains",name:{en:"Baker’s yeast",fr:"Levure de boulanger"},latin:"Saccharomyces cerevisiae",
origin:{en:"Wild, everywhere",fr:"Sauvage, partout"},season:[],
flavor:["earthy","toasty","mild","umami"],
story:{en:"Bread rose for thousands of years before anyone knew why. Pasteur identified the organism in the 1850s, and only then did it become possible to buy the living thing in a packet rather than keeping a piece of yesterday's dough alive.",
fr:"Le pain a levé pendant des millénaires sans que nul en sache la raison. Pasteur identifia l’organisme dans les années 1850, et alors seulement devint-il possible d’acheter le vivant en sachet plutôt que d’entretenir un morceau de la pâte de la veille."},
tip:{en:"Never let it touch salt directly in the bowl — salt kills it on contact. Put the flour between them.",
fr:"Ne la laissez jamais toucher le sel directement dans le bol — le sel la tue au contact. Mettez la farine entre les deux."},
pairs:["flour-t65","salt","butter","honey","rye-flour","olive-oil","cream","flour-t55"],
svg:'<path class="f2 sf" d="M34 70V48h28v22z"/><circle class="dot" cx="42" cy="58" r="2"/><circle class="dot" cx="52" cy="56" r="2"/><circle class="dot" cx="47" cy="64" r="2"/>'},

{id:"barley",cat:"grains",name:{en:"Barley",fr:"Orge"},latin:"Hordeum vulgare",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["nutty","earthy","mild"],
story:{en:"In Mesopotamia, wages and taxes were paid in barley — the first salary was a grain ration. It brews the world’s beer and whisky, and in a slow soup it turns to little cushions of comfort.",
fr:"En Mésopotamie, salaires et impôts se payaient en orge — le premier salaire fut une ration de grain. Elle brasse la bière et le whisky du monde, et dans une soupe mijotée elle devient de petits coussins de réconfort."},
tip:{en:"Pearl barley needs no soaking and loves mushrooms; treat it like risotto rice for a nuttier, humbler orzotto.",
fr:"L’orge perlé ne demande aucun trempage et adore les champignons ; traitez-le comme un riz à risotto pour un orzotto plus rustique et noisetté."},
pairs:["mushroom","beef","onion","thyme","carrot"],
svg:'<path class="s" d="M48 78V30"/><path class="f2 sf" d="M44 62q-6 0-8-8 8-2 10 4zM52 62q6 0 8-8-8-2-10 4zM44 50q-6 0-8-8 8-2 10 4zM52 50q6 0 8-8-8-2-10 4zM44 38q-6 0-8-8 8-2 10 4zM52 38q6 0 8-8-8-2-10 4z"/><path class="s" d="M44 30l-4-8M48 30v-9M52 30l4-8"/>'},

{id:"basmati",cat:"grains",name:{en:"Basmati rice",fr:"Riz basmati"},latin:"Oryza sativa",
origin:{en:"Himalayan foothills",fr:"Contreforts himalayens"},season:[],
flavor:["floral","nutty","delicate","mild"],
story:{en:"The name means fragrant in Hindi, and the aroma comes from a compound also found in pandan leaf and fresh bread. Unusually for rice, it is aged a year or more before sale — the drying intensifies the perfume and makes the grains elongate further.",
fr:"Le nom signifie parfumé en hindi, et l’arôme vient d’un composé que l’on trouve aussi dans la feuille de pandan et le pain frais. Fait rare pour un riz, il est vieilli un an ou plus avant la vente — le séchage intensifie le parfum et fait s’allonger davantage les grains."},
tip:{en:"Rinse until the water runs clear, then soak thirty minutes. The grains double in length rather than swelling fat.",
fr:"Rincez jusqu’à eau claire, puis trempez trente minutes. Les grains doublent en longueur plutôt que de gonfler en épaisseur."},
pairs:["cardamom","cumin","ghee","saffron","clove","cilantro","turmeric","cinnamon"],
svg:'<path class="f3 sf" d="M34 60q6-14 14-14t-2 18z"/><path class="f3 sf" d="M48 58q6-14 14-14t-2 18z"/><path class="f3 sf" d="M40 72q6-12 13-12t-2 16z"/>'},

{id:"black-rice",cat:"grains",name:{en:"Black rice",fr:"Riz noir"},latin:"Oryza sativa",
origin:{en:"China",fr:"Chine"},season:[],
flavor:["nutty","earthy","sweet","toasty"],
story:{en:"Chinese tradition calls it forbidden rice, reserved for the emperor and denied to everyone else — a story that may be embroidered, but the rarity was real. The colour is anthocyanin, the same pigment as blackcurrant and red cabbage.",
fr:"La tradition chinoise l’appelle riz interdit, réservé à l’empereur et refusé à tous les autres — récit peut-être brodé, mais la rareté était réelle. La couleur vient des anthocyanes, le pigment du cassis et du chou rouge."},
tip:{en:"It bleeds violet into everything it touches. Cook it separately if you want the rest of the plate to keep its colour.",
fr:"Il déteint en violet sur tout ce qu’il touche. Cuisez-le à part si vous voulez que le reste de l’assiette garde sa couleur."},
pairs:["coconut-milk","mango","lime","ginger","sesame","honey","chili","cilantro"],
svg:'<ellipse class="f1 sf" cx="40" cy="54" rx="4.5" ry="9"/><ellipse class="f1 sf" cx="53" cy="52" rx="4.5" ry="9"/><ellipse class="f1 sf" cx="46" cy="67" rx="4.5" ry="9"/>'},

{id:"bomba",cat:"grains",name:{en:"Bomba rice",fr:"Riz bomba"},latin:"Oryza sativa",
origin:{en:"Valencia, Spain",fr:"Valence, Espagne"},season:[],
flavor:["mild","nutty","delicate","sweet"],
story:{en:"It absorbs about three times its volume in liquid while staying separate — the opposite of risotto rice, and exactly what paella needs, since the grains must never be stirred or turn creamy. It is slow to grow and low-yielding, hence the price.",
fr:"Il absorbe environ trois fois son volume de liquide en restant détaché — l’inverse du riz à risotto, et exactement ce qu’exige la paella, dont les grains ne doivent jamais être remués ni crémer. Il pousse lentement et rend peu, d’où son prix."},
tip:{en:"Spread it in a thin layer and do not touch it. The prized socarrat is the crust that forms only if the rice is left alone.",
fr:"Étalez-le en couche mince et n’y touchez pas. Le socarrat, cette croûte convoitée, ne se forme que si le riz est laissé tranquille."},
pairs:["saffron","paprika","shrimp","chicken","olive-oil","piquillo","garlic","green-bean"],
svg:'<ellipse class="f3 sf" cx="40" cy="52" rx="5" ry="8"/><ellipse class="f3 sf" cx="53" cy="50" rx="5" ry="8"/><ellipse class="f3 sf" cx="46" cy="64" rx="5" ry="8"/><ellipse class="f3 sf" cx="58" cy="62" rx="5" ry="8"/>'},

{id:"buckwheat-flour",cat:"grains",name:{en:"Buckwheat flour",fr:"Farine de sarrasin"},latin:"Fagopyrum esculentum",
origin:{en:"Yunnan, China",fr:"Yunnan, Chine"},season:[],
flavor:["earthy","bitter","nutty","toasty"],
story:{en:"Brittany calls it blé noir, black wheat, though it is neither wheat nor a grass — it is a relative of rhubarb and sorrel. It grew where wheat would not, on poor acid soil, which is exactly why Brittany built a cuisine on it.",
fr:"La Bretagne l’appelle blé noir, bien qu’il ne soit ni blé ni graminée — c’est un parent de la rhubarbe et de l’oseille. Il poussait là où le blé refusait, sur des sols pauvres et acides, et c’est précisément pourquoi la Bretagne a bâti une cuisine dessus."},
tip:{en:"It has no gluten, so a galette batter needs resting overnight for the starch to swell and hold together in the pan.",
fr:"Sans gluten, la pâte à galette doit reposer une nuit pour que l’amidon gonfle et tienne à la poêle."},
pairs:["buttermilk","egg","beurre-demi-sel","prosciutto","comte","honey","apple","cider-vinegar"],
svg:'<path class="f1 sf" d="M34 70q0-18 14-24 14 6 14 24z"/><path class="s" d="M40 60q8 4 16 0"/><path class="s" d="M44 50l4-4 4 4"/>'},

{id:"buckwheat",cat:"grains",name:{en:"Buckwheat groats",fr:"Kasha"},latin:"Fagopyrum esculentum",
origin:{en:"Yunnan, China",fr:"Yunnan, Chine"},season:[],
flavor:["earthy","toasty","nutty","bitter"],
story:{en:"Toasted, it becomes kasha, the grain of the Russian and Ashkenazi table, and the toasting is not optional — raw groats cook to a grey mush while toasted ones stay separate and smell of hazelnut.",
fr:"Grillé, il devient le kacha, le grain de la table russe et ashkénaze, et le grillage n’est pas facultatif — les grains crus cuisent en bouillie grise quand les grillés restent détachés et sentent la noisette."},
tip:{en:"Coat the groats in beaten egg and dry them in the pan before adding liquid. That is the classic trick to keep every grain separate.",
fr:"Enrobez les grains d’œuf battu et séchez-les à la poêle avant d’ajouter le liquide. C’est l’astuce classique pour garder chaque grain détaché."},
pairs:["mushroom","onion","butter","egg","parsley","duck-fat","black-pepper","thyme"],
svg:'<path class="f1 sf" d="M40 46l8-14 8 14z"/><path class="f1 sf" d="M32 66l8-14 8 14zM48 66l8-14 8 14z"/>'},

{id:"bulgur",cat:"grains",name:{en:"Bulgur",fr:"Boulgour"},latin:"Triticum durum",
origin:{en:"Levant & Anatolia",fr:"Levant & Anatolie"},season:[],
flavor:["nutty","toasty","earthy","mild"],
story:{en:"Wheat that has been parboiled, dried and cracked — one of the oldest processed foods known, described in Hittite and Babylonian texts. The precooking is why it needs only soaking, which mattered enormously where fuel was scarce.",
fr:"Du blé précuit, séché puis concassé — l’un des plus anciens aliments transformés connus, décrit dans des textes hittites et babyloniens. C’est cette précuisson qui permet un simple trempage, ce qui comptait énormément là où le combustible manquait."},
tip:{en:"Fine bulgur for tabbouleh needs no cooking at all — the lemon juice and tomato water soften it. Boiling it makes porridge.",
fr:"Le boulgour fin du taboulé ne se cuit pas — le jus de citron et l’eau des tomates l’attendrissent. Le faire bouillir donne de la bouillie."},
pairs:["parsley","mint","lemon","tomato","olive-oil","spring-onion","cumin","pomegranate"],
svg:'<path class="f2 sf" d="M32 68q0-16 16-20 16 4 16 20z"/><circle class="dot" cx="41" cy="60" r="1.8"/><circle class="dot" cx="50" cy="57" r="1.8"/><circle class="dot" cx="55" cy="64" r="1.8"/>'},

{id:"carnaroli",cat:"grains",name:{en:"Carnaroli rice",fr:"Riz carnaroli"},latin:"Oryza sativa",
origin:{en:"Piedmont & Lombardy",fr:"Piémont & Lombardie"},season:[],
flavor:["mild","creamy","nutty","delicate"],
story:{en:"Italian cooks call it the king of risotto rices. It carries more amylose than arborio, so the grain holds its shape almost indefinitely while still releasing starch — it is harder to overcook and more expensive for exactly that reason.",
fr:"Les cuisiniers italiens l’appellent le roi des riz à risotto. Il porte plus d’amylose que l’arborio : le grain garde sa forme presque indéfiniment tout en libérant son amidon — plus difficile à surcuire, et plus cher pour cette raison même."},
tip:{en:"Toast the dry grains in fat until they turn translucent at the edges before any liquid goes in. That step sets the texture.",
fr:"Nacrez les grains à sec dans la matière grasse jusqu’à ce que les bords deviennent translucides avant tout liquide. Cette étape fixe la texture."},
pairs:["parmesan","butter","porcini","saffron","shallot","white-wine-vinegar","black-pepper","scallop"],
svg:'<ellipse class="f3 sf" cx="40" cy="50" rx="4.5" ry="10"/><ellipse class="f3 sf" cx="53" cy="52" rx="4.5" ry="10"/><ellipse class="f3 sf" cx="46" cy="66" rx="4.5" ry="10"/>'},

{id:"chestnut-flour",cat:"grains",name:{en:"Chestnut flour",fr:"Farine de châtaigne"},latin:"Castanea sativa",
origin:{en:"Corsica, Tuscany, Ardèche",fr:"Corse, Toscane, Ardèche"},season:[],
flavor:["sweet","nutty","earthy","toasty"],
story:{en:"In Corsica and the Cévennes the chestnut was called the bread tree, and whole mountain populations lived on its flour when no grain would grow at altitude. A failed chestnut harvest meant famine in a way a failed wheat harvest did not.",
fr:"En Corse et dans les Cévennes on appelait le châtaignier l’arbre à pain, et des populations entières de montagne vivaient de sa farine là où aucune céréale ne poussait en altitude. Une récolte de châtaignes manquée signifiait la famine comme une récolte de blé ne le faisait pas."},
tip:{en:"It is naturally sweet, so cut the sugar in any recipe using it. And sift it twice — it clumps more than any other flour.",
fr:"Elle est naturellement sucrée : réduisez le sucre de la recette. Et tamisez-la deux fois — elle s’agglomère plus que toute autre."},
pairs:["chestnut","dark-chocolate","cream","honey","ricotta","rosemary","pine-nut","butter"],
svg:'<path class="f1 sf" d="M34 70q0-18 14-24 14 6 14 24z"/><path class="s" d="M40 62q8 4 16 0"/><path class="f2 sf" d="M44 48q4-6 8 0z"/>'},

{id:"chickpea-flour",cat:"grains",name:{en:"Chickpea flour",fr:"Farine de pois chiche"},latin:"Cicer arietinum",
origin:{en:"India & the Mediterranean",fr:"Inde & Méditerranée"},season:[],
flavor:["nutty","earthy","bitter","mild"],
story:{en:"Nice bakes it into socca and Genoa into farinata — the same batter of flour, water and oil, poured thin and blasted in a fierce oven, claimed by both cities. India has used it as besan far longer than either.",
fr:"Nice en fait la socca et Gênes la farinata — la même pâte de farine, d’eau et d’huile, versée fine et saisie au four brûlant, revendiquée par les deux villes. L’Inde l’emploie sous le nom de besan depuis bien plus longtemps que l’une ou l’autre."},
tip:{en:"Let the batter rest at least an hour so the flour hydrates fully, or the socca tastes raw and chalky in the middle.",
fr:"Laissez reposer la pâte au moins une heure pour que la farine s’hydrate, sinon la socca a un goût cru et crayeux au centre."},
pairs:["olive-oil","black-pepper","rosemary","cumin","onion","chickpeas","turmeric","chili"],
svg:'<path class="f2 sf" d="M34 70q0-18 14-24 14 6 14 24z"/><circle class="f3 sf" cx="44" cy="58" r="4"/><circle class="f3 sf" cx="53" cy="62" r="4"/>'},

{id:"corn",cat:"grains",name:{en:"Corn",fr:"Maïs"},latin:"Zea mays",
origin:{en:"Mexico",fr:"Mexique"},season:[7,8,9],
flavor:["sweet","milky","buttery"],
story:{en:"Nine thousand years ago, Mexican farmers began turning teosinte — a grass with a dozen hard seeds — into cobs of hundreds: the greatest plant-breeding feat in history. They planted it with beans and squash, the “three sisters” who feed each other.",
fr:"Il y a neuf mille ans, des paysans mexicains commencèrent à transformer la téosinte — une herbe à douze graines dures — en épis de plusieurs centaines : le plus grand exploit de sélection végétale de l’histoire. Ils le semaient avec haricots et courges, les « trois sœurs » qui se nourrissent entre elles."},
tip:{en:"Sweetness starts fading the hour it is picked: cook fresh cobs the day you buy them, and scrape the milky pulp from spent cobs into soups.",
fr:"Le sucre décline dès la cueillette : cuisez les épis frais le jour même, et raclez la pulpe laiteuse des épis épuisés dans les soupes."},
pairs:["butter","chili","black-pepper","cream","paprika","quinoa"],
svg:'<path class="f1 sf" d="M42 28h12q4 16 0 34-2 10-6 10t-6-10q-4-18 0-34z"/><path class="s" d="M42 38h12M41 48h14M42 58h12M48 30v40"/><path class="f2 sf" d="M40 30q-8 14-4 34 6-2 6-10zM56 30q8 14 4 34-6-2-6-10z"/>'},

{id:"cornstarch",cat:"grains",name:{en:"Cornstarch",fr:"Maïzena"},latin:"Zea mays",
origin:{en:"New Jersey, 1840s",fr:"New Jersey, années 1840"},season:[],
flavor:["mild","delicate","sweet","milky"],
story:{en:"Invented in 1842 by Thomas Kingsford, who was trying to make starch for laundry rather than food — the culinary use came later and by accident. Its French brand name, Maïzena, has entirely replaced the generic word.",
fr:"Inventée en 1842 par Thomas Kingsford, qui cherchait un amidon pour la blanchisserie plutôt que pour la cuisine — l’usage culinaire vint plus tard et par accident. Son nom de marque français, Maïzena, a entièrement remplacé le mot générique."},
tip:{en:"Slake it in cold liquid first, always. Tipped into anything hot it seizes into lumps that will never dissolve.",
fr:"Délayez-la d’abord au liquide froid, toujours. Jetée dans du chaud, elle prend en grumeaux qui ne se dissoudront jamais."},
pairs:["cream","sugar","vanilla","egg","lemon","cream","dark-chocolate","butter"],
svg:'<path class="f3 sf" d="M36 70q0-16 12-20 12 4 12 20z"/><path class="s" d="M40 62q8 4 16 0"/>'},

{id:"couscous",cat:"grains",name:{en:"Couscous",fr:"Couscous"},latin:"Triticum durum",
origin:{en:"Maghreb",fr:"Maghreb"},season:[],
flavor:["mild","nutty","delicate","toasty"],
story:{en:"Not a grain but a pasta — semolina rolled by hand with water until it clumps into tiny beads, then steamed three separate times over the stew it will be served with. UNESCO listed the practice as shared heritage of four Maghreb nations.",
fr:"Non un grain mais une pâte — de la semoule roulée à la main avec de l’eau jusqu’à former de minuscules perles, puis cuite trois fois à la vapeur au-dessus du ragoût qu’elle accompagnera. L’UNESCO a inscrit cette pratique au patrimoine partagé de quatre nations du Maghreb."},
tip:{en:"Instant couscous rehydrated in a bowl is a different food from steamed. If you have a couscoussier, three steamings is the whole point.",
fr:"Le couscous instantané réhydraté dans un bol est un autre aliment que le couscous vapeur. Si vous avez un couscoussier, les trois passages sont tout l’intérêt."},
pairs:["lamb","harissa","cumin","carrot","chickpeas","preserved-lemon","cilantro","turnip"],
svg:'<path class="f3 sf" d="M30 68q0-18 18-22 18 4 18 22z"/><circle class="dot" cx="40" cy="58" r="1.6"/><circle class="dot" cx="48" cy="55" r="1.6"/><circle class="dot" cx="56" cy="59" r="1.6"/><circle class="dot" cx="44" cy="64" r="1.6"/><circle class="dot" cx="53" cy="64" r="1.6"/>'},

{id:"einkorn",cat:"grains",name:{en:"Einkorn",fr:"Petit épeautre"},latin:"Triticum monococcum",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["nutty","sweet","earthy","mild"],
story:{en:"The oldest cultivated wheat there is — grains were found in the stomach of Ötzi, the man frozen in an Alpine glacier five thousand years ago. Haute Provence still grows it, and it has never been crossbred into anything modern.",
fr:"Le plus ancien blé cultivé — on en a retrouvé des grains dans l’estomac d’Ötzi, l’homme gelé dans un glacier alpin il y a cinq mille ans. La Haute-Provence en cultive encore, et il n’a jamais été croisé avec quoi que ce soit de moderne."},
tip:{en:"Cook the whole grains like rice, in twice their volume of water. As a flour it barely rises — blend it with a stronger one.",
fr:"Cuisez les grains entiers comme du riz, dans deux fois leur volume d’eau. En farine il lève à peine — coupez-le avec une farine plus forte."},
pairs:["olive-oil","thyme","tomato","lamb","honey","almond","mushroom","lemon"],
svg:'<path class="s" d="M48 76V32"/><path class="f2 sf" d="M46 38q-7-3-8 2 7 5 8 0zM50 46q7-3 8 2-7 5-8 0zM46 54q-7-3-8 2 7 5 8 0zM50 62q7-3 8 2-7 5-8 0z"/>'},

{id:"freekeh",cat:"grains",name:{en:"Freekeh",fr:"Freekeh"},latin:"Triticum durum",
origin:{en:"Levant",fr:"Levant"},season:[],
flavor:["smoky","nutty","earthy","toasty"],
story:{en:"Wheat harvested green and set on fire — the high moisture in the young grain stops it burning while the chaff and husk char away. A thirteenth-century Baghdad cookbook already records it, and the smoke is the entire flavour.",
fr:"Du blé récolté vert puis incendié — l’humidité élevée du grain jeune l’empêche de brûler tandis que la balle et l’enveloppe se carbonisent. Un livre de cuisine bagdadien du XIIIe siècle le mentionne déjà, et la fumée fait tout le goût."},
tip:{en:"Rinse it well and pick it over — charred fragments and small stones are common even in good packets.",
fr:"Rincez-le bien et triez-le — fragments carbonisés et petits cailloux sont fréquents même dans de bons paquets."},
pairs:["lamb","yogurt","mint","cumin","pomegranate","olive-oil","almond","cilantro"],
svg:'<path class="f1 sf" d="M32 68q0-16 16-20 16 4 16 20z"/><path class="s" d="M38 52q4-8 10-8t10 8"/><circle class="dot" cx="44" cy="60" r="1.6"/><circle class="dot" cx="53" cy="62" r="1.6"/>'},

{id:"jasmine-rice",cat:"grains",name:{en:"Jasmine rice",fr:"Riz jasmin"},latin:"Oryza sativa",
origin:{en:"Thailand",fr:"Thaïlande"},season:[],
flavor:["floral","sweet","delicate","mild"],
story:{en:"Named for the colour of the milled grain rather than any scent of jasmine — Thai calls it hom mali, fragrant jasmine-white. Unlike basmati it is best fresh from the harvest, and Thai cooks pay attention to the crop year.",
fr:"Nommé pour la couleur du grain usiné plutôt que pour un parfum de jasmin — le thaï dit hom mali, blanc-jasmin parfumé. Contrairement au basmati, il se veut frais de récolte, et les cuisiniers thaïs regardent l’année."},
tip:{en:"Use less water than the packet says, roughly one and a quarter to one. It is stickier than basmati and floods easily.",
fr:"Mettez moins d’eau que le paquet ne l’indique, environ un et quart pour un. Il est plus collant que le basmati et se noie facilement."},
pairs:["coconut-milk","lemongrass","chili","fish-sauce","cilantro","lime","ginger","garlic"],
svg:'<ellipse class="f3 sf" cx="40" cy="54" rx="4" ry="10"/><ellipse class="f3 sf" cx="52" cy="52" rx="4" ry="10"/><ellipse class="f3 sf" cx="46" cy="68" rx="4" ry="10"/>'},

{id:"kuzu",cat:"grains",name:{en:"Kuzu",fr:"Kuzu"},latin:"Pueraria montana",
origin:{en:"Yoshino, Nara",fr:"Yoshino, Nara"},season:[],
flavor:["mild","delicate"],
story:{en:"Yoshino kuzu is made by washing crushed winter-dug root through change after change of cold water for months until nothing but the starch remains, which is why it arrives as chalky lumps and costs what it does. The same vine was shown at the 1876 Philadelphia exhibition, then planted across the American South to hold the soil, and is now the weed that ate the region.",
fr:"Le kuzu de Yoshino s'obtient en lavant la racine d'hiver broyée dans des eaux froides renouvelées pendant des mois, jusqu'à ne laisser que l'amidon : d'où ces morceaux crayeux, et d'où le prix. La même liane fut exposée à Philadelphie en 1876, puis plantée dans tout le Sud américain pour retenir les sols, et c'est aujourd'hui la mauvaise herbe qui a mangé la région."},
tip:{en:"Crush the lumps and dissolve them in cold water before they meet anything hot — kuzu will not disperse in a warm pan. About 2 % by weight gives a pourable sauce, and keep stirring a full minute after it turns clear or it tastes of raw starch.",
fr:"Écrasez les morceaux et dissolvez-les à l'eau froide avant tout contact avec le chaud : le kuzu ne se disperse pas dans une casserole tiède. Environ 2 % du poids donne une sauce nappante, et continuez de remuer une minute pleine après qu'elle est devenue limpide, sinon elle garde un goût d'amidon cru."},
pairs:["adzuki","ginger","kokuto","hon-mirin","kombu","soy-sauce","matcha","sugar"],
svg:'<path class="f1 sf" d="M34 68 30 54l10-8 6 10z"/><path class="f2 sf" d="M46 68 40 56l12-10 8 12z"/><path class="f1 sf" d="M60 68 56 58l10-6 6 10z"/><path class="s" d="M26 70h44"/>'},

{id:"millet",cat:"grains",name:{en:"Millet",fr:"Millet"},latin:"Panicum miliaceum",
origin:{en:"Northern China & the Sahel",fr:"Chine du Nord & Sahel"},season:[],
flavor:["mild","nutty","sweet","earthy"],
story:{en:"It fed northern China before rice reached it and it still feeds much of the Sahel, because it ripens in seventy days and survives drought that destroys everything else. In Europe it fell to birdseed, which is a demotion rather than a verdict.",
fr:"Il nourrissait la Chine du Nord avant l’arrivée du riz et nourrit encore une grande partie du Sahel, parce qu’il mûrit en soixante-dix jours et résiste à des sécheresses qui détruisent tout le reste. En Europe il a été relégué à la graine pour oiseaux, ce qui est une rétrogradation plutôt qu’un jugement."},
tip:{en:"Toast the grains dry in the pan before adding water. Untoasted millet tastes of nothing much at all.",
fr:"Grillez les grains à sec avant d’ajouter l’eau. Non grillé, le millet n’a pour ainsi dire aucun goût."},
pairs:["butter","onion","cumin","carrot","parsley","olive-oil","almond","turmeric"],
svg:'<path class="s" d="M48 76V38"/><circle class="f2 sf" cx="42" cy="42" r="4"/><circle class="f2 sf" cx="54" cy="46" r="4"/><circle class="f2 sf" cx="43" cy="54" r="4"/><circle class="f2 sf" cx="54" cy="58" r="4"/>'},

{id:"oats",cat:"grains",name:{en:"Oats",fr:"Avoine"},latin:"Avena sativa",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["mild","milky","toasty"],
story:{en:"Dr Johnson’s dictionary sneered that oats were “food for horses in England and for men in Scotland” — to which a Scot replied: “That is why England has such fine horses, and Scotland such fine men.” Porridge won the argument.",
fr:"Le dictionnaire du Dr Johnson raillait l’avoine, « nourriture des chevaux en Angleterre et des hommes en Écosse » — ce à quoi un Écossais répondit : « Voilà pourquoi l’Angleterre a de si beaux chevaux, et l’Écosse de si grands hommes. » Le porridge a gagné le débat."},
tip:{en:"A pinch of salt is the difference between wallpaper paste and breakfast. Toast the flakes in butter first and the whole bowl changes class.",
fr:"Une pincée de sel fait la différence entre la colle à papier et le petit-déjeuner. Torréfiez d’abord les flocons au beurre et tout le bol change de classe."},
pairs:["honey","apple","cinnamon","cream","raspberry","maple-syrup"],
svg:'<path class="s" d="M48 78q-2-26 0-46"/><path class="f2 sf" d="M46 38q-8-4-8-12 8 0 10 8zM50 38q8-4 8-12-8 0-10 8zM44 52q-8-4-8-12 8 0 10 8zM52 52q8-4 8-12-8 0-10 8z"/>'},

{id:"potato-starch",cat:"grains",name:{en:"Potato starch",fr:"Fécule de pomme de terre"},latin:"Solanum tuberosum",
origin:{en:"Northern Europe",fr:"Europe du Nord"},season:[],
flavor:["mild","delicate","milky","earthy"],
story:{en:"It thickens at a lower temperature than cornstarch and gives a clear, glossy result rather than a cloudy one — which is why it belongs in fruit glazes and clear sauces where cornstarch would look chalky.",
fr:"Elle épaissit à plus basse température que la maïzena et donne un résultat clair et brillant plutôt que trouble — d’où sa place dans les nappages de fruits et les sauces claires où la maïzena paraîtrait crayeuse."},
tip:{en:"Never boil it hard. Unlike cornstarch it breaks down and thins again if held at a rolling boil.",
fr:"Ne la faites jamais bouillir fort. Contrairement à la maïzena, elle se dégrade et redevient liquide si on la maintient à gros bouillons."},
pairs:["lemon","cream","egg","sugar","vanilla","apple","butter","raspberry"],
svg:'<path class="f3 sf" d="M36 70q0-16 12-20 12 4 12 20z"/><circle class="dot" cx="43" cy="60" r="1.5"/><circle class="dot" cx="52" cy="62" r="1.5"/>'},

{id:"quinoa",cat:"grains",name:{en:"Quinoa",fr:"Quinoa"},latin:"Chenopodium quinoa",
origin:{en:"Andean altiplano",fr:"Altiplano andin"},season:[],
flavor:["nutty","earthy","mild"],
story:{en:"The Incas called it chisaya mama — “mother of all grains” — and the emperor sowed the first seeds each year with a golden spade. Technically a seed cousin of spinach, it grows at altitudes where wheat gives up.",
fr:"Les Incas l’appelaient chisaya mama — « mère de toutes les graines » — et l’empereur en semait les premières chaque année avec une bêche d’or. Techniquement une graine cousine de l’épinard, elle pousse à des altitudes où le blé renonce."},
tip:{en:"Rinse it well — its natural coating is bitter — and toast it dry before adding water for a nuttier result.",
fr:"Rincez-le bien — son enrobage naturel est amer — et torréfiez-le à sec avant d’ajouter l’eau pour un goût plus noisetté."},
pairs:["lemon","corn","cilantro","pomegranate","beetroot","yogurt"],
svg:'<path class="dot" d="M40 44a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M51 44a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M35 53a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M45.5 53a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M56 53a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M40 62a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M51 62a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0"/><circle class="s" cx="48" cy="53" r="21"/>'},

{id:"rice",cat:"grains",name:{en:"Rice",fr:"Riz"},latin:"Oryza sativa",
origin:{en:"Yangtze valley, China",fr:"Vallée du Yangzi, Chine"},season:[],
flavor:["mild","sweet","milky"],
story:{en:"Domesticated some ten thousand years ago, rice now feeds half of humanity every single day. In Japanese, the word for cooked rice — gohan — is simply the word for “meal”: the grain and the act of eating are the same idea.",
fr:"Domestiqué il y a environ dix mille ans, le riz nourrit aujourd’hui la moitié de l’humanité chaque jour. En japonais, le mot pour le riz cuit — gohan — est tout simplement celui du « repas » : le grain et l’acte de manger sont une seule idée."},
tip:{en:"Rinse until the water runs clear for distinct grains; skip the rinse when you want creaminess, as in risotto or rice pudding.",
fr:"Rincez jusqu’à l’eau claire pour des grains détachés ; ne rincez pas quand vous cherchez le crémeux, comme pour un risotto ou un riz au lait."},
pairs:["saffron","shiitake","soy-sauce","coconut-milk","egg","sesame","turmeric"],
svg:'<path class="f1 sf" d="M30 54h36q0 16-18 16t-18-16z"/><path class="f2 sf" d="M38 50q-2-7 3-9 4 3 2 9zM47 48q-2-7 3-9 4 3 2 9zM56 50q-2-7 3-9 4 3 2 9z"/>'},

{id:"rye",cat:"grains",name:{en:"Rye berries",fr:"Grains de seigle"},latin:"Secale cereale",
origin:{en:"Anatolia",fr:"Anatolie"},season:[],
flavor:["earthy","nutty","sour","toasty"],
story:{en:"Rye began as a weed growing among wheat and barley, and it was domesticated almost by accident — as farming pushed north into colder ground, the weed survived where the crop failed, and farmers simply kept what was left.",
fr:"Le seigle a commencé comme une mauvaise herbe dans le blé et l’orge, et il fut domestiqué presque par accident — à mesure que l’agriculture montait vers le nord et le froid, l’adventice survivait là où la culture échouait, et les paysans gardaient simplement ce qui restait."},
tip:{en:"Soak the berries overnight before cooking. Without it they take well over an hour and stay stubbornly hard in the centre.",
fr:"Faites tremper les grains une nuit avant cuisson. Sans cela ils prennent plus d’une heure et restent obstinément durs au centre."},
pairs:["mushroom","butter","onion","thyme","caraway","beetroot","dill","walnut"],
svg:'<path class="s" d="M48 76V32"/><path class="f1 sf" d="M46 38q-8-4-9 1 8 6 9 0zM50 48q8-4 9 1-8 6-9 0zM46 58q-8-4-9 1 8 6 9 0z"/>'},

{id:"rye-flour",cat:"grains",name:{en:"Rye flour",fr:"Farine de seigle"},latin:"Secale cereale",
origin:{en:"Anatolia & Central Europe",fr:"Anatolie & Europe centrale"},season:[],
flavor:["earthy","sour","bitter","toasty"],
story:{en:"Rye tolerates cold and poor soil that would kill wheat, which is why northern and eastern Europe built their bread on it. Damp rye can carry ergot, a fungus whose effects are blamed for medieval outbreaks of mass hallucination.",
fr:"Le seigle supporte le froid et les sols pauvres qui tueraient le blé, d’où le pain de l’Europe du Nord et de l’Est. Le seigle humide peut porter l’ergot, un champignon dont les effets sont mis en cause dans les épisodes médiévaux d’hallucinations collectives."},
tip:{en:"Its gluten is weak and its pentosans make dough sticky. Wet your hands rather than adding flour, or you will make a brick.",
fr:"Son gluten est faible et ses pentosanes rendent la pâte collante. Mouillez-vous les mains plutôt que d’ajouter de la farine, sinon vous ferez une brique."},
pairs:["caraway","honey","butter","salmon","flour-t65","walnut","beurre-demi-sel","juniper"],
svg:'<path class="f1 sf" d="M32 72q0-22 16-30 16 8 16 30z"/><path class="s" d="M38 62q10 4 20 0M42 52q6 3 12 0"/><circle class="dot" cx="48" cy="68" r="1.6"/>'},

{id:"semolina",cat:"grains",name:{en:"Semolina",fr:"Semoule"},latin:"Triticum durum",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["nutty","sweet","toasty","mild"],
story:{en:"Milled from durum, a different and much harder wheat than the bread species — hard enough that its granules stay separate rather than forming a paste. That hardness is why dried pasta holds its shape in boiling water and why couscous rolls into grains.",
fr:"Moulue à partir du blé dur, une espèce différente et bien plus dure que le blé tendre — assez dure pour que ses grains restent séparés au lieu de former une pâte. C’est cette dureté qui fait tenir les pâtes sèches à l’eau bouillante et qui permet de rouler la semoule en couscous."},
tip:{en:"A scattering on the peel stops a pizza sticking better than flour, because the granules act as ball bearings.",
fr:"Une pincée sur la pelle empêche une pizza de coller mieux que la farine, les grains agissant comme des roulements."},
pairs:["olive-oil","egg","butter","honey","orange","almond","pistachio","cinnamon"],
svg:'<path class="f2 sf" d="M34 70q0-18 14-24 14 6 14 24z"/><circle class="dot" cx="42" cy="58" r="1.8"/><circle class="dot" cx="50" cy="55" r="1.8"/><circle class="dot" cx="54" cy="63" r="1.8"/><circle class="dot" cx="45" cy="65" r="1.8"/>'},

{id:"sorghum",cat:"grains",name:{en:"Sorghum",fr:"Sorgho"},latin:"Sorghum bicolor",
origin:{en:"Northeast Africa",fr:"Afrique du Nord-Est"},season:[],
flavor:["mild","earthy","sweet","nutty"],
story:{en:"The fifth most important cereal on Earth and almost unknown on European tables. Domesticated in Sudan some six thousand years ago, it will crop on rainfall that would kill maize, which is why half of Africa depends on it.",
fr:"La cinquième céréale mondiale, et presque inconnue des tables européennes. Domestiqué au Soudan il y a quelque six mille ans, il produit avec des pluies qui tueraient le maïs, d’où la dépendance de la moitié de l’Afrique."},
tip:{en:"The whole grains pop like tiny popcorn in a dry pan. It is the fastest way to see what it actually tastes of.",
fr:"Les grains entiers éclatent comme un minuscule pop-corn dans une poêle sèche. C’est le moyen le plus rapide de découvrir son vrai goût."},
pairs:["peanut","chili","onion","tomato","cilantro","lime","garlic","cumin"],
svg:'<path class="s" d="M48 76V40"/><path class="f1 sf" d="M48 26q-12 6-10 18 10 4 12-6zM48 26q12 6 10 18-10 4-12-6z"/>'},

{id:"spelt",cat:"grains",name:{en:"Spelt",fr:"Épeautre"},latin:"Triticum spelta",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["nutty","sweet","earthy","toasty"],
story:{en:"An ancient wheat that fell out of use because its tough husk has to be removed in a separate milling step — pure inefficiency in an industrial age. Hildegard of Bingen wrote about it in the twelfth century and it came back on her reputation.",
fr:"Un blé ancien tombé en désuétude parce que sa balle coriace exige une étape de mouture supplémentaire — pure inefficacité à l’ère industrielle. Hildegarde de Bingen en parlait au XIIe siècle, et il est revenu porté par sa réputation."},
tip:{en:"It has gluten, but a fragile kind. Knead it less than wheat and stop as soon as the dough comes together.",
fr:"Il contient du gluten, mais fragile. Pétrissez-le moins que le blé et arrêtez dès que la pâte se rassemble."},
pairs:["honey","walnut","mushroom","butter","thyme","comte","onion","hazelnut"],
svg:'<path class="s" d="M48 76V34"/><path class="f2 sf" d="M46 40q-8-4-10 2 8 6 10 0zM50 48q8-4 10 2-8 6-10 0zM46 56q-8-4-10 2 8 6 10 0z"/>'},

{id:"flour-t45",cat:"grains",name:{en:"T45 flour",fr:"Farine T45"},latin:"Triticum aestivum",
origin:{en:"France",fr:"France"},season:[],
flavor:["mild","sweet","delicate","toasty"],
story:{en:"The French T number counts ash left after burning a hundred grams of flour — T45 leaves 0.45%, meaning almost no bran. It is the whitest, finest flour milled, and the reason a croissant can be laminated into hundreds of leaves without tearing.",
fr:"Le chiffre T français mesure les cendres restant après combustion de cent grammes de farine — T45 en laisse 0,45 %, soit presque pas de son. C’est la farine la plus blanche et la plus fine, et la raison pour laquelle un croissant se feuillette en centaines de couches sans se déchirer."},
tip:{en:"Use it for viennoiserie and delicate cakes, never for bread — it has too little protein to build a proper gluten network.",
fr:"Réservez-la à la viennoiserie et aux gâteaux délicats, jamais au pain — elle a trop peu de protéines pour bâtir un vrai réseau de gluten."},
pairs:["butter","egg","cream","sugar","vanilla","beurre-de-baratte","cream","almond"],
svg:'<path class="f3 sf" d="M32 72q0-22 16-30 16 8 16 30z"/><path class="s" d="M40 60q8 4 16 0"/><circle class="dot" cx="44" cy="52" r="1.4"/><circle class="dot" cx="53" cy="55" r="1.4"/>'},

{id:"flour-t55",cat:"grains",name:{en:"T55 flour",fr:"Farine T55"},latin:"Triticum aestivum",
origin:{en:"France",fr:"France"},season:[],
flavor:["mild","toasty","sweet","nutty"],
story:{en:"The default flour of a French kitchen and the closest thing to Anglo-American all-purpose, though not identical — French wheat is generally softer and lower in protein. Most home recipes that simply say farine mean this.",
fr:"La farine par défaut de la cuisine française et l’équivalent le plus proche de l’all-purpose anglo-américaine, sans lui être identique — le blé français est généralement plus tendre et moins protéiné. La plupart des recettes qui disent simplement farine parlent de celle-ci."},
tip:{en:"It is the compromise flour: adequate for pastry, adequate for bread, ideal for neither. Keep it for tarts, sauces and pancakes.",
fr:"C’est la farine de compromis : correcte en pâtisserie, correcte en panification, idéale nulle part. Gardez-la pour les tartes, les sauces et les crêpes."},
pairs:["butter","egg","cream","sugar","salt","yeast","vanilla","cream"],
svg:'<path class="f3 sf" d="M32 72q0-22 16-30 16 8 16 30z"/><path class="s" d="M38 62q10 4 20 0M42 52q6 3 12 0"/>'},

{id:"flour-t65",cat:"grains",name:{en:"T65 bread flour",fr:"Farine T65"},latin:"Triticum aestivum",
origin:{en:"France",fr:"France"},season:[],
flavor:["toasty","nutty","earthy","mild"],
story:{en:"The legal flour of the baguette de tradition française, a 1993 decree that fixed what a real baguette may contain: flour, water, salt, yeast and nothing else — no additives, no freezing. The law was written to stop the industrial loaf.",
fr:"La farine légale de la baguette de tradition française, un décret de 1993 qui fixa ce qu’une vraie baguette peut contenir : farine, eau, sel, levure et rien d’autre — ni additif, ni surgélation. La loi fut écrite pour arrêter le pain industriel."},
tip:{en:"Its extra bran feeds fermentation, so doughs rise faster and taste more. Hold back a little water at first — it drinks less than it looks.",
fr:"Son son supplémentaire nourrit la fermentation : les pâtes lèvent plus vite et ont plus de goût. Retenez un peu d’eau au départ — elle en boit moins qu’il n’y paraît."},
pairs:["yeast","salt","butter","olive-oil","rye-flour","walnut","honey","beurre-demi-sel"],
svg:'<path class="f2 sf" d="M32 72q0-22 16-30 16 8 16 30z"/><path class="s" d="M38 62q10 4 20 0"/><circle class="dot" cx="42" cy="54" r="1.6"/><circle class="dot" cx="54" cy="57" r="1.6"/>'},

{id:"flour-complete",cat:"grains",name:{en:"Wholemeal flour",fr:"Farine complète"},latin:"Triticum aestivum",
origin:{en:"Everywhere wheat grows",fr:"Partout où pousse le blé"},season:[],
flavor:["earthy","nutty","bitter","toasty"],
story:{en:"White flour was a luxury for most of history precisely because removing the bran is work. Then the roller mill arrived in the 1870s, white bread became cheap, and within fifty years wholemeal had been reinvented as the expensive, healthy one.",
fr:"La farine blanche fut longtemps un luxe précisément parce qu’ôter le son demande du travail. Puis vint le moulin à cylindres dans les années 1870, le pain blanc devint bon marché, et en cinquante ans la farine complète fut réinventée en produit cher et sain."},
tip:{en:"The bran cuts gluten strands like tiny blades. Rest the dough half an hour before kneading and it hydrates enough to stop tearing.",
fr:"Le son coupe les brins de gluten comme de petites lames. Laissez la pâte reposer une demi-heure avant pétrissage : elle s’hydrate et cesse de se déchirer."},
pairs:["honey","walnut","butter","rye-flour","sesame","olive-oil","yeast","raisin"],
svg:'<path class="f1 sf" d="M32 72q0-22 16-30 16 8 16 30z"/><circle class="dot" cx="41" cy="56" r="1.6"/><circle class="dot" cx="50" cy="52" r="1.6"/><circle class="dot" cx="55" cy="62" r="1.6"/><circle class="dot" cx="44" cy="66" r="1.6"/>'},

{id:"wild-rice",cat:"grains",name:{en:"Wild rice",fr:"Riz sauvage"},latin:"Zizania palustris",
origin:{en:"Great Lakes, North America",fr:"Grands Lacs, Amérique du Nord"},season:[],
flavor:["nutty","toasty","earthy","smoky"],
story:{en:"Not rice at all but an aquatic grass, and it is sacred to the Anishinaabe, who call it manoomin and still harvest it from canoes by knocking the grain into the boat with wooden sticks — a method protected by treaty.",
fr:"Pas du riz mais une graminée aquatique, sacrée pour les Anishinaabe, qui l’appellent manoomin et la récoltent encore en canoë en faisant tomber le grain dans l’embarcation à l’aide de bâtons de bois — une méthode protégée par traité."},
tip:{en:"It takes forty-five minutes and is ready when the grains split open and curl. Undercooked it is simply inedible.",
fr:"Il demande quarante-cinq minutes et il est prêt quand les grains s’ouvrent et s’enroulent. Insuffisamment cuit, il est simplement immangeable."},
pairs:["mushroom","hazelnut","cranberry","butter","thyme","duck","onion","walnut"],
svg:'<path class="f1 sf" d="M36 30q4 26 0 44M44 26q4 28 0 48M52 30q4 26 0 44M60 34q3 22 0 38"/>'}
]);
