window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"ajwain",cat:"spices",name:{en:"Ajwain",fr:"Ajowan"},latin:"Trachyspermum ammi",
origin:{en:"India & Iran",fr:"Inde & Iran"},season:[],
flavor:["herbal","bitter","hot","pungent"],
story:{en:"It tastes overwhelmingly of thyme, because it contains the same compound — thymol — at a far higher concentration than thyme itself. Indian cooks use it in fried doughs and lentil dishes, traditionally because it is thought to settle the stomach.",
fr:"Il a un goût massif de thym, parce qu’il contient le même composé — le thymol — à une concentration bien supérieure à celle du thym lui-même. Les cuisiniers indiens l’emploient dans les pâtes frites et les plats de lentilles, traditionnellement parce qu’on lui prête des vertus digestives."},
tip:{en:"Crush it between your palms as it goes in. A tiny amount is enough — used generously it takes over everything.",
fr:"Écrasez-le entre les paumes au moment de l’ajouter. Une toute petite quantité suffit — généreusement dosé il prend le dessus sur tout."},
pairs:["chickpea-flour","potato","red-lentil","ghee","turmeric","cumin","chili","garlic"],
svg:'<path class="f1 sf" d="M40 48q4 10 0 18M48 46q4 11 0 20M56 48q4 10 0 18"/><circle class="dot" cx="40" cy="57" r="1.2"/><circle class="dot" cx="48" cy="56" r="1.2"/>'},

{id:"allspice",cat:"spices",name:{en:"Allspice",fr:"Piment de la Jamaïque"},latin:"Pimenta dioica",
origin:{en:"Jamaica",fr:"Jamaïque"},season:[],
flavor:["warm","woody","sweet","peppery"],
story:{en:"One berry that tastes convincingly of clove, cinnamon, nutmeg and pepper at once — hence the English name. Columbus was looking for black pepper when he found it, which is why the Spanish still call it pimienta.",
fr:"Une baie qui a de façon convaincante le goût du clou de girofle, de la cannelle, de la muscade et du poivre à la fois — d’où son nom anglais. Colomb cherchait du poivre noir quand il la trouva, et c’est pourquoi les Espagnols l’appellent encore pimienta."},
tip:{en:"It is the backbone of jerk and of most Caribbean marinades. Use the whole berries in braises and grind only what you need.",
fr:"C’est l’ossature du jerk et de la plupart des marinades caraïbes. Employez les baies entières dans les braisés et ne moulez que le nécessaire."},
pairs:["thyme","chili","clove","ginger","pork","cinnamon","onion","black-pepper"],
svg:'<circle class="f1 sf" cx="42" cy="52" r="8"/><circle class="f1 sf" cx="57" cy="57" r="8"/><circle class="f1 sf" cx="46" cy="67" r="7"/><path class="s" d="M42 44v-5M57 49v-5"/>'},

{id:"anise",cat:"spices",name:{en:"Anise",fr:"Anis vert"},latin:"Pimpinella anisum",
origin:{en:"Eastern Mediterranean",fr:"Méditerranée orientale"},season:[],
flavor:["anise","sweet","floral","warm"],
story:{en:"The flavour of pastis, ouzo, raki and sambuca — and the reason they all turn cloudy with water. Anethole dissolves in alcohol but not in water, so adding water forces it out of solution as microscopic droplets. The cloud is chemistry, not a trick.",
fr:"Le goût du pastis, de l’ouzo, du raki et de la sambuca — et la raison pour laquelle ils se troublent à l’eau. L’anéthol se dissout dans l’alcool mais pas dans l’eau : ajouter de l’eau le fait sortir de solution en gouttelettes microscopiques. Le trouble est de la chimie, non un tour de main."},
tip:{en:"Do not swap it for star anise. They share a compound but not a profile — anise is lighter and sweeter, star anise darker and more medicinal.",
fr:"Ne le remplacez pas par la badiane. Ils partagent un composé mais pas un profil — l’anis vert est plus léger et plus sucré, la badiane plus sombre et plus médicinale."},
pairs:["fennel","orange","honey","fig","star-anise","almond","carrot","flour-t55"],
svg:'<path class="f3 sf" d="M42 48q5 10 0 18M52 46q5 11 0 20"/><path class="s" d="M40 54h6M50 54h6"/><path class="s" d="M47 40q0-8 2-10"/>'},

{id:"avocado-leaf",cat:"spices",name:{en:"Avocado leaf",fr:"Feuille d’avocatier"},latin:"Persea americana var. drymifolia",
origin:{en:"Highlands of Michoacán, Mexico",fr:"Hauts plateaux du Michoacán, Mexique"},season:[],
flavor:["anise","nutty","toasty"],
story:{en:"Only the Mexican race of avocado has a scented leaf; crush a West Indian one and it smells of nothing at all. The compound responsible is estragole, the same molecule that makes tarragon taste of tarragon, and it is why a pot of black beans in Oaxaca tastes unlike a pot of black beans anywhere else.",
fr:"Seule la race mexicaine de l’avocatier a la feuille odorante : froissez celle d’un avocatier antillais, elle ne sent rien. La molécule responsable est l’estragole, celle-là même qui fait le goût de l’estragon, et c’est ce qui distingue une marmite de haricots noirs d’Oaxaca de toute autre."},
tip:{en:"Toast the dry leaf on a bare pan, ten seconds a side, until it smells of hazelnut, then drop it in whole and fish it out before serving. Untoasted it tastes of hay; a few seconds too long and it tastes of ash.",
fr:"Grillez la feuille sèche à sec, dix secondes par face, jusqu’à l’odeur de noisette, puis jetez-la entière dans la marmite et retirez-la avant de servir. Non grillée, elle a un goût de foin ; quelques secondes de trop, un goût de cendre."},
pairs:["black-bean","chili","pork","corn","tomato","lime"],
svg:'<path class="f2 sf" d="M48 18c14 13 16 35 0 55-16-20-14-42 0-55z"/><path class="s" d="M48 22v50"/><path class="s" d="M48 34 37 30M48 45 35 42M48 56l-11-1M48 34l11-4M48 45l13-3M48 56l11-1"/><path class="f3 sf" d="M46 73h4v9h-4z"/>'},

{id:"black-pepper",cat:"spices",name:{en:"Black pepper",fr:"Poivre noir"},latin:"Piper nigrum",
origin:{en:"Malabar coast, India",fr:"Côte de Malabar, Inde"},season:[],
flavor:["hot","woody","warm"],
story:{en:"Medieval Europe paid rents, dowries and ransoms in peppercorns — “peppercorn rent” survives in English law. Vasco da Gama sailed around Africa chasing this berry; whole cities, from Venice to Lisbon, grew rich on its trail.",
fr:"L’Europe médiévale payait loyers, dots et rançons en grains de poivre. Vasco de Gama contourna l’Afrique à la poursuite de cette baie ; des villes entières, de Venise à Lisbonne, s’enrichirent sur son sillage."},
tip:{en:"Grind it at the last moment — pre-ground pepper is mostly dust and regret. Try it on strawberries: it works.",
fr:"Moulez-le au dernier moment — le poivre pré-moulu n’est que poussière et regret. Essayez-le sur des fraises : ça fonctionne."},
pairs:["strawberry","beef","egg","lemon","parmesan","oyster"],
svg:'<circle class="f3 sf" cx="38" cy="50" r="8"/><circle class="f3 sf" cx="58" cy="46" r="8"/><circle class="f3 sf" cx="48" cy="64" r="8"/><path class="s" d="M35 47l6 6M55 43l6 6M45 61l6 6"/>'},

{id:"caraway",cat:"spices",name:{en:"Caraway",fr:"Carvi"},latin:"Carum carvi",
origin:{en:"Europe & Western Asia",fr:"Europe & Asie occidentale"},season:[],
flavor:["anise","earthy","warm","bitter"],
story:{en:"Constantly confused with cumin, and in several languages the two names are almost identical — which has caused centuries of recipe mistranslation. Caraway is the sharper, more anise one, and it is the seed in rye bread and in every sauerkraut worth eating.",
fr:"Constamment confondu avec le cumin, et dans plusieurs langues les deux noms sont presque identiques — d’où des siècles de recettes mal traduites. Le carvi est le plus vif, le plus anisé, et c’est la graine du pain de seigle et de toute choucroute qui vaille."},
tip:{en:"It is the missing note in most home harissa and in cabbage dishes that taste flat. A pinch changes both completely.",
fr:"C’est la note manquante de la plupart des harissas maison et des plats de chou qui semblent plats. Une pincée change tout."},
pairs:["cabbage","rye-flour","sauerkraut","pork","munster","potato","harissa","onion"],
svg:'<path class="f1 sf" d="M40 44q6 12 0 24M50 42q6 14 0 26"/><path class="s" d="M38 56h5M48 56h5"/><path class="s" d="M58 48q4 8 0 16"/>'},

{id:"cardamom",cat:"spices",name:{en:"Cardamom",fr:"Cardamome"},latin:"Elettaria cardamomum",
origin:{en:"Western Ghats, India",fr:"Ghats occidentaux, Inde"},season:[],
flavor:["floral","citrus","warm","fresh"],
story:{en:"The “queen of spices” grew in Indian rainforests, but Vikings met it in the markets of Constantinople and carried it north — which is why, a thousand years later, Scandinavia bakes with more cardamom per person than anywhere outside Asia.",
fr:"La « reine des épices » poussait dans les forêts humides de l’Inde, mais les Vikings la découvrirent sur les marchés de Constantinople et l’emportèrent vers le nord — voilà pourquoi, mille ans plus tard, la Scandinavie pâtisse avec plus de cardamome par habitant que partout hors d’Asie."},
tip:{en:"Crush the green pods to free the black seeds; grind those only. In coffee, a single crushed pod is a small journey.",
fr:"Écrasez les gousses vertes pour libérer les graines noires ; ne moulez que celles-ci. Dans le café, une seule gousse écrasée est un petit voyage."},
pairs:["coffee","orange","honey","rice","dark-chocolate","cinnamon","saffron"],
svg:'<path class="f1 sf" d="M34 44q0-10 7-10t7 10q0 12-7 16-7-4-7-16z" transform="rotate(-16 41 48)"/><path class="f1 sf" d="M50 46q0-10 7-10t7 10q0 12-7 16-7-4-7-16z" transform="rotate(12 57 50)"/><path class="dot" d="M39 46a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0M55 50a1.5 1.5 0 103 0 1.5 1.5 0 10-3 0"/>'},

{id:"cassia",cat:"spices",name:{en:"Cassia",fr:"Cannelle de Chine"},latin:"Cinnamomum cassia",
origin:{en:"Southern China",fr:"Chine du Sud"},season:[],
flavor:["sweet","warm","woody","hot"],
story:{en:"Most of what is sold as cinnamon in the world is actually cassia — thicker, harder, redder bark from a different tree, and much stronger. True Ceylon cinnamon is pale, brittle and layered like a cigar; cassia curls into a single thick scroll.",
fr:"L’essentiel de ce qui se vend comme cannelle dans le monde est en réalité de la casse — écorce plus épaisse, plus dure et plus rouge, d’un autre arbre, et bien plus puissante. La vraie cannelle de Ceylan est pâle, cassante et feuilletée comme un cigare ; la casse s’enroule en un unique rouleau épais."},
tip:{en:"It stands up to long braising where Ceylon cinnamon fades. Use it in savoury stews and Ceylon in delicate pastry.",
fr:"Elle tient au braisage long là où la cannelle de Ceylan s’efface. Réservez-la aux ragoûts et la Ceylan à la pâtisserie délicate."},
pairs:["star-anise","clove","beef","orange","soy-sauce","ginger","sugar","black-pepper"],
svg:'<path class="f1 sf" d="M36 30q14 0 14 24t-14 22q6-22 0-46z"/><path class="s" d="M50 34q10 6 10 20t-10 20"/>'},

{id:"celery-seed",cat:"spices",name:{en:"Celery seed",fr:"Graine de céleri"},latin:"Apium graveolens",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["bitter","earthy","herbal","warm"],
story:{en:"It comes from smallage, the wild ancestor of celery, and it is startlingly concentrated — a quarter-teaspoon carries more celery flavour than a whole stick. Ground with salt it becomes celery salt, which is the entire argument of a Bloody Mary.",
fr:"Elle vient de l’ache, l’ancêtre sauvage du céleri, et sa concentration surprend — un quart de cuillère à café porte plus de goût de céleri qu’une branche entière. Broyée avec du sel elle devient le sel de céleri, qui fait tout l’argument d’un Bloody Mary."},
tip:{en:"It turns bitter fast if you overdo it. Start with half what you think, especially in a coleslaw or a court-bouillon.",
fr:"Elle vire vite à l’amer si l’on force. Commencez par la moitié de ce que vous imaginez, surtout dans une rémoulade ou un court-bouillon."},
pairs:["tomato","celery","black-pepper","salt","cabbage","potato","onion","cider-vinegar"],
svg:'<path class="f2 sf" d="M42 50q3 8 0 14M50 48q3 9 0 16M58 52q3 7 0 12"/><path class="s" d="M40 56h5M48 56h5M56 57h5"/>'},

{id:"chili",cat:"spices",name:{en:"Chili pepper",fr:"Piment"},latin:"Capsicum spp.",
origin:{en:"Mexico & South America",fr:"Mexique & Amérique du Sud"},season:[7,8,9,10],
flavor:["hot","fruity","smoky"],
story:{en:"Columbus, hunting black pepper, found this instead and stubbornly called it “pepper”. Within a single century, Portuguese ships had planted it from West Africa to India to Thailand — the fastest conquest in food history, by a fruit pretending to burn you.",
fr:"Colomb, en quête de poivre noir, trouva ceci à la place et s’obstina à l’appeler « poivre ». En un seul siècle, les navires portugais l’avaient semé de l’Afrique de l’Ouest à l’Inde et au Siam — la conquête la plus rapide de l’histoire alimentaire, par un fruit qui fait semblant de vous brûler."},
tip:{en:"The heat lives in the white pith, not the seeds. Milk and yogurt douse the fire; water only spreads it.",
fr:"Le feu loge dans la membrane blanche, pas dans les graines. Le lait et le yaourt éteignent l’incendie ; l’eau ne fait que l’attiser."},
pairs:["dark-chocolate","mango","garlic","corn","coconut-milk","cilantro","peanut"],
svg:'<path class="f2 sf" d="M60 30q4 22-10 36-8 8-16 4 4-2 8-8 10-16 12-32z"/><path class="s" d="M60 30q2-6 8-6"/>'},

{id:"cinnamon",cat:"spices",name:{en:"Cinnamon",fr:"Cannelle"},latin:"Cinnamomum verum",
origin:{en:"Sri Lanka",fr:"Sri Lanka"},season:[],
flavor:["sweet","warm","woody"],
story:{en:"Herodotus reported that giant birds built nests of cinnamon sticks on cliffs, and harvesters tricked them into dropping it — a tall tale spice merchants encouraged to guard their sources. The truth was quieter: the rolled inner bark of a Sri Lankan tree.",
fr:"Hérodote racontait que des oiseaux géants bâtissaient des nids de bâtons de cannelle au sommet des falaises, et qu’on les ruse pour les faire tomber — une fable que les marchands d’épices entretenaient pour protéger leurs sources. La vérité était plus discrète : l’écorce intérieure roulée d’un arbre de Ceylan."},
tip:{en:"True Ceylon cinnamon is soft and layered like a cigar; cassia is harder and louder. Bloom either in warm butter or oil to open the perfume.",
fr:"La vraie cannelle de Ceylan est souple, feuilletée comme un cigare ; la casse est plus dure et plus criarde. Réveillez l’une ou l’autre dans un beurre ou une huile tiède."},
pairs:["apple","orange","honey","dark-chocolate","coffee","lamb","rice","pear"],
svg:'<rect class="f2 sf" x="28" y="42" width="40" height="10" rx="5" transform="rotate(-18 48 47)"/><rect class="f2 sf" x="28" y="56" width="40" height="10" rx="5" transform="rotate(-18 48 61)"/><path class="s" d="M32 44a3 3 0 106 2M32 58a3 3 0 106 2" transform="rotate(-18 48 52)"/>'},

{id:"clove",cat:"spices",name:{en:"Clove",fr:"Clou de girofle"},latin:"Syzygium aromaticum",
origin:{en:"Maluku Islands, Indonesia",fr:"Îles Moluques, Indonésie"},season:[],
flavor:["warm","pungent","sweet","woody"],
story:{en:"Chinese courtiers of the Han dynasty held cloves in their mouths before addressing the emperor, so their breath would be worthy. On Ternate, islanders planted a clove tree for each newborn child — the tree and the child grew together.",
fr:"Les courtisans chinois de la dynastie Han gardaient un clou de girofle en bouche avant de s’adresser à l’empereur, pour que leur haleine en soit digne. À Ternate, on plantait un giroflier à chaque naissance — l’arbre et l’enfant grandissaient ensemble."},
tip:{en:"An onion studded with two or three cloves, dropped into a broth or béchamel, is the old French trick for depth without visible spice.",
fr:"Un oignon piqué de deux ou trois clous, plongé dans un bouillon ou une béchamel, est la vieille astuce française pour donner du fond sans épice visible."},
pairs:["onion","apple","orange","pork","rice","honey"],
svg:'<path class="f3 sf" d="M44 30l8 0-2 26h-4z" transform="rotate(-18 48 44)"/><path class="f3 sf" d="M36 38a5 5 0 108-4z" transform="rotate(-18 48 44)"/><path class="f3 sf" d="M56 44l8 0-2 26h-4z" transform="rotate(14 62 58)"/><path class="f3 sf" d="M50 52a5 5 0 108-4z" transform="rotate(14 62 58)"/>'},

{id:"coriander-seed",cat:"spices",name:{en:"Coriander seed",fr:"Graine de coriandre"},latin:"Coriandrum sativum",
origin:{en:"Southern Europe & Near East",fr:"Europe du Sud & Proche-Orient"},season:[],
flavor:["citrus","warm","floral","nutty"],
story:{en:"The seed and the leaf come from one plant and taste nothing alike — the leaf is soapy and green, the seed warm and orange-peel sweet. Seeds were found in Tutankhamun's tomb, and the plant does not grow wild in Egypt, so someone imported them for him.",
fr:"La graine et la feuille viennent d’une même plante et n’ont rien du même goût — la feuille est savonneuse et verte, la graine chaude et sucrée comme l’écorce d’orange. On en a trouvé dans la tombe de Toutânkhamon, et la plante ne pousse pas à l’état sauvage en Égypte : quelqu’un les avait importées pour lui."},
tip:{en:"Toast and crush it coarsely rather than grinding to powder. The husk is papery and the fragments give little bursts of citrus.",
fr:"Grillez-la et concassez-la grossièrement plutôt que de la réduire en poudre. L’enveloppe est parcheminée et les éclats donnent de petites bouffées d’agrume."},
pairs:["cumin","orange","carrot","lamb","garlic","olive-oil","chickpeas","lemon"],
svg:'<circle class="f3 sf" cx="42" cy="54" r="8"/><circle class="f3 sf" cx="57" cy="58" r="8"/><path class="s" d="M36 54h12M51 58h12M42 46v16M57 50v16"/>'},

{id:"cubeb",cat:"spices",name:{en:"Cubeb pepper",fr:"Poivre cubèbe"},latin:"Piper cubeba",
origin:{en:"Java, Indonesia",fr:"Java, Indonésie"},season:[],
flavor:["peppery","resinous","bitter","warm"],
story:{en:"Recognisable by the little stalk left attached — the tailed pepper. Medieval Europe used it constantly, then Portugal banned its import in the seventeenth century to protect the black pepper trade, and it vanished from the repertoire for three hundred years.",
fr:"Reconnaissable à la petite queue qui lui reste — le poivre à queue. L’Europe médiévale en usait constamment, puis le Portugal en interdit l’importation au XVIIe siècle pour protéger le commerce du poivre noir, et il disparut du répertoire pendant trois cents ans."},
tip:{en:"It is closer to allspice and pine than to pepper. Use it in game marinades and in gin-scented dishes, sparingly.",
fr:"Il est plus proche du piment de la Jamaïque et du pin que du poivre. Employez-le dans les marinades de gibier et les plats genévrés, avec parcimonie."},
pairs:["juniper","venison","clove","bay-leaf","red-wine-vinegar","onion","black-pepper","thyme"],
svg:'<circle class="f1 sf" cx="44" cy="54" r="7"/><path class="s" d="M44 61v8"/><circle class="f1 sf" cx="58" cy="58" r="6"/><path class="s" d="M58 64v7"/>'},

{id:"cumin",cat:"spices",name:{en:"Cumin",fr:"Cumin"},latin:"Cuminum cyminum",
origin:{en:"Eastern Mediterranean & Egypt",fr:"Méditerranée orientale & Égypte"},season:[],
flavor:["earthy","warm","pungent"],
story:{en:"Found in pharaohs’ tombs and on every Roman table, where it sat like our pepper. Romans considered it the emblem of misers — emperor Marcus Aurelius was mocked as a “cumin-splitter” for his thrift. It now warms half the world’s cuisines.",
fr:"Présent dans les tombes des pharaons et sur toutes les tables romaines, où il trônait comme notre poivre. Les Romains en firent l’emblème des avares — l’empereur Marc Aurèle fut moqué comme « coupeur de cumin » pour sa pingrerie. Il réchauffe aujourd’hui la moitié des cuisines du monde."},
tip:{en:"Toast the whole seeds in a dry pan until they smell like a market in Marrakech, then grind — the difference is night and day.",
fr:"Torréfiez les graines entières à sec jusqu’à ce qu’elles sentent le souk de Marrakech, puis moulez — la différence est le jour et la nuit."},
pairs:["carrot","chickpeas","lamb","yogurt","lentils","beetroot","cilantro"],
svg:'<path class="f3 sf" d="M36 44q2-8 8-8-1 8-8 8zM52 38q2-8 8-8-1 8-8 8zM44 58q2-8 8-8-1 8-8 8zM58 54q2-8 8-8-1 8-8 8zM32 62q2-8 8-8-1 8-8 8zM50 70q2-8 8-8-1 8-8 8z"/>'},

{id:"dried-lime",cat:"spices",name:{en:"Dried lime",fr:"Citron noir séché"},latin:"Citrus aurantiifolia",
origin:{en:"Persian Gulf",fr:"Golfe Persique"},season:[],
flavor:["sour","bitter","earthy","musky"],
story:{en:"Limes boiled in brine and dried in the sun until they are hollow, light and almost black — loomi in the Gulf, limoo omani in Iran. The fermentation that happens as they dry turns the fresh acidity into something dusty and slightly bitter.",
fr:"Des citrons verts bouillis en saumure et séchés au soleil jusqu’à devenir creux, légers et presque noirs — loomi dans le Golfe, limoo omani en Iran. La fermentation qui se produit au séchage change l’acidité fraîche en quelque chose de poussiéreux et légèrement amer."},
tip:{en:"Pierce it twice and drop it in whole, then remove it before serving. Ground, it clouds the dish and turns aggressively bitter.",
fr:"Percez-le deux fois et jetez-le entier, puis retirez-le avant de servir. Moulu, il trouble le plat et devient agressivement amer."},
pairs:["lamb","rice","turmeric","onion","chickpeas","cilantro","cinnamon","saffron"],
svg:'<circle class="f1 sf" cx="48" cy="54" r="18"/><path class="s" d="M36 44q12 8 24 0M34 58q14 8 28 0"/><circle class="dot" cx="44" cy="50" r="1.6"/>'},

{id:"espelette",cat:"spices",rare:true,name:{en:"Espelette pepper",fr:"Piment d’Espelette"},latin:"Capsicum annuum 'Gorria'",
origin:{en:"Basque Country, France",fr:"Pays basque, France"},season:[],
flavor:["fruity","warm","hot","smoky"],
story:{en:"Brought back from the Americas in the 16th century, the pepper found its terroir in ten Basque villages, where autumn façades disappear under garlands of drying red pods. Protected like a great wine, it long replaced black pepper in Basque kitchens — warmth with a sunset colour.",
fr:"Rapporté des Amériques au XVIe siècle, le piment trouva son terroir dans dix villages basques, où les façades d’automne disparaissent sous les guirlandes de gousses rouges qui sèchent. Protégé comme un grand vin, il a longtemps remplacé le poivre noir dans les cuisines basques — une chaleur couleur de couchant."},
tip:{en:"Gentler than cayenne, fruitier than paprika: dust it on eggs, cod or chocolate at the end. It seasons like pepper, not like fire.",
fr:"Plus doux que le cayenne, plus fruité que le paprika : poudrez-le sur des œufs, un cabillaud ou un chocolat, en finition. Il assaisonne comme un poivre, pas comme un incendie."},
pairs:["cod","egg","tomato","olive-oil","dark-chocolate"],
svg:'<path class="f2 sf" d="M56 32q6 18-6 32-7 8-14 5 4-3 7-9 8-14 8-28z" transform="rotate(8 48 50)"/><path class="s" d="M56 32q1-5 6-6"/><path class="s" d="M34 66h8M32 71h12" stroke-width="1.6"/>'},

{id:"fennel-seed",cat:"spices",name:{en:"Fennel seed",fr:"Graine de fenouil"},latin:"Foeniculum vulgare",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["anise","sweet","warm","herbal"],
story:{en:"The Greeks called the plant marathon and named a battlefield after the fennel growing on it — the run that gave us the marathon began in a fennel field. Indian restaurants still set out sugared seeds by the door as a digestive.",
fr:"Les Grecs appelaient la plante marathon et donnèrent son nom à un champ de bataille couvert de fenouil — la course qui nous a donné le marathon partit d’un champ de fenouil. Les restaurants indiens en disposent encore, enrobées de sucre, près de la porte comme digestif."},
tip:{en:"Crack the seeds lightly before they go into a sausage or a pork rub. Whole they stay inert; powdered they turn medicinal.",
fr:"Concassez légèrement les graines avant de les mettre dans une saucisse ou un rub à porc. Entières elles restent inertes ; en poudre elles tournent au médicinal."},
pairs:["pork","lard","orange","olive-oil","garlic","tomato","chili","fennel"],
svg:'<path class="f2 sf" d="M40 46q4 10 0 20M48 42q4 12 0 24M56 46q4 10 0 20"/><path class="s" d="M38 56h4M46 56h4M54 56h4"/>'},

{id:"fenugreek",cat:"spices",name:{en:"Fenugreek",fr:"Fenugrec"},latin:"Trigonella foenum-graecum",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["bitter","sweet","nutty","earthy"],
story:{en:"It is the smell of commercial curry powder and of maple syrup imitation both — the compound responsible, sotolon, is the same. People who eat a lot of it genuinely smell of maple, which has caused more than one unnecessary medical consultation.",
fr:"C’est l’odeur du curry en poudre du commerce et de l’arôme artificiel de sirop d’érable — le composé responsable, le sotolon, est le même. Ceux qui en consomment beaucoup sentent réellement l’érable, ce qui a provoqué plus d’une consultation médicale inutile."},
tip:{en:"Toast it barely, and stop before it darkens. A second too long and the bitterness becomes the only thing you taste.",
fr:"Grillez-le à peine, et arrêtez avant qu’il ne fonce. Une seconde de trop et l’amertume devient tout ce que l’on goûte."},
pairs:["turmeric","cumin","ghee","tomato","garlic","ginger","red-lentil","cilantro"],
svg:'<path class="f2 sf" d="M40 50l8 4-8 4-2-4z"/><path class="f2 sf" d="M54 56l8 4-8 4-2-4z"/><path class="f2 sf" d="M44 64l8 4-8 4-2-4z"/>'},

{id:"galangal",cat:"spices",name:{en:"Galangal",fr:"Galanga"},latin:"Alpinia galanga",
origin:{en:"Southeast Asia",fr:"Asie du Sud-Est"},season:[],
flavor:["citrus","peppery","resinous","hot"],
story:{en:"A ginger relative, but sharper, more piney and far more fibrous — you cannot grate it, only slice it. Substituting ginger is the commonest way a Thai curry goes wrong at home, because the pine and citrus notes simply are not there.",
fr:"Un parent du gingembre, mais plus vif, plus résineux et bien plus fibreux — on ne peut pas le râper, seulement le trancher. Lui substituer du gingembre est la façon la plus courante de rater un curry thaï à la maison, car les notes de pin et d’agrume manquent tout simplement."},
tip:{en:"Slice it into coins and leave them in the pot to be fished out, like a bay leaf. It never softens enough to eat.",
fr:"Taillez-le en rondelles à retirer en fin de cuisson, comme une feuille de laurier. Il ne s’attendrit jamais assez pour être mangé."},
pairs:["lemongrass","coconut-milk","chili","kaffir-lime-leaf","fish-sauce","lime","cilantro","shrimp"],
svg:'<path class="f3 sf" d="M30 58q10-12 22-8t14 12-16 10-22-6z"/><path class="s" d="M40 54q8 6 16 4"/><circle class="dot" cx="38" cy="58" r="1.4"/>'},

{id:"ginger",cat:"spices",name:{en:"Ginger",fr:"Gingembre"},latin:"Zingiber officinale",
origin:{en:"Maritime Southeast Asia",fr:"Asie du Sud-Est insulaire"},season:[],
flavor:["hot","citrus","warm","fresh"],
story:{en:"In medieval England a pound of ginger cost a sheep, and Queen Elizabeth I is credited with the first gingerbread men, baked as portraits of her courtiers. A root that has been currency, medicine and flattery.",
fr:"Dans l’Angleterre médiévale, une livre de gingembre valait un mouton, et l’on attribue à Élisabeth Ire les premiers bonshommes en pain d’épices, cuits à l’effigie de ses courtisans. Une racine qui fut monnaie, remède et flatterie."},
tip:{en:"Peel it with the edge of a teaspoon — it follows the knots better than any knife. Frozen, it grates like a dream.",
fr:"Pelez-le avec le bord d’une petite cuillère — elle épouse les nœuds mieux qu’aucun couteau. Congelé, il se râpe à merveille."},
pairs:["carrot","soy-sauce","honey","mango","dark-chocolate","coconut-milk","salmon"],
svg:'<path class="f2 sf" d="M30 56q-2-10 8-10 4 0 6-4 3-6 10-6 8 0 8 8 0 4 4 6 6 3 4 10-2 8-12 6-4-1-6 2-4 5-11 2-8-3-11-14z"/><path class="s" d="M42 50l4 6M54 44l2 6"/>'},

{id:"grains-of-paradise",cat:"spices",rare:true,name:{en:"Grains of paradise",fr:"Maniguette"},latin:"Aframomum melegueta",
origin:{en:"West African coast",fr:"Côte ouest-africaine"},season:[],
flavor:["peppery","citrus","warm","floral"],
story:{en:"Medieval merchants claimed these seeds floated down rivers straight from Eden — marketing bold enough to name a spice, and to name Africa’s “Grain Coast” after the trade. A ginger cousin with pepper’s bite and cardamom’s perfume, it seasoned Europe for centuries before vanishing into gin botanicals.",
fr:"Les marchands médiévaux juraient que ces graines descendaient les fleuves depuis l’Éden même — un marketing assez audacieux pour nommer une épice, et pour baptiser la « côte des Graines » d’Afrique. Cousine du gingembre, au mordant de poivre et au parfum de cardamome, elle assaisonna l’Europe des siècles durant avant de se réfugier dans les gins."},
tip:{en:"Crush it coarsely at the last moment; it flatters lamb, roast chicken and glazed carrots with a warmth black pepper can’t reach.",
fr:"Concassez-la grossièrement au dernier moment ; elle flatte l’agneau, le poulet rôti et les carottes glacées d’une chaleur que le poivre noir n’atteint pas."},
pairs:["lamb","chicken","carrot","rice"],
svg:'<path class="f3" d="M38 42a3 3 0 106 0 3 3 0 10-6 0M52 38a3 3 0 106 0 3 3 0 10-6 0M32 54a3 3 0 106 0 3 3 0 10-6 0M46 52a3 3 0 106 0 3 3 0 10-6 0M60 50a3 3 0 106 0 3 3 0 10-6 0M40 64a3 3 0 106 0 3 3 0 10-6 0M54 62a3 3 0 106 0 3 3 0 10-6 0"/>'},

{id:"green-pepper",cat:"spices",name:{en:"Green peppercorn",fr:"Poivre vert"},latin:"Piper nigrum",
origin:{en:"Malabar coast, India",fr:"Côte de Malabar, Inde"},season:[],
flavor:["fresh","peppery","herbal","hot"],
story:{en:"Picked unripe and stopped before it can dry — either brined, freeze-dried or preserved in vinegar. Left on the vine the same berry would become black pepper; caught early it keeps a green, almost herbal freshness instead of heat.",
fr:"Cueilli vert et arrêté avant séchage — en saumure, lyophilisé ou conservé au vinaigre. Laissée sur la liane, la même baie deviendrait poivre noir ; saisie tôt elle garde une fraîcheur verte, presque herbacée, plutôt que du feu."},
tip:{en:"Crush the brined ones with the flat of a knife straight into a cream sauce. Drying them out defeats the purpose entirely.",
fr:"Écrasez ceux en saumure du plat du couteau directement dans une sauce crème. Les sécher annule tout l’intérêt."},
pairs:["cream","duck","beef","butter","thyme","shallot","mustard","tenderloin"],
svg:'<circle class="f2 sf" cx="42" cy="52" r="7"/><circle class="f2 sf" cx="56" cy="55" r="7"/><circle class="f2 sf" cx="47" cy="66" r="7"/><path class="s" d="M42 45v-6"/>'},

{id:"horseradish",cat:"spices",name:{en:"Horseradish",fr:"Raifort"},latin:"Armoracia rusticana",
origin:{en:"Southeastern Europe",fr:"Europe du Sud-Est"},season:[10,11,12,1,2,3],
flavor:["hot","pungent","bitter","earthy"],
story:{en:"Its heat goes up the nose rather than onto the tongue, because the compound released is volatile — it evaporates and hits the sinuses instead of the taste buds. Alsace grows most of France's crop and grates it into cream for boiled beef.",
fr:"Son feu monte au nez plutôt que sur la langue, parce que le composé libéré est volatil — il s’évapore et frappe les sinus au lieu des papilles. L’Alsace produit l’essentiel de la récolte française et le râpe à la crème pour le bœuf bouilli."},
tip:{en:"Add vinegar within three minutes of grating to lock the heat in. Left alone it keeps building, then collapses to bitterness.",
fr:"Ajoutez du vinaigre dans les trois minutes après râpage pour fixer le piquant. Laissé seul il monte encore, puis s’effondre en amertume."},
pairs:["beef","cream","beetroot","white-wine-vinegar","salmon","potato","apple","mustard"],
svg:'<path class="f3 sf" d="M44 26h8l-4 46q-2 6-4 0z"/><path class="s" d="M44 38h8M45 50h6M46 62h4"/><path class="s" d="M46 25q-4-6-10-6"/>'},

{id:"juniper",cat:"spices",rare:true,name:{en:"Juniper berry",fr:"Baie de genièvre"},latin:"Juniperus communis",
origin:{en:"Northern hemisphere scrubland",fr:"Landes de l’hémisphère Nord"},season:[],
flavor:["resinous","woody","bitter","fresh"],
story:{en:"The only spice we harvest from a conifer — each “berry” is a tiny cone that takes two years to ripen. It gave gin its soul and its name, via the Dutch genever, and it remains the mountain accent in choucroute, game and everything that tastes of a walk through cold pines.",
fr:"La seule épice récoltée sur un conifère — chaque « baie » est un minuscule cône qui met deux ans à mûrir. Elle a donné au gin son âme et son nom, via le genever hollandais, et reste l’accent montagnard de la choucroute, du gibier et de tout ce qui a le goût d’une marche dans les pins froids."},
tip:{en:"Crush the berries flat before they go in — whole, they stay mute. Three or four suffice for a whole braise; ten make it a pine forest.",
fr:"Écrasez les baies avant de les jeter dans la marmite — entières, elles restent muettes. Trois ou quatre suffisent à tout un braisé ; dix en font une forêt de pins."},
pairs:["duck","pork","beef","bay-leaf","black-pepper"],
svg:'<circle class="f3 sf" cx="42" cy="54" r="8"/><circle class="f3 sf" cx="58" cy="58" r="7"/><path class="s" d="M40 51l4 4M56 55l3 4" stroke-width="1.6"/><path class="s" d="M46 40l6-12M46 40l-2-10M46 40l10-8"/>'},

{id:"liquorice",cat:"spices",name:{en:"Liquorice",fr:"Réglisse"},latin:"Glycyrrhiza glabra",
origin:{en:"Middle East & southern Europe",fr:"Moyen-Orient & Europe du Sud"},season:[],
flavor:["sweet","anise","earthy","bitter"],
story:{en:"Its sweetness comes from glycyrrhizin, which is around fifty times sweeter than sugar and works on a completely different receptor — which is why the sweetness arrives late and lingers. Roots were found in Tutankhamun's tomb alongside the coriander.",
fr:"Sa douceur vient de la glycyrrhizine, environ cinquante fois plus sucrée que le sucre et agissant sur un récepteur tout différent — d’où une douceur qui arrive tard et s’attarde. On a trouvé des racines dans la tombe de Toutânkhamon, à côté de la coriandre."},
tip:{en:"A small piece of root in a braise with lamb or beef adds depth nobody can identify. Powdered it takes over instantly.",
fr:"Un petit morceau de racine dans un braisé d’agneau ou de bœuf donne une profondeur que personne n’identifie. En poudre elle prend le dessus aussitôt."},
pairs:["lamb","dark-chocolate","fennel","beef","orange","star-anise","cream","raspberry"],
svg:'<path class="f1 sf" d="M42 26v46q0 6-4 4V30z"/><path class="f1 sf" d="M52 32v40q0 6-4 4V36z"/><path class="s" d="M42 44h6M52 52h4"/>'},

{id:"long-pepper",cat:"spices",rare:true,name:{en:"Long pepper",fr:"Poivre long"},latin:"Piper longum",
origin:{en:"India & Indonesia",fr:"Inde & Indonésie"},season:[],
flavor:["hot","sweet","warm","woody"],
story:{en:"Pliny recorded that Rome paid more for it than for black pepper — its tiny catkins taste hotter, sweeter, almost of gingerbread. The chili’s arrival dethroned it into five centuries of obscurity, from which chefs and chocolatiers are quietly retrieving it.",
fr:"Pline rapporte que Rome le payait plus cher que le poivre noir — ses petits chatons goûtent plus chaud, plus sucré, presque le pain d’épices. L’arrivée du piment le détrôna pour cinq siècles d’oubli, dont chefs et chocolatiers le tirent aujourd’hui sans bruit."},
tip:{en:"Grate it like nutmeg rather than grinding: its warmth loves poached pears, duck, and anything with brown butter.",
fr:"Râpez-le comme une muscade plutôt que de le moudre : sa chaleur aime les poires pochées, le canard et tout ce qui touche au beurre noisette."},
pairs:["pear","duck","beef","dark-chocolate","honey"],
svg:'<path class="f3 sf" d="M40 28q6 2 6 12v24q0 10-6 12-6-2-6-12V40q0-10 6-12z" transform="rotate(-18 44 52)"/><path class="s" d="M40 34v36" transform="rotate(-18 44 52)" stroke-width="1.4"/><path class="dot" d="M56 60a2 2 0 104 0 2 2 0 10-4 0M62 52a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"mace",cat:"spices",name:{en:"Mace",fr:"Macis"},latin:"Myristica fragrans",
origin:{en:"Banda Islands, Indonesia",fr:"Îles Banda, Indonésie"},season:[],
flavor:["warm","floral","sweet","musky"],
story:{en:"The scarlet lace that wraps a nutmeg seed inside the fruit — one tree yields both spices, and mace is far scarcer because there is so little of it per nut. The Dutch fought a war for the Banda Islands over exactly this.",
fr:"La dentelle écarlate qui enveloppe la noix de muscade dans le fruit — un même arbre donne les deux épices, et le macis est bien plus rare tant il y en a peu par noix. Les Néerlandais ont fait une guerre pour les îles Banda précisément pour cela."},
tip:{en:"It is nutmeg's more delicate sibling — use it where nutmeg would be too heavy, in a béchamel or a pale potted meat.",
fr:"C’est le frère plus délicat de la muscade — employez-le là où la muscade pèserait trop, dans une béchamel ou une terrine claire."},
pairs:["cream","butter","potato","nutmeg","white-pepper","spinach","chicken","comte"],
svg:'<path class="f1 sf" d="M48 30q-16 8-14 26t14 18 14-18-14-26z"/><path class="s" d="M40 42q8 6 16 0M38 56q10 6 20 0"/>'},

{id:"mustard-seed",cat:"spices",name:{en:"Mustard seed",fr:"Graine de moutarde"},latin:"Brassica juncea / Sinapis alba",
origin:{en:"Eurasia",fr:"Eurasie"},season:[],
flavor:["pungent","hot","bitter","earthy"],
story:{en:"The heat does not exist in the intact seed — it is manufactured the instant the cell walls break in the presence of cold water, by an enzyme meeting a compound it is normally kept apart from. Hot water destroys the enzyme, which is why mustard is never made with it.",
fr:"Le piquant n’existe pas dans la graine intacte — il se fabrique à l’instant où les parois cellulaires se rompent en présence d’eau froide, une enzyme rencontrant un composé dont elle est normalement séparée. L’eau chaude détruit l’enzyme, et c’est pourquoi on ne fait jamais la moutarde avec."},
tip:{en:"Pop the whole seeds in hot oil until they jump, for Indian dishes. For a paste, crush them into cold liquid and wait ten minutes.",
fr:"Faites éclater les graines entières dans l’huile chaude jusqu’à ce qu’elles sautent, pour les plats indiens. Pour une pâte, écrasez-les dans un liquide froid et attendez dix minutes."},
pairs:["turmeric","curry-leaf","cider-vinegar","cabbage","potato","honey","chili","cumin"],
svg:'<circle class="f2 sf" cx="41" cy="52" r="5"/><circle class="f2 sf" cx="54" cy="50" r="5"/><circle class="f2 sf" cx="47" cy="62" r="5"/><circle class="f2 sf" cx="59" cy="62" r="5"/><circle class="f2 sf" cx="38" cy="64" r="4"/>'},

{id:"nigella",cat:"spices",name:{en:"Nigella seed",fr:"Nigelle"},latin:"Nigella sativa",
origin:{en:"Southwest Asia",fr:"Asie du Sud-Ouest"},season:[],
flavor:["bitter","peppery","herbal","earthy"],
story:{en:"Called black cumin, black caraway and black onion seed, and it is none of the three — it belongs to the buttercup family. It is the black seed of Islamic and Ayurvedic medicine, and it is what speckles the top of a naan.",
fr:"Appelée cumin noir, carvi noir et graine d’oignon noir, elle n’est aucun des trois — elle appartient à la famille des renoncules. C’est la graine noire de la médecine islamique et ayurvédique, et c’est elle qui mouchette le dessus d’un naan."},
tip:{en:"Scatter it on bread before baking, or bloom it in hot oil. Ground, it turns dusty and loses the oniony top note.",
fr:"Parsemez-la sur le pain avant cuisson, ou faites-la éclater dans l’huile chaude. Moulue, elle devient poussiéreuse et perd sa note d’oignon."},
pairs:["flour-t65","yogurt","onion","cumin","garlic","turmeric","feta","sesame"],
svg:'<path class="f1 sf" d="M42 48l4 8-4 8-4-8z"/><path class="f1 sf" d="M55 54l4 8-4 8-4-8z"/><path class="f1 sf" d="M48 64l3 6-3 6-3-6z"/>'},

{id:"nutmeg",cat:"spices",name:{en:"Nutmeg",fr:"Noix de muscade"},latin:"Myristica fragrans",
origin:{en:"Banda Islands, Indonesia",fr:"Îles Banda, Indonésie"},season:[],
flavor:["warm","sweet","woody","pungent"],
story:{en:"Once it grew on ten tiny islands and nowhere else on Earth. In 1667 the Dutch traded Manhattan to the English to keep Run, a nutmeg island two miles long — history’s verdict on that swap is still funny.",
fr:"Elle ne poussait jadis que sur dix îlots et nulle part ailleurs sur Terre. En 1667, les Hollandais cédèrent Manhattan aux Anglais pour garder Run, une île à muscade de trois kilomètres de long — le verdict de l’histoire sur cet échange fait encore sourire."},
tip:{en:"Buy it whole, grate it directly over the dish, and stop earlier than you think: three passes of the grater season a whole béchamel.",
fr:"Achetez-la entière, râpez-la directement sur le plat, et arrêtez-vous plus tôt que prévu : trois passages de râpe assaisonnent toute une béchamel."},
pairs:["spinach","potato","cream","egg","honey"],
svg:'<circle class="f2 sf" cx="48" cy="52" r="17"/><path class="s" d="M48 38q-8 6-8 14t8 14M48 38q8 6 8 14t-8 14"/><circle class="f3 sf" cx="48" cy="52" r="5"/>'},

{id:"paprika",cat:"spices",name:{en:"Paprika",fr:"Paprika"},latin:"Capsicum annuum",
origin:{en:"Americas, adopted by Hungary",fr:"Amériques, adopté par la Hongrie"},season:[],
flavor:["sweet","smoky","fruity","warm"],
story:{en:"An American pepper that walked through Ottoman camps into Hungarian kitchens and became a national identity. The scientist who first isolated vitamin C did it from Szeged paprika — and won a Nobel Prize for the national spice.",
fr:"Un piment américain qui traversa les campements ottomans jusqu’aux cuisines hongroises et devint une identité nationale. Le savant qui isola le premier la vitamine C le fit à partir du paprika de Szeged — un prix Nobel pour l’épice nationale."},
tip:{en:"Paprika burns and turns bitter in seconds: add it off the heat, into something moist, never into hot dry oil.",
fr:"Le paprika brûle et devient amer en quelques secondes : ajoutez-le hors du feu, dans un milieu humide, jamais dans une huile sèche et brûlante."},
pairs:["chicken","potato","egg","white-beans","pork","corn"],
svg:'<path class="f2 sf" d="M40 34q-12 18 0 32 8 10 16 2 8-9 0-22-6-9-16-12z" transform="rotate(14 48 52)"/><path class="s" d="M44 32q0-6 6-8"/><path class="dot" d="M60 70a2 2 0 104 0 2 2 0 10-4 0M66 64a2 2 0 104 0 2 2 0 10-4 0M68 72a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"poppy-seed",cat:"spices",name:{en:"Poppy seed",fr:"Graine de pavot"},latin:"Papaver somniferum",
origin:{en:"Mediterranean",fr:"Méditerranée"},season:[],
flavor:["nutty","toasty","bitter","earthy"],
story:{en:"Central Europe grinds them into a sweet paste for strudel and beigli, which is a different food from the whole seeds scattered on a bagel. It takes roughly three thousand seeds to make a gram, and the plant is the opium poppy.",
fr:"L’Europe centrale les broie en pâte sucrée pour le strudel et le beigli, ce qui est un autre aliment que les graines entières parsemées sur un bagel. Il faut environ trois mille graines pour un gramme, et la plante est le pavot à opium."},
tip:{en:"Grind them or soak them in hot milk before baking. Whole and dry they contribute crunch and almost no flavour.",
fr:"Broyez-les ou faites-les tremper dans du lait chaud avant cuisson. Entières et sèches elles n’apportent que du croquant et presque aucun goût."},
pairs:["lemon","honey","butter","flour-t45","cream","orange","almond","sugar"],
svg:'<circle class="dot" cx="40" cy="50" r="2.5"/><circle class="dot" cx="50" cy="48" r="2.5"/><circle class="dot" cx="58" cy="54" r="2.5"/><circle class="dot" cx="44" cy="60" r="2.5"/><circle class="dot" cx="54" cy="62" r="2.5"/><circle class="dot" cx="46" cy="70" r="2.5"/>'},

{id:"quatre-epices",cat:"spices",name:{en:"Quatre-épices",fr:"Quatre-épices"},latin:"Mélange français",
origin:{en:"France",fr:"France"},season:[],
flavor:["warm","peppery","sweet","woody"],
story:{en:"White pepper, nutmeg, clove and ginger — the charcutier's blend, and it is what makes a French terrine or a boudin taste French rather than merely of pork. It is one of the few classical blends that is savoury rather than sweet.",
fr:"Poivre blanc, muscade, girofle et gingembre — le mélange du charcutier, et c’est lui qui fait qu’une terrine ou un boudin ont un goût français plutôt que simplement de porc. C’est l’un des rares mélanges classiques salés plutôt que sucrés."},
tip:{en:"Pepper should dominate, not clove. If yours smells mainly of clove it is out of balance and will overwhelm a pâté.",
fr:"Le poivre doit dominer, non le girofle. Si le vôtre sent surtout le girofle, il est déséquilibré et écrasera un pâté."},
pairs:["pork","foie-gras","onion","bay-leaf","thyme","lard","beef","black-pepper"],
svg:'<path class="f1 sf" d="M34 66q0-16 14-20 14 4 14 20z"/><path class="s" d="M48 46v20M34 60h28"/>'},

{id:"ras-el-hanout",cat:"spices",name:{en:"Ras el hanout",fr:"Ras el hanout"},latin:"رأس الحانوت",
origin:{en:"Maghreb",fr:"Maghreb"},season:[],
flavor:["warm","floral","sweet","peppery"],
story:{en:"The name means head of the shop — the best a spice merchant has, and every merchant's blend is different by design. Traditional versions ran to thirty ingredients and included rosebuds, and some historical ones contained things now illegal.",
fr:"Le nom signifie tête de la boutique — le meilleur que possède un marchand d’épices, et chaque mélange diffère par principe. Les versions traditionnelles comptaient jusqu’à trente ingrédients dont des boutons de rose, et certaines anciennes contenaient des choses aujourd’hui interdites."},
tip:{en:"Bloom it in fat at the start, never sprinkle it on at the end. Half the blend is woody spices that need heat to open.",
fr:"Faites-le revenir dans le gras au départ, ne le saupoudrez jamais à la fin. La moitié du mélange est faite d’épices ligneuses qui ont besoin de chaleur pour s’ouvrir."},
pairs:["lamb","couscous","carrot","chickpeas","preserved-lemon","almond","onion","date"],
svg:'<path class="f2 sf" d="M32 68q0-18 16-22 16 4 16 22z"/><circle class="dot" cx="41" cy="58" r="1.8"/><circle class="dot" cx="50" cy="55" r="1.8"/><circle class="dot" cx="55" cy="63" r="1.8"/><circle class="dot" cx="44" cy="65" r="1.8"/>'},

{id:"saffron",cat:"spices",name:{en:"Saffron",fr:"Safran"},latin:"Crocus sativus",
origin:{en:"Persia & Kashmir",fr:"Perse & Cachemire"},season:[],
flavor:["floral","honeyed","bitter","earthy"],
story:{en:"Each crocus flower gives three red threads, picked by hand at dawn before the sun wilts them; a gram costs about a hundred and fifty flowers. It has been worth more than gold for most of recorded history — the only spice measured like jewellery.",
fr:"Chaque fleur de crocus donne trois filaments rouges, cueillis à la main à l’aube avant que le soleil ne les fane ; un gramme coûte environ cent cinquante fleurs. Il a valu plus cher que l’or pendant l’essentiel de l’histoire écrite — la seule épice qu’on pèse comme un bijou."},
tip:{en:"Steep the threads in warm water or stock for twenty minutes before using — thrown in dry, half their perfume never wakes up.",
fr:"Laissez infuser les filaments dans une eau ou un bouillon tiède vingt minutes avant usage — jetés à sec, la moitié de leur parfum ne se réveille jamais."},
pairs:["rice","shrimp","cod","chicken","cardamom","orange","honey"],
svg:'<path class="s" d="M40 70q-4-16 2-30M48 72q-2-18 2-34M56 70q4-14-2-30"/><path class="f3" d="M40 38a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M47 34a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0M52 40a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0"/>'},

{id:"sichuan-pepper",cat:"spices",rare:true,name:{en:"Sichuan pepper",fr:"Poivre du Sichuan"},latin:"Zanthoxylum simulans",
origin:{en:"Sichuan, China",fr:"Sichuan, Chine"},season:[],
flavor:["numbing","citrus","woody","hot"],
story:{en:"Not a pepper at all but the husk of a citrus-family berry. Its molecule, sanshool, tricks the touch receptors of the lips into feeling a vibration — researchers measured the phantom buzz at around fifty hertz. Paired with chili it creates málà, Sichuan’s “numbing-hot”, a sensation more than a taste.",
fr:"Pas un poivre du tout, mais l’écorce d’une baie de la famille des agrumes. Sa molécule, le sanshoöl, leurre les récepteurs tactiles des lèvres et leur fait sentir une vibration — les chercheurs ont mesuré ce bourdonnement fantôme autour de cinquante hertz. Marié au piment, il crée le málà, le « piquant-engourdissant » du Sichuan, une sensation plus qu’un goût."},
tip:{en:"Toast the husks dry, discard the gritty black seeds, grind coarsely. Start with a pinch — the tingle builds like applause.",
fr:"Torréfiez les écorces à sec, jetez les graines noires et sableuses, moulez grossièrement. Commencez par une pincée — le picotement monte comme des applaudissements."},
pairs:["chili","duck","dark-chocolate","ginger","soy-sauce"],
svg:'<path class="f3 sf" d="M40 46a7 7 0 107 7q4 3 8 0a7 7 0 107-7 7 7 0 10-7-7q-4-3-8 0a7 7 0 10-7 7z" transform="scale(.85) translate(9 10)"/><path class="s" d="M44 52q4 4 8 0" transform="scale(.85) translate(9 10)"/>'},

{id:"star-anise",cat:"spices",name:{en:"Star anise",fr:"Badiane"},latin:"Illicium verum",
origin:{en:"Southern China & Vietnam",fr:"Chine du Sud & Vietnam"},season:[],
flavor:["anise","sweet","woody","warm"],
story:{en:"Until recently it was the industrial source of shikimic acid, the starting material for the antiviral oseltamivir — a global flu scare in 2005 caused a genuine shortage of a cooking spice. It is one of the five in Chinese five-spice.",
fr:"Jusqu’à récemment elle était la source industrielle d’acide shikimique, matière première de l’antiviral oseltamivir — une alerte grippale mondiale en 2005 provoqua une véritable pénurie d’une épice de cuisine. C’est l’une des cinq du cinq-épices chinois."},
tip:{en:"One whole star is enough for a large pot. Two is too many, and there is no way to take it back out once it has infused.",
fr:"Une étoile entière suffit pour une grande casserole. Deux est de trop, et il n’y a aucun moyen de revenir en arrière une fois l’infusion faite."},
pairs:["pork","soy-sauce","cassia","orange","ginger","duck","plum","cinnamon"],
svg:'<path class="f1 sf" d="M48 28l5 12 13 1-10 8 4 13-12-7-12 7 4-13-10-8 13-1z"/><circle class="dot" cx="48" cy="50" r="3"/>'},

{id:"sumac",cat:"spices",rare:true,name:{en:"Sumac",fr:"Sumac"},latin:"Rhus coriaria",
origin:{en:"Middle East & Mediterranean",fr:"Moyen-Orient & Méditerranée"},season:[],
flavor:["sour","tangy","fruity"],
story:{en:"Before lemons reached Europe, Romans soured their dishes with these crushed crimson berries — acidity you can sprinkle. It never left the Levant, where it crowns fattoush, stains onions pink beside kebabs, and anchors the za’atar blend.",
fr:"Avant que le citron n’atteigne l’Europe, les Romains acidifiaient leurs plats avec ces baies cramoisies pilées — de l’acidité à saupoudrer. Il n’a jamais quitté le Levant, où il couronne le fattouche, teinte de rose les oignons des kebabs et fonde le mélange zaatar."},
tip:{en:"Think of it as dry lemon juice: over grilled meat, yogurt or raw onions at the end, never long-cooked. It wakes a dish without wetting it.",
fr:"Pensez-le comme du jus de citron sec : sur une viande grillée, un yaourt ou des oignons crus, à la fin, jamais en cuisson longue. Il réveille un plat sans le mouiller."},
pairs:["onion","yogurt","lamb","chickpeas","tomato"],
svg:'<path class="f3 sf" d="M48 30l14 22q6 12-4 18-10 5-20 0-10-6-4-18z"/><path class="dot" d="M42 48a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M50 46a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M46 56a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0M54 54a1.6 1.6 0 103.2 0 1.6 1.6 0 10-3.2 0"/>'},

{id:"timut-pepper",cat:"spices",name:{en:"Timut pepper",fr:"Poivre de Timut"},latin:"Zanthoxylum armatum",
origin:{en:"Nepal",fr:"Népal"},season:[],
flavor:["citrus","numbing","floral","peppery"],
story:{en:"Not a pepper but a Himalayan cousin of Sichuan pepper, and it smells overwhelmingly of grapefruit — so much so that blind tasters routinely guess citrus zest. The numbing tingle is the family signature, milder here than in its Chinese relative.",
fr:"Pas un poivre mais un cousin himalayen du poivre de Sichuan, et il sent massivement le pamplemousse — au point que les dégustateurs à l’aveugle devinent régulièrement du zeste d’agrume. Le picotement anesthésiant est la signature de la famille, plus doux ici que chez son parent chinois."},
tip:{en:"Grind it over the finished plate, never into the cooking. Heat destroys the citrus note within a minute.",
fr:"Moulez-le sur le plat fini, jamais dans la cuisson. La chaleur détruit la note d’agrume en une minute."},
pairs:["dark-chocolate","scallop","honey","grapefruit","cream","salmon","lime","vanilla"],
svg:'<circle class="f2 sf" cx="42" cy="54" r="7"/><circle class="f2 sf" cx="56" cy="52" r="6"/><circle class="f2 sf" cx="48" cy="66" r="6"/><path class="s" d="M39 51l6 6M53 49l6 6"/>'},

{id:"tonka",cat:"spices",rare:true,name:{en:"Tonka bean",fr:"Fève tonka"},latin:"Dipteryx odorata",
origin:{en:"Guyana & Venezuela rainforests",fr:"Forêts de Guyane & du Venezuela"},season:[],
flavor:["sweet","warm","honeyed","woody"],
story:{en:"A wrinkled black seed smelling of vanilla, bitter almond, fresh hay and tobacco all at once — thanks to coumarin, the compound that got it banned from American kitchens in 1954. French pâtissiers, unbanned and unbothered, grate it over everything creamy.",
fr:"Une graine noire et fripée qui sent à la fois la vanille, l’amande amère, le foin coupé et le tabac — grâce à la coumarine, la molécule qui l’a fait interdire des cuisines américaines en 1954. Les pâtissiers français, ni interdits ni inquiets, la râpent sur tout ce qui est crémeux."},
tip:{en:"Use it like nutmeg, in whispers: three strokes of the grater into a warm cream, then stop. Its perfume expands as the dish cools.",
fr:"Utilisez-la comme la muscade, en murmures : trois coups de râpe dans une crème tiède, puis arrêtez. Son parfum se déploie quand le plat refroidit."},
pairs:["dark-chocolate","cream","coffee","hazelnut","cherry","vanilla"],
svg:'<path class="f3 sf" d="M36 44q8-10 22-6 10 3 6 14-4 12-18 10-14-3-10-18z" transform="rotate(-12 48 52)"/><path class="s" d="M40 48q6 8 16 6" transform="rotate(-12 48 52)"/>'},

{id:"turmeric",cat:"spices",name:{en:"Turmeric",fr:"Curcuma"},latin:"Curcuma longa",
origin:{en:"India",fr:"Inde"},season:[],
flavor:["earthy","bitter","warm","pungent"],
story:{en:"India’s golden root dyes robes, blesses weddings — brides are painted with it for luck — and colours nearly every curry. Marco Polo described it as a vegetable with the qualities of saffron; merchants happily sold it as “Indian saffron” for centuries.",
fr:"La racine d’or de l’Inde teint les robes, bénit les mariages — on en enduit les mariées pour la chance — et colore presque tous les currys. Marco Polo la décrivit comme un légume aux qualités du safran ; les marchands la vendirent volontiers comme « safran des Indes » pendant des siècles."},
tip:{en:"A pinch of black pepper multiplies what your body absorbs from it — the two are old partners. Mind your clothes: the stain is forever.",
fr:"Une pincée de poivre noir démultiplie ce que le corps en absorbe — les deux sont de vieux associés. Gare à vos vêtements : la tache est éternelle."},
pairs:["rice","coconut-milk","lentils","chickpeas","ginger","yogurt"],
svg:'<path class="f3 sf" d="M32 60q-4-8 4-10 6-1 8-6 2-6 8-6t8 6q2 5 8 6-2 10-10 10-4 0-6 4-2 5-8 5t-8-5q-2-4-4-4z"/><path class="dot" d="M60 68a2 2 0 104 0 2 2 0 10-4 0M66 62a2 2 0 104 0 2 2 0 10-4 0"/>'},

{id:"vanilla",cat:"spices",name:{en:"Vanilla",fr:"Vanille"},latin:"Vanilla planifolia",
origin:{en:"Mexico, grown in Madagascar & Réunion",fr:"Mexique, cultivée à Madagascar & à la Réunion"},season:[],
flavor:["sweet","floral","warm","honeyed"],
story:{en:"The Totonacs of Mexico cured the orchid’s pods first, but outside Mexico the flower refused to fruit — its bee had stayed home. In 1841, Edmond Albius, a twelve-year-old enslaved boy on Réunion island, invented hand-pollination with a thorn, and gave vanilla to the world.",
fr:"Les Totonaques du Mexique furent les premiers à affiner les gousses de l’orchidée, mais hors du Mexique la fleur refusait de fructifier — son abeille était restée au pays. En 1841, Edmond Albius, un garçon esclave de douze ans à la Réunion, inventa la pollinisation à la main avec une épine, et offrit la vanille au monde."},
tip:{en:"Split the pod and scrape the seeds, then bury the empty pod in your sugar jar — it will perfume it for months.",
fr:"Fendez la gousse et grattez les graines, puis enterrez la gousse vide dans votre pot de sucre — elle le parfumera des mois durant."},
pairs:["cream","dark-chocolate","peach","pear","raspberry","coffee"],
svg:'<path class="f3 sf" d="M36 26q-6 26 6 48 3-26-6-48z" transform="rotate(-6 40 50)"/><path class="f3 sf" d="M56 26q6 26-6 48-3-26 6-48z" transform="rotate(6 56 50)"/><path class="f1 sf" d="M48 60l4-6 6 3-2 7-7 2z"/>'},

{id:"wasabi",cat:"spices",name:{en:"Wasabi",fr:"Wasabi"},latin:"Eutrema japonicum",
origin:{en:"Japan",fr:"Japon"},season:[],
flavor:["hot","pungent","fresh","grassy"],
story:{en:"Real wasabi is a rhizome grown in cold running mountain streams, takes two years, and is one of the hardest crops in the world to farm. Almost everything served under the name outside Japan is horseradish, mustard and green dye.",
fr:"Le vrai wasabi est un rhizome cultivé dans des ruisseaux de montagne froids et courants, met deux ans à pousser, et compte parmi les cultures les plus difficiles au monde. Presque tout ce qui est servi sous ce nom hors du Japon est du raifort, de la moutarde et du colorant vert."},
tip:{en:"Grated fresh, it loses its heat within fifteen minutes. That is why it is grated at the counter in front of you and never in advance.",
fr:"Râpé frais, il perd son piquant en quinze minutes. C’est pourquoi on le râpe au comptoir devant vous et jamais à l’avance."},
pairs:["tuna","soy-sauce","rice","tamari","salmon","sesame","spring-onion","scallop"],
svg:'<path class="f3 sf" d="M40 72V44q-6-8 0-14 10 4 8 14v28z"/><path class="f2 sf" d="M50 40q10-8 14 0-8 8-14 4z"/>'},

{id:"white-pepper",cat:"spices",name:{en:"White pepper",fr:"Poivre blanc"},latin:"Piper nigrum",
origin:{en:"Malabar coast, India",fr:"Côte de Malabar, Inde"},season:[],
flavor:["peppery","hot","musky","earthy"],
story:{en:"The same berry as black pepper, but soaked in running water for a week until the outer skin rots away and can be rubbed off. That fermentation is where its barnyard note comes from, and why it tastes nothing like black.",
fr:"La même baie que le poivre noir, mais trempée une semaine en eau courante jusqu’à ce que l’enveloppe pourrisse et se frotte. C’est de cette fermentation que vient sa note d’étable, et pourquoi il n’a rien du goût du noir."},
tip:{en:"Use it where black specks would be visible and unwanted — béchamel, a white fish sauce, a pale soup. That is its real job.",
fr:"Employez-le là où des points noirs se verraient — béchamel, sauce de poisson blanc, potage clair. C’est sa vraie fonction."},
pairs:["cream","butter","potato","scallop","turbot","nutmeg","chicken","comte"],
svg:'<circle class="f3 sf" cx="42" cy="52" r="7"/><circle class="f3 sf" cx="56" cy="56" r="7"/><circle class="f3 sf" cx="47" cy="66" r="7"/><path class="s" d="M38 50q4-3 8 0"/>'},

{id:"zaatar",cat:"spices",name:{en:"Za’atar",fr:"Zaatar"},latin:"زعتر",
origin:{en:"Levant",fr:"Levant"},season:[],
flavor:["herbal","sour","nutty","toasty"],
story:{en:"The word means both the blend and the wild hyssop in it, which is protected in parts of the Levant because over-picking nearly wiped it out. Sumac gives the sourness, toasted sesame the body — a blend that is as much texture as flavour.",
fr:"Le mot désigne à la fois le mélange et l’hysope sauvage qu’il contient, protégée dans certaines régions du Levant où la cueillette excessive a failli l’éradiquer. Le sumac apporte l’acidité, le sésame grillé le corps — un mélange qui est autant texture que saveur."},
tip:{en:"Mix it with olive oil into a paste before spreading on bread. Dry on the surface it just falls off.",
fr:"Mélangez-le à l’huile d’olive en pâte avant de l’étaler sur le pain. Sec en surface, il tombe simplement."},
pairs:["olive-oil","sumac","sesame","flour-t65","yogurt","feta","tomato","cucumber"],
svg:'<path class="f2 sf" d="M32 66q0-16 16-20 16 4 16 20z"/><path class="s" d="M40 58q8-4 16 0M38 64q10-4 20 0"/><circle class="dot" cx="44" cy="54" r="1.4"/>'}
]);
