window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"adzuki",cat:"legumes",name:{en:"Adzuki bean",fr:"Haricot azuki"},latin:"Vigna angularis",
origin:{en:"East Asia",fr:"Asie de l’Est"},season:[],
flavor:["sweet","earthy","nutty","mild"],
story:{en:"In Japan and China it is treated as a dessert ingredient rather than a savoury one — boiled with sugar into anko, the sweet red paste inside almost every traditional confection. Red beans and rice are eaten at celebrations for the auspicious colour.",
fr:"Au Japon et en Chine on le traite en ingrédient de dessert plutôt que salé — bouilli avec du sucre en anko, la pâte rouge sucrée que renferme presque toute confiserie traditionnelle. Haricots rouges et riz se mangent aux fêtes pour la couleur porte-bonheur."},
tip:{en:"Change the water once during cooking if you want a clean sweet paste. The first water carries the bitterness.",
fr:"Changez l’eau une fois en cours de cuisson pour une pâte sucrée nette. La première eau emporte l’amertume."},
pairs:["sugar","rice","sesame","vanilla","coconut-milk","ginger","dark-chocolate","honey"],
svg:'<ellipse class="f1 sf" cx="41" cy="55" rx="6.5" ry="5"/><ellipse class="f1 sf" cx="54" cy="53" rx="6.5" ry="5"/><ellipse class="f1 sf" cx="47" cy="66" rx="6.5" ry="5"/><path class="s" d="M36 55h10M49 53h10"/>'},

{id:"ayocote-bean",cat:"legumes",rare:true,name:{en:"Ayocote bean",fr:"Haricot ayocote"},latin:"Phaseolus coccineus",
origin:{en:"Highland Mexico",fr:"Hauts plateaux du Mexique"},season:[],
flavor:["earthy","meaty","nutty","mild"],
story:{en:"Phaseolus coccineus is a different species from the common bean — perennial, regrowing each year from a starchy root — and Europe kept it for two centuries as a garden climber, grown for its scarlet flowers rather than its seed. In Mexico the pot liquor counts as much as the bean: ayocotes are ladled out in their own dark broth as a course, not a side.",
fr:"Le Phaseolus coccineus est une espèce distincte du haricot commun — vivace, il repart chaque année d’une racine tubéreuse — et l’Europe l’a cultivé deux siècles durant comme grimpante d’ornement, pour ses fleurs écarlates plus que pour sa graine. Au Mexique, le bouillon compte autant que le grain : les ayocotes se servent dans leur jus sombre, en plat à part entière."},
tip:{en:"Hold the pot below a simmer for two to three hours — a rolling boil bursts these skins long before the chestnut-textured centre gives way. Never drain them; that broth is the sauce.",
fr:"Maintenez la casserole juste sous le frémissement deux à trois heures : une ébullition franche fait éclater la peau bien avant que le cœur, à la texture de châtaigne, ne s’attendrisse. Ne les égouttez jamais — ce bouillon est la sauce."},
pairs:["epazote","avocado-leaf","ancho-chilli","mexican-oregano","lard","onion","nopal","tomato"],
svg:'<path class="f3 sf" d="M36 30q19-4 25 13t-11 27q-17 4-21-11t7-29z"/><path class="s" d="M39 44q4 7 2 14"/><path class="f2 sf" d="M58 66q11-3 13 5t-10 7-6-8z"/>'},

{id:"beluga-lentil",cat:"legumes",name:{en:"Beluga lentil",fr:"Lentille beluga"},latin:"Lens culinaris",
origin:{en:"Canada & North America",fr:"Canada & Amérique du Nord"},season:[],
flavor:["earthy","nutty","mild","umami"],
story:{en:"Named for the caviar it resembles once cooked — small, glossy and jet black. The colour is anthocyanin and it survives cooking better than most, which is why the lentil stays black rather than turning the muddy brown of its cousins.",
fr:"Nommée d’après le caviar qu’elle évoque une fois cuite — petite, brillante et noire de jais. La couleur vient des anthocyanes et résiste mieux que la plupart à la cuisson, d’où une lentille qui reste noire au lieu de virer au brun boueux de ses cousines."},
tip:{en:"Serve it where the colour shows — under white fish, beside a poached egg. Buried in a brown stew you have wasted the point.",
fr:"Servez-la là où la couleur se voit — sous un poisson blanc, à côté d’un œuf poché. Noyée dans un ragoût brun, l’intérêt est perdu."},
pairs:["salmon","creme-fraiche","shallot","lemon","dill","olive-oil","egg","chives"],
svg:'<circle class="f1 sf" cx="40" cy="52" r="6.5"/><circle class="f1 sf" cx="55" cy="55" r="6.5"/><circle class="f1 sf" cx="46" cy="65" r="6.5"/><circle class="f1 sf" cx="59" cy="66" r="5.5"/>'},

{id:"black-bean",cat:"legumes",name:{en:"Black bean",fr:"Haricot noir"},latin:"Phaseolus vulgaris",
origin:{en:"Mexico & Central America",fr:"Mexique & Amérique centrale"},season:[],
flavor:["earthy","sweet","creamy","umami"],
story:{en:"The backbone of Brazilian feijoada and Cuban moros y cristianos, and it colours its cooking liquid deep purple-black — that liquid is not waste but the sauce, and throwing it away is the commonest mistake made with this bean.",
fr:"L’ossature de la feijoada brésilienne et des moros y cristianos cubains, et il colore son eau de cuisson en noir violacé — ce liquide n’est pas un déchet mais la sauce, et le jeter est l’erreur la plus fréquente avec ce haricot."},
tip:{en:"Keep the cooking liquid and reduce it. It is where the flavour and the body of the dish live.",
fr:"Gardez l’eau de cuisson et faites-la réduire. C’est là que résident le goût et le corps du plat."},
pairs:["cumin","lime","cilantro","chili","garlic","onion","avocado","orange"],
svg:'<ellipse class="f1 sf" cx="41" cy="54" rx="8.5" ry="6"/><ellipse class="f1 sf" cx="56" cy="56" rx="8.5" ry="6"/><ellipse class="f1 sf" cx="47" cy="67" rx="8.5" ry="6"/>'},

{id:"black-chickpea",cat:"legumes",name:{en:"Black chickpea",fr:"Pois chiche noir"},latin:"Cicer arietinum",
origin:{en:"Murgia Carsica, Puglia",fr:"Murgia Carsica, Pouilles"},season:[],
flavor:["earthy","nutty","mild"],
story:{en:"The black chickpea of the Murgia Carsica, around Cassano delle Murge in Puglia, was nearly abandoned because its thick wrinkled skin demands twelve hours of soaking and two of cooking. It carries roughly three times the fibre of a common chickpea, which is also why it stays whole where the pale ones collapse.",
fr:"Le pois chiche noir de la Murgia Carsica, autour de Cassano delle Murge dans les Pouilles, a failli disparaître : sa peau épaisse et ridée exige douze heures de trempage et deux heures de cuisson. Il contient environ trois fois plus de fibres qu’un pois chiche ordinaire, ce qui explique aussi qu’il reste entier quand les blonds s’effondrent."},
tip:{en:"Soak overnight at the very least, then cook two hours at a bare tremble. The skins tint the water grey-violet - keep that broth, most of the flavour has gone into it.",
fr:"Trempez-le une nuit au minimum, puis cuisez-le deux heures à frémissement à peine perceptible. Les peaux teintent l’eau d’un gris violacé : gardez ce bouillon, l’essentiel du goût y est passé."},
pairs:["olive-oil","rosemary","garlic","cavolo-nero","anchovy","semola-rimacinata"],
svg:'<path class="f3 sf" d="M30 26l16 8a18 18 0 1 1-16-8z"/><path class="f2 sf" d="M62 46l10 5a12 12 0 1 1-10-5z"/><path class="s" d="M36 44q10 4 14 14"/>'},

{id:"cowpea",cat:"legumes",name:{en:"Black-eyed pea",fr:"Haricot cornille"},latin:"Vigna unguiculata",
origin:{en:"West Africa",fr:"Afrique de l’Ouest"},season:[],
flavor:["earthy","creamy","mild"],
story:{en:"The black-eyed pea is a Vigna, domesticated in West Africa and carried to the American South, where it became Hoppin' John. It is not a Phaseolus bean at all, which is why it behaves like none of them in the pot.",
fr:"Le haricot cornille est un Vigna, domestiqué en Afrique de l’Ouest puis emporté vers le Sud des États-Unis, où il est devenu le Hoppin’ John. Ce n’est pas un Phaseolus, et c’est pour cela qu’il ne se comporte comme aucun autre haricot dans la casserole."},
tip:{en:"Cook it dry and unsoaked, thirty-five to forty-five minutes, salting from the start so the skins hold. Soak it and you get puree.",
fr:"Cuisez-le sec, sans trempage, trente-cinq à quarante-cinq minutes, en salant dès le départ pour que les peaux tiennent. Trempé, il part en purée."},
pairs:["rice","pork-belly","thyme","tomato","spring-onion","chili"],
svg:'<ellipse class="f1 sf" cx="44" cy="42" rx="22" ry="15"/><ellipse class="f3" cx="44" cy="42" rx="6" ry="3.5"/><ellipse class="f2 sf" cx="54" cy="66" rx="18" ry="12"/><ellipse class="f3" cx="54" cy="66" rx="5" ry="3"/>'},

{id:"lentille-blonde",cat:"legumes",rare:true,name:{en:"Blond lentil",fr:"Lentille blonde de Saint-Flour"},latin:"Lens culinaris",
origin:{en:"Planeze de Saint-Flour, Cantal",fr:"Planèze de Saint-Flour, Cantal"},season:[],
flavor:["sweet","mild","earthy"],
story:{en:"Grown on the basalt plateau of the Planeze de Saint-Flour since the Middle Ages, the blond lentil had all but vanished by the 1960s and came back with a Label Rouge in 2009 and an IGP behind it. Production runs to some eighty tonnes a year against six thousand for the green lentil of Le Puy - and the two are opposite tools.",
fr:"Cultivée depuis le Moyen Âge sur le plateau basaltique de la Planèze de Saint-Flour, la lentille blonde avait presque disparu dans les années 1960 ; elle est revenue avec un Label rouge en 2009, puis une IGP. On en produit quelque quatre-vingts tonnes par an contre six mille pour la verte du Puy — et ce sont deux outils opposés."},
tip:{en:"It slumps at twenty-five minutes, and that is the point: cook it in milk or stock for a puree or a soup. Do not build a salad on it, the grain will not hold.",
fr:"Elle s’affaisse en vingt-cinq minutes, et c’est tout l’intérêt : cuisez-la au lait ou au bouillon, pour une purée ou une soupe. N’en faites pas une salade, le grain ne tiendra pas."},
pairs:["carrot","onion","poitrine-fumee","thyme","cream","walnut-oil"],
svg:'<circle class="f1 sf" cx="42" cy="42" r="16"/><circle class="s" cx="42" cy="42" r="8"/><path class="f2 sf" d="M30 68q16-12 32 0-16 10-32 0z"/><path class="s" d="M30 68h32"/>'},

{id:"borlotti",cat:"legumes",name:{en:"Borlotti bean",fr:"Haricot borlotti"},latin:"Phaseolus vulgaris",
origin:{en:"Italy, from the Americas",fr:"Italie, depuis les Amériques"},season:[8,9,10],
flavor:["creamy","nutty","earthy","sweet"],
story:{en:"The cranberry-splashed pod and bean are spectacular raw and lose every trace of the pattern in the pot — they cook to a uniform brown. Nothing is wrong; the pigment is simply not heat stable, and Italian cooks have never minded.",
fr:"La cosse et le grain éclaboussés de rouge sont spectaculaires crus et perdent toute trace du motif à la casserole — ils cuisent en brun uniforme. Rien d’anormal : le pigment n’est simplement pas stable à la chaleur, et les cuisiniers italiens ne s’en sont jamais souciés."},
tip:{en:"Cook them with a whole peeled onion, a carrot and a stick of celery, then discard all three. It is the Italian way and it works.",
fr:"Cuisez-les avec un oignon épluché entier, une carotte et une branche de céleri, puis jetez les trois. C’est la méthode italienne et elle fonctionne."},
pairs:["sage","olive-oil","garlic","tomato","rosemary","pecorino","guanciale","cavolo-nero"],
svg:'<ellipse class="f2 sf" cx="41" cy="54" rx="9" ry="6.5"/><ellipse class="f2 sf" cx="56" cy="57" rx="9" ry="6.5"/><ellipse class="f2 sf" cx="47" cy="68" rx="9" ry="6.5"/><circle class="dot" cx="39" cy="53" r="1.4"/><circle class="dot" cx="57" cy="56" r="1.4"/>'},

{id:"cannellini",cat:"legumes",name:{en:"Cannellini bean",fr:"Haricot cannellini"},latin:"Phaseolus vulgaris",
origin:{en:"Tuscany, Italy",fr:"Toscane, Italie"},season:[],
flavor:["creamy","mild","nutty","earthy"],
story:{en:"Tuscans are nicknamed mangiafagioli, bean-eaters, and this is the bean they mean. The classic preparation is al fiasco — cooked overnight in a wine flask buried in the dying embers of a fire, with oil, garlic and sage.",
fr:"On surnomme les Toscans mangiafagioli, mangeurs de haricots, et c’est de celui-ci qu’il s’agit. La préparation classique est al fiasco — cuits toute la nuit dans une fiasque à vin enfouie sous les braises mourantes, avec huile, ail et sauge."},
tip:{en:"Save a ladle of the cooking liquid to loosen any purée. It emulsifies with olive oil far better than water does.",
fr:"Réservez une louche d’eau de cuisson pour détendre une purée. Elle s’émulsionne avec l’huile d’olive bien mieux que l’eau."},
pairs:["sage","olive-oil","garlic","rosemary","tomato","cavolo-nero","parmesan","escarole"],
svg:'<ellipse class="f3 sf" cx="40" cy="54" rx="9" ry="6"/><ellipse class="f3 sf" cx="56" cy="57" rx="9" ry="6"/><ellipse class="f3 sf" cx="47" cy="68" rx="9" ry="6"/>'},

{id:"chana-dal",cat:"legumes",name:{en:"Chana dal",fr:"Chana dal (pois chiche cassé)"},latin:"Cicer arietinum",
origin:{en:"Northern India",fr:"Inde du Nord"},season:[],
flavor:["nutty","earthy","sweet","toasty"],
story:{en:"It is the small dark desi chickpea, not the pale kabuli, hulled and split, and it carries one of the lowest glycaemic indices of any everyday starch. Dry-roasted whole it becomes daria, the crunchy split pea South Indian cooks drop into hot oil at the start of a tempering.",
fr:"C’est le petit pois chiche desi, sombre et non le kabuli pâle, décortiqué et cassé ; il affiche l’un des index glycémiques les plus bas parmi les féculents courants. Grillé à sec, il devient le daria, ce pois croquant que les cuisiniers du sud de l’Inde jettent dans l’huile chaude au début d’un tadka."},
tip:{en:"Soaked an hour it cooks in about 35 minutes and the pieces stay whole — this is the dal for texture, not purée. A pinch of asafoetida in the tempering does more for it than any amount of extra salt.",
fr:"Trempé une heure, il cuit en 35 minutes environ et les grains restent entiers : c’est le dal de la texture, pas de la purée. Une pincée d’asafoetida dans le tadka lui apporte plus que n’importe quel excès de sel."},
pairs:["cumin","asafoetida","ginger","turmeric","ghee","curry-leaf","coconut","chili"],
svg:'<path class="f2 sf" d="M26 58a11 11 0 0 1 22 0z"/><path class="f1 sf" d="M44 70a12 12 0 0 1 24 0z"/><path class="f3 sf" d="M38 44a10 10 0 0 1 20 0z"/><path class="f2 sf" d="M56 58a9 9 0 0 1 18 0z"/>'},

{id:"chickpeas",cat:"legumes",name:{en:"Chickpeas",fr:"Pois chiches"},latin:"Cicer arietinum",
origin:{en:"Fertile Crescent & Anatolia",fr:"Croissant fertile & Anatolie"},season:[],
flavor:["nutty","earthy","buttery"],
story:{en:"Rome’s greatest orator, Cicero, owed his family name to the chickpea (cicer) — an ancestor supposedly had a chickpea-shaped wart, and he refused to change the name, promising to make it glorious instead. He did.",
fr:"Le plus grand orateur de Rome, Cicéron, devait son nom au pois chiche (cicer) — un ancêtre aurait porté une verrue en forme de pois chiche, et il refusa d’en changer, promettant plutôt de rendre ce nom glorieux. Il tint parole."},
tip:{en:"Keep the cooking water: whipped, it foams like egg white. A tin of chickpeas plus sesame paste and lemon is a five-minute feast.",
fr:"Gardez l’eau de cuisson : fouettée, elle monte comme du blanc d’œuf. Une boîte de pois chiches, de la crème de sésame et du citron : festin en cinq minutes."},
pairs:["sesame","lemon","cumin","garlic","spinach","tomato"],
svg:'<path class="f1 sf" d="M40 44a8 8 0 11-1 8q-2-4 1-8z"/><path class="f1 sf" d="M56 42a8 8 0 11-1 8q-2-4 1-8z"/><path class="f1 sf" d="M48 58a8 8 0 11-1 8q-2-4 1-8z"/>'},

{id:"cicerchia",cat:"legumes",rare:true,name:{en:"Cicerchia",fr:"Gesse (pois carré)"},latin:"Lathyrus sativus",
origin:{en:"Central Italy and the Mediterranean",fr:"Italie centrale et Méditerranée"},season:[],
flavor:["earthy","bitter","nutty","creamy"],
story:{en:"Cicerchia carries a neurotoxin, β-ODAP, that caused outbreaks of lathyrism in Europe whenever it became the only thing left to eat — and it became that often, because the plant yields through drought and flood alike. Serra de' Conti in the Marche keeps a low-toxin local variety alive as a Slow Food presidium, sown now by choice rather than by desperation.",
fr:"La gesse renferme une neurotoxine, la β-ODAP, responsable des poussées de lathyrisme en Europe chaque fois qu’elle restait le seul aliment disponible — ce qui arrivait souvent, la plante produisant aussi bien en sécheresse qu’en terrain noyé. Serra de’ Conti, dans les Marches, maintient une variété locale peu toxique en sentinelle Slow Food, semée aujourd’hui par choix et non par détresse."},
tip:{en:"Soak 12 to 24 hours through three changes of water and throw every soak away, then simmer 90 minutes — the water carries off the toxin and the bitterness together. It never firms up the way chickpeas do: expect a loose creamy mass, and dress it while warm.",
fr:"Faites tremper 12 à 24 heures en changeant l’eau trois fois, jetez chaque eau de trempage, puis laissez frémir 90 minutes : l’eau emporte à la fois la toxine et l’amertume. Elle ne se tient jamais comme le pois chiche — attendez-vous à une masse crémeuse et lâche, à assaisonner tiède."},
pairs:["rosemary","olive-oil","garlic","sage","chestnut","guanciale","bay-leaf","pecorino"],
svg:'<path class="f2 sf" d="M28 44l14-9 13 10-8 14z"/><path class="f1 sf" d="M55 33l15 7-5 15-13-11z"/><path class="f3 sf" d="M34 61l13-5 11 7-9 11-13-5z"/><path class="s" d="M40 42l6 6M60 40l4 5"/>'},

{id:"coco-de-paimpol",cat:"legumes",name:{en:"Coco de Paimpol",fr:"Coco de Paimpol"},latin:"Phaseolus vulgaris",
origin:{en:"Côtes-d’Armor, Brittany",fr:"Côtes-d’Armor, Bretagne"},season:[8,9,10],
flavor:["creamy","sweet","mild","earthy"],
story:{en:"A fresh shelling bean rather than a dried one, sold still in its marbled pod and podded by hand — Brittany calls the work le plumage. It holds an AOC, and the season is short enough that most of the country never sees it.",
fr:"Un haricot demi-sec plutôt que sec, vendu encore dans sa cosse marbrée et écossé à la main — la Bretagne appelle ce travail le plumage. Il détient une AOC, et la saison est assez brève pour que la plus grande part du pays ne le voie jamais."},
tip:{en:"It needs no soaking, unlike every dried bean. Forty minutes in unsalted water and it is done.",
fr:"Il ne se trempe pas, contrairement à tout haricot sec. Quarante minutes à l’eau non salée et c’est prêt."},
pairs:["thyme","garlic","tomato","olive-oil","lamb","onion","bay-leaf","parsley"],
svg:'<path class="f3 sf" d="M28 58q14-18 40-14-6 20-30 24-12 2-10-10z"/><circle class="f2 sf" cx="42" cy="54" r="5"/><circle class="f2 sf" cx="54" cy="50" r="5"/>'},

{id:"douchi",cat:"legumes",name:{en:"Douchi",fr:"Haricots noirs fermentés (douchi)"},latin:"Glycine max",
origin:{en:"Sichuan and Guangdong",fr:"Sichuan et Guangdong"},season:[],
flavor:["salty","umami","pungent"],
story:{en:"Sealed jars of fermented black beans were recovered from the Han-dynasty tombs at Mawangdui, which makes them one of the oldest soy preparations still cooked from daily. Unlike every paste made from the same bean, they are fermented dry and kept whole, so the salt stays on the outside and the funk is only released when they are crushed.",
fr:"Des jarres scellées de haricots noirs fermentés ont été exhumées des tombes Han de Mawangdui, ce qui en fait l'une des plus anciennes préparations de soja encore cuisinées au quotidien. Contrairement à toutes les pâtes tirées de la même fève, ils fermentent à sec et restent entiers : le sel demeure en surface et le fumet ne se libère qu'à l'écrasement."},
tip:{en:"Rinse them a few seconds to take the surface salt off, then crush them roughly under the flat of the knife and drop them into hot oil before anything else — left whole they stay mute. Salt the dish only at the end.",
fr:"Rincez-les quelques secondes pour ôter le sel de surface, écrasez-les grossièrement sous le plat du couteau et jetez-les dans l'huile chaude avant tout le reste : entiers, ils restent muets. Ne salez le plat qu'à la fin."},
pairs:["garlic","ginger","chili","pork","sea-bass","doubanjiang","spring-onion","shaoxing-wine"],
svg:'<path class="f1 sf" d="M28 52h40q-2 18-20 18t-20-18z"/><path class="f3 sf" d="M32 52q4-10 16-10t16 10z"/><circle class="dot" cx="42" cy="46" r="3"/><circle class="dot" cx="53" cy="45" r="3"/><circle class="dot" cx="47" cy="38" r="3"/>'},

{id:"dried-fava",cat:"legumes",name:{en:"Dried broad bean",fr:"Fève sèche"},latin:"Vicia faba",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["earthy","nutty","mild","bitter"],
story:{en:"Egypt eats it at breakfast as ful medames, simmered overnight in a narrow-necked pot, and the dish is older than the pyramids. In Sicily and Puglia it is boiled to a purée called macco and served with wild greens.",
fr:"L’Égypte la mange au petit-déjeuner en ful medames, mijotée toute la nuit dans une jarre à col étroit, et le plat est plus ancien que les pyramides. En Sicile et dans les Pouilles on la réduit en purée, le macco, servi avec des herbes sauvages."},
tip:{en:"Buy them already skinned if you can. Peeling a kilo of soaked dried favas by hand is an afternoon's work.",
fr:"Achetez-les décortiquées si possible. Peler un kilo de fèves sèches trempées à la main occupe un après-midi."},
pairs:["olive-oil","cumin","lemon","garlic","parsley","chili","escarole","onion"],
svg:'<path class="f2 sf" d="M34 34q-6 22 4 34t18-4q4-16-6-28t-16-2z"/><path class="s" d="M40 46q6 12 8 20"/>'},

{id:"faba-asturiana",cat:"legumes",luxe:true,name:{en:"Faba asturiana",fr:"Fabes de la Granja"},latin:"Phaseolus vulgaris",
origin:{en:"Asturias, northern Spain",fr:"Asturies, Espagne du Nord"},season:[9,10],
flavor:["buttery","creamy","mild"],
story:{en:"The variety is Granja Asturiana, long and flat and ivory, selected around a single dish; the protected designation demands a skin fine enough to go unnoticed on the palate and a grain that holds its shape through three hours in the pot. Cooks still interrupt the boil two or three times with a splash of cold water — asustar les fabes, frightening the beans — a habit inherited from charcoal ranges that no modern hob requires.",
fr:"La variété est la Granja Asturiana, longue, plate et ivoire, sélectionnée autour d’un seul plat ; l’appellation exige une peau assez fine pour passer inaperçue en bouche et un grain qui tienne sa forme après trois heures de cuisson. Les cuisiniers coupent encore l’ébullition deux ou trois fois d’un filet d’eau froide — asustar les fabes, « effrayer » les haricots — habitude héritée des fourneaux à charbon dont aucune plaque moderne n’a besoin."},
tip:{en:"Soak overnight, then hold the pot at a bare tremble; one real boil splits the skins and clouds the fabada past saving. Skim the fat rendered by the compango once, early, rather than chasing it at the table.",
fr:"Trempage d’une nuit, puis maintenez la marmite à peine frémissante : une seule ébullition franche fend les peaux et trouble la fabada sans retour. Dégraissez une fois, tôt, le gras rendu par le compango, plutôt que de le poursuivre à table."},
pairs:["chorizo","lard","saffron","onion","bay-leaf","clam","parsley"],
svg:'<path class="f1 sf" d="M26 34q22-10 40 2 8 6 4 14t-16 6q-16-2-26-10t-2-12z"/><path class="s" d="M30 38q20-4 34 6"/><path class="f2 sf" d="M28 60q20-8 38 2 8 5 4 12t-16 5q-16-2-26-9t0-10z"/><path class="s" d="M32 63q18-3 32 6"/>'},

{id:"furu",cat:"legumes",name:{en:"Fermented bean curd",fr:"Tofu fermenté (furu)"},latin:"Glycine max",
origin:{en:"China",fr:"Chine"},season:[],
flavor:["salty","pungent","rich"],
story:{en:"Cubes of tofu are grown over with a white Mucor mould until they are furred like a young cheese rind, then salted and jarred in brine, rice wine or red yeast rice — which is where the crimson version takes both its colour and its name. Nineteenth-century European visitors filed it under cheese, and the texture is why: nothing else made from soy behaves like it.",
fr:"Des cubes de tofu sont couverts d'une moisissure blanche du genre Mucor jusqu'à se feutrer comme une jeune croûte de fromage, puis salés et mis en pot dans la saumure, l'alcool de riz ou la levure de riz rouge — d'où la couleur et le nom de la version pourpre. Les voyageurs européens du XIXᵉ siècle le rangeaient parmi les fromages, et c'est la texture qui l'explique : rien d'autre issu du soja ne se comporte ainsi."},
tip:{en:"One cube mashed with a spoonful of its own brine will season a whole wok of greens; it runs about as salty as anchovy paste, so nothing else salted goes in. Take it from the jar with a dry spoon or the surface spoils within the week.",
fr:"Un cube écrasé avec une cuillerée de sa propre saumure assaisonne un wok entier de légumes verts ; il sale à peu près comme la pâte d'anchois, donc rien d'autre de salé n'entre dans le plat. Prélevez-le avec une cuillère sèche, sinon la surface tourne en une semaine."},
pairs:["water-spinach","garlic","rice","pork-belly","chili","sesame-oil","spring-onion","shaoxing-wine"],
svg:'<path class="s" d="M34 32h28v7H34z"/><path class="f1 sf" d="M36 39h24v35q0 4-4 4H40q-4 0-4-4z"/><path class="f3 sf" d="M40 55h9v9h-9zM52 61h6v6h-6zM42 68h9v8h-9z"/><path class="s" d="M36 48h24"/>'},

{id:"flageolet",cat:"legumes",name:{en:"Flageolet",fr:"Flageolet"},latin:"Phaseolus vulgaris",
origin:{en:"Brittany, France",fr:"Bretagne, France"},season:[],
flavor:["delicate","fresh","mild","grassy"],
story:{en:"Picked before maturity, which is why it stays pale green rather than turning white — the bean is harvested young and dried immature. A Breton grower named Chevrier fixed the technique in the 1870s, and the French still call it the chevrier.",
fr:"Cueilli avant maturité, d’où sa couleur vert pâle plutôt que blanche — le grain est récolté jeune et séché immature. Un maraîcher breton nommé Chevrier fixa la technique dans les années 1870, et les Français l’appellent encore le chevrier."},
tip:{en:"It is the classic bean for gigot d'agneau, and it wants nothing more than butter, garlic and parsley. Do not overwhelm it.",
fr:"C’est le haricot classique du gigot d’agneau, et il ne demande que du beurre, de l’ail et du persil. Ne le noyez pas."},
pairs:["lamb","garlic","butter","parsley","cream","thyme","shallot","rosemary"],
svg:'<ellipse class="f3 sf" cx="40" cy="54" rx="9" ry="6"/><ellipse class="f3 sf" cx="55" cy="58" rx="9" ry="6"/><ellipse class="f3 sf" cx="47" cy="68" rx="9" ry="6"/>'},

{id:"judion",cat:"legumes",rare:true,luxe:true,name:{en:"Judión bean",fr:"Judión (haricot géant d’Espagne)"},latin:"Phaseolus coccineus",
origin:{en:"La Granja de San Ildefonso, Segovia",fr:"La Granja de San Ildefonso, Ségovie"},season:[],
flavor:["buttery","creamy","mild"],
story:{en:"The scarlet runner reached the royal gardens at La Granja as an ornamental, grown for its red flowers and fed to the palace's game birds before anyone thought to eat it. Gardeners selected it for the pot over generations, and the stew that made it famous only reached restaurant menus in the 1950s.",
fr:"Le haricot d’Espagne arriva aux jardins royaux de La Granja comme plante d’ornement, cultivé pour ses fleurs rouges et donné au gibier du palais avant que quiconque songe à le manger. Les jardiniers l’ont sélectionné pour la marmite au fil des générations, et le ragoût qui l’a rendu célèbre n’a gagné les cartes qu’au cours des années 1950."},
tip:{en:"Soak twelve hours, start in cold unsalted water and never let it do more than tremble — a rolling boil bursts the skins and loses the whole point of the bean. Salt only once they are tender.",
fr:"Trempez-les douze heures, démarrez à l’eau froide non salée et ne dépassez jamais le frémissement : une ébullition vive fait éclater la peau et ruine tout l’intérêt du grain. Salez seulement une fois tendres."},
pairs:["chorizo","morcilla-de-burgos","pimenton-de-la-vera","bay-leaf","garlic","olive-oil"],
svg:'<ellipse class="f1 sf" cx="48" cy="50" rx="25" ry="18"/><path class="s" d="M32 45q16-8 32 0"/><ellipse class="f3 sf" cx="48" cy="67" rx="6" ry="2.5"/>'},

{id:"kidney-bean",cat:"legumes",name:{en:"Kidney bean",fr:"Haricot rouge"},latin:"Phaseolus vulgaris",
origin:{en:"Peru & Central America",fr:"Pérou & Amérique centrale"},season:[],
flavor:["earthy","sweet","creamy","mild"],
story:{en:"Raw or undercooked, it is genuinely poisonous — it carries phytohaemagglutinin, and as few as four raw beans can make you seriously ill. Ten minutes at a hard boil destroys it, but a slow cooker never gets hot enough on its own.",
fr:"Crus ou insuffisamment cuits, ils sont réellement toxiques — ils portent de la phytohémagglutinine, et quatre grains crus suffisent à rendre gravement malade. Dix minutes à gros bouillons la détruisent, mais une mijoteuse seule n’atteint jamais cette température."},
tip:{en:"Boil hard for ten full minutes before any slow cooking. This is the one bean where the instruction is a safety rule, not a preference.",
fr:"Faites bouillir à gros bouillons dix minutes pleines avant toute cuisson lente. C’est le seul haricot où la consigne est une règle de sécurité, non une préférence."},
pairs:["chili","cumin","onion","tomato","garlic","paprika","rice","cilantro"],
svg:'<path class="f1 sf" d="M32 56q4-12 16-10t14 12-12 12-18-14z"/><path class="f1 sf" d="M44 70q4-8 14-6t8 10-14 6-8-10z"/>'},

{id:"kinako",cat:"legumes",name:{en:"Kinako",fr:"Kinako (farine de soja grillé)"},latin:"Glycine max",
origin:{en:"Japan",fr:"Japon"},season:[],
flavor:["nutty","toasty","mild","earthy"],
story:{en:"Kinako is nothing but soybeans dry-roasted and milled, and the name means, flatly, yellow flour. The roast is the whole of it — the same beans boiled taste of very little, which is why kinako is a finishing ingredient and never a cooking one.",
fr:"Le kinako n’est rien d’autre que du soja torréfié puis moulu, et son nom veut dire platement farine jaune. La torréfaction fait tout : les mêmes graines bouillies ne goûtent presque rien, ce qui fait du kinako un ingrédient de finition et jamais de cuisson."},
tip:{en:"Toast it thirty seconds in a dry pan before use; kinako that has sat on the shelf smells of cardboard and the heat brings it straight back. Cut it with sugar at four to one plus a good pinch of salt, or it clings to the tongue and dries the mouth.",
fr:"Passez-le trente secondes à la poêle sèche avant emploi : un kinako qui a traîné sent le carton et la chaleur le ramène aussitôt. Coupez-le de sucre à quatre pour un, avec une bonne pincée de sel, sinon il colle à la langue et assèche la bouche."},
pairs:["adzuki","kokuto","mizuame","glutinous-rice","matcha","honey"],
svg:'<ellipse class="f3 sf" cx="36" cy="32" rx="10" ry="8"/><ellipse class="f2 sf" cx="56" cy="38" rx="10" ry="8"/><path class="f1 sf" d="M20 66q14-12 28-10t28 10q-14 6-28 6t-28-6z"/><path class="s" d="M33 29q4-3 8-1"/>'},

{id:"koya-dofu",cat:"legumes",name:{en:"Koya-dofu",fr:"Tofu séché (koya-dofu)"},latin:"Glycine max",
origin:{en:"Mount Kōya, Wakayama",fr:"Mont Kōya, Wakayama"},season:[],
flavor:["mild","nutty"],
story:{en:"It takes its name from the monastery complex on Mount Kōya, where tofu left out in the winter cold froze, thawed and dried into something that kept a year on a shelf. The ice crystals are the structure: they shoulder the protein aside as they grow, and the sponge they leave behind is the reason the block drinks dashi the way it does.",
fr:"Il tient son nom du complexe monastique du mont Kōya, où le tofu laissé dehors dans le froid de l'hiver gelait, dégelait et séchait en quelque chose qui se gardait un an sur une étagère. Les cristaux de glace sont la structure : en grossissant ils repoussent les protéines, et l'éponge qu'ils laissent explique pourquoi le bloc boit ainsi le dashi."},
tip:{en:"Modern blocks need no hot pre-soak: five minutes in warm dashi is enough. Press it gently between the palms rather than wringing it out, and hold the simmer at a bare tremble — a real boil tears the sponge apart.",
fr:"Les blocs modernes ne demandent aucun trempage à l'eau chaude : cinq minutes dans un dashi tiède suffisent. Pressez-le doucement entre les paumes plutôt que de le tordre, et maintenez la cuisson à peine frémissante : une vraie ébullition déchire l'éponge."},
pairs:["kombu","dried-shiitake-donko","hon-mirin","soy-sauce","carrot","mangetout","egg","chicken"],
svg:'<path class="f1 sf" d="M30 36h36v32H30z"/><path class="s" d="M30 36 38 30h36v32l-8 6"/><circle class="s" cx="40" cy="46" r="3"/><circle class="s" cx="53" cy="42" r="2.5"/><circle class="s" cx="46" cy="58" r="3.5"/><circle class="s" cx="58" cy="57" r="2.5"/>'},

{id:"lentils",cat:"legumes",name:{en:"Lentils",fr:"Lentilles"},latin:"Lens culinaris",
origin:{en:"Fertile Crescent",fr:"Croissant fertile"},season:[],
flavor:["earthy","mild","nutty"],
story:{en:"Esau sold his birthright for a bowl of lentil stew — the most expensive lunch in scripture. The optical lens is named after this seed, not the other way round; Italians eat them at New Year, each little disc a coin of luck.",
fr:"Ésaü vendit son droit d’aînesse pour un plat de lentilles — le déjeuner le plus cher des Écritures. La lentille optique doit son nom à cette graine, et non l’inverse ; les Italiens en mangent au Nouvel An, chaque petit disque valant une pièce de fortune."},
tip:{en:"Salt them only at the end — salted water toughens their skins. The little green ones from Le Puy hold their shape best in salads.",
fr:"Ne les salez qu’en fin de cuisson — l’eau salée durcit leur peau. Les petites vertes du Puy tiennent le mieux en salade."},
pairs:["cumin","bay-leaf","carrot","pork","yogurt","cilantro","turmeric"],
svg:'<path class="f2 sf" d="M36 46a5.5 5.5 0 100 .1zM52 42a5.5 5.5 0 100 .1zM62 52a5.5 5.5 0 100 .1zM42 58a5.5 5.5 0 100 .1zM54 62a5.5 5.5 0 100 .1zM34 64a5.5 5.5 0 100 .1z"/>'},

{id:"lupini",cat:"legumes",name:{en:"Lupini beans",fr:"Lupins"},latin:"Lupinus albus",
origin:{en:"Mediterranean basin",fr:"Bassin méditerranéen"},season:[],
flavor:["salty","bitter","fresh"],
story:{en:"The bitterness is lupanine, an alkaloid the plant makes as a defence; Roman and Egyptian eaters dealt with it by boiling the beans and then leaving them for days in running water. Sweet, low-alkaloid lupins were only bred in the 1930s, and most beans sold in brine are still the bitter kind, tamed.",
fr:"L’amertume, c’est la lupanine, un alcaloïde défensif de la plante ; Romains et Égyptiens la chassaient en faisant bouillir les graines puis en les laissant plusieurs jours dans l’eau courante. Les lupins doux, pauvres en alcaloïdes, ne datent que des années 1930 : la plupart des lupins en saumure restent des amers, domptés."},
tip:{en:"Taste one before serving: any bitterness left means the water needs changing again, daily, until it goes. Squeeze the bean out of its skin between your teeth, and never cook it soft — the snap is the point.",
fr:"Goûtez-en un avant de servir : la moindre amertume persistante impose de renouveler l’eau, chaque jour, jusqu’à disparition. On presse la graine hors de sa peau entre les dents ; ne la cuisez jamais longuement, tout est dans le croquant."},
pairs:["lemon","olive-oil","olive-castelvetrano","oregano","garlic","chili","parsley"],
svg:'<ellipse class="f2 sf" cx="38" cy="44" rx="16" ry="13"/><ellipse class="f1 sf" cx="58" cy="60" rx="16" ry="13"/><path class="s" d="M28 40q10 6 20 0M48 56q10 6 20 0"/><circle class="dot" cx="53" cy="47" r="2"/><circle class="dot" cx="73" cy="63" r="2"/>'},

{id:"mogette",cat:"legumes",name:{en:"Mogette de Vendée",fr:"Mogette de Vendée"},latin:"Phaseolus vulgaris",
origin:{en:"Vendée, western France",fr:"Vendée"},season:[7,8,9],
flavor:["creamy","mild","buttery"],
story:{en:"Physicians were already recording bean fields in the Vendée at the end of the seventeenth century, and the name is usually traced to the mounges — the monks of the local abbeys. Picked half-dry in late summer, the bean skips the drying yard entirely and goes to market as a fresh vegetable.",
fr:"Les médecins signalaient déjà des champs de haricots en Vendée à la fin du XVIIe siècle, et l’on rattache d’ordinaire le nom aux « mounges », les moines des abbayes locales. Cueillie demi-sèche à la fin de l’été, elle saute l’étape du séchoir et part au marché comme un légume frais."},
tip:{en:"Half-dry mogettes need no soaking at all: cold unsalted water, a bare simmer, and they are creamy in about forty minutes — salt any earlier and the skins toughen. Fully dried ones want a night in water and twice the time.",
fr:"La mogette demi-sèche ne se trempe pas : eau froide non salée, frémissement, et elle est fondante en quarante minutes environ — salée plus tôt, la peau durcit. Sèche, elle réclame une nuit de trempage et le double de cuisson."},
pairs:["butter","garlic","jambon-de-vendee","bay-leaf","thyme","cream","parsley"],
svg:'<path class="f2 sf" d="M22 60q16-22 52-24 4 14-14 22t-38 2z"/><path class="s" d="M22 60q14-30 52-24"/><ellipse class="f1 sf" cx="36" cy="54" rx="8" ry="6"/><ellipse class="f1 sf" cx="52" cy="48" rx="8" ry="6"/><ellipse class="f1 sf" cx="67" cy="42" rx="8" ry="6"/>'},

{id:"mung-bean",cat:"legumes",name:{en:"Mung bean",fr:"Haricot mungo"},latin:"Vigna radiata",
origin:{en:"India",fr:"Inde"},season:[],
flavor:["sweet","fresh","mild","grassy"],
story:{en:"What most of the world calls bean sprouts are these, germinated in the dark for four days. Whole, they are the base of Indian moong dal; ground and made into a batter they become the noodles sold across Asia as glass or cellophane noodles.",
fr:"Ce que le monde appelle germes de soja est en réalité ce haricot, germé quatre jours à l’obscurité. Entier, il fait le moong dal indien ; broyé et transformé en pâte, il devient les nouilles vendues dans toute l’Asie sous le nom de vermicelles de verre."},
tip:{en:"It is the one pulse that genuinely needs no soaking. Twenty-five minutes from dry and it is soft.",
fr:"C’est la seule légumineuse qui ne demande réellement aucun trempage. Vingt-cinq minutes depuis le sec et il est tendre."},
pairs:["ginger","turmeric","cumin","ghee","cilantro","chili","coconut-milk","lime"],
svg:'<ellipse class="f2 sf" cx="41" cy="55" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="53" cy="52" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="47" cy="64" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="58" cy="63" rx="6" ry="4.5"/>'},

{id:"natto",cat:"legumes",name:{en:"Natto",fr:"Natto"},latin:"Bacillus subtilis var. natto",
origin:{en:"Ibaraki, Japan",fr:"Ibaraki, Japon"},season:[],
flavor:["umami","pungent","earthy"],
story:{en:"The threads are polyglutamic acid, spun by Bacillus subtilis, a bacterium that lives on rice straw — hence the story that natto was found by accident in boiled beans packed in straw bales. Sake and miso brewers still refuse to eat it before entering the fermentation room: the bacterium travels on skin and clothes, and it overruns koji.",
fr:"Les fils sont de l’acide polyglutamique, filé par Bacillus subtilis, une bactérie qui vit sur la paille de riz — d’où l’histoire, dit-on, de fèves bouillies oubliées dans des bottes de paille. Les brasseurs de saké et de miso refusent encore d’en manger avant d’entrer dans la salle de fermentation : la bactérie voyage sur la peau et les vêtements, et elle écrase le koji."},
tip:{en:"Beat the beans on their own thirty or fifty times before the mustard and the tare go in — liquid added first stops the threads forming. Over rice just off the boil, never scalding.",
fr:"Battez les fèves seules trente à cinquante fois avant d’ajouter la moutarde et la sauce : versé en premier, le liquide empêche les fils de se former. Sur du riz à peine tiédi, jamais brûlant."},
pairs:["rice","karashi","negi","soy-sauce","egg","nori","kimchi"],
svg:'<path class="f1 sf" d="M26 52h44q-3 20-22 20T26 52z"/><ellipse class="f2 sf" cx="40" cy="56" rx="6" ry="4.5"/><ellipse class="f2 sf" cx="54" cy="58" rx="6" ry="4.5"/><path class="s" d="M40 50q1-14 10-22M54 52q0-12 8-18"/>'},

{id:"pigeon-pea",cat:"legumes",name:{en:"Pigeon pea (toor dal)",fr:"Pois d’Angole (toor dal)"},latin:"Cajanus cajan",
origin:{en:"Indian subcontinent",fr:"Sous-continent indien"},season:[],
flavor:["earthy","sweet","nutty","mild"],
story:{en:"Cajanus cajan is a woody shrub that crops for several years running, which is why it stands at the edge of compounds and field boundaries from Gujarat to Jamaica rather than in tidy rows. The English name is traced to Barbados, where the seed was grown as feed for pigeons long before European kitchens took it seriously.",
fr:"Le Cajanus cajan est un arbuste ligneux qui produit plusieurs années de suite : d’où sa place en bordure de parcelle, du Gujarat à la Jamaïque, plutôt qu’en rangs cultivés. Son nom anglais vient de la Barbade, où la graine servait à nourrir les pigeons bien avant que les cuisines européennes ne s’y intéressent."},
tip:{en:"Unsoaked toor dal takes about 40 minutes at a bare simmer and a spoon of oil to hold the foam down. It thickens hard as it cools, so stop the pot looser than you mean to serve it.",
fr:"Sans trempage, le toor dal demande environ 40 minutes de frémissement et une cuillerée d’huile pour maîtriser la mousse. Il épaissit beaucoup en refroidissant : arrêtez la cuisson plus liquide que le service voulu."},
pairs:["coconut-milk","curry-leaf","tamarind-paste","turmeric","asafoetida","mustard-seed","thyme","rice"],
svg:'<path class="f1 sf" d="M24 60q10-19 26-23t26 5q-8 15-25 19t-27-1z"/><circle class="f2 sf" cx="38" cy="53" r="6"/><circle class="f2 sf" cx="51" cy="47" r="6"/><circle class="f2 sf" cx="64" cy="43" r="6"/>'},

{id:"pochas",cat:"legumes",rare:true,name:{en:"Pochas",fr:"Pochas (haricots demi-secs de Navarre)"},latin:"Phaseolus vulgaris",
origin:{en:"Navarre and the Ebro valley",fr:"Navarre et vallée de l’Èbre"},season:[8,9],
flavor:["fresh","grassy","delicate"],
story:{en:"A pocha is not a variety but a moment: the same white bean picked once the pod has gone pale and papery but before the seed inside has given up its water. The window runs a few weeks in late summer, which is why a bean that cooks in half an hour supports an entire tinned and frozen trade.",
fr:"La pocha n’est pas une variété mais un instant : le même haricot blanc, cueilli quand la gousse a pâli et pris du parchemin, mais avant que la graine n’ait perdu son eau. La fenêtre dure quelques semaines à la fin de l’été, ce qui explique qu’un haricot cuisant en une demi-heure fasse vivre tout un commerce de conserve et de surgelé."},
tip:{en:"No soaking, and no acid until the end: start them cold with a whole onion and a green pepper, thirty to forty minutes at a tremble, salt off the heat. Tomato or vinegar added early sets the skins hard and no amount of extra time softens them again.",
fr:"Pas de trempage, et pas d’acide avant la fin : départ à froid avec un oignon entier et un poivron vert, trente à quarante minutes à frémissement, sel hors du feu. Tomate ou vinaigre ajoutés trop tôt durcissent les peaux, et aucune prolongation de cuisson ne les rattrape."},
pairs:["quail","chorizo","piquillo","green-bean","onion","olive-oil","garlic","clam"],
svg:'<path class="f1 sf" d="M24 60q4-24 22-32t26 4q-6 16-22 26t-26 2z"/><path class="s" d="M28 58q8-20 24-28"/><circle class="f2 sf" cx="38" cy="52" r="7"/><circle class="f2 sf" cx="52" cy="42" r="7"/><circle class="f1 sf" cx="64" cy="34" r="6"/><path class="f2 sf" d="M26 68q12 2 16 12-12 4-18-4z"/>'},

{id:"lentille-du-puy",cat:"legumes",name:{en:"Puy lentil",fr:"Lentille verte du Puy"},latin:"Lens culinaris",
origin:{en:"Haute-Loire, Auvergne",fr:"Haute-Loire, Auvergne"},season:[],
flavor:["earthy","peppery","nutty","mild"],
story:{en:"The first vegetable in France to be granted an AOC, in 1996. It grows on volcanic soil at altitude where the summers are dry, and the lack of water is what keeps the skin thin and stops the lentil bursting — scarcity as a quality control.",
fr:"Le premier légume français à recevoir une AOC, en 1996. Elle pousse sur sol volcanique en altitude, sous des étés secs, et c’est le manque d’eau qui garde la peau fine et empêche la lentille d’éclater — la rareté comme contrôle qualité."},
tip:{en:"Never salt the cooking water at the start. Salt firms the skins and they take twice as long to soften.",
fr:"Ne salez jamais l’eau de cuisson au départ. Le sel raffermit les peaux et double le temps d’attendrissement."},
pairs:["sherry-vinegar","shallot","carrot","bay-leaf","duck","mustard","parsley","lard"],
svg:'<circle class="f2 sf" cx="40" cy="52" r="7"/><circle class="f2 sf" cx="56" cy="56" r="7"/><circle class="f2 sf" cx="47" cy="66" r="7"/><path class="s" d="M36 52h8M52 56h8"/>'},

{id:"red-lentil",cat:"legumes",name:{en:"Red lentil",fr:"Lentille corail"},latin:"Lens culinaris",
origin:{en:"Near East & South Asia",fr:"Proche-Orient & Asie du Sud"},season:[],
flavor:["sweet","earthy","mild","nutty"],
story:{en:"It is a brown lentil with its skin removed, which is why it is orange rather than red and why it collapses so fast — nothing is left to hold it together. Split and skinned, it cooks in fifteen minutes and turns to purée on its own.",
fr:"C’est une lentille brune décortiquée, d’où sa couleur orange plutôt que rouge et son effondrement si rapide — plus rien ne la tient. Fendue et sans peau, elle cuit en quinze minutes et se réduit en purée d’elle-même."},
tip:{en:"Use it when you want it to disappear — dal, soup, a thickener. If you need lentils to stay whole, this is the wrong one.",
fr:"Employez-la quand vous voulez qu’elle disparaisse — dal, soupe, liant. S’il faut des lentilles entières, ce n’est pas la bonne."},
pairs:["cumin","turmeric","ghee","ginger","garlic","cilantro","coconut-milk","chili"],
svg:'<circle class="f2 sf" cx="41" cy="54" r="7"/><circle class="f2 sf" cx="56" cy="52" r="7"/><circle class="f2 sf" cx="48" cy="66" r="7"/>'},

{id:"santorini-fava",cat:"legumes",rare:true,name:{en:"Santorini fava",fr:"Fava de Santorin"},latin:"Lathyrus clymenum",
origin:{en:"Santorini and the Cyclades",fr:"Santorin et les Cyclades"},season:[6,7],
flavor:["sweet","earthy","nutty"],
story:{en:"Despite the name it is neither a broad bean nor a split pea but a grass pea, Lathyrus clymenum, and carbonised seeds of that exact species were excavated from the Bronze Age town at Akrotiri — the same crop on the same island before the eruption. It is still grown without irrigation, rooted in volcanic ash that holds the night humidity the plants live on.",
fr:"Malgré son nom, ce n’est ni une fève ni un pois cassé mais une gesse, Lathyrus clymenum, dont des graines carbonisées ont été exhumées de la cité de l’âge du bronze d’Akrotiri — la même culture sur la même île, avant l’éruption. On la cultive toujours sans irrigation, enracinée dans une cendre volcanique qui retient l’humidité nocturne dont vivent les plants."},
tip:{en:"One part fava to three of water with an onion in the pot, forty to sixty minutes; it collapses by itself. Finish it with a whisk, never a blender — blended it goes to glue — and keep the oil, lemon and raw onion for the table.",
fr:"Un volume de fava pour trois d’eau avec un oignon dans la casserole, quarante à soixante minutes : elle se défait toute seule. Terminez au fouet, jamais au mixeur — mixée, elle devient colle — et réservez l’huile, le citron et l’oignon cru pour la table."},
pairs:["olive-oil","lemon","red-onion","capers","oregano","octopus","dill"],
svg:'<path class="s" d="M20 66q28 12 56 0"/><path class="f1 sf" d="M26 62q5-24 22-24t22 24q-22 9-44 0z"/><path class="s" d="M34 54q14 5 28 0"/><path class="f2 sf" d="M40 44q9-5 16 2-7 6-16 3z"/><circle class="dot" cx="36" cy="46" r="2"/><circle class="dot" cx="62" cy="50" r="2"/>'},

{id:"silken-tofu",cat:"legumes",name:{en:"Silken tofu (kinugoshi)",fr:"Tofu soyeux"},latin:"Glycine max",
origin:{en:"Japan",fr:"Japon"},season:[],
flavor:["mild","milky","delicate","creamy"],
story:{en:"Kinugoshi means silk-strained, and neither word is true: no silk touches it and nothing is strained. The soy milk is set with its coagulant directly in the box it will be sold in, so curds and whey never separate at all — the name describes only how it feels.",
fr:"Kinugoshi veut dire « passé à la soie », et aucun des deux mots n’est vrai : nulle soie n’intervient et rien n’est passé. Le lait de soja prend avec son coagulant directement dans la barquette où il sera vendu, si bien que caillé et petit-lait ne se séparent jamais — le nom ne décrit que la sensation."},
tip:{en:"It cannot be pressed, so stop trying; drain it on a tilted plate for ten minutes instead. Slide it into simmering water on the flat of a knife and keep the pot below a boil — anything more agitated and it breaks into clouds.",
fr:"Il ne se presse pas : égouttez-le dix minutes sur une assiette inclinée. Faites-le glisser dans l’eau frémissante sur le plat d’un couteau et maintenez la casserole sous l’ébullition — plus agité, il part en nuages."},
pairs:["koikuchi-shoyu","ginger","negi","katsuobushi","sesame-oil","century-egg","wasabi"],
svg:'<path class="f2 sf" d="M20 72h56q-4 8-10 8H30q-6 0-10-8z"/><path class="f1 sf" d="M26 40q0-6 6-6h32q6 0 6 6v26q0 6-6 6H32q-6 0-6-6z"/><path class="s" d="M40 40q8 8 16 0"/><path class="s" d="M26 56h44"/>'},

{id:"soissons-bean",cat:"legumes",rare:true,luxe:true,name:{en:"Soissons bean",fr:"Haricot de Soissons"},latin:"Phaseolus coccineus",
origin:{en:"Aisne valley, Picardy",fr:"Vallée de l’Aisne, Picardie"},season:[9,10],
flavor:["creamy","mild","earthy"],
story:{en:"It is not the common bean at all but a runner bean, Phaseolus coccineus, sent three or four metres up poles on the Aisne floodplain. The specification effectively sells it by the ruler: pods of twenty to twenty-five centimetres, and a dried grain of at least seventeen millimetres to carry the name.",
fr:"Ce n’est pas du tout le haricot commun mais un haricot d’Espagne, Phaseolus coccineus, mené à trois ou quatre mètres sur rames dans la plaine alluviale de l’Aisne. Le cahier des charges le vend pour ainsi dire à la règle : des gousses de vingt à vingt-cinq centimètres, et un grain sec d’au moins dix-sept millimètres pour porter le nom."},
tip:{en:"Soak twelve hours and it needs barely an hour of gentle cooking, half what a lingot takes. Go past that and you have purée — excellent if you meant it, and the end of any salad if you did not.",
fr:"Après douze heures de trempage, il ne demande guère plus d’une heure de cuisson douce, moitié moins qu’un lingot. Au-delà, vous avez une purée — excellente si c’était l’intention, fatale à toute salade sinon."},
pairs:["butter","cream","garlic","thyme","sage","pork","parsley","bay-leaf"],
svg:'<path class="f1 sf" d="M20 44q14-13 28-13t28 13q-14 8-28 8t-28-8z"/><path class="s" d="M22 43q13-10 26-10t26 10"/><ellipse class="f2 sf" cx="34" cy="62" rx="11" ry="8"/><ellipse class="f3 sf" cx="58" cy="66" rx="12" ry="9"/><path class="s" d="M26 60q8 4 16 0M48 64q10 5 20 0"/>'},

{id:"sorana-bean",cat:"legumes",rare:true,luxe:true,name:{en:"Sorana bean",fr:"Haricot de Sorana"},latin:"Phaseolus vulgaris",
origin:{en:"Pescia valley, Tuscany",fr:"Vallée de la Pescia, Toscane"},season:[9,10],
flavor:["delicate","mild","buttery"],
story:{en:"It grows on one strip of sand and gravel along the Pescia river, the ghiareto, on ground reclaimed under the Medici and later the grand dukes; the skin that all but disappears in cooking is credited to that poor, fast-draining soil and the damp valley air. The protected area is measured in hectares, and the plants are still staked on cane by hand.",
fr:"Il pousse sur une seule bande de sable et de graviers le long de la Pescia, le ghiareto, sur des terres assainies sous les Médicis puis sous les grands-ducs ; cette peau qui disparaît presque à la cuisson tient à ce sol pauvre et drainant et à l’air humide de la vallée. L’aire protégée se compte en hectares, et les plants sont encore ramés à la canne, à la main."},
tip:{en:"Cook it in unsalted water at a bare tremble, or in a low oven, with a garlic clove and a sage leaf, then dress it warm with oil and pepper. There is no skin to hold it together, so a real boil shreds it — and it needs no soffritto to hide behind.",
fr:"Cuisez-le à l’eau non salée, à peine frémissante, ou au four doux, avec une gousse d’ail et une feuille de sauge, puis assaisonnez-le tiède à l’huile et au poivre. Il n’a pas de peau pour le tenir : une vraie ébullition le met en lambeaux — et il n’a aucun soffritto derrière lequel se cacher."},
pairs:["olive-oil","rosemary","tomato","prosciutto","black-pepper","garlic","parsley"],
svg:'<path class="f1 sf" d="M22 56h52q-4 18-26 18T22 56z"/><path class="s" d="M20 56h56"/><ellipse class="f2 sf" cx="36" cy="44" rx="9" ry="6"/><ellipse class="f1 sf" cx="56" cy="42" rx="9" ry="6"/><ellipse class="f2 sf" cx="46" cy="54" rx="9" ry="6"/><path class="s" d="M30 44q6 3 12 0M50 42q6 3 12 0"/>'},

{id:"soy-bean",cat:"legumes",name:{en:"Soybean",fr:"Soja"},latin:"Glycine max",
origin:{en:"Northeast China",fr:"Nord-est de la Chine"},season:[],
flavor:["nutty","earthy","umami","mild"],
story:{en:"Domesticated in China more than three thousand years ago, and almost nothing about it is eaten as a bean — it becomes tofu, miso, soy sauce, oil and animal feed. Fresh in the pod it is edamame, which is the exception.",
fr:"Domestiqué en Chine il y a plus de trois mille ans, et il ne se mange presque jamais tel quel — il devient tofu, miso, sauce soja, huile et aliment du bétail. Frais dans sa cosse c’est l’edamame, qui fait exception."},
tip:{en:"Dried soybeans must be boiled hard and long — they contain trypsin inhibitors that raw or gently cooked beans retain.",
fr:"Les graines sèches doivent bouillir fort et longtemps — elles contiennent des inhibiteurs de trypsine que la cuisson douce ne détruit pas."},
pairs:["soy-sauce","miso","sesame","ginger","spring-onion","garlic","chili","tamari"],
svg:'<path class="f3 sf" d="M28 60q16-20 40-16-8 22-32 26-12 2-8-10z"/><circle class="f2 sf" cx="40" cy="56" r="5"/><circle class="f2 sf" cx="53" cy="51" r="5"/>'},

{id:"split-pea",cat:"legumes",name:{en:"Split pea",fr:"Pois cassé"},latin:"Pisum sativum",
origin:{en:"Near East",fr:"Proche-Orient"},season:[],
flavor:["sweet","earthy","mild","creamy"],
story:{en:"A field pea dried, skinned and split along its natural seam, which is where it wants to divide anyway. Splitting doubles the surface and halves the cooking time — a piece of food engineering several thousand years old.",
fr:"Un pois de champ séché, décortiqué et fendu le long de sa suture naturelle, là où il tend de toute façon à se séparer. La fente double la surface et divise par deux le temps de cuisson — un travail d’ingénierie alimentaire vieux de plusieurs millénaires."},
tip:{en:"It foams enormously at first boil. Skim it once and the soup stays clear instead of turning grey.",
fr:"Il mousse énormément à la première ébullition. Écumez une fois et la soupe reste nette au lieu de grisonner."},
pairs:["lard","onion","carrot","bay-leaf","mint","thyme","black-pepper","butter"],
svg:'<path class="f2 sf" d="M32 54a8 8 0 0 1 16 0z"/><path class="f2 sf" d="M48 60a8 8 0 0 1 16 0z"/><path class="f2 sf" d="M38 68a8 8 0 0 1 16 0z"/>'},

{id:"haricot-tarbais",cat:"legumes",name:{en:"Tarbais bean",fr:"Haricot tarbais"},latin:"Phaseolus vulgaris",
origin:{en:"Hautes-Pyrénées, France",fr:"Hautes-Pyrénées, France"},season:[],
flavor:["creamy","mild","earthy","nutty"],
story:{en:"Traditionally grown climbing up maize stalks, which act as living stakes — the two crops were planted together for two centuries. Its skin is unusually fine, so it absorbs the fat of a cassoulet without disintegrating, which is why the dish specifies it.",
fr:"Traditionnellement cultivé grimpant sur des tiges de maïs, qui servent de tuteurs vivants — les deux cultures étaient associées depuis deux siècles. Sa peau est exceptionnellement fine : il absorbe le gras d’un cassoulet sans se déliter, et c’est pourquoi la recette l’exige."},
tip:{en:"Soak twelve hours, then start it in cold water and bring it up slowly. Dropping beans into boiling water splits every skin.",
fr:"Trempez douze heures, puis démarrez à l’eau froide en montant lentement. Jeter des haricots dans l’eau bouillante fend toutes les peaux."},
pairs:["duck-fat","garlic","thyme","lard","onion","tomato","bay-leaf","carrot"],
svg:'<path class="f3 sf" d="M34 32q-8 24 4 38t20-6q4-18-6-30t-18-2z"/><path class="s" d="M40 44q6 14 8 22"/>'},

{id:"tempeh",cat:"legumes",name:{en:"Tempeh",fr:"Tempeh"},latin:"Rhizopus oligosporus",
origin:{en:"Java, Indonesia",fr:"Java, Indonésie"},season:[],
flavor:["nutty","earthy","umami","mild"],
story:{en:"A colony of Rhizopus knits whole cooked soybeans into a solid white cake in about thirty-six hours, and the mycelium itself is eaten - it is the structure, not a seasoning. Javanese writing of the early nineteenth century already describes it, which makes it, unusually among soy foods, an Indonesian invention rather than a Chinese one.",
fr:"Une colonie de Rhizopus lie en trente-six heures des graines de soja entières en un gâteau blanc et ferme, et l’on mange le mycélium lui-même : il est la structure, non l’assaisonnement. Des textes javanais du début du XIXe siècle le décrivent déjà, ce qui en fait, chose rare parmi les produits du soja, une invention indonésienne et non chinoise."},
tip:{en:"Steam it ten minutes before marinating: it opens up, takes salt, and any raw bitterness goes off with the steam. Grey and black patches are the mould sporing and are harmless, but a smell of ammonia is not - that block goes out.",
fr:"Faites-le cuire dix minutes à la vapeur avant de le mariner : il s’ouvre, prend le sel, et l’amertume crue part avec la vapeur. Les taches grises ou noires sont le champignon qui sporule, sans danger ; une odeur d’ammoniac, elle, condamne le pain."},
pairs:["soy-sauce","garlic","palm-sugar","coriander-seed","tamarind-paste","chili","lime","peanut"],
svg:'<path class="f1 sf" d="M24 42h40v22H24z"/><path class="f2 sf" d="M24 42l8-8h40l-8 8z"/><path class="f2 sf" d="M64 42l8-8v22l-8 8z"/><path class="dot" d="M32 50a3 2 0 106 0 3 2 0 10-6 0M44 56a3 2 0 106 0 3 2 0 10-6 0M52 48a3 2 0 106 0 3 2 0 10-6 0"/>'},

{id:"tolosa-black-bean",cat:"legumes",rare:true,luxe:true,name:{en:"Tolosa black bean",fr:"Haricot noir de Tolosa"},latin:"Phaseolus vulgaris",
origin:{en:"Tolosaldea, Gipuzkoa",fr:"Tolosaldea, Guipuscoa"},season:[9,10],
flavor:["earthy","rich","meaty"],
story:{en:"Cooked, it throws a broth so dark and so bound by its own dissolved skins that Basque cooks judge the dish by the liquid rather than the bean — nothing like the firm, dry turtle bean the name suggests. The growers organised formally only in 1994, as Tolosako Babarruna, to defend a bean that had been local currency for far longer.",
fr:"À la cuisson, il rend un bouillon si sombre et si lié par ses propres peaux dissoutes que les cuisiniers basques jugent le plat au liquide plutôt qu’au grain — rien à voir avec le haricot noir ferme et sec que le nom laisse imaginer. Les producteurs ne se sont organisés qu’en 1994, sous le nom de Tolosako Babarruna, pour défendre un haricot qui faisait monnaie locale depuis bien plus longtemps."},
tip:{en:"Do not soak it. Start cold, hold it just under a simmer for two to three hours, top up only with cold water, and let the pot stand off the heat ten minutes before serving — that rest is what pulls the broth together.",
fr:"Ne le faites pas tremper. Départ à froid, maintenez-le juste sous le frémissement deux à trois heures, ne rallongez qu’à l’eau froide, et laissez la marmite reposer dix minutes hors du feu avant de servir : c’est ce repos qui lie le bouillon."},
pairs:["morcilla-de-burgos","chorizo","pork-belly","guindilla","cabbage","garlic","olive-oil"],
svg:'<path class="f1 sf" d="M22 40h52l-6 26a10 10 0 0 1-10 8H38a10 10 0 0 1-10-8z"/><path class="f3 sf" d="M24 48h48l-4 18a10 10 0 0 1-10 8H38a10 10 0 0 1-10-8z"/><path class="s" d="M20 40h56"/><circle class="dot" cx="40" cy="56" r="2.5"/><circle class="dot" cx="52" cy="60" r="2.5"/><circle class="dot" cx="62" cy="54" r="2.5"/>'},

{id:"urad-dal",cat:"legumes",name:{en:"Urad dal",fr:"Urad dal (haricot urd)"},latin:"Vigna mungo",
origin:{en:"South Asia",fr:"Asie du Sud"},season:[],
flavor:["earthy","nutty","mild"],
story:{en:"Ground and left to stand with rice, urad does what no other pulse does: its arabinogalactan mucilage traps the gas of fermentation, and the batter rises with no yeast added at all. South Indian cooks read the ratio in the grinder rather than the recipe — three or four parts rice to one of urad, the dal ground longer and finer than the rice.",
fr:"Moulu et laissé à reposer avec du riz, l’urad fait ce qu’aucune autre légumineuse ne fait : son mucilage d’arabinogalactane retient le gaz de la fermentation, et la pâte lève sans la moindre levure ajoutée. Les cuisiniers du sud de l’Inde lisent le rapport dans le moulin plutôt que dans la recette — trois à quatre volumes de riz pour un d’urad, le dal broyé plus longtemps et plus fin que le riz."},
tip:{en:"Grind the urad separately and cold, adding water in small pours until the paste is white and fluffy and a drop of it floats in water — that float test is the only reliable sign the batter will rise. Whole black urad and the skinned white split are not interchangeable: only the skinned one makes idli.",
fr:"Broyez l’urad à part et au frais, en ajoutant l’eau par petites doses jusqu’à une pâte blanche et aérée dont une goutte flotte dans l’eau : ce test de flottaison est le seul signe fiable que la pâte lèvera. L’urad noir entier et le blanc décortiqué cassé ne sont pas interchangeables — seul le décortiqué donne l’idli."},
pairs:["rice","fenugreek","curry-leaf","asafoetida","ghee","coconut"],
svg:'<ellipse class="f3 sf" cx="38" cy="42" rx="11" ry="8"/><path class="s" d="M28 42h20"/><ellipse class="f1 sf" cx="58" cy="56" rx="11" ry="8"/><path class="s" d="M48 56h20"/><ellipse class="f2 sf" cx="41" cy="63" rx="9" ry="7"/>'},

{id:"white-beans",cat:"legumes",name:{en:"White beans",fr:"Haricots blancs"},latin:"Phaseolus vulgaris",
origin:{en:"Americas",fr:"Amériques"},season:[],
flavor:["mild","buttery","earthy"],
story:{en:"Beans crossed from the Americas in the 1530s; Catherine de’ Medici reportedly carried a pouch of them to France in her wedding luggage. Tuscans became such devotees that the rest of Italy nicknamed them mangiafagioli — the bean-eaters.",
fr:"Le haricot arriva des Amériques dans les années 1530 ; Catherine de Médicis, dit-on, en emporta une bourse dans ses bagages de mariage vers la France. Les Toscans en devinrent si friands que le reste de l’Italie les surnomma mangiafagioli — les mangeurs de haricots."},
tip:{en:"Cook them gently — a hard boil bursts their jackets — and always with a bay leaf and a whole garlic clove. Their broth is liquid silver: keep it.",
fr:"Cuisez-les doucement — un gros bouillon fait éclater leur peau — et toujours avec du laurier et une gousse d’ail entière. Leur bouillon est de l’argent liquide : gardez-le."},
pairs:["sage","tomato","rosemary","pork","bay-leaf","olive-oil","onion"],
svg:'<path class="f1 sf" d="M34 48q2-8 10-6 6 2 6 8t-8 8q-8 0-8-10z" transform="rotate(-14 42 52)"/><path class="f1 sf" d="M50 52q2-8 10-6 6 2 6 8t-8 8q-8 0-8-10z" transform="rotate(10 58 56)"/>'},

{id:"yuba",cat:"legumes",luxe:true,name:{en:"Yuba",fr:"Yuba (peau de soja)"},latin:"Glycine max",
origin:{en:"Temple kitchens of Kyoto and Nikko, Japan",fr:"Cuisines de temple de Kyoto et Nikko, Japon"},season:[],
flavor:["creamy","mild","nutty"],
story:{en:"Yuba is the skin that forms on soy milk held just below the boil, lifted off one sheet at a time on a bamboo rod until the pan is spent. Kyoto and Nikko each built a temple cuisine on it and even write the word with different characters: Nikko folds its sheets double as they come off, so they eat thicker.",
fr:"Le yuba est la peau qui se forme sur le lait de soja maintenu juste sous l’ébullition, levée feuille à feuille à la baguette de bambou jusqu’à épuisement du bain. Kyoto et Nikko en ont chacune tiré une cuisine de temple et écrivent même le mot avec des caractères différents : Nikko plie sa feuille en deux au moment de la lever, elle se mange donc plus épaisse."},
tip:{en:"Fresh yuba wants no cooking at all: eat it the same day with a trace of soy and wasabi. Dried sheets need only a brief dip in warm water — left to soak, they dissolve into the bowl.",
fr:"Le yuba frais ne se cuit pas : mangez-le dans la journée avec un trait de soja et un peu de wasabi. Les feuilles sèches ne demandent qu’un passage bref en eau tiède, oubliées à tremper elles se dissolvent dans le bol."},
pairs:["wasabi","usukuchi-shoyu","kombu","mitsuba","sesame","myoga"],
svg:'<path class="s" d="M24 30h48"/><path class="f1 sf" d="M36 30q-2 20 2 28 6-10 10 0 6-8 12 0 4-8 2-28z"/><path class="f3 sf" d="M26 62h44q-2 10-10 10H36q-8 0-10-10z"/>'},

{id:"zolfino-bean",cat:"legumes",rare:true,luxe:true,name:{en:"Zolfino bean",fr:"Haricot zolfino"},latin:"Phaseolus vulgaris",
origin:{en:"Pratomagno terraces, Tuscany",fr:"Terrasses du Pratomagno, Toscane"},season:[7,8],
flavor:["buttery","nutty","earthy"],
story:{en:"It is sown in April on dry-stone terraces between roughly 250 and 600 metres, often under the olives so that rain runs straight off: its root system is so shallow that a day of standing water finishes the plant. The traditional pot is a straw-wrapped wine flask set among the embers, which happens to give exactly the slow, never-boiling heat the bean wants.",
fr:"On le sème en avril sur des terrasses en pierre sèche, entre 250 et 600 mètres environ, souvent sous les oliviers pour que la pluie s’écoule : son enracinement est si superficiel qu’une journée d’eau stagnante tue le plant. Le récipient traditionnel est un fiasque gainé de paille posé dans la braise, ce qui donne précisément la chaleur lente et jamais bouillante que ce haricot réclame."},
tip:{en:"Start it in cold unsalted water and raise the heat so slowly that the surface only trembles — three hours or more. A rolling boil bursts those very thin skins and the buttery density you paid for turns to soup.",
fr:"Démarrez-le à l’eau froide non salée et montez si lentement que la surface ne fait que frissonner — trois heures ou davantage. Une ébullition franche fait éclater ces peaux très fines, et la densité beurrée que vous avez payée tourne à la soupe."},
pairs:["olive-oil","garlic","sage","cavolo-nero","pancetta","black-pepper","thyme"],
svg:'<path class="f1 sf" d="M44 18h8v18q14 8 14 24t-14 20q-8 4-16 0t-14-20 14-24z"/><path class="f2 sf" d="M30 58q18 8 36 0-2 16-14 22-8 4-16 0t-6-22z"/><path class="s" d="M34 44q14 6 28 0M32 52q16 6 32 0M32 66q16 6 32 0M32 74q14 5 28 0"/><path class="f3 sf" d="M42 12h12v6H42z"/>'}
]);
