window.INGREDIENTS = (window.INGREDIENTS || []).concat([
{id:"acacia-honey",cat:"sweet",name:{en:"Acacia honey",fr:"Miel d’acacia"},latin:"Robinia pseudoacacia",
origin:{en:"Europe & North America",fr:"Europe & Amérique du Nord"},season:[5,6],
flavor:["sweet","floral","delicate","mild"],
story:{en:"From the false acacia, which flowers for barely two weeks in late spring — a single storm can wipe out an entire year's crop. Its very high fructose content is why it stays liquid for years while other honeys crystallise.",
fr:"Issu du robinier faux-acacia, qui ne fleurit qu’une quinzaine de jours à la fin du printemps — un seul orage peut anéantir une année de récolte. Sa très forte teneur en fructose explique qu’il reste liquide des années quand les autres miels cristallisent."},
tip:{en:"It is the neutral honey — use it where you want sweetness without the honey announcing itself.",
fr:"C’est le miel neutre — employez-le quand vous voulez du sucré sans que le miel s’annonce."},
pairs:["goat-cheese","yogurt","lemon","almond","apple","cream","walnut","honey"],
svg:'<path class="f3 sf" d="M36 70V44h24v26z"/><path class="s" d="M36 52h24"/><path class="f2 sf" d="M42 58l4-6 4 6-4 6z"/>'},

{id:"agave-syrup",cat:"sweet",name:{en:"Agave syrup",fr:"Sirop d’agave"},latin:"Agave tequilana",
origin:{en:"Jalisco, Mexico",fr:"Jalisco, Mexique"},season:[],
flavor:["sweet","mild","floral","earthy"],
story:{en:"From the same plant that makes tequila — the heart of the agave is cut out and its sap boiled down. Marketed for years as a low-glycaemic alternative, though it is largely fructose, which is a rather different claim than most labels imply.",
fr:"De la même plante que la tequila — on découpe le cœur de l’agave et l’on réduit sa sève. Vendu des années comme alternative à faible index glycémique, alors qu’il est majoritairement fructose, ce qui n’est pas tout à fait ce que suggèrent les étiquettes."},
tip:{en:"It is sweeter than sugar, so use about three quarters as much, and reduce the other liquid slightly.",
fr:"Il sucre plus que le sucre : comptez environ les trois quarts, et réduisez légèrement les autres liquides."},
pairs:["lime","chili","grapefruit","mint","coffee","cinnamon","orange","yogurt"],
svg:'<path class="f2 sf" d="M40 74V42h16v32z"/><path class="s" d="M40 50h16"/><path class="f3 sf" d="M44 38q4-12 8 0z"/>'},

{id:"buckwheat-honey",cat:"sweet",name:{en:"Buckwheat honey",fr:"Miel de sarrasin"},latin:"Fagopyrum esculentum",
origin:{en:"Brittany & northern Europe",fr:"Bretagne & Europe du Nord"},season:[7,8],
flavor:["earthy","musky","rich","smoky"],
story:{en:"Almost black, and it smells of molasses, malt and the farmyard — it is the most divisive honey there is, and the one with by far the most antioxidants. Brittany makes it because Brittany grows buckwheat for its galettes.",
fr:"Presque noir, il sent la mélasse, le malt et l’étable — c’est le miel le plus clivant qui soit, et de loin le plus riche en antioxydants. La Bretagne en produit parce qu’elle cultive le sarrasin pour ses galettes."},
tip:{en:"Do not try it on a scone. It belongs in a marinade, a barbecue glaze or a dark gingerbread.",
fr:"N’en mettez pas sur une tartine. Sa place est dans une marinade, un laquage de barbecue ou un pain d’épices sombre."},
pairs:["buckwheat-flour","pork","rye-flour","ginger","dark-chocolate","clove","walnut","cider-vinegar"],
svg:'<path class="f1 sf" d="M36 70V44h24v26z"/><path class="s" d="M36 52h24"/><path class="f1 sf" d="M44 58l4-6 4 6-4 6z"/>'},

{id:"cassonade",cat:"sweet",name:{en:"Cassonade",fr:"Cassonade"},latin:"Saccharum — sucre roux de canne",
origin:{en:"France & Belgium",fr:"France & Belgique"},season:[],
flavor:["sweet","toasty","warm","rich"],
story:{en:"Beware the word: in France cassonade means unrefined cane sugar, in Belgium and Quebec it means something closer to soft brown sugar made from beet. Recipes crossing those borders go wrong on this single term more than any other.",
fr:"Méfiez-vous du mot : en France la cassonade est un sucre de canne roux non raffiné, en Belgique et au Québec elle désigne un sucre brun de betterave. Plus qu’aucun autre terme, celui-ci fait dérailler les recettes qui traversent ces frontières."},
tip:{en:"It is what goes on a crème brûlée because it caramelises faster than white sugar and colours more evenly.",
fr:"C’est elle qu’on met sur une crème brûlée parce qu’elle caramélise plus vite que le sucre blanc et colore plus régulièrement."},
pairs:["cream","vanilla","butter","apple","cinnamon","egg","orange","dark-chocolate"],
svg:'<path class="f2 sf" d="M34 68V50h28v18z"/><path class="s" d="M34 58h28M44 50v18M54 50v18"/>'},

{id:"chestnut-honey",cat:"sweet",name:{en:"Chestnut honey",fr:"Miel de châtaignier"},latin:"Castanea sativa",
origin:{en:"Corsica, Cévennes, Italy",fr:"Corse, Cévennes, Italie"},season:[6,7],
flavor:["bitter","earthy","woody","rich"],
story:{en:"Dark, resinous and genuinely bitter — the honey people either love or send back. Its pollen count is so distinctive that laboratories use it as a reference sample, and Corsica protects its version with an appellation.",
fr:"Sombre, résineux et franchement amer — le miel que l’on adore ou que l’on renvoie. Son spectre pollinique est si caractéristique que les laboratoires s’en servent d’échantillon de référence, et la Corse protège le sien par une appellation."},
tip:{en:"It is a savoury honey. Put it with blue cheese, game or a duck glaze rather than on toast.",
fr:"C’est un miel salé. Mettez-le avec un bleu, du gibier ou un laquage de canard plutôt que sur une tartine."},
pairs:["blue-cheese","pecorino","venison","walnut","duck","fig","ricotta","chestnut"],
svg:'<path class="f1 sf" d="M36 70V44h24v26z"/><path class="s" d="M36 52h24"/><path class="f2 sf" d="M43 60q5-8 10 0z"/>'},

{id:"cocoa-nibs",cat:"sweet",name:{en:"Cocoa nibs",fr:"Grué de cacao"},latin:"Theobroma cacao",
origin:{en:"Central & South America",fr:"Amérique centrale et du Sud"},season:[],
flavor:["bitter","toasty","earthy","nutty"],
story:{en:"Roasted cocoa beans cracked into fragments, before any sugar or grinding — this is what chocolate is made from, and it is unrecognisably bitter. The Aztecs drank it with chilli and used the beans as currency.",
fr:"Des fèves de cacao torréfiées et concassées, avant tout sucre et tout broyage — c’est la matière du chocolat, et elle est amère au point d’être méconnaissable. Les Aztèques la buvaient au piment et se servaient des fèves comme monnaie."},
tip:{en:"Use them as you would a nut, for crunch and bitterness against something sweet. They never soften.",
fr:"Employez-le comme un fruit sec, pour le croquant et l’amertume contre un élément sucré. Il ne s’attendrit jamais."},
pairs:["dark-chocolate","cream","raspberry","banana","coffee","honey","hazelnut","orange"],
svg:'<path class="f1 sf" d="M38 48l6 4-4 6-6-4z"/><path class="f1 sf" d="M52 54l6 4-4 6-6-4z"/><path class="f1 sf" d="M44 64l6 4-4 6-6-4z"/>'},

{id:"coffee",cat:"sweet",name:{en:"Coffee",fr:"Café"},latin:"Coffea arabica",
origin:{en:"Ethiopian highlands",fr:"Hauts plateaux d’Éthiopie"},season:[],
flavor:["bitter","toasty","fruity","rich"],
story:{en:"Legend credits Kaldi, an Ethiopian goatherd, whose goats danced after eating red berries. From Sufi monasteries it reached Ottoman coffeehouses — nicknamed “schools of the wise” — and Europe’s cafés, where more than one revolution was stirred with a spoon.",
fr:"La légende crédite Kaldi, un chevrier éthiopien, dont les chèvres dansaient après avoir mangé des baies rouges. Des monastères soufis, il gagna les cafés ottomans — surnommés « écoles des sages » — puis les cafés d’Europe, où plus d’une révolution fut remuée à la petite cuillère."},
tip:{en:"In cooking it works like a spice: a shot of espresso deepens chocolate cakes, chili con carne and even a beef glaze without tasting of coffee.",
fr:"En cuisine, il agit comme une épice : un trait d’expresso approfondit les gâteaux au chocolat, le chili et même un jus de bœuf, sans goût de café."},
pairs:["dark-chocolate","cardamom","hazelnut","vanilla","cinnamon","walnut","maple-syrup"],
svg:'<ellipse class="f3 sf" cx="40" cy="48" rx="10" ry="13" transform="rotate(-20 40 48)"/><path class="s" d="M35 39q6 9 2 18" transform="rotate(-20 40 48)"/><ellipse class="f3 sf" cx="58" cy="60" rx="10" ry="13" transform="rotate(24 58 60)"/><path class="s" d="M53 51q6 9 2 18" transform="rotate(24 58 60)"/>'},

{id:"dark-chocolate",cat:"sweet",name:{en:"Dark chocolate",fr:"Chocolat noir"},latin:"Theobroma cacao",
origin:{en:"Mesoamerica",fr:"Mésoamérique"},season:[],
flavor:["bitter","rich","fruity","toasty"],
story:{en:"The Aztecs used cacao beans as money and drank chocolate bitter, spiced with chili — Linnaeus later named the tree Theobroma, “food of the gods”. Europe added sugar in the 1600s, and chocolate houses became the social networks of London and Madrid.",
fr:"Les Aztèques utilisaient les fèves de cacao comme monnaie et buvaient le chocolat amer, relevé de piment — Linné nomma plus tard l’arbre Theobroma, « nourriture des dieux ». L’Europe y ajouta le sucre au XVIIe siècle, et les maisons de chocolat devinrent les réseaux sociaux de Londres et de Madrid."},
tip:{en:"A pinch of salt makes chocolate taste more of chocolate. Melt it gently — past 55°C it seizes and sulks, and no apology will bring it back.",
fr:"Une pincée de sel donne au chocolat un goût plus profond de chocolat. Fondez-le doucement — passé 55 °C il tranche et boude, et aucune excuse ne le ramène."},
pairs:["raspberry","orange","coffee","chili","hazelnut","cardamom","vanilla","pear"],
svg:'<rect class="f3 sf" x="32" y="36" width="32" height="36" rx="3"/><path class="s" d="M48 36v36M32 54h32M40 36v36M56 36v36M32 45h32M32 63h32" stroke-width="1.6"/>'},

{id:"glucose-syrup",cat:"sweet",name:{en:"Glucose syrup",fr:"Sirop de glucose"},latin:"Glucosum liquidum",
origin:{en:"Europe, 1811",fr:"Europe, 1811"},season:[],
flavor:["sweet","mild","delicate","milky"],
story:{en:"Invented by a Russian chemist during the Napoleonic blockade, when cane sugar could not reach the continent — he made it from potato starch. Confectioners use it not for sweetness but to stop other sugars crystallising.",
fr:"Inventé par un chimiste russe pendant le blocus napoléonien, quand le sucre de canne n’atteignait plus le continent — il le tira de la fécule de pomme de terre. Les confiseurs l’emploient non pour sucrer mais pour empêcher les autres sucres de cristalliser."},
tip:{en:"It is what keeps sorbet scoopable and caramel smooth. A spoonful is a technical decision, not a sweetening one.",
fr:"C’est lui qui garde un sorbet malléable et un caramel lisse. Une cuillerée est une décision technique, non un ajout de sucre."},
pairs:["sugar","cream","butter","vanilla","dark-chocolate","lemon","raspberry","honey"],
svg:'<path class="f3 sf" d="M40 74V40h16v34z"/><path class="s" d="M40 48h16"/><circle class="dot" cx="48" cy="60" r="2"/>'},

{id:"honey",cat:"sweet",name:{en:"Honey",fr:"Miel"},latin:"Apis mellifera (nectar)",
origin:{en:"Everywhere bees fly",fr:"Partout où volent les abeilles"},season:[],
flavor:["sweet","floral","honeyed","warm"],
story:{en:"Jars of honey found in pharaohs’ tombs were still edible after three thousand years — it is the only food that never spoils. A single pound represents the nectar of about two million flowers; every spoonful is a map of a landscape in bloom.",
fr:"Des pots de miel trouvés dans les tombes des pharaons étaient encore comestibles après trois mille ans — c’est le seul aliment qui ne se gâte jamais. Un seul kilo représente le nectar d’environ quatre millions de fleurs ; chaque cuillerée est la carte d’un paysage en fleurs."},
tip:{en:"Crystallised honey isn’t spoiled — warm the jar gently in water and it clears. Match its strength to the dish: acacia whispers, chestnut argues.",
fr:"Un miel cristallisé n’est pas perdu — tiédissez le pot au bain-marie et il s’éclaircit. Accordez sa force au plat : l’acacia murmure, le châtaignier discute."},
pairs:["blue-cheese","walnut","yogurt","fig","lemon","ginger","goat-cheese","rosemary"],
svg:'<path class="s" d="M60 36L44 52"/><path class="f2 sf" d="M34 58h20M32 63h24M34 68h20M38 73h12" stroke-width="4"/><path class="f2 sf" d="M40 50a8 8 0 0016 0 8 8 0 00-16 0z" transform="translate(-6 8)"/>'},

{id:"icing-sugar",cat:"sweet",name:{en:"Icing sugar",fr:"Sucre glace"},latin:"Saccharum pulverulentum",
origin:{en:"Europe",fr:"Europe"},season:[],
flavor:["sweet","delicate","mild","milky"],
story:{en:"Ground to a powder and cut with two or three per cent starch to stop it caking — which is why it clouds a liquid and why it can never be used to make caramel. The starch is the reason, not the fineness.",
fr:"Broyé en poudre et coupé de deux ou trois pour cent d’amidon pour l’empêcher de prendre en masse — d’où le trouble qu’il laisse dans un liquide et son inaptitude au caramel. C’est l’amidon la cause, non la finesse."},
tip:{en:"Always sift it, without exception. It clumps in the box and a lump will not dissolve in a buttercream.",
fr:"Tamisez-le toujours, sans exception. Il s’agglomère dans la boîte et un grumeau ne se dissoudra pas dans une crème au beurre."},
pairs:["butter","vanilla","lemon","cream","strawberry","dark-chocolate","raspberry","almond"],
svg:'<path class="f3 sf" d="M34 70q0-18 14-22 14 4 14 22z"/><circle class="dot" cx="42" cy="62" r="1.2"/><circle class="dot" cx="52" cy="60" r="1.2"/><circle class="dot" cx="47" cy="68" r="1.2"/>'},

{id:"lavender-honey",cat:"sweet",name:{en:"Lavender honey",fr:"Miel de lavande"},latin:"Lavandula angustifolia",
origin:{en:"Haute-Provence",fr:"Haute-Provence"},season:[7,8],
flavor:["floral","sweet","delicate","herbal"],
story:{en:"Hives are trucked up to the Provençal plateaux in July when the lavender opens, a migration beekeepers have made for generations. It crystallises into a fine white cream rather than gritty crystals, which is the mark of the real thing.",
fr:"Les ruches montent en camion sur les plateaux provençaux en juillet quand la lavande s’ouvre, une transhumance que les apiculteurs font depuis des générations. Il cristallise en une crème blanche et fine plutôt qu’en cristaux grossiers, marque de l’authentique."},
tip:{en:"Use it where its perfume is the point — over goat's cheese, in an ice cream, with apricots. Cooked hard it is wasted.",
fr:"Employez-le là où son parfum compte — sur du chèvre, dans une glace, avec des abricots. Trop cuit il est gâché."},
pairs:["goat-cheese","apricot","peach","almond","cream","fig","lemon","yogurt"],
svg:'<path class="f3 sf" d="M36 70V44h24v26z"/><path class="s" d="M36 52h24"/><path class="f1 sf" d="M46 62q2-10 4 0z"/><circle class="dot" cx="48" cy="58" r="1.4"/>'},

{id:"sirop-de-liege",cat:"sweet",name:{en:"Liège syrup",fr:"Sirop de Liège"},latin:"Sirop de Liège",
origin:{en:"Wallonia, Belgium",fr:"Wallonie, Belgique"},season:[],
flavor:["sweet","sour","fruity","rich"],
story:{en:"Pears and apples boiled for hours until they reduce to a near-black paste, with no added sugar at all — the sweetness is entirely the fruit's. It has been made in the Pays de Herve since the seventeenth century and is eaten with cheese.",
fr:"Des poires et des pommes cuites des heures jusqu’à une pâte presque noire, sans aucun sucre ajouté — la douceur vient entièrement du fruit. On le fait au Pays de Herve depuis le XVIIe siècle et on le mange avec du fromage."},
tip:{en:"Belgians put it with strong cheese and with rabbit. Treating it as a jam misses most of what it can do.",
fr:"Les Belges le servent avec un fromage fort et avec le lapin. Le prendre pour une confiture passe à côté de l’essentiel."},
pairs:["rabbit","blue-cheese","pear","apple","flour-t65","beurre-demi-sel","onion","mustard"],
svg:'<path class="f1 sf" d="M38 74V42h20v32z"/><path class="s" d="M38 50h20"/><path class="f2 sf" d="M44 60q4-8 8 0z"/>'},

{id:"maple-syrup",cat:"sweet",name:{en:"Maple syrup",fr:"Sirop d’érable"},latin:"Acer saccharum",
origin:{en:"Northeastern North America",fr:"Nord-Est de l’Amérique du Nord"},season:[3,4],
flavor:["sweet","woody","toasty","warm"],
story:{en:"Indigenous peoples of the northeastern forests taught settlers to read the “sugar moon” — the late-winter thaw when maples let their sap rise. It takes forty litres of sap, boiled down over days, to make a single litre of syrup: patience you can pour.",
fr:"Les peuples autochtones des forêts du Nord-Est apprirent aux colons à lire la « lune du sucre » — le redoux de fin d’hiver où l’érable laisse monter sa sève. Il faut quarante litres de sève, réduits des jours durant, pour un seul litre de sirop : de la patience qui se verse."},
tip:{en:"Darker grades carry more maple character — save “golden” for pancakes and cook with “dark”. It loves pork fat and coffee equally.",
fr:"Les grades foncés ont plus de caractère — gardez le « doré » pour les crêpes et cuisinez avec l’« ambré foncé ». Il aime autant le gras du porc que le café."},
pairs:["pork","walnut","apple","oats","butter","coffee"],
svg:'<path class="f2 sf" d="M48 26l4 8 8-2-2 8 8 4-8 6 2 8-8-2-4 8-4-8-8 2 2-8-8-6 8-4-2-8 8 2z"/><path class="s" d="M48 66v10"/>'},

{id:"matcha",cat:"sweet",name:{en:"Matcha",fr:"Matcha"},latin:"Camellia sinensis",
origin:{en:"Uji, Japan",fr:"Uji, Japon"},season:[],
flavor:["bitter","grassy","umami","earthy"],
story:{en:"The bushes are shaded for three weeks before harvest, which forces them to make more chlorophyll and more theanine — that is where the colour and the savoury depth come from. The leaves are then stone-ground, a kilo taking about an hour.",
fr:"Les théiers sont ombrés trois semaines avant la récolte, ce qui les force à produire plus de chlorophylle et plus de théanine — d’où la couleur et la profondeur umami. Les feuilles sont ensuite broyées à la meule de pierre, un kilo demandant environ une heure."},
tip:{en:"Never use boiling water — 70 to 80°C at most. Boiling water makes it aggressively bitter within seconds.",
fr:"N’utilisez jamais d’eau bouillante — 70 à 80 °C au plus. L’eau bouillante le rend agressivement amer en quelques secondes."},
pairs:["white-chocolate","cream","adzuki","sugar","sesame","vanilla","lemon","rice"],
svg:'<path class="f2 sf" d="M32 60q0-14 16-14t16 14q-14 10-32 0z"/><path class="s" d="M36 54q12 6 24 0"/><path class="s" d="M48 46v-8"/>'},

{id:"milk-chocolate",cat:"sweet",name:{en:"Milk chocolate",fr:"Chocolat au lait"},latin:"Theobroma cacao",
origin:{en:"Vevey, Switzerland, 1875",fr:"Vevey, Suisse, 1875"},season:[],
flavor:["sweet","creamy","milky","rich"],
story:{en:"Daniel Peter spent eight years failing to combine milk and chocolate — the water in milk seizes cocoa butter. His neighbour Henri Nestlé had just invented condensed milk, and the two of them solved it in 1875 by removing the water first.",
fr:"Daniel Peter passa huit ans à échouer à marier lait et chocolat — l’eau du lait fait figer le beurre de cacao. Son voisin Henri Nestlé venait d’inventer le lait condensé, et à eux deux ils résolurent le problème en 1875 en ôtant l’eau d’abord."},
tip:{en:"It burns and seizes far more easily than dark. Melt it over water that is barely steaming, never simmering.",
fr:"Il brûle et fige bien plus facilement que le noir. Faites-le fondre sur une eau à peine frémissante, jamais bouillante."},
pairs:["hazelnut","maple-syrup","banana","almond","coffee","cream","salt","orange"],
svg:'<path class="f2 sf" d="M28 44h40v24H28z"/><path class="s" d="M28 56h40M42 44v24M56 44v24"/>'},

{id:"molasses",cat:"sweet",name:{en:"Molasses",fr:"Mélasse"},latin:"Melassum",
origin:{en:"Caribbean",fr:"Caraïbes"},season:[],
flavor:["bitter","rich","smoky","earthy"],
story:{en:"What is left after sugar crystals are spun out, and it was the raw material of rum and of the triangular trade. In 1919 a storage tank burst in Boston and sent a wave of it through the streets, killing twenty-one people.",
fr:"Ce qui reste après extraction des cristaux de sucre, et la matière première du rhum et du commerce triangulaire. En 1919 une cuve éclata à Boston et déversa une vague dans les rues, tuant vingt et une personnes."},
tip:{en:"Blackstrap is the third boiling and is genuinely bitter. For baking you almost always want the lighter grade.",
fr:"La blackstrap est issue de la troisième cuite et elle est franchement amère. En pâtisserie on veut presque toujours la qualité plus claire."},
pairs:["ginger","dark-chocolate","rye-flour","clove","cinnamon","butter","coffee","orange"],
svg:'<path class="f1 sf" d="M38 74V40h20v34z"/><path class="s" d="M38 48h20"/><path class="s" d="M44 58q4 6 8 0"/>'},

{id:"muscovado",cat:"sweet",name:{en:"Muscovado",fr:"Muscovado"},latin:"Saccharum officinarum",
origin:{en:"Mauritius & the Philippines",fr:"Maurice & Philippines"},season:[],
flavor:["rich","earthy","smoky","sweet"],
story:{en:"Sugar with none of its molasses removed — the darkest, stickiest, least processed form there is, and it tastes of liquorice and smoke rather than simple sweetness. The name comes from Portuguese mascavado, unrefined.",
fr:"Un sucre dont on n’a retiré aucune mélasse — la forme la plus sombre, la plus collante et la moins transformée, au goût de réglisse et de fumée plutôt que de simple sucre. Le nom vient du portugais mascavado, non raffiné."},
tip:{en:"It clumps into rock. Keep a piece of bread or a terracotta disc in the jar and it stays workable.",
fr:"Il durcit en bloc. Gardez un morceau de pain ou un disque de terre cuite dans le pot et il reste souple."},
pairs:["dark-chocolate","coffee","ginger","butter","cream","banana","cinnamon","pecan"],
svg:'<path class="f1 sf" d="M32 68V48h32v20z"/><path class="s" d="M32 58h32"/><circle class="dot" cx="42" cy="63" r="1.6"/><circle class="dot" cx="54" cy="53" r="1.6"/>'},

{id:"palm-sugar",cat:"sweet",name:{en:"Palm sugar",fr:"Sucre de palme"},latin:"Borassus flabellifer",
origin:{en:"Southeast Asia",fr:"Asie du Sud-Est"},season:[],
flavor:["sweet","toasty","earthy","floral"],
story:{en:"Tapped from the flower stalk of a palm, not from any fruit — a climber cuts the stem and hangs a pot beneath it every morning. The sap is boiled the same day, because it ferments within hours in tropical heat.",
fr:"Récolté sur la hampe florale d’un palmier, non sur un fruit — un grimpeur entaille la tige et suspend un pot chaque matin. La sève est bouillie le jour même, car elle fermente en quelques heures sous la chaleur tropicale."},
tip:{en:"It is far less sweet than white sugar and more savoury. Do not substitute it one for one in a Western recipe.",
fr:"Il sucre bien moins que le sucre blanc et tire vers le salé. Ne le substituez pas au poids dans une recette occidentale."},
pairs:["fish-sauce","lime","chili","ginger","coconut-milk","lemongrass","garlic","peanut"],
svg:'<path class="f2 sf" d="M34 66q0-16 14-16t14 16q-14 8-28 0z"/><path class="s" d="M34 60q14 6 28 0"/>'},

{id:"rapadura",cat:"sweet",name:{en:"Rapadura",fr:"Rapadura"},latin:"Saccharum officinarum",
origin:{en:"Brazil & Latin America",fr:"Brésil & Amérique latine"},season:[],
flavor:["earthy","rich","sweet","smoky"],
story:{en:"Whole cane juice boiled down and left to set in a block, then scraped — rapar means to scrape. It is called panela in Colombia, piloncillo in Mexico, jaggery in India: the same product with five names and no refining at any point.",
fr:"Du pur jus de canne réduit et laissé prendre en bloc, puis râpé — rapar signifie racler. On l’appelle panela en Colombie, piloncillo au Mexique, jaggery en Inde : le même produit sous cinq noms, sans aucun raffinage."},
tip:{en:"It does not dissolve like white sugar. Melt it in a little hot liquid first, or you get gritty pockets.",
fr:"Elle ne se dissout pas comme le sucre blanc. Faites-la fondre d’abord dans un peu de liquide chaud, sinon vous aurez des grumeaux."},
pairs:["lime","coffee","cinnamon","dark-chocolate","banana","ginger","coconut-flakes","clove"],
svg:'<path class="f1 sf" d="M32 44l32 8-4 20-32-8z"/><path class="s" d="M34 56l30 8"/>'},

{id:"vergeoise",cat:"sweet",name:{en:"Vergeoise",fr:"Vergeoise"},latin:"Saccharum — sucre de betterave",
origin:{en:"Northern France & Belgium",fr:"Nord de la France & Belgique"},season:[],
flavor:["sweet","toasty","rich","warm"],
story:{en:"A beet sugar, not a cane one — which is what separates it from cassonade and why the north of France insists on it. Speculoos, tarte au sucre and gaufres de Lille are all built on vergeoise brune and taste wrong without it.",
fr:"Un sucre de betterave, non de canne — ce qui la distingue de la cassonade et pourquoi le Nord y tient. Spéculoos, tarte au sucre et gaufres de Lille reposent tous sur la vergeoise brune et sonnent faux sans elle."},
tip:{en:"Blonde and brune are not interchangeable. Brune is caramelised twice and carries most of the flavour.",
fr:"Blonde et brune ne sont pas interchangeables. La brune est caramélisée deux fois et porte l’essentiel du goût."},
pairs:["butter","cinnamon","flour-t55","cream","egg","apple","clove","dark-chocolate"],
svg:'<path class="f2 sf" d="M34 68V50h28v18z"/><path class="s" d="M34 60h28"/><circle class="dot" cx="44" cy="55" r="1.4"/><circle class="dot" cx="54" cy="64" r="1.4"/>'},

{id:"white-chocolate",cat:"sweet",name:{en:"White chocolate",fr:"Chocolat blanc"},latin:"Theobroma cacao — beurre de cacao",
origin:{en:"Switzerland, 1930s",fr:"Suisse, années 1930"},season:[],
flavor:["sweet","creamy","milky","buttery"],
story:{en:"Cocoa butter, sugar and milk with no cocoa solids at all — which is why purists argue it is not chocolate. It was invented to use up surplus cocoa butter left over from making cocoa powder, and it is a by-product that became a product.",
fr:"Du beurre de cacao, du sucre et du lait sans aucune matière sèche de cacao — d’où l’argument des puristes qu’il n’est pas du chocolat. Il fut inventé pour écouler le beurre de cacao excédentaire de la fabrication du cacao en poudre : un sous-produit devenu produit."},
tip:{en:"Check the label says cocoa butter and not vegetable fat. That single line separates the real thing from confectionery.",
fr:"Vérifiez que l’étiquette dit beurre de cacao et non matière grasse végétale. Cette seule ligne sépare le vrai du produit de confiserie."},
pairs:["raspberry","passion-fruit","pistachio","lime","cardamom","matcha","vanilla","timut-pepper"],
svg:'<path class="f3 sf" d="M28 44h40v24H28z"/><path class="s" d="M28 56h40M42 44v24M56 44v24"/>'},

{id:"sugar",cat:"sweet",name:{en:"White sugar",fr:"Sucre blanc"},latin:"Saccharum officinarum",
origin:{en:"New Guinea, via India",fr:"Nouvelle-Guinée, via l’Inde"},season:[],
flavor:["sweet","mild","delicate","toasty"],
story:{en:"Cane was chewed in New Guinea nine thousand years ago; India learned to crystallise the juice, and the Sanskrit sharkara became sucre, sugar, azúcar. For four centuries it was the engine of the Atlantic slave trade, which is the part the word does not carry.",
fr:"On mâchait la canne en Nouvelle-Guinée il y a neuf mille ans ; l’Inde apprit à en cristalliser le jus, et le sanskrit sharkara devint sucre, sugar, azúcar. Pendant quatre siècles il fut le moteur de la traite atlantique, ce que le mot ne porte pas."},
tip:{en:"It does far more than sweeten — it holds moisture, browns, and stops gluten forming. Cutting it in a cake changes the texture, not just the taste.",
fr:"Il fait bien plus que sucrer — il retient l’humidité, colore et freine la formation du gluten. En réduire dans un gâteau change la texture, pas seulement le goût."},
pairs:["butter","egg","vanilla","flour-t45","lemon","cream","dark-chocolate","cinnamon"],
svg:'<path class="f3 sf" d="M34 70V50h28v20z"/><path class="s" d="M34 58h28M44 50v20M54 50v20"/>'}
]);
