// Curated three-ingredient combinations. ids must exist in INGREDIENTS.
window.TRIOS = [
{ids:["tomato","basil","mozzarella"],name:{en:"The Caprese spirit",fr:"L’esprit caprese"},
 note:{en:"Italy’s flag on a plate — sweet, milky, perfumed.",fr:"Le drapeau italien dans l’assiette — sucré, lacté, parfumé."}},
{ids:["lemon","garlic","parsley"],name:{en:"Gremolata",fr:"Gremolata"},
 note:{en:"Chopped together, they wake up any braise, fish or vegetable.",fr:"Ciselés ensemble, ils réveillent braisés, poissons et légumes."}},
{ids:["onion","carrot","celery"],name:{en:"Mirepoix",fr:"Mirepoix"},
 note:{en:"The quiet foundation under half of French cooking.",fr:"La fondation silencieuse de la moitié de la cuisine française."}},
{ids:["garlic","chili","olive-oil"],name:{en:"Aglio, olio e peperoncino",fr:"Aglio, olio e peperoncino"},
 note:{en:"Three pantry items, one midnight feast.",fr:"Trois produits de placard, un festin de minuit."}},
{ids:["beetroot","goat-cheese","walnut"],name:{en:"The bistro salad",fr:"La salade bistrot"},
 note:{en:"Earth, cream and crunch in perfect proportion.",fr:"Terre, crème et croquant en proportions parfaites."}},
{ids:["honey","blue-cheese","walnut"],name:{en:"Sweet meets sharp",fr:"Le doux rencontre le puissant"},
 note:{en:"The cheese-board equation that never fails.",fr:"L’équation du plateau de fromages qui ne rate jamais."}},
{ids:["salmon","dill","lemon"],name:{en:"The Nordic classic",fr:"Le classique nordique"},
 note:{en:"Scandinavia’s gift to fish cookery.",fr:"Le cadeau de la Scandinavie à la cuisine du poisson."}},
{ids:["duck","orange","thyme"],name:{en:"À l’orange",fr:"À l’orange"},
 note:{en:"Rich meat, bright fruit, woodland herb — old-school elegance.",fr:"Viande riche, fruit vif, herbe des bois — l’élégance à l’ancienne."}},
{ids:["lamb","rosemary","garlic"],name:{en:"The Sunday roast",fr:"Le rôti du dimanche"},
 note:{en:"Three ingredients that smell like a family gathering.",fr:"Trois ingrédients qui sentent le repas de famille."}},
{ids:["pork","apple","sage"],name:{en:"Orchard & farmyard",fr:"Verger & basse-cour"},
 note:{en:"Autumn on a plate, balanced by centuries of habit.",fr:"L’automne dans l’assiette, équilibré par des siècles d’habitude."}},
{ids:["strawberry","balsamic","black-pepper"],name:{en:"The Modena surprise",fr:"La surprise de Modène"},
 note:{en:"Sounds wrong, tastes inevitable.",fr:"Ça semble étrange, ça devient une évidence."}},
{ids:["cilantro","coconut-milk","ginger"],name:{en:"The Southeast Asian base",fr:"La base d’Asie du Sud-Est"},
 note:{en:"The velvet trio under countless curries and soups.",fr:"Le trio de velours sous d’innombrables currys et soupes."}},
{ids:["chickpeas","sesame","lemon"],name:{en:"The hummus spirit",fr:"L’esprit houmous"},
 note:{en:"The Levant’s proof that three humble things beat one fancy one.",fr:"La preuve levantine que trois choses humbles battent une seule sophistiquée."}},
{ids:["egg","asparagus","parmesan"],name:{en:"Spring on toast",fr:"Le printemps sur le plat"},
 note:{en:"Soft yolk as sauce, spears as spoon, cheese as salt.",fr:"Le jaune coulant en sauce, les pointes en cuillère, le fromage en sel."}},
{ids:["eggplant","miso","sesame"],name:{en:"Nasu dengaku",fr:"Nasu dengaku"},
 note:{en:"Japan’s velvet-and-lacquer treatment of the humble aubergine.",fr:"Le traitement velours et laque du Japon pour l’humble aubergine."}},
{ids:["potato","leek","cream"],name:{en:"The vichyssoise spirit",fr:"L’esprit vichyssoise"},
 note:{en:"Comfort in three ingredients, hot or cold.",fr:"Le réconfort en trois ingrédients, chaud ou froid."}},
{ids:["apple","cinnamon","butter"],name:{en:"The heart of the tart",fr:"Le cœur de la tarte"},
 note:{en:"The smell every kitchen wants to have.",fr:"L’odeur que toute cuisine voudrait avoir."}},
{ids:["dark-chocolate","orange","cardamom"],name:{en:"The perfumed dark",fr:"Le noir parfumé"},
 note:{en:"Bitter depth lifted by citrus and the queen of spices.",fr:"La profondeur amère relevée par l’agrume et la reine des épices."}}
];
