/* Copius service worker — generated by tools/build-sw.py. Do not edit by hand. */
const VERSION = 'v41';
const CACHE = 'copius-' + VERSION;
const ASSETS = [
  './',
  './index.html',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/apple-touch-icon.png',
  'manifest.json',
  'css/style.css?v=41',
  'js/app.js?v=41',
  'js/data-cellar.js?v=41',
  'js/data-chefs.js?v=41',
  'js/data-condiments.js?v=41',
  'js/data-cuts.js?v=41',
  'js/data-dairy.js?v=41',
  'js/data-fats.js?v=41',
  'js/data-fruits.js?v=41',
  'js/data-grains.js?v=41',
  'js/data-herbs.js?v=41',
  'js/data-infusions.js?v=41',
  'js/data-legumes.js?v=41',
  'js/data-meat.js?v=41',
  'js/data-mushrooms.js?v=41',
  'js/data-nuts.js?v=41',
  'js/data-roe.js?v=41',
  'js/data-seafood.js?v=41',
  'js/data-seaweed.js?v=41',
  'js/data-shellfish.js?v=41',
  'js/data-spices.js?v=41',
  'js/data-sweet.js?v=41',
  'js/data-texture.js?v=41',
  'js/data-trees.js?v=41',
  'js/data-vegetables.js?v=41',
  'js/i18n.js?v=41',
  'js/photos.js?v=41',
  'js/trios-gastronomy.js?v=41',
  'js/trios-premium.js?v=41',
  'js/trios.js?v=41',
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }).then(function () {
    return self.skipWaiting();
  }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) {
      return k.indexOf('copius-') === 0 && k !== CACHE;
    }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  // The page itself: network first, so a new deploy is picked up. Cache is the offline fallback.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (res) {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put('./index.html', copy); });
        return res;
      }).catch(function () {
        return caches.match('./index.html');
      })
    );
    return;
  }

  // Everything else is versioned by ?v=, so cache-first is safe and instant.
  e.respondWith(
    caches.match(req).then(function (hit) {
      return hit || fetch(req).then(function (res) {
        if (res && res.status === 200) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      });
    })
  );
});
