#!/usr/bin/env python3
"""Generate js/tier.js from tools/free-tier.json.

The 499 ids have one home — the JSON, which carries its own provenance. This
writes the browser copy so the two cannot drift; run it whenever the list moves.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = json.loads((ROOT / "tools" / "free-tier.json").read_text(encoding="utf-8"))
ids = sorted(src["ids"])

out = '''/* Generated by tools/build-tier.py from tools/free-tier.json — do not edit.

   The free tier: %d ingredients a cook is expected to know, and no pairings.
   Everything else — the other entries, the pairing lab, the trios and the
   %s recorded pairings — is the paid product.

   MODE is "full" until there is something to buy. Flipping it to "free" is the
   whole switch: rebuildIndex() filters on it and the paid sections hide. */
window.COPIUS_TIER = {
  MODE: "full",
  FREE_IDS: [%s]
};
''' % (len(ids), "12 804", ",".join('"%s"' % i for i in ids))

(ROOT / "js" / "tier.js").write_text(out, encoding="utf-8")
print("js/tier.js — %d free ids, MODE=full" % len(ids))
