// The public data and the unpublished full bundle, from the source data.
//
//   osascript -l JavaScript tools/build-free.js          (from the project root; bump.sh runs it)
//
// js/free.js — the only ingredient data the public atlas loads: the ids in
//   tools/free-tier.json, each record as in the source minus pairs and parent (the
//   pairings, and the variety links that exist only for them), then COPIUS_LOCKED,
//   the teaser: the paid entries' names and families, and the counts the locked
//   panels quote. Nothing else of the full version goes in it.
// js/_premium.js — every source file but the techniques (public on their own), in
//   tools/sources.txt order, behind a reset of INGREDIENTS. Never published: it is
//   in .gitignore, and the leading underscore keeps Jekyll off it as well. Locally,
//   atlas.html?full loads it; step 2 has the server hand the same bundle to
//   subscribers.
ObjC.import("Foundation");
var root = ObjC.unwrap($.NSFileManager.defaultManager.currentDirectoryPath);
function read(f) {
  var s = $.NSString.stringWithContentsOfFileEncodingError(root + "/" + f, $.NSUTF8StringEncoding, null);
  if (!s || s.isNil()) throw new Error("cannot read " + f);
  return ObjC.unwrap(s);
}
function write(f, text) {
  var ok = $(text).writeToFileAtomicallyEncodingError(root + "/" + f, true, $.NSUTF8StringEncoding, null);
  if (!ok) throw new Error("cannot write " + f);
}

var SOURCES = read("tools/sources.txt").split("\n").map(function (l) { return l.trim(); })
  .filter(function (l) { return l && l.charAt(0) !== "#"; });
var g = globalThis; g.window = { console: console };
SOURCES.forEach(function (f) { eval(read(f)); });
var ALL = g.window.INGREDIENTS, CHEFS = g.window.CHEFS || [], BASES = g.window.BASES || [],
    TREES = g.window.TREES || [], TRIOS = g.window.TRIOS || [];

var FREE_IDS = JSON.parse(read("tools/free-tier.json")).ids;
var byId = {};
ALL.forEach(function (i) { byId[i.id] = i; });
var missing = FREE_IDS.filter(function (id) { return !byId[id]; });
if (missing.length) throw new Error("free ids missing from the source data: " + missing.join(", "));
var FREE = {};
FREE_IDS.forEach(function (id) { FREE[id] = 1; });

// The symmetric pairing graph the full atlas builds (app.js rebuildIndex).
var PAIRS = {}, edges = {};
ALL.forEach(function (i) { PAIRS[i.id] = {}; });
ALL.forEach(function (i) {
  (i.pairs || []).forEach(function (p) {
    if (!byId[p]) return;
    PAIRS[i.id][p] = 1; PAIRS[p][i.id] = 1;
    edges[i.id < p ? i.id + "|" + p : p + "|" + i.id] = 1;
  });
});

// Same species, as app.js keys it (kinKey there; keep the two in step).
function kinKey(lat) {
  if (!lat) return null;
  var m = lat.replace(/×(?=\S)/g, "× ").match(/^([A-Z][a-z]+) (?:× )?([a-z]+(?:-[a-z]+)?)(?=$|[\s(,])/);
  if (!m || /^(spp|var|subsp|cv|de|des|du|di|del|della)$/.test(m[2]) || /^(Natrii|Acetum|Calcium)$/.test(m[1])) return null;
  return (m[1] + " " + m[2]).toLowerCase();
}
var KIN = {};
ALL.forEach(function (i) { var k = kinKey(i.latin); if (k) (KIN[k] = KIN[k] || []).push(i.id); });

// What a free record may carry, by name: a field added to the sources later stays
// out of the public file until it is added here (tools/validate.js holds the same list).
var FREE_KEYS = ["id", "cat", "price", "pk", "name", "latin", "origin", "season", "flavor",
                 "texture", "story", "tip", "svg", "sign", "luxe", "rare", "kin"];
var free = [], items = [], pairs = {}, kin = {}, trees = {}, familyPaid = {}, basesUsing = {};
ALL.forEach(function (i) {
  if (!FREE[i.id]) {
    items.push([i.id, i.name.en, i.name.fr, i.cat]);
    familyPaid[i.cat] = (familyPaid[i.cat] || 0) + 1;
    return;
  }
  var r = {};
  FREE_KEYS.forEach(function (k) { if (Object.prototype.hasOwnProperty.call(i, k)) r[k] = i[k]; });
  free.push(r);
  pairs[i.id] = Object.keys(PAIRS[i.id]).length;
  var k = kinKey(i.latin);
  var paidKin = k ? KIN[k].filter(function (x) { return x !== i.id && !FREE[x]; }).length : 0;
  if (paidKin) kin[i.id] = paidKin;
});
items.sort(function (a, b) { return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0; });
TREES.forEach(function (t) { if (FREE[t.id]) trees[t.id] = (t.branches || []).length; });
BASES.forEach(function (b) {
  (b.techniques || []).forEach(function (t) { basesUsing[t] = (basesUsing[t] || 0) + 1; });
});

var LOCKED = {
  counts: {
    ingredients: ALL.length, free: free.length, paid: items.length,
    pairings: Object.keys(edges).length, chefs: CHEFS.length,
    dishes: CHEFS.reduce(function (n, c) { return n + (c.dishes || []).length; }, 0),
    bases: BASES.length, trios: TRIOS.length, trees: TREES.length
  },
  familyPaid: familyPaid, pairs: pairs, kin: kin, trees: trees, basesUsing: basesUsing,
  items: items
};

var out = "/* Generated by tools/build-free.js from the source data and tools/free-tier.json — do not edit.\n" +
  "   The free version: " + free.length + " ingredients without pairings, then COPIUS_LOCKED, the teaser\n" +
  "   for the full version (names, families and counts only). */\n" +
  "window.INGREDIENTS = [\n" + free.map(function (r) { return JSON.stringify(r); }).join(",\n") + "\n];\n" +
  "window.COPIUS_LOCKED = " + JSON.stringify(LOCKED) + ";\n";
write("js/free.js", out);

var bundle = "/* The full version, generated by tools/build-free.js — never published (see .gitignore). */\n" +
  "window.INGREDIENTS = [];\n" +
  SOURCES.filter(function (f) { return f !== "js/data-techniques.js"; })
    .map(function (f) { return "/* " + f + " */\n" + read(f); }).join("\n") +
  "\nwindow.COPIUS_PREMIUM = true;\n";
write("js/_premium.js", bundle);

console.log("js/free.js: " + free.length + " free entries, " + items.length + " locked names, " +
  Math.round(out.length / 1024) + " KB; js/_premium.js: " + Math.round(bundle.length / 1024) + " KB");
