#!/usr/bin/env python3
"""Regenerate service-worker.js from index.html so its cache list can never drift.
Run after changing assets:  python3 tools/build-sw.py"""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
html = (root / "index.html").read_text()

m = re.search(r'\?v=(\d+)', html)
if not m: sys.exit("no ?v=N found in index.html")
version = m.group(1)

assets = re.findall(r'(?:src|href)="((?:js|css)/[^"]+)"', html)
assets = sorted(set(assets))
extra = ["./", "./index.html", "icons/icon-192.png", "icons/icon-512.png",
         "icons/apple-touch-icon.png", "manifest.json"]
urls = extra + assets

sw = '''/* Copius service worker — generated by tools/build-sw.py. Do not edit by hand. */
const VERSION = 'v%s';
const CACHE = 'copius-' + VERSION;
const ASSETS = [
%s
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }).then(function () {
    return self.skipWaiting();
  }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) {
      return k.indexOf('copius-') === 0 && k !== CACHE;
    }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  // The page itself: network first, so a new deploy is picked up. Cache is the offline fallback.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (res) {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put('./index.html', copy); });
        return res;
      }).catch(function () {
        return caches.match('./index.html');
      })
    );
    return;
  }

  // Everything else is versioned by ?v=, so cache-first is safe and instant.
  e.respondWith(
    caches.match(req).then(function (hit) {
      return hit || fetch(req).then(function (res) {
        if (res && res.status === 200) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      });
    })
  );
});
''' % (version, "\n".join("  '%s'," % u for u in urls))

(root / "service-worker.js").write_text(sw)
print("service-worker.js written — VERSION v%s, %d assets cached" % (version, len(urls)))
