#!/usr/bin/env python3
"""Regenerate service-worker.js from atlas.html so its cache list can never drift.
Run after changing assets:  python3 tools/build-sw.py"""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
# The app moved off the root: / is the holding page, the atlas is a link away.
APP = "atlas.html"
html = (root / APP).read_text()

m = re.search(r'\?v=(\d+)', html)
if not m: sys.exit("no ?v=N found in " + APP)
version = m.group(1)

assets = re.findall(r'(?:src|href)="((?:js|css)/[^"]+)"', html)
assets = sorted(set(assets))
extra = ["./", "./" + APP, "icons/icon-192.png", "icons/icon-512.png",
         "icons/apple-touch-icon.png", "manifest.json"]
urls = extra + assets

sw = '''/* Copius service worker — generated by tools/build-sw.py. Do not edit by hand. */
const VERSION = 'v%s';
const CACHE = 'copius-' + VERSION;
const APP_URL = './%s';
const NAV_LIMIT = 150;   // runtime entries kept beyond ASSETS, oldest evicted
const ASSETS = [
%s
];
// As cache keys report them: absolute, resolved the way addAll resolved them.
const ASSET_URLS = ASSETS.map(function (u) { return new URL(u, self.location.href).href; });

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }).then(function () {
    return self.skipWaiting();
  }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) {
      return k.indexOf('copius-') === 0 && k !== CACHE;
    }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  // The page itself: network first, so a new deploy is picked up. Cache is the offline fallback.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (res) {
        // Only a good page is kept: a stored 404 would come back offline as
        // that URL. Keyed on the page's own URL. It used to put every
        // navigation under './index.html', so opening any second page
        // overwrote the app's offline copy with that page.
        if (res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) {
            return c.put(req, copy).then(function () { return c.keys(); }).then(function (keys) {
              // Bounded: thousands of generated pages would otherwise pile up
              // under one cache name. keys() is in insertion order, so the
              // front is the oldest. The precached assets are left alone.
              var pages = keys.filter(function (k) { return ASSET_URLS.indexOf(k.url) < 0; });
              return Promise.all(pages.slice(0, Math.max(0, pages.length - NAV_LIMIT))
                .map(function (k) { return c.delete(k); }));
            });
          });
        }
        return res;
      }).catch(function () {
        return caches.match(req).then(function (hit) { return hit || caches.match(APP_URL); });
      })
    );
    return;
  }

  // Everything else is versioned by ?v=, so cache-first is safe and instant.
  e.respondWith(
    caches.match(req).then(function (hit) {
      return hit || fetch(req).then(function (res) {
        if (res && res.status === 200) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      });
    })
  );
});
''' % (version, APP, "\n".join("  '%s'," % u for u in urls))

(root / "service-worker.js").write_text(sw)
print("service-worker.js written — VERSION v%s, %d assets cached" % (version, len(urls)))
