#!/usr/bin/env python3
"""Build a fact reel: one drawing, one hook line, one explaining line.

The copy is authored — a hook and a line, in both languages — and everything
else is pulled from the atlas: the name, the drawing in img/<id>.svg, the logo.
Written to tools/, which _config.yml keeps off the published site.

    python3 tools/mkfact.py rhubarb \
      --hook-en "Rhubarb is legally a fruit." --hook-fr "La rhubarbe est légalement un fruit." \
      --line-en "…" --line-fr "…"
"""
import argparse, base64, glob, io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ap = argparse.ArgumentParser()
ap.add_argument("id")
for k in ("hook-en", "hook-fr", "line-en", "line-fr"): ap.add_argument("--" + k, required=True)
ap.add_argument("--out", default=os.path.join(ROOT, "tools", "reel-fact.html"))
a = ap.parse_args()

# the entry, by id, from whichever data file holds it
name = None
for p in glob.glob(os.path.join(ROOT, "js", "data-*.js")):
    t = io.open(p, encoding="utf-8").read()
    i = t.find('{id:"%s"' % a.id)
    if i < 0: continue
    m = re.search(r'name:\{en:"([^"]*)",fr:"([^"]*)"\}', t[i:i + 2000])
    if m: name = {"en": m.group(1), "fr": m.group(2)}; break
if not name: sys.exit("no entry with id %r" % a.id)

svgp = os.path.join(ROOT, "img", a.id + ".svg")
if not os.path.exists(svgp): sys.exit("no drawing at " + svgp)
svg = io.open(svgp, encoding="utf-8").read()
# width/height attributes pin it at 104 px; the frame sizes it by CSS instead
svg = re.sub(r'\s(width|height)="[^"]*"', "", svg, count=2)
logo = base64.b64encode(io.open(os.path.join(ROOT, "brand", "copius-profile.png"), "rb").read()).decode()

copy = {
  "fr": {"name": name["fr"], "hook": a.hook_fr, "line": a.line_fr, "mark": "l’atlas des ingrédients", "end": "1 838 ingrédients.\nCompose ton assiette."},
  "en": {"name": name["en"], "hook": a.hook_en, "line": a.line_en, "mark": "the ingredient atlas",  "end": "1,838 ingredients.\nBuild your plate."},
}

html = r'''<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<title>Copius — fait du jour</title>
<!-- Generated by tools/mkfact.py. A reel that plays itself: open it, R arms, space starts,
     E switches language, F hides the controls. Record only the light frame. -->
<style>
  :root{--bg:#F7F6F1;--card:#FFFEFC;--border:#E5E7DA;--border-strong:#D1D5C3;--ink:#1E211A;--ink-2:#565A4C;--ink-3:#6A6E5F;
    --chip:#EDEFE3;--accent:#4F5B3F;--serif:Georgia,"Iowan Old Style","Times New Roman",serif;
    --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif}
  *{box-sizing:border-box}
  html,body{margin:0;height:100%;background:#15170F;font-family:var(--sans)}
  body{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;padding:14px}
  #stage{width:1080px;height:1920px;transform-origin:top center;flex:none}
  #wrap{display:flex;justify-content:center;overflow:hidden}
  .frame{width:1080px;height:1920px;background:var(--bg);color:var(--ink);padding:104px 84px;display:flex;flex-direction:column;position:relative}
  .mark{font-family:var(--serif);font-size:38px;color:var(--ink-2)}
  .mark b{color:var(--ink);font-weight:400}
  .art{margin:60px auto 0;width:600px;height:600px;display:flex;align-items:center;justify-content:center}
  .art svg{width:100%;height:100%}
  .name{margin-top:36px;text-align:center;font-size:34px;letter-spacing:.12em;text-transform:uppercase;color:var(--ink-3)}
  .hook{margin-top:22px;text-align:center;font-family:var(--serif);font-size:92px;line-height:1.1;color:var(--ink);text-wrap:balance}
  .line{margin:40px auto 0;max-width:860px;text-align:center;font-size:40px;line-height:1.45;color:var(--ink-2);
    opacity:0;transform:translateY(14px);transition:opacity .45s ease,transform .5s ease}
  .line.in{opacity:1;transform:none}
  .end{position:absolute;inset:0;background:#F1F1F0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:26px;padding:76px;text-align:center;
    opacity:0;pointer-events:none;transition:opacity .5s ease}
  .end.in{opacity:1}
  .end img{width:620px;height:auto;display:block;margin-bottom:-40px}
  .end p{margin:0;font-size:40px;color:var(--ink-2);line-height:1.4;white-space:pre-line}
  .end .url{margin-top:16px;font-size:52px;color:var(--accent);font-family:var(--serif)}
  .ctrl{display:flex;gap:10px;align-items:center;font-size:13px;color:#C9CBBE}
  .ctrl button{font:inherit;padding:8px 16px;border-radius:999px;border:1px solid #3A3D31;background:#22251B;color:#E8EADE;cursor:pointer}
  .ctrl button[aria-pressed="true"]{background:#E8EADE;color:#22251B;border-color:#E8EADE}
  .ctrl .t{font-variant-numeric:tabular-nums;min-width:52px;color:#8A8D7E}
  body.clean{padding:0;gap:0} body.clean .ctrl{display:none}
</style>
</head>
<body>
<div id="wrap"><div id="stage"><div class="frame">
  <div class="mark"><b>Copius</b> — <span id="markSub"></span></div>
  <div class="art">__SVG__</div>
  <p class="name" id="name"></p>
  <p class="hook" id="hook"></p>
  <p class="line" id="line"></p>
  <div class="end" id="end"><img alt="Copius" src="data:image/png;base64,__LOGO__"><p id="endSub"></p><div class="url">copius.fr</div></div>
</div></div></div>
<div class="ctrl">
  <button id="play">▶ Armer (R)</button><button id="fr" aria-pressed="true">FR</button><button id="en" aria-pressed="false">EN</button>
  <button id="clean">F — mode propre</button><span class="t" id="clock">0.0s</span>
  <span>R arme · lance l’enregistrement · Espace démarre</span>
</div>
<script>
(function(){"use strict";
  var COPY=__COPY__;
  var $=function(id){return document.getElementById(id);};
  var lang="fr",timers=[],t0=0,clockRaf=0,armed=false;
  function fit(){var c=document.body.classList.contains("clean");
    var s=Math.min((window.innerWidth-(c?0:28))/1080,(window.innerHeight-(c?0:90))/1920);
    $("stage").style.transform="scale("+s+")";$("wrap").style.width=Math.ceil(1080*s)+"px";$("wrap").style.height=Math.ceil(1920*s)+"px";}
  window.addEventListener("resize",fit);
  function at(ms,fn){timers.push(setTimeout(fn,ms));}
  function stop(){timers.forEach(clearTimeout);timers=[];cancelAnimationFrame(clockRaf);}
  function clearStage(){$("line").classList.remove("in");$("end").classList.remove("in");}
  function fill(){var C=COPY[lang];$("markSub").textContent=C.mark;$("name").textContent=C.name;$("hook").textContent=C.hook;$("line").textContent=C.line;$("endSub").textContent=C.end;}
  /* R arms: the drawing, the name and the hook are on screen at t=0 — that IS the first frame
     and the cover. Space starts the run. The recording can roll as long as it likes before that. */
  function arm(){stop();clearStage();fill();armed=true;$("clock").textContent="armed";$("play").textContent="▶ Espace — lancer";}
  function play(){stop();clearStage();fill();armed=false;$("play").textContent="▶ Armer (R)";t0=performance.now();
    at(2000,function(){$("line").classList.add("in");});
    at(5500,function(){$("end").classList.add("in");});
    at(8500,play);
    (function tick(now){$("clock").textContent=((now-t0)/1000).toFixed(1)+"s";clockRaf=requestAnimationFrame(tick);})(t0);}
  function setLang(l){lang=l;$("fr").setAttribute("aria-pressed",String(l==="fr"));$("en").setAttribute("aria-pressed",String(l==="en"));document.documentElement.lang=l;arm();}
  $("play").addEventListener("click",function(){armed?play():arm();});
  $("fr").addEventListener("click",function(){setLang("fr");});
  $("en").addEventListener("click",function(){setLang("en");});
  $("clean").addEventListener("click",function(){document.body.classList.add("clean");fit();});
  document.addEventListener("keydown",function(e){
    if(e.key==="r"||e.key==="R")arm();
    if(e.key===" "){e.preventDefault();play();}
    if(e.key==="e"||e.key==="E")setLang(lang==="fr"?"en":"fr");
    if(e.key==="f"||e.key==="F"){document.body.classList.toggle("clean");fit();}});
  fit();arm();
})();
</script>
</body>
</html>
'''
html = html.replace("__SVG__", svg).replace("__LOGO__", logo).replace("__COPY__", json.dumps(copy, ensure_ascii=False))
io.open(a.out, "w", encoding="utf-8").write(html)
print("wrote %s  (%d KB)  %s / %s" % (os.path.relpath(a.out, ROOT), len(html) // 1024, name["en"], name["fr"]))
