<?php
/* GET ?v=N: the full version for a signed-in person with access, built from
   the checkout's own sources; a stub script naming why not otherwise
   (DESIGN.md section 2, the bundle). */
declare(strict_types=1);
require __DIR__ . '/_lib.php';

/* Every stub is a 200 script so that it runs, and carries no validator: a 304
   on one would make the browser run the bundle it kept (decision 2). */
function stub(string $state, bool $clear): never {
    http_response_code(200);
    api_headers();
    header('Content-Type: text/javascript; charset=utf-8');
    if ($clear) clear_cookies();
    echo 'window.COPIUS_SESSION = "' . $state . '";';
    log_api($state);
    exit;
}

try {
    $s = current_session();
    if (!$s) stub('ended', true);
    $acc = access_for((string)$s['email']);
} catch (Throwable $e) {
    log_php('premium: ' . describe($e));
    stub('unavailable', false);                         // a database blip signs nobody out
}
if (!$acc['access']) stub('noaccess', false);

const BUNDLE_HEAD = "/* The full version, generated by tools/build-free.js and by api/premium.php from the same sources — served only to a signed-in person with access. */\n";

/* tools/sources.txt with build-free.js's parsing: js/ files only, the
   techniques left out (they are public on their own). */
function sources(): array {
    $out = [];
    foreach (file(SITE . '/tools/sources.txt') ?: [] as $l) {
        $l = trim($l);
        if ($l === '' || $l[0] === '#' || $l === 'js/data-techniques.js') continue;
        if (!preg_match('#^js/[a-z0-9-]+\.js$#', $l)) continue;
        $out[] = $l;
    }
    return $out;
}

/* A format number and each file's path, size and time: a Git deploy changes
   the times of the files it touches. */
function bundle_key(array $files): string {
    clearstatcache();
    $sig = (string)BUNDLE_FORMAT;
    foreach ($files as $f) $sig .= "\n$f " . filesize(SITE . "/$f") . ' ' . filemtime(SITE . "/$f");
    return sha1($sig);
}

/* Written through a temporary file of its own, checked, then renamed: the .js
   first and the .gz last, so a key is served only once both are whole. */
function build(string $key, array $files): bool {
    $dir = PRIV . '/cache';
    if (!is_dir($dir)) @mkdir($dir, 0700);
    $parts = []; $want = 0;
    foreach ($files as $f) {
        $parts[] = "/* $f */\n" . file_get_contents(SITE . "/$f");
        $want += strlen("/* $f */\n") + filesize(SITE . "/$f");
    }
    $js = BUNDLE_HEAD . "window.INGREDIENTS = [];\n" . implode("\n", $parts) . "\nwindow.COPIUS_PREMIUM = true;\n";
    $want += strlen(BUNDLE_HEAD . "window.INGREDIENTS = [];\n") + count($parts) - 1 + strlen("\nwindow.COPIUS_PREMIUM = true;\n");
    if (strlen($js) !== $want) { log_php("bundle: $want bytes expected, " . strlen($js) . ' built'); return false; }
    $gz = gzencode($js, 9);
    if ($gz === false || gzdecode($gz) !== $js) { log_php('bundle: gzip check failed'); return false; }
    /* Each file is read back before its rename: a write error that shows only
       at close on a shared file server must not be served to everyone. */
    foreach (['.js' => $js, '.js.gz' => $gz] as $ext => $bytes) {
        $tmp = @tempnam($dir, 'tmp-');
        $ok = $tmp !== false && @file_put_contents($tmp, $bytes) === strlen($bytes);
        clearstatcache();
        $ok = $ok && @filesize($tmp) === strlen($bytes) && @file_get_contents($tmp) === $bytes;
        if (!$ok || !@rename($tmp, "$dir/premium-$key$ext")) {
            if ($tmp) @unlink($tmp);
            log_php("bundle: $ext not written");
            return false;
        }
    }
    return true;
}

/* Only keys whose files are more than an hour old go, and never the previous
   one: during a deploy, web servers can disagree on the key for a while. */
function collect(string $key): void {
    /* Another web server may rename or delete a file between the glob and the
       time read: such a file is simply skipped. */
    $by = [];
    foreach (glob(PRIV . '/cache/premium-*.js') ?: [] as $f) {
        $t = @filemtime($f);
        if ($t !== false && preg_match('/premium-([0-9a-f]{40})\.js$/', $f, $m) && $m[1] !== $key) $by[$m[1]] = $t;
    }
    arsort($by);
    array_shift($by);                                   // the previous key stays
    foreach ($by as $k => $t) {
        if ($t < now() - 3600) { @unlink(PRIV . "/cache/premium-$k.js.gz"); @unlink(PRIV . "/cache/premium-$k.js"); }
    }
    foreach (glob(PRIV . '/cache/tmp-*') ?: [] as $f) {
        $t = @filemtime($f);
        if ($t !== false && $t < now() - 3600) @unlink($f);
    }
}

$files = sources();
$key = bundle_key($files);
$etag = '"' . $key . '"';

/* A 304 only here, for a valid session with access, once W/, the quotes and
   mod_deflate's -gzip are stripped from what the browser sends. */
foreach (explode(',', (string)($_SERVER['HTTP_IF_NONE_MATCH'] ?? '')) as $v) {
    $v = preg_replace('/-gzip$/', '', trim(preg_replace('#^W/#', '', trim($v)), '"'));
    if ($v === $key) {
        http_response_code(304);
        api_headers('private, no-cache');
        header('ETag: ' . $etag);
        log_api('304');
        exit;
    }
}

$base = PRIV . "/cache/premium-$key";
$built = false;
if (!(is_file("$base.js") && is_file("$base.js.gz"))) {
    if (!build($key, $files)) stub('unavailable', false);
    $built = true;
}
$gzip = stripos((string)($_SERVER['HTTP_ACCEPT_ENCODING'] ?? ''), 'gzip') !== false;
$path = $gzip ? "$base.js.gz" : "$base.js";
http_response_code(200);
api_headers('private, no-cache');
header('Content-Type: text/javascript; charset=utf-8');
header('ETag: ' . $etag);
header('Vary: Accept-Encoding, Cookie');
if ($gzip) header('Content-Encoding: gzip');
header('Content-Length: ' . filesize($path));
readfile($path);
log_api($gzip ? 'bundle_gz' : 'bundle');
/* Clean-up comes after the answer and can never fail a bundle being served. */
if (function_exists('fastcgi_finish_request')) fastcgi_finish_request();
if ($built) { try { collect($key); } catch (Throwable $e) { log_php('collect: ' . describe($e)); } }
purge_soon();
